### ISSUE TITLE
Link Isaura to the AWS Registry of Open Data

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#10]
# Background
A few months ago, we created a small repository named [isaura](https://github.com/ersilia-os/isaura) to manage calculated data. Storing calculations is very relevant, especially for computationally intensive models that have not been optimized for production by original authors. Isaura works mainly on HDF5 files, and our idea is to store these files in the [AWS Registry of Open Data (ROD)](https://registry.opendata.aws/), eventually.

The current logic behind Isaura is that a `local` and a `public` file exist. The public file is typically large, and is downloaded (optionally) at fetching time. The local file contains only calculations performed by the user (i.e. those that were not available in the public file). Users have the option to contribute their calculations to the public file. We are currently tackling this issue with data version control [DVC](https://dvc.org/).

# Discussion
We would like to open a discussion with the goal of identifying the best design of Isaura, and the best way to link it to the AWS ROD. Two urging questions we have are:
- Is it safe to allow users to contribute their precalculations? What risks may exists?
- Is it possible to keep the public file in the ROD and directly fetch precalculations from there?

We suggest that we start the discussion here and then we open more specific issues to tackle each point.

**Comment by ashaby4000** [comment]
my opinion on this would be to allow users to contribute their precalculation but not directly. It has to be properly moderated and verified before it can be added to the public file. I'm suggesting this because user contribution will eventually enhance the models.  If its possible, a user public file can be created for users to contribute their precalculation. After the contribution has been verified, it can then be moved to the main public file

**Comment by Rufaida98** [comment]
@ashaby4000 your idea sounds good

**Comment by resiato** [comment]
@busiratazeez we share the same idea. Allowing users to contribute their precalculation goes a long way in enhancing the models. @miquelduranfrigola my concern which is a potential risk is that these calculations may not be accurate and hence the need for verification before being added to the public file

**Comment by miquelduranfrigola** [comment]
Hi @busiratazeez and @resiato, thanks for your excellent feedback. I did some thinking on all of this a while ago. You can see a scheme I draw back in the day: [s3-hdf5-scheme.pdf](https://github.com/ersilia-os/ersilia/files/8383027/s3-hdf5-scheme.pdf) (please don't worry if you don't understand it! Bottomline is... it's complicated :))

Our colleague @JHlozek has done a lot of thinking about it too. Our current solution involves DVC. Before we jump into coding: are you familiar with it?

To give space to everyone to contribute, I am assigning the issue to @resiato and @busiratazeez, but please @loweyvana and @Rufaida98 feel welcome to jump in!

**Comment by resiato** [comment]
> 

@miquelduranfrigola Honestly, I can't say I have encountered DVC before but I'm open to learning the innings of this of this system

**Comment by busiratazeez** [comment]
@miquelduranfrigola I'm a beginner in coding. So I checked out [DVC](https://dvc.org/) and I understand why it's the current solution. It will provide a pointer to the large files but it definitely not solving the issue of verifying what a user uploads. I'm willing to dive into brainstorming alongside the team and see what we can come up with.

**Comment by Rufaida98** [comment]
@miquelduranfrigola I'll be happy to learn new things and apply it.

**Comment by JHlozek** [comment]
Hi all. 

@busiratazeez I agree with your comments. DVC is just the back-end storage facilitator and here we need to add an extra layer of functionality where users can opt to contribute data that is verified. I think the idea of staging them first (as you suggest) is prudent.

Some points to think about for implementation of data contribution:
- Where and how is the contributed data staged? Is this also done through DVC with a pointer to the staging H5 file or is there a better approach?
- How do efficiently evaluate our confidence in contributed data? I doubt we need/want to recalculate every data point.
- What is our tolerance for data variability? If there is some variability in a calculation for the same input, how do we intelligently decide that two values agree or disagree? Do we require 100% agreement when we validate this data?

**Comment by EugeniaDedeTeye** [comment]
@busiratazeez  I like your points made. @miquelduranfrigola  The best situation would be to allow users to make their contributions to their local files, I believe the DVC would track any changes made to the calculations and would also allow users to go back on calculations done if any mistakes are made. This way users would be allowed to make changes to their precalculations after reviewing them before pushing them to the public files.
@miquelduranfrigola I would love to be part of contributing to this issue.

**Comment by miquelduranfrigola** [comment]
Thanks all for the feedback. All is well noted.

@JHlozek thanks for these excellent points.

Gathering your points, we are consulting now with AWS and we are awaiting their feedback. Will keep you updated. I anticipate this will be a "slow" thread.

**Comment by miquelduranfrigola** [comment]
Closing this issue for now. We might resolve to DynamoDb eventually.
