### ISSUE TITLE
Outreachy Documentation Project: <Busirat Azeez/busiratazeez>

### ISSUE THREAD

**Issue by busiratazeez** [ersilia-os/ersilia#100]
Applicant: <busiratazeez>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by GemmaTuron** [comment]
Hi @busiratazeez 

If you have done some work on the project, can you check the tasks and link the relevant documents here so we can provide feedback?

thanks!

**Comment by busiratazeez** [comment]
Hello @GemmaTuron 
Yes I have done some work on the project. Kindly give me a little time to link the documents. Thank you.

**Comment by busiratazeez** [comment]
**Contributions so far:**

1. #58 
2. #65

**Comment by busiratazeez** [comment]
**Why I am Intrested in Ersilia project**
As a Biomedical Engineering student, I got excited when I read through the Ersilia project description. The thought of providing a pre-trained Artificial Intelligence models in daily experimental tasks attracted me towards this project. 
While I was doing my thesis reasearch, I was limited to resources. This is the situation most student face during research work and Ersilia Hub is providing a strategic way to provide a platform whereby scientist and students can have access to more digital resources which will aid their investigation in drug solution diseases. 
I am very eager to making meaningful contributions towards this project.

**Comment by busiratazeez** [comment]
**Slide [Link](https://docs.google.com/presentation/d/1pQhlBWDxDw68CFfXGvYVazQQOeDjp4Z9NsjL8lu-uwM/edit?usp=sharing) explaining Ersilia’s mission and vision**

@GemmaTuron kindly review

**Comment by busiratazeez** [comment]
Hello @GemmaTuron 
kindly check this 1- page blogpost on [Strategic plan 2021 - 2023](https://busirat.com.ng/2022/04/13/ersilia-open-source-initiative/)

**Comment by GemmaTuron** [comment]
Hi @busiratazeez 

Thanks for your contributions. I am leaving here a few comments for you to address to prepare your final contribution:
- Readme: the installation section could be clearer. You explain how to install Ersilia in Ubuntu, and then for windows installation you just refer to installing WSL, not ersilia itself. PErhaps explaining somewhere that you need wsl before installing on windows would help users. And please check the license file
- Strategic goals: good job, nice formatting with the quote from the WHO. The only thing I would remove is expected grant makers, though this is in the main document, we do not know if we will get these big organisations to support our work, I would not add them in the summary
- Mission and vision: I like it, no major comments!

Please revise the following comments and prepare your final application linking this issue in the application

thanks!

**Comment by busiratazeez** [comment]
Hi @GemmaTuron 

Thanks for your feedbacks.

- Readme: I have updated the windows installation guide, the license file and also created a pull request #227 
- Strategic goals: I have removed the grant maker as suggested.

**Comment by GemmaTuron** [comment]
Thanks @busiratazeez 

Please now focus on the final application in the Outreachy website.

**Comment by busiratazeez** [comment]
> Thanks @busiratazeez ! Please check my comment on PR #227 and amend

Hi @GemmaTuron

Thanks for the correction
I'm new to every part of open source contribution but I've been able to amend as requested. Please kindly review my correctiion. #227
Thankyou

**Comment by busiratazeez** [comment]
#10 is definitely a slow thread as @miquelduranfrigola anticipated. 
Do we have any recent development from AWS ?
