### ISSUE TITLE
✍️ Contribution period: Monya Mehta

### ISSUE THREAD

**Issue by monya217** [ersilia-os/ersilia#1002]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by monya217** [comment]
**### Motivation for Interest in Ersilia**

I am Monya Mehta, a sophomore student pursuing Bachelor of Technology in Artificial Intelligence and Machine Learning from Indira Gandhi Delhi Technical University for Women.

As part of one of my first foray into ML, I worked on a project that focused on improving ultrasound segmentation results using ensemble learning, which created in me a fascination for the use of ML in the medical field. Thus the goals of the Ersilia Open Source Initiative align perfectly with my interests and will be a great opportunity to further my skills and gain experience. I am eager to learn from my mentors and hopefully contribute to the organization even beyond the internship.  

With my technical skills and eagerness to learn, I think I will be able to make a positive impact on the project. Looking forward to an amazing month of learning. Thank you!

**Comment by monya217** [comment]
Here is the link of the github repositart for task 2
https://github.com/monya217/Ersiliaeos30gr

**Comment by DhanshreeA** [comment]
@monya217 Looks good so far! Ping me here when you update the repository with Task 2 from Week 2, and then proceed to work on Task 3.

**Comment by monya217** [comment]
@DhanshreeA Hi! Thank you for the feedback and I'm currentlt working on task2 and I actually I had a query. I am trying to reproduce the model by loading the checkpoints but it;s showing me error due to version of scikit-learn. I have the latest version installed but I think the model was saved using some other version, which is causing the issue. The requirements.txt doesn't state the version so is there any way to figure out which version is required?

**Comment by monya217** [comment]
@DhanshreeA Hi I;ve also updated the repository with task2! However it only contains the ersilia results and not the model implementation since my earlier doubt has not been resolved.  Please review and share any suggestions for improvement. Thanks!

**Comment by DhanshreeA** [comment]
Hi @monya217 regarding your work so far, few comments: 
1. Regarding data, can you create a README within the data folder highlighting exactly which files are what?
2. You said you couldn't implement the model because of dependency issues however I see a scatter plot where you compare model probabilities vs Ersilia probabilities. What's happening?
3. How are getting an ROC-AUC curve of 1? That's impossible! 😁 Please compare your ROC-AUC score with that published in the paper by the authors. Only then will the model result be considered reproducible, if we are getting the same results as in the paper.

**Comment by monya217** [comment]
H, @DhanshreeA!  Thanks a lot for the feedback. Regarding the comments:
1. I have made a readme file in the data folder explaining each file.
2. The model probabilities that were mentioned were actually the predictions of the models that were made by the authors. Since the graph was a bit unclear I have made the changes to make it a bit more clear.
3. I don't really know what is up with AUC value 0f 1. Maybe it is due to some error in my implementation but I have been unable to find it. This value was something I got for the testing dataset but the authors actually haven't mentioned the AUC value for the testing dataset, only for the testing data and the validation data. So I'm currently working on the validation data to check whether it is reproducible or not. Once done I'll surely update.

**Comment by monya217** [comment]
> H, @DhanshreeA! Thanks a lot for the feedback. Regarding the comments:
> 
> 1. I have made a readme file in the data folder explaining each file.
> 2. The model probabilities that were mentioned were actually the predictions of the models that were made by the authors. Since the graph was a bit unclear I have made the changes to make it a bit more clear.
> 3. I don't really know what is up with AUC value 0f 1. Maybe it is due to some error in my implementation but I have been unable to find it. This value was something I got for the testing dataset but the authors actually haven't mentioned the AUC value for the testing dataset, only for the testing data and the validation data. So I'm currently working on the validation data to check whether it is reproducible or not. Once done I'll surely update.

@DhanshreeA So I tried to check whether the results on validation data  were reproducible or not but I am still getting AUC value of 1.  I am not sure what this could be an indication for. Would appreciate if you looked into my work and see perhaps there is some issue in the implementation.
Thanks for your time.

**Comment by DhanshreeA** [comment]
Hi @monya217 

Perhaps it 

> > H, @DhanshreeA! Thanks a lot for the feedback. Regarding the comments:
> > 
> > 1. I have made a readme file in the data folder explaining each file.
> > 2. The model probabilities that were mentioned were actually the predictions of the models that were made by the authors. Since the graph was a bit unclear I have made the changes to make it a bit more clear.
> > 3. I don't really know what is up with AUC value 0f 1. Maybe it is due to some error in my implementation but I have been unable to find it. This value was something I got for the testing dataset but the authors actually haven't mentioned the AUC value for the testing dataset, only for the testing data and the validation data. So I'm currently working on the validation data to check whether it is reproducible or not. Once done I'll surely update.
> 
> @DhanshreeA So I tried to check whether the results on validation data were reproducible or not but I am still getting AUC value of 1. I am not sure what this could be an indication for. Would appreciate if you looked into my work and see perhaps there is some issue in the implementation. Thanks for your time.

Hi @monya217 no worries, I'll look into it soon. On the surface, I'm unable to see what's going on either. In any case, I would advise starting work on your final application. This has been good work so far, so don't worry.

**Comment by monya217** [comment]
Thanks for your response and reassurance @DhanshreeA! I'll surely get started working on my final application.
