### ISSUE TITLE
✍️ Contribution period: Ayushi Dubey

### ISSUE THREAD

**Issue by dubeyayushi** [ersilia-os/ersilia#1004]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [x] Find a suitable dataset with sufficient experimental results
- [x] Clean and standardize the dataset
- [x] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by dubeyayushi** [comment]
# Motivation for Joining Outreachy and Interest in Ersilia Model Hub ✨

Hi <img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="15px"> , I'm Ayushi Dubey, currently a sophomore pursuing B.Tech in Artificial Intelligence and Machine Learning at Indira Gandhi Delhi Technical University for Women (IGDTUW), New Delhi, India. My academic journey reflects my deep passion for machine learning, web development, and competitive programming.

The opportunity to join Outreachy and contribute to Ersilia's Model Hub is particularly appealing to me. The project's emphasis on AI/ML models for drug discovery aligns seamlessly with my interests and offers an exciting platform for learning and collaboration.

The outlined tasks, ranging from literature reviews to model documentation, resonate with my detail-oriented approach and enthusiasm for contributing to impactful projects. I'm eager to dive into source code integrity checks and gain a deeper understanding of model architectures.

Beyond the internship period, my commitment to Ersilia extends. I am keen on contributing to the organization's goals even after the internship concludes. The collaborative nature of open source work at Ersilia perfectly aligns with my belief in the power of teamwork and shared passion among tech enthusiasts.

The internship promises not just a learning experience but a significant contribution to my professional growth. Exposure to ML methods, Git Projects, and Docker deployment, along with a professional development environment will undoubtedly elevate my skills in the field.

Excited about the journey ahead!

**Comment by dubeyayushi** [comment]
> _This comment is for documenting the progress made during the Outreachy contribution period for the Ersilia Model Hub project_

### 4 March, 2023 -

1. Received mail for being shortlisted for contributing during the contribution period ending on 2 April, 2024.
2. Searched and explored the organisations aligning with my skills and vision. 

### Week-1 

**_Tasks:_**
Task 1 : Join the communication channels 
Task 2 : Open a GitHub issue (this one!) 
Task 3 :  Install the Ersilia Model Hub and test the simplest model 
Task 4 :  Install Docker if needed, and test another model 
Task 5 : Write a motivation statement to work at Ersilia 
Task 6 : Submit your first contribution to the Outreachy site

**Day -1 (5 March, 2024)**

1. Researched about Ersilia, went through the GitHub repository and the GitBook. Read about the tasks and explored the Ersilia website to understand the work they do. 
2. Joined the slack community and starred the Ersilia repository. 

**Day-2 (6 March, 2024)**

1. Opened the GitHub issue following the instructions mentioned in the GitBook
2. Installed the Ersilia Model Hub on my system, and tested a simple model eos3b5e to make sure that the system is now compatible with running the Ersilia models.
3. Installed Docker, went through the basics of it using the learning path of Docker. Tested eos4wt0 model by fetching the image from DockerHub.

**Day-3 (7 March, 2024)**

1. Wrote the motivation statement about my interest in joining Ersilia as an intern. Commented the statement under the issue created.
2. Submitted my first contribution to Ersilia to the Outreachy site.

### Week-2

**_Tasks:_**
Task 1 : Select a model from the list suggested in GitBook 
Task 2 : Download and serve the model via the Ersilia Model Hub to ensure it works 
Task 3 :  Open a repository on your GitHub user with all the necessary files 
Task 4 : Select and clean a dataset of 1000 molecules (example notebook 1) 
Task 5 : Run predictions for the molecules on the selected model and evaluate the results 

**Day-1 (8 March, 2024)**

1. Attended the community call at 10am CET to get familiar with the upcoming tasks of week-2 and 3 and have an interaction with the mentors.

**Day-2 (9 March, 2024)**

1. Selected the model eos30gr from the list of suggested models in GitBook.
2. Read the publication of the model to get a deeper understanding of the model
3. Downloaded, served and ran the model to ensure that it works on my system using the following commands :
```
ersilia -v fetch eos30gr
ersilia serve eos30gr
ersilia -v api run -i "CCCC" > run_selected_model.log
```

> Log file of the output : 
> [run_selected_model.log](https://github.com/ersilia-os/ersilia/files/14546254/run_selected_model.log)
> 

4. Opened a GitHub repository to contain all the necessary files

**Comment by dubeyayushi** [comment]
@DhanshreeA I have finished the first task of the second week, i.e. created the model_bias.ipynb notebook and added all the necessary files in the GitHub repository. As mentioned in the Ersilia GitBook, I request you to review the [GitHub Repository](https://github.com/dubeyayushi/Outreachy_Contribution_Period-Ersilia-Model-Hub/tree/main) and suggest any changes that I need to incorporate. Thanks!

**Comment by DhanshreeA** [comment]
Hey @dubeyayushi, good job so far! Perhaps you would like to binarize the probability outcome based on some threshold value and comment on whether you think the model produces biased outcomes or not.

**Comment by dubeyayushi** [comment]
Thanks for the review @DhanshreeA! Sure, I'll start working on it right away.

**Comment by dubeyayushi** [comment]
Hi @DhanshreeA,
I would like to draw your attention to an issue related to the eos30gr model, that I and a few of the Outreachy applicants are facing.

**_Issue Title_: Unable to Obtain Model Output after Recent Repository Commits**

**Description:**
After attempting to fetch and run the eos30gr model from the repository, I encountered an issue where the model output was returning null values. Initially, I had opened the Conda environment in which I had done the tasks of the first week and the first task of the second week, and attempted to fetch the model, but encountered a message indicating that several dependencies were not installed, despite being previously installed. In response, I closed the terminals, reactivated the Ersilia environment, and reinstalled the package using pip install -e .. However, after these steps, the model began to produce null output. Upon inspecting the model repository, I noticed that there have been recent commits made to the repository in the past 3-4 days. I suspect that the recent commits may have affected the functionality of the model, possibly due to changes in dependencies or other factors.

**Steps to Reproduce:**

1. Reactivate Conda Ersilia environment.
2. Reinstall Ersilia package using pip install -e ..
3. Fetch and run eos30gr model using the following commands:
```
ersilia -v fetch eos30gr
ersilia serve eos30gr
ersilia -v api run "CCCC"
```
4. Observe null output. Here is the log file of the output I received after running the above commands.
[null_outcome.log](https://github.com/ersilia-os/ersilia/files/14623943/null_outcome.log)

**Expected Behavior:**
After reactivating the environment and reinstalling the package, the eos30gr model should produce valid output as expected.

**Additional Information:**

- Other models are functioning properly.
- Suspect that recent commits to the repository may have impacted model functionality.
- Requesting assistance in resolving the issue and restoring proper functionality to the eos30gr model.

**Comment by dubeyayushi** [comment]
@DhanshreeA, I have completed the second task of the second week, i.e., model reproducibility. Since the model was giving null output for every input, I requested my friend, who had not run the `pip install -e .` command on her system recently to reinstall the Ersilia Python Package, to run my input file on her system. I performed further analysis on the output file that was generated after running the model on CLI. Here is the [link](https://github.com/dubeyayushi/model-validation-eos30gr/tree/main) to the repository. Kindly review my work and suggest required changes. Thanks!

**Comment by DhanshreeA** [comment]
> Hi @DhanshreeA, I would like to draw your attention to an issue related to the eos30gr model, that I and a few of the Outreachy applicants are facing.
> 
> **_Issue Title_: Unable to Obtain Model Output after Recent Repository Commits**
> 
> **Description:** After attempting to fetch and run the eos30gr model from the repository, I encountered an issue where the model output was returning null values. Initially, I had opened the Conda environment in which I had done the tasks of the first week and the first task of the second week, and attempted to fetch the model, but encountered a message indicating that several dependencies were not installed, despite being previously installed. In response, I closed the terminals, reactivated the Ersilia environment, and reinstalled the package using pip install -e .. However, after these steps, the model began to produce null output. Upon inspecting the model repository, I noticed that there have been recent commits made to the repository in the past 3-4 days. I suspect that the recent commits may have affected the functionality of the model, possibly due to changes in dependencies or other factors.
> 
> **Steps to Reproduce:**
> 
>     1. Reactivate Conda Ersilia environment.
> 
>     2. Reinstall Ersilia package using pip install -e ..
> 
>     3. Fetch and run eos30gr model using the following commands:
> 
> 
> ```
> ersilia -v fetch eos30gr
> ersilia serve eos30gr
> ersilia -v api run "CCCC"
> ```
> 
>     4. Observe null output. Here is the log file of the output I received after running the above commands.
>        [null_outcome.log](https://github.com/ersilia-os/ersilia/files/14623943/null_outcome.log)
> 
> 
> **Expected Behavior:** After reactivating the environment and reinstalling the package, the eos30gr model should produce valid output as expected.
> 
> **Additional Information:**
> 
>     * Other models are functioning properly.
> 
>     * Suspect that recent commits to the repository may have impacted model functionality.
> 
>     * Requesting assistance in resolving the issue and restoring proper functionality to the eos30gr model.

Thank you @dubeyayushi , we will look into this.

**Comment by Tsion-Zeleke** [comment]
@dubeyayushi try git fetch eos30gr --from_git (this worked for me after trying for weeks :))

**Comment by DhanshreeA** [comment]
@dubeyayushi good work so far! We have noticed in other applicants' results as well that model eos30gr is indeed not reproducing the same results as in the publication. This is very helpful for us, thank you.
You can proceed to submit the final application by linking this issue.

**Comment by dubeyayushi** [comment]
> @dubeyayushi try ersila -v fetch eos30gr --from_git (this worked for me after trying for weeks :))

Thanks for your reply @Tsion-Zeleke. However, I did try this command multiple times. I tried it again, but it still gives `null` outcome. Following are the commands I used:

```
ersilia -v fetch eos30gr --from_github
ersilia serve eos30gr
ersilia -v api run -i "CCCC" > output.log
```
And this is the `output.log` file that I am getting: 
[output.log](https://github.com/ersilia-os/ersilia/files/14724566/output.log)

**Comment by dubeyayushi** [comment]
Hi @DhanshreeA @GemmaTuron, I've completed the third task of the contribution period,i.e., external validation. I chose the dataset used as a testing and validation dataset by Li et al. in their [publication](https://acrobat.adobe.com/id/urn:aaid:sc:ap:01ce6a64-01b1-4369-a583-84e1c8da5015). The dataset can be downloaded using this [link](https://ochem.eu/login/show.do?render-mode=full). I preprocessed and eliminated repeated molecules and upon further analysis, I found that the model's predictions differed from the experimental results provided in the dataset. I created all the necessary visualizations and finalized the notebook. Furthermore, I have also revised the repository and all the files and added final updates. Please review my work and suggest any final incorporations before I proceed to work on my final application. Thank you! [GitHub Repository Link](https://github.com/dubeyayushi/model-validation-eos30gr/tree/main)

**Comment by dubeyayushi** [comment]
> Hi @dubeyayushi
> 
> As @DhanshreeA said last Friday, please start working on your final application as we are nearing the end of the contribution period and we will only provide feedback on final applications this week. On a quick look on your last task nonetheless, the AUROC curve has a wierd shape, how many molecules are you evaluating? please have a look at why it is just giving an almost straight line

Thanks for your prompt response @GemmaTuron. I've taken note of your feedback and have started working on my final application. I'll make sure to let you know as soon as it's ready for review.

Regarding the shape of the AUROC curve, I believe that it is due to the false positive rate being zero (as evidenced by the confusion matrix) which typically indicates that the model is highly conservative in making positive predictions, i.e., it tends to predict only true positive instances and avoids false positives altogether. I am evaluating all the 562 molecules that have been filtered after dealing with data leakage and eliminating repeated molecules between the training and external datasets.
