### ISSUE TITLE
Contribution Period: <Kunga Derick Abongho>

### ISSUE THREAD

**Issue by Dericko681** [ersilia-os/ersilia#1005]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Dericko681** [comment]
Letter of motivation to work at ersilia
 As a computer engineering student, my primary objective is to contribute meaningfully to projects which enhance the well being of humans. Working at ersilia will enable me to gain experience in applying my skill in Data analytics, shell scripting, data science, programming languages(R, python) to drive innovation
My proficiency in data analysis allows me to dive deep and draw insights from a large amount of data using spreadsheets, DBMS, rstudio, pandas and numpy and to create responsive reports and dashboards to display visualization of results from my analysis. I used tools like Tableau, spreadsheets and ggplot2 package in R and cognos.
I look forward to contribute to this open source project not only for the 12 weeks as required by outreachy but also to work handy with my mentors and project team after my project untill this project is taken to the market as a finished product.This will allow me to gain experience which can be showcased on my social Media handles and resume to catch the sight of human resource recruiters
I look forward to working with you 
Thank you for considering me
Warm regards,
Kunga Derick Abongho

**Comment by Dericko681** [comment]
@DhanshreeA please find my week2 task in this github repository
https://github.com/Dericko681/classification_of_hERG_blockers_and_nonblockers/blob/master/ersilia

**Comment by GemmaTuron** [comment]
Hi @Dericko681 

In order for us to review the tasks, please make sure to follow the template provided for the repository, using the same file structure and making sure the notebooks are in the right format

**Comment by DhanshreeA** [comment]
Closing issue due to no response from @Dericko681

**Comment by Dericko681** [comment]
@DhanshreeA I'm still active and hasn't been able to respond to the comment or update my repository until today due to the submarine damage on optic fibers along the coastline of central Africa affecting Internet connection in multiple African countries
I hope you understand
