### ISSUE TITLE
✍️ Contribution Period: Marsha T

### ISSUE THREAD

**Issue by marshatiisa** [ersilia-os/ersilia#1006]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by marshatiisa** [comment]
I joined Outreachy because of the access to various open source projects that I could engage in and find interesting communities and projects to contribute to, address modern problems and learn from peers and mentors. I'm interested in working at Ersilia because of your work impacting and supporting disease research in lower income countries, leveraging AI/ML tools. As a self-taught and early career software engineer, I have used Python, JavaScript, git, GitHub, GitHub Actions, data visualization libraries, Docker, etc. to build personal projects and train AI models to choose the best code responses according to project requirements. This got me interested in discovering more about machine learning.  I believe that working directly on this platform and learning more about AI/ML tools will enable me to advance my career through skill building. My plans during the internship are to collaborate, meet deliverables and learning goals. My plans after are to continue with open source contributions with my deepened skills and work full-time.

**Comment by GemmaTuron** [comment]
Hi @marshatiisa 

We have not found the application to Outreachy. Which name did you use when submitting your application? If you no longer wish to contribute please let us know so we can close the issue

**Comment by GemmaTuron** [comment]
Thanks @marshatiisa found it!

Please update this issue with Week 2 tasks so we can provide feedback when you are ready

**Comment by DhanshreeA** [comment]
Closing issue due to no response from @marshatiisa
