### ISSUE TITLE
✍️ Contribution period: Tsion Zeleke

### ISSUE THREAD

**Issue by Tsion-Zeleke** [ersilia-os/ersilia#1007]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [x] Find a suitable dataset with sufficient experimental results
- [x] Clean and standardize the dataset
- [x] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by Tsion-Zeleke** [comment]
I  Installed the Ersilia Model Hub and test the simplest model
- ###  *pre-requisite*
```console

**Comment by Tsion-Zeleke** [comment]
### I installed Ersilia and tested the model. The model run successfully with the below output
```console
(ersilia) tsion@LAPTOP-MRB3DIHJ:~/ersilia$ ersilia -v api run -i "CCCC"
...
23:13:49 | DEBUG    | Rearranging and returning
23:13:49 | DEBUG    | Done with unique posting
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}
(ersilia) tsion@LAPTOP-MRB3DIHJ:~/ersilia$
```

**Comment by Tsion-Zeleke** [comment]
## Motivation Letter
### Self Introduction
I'd like to introduce myself as a person who is enthusiastic about automation and its impacts. In addition to studying computer science, I completed a 1 year intensive software engineering program with a focus on backend development at ALX.
Over the past few years, I have worked in various sectors, including full-stack development and data analysis, utilizing my research and analytical skills to improve smallholder farmers' lives.

### How I was Introduced to Machine Learning
I was first introduced to ML when working on a project on developing a REST API for a Y-Maze test. It was based on a pretrained model aiming to automate laboratory researchers' tasks. The project initially seemed intimidating, but with intensive research, I learned a lot and am grateful for the exposure.
### Ersilia 
It was fascinating to see that Ersilia has already begun the path of utilizing currently released technologies to help the world. I think that technology has the potential to change people's lives in different sectors, but that potential is not fully utilized. There is yet to be discovered. Research centers and labs are not as fully automated as they could be.
It was quite exciting when I ran the previous (ersila week 1) task with minimal commands and setups. I was able to run a test, which might have taken a significant amount of time, energy, and skill. Ersilia, in my opinion, is achieving what most software engineers and I hope to achieve, which is using various technologies to improve the world and serve as an inspiration for future innovations.
I believe we are in the perfect time where initiatives and ideas can be easily brought to light, but many people still lack knowledge and tools. Growing open-source projects like Ersilia can assist individuals learn and contribute to the community.
### Conclusion
It would be a great pleasure to join a nonprofit organization that aims to assist experts in discovering new drugs for treating infectious and neglected diseases using the latest technologies, making it convenient and time-saving.
My long-term goal is to work on a project that improves people's lives. I have the vision to enhance my country and the world by coming up with new solutions to various problems.
I would love to be a part of the team so that I can give back to the community. I'm eager to contribute to and learn from Ersilia!

Best,
*Tsion Zeleke*

**Comment by Tsion-Zeleke** [comment]
## Week 2
### I selected Esilia's model *eos30gr*
   - After conducting some research on HERG, HERG Blockage, and the risks for the heart, I found the model that works on the classification of hERG blockers and non-blockers (eos30gr) to be interesting.

**Comment by Tsion-Zeleke** [comment]
### I decided to use codespace to run the selected model following below steps:
  - I re-installed all the prerequisites on Codespace
      - >_I really enjoyed using CodeSpace instead of my Ubuntu terminal. 🚀 Compared to last week's installation on Ubuntu, this week's installation prerequisites on CodeSpace were super fast and time-saving._⏱
   - I found out from this [link] that the Ersilia hub can be run as a Python function so I fetched and served the model as a function in Jupyter inside codespace
      -  > _the jupyter notebook for for fetching and serving model via python function can be found here_ []

**Comment by Tsion-Zeleke** [comment]
@DhanshreeA I keep getting null as output despite trying all the above method.

**Comment by GemmaTuron** [comment]
Hi @Tsion-Zeleke 
Sorry to hear you are still facing trouble. I cannot comment on the log as I need you to run and save them with the -v command when fetching the model, please could you run in your CLI:

`ersilia -v fetch eos30gr > out.log 2>&1`

And, in paralel: open a codespace from Ersilia's main repository (Ersilia is automatically installed there) and try to do the fecthing in CodeSpaces? Each github user has free Codespace time, so that should be fine for you to try. Remember to close the codespace once finished.

Hope this is helpful

**Comment by Tsion-Zeleke** [comment]
@GemmaTuron thank you for the comments!!
I tried to run codespace from [Ersilia main repo](https://github.com/ersilia-os/ersilia/). but out put is still "null"
   - I fetch the model and saved  the log file as mentioned [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/Debugging%20model%20eos30gr/logs/fetch_eos30gr.log)
   - The log file for serving the model can also be found [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/Debugging%20model%20eos30gr/logs/serve_eos30gr_.log)
   - I used the molecule "CCCC" and directly ran the model via `ersilia -v api run -i "CCCC"`  output is null. out put  is uploaded [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/Debugging%20model%20eos30gr/logs/run_eos30gr%20%5B_CCCC_%5D.log)
   - I tested it again this with 10 different smiles molecules using `ersilia api run -i input.csv -o run_eos30gr_using_file.csv
` please find log file [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/Debugging%20model%20eos30gr/logs/run_eos30gr_using_file.csv) with empty output for all 10 molecules

**Comment by GemmaTuron** [comment]
Does it happen with any other model on Ersilia? Did you run eos3b5e first to check the ersilia installation?

**Comment by GemmaTuron** [comment]
Please make sure you have ersilia properly installed, using a simple model as test (eos3b5e) as the model works fine for me simply following the standard Ersilia commands:
```
(ersilia) gturon@pujarnol:~$ ersilia run -i "CCCCC"
{
    "input": {
        "key": "OFBQJSOFQDEBGM-UHFFFAOYSA-N",
        "input": "CCCCC",
        "text": "CCCCC"
    },
    "output": {
        "outcome": [
            0.4752475247524752
        ]
    }
}
```

**Comment by Tsion-Zeleke** [comment]
@GemmaTuron [this](https://ersilia-outreachy-s24.slack.com/archives/C06K0999MMW/p1710754042474099) slack conversation was mentioning that the model works fine for the ones who fetched earlier but other who fetched it later were having null output issue. could it be related to new commits made to the model repo

**Comment by GemmaTuron** [comment]
Hi @Tsion-Zeleke 

The models are being regularly updated for maintenance. I'd suggest making sure you have the latest ersilia code pulled from the repository, and then the models should work fine

**Comment by Tsion-Zeleke** [comment]
@GemmaTuron thank you so much!!! I tried running the latest model as suggested using `ersilia -v fetch eos30gr --from_github` and it worked 
```console
(ersilia) root@codespaces-ea4b15:/workspaces/ersilia# ersilia api run -i "CCCC"
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "outcome": [
            0.1782178217821782
        ]
    }
}
```

**Comment by DhanshreeA** [comment]
Hi @Tsion-Zeleke you can submit the final application.

**Comment by Tsion-Zeleke** [comment]
@DhanshreeA I encountered multiple issues when running the model and tried different methods to debug 
I've included the details of issues and debugging I performed [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/). I will process and submit the final application as your suggestion thanks

**Comment by Tsion-Zeleke** [comment]
###Task 1 can be found [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation)
- 00_eos30gr_model_bias.ipynb
   - [Data Processing](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-1)
   - [Running Model](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-2)
   -[Evaluate Prediction](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3)
   -[histograph](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-1)
   -[basic statistics mean,median...](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-2)
   -[Threshold Prediction using 0.5 as value](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-3)
   -[Frequency](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-4)
   -[Top 10 non HERG Blocker molecules](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-5)
   -[Top 20 non HERG Blocker molecules](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/README.md#section-3-6)

**Comment by Tsion-Zeleke** [comment]
### Task 2 can you found [here]()
   - Model Reproducibility [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/01_model_reproducibility.ipynb)
      - [deephERG(authors model) Output Cleaning and Calcualtion](#section-1)
      - [eos30gr Output cleaning and calculation](#section-2)
      - [Compare both outputs and visualize analysis](#section-3)

**Comment by Tsion-Zeleke** [comment]
### Task 3 can be found [here](https://github.com/Tsion-Zeleke/Ersilia_Model_eos30gr_Validation/blob/main/notebooks/02_external_validation.ipynb)
   - #### Model Validation
      - In this notebook, I will try to get the performance of the model on an external dataset I have obtained from ChEMBL [here](https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL1794573/)
      - The dataset contains [Small Molecule Inhibitors of the Human hERG Channel Activity](https://www.ebi.ac.uk/chembl/assay_report_card/CHEMBL1794573/)
      - I'll Clean the [dataset](https://www.ebi.ac.uk/chembl/g/#browse/compounds/filter/_metadata.related_assays.all_chembl_ids%3ACHEMBL1794573)
      - Add class to represent hERG blockers
      - Run prediction for the same smile using eos30gr(the model implemented by ersilia)
      - I'll Clean the [dataset](https://www.ebi.ac.uk/chembl/g/#browse/compounds/filter/_metadata.related_assays.all_chembl_ids%3ACHEMBL1794573)
      - Add class to represent hERG blockers
      - Run prediction for the same smile using eos30gr(the model implemented by ersilia)
      - Compare results using several ML performance metrics

**Comment by Tsion-Zeleke** [comment]
@DhanshreeA I have submitted my final application to Outreachy. I thoroughly enjoyed working with the Ersilia Hub and am grateful I chose eos30gr, as it has taught me a lot about how models are implemented and the overall process. Thank you for the support; I have learned a lot over the past few weeks.
