### ISSUE TITLE
✍️ Contribution period: Darren Enow Eban Odi 

### ISSUE THREAD

**Issue by darrenodi** [ersilia-os/ersilia#1012]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by darrenodi** [comment]
#Motivation for Joining Outreachy and Interest in Ersilia

Dear Ersilia Team,

I am writing to express my strong interest in the Outreachy program and my keen desire to work with Ersilia.

As a recent graduate with a degree in Computer Engineering and experience in full-stack web development, data science, and JavaScript, I am eager to contribute my skills to your organization's mission of democratizing access to AI/ML models for biomedical research.

I am particularly drawn to Ersilia's focus on supporting research in neglected disease areas and its collaboration with the University of Buea Centre for Infectious Disease Research, my alma mater. I believe that my skills and passion for using technology to address global health challenges make me a good fit for Ersilia.

During the internship, I plan to actively engage with the team, contribute to the development of the Ersilia Model Hub, and learn from experienced professionals. I am confident that the experience gained at Ersilia will be invaluable to my career growth.

Beyond the internship, I am eager to continue working at the intersection of AI/ML and biomedical research, with a focus on neglected diseases. I believe that my contributions can make a positive impact on global health.

Thank you for considering my application. I am excited about the possibility of joining the Ersilia team and contributing to your important work.

Sincerely,
Darren Enow Eban Odi

**Comment by darrenodi** [comment]
@DhanshreeA Greetings . I have successfully completed all the week 2 tasks as seen in my github . Can you please review it 
https://github.com/darrenodi/model-validation-example.

**Comment by darrenodi** [comment]
Greetings @DhanshreeA . Please can you review my work and comment on how I am doing? Thank you :)

**Comment by GemmaTuron** [comment]
Hi @darrenodi thanks,w e will provide feedback today

**Comment by darrenodi** [comment]
> Hi @darrenodi thanks,w e will provide feedback today

Thank you so much. My work was slow because I hadn't received feedback so I was unsure of my progress.

**Comment by darrenodi** [comment]
Thank you @DhanshreeA , working on that now

**Comment by DhanshreeA** [comment]
Hi @darrenodi please submit the final application. It is okay if you couldn't finish everything.

**Comment by darrenodi** [comment]
Good morning @DhanshreeA, @GemmaTuron  . 
I hope you are well
I completed my application but I couldn't answer the final question on project time line and I was asked to talk to. mentor. Can you help me with that?
