### ISSUE TITLE
Outreachy Code Project: Abdelrahman Nawar

### ISSUE THREAD

**Issue by Nawarrr** [ersilia-os/ersilia#102]
Applicant: Abdelrahman Nawar @Nawarrr

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [x] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [x] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [x] Select one issue related to improving the CLI and request to be assigned to it.
- [x] Link the #PR as a comment under this issue.
- [x] Make any changes required in the PR and tick this box once it has been approved.
- [x] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [x] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [x] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [x]  Check the models available in the Hub
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [x] Link in the comments any other PR you have contributed to.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by Nawarrr** [comment]
![WhatsApp Image 2022-04-03 at 4 09 41 PM](https://user-images.githubusercontent.com/46817360/161432753-eb6ed3ac-20f5-4f8f-9ea1-872387392c4a.jpeg)

**Comment by GemmaTuron** [comment]
Ho @Nawarrr please could you add your name in the Issue title? where it says <Applicant>

**Comment by Nawarrr** [comment]
I'm Interested in Ersilia as I believe in the product and what it delivers, I think I will be learning a lot if I got accepted, 
I've applied to this project specially because I think it fits my skills and the benefit are what I need to learn for the career that I want, I've been using Python for the past three years, I freelanced for a couple of months doing Python Automation and Scripting, I've also built multiple projects, in backend, Data science, Desktop automations, etc.

**Comment by Nawarrr** [comment]
fetched 3 models
![Ersilia_3models](https://user-images.githubusercontent.com/46817360/161737717-8e7a7f79-baba-4c32-8c8d-445e4a516550.png)

**Comment by Nawarrr** [comment]
Perdiction using as a Python library![ersilia_jup_notebook](https://user-images.githubusercontent.com/46817360/162090634-4e700e51-fcfb-440f-8e86-a7e2896e4e8a.png)

**Comment by Nawarrr** [comment]
Here is a simple Streamlit app
![Screenshot 2022-04-07 at 04-04-19 main · Streamlit](https://user-images.githubusercontent.com/46817360/162105894-a7785321-d799-4893-96bf-29d9b99176d7.png)

**Comment by GemmaTuron** [comment]
Hi @Nawarrr 

Thanks! I am tagging @miquelduranfrigola to check on this but looks good! As I suggested to some other applicants, displaying the molecule as an image when it is inputed would be cool

**Comment by Nawarrr** [comment]
> Hi @Nawarrr
> 
> Thanks! I am tagging @miquelduranfrigola to check on this but looks good! As I suggested to some other applicants, displaying the molecule as an image when it is inputed would be cool
![ersilia_streamlit_visualised](https://user-images.githubusercontent.com/46817360/162235281-e82f0996-1c5a-4bd4-bd23-e09b36f526af.png)

**Comment by Nawarrr** [comment]
#180

**Comment by GemmaTuron** [comment]
thanks @Nawarrr this looks cool with the molecule drawn!

**Comment by miquelduranfrigola** [comment]
Indeed this is quite good. Thanks @Nawarrr

**Comment by Nawarrr** [comment]
Here is my suggestion : #211
I'm currently studying solutions for it

**Comment by Nawarrr** [comment]
@GemmaTuron @miquelduranfrigola,
Here is the docstring for ErsiliaModel class, but I have multiple inquires



```python
class ErsiliaModel(ErsiliaBase):
    """The ErsiliaModel object works as the main object for 
    ersilia. It takes the identifier of the model as an attribute,
    then it gets used as an interface for fetching, serving and using the model.

    Identifier is used in fetching model information, the avalibilty
    of the model locally will be checked before fetching. The identifier
    and the slug can be used interchangebly to fetch the model information.

    Typical usage example:
    
        from ersilia import ErsiliaModel
        mdl = ErsiliaModel(__identifier__) 
    
    Attributes:
        model: A str of the identifier or the slug of the model.
        save_to_lake (optional): A boolean Indicating whether the calculations
            will be stored to the lake.
        service_class (optional): A str Indicating the service class.
        config_json (optional): A str of the path to a configuration file.
        credentials_json (optional): A str of the path to a credentials file.
        verbose (optional): A boolean to control enabling verbose output.
        fetch_of_not_avalible (optional): A boolean to enable fetching the model
            if it's not avalible locally.
    """
```
1- The 2nd paragraph is more of about what the class does with the main argument, not the class itself, should that be removed ?
2- The way I've mentioned the type of the Argument is the same as the google style guide, but in ErsiliaBase init's docstring, the notation used is the parentheses() as I've used to mention that the attribute is optional
I've used the parentheses to mention the optionality of the attribute, should I add the type with it instead of what I'm doing ?

**Comment by dauinh** [comment]
Hi @Nawarrr I think your CLI feature suggestion is a really good idea

**Comment by Nawarrr** [comment]
> Hi @Nawarrr I think your CLI feature suggestion is a really good idea

Thanks, I really appreciate you helping me in that feature

**Comment by Nawarrr** [comment]
Natural Product Fingerprint Model Card
![card_pic](https://user-images.githubusercontent.com/46817360/163908253-36f84378-50aa-4a8b-a8ec-8ad70bad9273.png)

**Comment by Nawarrr** [comment]
[here](https://github.com/ersilia-os/ersilia/issues/211) is my idea to improve ersilia , I also think that automated tests to check PR would accelerate the contribution process ,
Other PRs I've worked on:
#180

**Comment by Nawarrr** [comment]
I'm assigned to  #211, but I do intend to work in this after the final application, I won't mark the "All PR or issues assigned to me are complete"
