### ISSUE TITLE
✍️ Contribution period: Prakriti Maurya

### ISSUE THREAD

**Issue by prakmaurya** [ersilia-os/ersilia#1021]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by prakmaurya** [comment]
### **Motivation for joining Outreachy and interest to work with Ersilia Open Source Initiative**
______________________________________________________________________________________________________
Hello dear mentors,

I am Prakriti Maurya, an undergraduate sophomore pursuing Bachelors in Technology in Computer Science and Artificial Intelligence from Indira Gandhi Delhi Technical University for Women. My field of interests are creative writing, machine learning and competitive programming. I am also decent in UI/UX.

I was introduced to Outreachy by one of my seniors in college. I myself being a self-taught learner believe that open source contributions and collaborations are one of the best way of development and growth. Hence, I was motivated to join this program and add more value to projects through my contributions.

Ersilia Open Source Initiative's vision of integrating ML in healthcare and making healthcare more accessible aligns fairly with my vision and compassion. I have also been a part of research work in the same domain previously which aimed to use ML in medical analysis. In that project, I had worked with PhD scholars to conduct literature reviews and find research gaps on the use of LLMs in gastroenterology and gynecology. I have also worked previously on some ML models and data science projects.

My belief of making our lives better with the use of ML and technology resonates well with Ersilia. I am excited to work in this project and add more value to it. I am looking forward to keep learning and improving my skills with this project and make meaningful contributions to this project.

**Comment by prakmaurya** [comment]
### 📝  **Week-2 Task Update**
_______________________________________________________________________________________________________________________________________

- ###  Task-1 

1. After exploring the 8 models for biomedical and biochemistry application, I have decided to proceed working with the "eos30gr" model. I found the paper published on this model it relatable and interesting. I am excited to explore this model, perform data augmentation, data visualization and predictions on this model.

> Work in progress for this task.

**Comment by GemmaTuron** [comment]
Hi @prakmaurya 

If it is giving Null outputs, it means there is probably an error in model fetching (for example a package not installing correctly).
Can you let me know:
- What command are you using to fetch? We recommend Docker 
- Please use the -v command at fetch time and attach the logs here
- Is the eos6oli working for you or is the same results?
