### ISSUE TITLE
✍️ Contribution period: <Gurjot Kaur> 

### ISSUE THREAD

**Issue by gjyotk** [ersilia-os/ersilia#1024]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by gjyotk** [comment]
Hello Ersilia Community!

I am Gurjot Kaur, a sophomore student doing my Undergraduate in Computer Science Hons. in Artificial Intelligence and Machine Learning. While exploring the Data Science and Machine Learning domain through Outreachy, I came across Ersilia Open Source Initiative. I found the open project of creating a platform to feature pre-trained AI/ML Models for Biomedical quite interesting and fulfilling. Given my previous experience working in data science, I believe that I can contribute to its growth and learn new things along the way.

As a beginner to Open Source contribution, I am deeply motivated as well as excited to work alongside Ersilia community, to learn from them, and navigate through this vast space of Open Source.

Thank you,
Gurjot Kaur

**Comment by gjyotk** [comment]
## Testing sample model

## Steps followed-
- Setting up pre-requisites:
  1.  Installing gcc compiler
  2. Python latest version
  3. Anaconda environment
  4. Git and Github CLI
  5. Git LFS
  6. Isaura data lake
  7. Docker 
- Install and activate Ersilia
- Select a model ID(EOS-ID) from ersilia catalog
- Fetch the selected model and install it locally
- Serve the model and run it
- Close the model


<img width="681" alt="Screenshot 2024-03-10 at 12 56 27 AM" src="https://github.com/ersilia-os/ersilia/assets/112189682/5cb3833b-9f76-4f21-ab5d-14dd75f3a7d3">

**Comment by GemmaTuron** [comment]
Hi @gjyotk 
Good start, please let us know when you continue with week 2 tasks and remember there is a lot of information on Slack to help you out!

**Comment by gjyotk** [comment]
Hello @GemmaTuron 
Sure! I am currently working on dataset selection and cleaning and will share my task update along with the link

**Comment by DhanshreeA** [comment]
Hi @gjyotk unfortunately the mentors will not be able to provide any feedback on your work at this time. However feel free to share it with your peers over Slack if you wish to. 
You can submit your final application at this point, as that is the only thing we are actively providing feedback for within this week.
