### ISSUE TITLE
✍️ Contribution period: Anshika Vashistha 

### ISSUE THREAD

**Issue by anshikavashistha** [ersilia-os/ersilia#1029]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by anshikavashistha** [comment]
## Motivation for joining Outreachy and interest to work with Ersilia Open Source Initiative
Greetings to everyone, I am Anshika Vashistha, an undergraduate pursuing Bachelors in Technology in Information Technology from Galgotias College of Engineering and Technology, India.I have a keen a interest in the field of data science,LLMs and docker as I learnt little about these tech stacks in my internship where I worked with various LLM models and text summarization (https://cuddly-rosehip-b51.notion.site/Text-Summarization-7ea8c07bb8e04842969615e6a9252265).
I was first being introduced to Outreachy by one of my friend in Codivas.I was motivated to be a part of this wonderful community to learn more about open-source .The thing which motivates me the most about outreachy is it motivates and provides beginners an opportunity to enter  into the world of open-source encouraging great diversity and socio-economic disparities.
Ersilia Open Source Initiative stands out as an ideal organization to collaborate with during the Outreachy internship. Ersilia's commitment to leverage technology for social good aligns perfectly with my own values and aspirations. The opportunity to work with Ersilia presents a chance to enhance my skills and knowledge in a meaningful context, contributing to projects that have a tangible impact on communities and society at large.
My motivation for joining Outreachy and my interest in working with Ersilia Open Source Initiative stem from a deep-seated commitment to leverage technology for social good. I am excited about the opportunity to embark on this journey with Ersilia and make a meaningful impact through my contributions as an Outreachy intern.

**Comment by anshikavashistha** [comment]
@DhanshreeA Please review my tasks for first week

**Comment by anshikavashistha** [comment]
I have selected [eos4tcc](https://github.com/ersilia-os/eos4tcc) from the gitbook mentioned. I find this interesting as it is pretrained on a bayesian graph neural network.I have some sort of experience with bayesian graph neural network and would love to contribute and learn about this model

**Comment by anshikavashistha** [comment]
I have created a repository for validation of ersilia model - https://github.com/anshikavashistha/eos4tcc-validation

**Comment by anshikavashistha** [comment]
I have also done some sort of research on the model on which I am working.Here is the link to https://glitter-germanium-512.notion.site/Ersilia-31a63e1433d54b0d864c10ecd93a47b3

**Comment by DhanshreeA** [comment]
> I have also done some sort of research on the model on which I am working.Here is the link to https://glitter-germanium-512.notion.site/Ersilia-31a63e1433d54b0d864c10ecd93a47b3

Hi @anshikavashistha I recommend using comments on this issue or your repository's README to document all your research efforts.

**Comment by GemmaTuron** [comment]
Hi @anshikavashistha 

Let us know once this task has been updated so we can provide feedback

**Comment by anshikavashistha** [comment]
Sure @GemmaTuron

**Comment by DhanshreeA** [comment]
Hi @anshikavashistha I see that there are no updates within the repository you have provided since the last check in. I am unsure if you want to continue at this point because this is the last week of the contribution period. I am closing this issue, feel free to open it if you have any updates. You can still submit your final application with us if you so wish.
