### ISSUE TITLE
✍️ Contribution Period: Ogbonna Chidinma 

### ISSUE THREAD

**Issue by chibaby-cyber** [ersilia-os/ersilia#1031]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by chibaby-cyber** [comment]
**My Motivation For Joining Ersilia**

When I was first going through the list of available projects, this one first caught my eyes because I have good practice with two of the wanted skills, python and docker. I have always had an interest in learning machine learning and data science so when I saw this project, I was immediately drawn to it. My motivation is my eagerness to learn and be better at what I do every day.

Most importantly the Ersilia Open-Source Initiative is a UK-based charity focused on strengthening the research capacity for infectious and neglected diseases by developing and implementing novel artificial intelligence and machine learning tools. I see this as an opportunity to contribute to making the world a better place. I have a family member who has been ill for a while and though I may not be able to help him, I think it is a good thing that I can help others.

**Comment by GemmaTuron** [comment]
Hi @chibaby-cyber 

We have seen you have ticked some of W2 tasks but have not updated anything here. Please, let us know the status so we can provide feedback
