### ISSUE TITLE
🦠 Model Request: REINVENT 4 Mol2MolScaffold

### ISSUE THREAD

**Issue by ankitskvmdam** [ersilia-os/ersilia#1032]
### Model Name

REINVENT 4 Mol2MolScaffold

### Model Description

Mol2MolScaffold uses REINVENT4's mol2mol_scaffold.prior and mol2mol_scaffold_generic.prior to generate around 500 new molecules similar to the provided molecuels.

### Slug

reinvent4-mol2mol-scaffold

### Tag

Similarity

### Publication

https://chemrxiv.org/engage/chemrxiv/article-details/65463cafc573f893f1cae33a

### Source Code

https://github.com/MolecularAI/REINVENT4

### License

Apache License 2.0

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam ! @GemmaTuron can you please have a look in the context of ChemSampler and close this model if it works?

**Comment by GemmaTuron** [comment]
thanks @ankitskvmdam great work! I'll test it and get back to you!

**Comment by GemmaTuron** [comment]
Hey @miquelduranfrigola and @ankitskvmdam 

The model works but I have not used it in the context of chemsampler. I'll close the model request and if there is need for edits I'll open issues on the model repository itself
