### ISSUE TITLE
Paseda Modupe Oluwaseun

### ISSUE THREAD

**Issue by PASEDA-MODUPE** [ersilia-os/ersilia#1036]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by PASEDA-MODUPE** [comment]
![Screenshot 2024-03-08 163606](https://github.com/ersilia-os/ersilia/assets/127091710/4f9e41f9-7fa6-4788-a499-e303a6cb51a4)
![Screenshot 2024-03-08 163540](https://github.com/ersilia-os/ersilia/assets/127091710/31058952-8c0b-4316-8b9e-90bad58e2b64)

-  Installed ubuntu in Wsl environment 
- Installed docker desktop
- Install the Ersilia Python package

**Comment by PASEDA-MODUPE** [comment]
MOTIVATIONAL STATEMENT

As a Nigerian woman, I recognize the importance of representation and diversity in the tech sector we are limited to technology and made to believe digital world is for the men fairly underrepresented because of our gender that I became so determined hope to serve as a role model for others from underrepresented backgrounds, demonstrating that individuals with diverse experiences and perspectives can thrive in the tech industry especially women.

I Studied hospitality management  being a self-taught learner i strongly believe that open source contributions and collaborations are one of the best way of development and growth.so when the opportunity came I was motivated to join this program and add more value to projects through my contributions.

By participating in projects with Ersilia, I seek to learn and acquire technical skills while making meaningful contributions to initiatives that address societal challenges. As a Nigerian woman, I am driven to leverage technology for positive change within my community and beyond. I see an avenue to not only expand my professional horizons but also to empower myself and others by utilizing technology to create tangible solutions and foster inclusive innovation.

**Comment by PASEDA-MODUPE** [comment]
[](https://github.com/PASEDA-MODUPE/eos6oli-model-testing)

**Comment by PASEDA-MODUPE** [comment]
@DhanshreeA  pls review my task so i can continue to the next stage thanks

**Comment by DhanshreeA** [comment]
Hi @PASEDA-MODUPE please go ahead and create the final application.

**Comment by PASEDA-MODUPE** [comment]
Alright noted @DhanshreeA will go ahead with the final application thank you
