### ISSUE TITLE
✍️ Contribution period: <Oluwaseun_Odusanwo> 

### ISSUE THREAD

**Issue by OluwaseunOdusanwo** [ersilia-os/ersilia#1037]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by OluwaseunOdusanwo** [comment]
OLUWASEUN ODUSANWO MOTIVATION LETTER

I am excited to express my interest in the internship at Ersilia. My keen interest in Data Science and AI, and passion for contributing to open-source projects motivated me to apply for this position.

I strongly believe that my experience has equipped me with the necessary skills, Python, machine learning, and model development needed to excel in this project. I am eager to learn new things and passionate about using my skills to contribute to the betterment of the healthcare industry.  

While researching Ersilia hub, I learned that it is an open-source platform with ready-to-use AI/ML models available to scientists to browse and make predictions, especially for diseases that are neglected due to lack of funding. I am excited that the organization uses its offering for social good which aligns with my purpose.

Thank you for your consideration. I look forward to the opportunity to contribute to the success and advancement of the organisation.

**Comment by GemmaTuron** [comment]
Hello  @OluwaseunOdusanwo 

We have not seen your application in the Outreachy website. Please let us know if you plan to continue with your contribution by the next 2 days, otherwise we will close this issue so we can focus on the applicants who want to make a final application to Ersilia.

**Comment by GemmaTuron** [comment]
Hi @OluwaseunOdusanwo 

I will close this issue so that mentors can focus on supporting applicants who wish to make a final contribution to Ersilia. If you still plan on applying, please let us know! Thanks for your understanding
