### ISSUE TITLE
✍️ Contribution period: Manya Sachdeva

### ISSUE THREAD

**Issue by manyajsingh** [ersilia-os/ersilia#1038]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by manyajsingh** [comment]
Week 1 tasks
Installed WSL on my system (Ubuntu version 22.0)
Installed Miniconda
Installed ersilia
Fetched model retrosynthetic-accessibility, ie, eos2r5a
Served and tested the model (found it quite interesting!)
Made predictions using it

Now, I will proceed to write my motivation letter as a part of the week-1 tasks given to us

**Comment by manyajsingh** [comment]
Motivation Letter to work at Ersilia (Week 1 Tasks)

Dear Erislia team and fellow contributors,
It's a pleasure to be working with you all. I found out about outreachy when I was working with one of my seniors on a data science project. I decided to give it a shot and therefore, wrote my initial application.

4th March the results come out and HURRAY!! Initial application approved. I was so happy and excited, but what followed it was not as wonderful.
Despite having made multiple projects using Python, Django, Flask, Medical Imaging and Signal Analysis Hub, Data Science and Machine Learning, this would be my very first time, properly contributing to open source.
I was simply so overwhelmed by everything that's going on.
But then I stumbled upon Ersilia. I ticked all the boxes when it came to their 'Required', 'Preferred', 'Nice to Have'. So I went with it and joined their team on Slack.

The team and the mentors I found were so so cooperative, understanding, helpful, and not to mention, EXTREMELY smart!!

Every task was specified so beautifully, the gitbook was impeccably made with so much love, everything was so easy-to-understand thanks to their way of presenting.

The Ersilia team can take the most complicated of the things and simplify it in the best way possible. 

To be very frank with you, chemistry as a subject used to be intolerable for me during high school, but when I read about the basic chemistry that we would be using for this project in the gitbook, it interested me and I couldn't wait to work more and learn more.

You ask me why I want to work for Ersilia, I ask you, WHY NOT?!
Ersilia as a concept appeals to me so much, I believe in it's cause, it's work, it's purpose, it's everything. If you ask me to devote all my time and days to this robust, wonderful, beautiful project to make it even more wonderful, I would. I happily would.

I believe that projects like these can help in truly tranforming our society for the better. I wish to be a part of ersilia regardless of whether I get selected as an intern or not.

If you've made it this far, thank you :)
And big thank you to Ersilia and team
Special Thanks to Ms. Dhanshree Arora, the one whom I've been following for quite some time and the one who's content gave me the courage and motivation to work towards my dreams.

**Comment by GemmaTuron** [comment]
Hi @manyajsingh 
We are on week 3 of the contribution period. Please let us know if you plan to continue with your contribution by the next 2 days, otherwise we will close this issue so we can focus on the applicants who want to make a final application to Ersilia.

**Comment by GemmaTuron** [comment]
@manyajsingh  sure, no problem.

You have ticked off week 2 tasks but there is no update here, please link your repository and explain the work you have done so far

**Comment by manyajsingh** [comment]
Hello, i have created a github repository for my week 2 work and also
uploaded the link as a contribution on the outreachy website. Do you want
me to reply to this email with the link as well?

**Comment by GemmaTuron** [comment]
Hi @manyajsingh 

Please link this issue on the Outreachy website and then report the work here, so we can follow up, discuss etc. You can check issues from other applicants to see how they are reporting on the work done. Let me know once it is updated.

**Comment by manyajsingh** [comment]
@GemmaTuron here is my work for week 2:
[https://github.com/manyajsingh/ersilia/blob/master/eos9f6t.ipynb](url)
[https://github.com/manyajsingh/ersilia/blob/master/ersilia_on_colab.ipynb](url)
[https://github.com/manyajsingh/ersilia/tree/master/notebooks](url)

**Comment by GemmaTuron** [comment]
Hi @manyajsingh 
The links do not redirect me to the right place apparently

Please make sure to create a NEW repo wit the structure suggested in the example repository provided in the documentation
