### ISSUE TITLE
Outreachy Code Project: Amna Ali

### ISSUE THREAD

**Issue by Amna-28** [ersilia-os/ersilia#104]
Applicant:  @Amna-28

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [x] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [x] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [x] Select one issue related to improving the CLI and request to be assigned to it.
- [x] Link the #PR as a comment under this issue.
- [x] Make any changes required in the PR and tick this box once it has been approved.
- [x] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [x] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [x] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [x]  Check the models available in the Hub
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [x] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [x] Link in the comments any other PR you have contributed to.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by Amna-28** [comment]
**Running "molecular-weight" Model:**

![ersilia-install](https://user-images.githubusercontent.com/98670206/161435602-409008d3-b2c8-470a-9f6a-71397f5f80f9.png)

**Comment by Amna-28** [comment]
**Screenshot of command "ersilia catalog --local" :**

![image](https://user-images.githubusercontent.com/98670206/161500978-d1a54241-08b1-4891-be84-563a3b61ac3d.png)

**Comment by Amna-28** [comment]
I am working on issue #8 - Track unused models and automatically delete them

**Comment by Amna-28** [comment]
**Suggest at least one missing feature in the CLI :** Improve catalog by including model size in "ersilia catalog" output
I have opened the issue #95 as an enhancement, I would love to work on it.

**Comment by Amna-28** [comment]
**Prediction Example using ersilia model on jupyter notebook**

![image](https://user-images.githubusercontent.com/98670206/161588394-d553a2df-6544-42ae-8d4b-dd68609e82a8.png)

**Comment by Amna-28** [comment]
**Created a simple Streamlit app :** takes the chemical structure as input and displays the results based on which model and api is selected by the user:

**Calculating the molecular weight of Aspirin**
![Capture1](https://user-images.githubusercontent.com/98670206/161626416-e504b898-38e0-44fa-88c5-071f7d1e682b.PNG)

**The antibiotic activity prediction** 
![Capture2](https://user-images.githubusercontent.com/98670206/161626509-db9df10f-f1cd-4b44-83fd-aaf607836246.PNG)

**Comment by GemmaTuron** [comment]
Hi @Amna-28 this looks great
See my suggestion under issue #126

**Comment by Amna-28** [comment]
I am working on issue **#126 - Add a streamlit app for ersilia model**

**Comment by Amna-28** [comment]
#126

**Comment by Amna-28** [comment]
**Why am I interested in this project?**

I am a Data science and Machine learning enthusiast with a masters degree in computer science. I have worked with different machine learning algorithms and tools. As this project involves Machine learning and Python programming, that I am very passionate about, I would really like to be a part of something that helps people and institutes where ML and bioinformatic experties are difficult to obtain.

**Comment by Rufaida98** [comment]
@Amna-28 hi amna sorry to bother you but i am trying to do the prediction by jupytor notebook but it does not work do you know if there is something i should do even though i installed all the necessary package

**Comment by Amna-28** [comment]
> @Amna-28 hi amna sorry to bother you but i am trying to do the prediction by jupytor notebook but it does not work do you know if there is something i should do even though i installed all the necessary package

Hi @Rufaida98 , I am happy to help. Can you please share exactly what problem are you facing?

**Comment by Rufaida98** [comment]
![eew](https://user-images.githubusercontent.com/92082003/162939185-53dd27e8-b3d7-481b-bb38-be4863ddafaf.PNG)

**Comment by Rufaida98** [comment]
@Amna-28 that the problem

**Comment by Nawarrr** [comment]
> ![eew](https://user-images.githubusercontent.com/92082003/162939185-53dd27e8-b3d7-481b-bb38-be4863ddafaf.PNG)

You can install it using pip in the notebook, I think it will fix this

**Comment by Rufaida98** [comment]
Yes I did install and of course please delete it

**Comment by Amna-28** [comment]
**Select one model from the list and write a technical card** 
![66585ecb76614e319d3161ff9690a5ec-0001](https://user-images.githubusercontent.com/98670206/163260023-f9bfa9a5-bdfc-4f75-8bbe-18db41ab702d.jpg)

Hi @GemmaTuron , this is my first time writing a technical card for a ML model. I followed [this](https://arxiv.org/abs/1810.03993) article to write it. Please let me know if there is anything that I can improve. Thanks!

**Comment by mahamtariq58** [comment]
Hi @Amna-28 , you have done an amazing job and the approach you used for tracking of unused models is quite good. Also, the streamlit app looks awesome.

**Comment by Amna-28** [comment]
> Hi @Amna-28 , you have done an amazing job and the approach you used for tracking of unused models is quite good. Also, the streamlit app looks awesome.

Thank you very much @mahamtariq58 for your feedback

**Comment by Nawarrr** [comment]
> **Select one model from the list and write a technical card** ![66585ecb76614e319d3161ff9690a5ec-0001](https://user-images.githubusercontent.com/98670206/163260023-f9bfa9a5-bdfc-4f75-8bbe-18db41ab702d.jpg)
> 
> Hi @GemmaTuron @miquelduranfrigola, this is my first time writing a technical card for a ML model. I followed [this](https://arxiv.org/abs/1810.03993) article to write it. Please let me know if there is anything that I can improve. Thanks!

Great Model card, seems to cover all the important points about the model, 
just remember to add the References

**Comment by Amna-28** [comment]
> > **Select one model from the list and write a technical card** ![66585ecb76614e319d3161ff9690a5ec-0001](https://user-images.githubusercontent.com/98670206/163260023-f9bfa9a5-bdfc-4f75-8bbe-18db41ab702d.jpg)
> > Hi @GemmaTuron @miquelduranfrigola, this is my first time writing a technical card for a ML model. I followed [this](https://arxiv.org/abs/1810.03993) article to write it. Please let me know if there is anything that I can improve. Thanks!
> 
> Great Model card, seems to cover all the important points about the model, just remember to add the References

Thank you @Nawarrr for your feedback!

**Comment by Amna-28** [comment]
### Write a docstring for the ErsiliaModel class

```

class ErsiliaModel(ErsiliaBase):
    '''
    Ersilia Model class
    This is the main used to perform operations on models such as serve and predict   

    Attributes:
        model (str): slug of model
        save_to_lake (bool): flag that determines whether to cache model predictions or not 
        service_class (str): contains the service class
        config_json (str): contains path to json configuration file
        credentials_json (str): contains path to json credentials file
        verbose (bool): flag to enable or disable verbose output
        fetch_of_not_avalible (bool): flag to enable or disable fetch operation

    '''
```

![image](https://user-images.githubusercontent.com/98670206/164220132-d2a4746f-c928-4499-a12f-7118557c100b.png)

**Comment by Amna-28** [comment]
### Search the scientific literature and suggest 3 new models that would be relevant to incorporate in the Hub

1. **Next-Gen QSAR Models with MolPMoFiT** 
    [Inductive transfer learning for molecular activity prediction: Next-Gen QSAR Models with MolPMoFiT](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00430-x)

2. **Mycobacterium tuberculosisIn Vitro Activity Prediction and Target Visualization**
    [Machine Learning Models for Mycobacterium tuberculosisIn Vitro Activity: Prediction and Target Visualization](https://pubs.acs.org/doi/abs/10.1021/acs.molpharmaceut.1c00791)

3. **Novel MAO-B Hit Inhibitors Using Multidimensional Molecular Modeling for Prediction of Therapeutic Activity, Pharmacokinetic and Toxicity Properties**
    [Proposing Novel MAO-B Hit Inhibitors Using Multidimensional Molecular Modeling Approaches and Application of Binary QSAR Models for Prediction of Their Therapeutic Activity, Pharmacokinetic and Toxicity Properties](https://pubs.acs.org/doi/abs/10.1021/acschemneuro.8b00095)
