### ISSUE TITLE
✍️ Contribution period: <Chisom Nwankwo> 

### ISSUE THREAD

**Issue by ChisomNwankwo** [ersilia-os/ersilia#1042]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by ChisomNwankwo** [comment]
link to my git repository : https://github.com/ChisomNwankwo/Classification-of-hERG-blockers-and-nonblockers.git

**Comment by GemmaTuron** [comment]
Hi @ChisomNwankwo 

Please update us here explaining the W2 tasks you are working on once you have time, thanks!

**Comment by DhanshreeA** [comment]
Hi @ChisomNwankwo I do not see any work done since Week 2. Please let us know if you wish to continue otherwise we can close this issue, seeing as we are in the last week.

**Comment by DhanshreeA** [comment]
Closing due to no response from @ChisomNwankwo
