### ISSUE TITLE
✍️ Contribution period: Ana K

### ISSUE THREAD

**Issue by kiselyochek** [ersilia-os/ersilia#1043]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by kiselyochek** [comment]
**Why I want to be an Ersilia Intern**

Ever since I was little, I was fascinated by technology. My neverending curiousity led me into the field of computer science. When I was 14, I was accepted into a programming learning program hosted by Yandex, the plan for which is compiled by leaders of the industry in Russia and taught by some of the best computing educators in the area. The course involved multiple personal projects and introduced the students to fundamental concepts of Python while encouraging constant practice and participation in various hackathons and competitions. 

As I embarked on my programming journey, I discovered my passion for data and ways it can be manipulated and analyzed through programming, which is how I was introduced to the field of data science. Back in Russia, I participated in an AI Intensive that taught me various concepts of machine learning and data analysis. At the end of the course, I trained a model to categorize goods for a local marketplace, which was an incredibly exciting project to work on. This project only reinforced my decision to pursue data science as a career.

A few years ago, I moved to the US to pursue my undergraduate degree and become an expert in the field. During researching internships, I stumbled upon Outreachy, and its mission aligned with what I believed in. I have a great appreciation for this program due to its emphasis on minority inclusion, and, after years of being antagonized back in my home country for being queer and having a liberal mindset, this opportunity made me feel seen, especially in such a male-dominated field as technology. I eagerly applied and was ecstatic to be accepted into the first round. 

As I started picking the projects I want to contribute to, Ersilia piqued my interest due to its mission to help people. I have always wanted to leave an impact with my work, and being a part of a minority group, I want to be able to do something great for those who need it most. I am extremely driven by both learning and cause, so being able to contribute to a project such as this not only lets me fulfill my purpose, but also to challenge myself. I have never worked on projects this big before, and there are a lot of unfamilar concepts I am yet to grasp. I believe that being accepted as an Ersilia intern will allow me to greatly expand my knowledge and apply it to solve a real-world problem while fulfilling both my spiritual and educational goals, allowing me to push the boundaries of my learning.

**Comment by GemmaTuron** [comment]
Hello @kiselyochek 

You have not registered your application in the Outreachy website, to focus on those applicants who wish to make a final application, we will close this issue. Please let us know if you registered with a different name.

**Comment by kiselyochek** [comment]
Hello @GemmaTuron,

I have registered on the Outreachy Website during the first week, please see the screenshot below to confirm. Could it be that my Outreachy name is displayed as "Ana K" as opposed to my full name in the repo?

![image](https://github.com/ersilia-os/ersilia/assets/66618160/08148766-0dd3-4037-928a-1005862ea445)

**Comment by GemmaTuron** [comment]
Hi @kiselyochek 

Thanks, I have found your registration. Please, as we asked on Slack, change your name on the issue for the name you use in Outreachy, so we can more easily keep track of applicants.
Let us know once week 2 tasks are ongoing so we can provide feedback.

**Comment by DhanshreeA** [comment]
Hi @kiselyochek checking in - do you wish to continue? We would not be able to provide technical feedback on your work at this point. However you can still submit a final application with us if you so wish. Thank you.

**Comment by kiselyochek** [comment]
> Hi @kiselyochek checking in - do you wish to continue? We would not be able to provide technical feedback on your work at this point. However you can still submit a final application with us if you so wish. Thank you.

Hi, yes, I apologize for not documenting my work on Github. I will make sure to submit all of documentation and work process before the final application period.
