### ISSUE TITLE
✍️ Contribution period: Ishita Pathak 

### ISSUE THREAD

**Issue by IshitaPathak** [ersilia-os/ersilia#1044]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [x] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by IshitaPathak** [comment]
## Week 1 TASK ✅

> Install and test the Ersilia Model Hub

<img width="329" alt="Screenshot 2024-03-12 213405" src="https://github.com/ersilia-os/ersilia/assets/75848598/1d4786c8-06d8-478e-b64b-91adee20cbd7">

<img width="321" alt="Screenshot 2024-03-12 213551" src="https://github.com/ersilia-os/ersilia/assets/75848598/6469494a-53aa-42b7-a24b-2e78252ba571">

<br>
<br>

> While completing the task I stuck at a point when I was  testing ersillia model `eos3b5e` , where the container is always in exited status. I asked about this in Slack channel, where mentor helped me resolve the issue. 

<img width="439" alt="Screenshot 2024-03-12 210909" src="https://github.com/ersilia-os/ersilia/assets/75848598/f4d0b082-6b4e-462b-b67d-93d3c62d6e33">
<br>
<br>
I truly appreciate the supportive environment within our community, where both mentors and peers are always ready to lend a helping hand.

**Comment by GemmaTuron** [comment]
Hi @IshitaPathak 
Please update here w2 tasks that you have marked as done, so we can provide feedback

**Comment by IshitaPathak** [comment]
## MY PROGRESS AND LEARNINGS 

So far, I've learned valuable skills to contribute to Ersilia. It's been an exciting journey

* Learned Docker by Dockerized a simple app [GitHub repo here](https://github.com/IshitaPathak/Dockerization-node.git), learned about 
    * Dockerfile
    * Caching layers
    * Publishing to Docker Hub.
* Explored Docker Compose, understanding port mapping and managing environment variables.

I have a strong foundation in Python, but my exposure to libraries was somewhat limited. To address this, I've invested some time in learning some libraries [GitHub repo here](https://github.com/IshitaPathak/Data-Analysis.git) like Pandas and NumPy. By today, I aim to complete my understanding of Matplotlib and other libraries essential for my current task. Following this, I move forward with the next part of Week 2 tasks.

**Comment by IshitaPathak** [comment]
## Week 2 Task

* Chose the hERG model "eos30gr" from the list of suggested models in GitBook.
* Read the [publication](https://acrobat.adobe.com/id/urn:aaid:sc:ap:3cca2c36-6b4f-478a-996c-7f77423e819e) to better understand the model.
#
###  About hERG
  
  • hERG is a gene encoding the hERG potassium ion channel, pivotal for heart electrical activity.
  • Analogously, hERG acts as a gatekeeper in heart cells, regulating potassium ion flow to manage heart rhythm via electrical signals.
  • A functional hERG channel maintains a regular, healthy heartbeat, but issues can lead to abnormal heart activity, such as arrhythmias or long QT syndrome.
#
* Ensured model functionality on my system by downloading, serving, and running it using the following commands:

```
ersilia -v fetch eos30gr
ersilia serve eos30gr
ersilia -v api run -i "CCCC" 
```
Upon fetching the eos30gr model, I encountered consistent null output for the smiles prediction. Since the models are regularly updated, I tried the command `ersilia -v fetch eos30gr --from_github` to fetch the latest code from GitHub, which resolved the issue seamlessly.
```
ersilia -v fetch eos30gr --from_github
ersilia serve eos30gr
ersilia -v api run -i input.csv -o output.csv
```
I use the reference_library.csv provided on the #data channel in Slack as input dataset. The input and output files can be found at [input.csv](https://github.com/IshitaPathak/model-validation-eos30gr/blob/master/data/input.csv) and [output.csv](https://github.com/IshitaPathak/model-validation-eos30gr/blob/master/data/output.csv), respectively.

 ### Output I get for single SMILES
<img width="287" alt="Screenshot 2024-03-22 140337" src="https://github.com/ersilia-os/ersilia/assets/75848598/f46b7430-53b8-4887-a315-6f97e1a8a66e">


#


* Next I understood the repository structure from the provided [example](https://github.com/GemmaTuron/model-validation-example/tree/main) and created the [GitHub Repository](https://github.com/IshitaPathak/model-validation-eos30gr/tree/master) that has all necessary files.

**Comment by GemmaTuron** [comment]
Hi @IshitaPathak 

Thanks for the explanation. I suggest the following timeline:

- [ ] Finish week 2 tasks, including a good explanation of what you have done and your conclusions
- [ ] Start working on your final application

As the application period is coming to an end and we want to ensure applicants have time to prepare strong applications please do not tackle Week 3 tasks and focus on the final application instead. Thanks!

**Comment by IshitaPathak** [comment]
Thankyou so much @GemmaTuron for the guidance and timeline. I'm committed to finishing the week 2 tasks and starting work on my final application right away.

**Comment by IshitaPathak** [comment]
I selected a list of 1000 molecules `reference_library.csv"`shared in Slack (data channel). To make sure the data was consistent, I standardized this SMILES representations using RDKit, a tool for handling chemical data. Sometimes, RDKit encounters invalid SMILES, resulting in NaN values. In such cases, I removed those invalid entries from the dataset.

Next, I obtained the InChIKey representation for all the standardized SMILES. This information was used to create a DataFrame containing the processed SMILES and their corresponding InChIKeys. Now, this DataFrame had two columns: "smiles" and "InChI_key." I then saved this processed data as a file named `processed_input.csv.`

After cleaning the data, I ran the model on the processed dataset using following commands
```
ersilia -v fetch eos30gr --from_github
ersilia serve eos30gr
ersilia -v api run -i processed_input.csv -o output.csv

```

The output generated by the model is saved in the file `output.csv` located in the data directory

**Comment by GemmaTuron** [comment]
Hi @IshitaPathak 

Thanks for the explanations, much celarer now, and good job on doing a PCA as well!
Please move onto preparing your final application, many thanks!

**Comment by IshitaPathak** [comment]
Thankyou soo much @GemmaTuron. I really appreciate your time and feedback. Started working on final application.

**Comment by IshitaPathak** [comment]
## WEEK 4 TASK ✅
* Created final application and received feedback from mentor.
* Submitted the final application on the Outreachy website.
