### ISSUE TITLE
✍️ Contribution period: Binita Dhakal

### ISSUE THREAD

**Issue by binitadkl** [ersilia-os/ersilia#1048]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by binitadkl** [comment]
Dear Ersilia Open Source Initiative and Outreachy Team,

I am a strong candidate as an intern position at Ersilia due to my diverse background and the skills I have been learning and mastering over the course of my personal and professional development. My name is Binita Dhakal from Nepal (Global South). I am currently pursuing my undergraduate degree in Computer Science from University of Southern Mississippi (USM) in the United States. I come from a low-income family background and am a first generation college student. I am a freshman in my second semester studying at USM with full scholarships for four years. My significant experience in python programming language, intermediate knowledge about data science and newly discovered passion in Artificial Intelligence and Machine Learning since my first semester has given me a familiarity of how I can contribute, learn and work under the Ersilia Open Source Initiative.

Being from the warm and humid temperature of Nepal, where infectious disease like malaria is very common because of mosquitoes, I was able to connect with Ersilia’s mission to eradicate infectious disease through sustainable research and various means from the very first day. Although I was able to learn and excel in python programming completely via online resources when I was in high school, I noticed the limited resources about science in my home country compared to the global world. This encouraged me to study in global world education where I can get access to global resources. After getting very good financial support from the university, I came to the United States with the hope to hone my knowledge and skills. I am able to take different classes such as economics, wellness, chemistry when also majoring in computer science have helped me identify my passion in AI and ML with science. Currently, as a second semester student, I am also learning Machine Learning under USM Al and ML professor’s guidance where I have started learning from concepts like reinforcement learning. Continuing my study of ML this semester, in the coming summer I am willing to learn more about ML with AI through Ersilia.  

Before coming to the United States for education, I took part in several competitive opportunities. I believe that was possible because of my hard work, dedication, passion and most importantly by being around like-minded people who believed in me whether it was virtual projects like Incubate Nepal or physical programs like Glocal Teen Hero Nepal. During COVID-19 pandemic time, I enhanced my python programming skills exponentially. I used to work as a student data researcher and programmer in an organization initiated by MIT and Harvard graduated students. I used my programming skills there in an open-ended project to analyze data, to make graphs and simultaneously developed my collaborative team-work skill. From this program, Incubate Nepal, I became familiar with data in a real-world based project other than academic for the first time and from that time, it became a part of me as I became sure that my passion for data is life long until my last breath. I was also awarded as Nepal's teenage changemakers in 2022 by Glocal Teen Hero Nepal organization because of my impactful work in society for raising awareness about women’s rights and against violence. 

As I learned programming skills through online resources, I value open resources available on the internet very much. Outreachy being a platform for open source projects is one of the best access to students like me to learn and grow. Its value, mission, and resources motivates and inspires me to learn more and share what I learn whether for a group of people or whether it is just a person. Personally, Outreachy has also made my goal to give back to my country and world more stronger than ever, making me believe that giving back to society, and country and learning from it never should be limited. I would be honored to have the opportunity to work alongside a like-minded team as an intern, a position that would enable me to use my best skills to contribute and grow making a meaningful contribution in the urgent health issues in developing countries like Nepal.

Sincerely, 
Binita Dhakal

**Comment by Adhivp** [comment]
Hi @binitadkl  , I can see that you are active on slack, but no tasks completed. If you face any difficulties completing your tasks please let know in slack.

**Comment by GemmaTuron** [comment]
@binitadkl 

Please if you mark tasks as completed, report here updates so we can provide feedback. Let us know when you are ready to continue

**Comment by DhanshreeA** [comment]
Closing due to no response from @binitadkl
