### ISSUE TITLE
✍️ Contribution period: <Anonymous> 

### ISSUE THREAD

**Issue by Anonymou4** [ersilia-os/ersilia#1049]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by DhanshreeA** [comment]
Hi @Anonymou4 this is a final warning from our side. Please update your name to the name you have provided in your Outreachy application, both here and on Slack. Otherwise we would not be able to consider your application.

**Comment by DhanshreeA** [comment]
Hi @Anonymou4 please consider this a final warning from our side. Please update your name to the name you have provided in your Outreachy application, both here and on Slack. Otherwise we would not be able to consider your application.

**Comment by Anonymou4** [comment]
@DhanshreeA thanks for the Update... I was just using the name which is publicly visible on my profile for outreachy...

or this isn't the Name your speaking of?

**Comment by DhanshreeA** [comment]
Hi @Anonymou4 , understood, thank you for letting us know.

**Comment by Anonymou4** [comment]
My desire to work with Ersilia stems from my love for data science as a tool for creating positive impact in our world of today. Added to my desire for data science is the motivation of my dad's passing from a deadly disease which couldn't be easily diagnosed due to the fact that my country isn't technologically advanced which made his treatment not prompt.

After being selected and going through the project, Ersilia provided a perfect fit as it meant I could also help to safeguard other peoples life's by contributing to it's course of providing models to help aid the medical sector. 

I believe I am competent and open to learning new things and I'll love to embark on this journey with Ersilia community.

**Comment by Ajoke23** [comment]
Hi @Anonymou4. I noticed you're yet to update your week 2.
Are you experiencing any challenges regarding the week 2 task?
If yes, comment your issue here. I will glad to put you through.

**Comment by GemmaTuron** [comment]
> @DhanshreeA thanks for the Update... I was just using the name which is publicly visible on my profile for outreachy...
> 
> or this isn't the Name your speaking of?
> 
> ![image](https://private-user-images.githubusercontent.com/162900755/311625898-b5627349-b614-4490-9655-b71037850bda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDI0NTcsIm5iZiI6MTcxMDQwMjE1NywicGF0aCI6Ii8xNjI5MDA3NTUvMzExNjI1ODk4LWI1NjI3MzQ5LWI2MTQtNDQ5MC05NjU1LWI3MTAzNzg1MGJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwNzQyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzAzODIyZWM3N2I5MDU3MzhkZTUxN2YyNWMzN2Q0Y2Q3YjUzY2FlOTdjZDBjMjUzNDg4MjY2ZDU3YjU3MTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wl3GExS7cS4VPzNPPysJO40diE0jfmHZogBomnGp1-8)

Hello, 
Outreachy requires your real name, are you confirming your name is Anonymous? If not, please change it to your real name. Thanks.

**Comment by Anonymou4** [comment]
Hi @GemmaTuron, My real name is available on outreachy... this is the nickname that outreachy allows for applicants to use which I have on here and it is also the name publicly visible on outreachy as I earlier notified the mentor @DhanshreeA ... That not withstanding my legal names are Muluh Derick Awa.

**Comment by Anonymou4** [comment]
Sorry for the delay in updating my repository... My country was affected by the fiber breakdown and although things aren't back to normal, it's a lot better now.

**Comment by GemmaTuron** [comment]
Hi @Anonymou4 

Thanks for the clarification on the names. Sorry to hear you were facing internet issues. Is the repository now up to date for revision?
