### ISSUE TITLE
🐛 Bug: Pandas slows down build time for ersiliaos/base image

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1054]
### Describe the bug.

The [action](https://github.com/ersilia-os/ersilia/actions/workflows/ersilia-base-image-to-dockerhub.yml) building and pushing ersilia's base image (ersiliaos/base) takes disproportionately long to run. Although this could be due to any number of things, for example the runner having a modest amount of resources, however the primary culprit seems to be installation of pandas during ersilia install. It appears that instead of downloading a wheel, pip is [downloading the source](https://github.com/ersilia-os/ersilia/actions/runs/8231029101/job/22505530889#step:9:7239) for this version of Pandas, and then pip takes forever to [build a wheel](https://github.com/ersilia-os/ersilia/actions/runs/8231029101/job/22505530889#step:9:7364) for Pandas. As a consequence, what used to take <20 mins for building this image, now ends up taking ~1h26 minutes. 

This is a low priority issue since our base image gets updated infrequently and building this image is not time critical but maybe we should look into why that's happening, and it could involve one or more of the following:
- updating base python version in this image
- maybe it is as simple as updating pip?
- upgrading pandas version, as it could be that pip is unable to find a wheel from PyPI and resorts to downloading source instead (However I haven't completely verified this)

### Operating environment

NA

**Comment by GemmaTuron** [comment]
I agree Pandas slows things down, I'd remove the dependency, as stated in the #928 :)

**Comment by miquelduranfrigola** [comment]
https://github.com/ersilia-os/ersilia/blob/376f886da37e3e45c2a0a0a71f700bc94b0deea1/ersilia/core/tracking.py#L3

Pandas here is only used for reading CSV files. We definitely need to use `csv` library and remove pandas dependency

**Comment by DhanshreeA** [comment]
#1131 should resolve this hopefully
