### ISSUE TITLE
✍️ Contribution period: NAKACWA OLIVIA 

### ISSUE THREAD

**Issue by NakacwaOlivia** [ersilia-os/ersilia#1058]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [X] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by GemmaTuron** [comment]
Hello @NakacwaOlivia 

Please do not tick tasks when they are not completed. We have not seen your motivation statement nor your application on the outreachy website. The project is now closed to new applicants, so we will close this issue unless you are working on it.

**Comment by NakacwaOlivia** [comment]
### **Motivation Statement**
**_Nakacwa Olivia_**

**## Why would I want to join Outreachy?**
Outreachy provides three-month internships with free and open-source software projects, providing practical experience, mentorship, and networking opportunities. It promotes inclusivity, diversity, and problem-solving skills, fosters a supportive community, and enhances technical skills through real-world projects.
## **Why do I want to join Ersilia, in particular?**
By joining EOSI, I will be able to directly support global health initiatives, especially in the battle against infectious and neglected illnesses, which will improve public health outcomes all throughout the world. EOSI promotes accessibility, transparency, and cooperation in research by advocating for open science principles.
##**My background**
I am a finalist student at Makerere University, offering a bachelor's degree in computer engineering. I am specifically interested in AI, but currently, I am a data scientist and Python developer. I am an enthusiastic AI engineer.
## **How will interning with Ersilia help improve my skills?**
Working with EOSI provides excellent chances for professional advancement, including project management, data science, and AI/ML methodologies. Working with a varied and global community of volunteers, partners, and researchers can also promote networking possibilities for personal and professional development. EOSI provides a platform for interacting with cutting-edge AI/ML models and tools because it is focused on utilising these technologies for biomedical research.
## **What are your plans during and after the internship?**
**# During Internship**
Establish clear goals for my career and learning objectives. To make sure the goals are in line and to get advice on how to reach them, talk about the objectives with the mentors and supervisors. Engage in active participation in project activities, team meetings, and discussions. Take the initiative to offer suggestions, pose queries, and look for feedback in order to further your understanding and add significant value to the team's efforts.
Benefit from the organisation's educational options, which include training sessions, workshops, and mentorship programmes. Experiment with new tools, methods, and technologies that are pertinent to your work to increase your knowledge and skill set. Make relationships with mentors, coworkers, and other interns at Ersilia.
# **After Internship**
Reflect on my internship experience, including what I learned, the problems I overcame, and opportunities for development. Analyze my performance in relation to my initial objectives, and note any lessons that can be applied to my future work. Add the new abilities, experiences, and successes I obtained during the internship to my resume. Ask my mentors or supervisors for their opinions on how I performed during the internship. Make use of their observations to pinpoint my areas of strength and growth, and build my future professional goals around their recommendations. Continue expanding on the abilities and information I gained throughout the internship, as well as investigating several career options and pathways that fit my objectives, interests, and experiences from the internship.

**Comment by Ajoke23** [comment]
Hi @NakacwaOlivia. I noticed you haven't commented regarding the progress of your task.
Are you facing any challenges regarding the task?
If you need help, pls comment here. I will be glad to help you out.

**Comment by GemmaTuron** [comment]
Hi @NakacwaOlivia 

I do not see your application to Outreachy, the project closed to new contributors on Tuesday 12th March.

**Comment by NakacwaOlivia** [comment]
@Ajoke23 I am doing well, i have been doing some review on molecules

@GemmaTuron, Well, I was going to record my contribution this weekend after finalising the review i was doing on molecules. 
Does it mean that I cannot continue with the application anymore?

Thank you both for the check up.

**Comment by Ajoke23** [comment]
> @Ajoke23 I am doing well, i have been doing some review on molecules
> 
> @GemmaTuron, Well, I was going to record my contribution this weekend after finalising the review i was doing on molecules. 
> Does it mean that I cannot continue with the application anymore?
> 
> Thank you both for the check up.

Any success regarding that. The mentors dropped an important information regarding timeline of task. Pls kindly check slack specifically the general channel

**Comment by GemmaTuron** [comment]
Hi @NakacwaOlivia 

I am sorry but the project is closed to new contributors since March 11th, so I would suggest you focus your efforts on a project that is still looking for candidates.
Thanks for your interest and your understanding

**Comment by NakacwaOlivia** [comment]
Thank you so very much everyone
