### ISSUE TITLE
Outreachy Documentation Project: victorabba

### ISSUE THREAD

**Issue by victorabba** [ersilia-os/ersilia#106]
Applicant: @victorabba 
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improving the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the  [slack](https://app.slack.com/client/T038M82LJES/C038TTEGPD0) channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [ ] Create a README file with the name <README_yourname.md> under the /documentation folder
- [ ] Link the #PR in a comment under this issue
- [ ] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template for a  short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [x] Test one model
- [x] Add a screenshot under this issue showing the model running in your computer
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [x] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [x] Link the #PR in this issue
- [x] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by victorabba** [comment]
There are a lot of scientist and researchers that are not technically inclined especially  in the programming field. This is a huge limitation as most medical  research works deals with analysis of historical data which is required to design the predictive model. 
Ersilia could help  eliminate this huddle by designing models that requires little or no programming experience. This will save the researcher a lot of resources outsourcing the task. 

The potential ability of the Ersilia model in predicting and preventing future disease occurance in an individual cannot be overemphasized. For instance the incorporation of a machine learning model capable of predicting wether an individual is potentially diabetic or not is quite possible since such a model is built using prognosis data of several patients. Such technique can be applied to the prediction of heart diseases. 

I believe the Ersilia model is the future of AI in medicine.

**Comment by victorabba** [comment]
I made the 'slack' word a link and also modified the project name.

**Comment by GemmaTuron** [comment]
Hi @victorabba 
You have already made some previous contributions, could you check how @ifeoluwafavour has linked them in her github issue and do the same? This way we have all contributions in one space.
Thanks!

**Comment by victorabba** [comment]
Initial tasks:

I added a [contributing guideline](folder.https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTION.md) for contributors.

2 I created a step by step process 
 for installing the Ersilia model in a windows operating system. I used the Oracle virtual box system to install the Ubuntu. The file is present in the [documentation folder](https://github.com/ersilia-os/ersilia/blob/0945fbd6db6c022bd452817e57248d6b3bfb1e93/documentation/victor_windows.md)

3. I modified the template for a fixing a [bug issue](https://github.com/ersilia-os/ersilia/issues/24#issue-1182396154)

4. I added a question to [feature request](https://github.com/ersilia-os/ersilia/issues/25#issue-1182401431)

5. In the [Outreachy documentation project] (https://github.com/ersilia-os/ersilia/issues/106#issue-1190986405)
I made the 'slack' word a link and also modified the project name.

**Comment by victorabba** [comment]
Hi @GemmaTuron , I added some contents to my file containing the Ersilia installation steps using Windows. I've also created a pull request for it, please review and let me know if there are any other changes required.

**Comment by GemmaTuron** [comment]
Hi @victorabba thanks for linking your work here. 
The WSL installation is very detailed, but I would appreciate if you use markdown formatting to make it easier to follow (for example, use titles and subtitles with the ### ). The steps are really detailed so perhaps you could divide them in sections (Installation of Oracle, Installation of Ubutnu, Installation of Dependencies)

Like I commented in @ifeoluwafavour 's work, state somewhere that it does not matter if the dependencies are installed in windows they need to be installed again in the virtual box

thanks!

**Comment by victorabba** [comment]
Thanks for the corrections @Gemma. I will implement them right away.

**Comment by victorabba** [comment]
Current tasks:
1 Blogpost for the [Ersilia 2021-2023 strategic plan](https://docs.google.com/document/d/1rUwg7aoDGgteAw-BpxA0yFMQp-JCQMq57zdVmBEg5KQ/edit?usp=drivesdk).

**Comment by victorabba** [comment]
![ersilla result 1](https://user-images.githubusercontent.com/97383086/161992865-b8a47258-cc1f-49c0-a64e-4923b3779d23.png)

**Comment by victorabba** [comment]
![ersilla result 2](https://user-images.githubusercontent.com/97383086/161993140-f1f96326-46d6-4817-a7e9-1a6aa045477a.png)

Result of molecular mass of Aspirin.

**Comment by GemmaTuron** [comment]
Hi @victorabba 

I cannot access the blogposts, can you revise permissions? thanks!

**Comment by victorabba** [comment]
Ok. You can try now I have reviewed permissions.

**Comment by victorabba** [comment]
Class ErsiliaModel(ErsiliaBase):
""" Defines the instance of the ersilia model class and fetches the model""".

def is_valid(self):
""" Checks if the model is valid""".

def api(
        self, api_name=None, input=None, output=None, batch_size=DEFAULT_BATCH_SIZE
    ):
""" Defines the model  API name, input, output and size""".

def api_task(self, api_name, input, output, batch_size):
""" Defines the tasks of the model API"""

def serve(self):
""" Serves the model""".

def close(self):
"""Closes the model""".

**Comment by victorabba** [comment]
Graphic material

1 An image slide to explain Ersilia's mission and vision. 
https://docs.google.com/presentation/d/1zKa6SBnGXrmIa-vwR87I8HGK00DAZ2IO/edit?usp=drivesdk&ouid=108466039633231002874&rtpof=true&sd=true

**Comment by adeolaadedeji** [comment]
Hi @victorabba i was going through your image and i noticed that the content was overlapping the slides. Kindly re-check.

**Comment by victorabba** [comment]
@adeolaadedeji what app are you using to view it? I'm using a Wps app and it's perfectly fine.

**Comment by victorabba** [comment]
It's not a doc file. It's a ppt file. It's uploaded to Google drive but
opens with wps or any app that has PowerPoint.

**Comment by ifeoluwafavour** [comment]
Well done Victor!

**Comment by victorabba** [comment]
Thanks @Ife

**Comment by GemmaTuron** [comment]
Hi @victorabba,

I am revising all your work, thanks for the effort you are putting into this.

- Strategic plan: I really like that you use the KPI term, well thought. Some minor changes: I would try to rephrase the " we tend to" for something more clear, we accomplish, we aim to... and I know its boring but try to find a different sentence each time rather than repeating the same. Many times writing requires to find two or three ways to say the same. And revise the acronyms, the best is to add them the first time they appear, for example Low and Middle Income Countries (LMIC) and then simply use the same throughout the text.
- AI in biomedical Research: _Researchers at the  Ersilia institute have developed a model which can predict whether a substance has antibiotic components or not._ Can you make this more general? we do not only work on antibiotics but in general try to speed up drug discovery against infectious diseases
- The twitter post is good but could you try to make it more catchy? People only spend seconds looking at Twitter! Somthing like: _We have a new model in the Hub! ..._ Also if you need you can use more than one post (if you do not have twitter, these are called threads, so there is a main message and then a few hidden, with less important messages. All limited in length)
- Good its the first newsletter template I am revising! Could you separate between users and then funders, or how much we have raised? Something about how many volunteers work with us would be nice

Hope you find some of these comments helpful, take your time to incorporate them and let us know

**Comment by victorabba** [comment]
Thanks @Gemma, I will make the changes.

**Comment by dchidindu5** [comment]
Hey @victorabba I actually a little correction on a document you created victor_windows.md #181
a typo where **they** was used instead of **the**.

**Comment by victorabba** [comment]
Thanks @dchidindu5

**Comment by victorabba** [comment]
Hello @GemmaTuron , I have implemented all the changes.

**Comment by loweyvana** [comment]
Great job @victorabba  so far. I really love your blogpost on AI in medical research. Very insightful.

**Comment by victorabba** [comment]
Thanks @loweyvana

**Comment by GemmaTuron** [comment]
Hi @victorabba 

You have done a lot of work, I am loving the video, very explanatory!
I think you are  more than ready to submit your final application, thanks for the hard work you put into it!

**Comment by victorabba** [comment]
Thanks @Gemma. I'm pleased to hear that.

**Comment by tracycod3r** [comment]
Great tutorial @victorabba

**Comment by victorabba** [comment]
This issue has been closed.
