### ISSUE TITLE
[🐕 Batch]: Use Mamba instead of Conda environments in Ersilia

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1062]
### Summary

Just one word: Speed.

### Objectives

Conda is painfully slow, and Mamba is increasingly becoming popular as a significantly faster alternative to Conda, so much so, it now ships as a configurable solver with Conda as well. So either we can use Mamba entirely, or at the very least shift to using Mamba as a default solver in model environments that Ersilia creates. 

### Documentation

https://micromamba-docker.readthedocs.io/en/latest/quick_start.html#running-commands-in-dockerfile-within-the-conda-environment

**Comment by anshikavashistha** [comment]
May I work on this issue @DhanshreeA ?

**Comment by DhanshreeA** [comment]
Hey @anshikavashistha thank you for your comment. This issue is currently only under discussion, and will affect several key areas within ersilia. So we might not open it to outside contributions just yet.

**Comment by anshikavashistha** [comment]
No problem @DhanshreeA 
I would love to contribute to any beginner level issue.If there is any issue where I could contribute,I would love to work.Please let me know.

**Comment by miquelduranfrigola** [comment]
Update based on discussion:
 - Conda-pack does not work with mamba
 - We should (if anything) use libmamba within conda.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

I think we have made progress on that specially related to ersilia-pack. Can you summarise the status here, and next steps?

**Comment by DhanshreeA** [comment]
At present all our actions and models end up using the latest version of conda which comes prebundled with libmamba as the default solver. So this has been implicitly handled.
