### ISSUE TITLE
✍️ Contribution period: Anushka Srivastava

### ISSUE THREAD

**Issue by anushk4** [ersilia-os/ersilia#1066]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by anushk4** [comment]
## Motivation statement

Dear Ersilia Team
I am writing this to express my sincere interest in contributing to Ersilia. I was impressed by Ersilia's mission to develop AI/ML tools to strengthen research capacity for infectious and neglected diseases. It made me eager to be a part of this community.

My current skill set in data analysis, programming, and machine learning, honed through academic coursework and practical projects, gives me confidence in my ability to make a meaningful contribution while being a part of Ersilia. I am proficient in Python and have sufficient experience working with libraries like TensorFlow and PyTorch. I have worked on a handful of ML projects where I had to first use a pre-trained model, and then train a model to build an Image Classifier which provided me a deep understanding of Deep Learning and Neural Networks and the various CNN architectures present. Working on these initial projects has equipped me with the basics of Machine Learning which further provides a base for me to build up and grow my skills.
My experience in data science courses like Practical Bioinformatics provides me with necessary insight into the challenges and possibilities when the field of technology intersects with the field of biology. This has further fueled my passion to use my skills to make this world a better place.

I am committed to constantly developing my skills and actively participating in every opportunity I get. Participating in this internship at Ersilia represents an invaluable opportunity to develop my technical skills further, gain hands-on experience in real-world ML projects, and contribute to a cause of immense significance for global health. 

During the internship, I am committed to immersing myself fully in Ersilia's projects, collaborating closely with the team to work on the existing issues, and improving the existing model by identifying potential issues, if needed.

After the internship, I look forward to making use of the skills I learned while being a part of Ersilia and strive to make a difference in the real world with the help of machine learning, which expands beyond healthcare.

I would like to conclude by mentioning that I am an ambitious, hard-working, and quick-learning individual. These qualities, along with my technical qualifications, make me a strong candidate to be a part of this organization. I am confident that my passion, skills, and dedication will make a positive impact on the organization's initiatives.

**Comment by anushk4** [comment]
Hi @DhanshreeA
Please give me feedback for my task 1 of week 2. The github link has been attached
https://github.com/anushk4/model-validation

**Comment by anushk4** [comment]
Hi @GemmaTuron and @DhanshreeA
I have completed my tasks for week 2. The GitHub link has been attached.
https://github.com/anushk4/model-validation.git
I have used this [research paper](https://pubs.acs.org/doi/full/10.1021/acs.jcim.8b00769) and Table S7 as the dataset for the task
Kindly provide feedback on my task so that I can improve upon the feedback and proceed with the week 3 task.
Thank you

**Comment by DhanshreeA** [comment]
Hi @anushk4 thank you for your interest in Ersilia. Unfortunately, we have closed the project for contributions to new Outreachy applicants on 11th March, 2024 and cannot review your application at this time. Please try to contribute to projects that are still accepting contributions.

**Comment by anushk4** [comment]
Hi @DhanshreeA thank you for your response. As far as I remember, I had joined the Ersilia community when it was still listed as open on the Outreachy website. This [message](https://ersilia-outreachy-s24.slack.com/archives/C06K0999MMW/p1710745808696999?thread_ts=1710745808.696999&cid=C06K0999MMW), which said that the project has been closed, was posted days after I had joined and already started working on the tasks. Any clarification regarding this would be highly appreciated.

**Comment by GemmaTuron** [comment]
Hi @anushk4 

I see you registered your application, the slack messages are not a good indication of dates as we post many times a day there - in any case, if you wish to continue with the application given the work you have already done, these are a few pointers:

- [ ] Use a scatter plot to better visualise the results and model bias
- [ ] Update the README file with your work and conclusions on Week 2 tasks
- [ ] Start working on your final application

Given the short time left, let's skip w3 tasks and move to cleaning up the work and writing the final application!

Thanks

**Comment by anushk4** [comment]
Thank you @GemmaTuron . I will start working on the suggestions

**Comment by anushk4** [comment]
Hi @GemmaTuron 
I have made changes according to your feedback
https://github.com/anushk4/model-validation
#### Changes made
- Added a scatter plot for better visualisation in the notebook 00 and notebook 01
- Updated the markdowns of both the notebooks for explaining the results from the graphs
- Updated the README by adding the summaries of the conclusion of week 2 tasks

**Comment by GemmaTuron** [comment]
Hi @anushk4 

Thanks for the work and for adding the details in the readme file, and for the graphs!
Please go ahead and work on your final application
