### ISSUE TITLE
🐛 Bug: Investigate "No space left on device" in our pipelines

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1067]
### Describe the bug.

A number of our model pipelines, typically in the "upload model to dockerhub" stage fail because of "No space left on device".
Exhibits:

- https://github.com/ersilia-os/eos42ez/actions/runs/8191687245
- https://github.com/ersilia-os/eos18ie/actions/runs/8191708280
- https://github.com/ersilia-os/eos31ve/actions/runs/8192443412
- https://github.com/ersilia-os/eos9tyg/actions/runs/8192501865
- https://github.com/ersilia-os/eos4tcc/actions/runs/8235442007
- https://github.com/ersilia-os/eos30f3/actions/runs/8233315503
- https://github.com/ersilia-os/eos4x30/actions/runs/8232877335
- https://github.com/ersilia-os/eos7w6n/actions/runs/8250745999
- https://github.com/ersilia-os/eos4u6p/actions/runs/8251316509

### Describe the steps to reproduce the behavior

Go to any one of the jobs above and re run. I tried to run these jobs when no other jobs were running on our runners and yet they failed.

### Expected behavior.

These jobs should pass.

### Operating environment

Runner OS

### Additional context

Potentially useful resources:

- https://github.com/actions/runner-images/issues/1860
- https://github.com/orgs/community/discussions/26351
- https://github.com/actions/runner-images/issues/2875
- https://github.com/orgs/community/discussions/25678

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 
I am highlighting this model: https://github.com/ersilia-os/eos9taz/actions as I need it for chemsampler but it is not passing either :)

**Comment by DhanshreeA** [comment]
@GemmaTuron , I've pushed it manually for now to unblock you. However there's a related issue that I'm on top of: #1068 which I opened with specifically this model in mind.

**Comment by DhanshreeA** [comment]
Root Cause:  With GitHub hosted runners, one of the guarantees is getting software updates. This could mean one or all of the following frequently: runner updates, runner provisioner updates, patches to the OS on the runner, the software bundled in the OS, etc. Every such update is quite likely to eat into the disk space. For example, [here's the list](https://github.com/actions/runner-images/blob/ubuntu22/20240212.1/images/ubuntu/Ubuntu2204-Readme.md) of all the tools installed on the runner OS, that we do not need for our builds. So far there is no straightforward solution other than an aggressive disk clean up. This has been implemented at the level of the [eos-template repository](https://github.com/ersilia-os/eos-template/pull/33). While this works for now, it is not guaranteed that this issue will not come up again.
