### ISSUE TITLE
📑 Feature Request: Use Caching in our Docker workflows

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1068]
### Is your feature request related to a problem? Please describe.

A lot of our model build workflows even when they are running smoothly tend to fail because of time out. That is, the build does not finish in the default time limit of 6 hours for any job. I believe we could benefit from enabling caching such that at least the base images (ersiliaos/base, and python:3.7-slim-buster images) are cached for each model repository so we save some time from pulling and unpacking these images.

**Comment by miquelduranfrigola** [comment]
As discussed, perhaps caching is not the solution but specifying architecture-specific dependencies.

**Comment by DhanshreeA** [comment]
I'm closing this for now.
