### ISSUE TITLE
✍️ Contribution period: <Ilma Salsabil> 

### ISSUE THREAD

**Issue by crocmons** [ersilia-os/ersilia#1070]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by crocmons** [comment]
Hello Team,

I'm writing to tell you how excited I am to help Ersilia as an Outreachy applicant, especially by expanding the Ersilia Model Hub, which is a free software platform that shows off pre-trained AI and machine learning models for biological uses. I really agree with Ersilia's goal of creating AI/ML tools to help studies on neglected and contagious diseases move forward. This makes me want to be an important part of this community.

I've learned a lot about data analysis, programming, and machine learning through self-study and hands-on projects. This makes me the right person to make a big difference on the Extension of the Ersilia Model Hub project. Because I know how to use important libraries like Pandas, Numpy, and Scikit-Learn, I can make a good contribution to the growth and integration of models that have already been trained into the platform. Working on different machine learning projects, like predictive modeling and classification algorithms, has taught me a lot about machine learning methods and how they can be used in biological research.

I am deeply dedicated to always learning new things and taking part in all the chances that come my way. Joining Ersilia for this internship is a great chance for me to improve my technical skills, work on real-world machine learning projects, and make a real difference in a cause that is very important for global health.

I'm fully committed to working on the Extension of the Ersilia Model Hub project during my internship. I will be working closely with the team to solve current problems and add more features to the platform so it can better serve the biomedical research community.

After my internship is over, I can't wait to use the skills I learned at Ersilia to make a real change in the world by helping to create AI/ML solutions that aren't just for healthcare.

Last but not least, I have drive, passion, and a strong desire to learn quickly. All of these things, along with my technical skills, make me a great candidate to help Ersilia with this project. I'm sure that my dedication, drive, and skills will help the group reach its goal in a way that lasts.

Thanks for taking my application into account. I am truly thrilled about the chance to work with Ersilia and make a difference through its changing work.

Best regards, 
Ilma Salsabil

**Comment by DhanshreeA** [comment]
Hi @crocmons thank you for your interest in Ersilia. We have several strong applicants right now. Therefore, unfortunately, we have closed Ersilia to new applicants on 11th March and are unable to review new contributions at this time. I advise you to check out other projects within Outreachy that are still open to new contributors. All the best. 

I am closing this issue now.

**Comment by crocmons** [comment]
> Hi @crocmons thank you for your interest in Ersilia. We have several strong applicants right now. Therefore, unfortunately, we have closed Ersilia to new applicants on 11th March and are unable to review new contributions at this time. I advise you to check out other projects within Outreachy that are still open to new contributors. All the best.
> 
> I am closing this issue now.

@DhanshreeA yeah sure, I'm also finding that it's a bit harder for me to do it right now..so yeah, If there are any future opportunities to contribute to Ersilia or other projects within Outreachy, please do not hesitate to reach out. I will continue exploring other projects and look forward to potential future collaborations. Thank you again for your consideration. Best wishes to you and the Ersilia team.
