### ISSUE TITLE
✍️ Contribution period: <Dyuthi Vivek> 

### ISSUE THREAD

**Issue by DyuthiVivek** [ersilia-os/ersilia#1073]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by DyuthiVivek** [comment]
Hi,

I am writing this letter to show my interest in joining Ersilia Organization as an Outreachy intern. I am truly inspired by Ersilla’s mission to support research in infectious and neglected diseases. I believe that it can help in addressing my country, India's healthcare needs. India is a lower-middle-income country with many rural people facing the challenge of inadequate medical facilities. The availability of primary health centers for only 13% and hospitals for as low as 9.6% are some of the indicators. According to The Lancet, each year around 2.4 million Indians die from treatable diseases out of which about 1.6 million deaths are due to poor quality care. This is the worst situation among 136 nations studied. AI/ML powered innovative solutions could enhance early disease diagnosis/treatment and improve healthcare services in my nation.

Considering my foundation in machine learning, working with Ersilia also aligns perfectly with my career goals. As a second year undergraduate student at IIIT Bangalore in India, I have an exposure to several technologies. I have experience with Python programming for 4 years. I also have knowledge about scikit-learn and PyTorch libraries. As an awardee of the AWS AI/ML scholarship, I have completed an AI Programming with Python Nanodegree with Udacity. As part of this Nanodegree, I successfully completed a project involving image classification of flowers using deep learning techniques. Additionally, I am presently a mentor for a machine-learning hackathon taking place in my college. This internship has helped me to acquire skills in leadership and communication which I believe will be useful during the internship period. In addition, having participated in the Girlscript Summer of Code 2023, I have experience with open source contributions and was ranked among the top 100 contributors.

After my internship, I wish to specialize in AI/ML while studying and wish to continue contributing to open-source projects as well as broaden my knowledge about AI/ML. Collaboration with the Ersilla community will definitely assist me in achieving these objectives.

I appreciate your considering my application and look forward to an exciting contributing phase with the Ersilla community!

Yours sincerely,
Dyuthi Vivek

**Comment by DyuthiVivek** [comment]
https://github.com/DyuthiVivek/eos2ta5_model_testing

**Comment by GemmaTuron** [comment]
Hello @DyuthiVivek 

Unfortunately the mentors decided to close the Outreachy project to new applicants on Tuesday last week as we already have many strong applicants, so we won't be able to evaluate and provide feedback on your contributions. This was already updated on the Outreachy website. Thanks for your understanding and wishing you all the best!
