### ISSUE TITLE
🐛 Bug:  "Something is wrong with Ersilia: EmptyOutputError"

### ISSUE THREAD

**Issue by manyajsingh** [ersilia-os/ersilia#1074]
### Describe the bug.

When I tried fetching the model eos46ev, after a few minutes, it displayed the following on my terminal:

🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos46ev:run did not produce an outputTraceback (most recent call last):
  File "/home/manyasachdeva/eos/repository/eos46ev/20240315123850_60AC92/eos46ev/artifacts/framework/code/main.py", line 10, in <module>
    from PyBioMed.PyMolecule import fingerprint
ModuleNotFoundError: No module named 'PyBioMed'

Hints:
- Visit the fetch troubleshooting site

### Describe the steps to reproduce the behavior

1. On your wsl terminal, type:
 conda activate ersilia

2. It should show (ersilia) instead of (base). Once you are in ersilia, type:
 cd ersilia

3. Now to fetch the model, type ersilia fetch eos46ev

### Expected behavior.

Model API eos46ev is supposed to produce an output traceback and not raise an error.
There is no module named PyBioMed and this is raising ModuleNotFoundError
Please fix this! And if I am missing some command/ installation procedure, please let me know!

### Operating environment

I am using WSL (Ubuntu) 23.10

**Comment by DhanshreeA** [comment]
Hi @manyajsingh can you check the environment of the model and list the dependencies in there?

**Comment by manyajsingh** [comment]
Hi @DhanshreeA 
Where shall I refer it from?
This is the github repo link for the model: 
[https://github.com/ersilia-os/eos46ev](url)

**Comment by GemmaTuron** [comment]
Hello @manyajsingh,

If this is related to the Outreachy contribution period please, explain the erorrs / issues you are encountering in your issue, do not open a bug report - this will help the community managers follow the Outreachy applications better. @DhanshreeA please feel free to close this comment and move the conversation to the appropriate issue

**Comment by manyajsingh** [comment]
Alright @GemmaTuron and @DhanshreeA for your patience and help
I will let you know in case I encountered more issues along the way
