### ISSUE TITLE
🐛 Bug: zsh: segmentation fault (Ersilia)

### ISSUE THREAD

**Issue by marshatiisa** [ersilia-os/ersilia#1075]
### Describe the bug.

Successfully completed installation and tested model usage. Checked ersilia was working using the `erislia --help ` command. It was working as expected.
After fetching model using a slug, ersilia commands stopped working and now return ` segmentation fault ` error message each time I use the ersilia command.

A previous error message suggested to create an issue here. Restarted shell and lost it.

### Describe the steps to reproduce the behavior

In the command line:
1. conda
2. conda activate ersilia
3. ersilia --help

### Expected behavior.

A list of ersilia commands

### Operating environment

MacOS

**Comment by GemmaTuron** [comment]
Hello @marshatiisa 

In order to help the community managers keep track of outreachy contributors, please use your dedicated issue for the Outreachy contribution period to explain the issues you are finding.
