### ISSUE TITLE
🐛 Bug: Documentation Correction(Reorder Installation Steps)

### ISSUE THREAD

**Issue by marshatiisa** [ersilia-os/ersilia#1076]
### Describe the bug.

In the Ersilia git book, the steps activate ersilia before it is actually installed:

Pre-requisite 5: The Isaura data lake 
```
#activate ersilia's conda environment (see instructions below to create it)
conda activate ersilia
python -m pip install isaura==0.1
```
is followed by:

2.2. Install Ersilia
After all the pre-requisites are met, we are ready to install the Ersilia tool.

Open a terminal and set up a [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/) environment.
```
# create a conda environment
conda create -n ersilia python=3.7
# activate the environment
conda activate ersilia
```

### Operating environment

MacOS

**Comment by DhanshreeA** [comment]
Hi @marshatiisa the steps indicate activating the conda environment named ersilia.
