### ISSUE TITLE
✍️ Initial Contribution period: <Taiye Michaels> 

### ISSUE THREAD

**Issue by TMicha** [ersilia-os/ersilia#1079]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [X] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by TMicha** [comment]
**Motivation Statement**

Dear Ersilia Team,

My name is Taiye Michaels from Nigeria, I am Data Analyst and an aspiring Data Scientist. My motivation for joining Outreachy is because of the unmatched value it creates by establishing a platform that gives a level playing field for underrepresented persons due to systemic bias and/or discrimination in the technological industry of host countries on the basis of nationality, educational background and gender.

Ersilia’s vision of a world with egalitarian access to healthcare through its mission to equip laboratories in low- and middle-income countries with state-of-the-art Artificial Intelligence (AI)/ Machine Learning (ML) tools for infectious and neglected disease research, resonates with me. Service to humanity while attaining my career objectives inspires me. At the start of this contribution period and having looked through the task description and requirements for the Ersilia project, it comes across as the only relatable Data Science and ML project hence the need to come on board.

I have an undergraduate degree in accounting however, as part of my transitioning process into the tech space, I have acquired related basic skill set for my chosen field. In the course of my previous career, I had also acquired soft skills such as communication, collaboration, teamwork, attention to details, critical thinking and skepticism. I am new to FOSS however, I have experimented with Python and will be happy to collaborate with the Ersilia team on this journey. 

Thus far, I have been able to learn quite a lot during this initial contribution period, and it will always be a learning process for me considering my non-tech background. I have created my very first ‘GitHub Issue’ with this project… interning with Ersilia will help me learn how to work better with GitHub, different ML models and understand the field of ML applied to drug discovery.
During the internship, I plan to learn, contribute and collaborate as much as possible and after the internship I will be more confident to take up Data Science related roles/ internships and/or continue to upskill as much as the situation permits.

I am certain that if my final application for this internship is successful, it will be a crucial step to horning my abilities while driving significant positive changes as a woman in tech. Thank You so much.

**Comment by GemmaTuron** [comment]
Hello @TMicha 

Unfortunately the mentors decided to close the Outreachy project to new applicants last week as we already have many strong applicants, so we won't be able to evaluate and provide feedback on your contributions. This was already updated on the Outreachy website. Thanks for your understanding and wishing you all the best!

**Comment by TMicha** [comment]
Hello @GemmaTuron 

Thank You for your responses. I thought the message you had dropped on the Slack Channel on 18.03.2024 was directed to those who were just arriving there rather than the open of a new issue. I had joined and introduced myself on the #general slack community about 8 days ago, briefly looked through the issues on Ersilia's Github channel, watched a replay of the introduction community call, read the code of conduct and completed and the installation process.

I tried updating my motivation letter on the issue I had earlier created and couldn't find it after searching thoroughly (or maybe I did something wrong initially) that was why I created this new issue. Apologies for the mix up and any other inconveniences ...please let me know your thoughts. Thank You.

**Comment by GemmaTuron** [comment]
Hello @TMicha 

I am sorry but the project closed to new contributors (meaning, all of those who had not yet opened an issue, a requirement to submit the first contribution on the website) on Monday 11th.
We already have many strong applicants so I strongly encourage you to look for projects who might be open to new contributors in order to make the most of your contribution period.
Many thanks!

**Comment by TMicha** [comment]
Hello @GemmaTuron 

This is noted. Thank you
