### ISSUE TITLE
Outreachy Code Project: Linh (@dauinh)

### ISSUE THREAD

**Issue by dauinh** [ersilia-os/ersilia#108]
Applicant: @dauinh

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [x] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [x] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [x] Select one issue related to improving the CLI and request to be assigned to it.
- [x] Link the #PR as a comment under this issue.
- [ ] Make any changes required in the PR and tick this box once it has been approved.
- [ ] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [x] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [x] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [ ]  Check the models available in the Hub
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by dauinh** [comment]
![Screen Shot 2022-03-28 at 8 31 28 PM](https://user-images.githubusercontent.com/62679553/161453429-730be962-c62f-42c1-8c16-35a8c120d172.png)

**Comment by dauinh** [comment]
![Screen Shot 2022-04-03 at 10 40 08 PM](https://user-images.githubusercontent.com/62679553/161465172-f1bf0edc-0a8d-4f30-856b-83946813b12b.png)

**Comment by dauinh** [comment]
Why I'm interested in this project:
- I started learning about AI/ML recently and I really want to get involved with a real-life application. I'm excited to create tools that help people.
- I'm currently a CS student and I'm also interested in the field of Bioinformatics. I want to learn more about genetic diseases.

**Comment by dauinh** [comment]
**Python library**
![Screen Shot 2022-04-04 at 12 43 56 AM](https://user-images.githubusercontent.com/62679553/161475414-4fad5522-f643-44ee-96ca-705f39274fc4.png)

**Comment by GemmaTuron** [comment]
Thanks @dauinh great work, keep on the task list and check for new issues as they appear later in the week!

**Comment by Kcfreshly** [comment]
@dauinh your work flow looks very good

**Comment by dauinh** [comment]
> @dauinh your work flow looks very good

Thank you so much! 😄

**Comment by dauinh** [comment]
PR #212 to solve #168

**Comment by dauinh** [comment]
**Python library**: Docstring for the ErsiliaModel class

`"""ErsiliaModel class

This class runs models that user have fetched from the 
Ersilia Model Hub. This class inherits from ErsiliaBase
class.

Attributes:
    model (ErsiliaBase): Import model that user has fetched
    save_to_lake (bool, optional): Check if model is saved to Lake.
    service_class (str, optional): Keep track of which environment
        is being used (i.e. system, venv, conda, or docker).
    config_json (str, optional): Path to a configuration file.
    credentials_json (str, optional): Path to a credentials file.
    verbose (str, optional): Open debugging console.
    fetch_if_not_available (bool, optional): Check for local model,
        fetch a model if none is available.
"""`

**Comment by dauinh** [comment]
**Python library**

Streamlit app

![Screen Shot 2022-04-18 at 11 54 17 PM](https://user-images.githubusercontent.com/62679553/163917338-779543a4-f264-4b39-a872-9a322dd1885e.png)

![Screen Shot 2022-04-18 at 11 56 29 PM](https://user-images.githubusercontent.com/62679553/163917433-54c23939-b723-47e6-961f-2b19fc799555.png)

![Screen Shot 2022-04-18 at 11 57 27 PM](https://user-images.githubusercontent.com/62679553/163917439-09628065-6db2-4914-af80-ffc1b7cd39df.png)

**Comment by Nawarrr** [comment]
Great work on the docstring, also the streamlit app looks really good

**Comment by dauinh** [comment]
> Great work on the docstring, also the streamlit app looks really good

thank you so much!

**Comment by GemmaTuron** [comment]
The Outreachy contribution period has come to an end, so I will close this issue. If you want to continue contributing to Ersilia, please follow the guidelines in the CONTRIBUTING file
