### ISSUE TITLE
🐛 Bug: Annoying debug logs making it hard to discern what's happening

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1080]
### Describe the bug.

when testing a model in git actions, an annoying repeat piece of code appears, making you need to scroll to the end of it to read the error.  This is the repeated snippet
```
{
        "Identifier": "",
        "BENTO_SERVICE": "",
        "AGE": "",
        "APIS": "",
        "ARTIFACTS": "d"
    },
```

### Describe the steps to reproduce the behavior
Any git action failed, like: https://github.com/ersilia-os/eos24ur/actions/runs/8341255469/job/22826933984

### Expected behavior.

No need for this print, is possible an old debugging print

### Operating environment

Git Action runner

**Comment by GemmaTuron** [comment]
@DhanshreeA since I described the bug I added some more info in the issue for clarity :)
attaching here the whole copy of the annoying piece of print
[Uploading log.txt…]()

**Comment by DhanshreeA** [comment]
@Malikbadmus or @dzumii do either of you want to take up this issue?

**Comment by Malikbadmus** [comment]
> @Malikbadmus or @dzumii do either of you want to take up this issue?

I'll take this up.
