### ISSUE TITLE
✍️ Contribution period: Pujita Sunnapu

### ISSUE THREAD

**Issue by pujitasunnapu** [ersilia-os/ersilia#1082]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [ ] Install Docker if needed, and test another model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by GemmaTuron** [comment]
Hello @pujitasunnapu 

The Outreachy contribution period is closed to new applicants, as indicated on the website. We already have many strong candidates and cannot support further applications. Thanks for your understanding and wishing you all the best for the Outreachy application to other projects.
I will close this issue

**Comment by pujitasunnapu** [comment]
Hey! I have been on slack since week 2 I couldn't raise an issue or work on this because of my exams. Is there any  I initially downloaded a few packages when I joined the channel. Is there any way I can start now?

**Comment by GemmaTuron** [comment]
Hello @pujitasunnapu 

We already have many strong applicants so we really suggest new applicants to look for projects that might still be looking for contributors, as we are not able to provide feedback and review all newcomer applications.
The project closed to new applicants (all of those who had not opened a github issue) on Monday 11th. Thanks for your understanding!
