### ISSUE TITLE
🦠 Model Request: Signaturizer 3D

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1083]
### Model Name

Chemical Checker Signaturizer 3D

### Model Description

Building on the Chemical Checker bioactivity signatures (available as eos4u6p), the authors use the relation between stereoisomers and bioactivity of over 1M compounds to train stereochemically-aware signaturizers that better describe small molecule bioactivity properties.

### Slug

cc-signaturizer-3d

### Publication

https://www.biorxiv.org/content/10.1101/2024.03.15.584974v1

### Source Code

https://gitlabsbnb.irbbarcelona.org/packages/signaturizer3d

### License

MIT

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 

The weights of the models are total 14GB, which makes it almost unfeasible to handle as an ersilia model. (see https://gitlabsbnb.irbbarcelona.org/packages/signaturizer3d/-/blob/main/docs/weights.md) should we only select one or a few of the signaturizers?

**Comment by GemmaTuron** [comment]
These are the 25 signaturizers:
```
A1: 2D fingerprints
A2: 3D fingerprints
A3: Scaffolds
A4: Structural keys
A5: Physiochemistry
B1: Mechanism of action
B2: Metabolic genes
B3: Crystals
B4: Binding
B5: HTS bioassasy
C1: Small molecule roles
C2: Small molecule pathways
C3: Signaling pathways
C4: Biological processes
C5: Interactome
D1: Transcription
D2: Cancer cell lines
D3: Chemical genetics
D4: Morphology
D5: Cell bioassasy
E1: Theraupetic areas
E2: Indications
E3: Side effects
E4: Diseases & toxicology
E5: Drug-drug interactions
```

**Comment by GemmaTuron** [comment]
Should we get a combination of A and B?

Maybe A2, A3, B1, B4 ?

**Comment by arnaucoma24** [comment]
Hi Gemma! I'd say B4 is a must-have and then you could also include A1, B1, C3 and D1, which are the CC spaces we mostly use in the lab. Since you are particularly interested in scaffold hopping, A3 is also a great choice :)

Let me know if I can help in any additional way!

**Comment by GemmaTuron** [comment]
Thanks @arnaucoma24 for the suggestion !

I'll try: A1, A2,A3, B1, B4, C3

**Comment by GemmaTuron** [comment]
@arnaucoma24 is there an easy way to pass the path to local checkpoints when instantiating the signaturizer? something like:
`signaturizer = Signaturizer(space="A1", model = path_to_checkpoints)`

**Comment by arnaucoma24** [comment]
I don't really know. Aksel will for sure have an answer for that! @aksell [aksel.lenes@gmail.com](mailto:aksel.lenes@gmail.com)

**Comment by GemmaTuron** [comment]
Thanks @arnaucoma24 

Seems the paths are a bit hard-coded and not easy to modify, I am trying to add the checkpoints directory in the FineTunedUniMol() class, as otherwise it resorts to None and automatically looks for `lib/python3.10/site-packages/weights/`

**Comment by GemmaTuron** [comment]
ok, I think I have found a small potential bug @aksell you might want to check.

I have manually modified the FineTunedUniMol class to add the model_file_url as a parameter, so that if use_local_weights is True, it will not resort to the online repository and instead use that url


```
class FineTunedUniMol(object):
    def __init__(
        self,
        space: CCSpace,
        remove_hs: bool = True,
        use_gpu: bool = True,
        use_local_weights: bool = False,
        model_file_url = None
    ):
        self.space = space
        self.device = torch.device(
            "cuda:0" if torch.cuda.is_available() and use_gpu else "cpu"
        )

        model_file_name = None
        self.model_file_url = model_file_url
        print(self.model_file_url)
        if use_local_weights:
            model_file_name = f"{self.space.name}_split0.pt" #also manually modified this as I have the split3 from the original downloaded checkpoint
        else:
            model_file_url = (
                "https://github.com/aksell/test-pytorch-modelhub/releases/download/full-CC-95/"
                + f"{self.space.name}_split3.pt"
            )
```

The bug is in the if/else statement of the use_local_weights, as the next class UniMolModel is instantiated as follows:
```
        self.model = UniMolModel(
            model_file_name = model_file_name,
            model_file_URL = self.model_file_url,
            classification_head_name=self.space.name,
            output_dim=128,
            remove_hs=remove_hs,
        ).to(self.device)
```

If the use_local_weights is True, the model_file_name is not None, and this triggers the following piece of code:
```
        if model_file_name:
            self.pretrain_path = (WEIGHT_DIR / self.model_file_name).as_posix()
            self.load_pretrained_weights(path=self.pretrain_path)
        elif model_file_URL:
            self.download_and_load_pretrained_weights(model_file_URL)
        else:
            raise ValueError("Please provide either model_file_name or model_file_URL")
```

and overrides my instantiated `model_file_url` with the `self.pretrain_path` 

It could be confusing to other users as well!
I am currently commenting out the if/else statement so that the model_file_name remains None even if use_local_weights is True, and therefore it really uses the model_file_url I want

Hope this makes sense :)

**Comment by aksell** [comment]
Thanks for the detailed description of the issue! 
The local weights path is a leftover from my testing when developing locally, but I see from your use case that it makes sense to support it properly. What would work for you a custom URL for the weights directory or a local file path?

I added an issue for this https://gitlabsbnb.irbbarcelona.org/packages/signaturizer3d/-/issues/1, and will update you here once I've had a go at implementing it. (I'm not sure I'll be able to look at it before this weekend, but for sure then)

Happy to see the package used, let me know if you have any other issues or have suggestions for improvements : )

**Comment by GemmaTuron** [comment]
Thanks so much @aksell !

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 
I have managed to do the necessary installs via Ersilia, but while the model runs in local, it does not run in Ersilia due to the path to checkpoints, which still tries to download to a local folder from the github repo (it will never work inside docker if it tries to do that)
See the error. I probably need some help in debugging this, it is probably in the signaturizer code:

```
Detailed error:
Model API eos8aox:run did not produce an outputINFO:signaturizer3d.unimol.unimol:Loading pretrained weights from /Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/../../checkpoints/A1_split3.pt
Downloading: "/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/../../checkpoints/A1_split3.pt" to /Users/gemmaturon/.cache/torch/hub/checkpoints/A1_split3.pt
/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/../../checkpoints/A1_split3.pt
Traceback (most recent call last):
  File "/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/main.py", line 53, in <module>
    signaturizer = Signaturizer(space=ds, model_file_url= path)
  File "/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/main.py", line 44, in __init__
    self.model = FineTunedUniMol(space=self.space, remove_hs=True, use_local_weights=True, model_file_url = self.model_file_url)
  File "/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/model.py", line 51, in __init__
    self.model = UniMolModel(
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/site-packages/signaturizer3d/unimol/unimol.py", line 94, in __init__
    self.download_and_load_pretrained_weights(model_file_URL)
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/site-packages/signaturizer3d/unimol/unimol.py", line 105, in download_and_load_pretrained_weights
    state_dict = torch.hub.load_state_dict_from_url(url)
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/site-packages/torch/hub.py", line 766, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/site-packages/torch/hub.py", line 619, in download_url_to_file
    req = Request(url, headers={"User-Agent": "torch.hub"})
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/Users/gemmaturon/miniconda3/envs/eos8aox/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/../../checkpoints/A1_split3.pt'
```

**Comment by miquelduranfrigola** [comment]
OK thanks @GemmaTuron - not sure how to solve this specifically.

Does this file exist? `/Users/gemmaturon/eos/repository/eos8aox/20240320162908_84A61A/eos8aox/artifacts/framework/code/../../checkpoints/A1_split3.pt`?

**Comment by GemmaTuron** [comment]
The file is there, the problem is that it tries use it as a URL, not a file path, and so it fails. So the only option seems to me use the file_name instead of the file_url, but I get stuck at the multiprocessing error

**Comment by GemmaTuron** [comment]
Hi @aksell 

Sorry to ping you back here, did you hit before this multiprocessing error when trying to use local checkpoints?

**Comment by aksell** [comment]
Hey, I have not used local checkpoints for a while with this package. I will give local checkpoints a go on Sunday when I try to implement support for it. I'll likely hit similar issues to what you're hitting now and can give a better answer after that 😀 
sorry you're having to wade through errors to get this working, I hope I can get local checkpoints working out of the box so you don't need to hit all these errors!

**Comment by GemmaTuron** [comment]
Thanks so much @aksell ! Let me know if there is anything I can help with on my end.

**Comment by aksell** [comment]
I am releasing `0.1.8` now which adds the `local_weights_path` argument to `Signaturizer` like this:
```python
 signaturizer = Signaturizer(space="A1", local_weights_path = "/absolute/path/to/weights/A1_split3.pt")
```
The weights file can be called whatever but it should have the weights for the space you pass as the `space` argument.
Let me know if this solves your problem, and if not I can tweak it further!

About the multiprocessing error, I haven't seen that before but I've only tested this on a linux machine. Looking up the error I'm wondering if it could be a multiprocessing issue on MacOs and Windows, when the main script doesn't have main guards. If you're on MacOS or Windows could you try running inside a main guard to see if that would work?
```python
from signaturizer3d import CCSpace, Signaturizer

def main():
    signaturizer_B4 = Signaturizer(CCSpace.B4)
    smiles_list = ["C", "CCC"]
    signatures = signaturizer_B4.infer_from_smiles(smiles_list)

if __name__ == '__main__':
    main()
```
If this is the problem and fix I'm wondering how to make this easier to use for other non linux users, maybe an option to generate conformations without using multi processing? Or at least I can include this information in the user. But lets' see if this is the right fix first : )

**Comment by GemmaTuron** [comment]
Hi @aksell !

Many thanks, this works like a charm! I've been able to upload the Signaturizer3D in Ersilia with the checkpoints for A1, A2,A3, B1, B4, C3.

As for the multiprocessor error, I was working on a Linux machine so I don't know what might be going on, happy to run any other tests if you need

**Comment by GemmaTuron** [comment]
I'll close this issue as the model is incorporated but feel free to reopen it or ping me if you need anything
