### ISSUE TITLE
[🐈 Task]: Add a test to check dockerized model works before pushing the model image to DockerHub

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1096]
### Summary

For some models we are experiencing errors with Dockerized models such as RunTime errors during prediction, or Null outputs. Eg: https://github.com/ersilia-os/zaira-chem/issues/36#issuecomment-2018153637

### Objectives

While this could be due to any number of issues, eg, such as #1051 however we should still run a prediction test for a dockerized model in our `Build and push to DockerHub` pipeline before a model image is pushed to DockerHub.

**Comment by miquelduranfrigola** [comment]
I completely agree with this, @DhanshreeA , and I agree it is critical

**Comment by DhanshreeA** [comment]
This is handled in the eos-template repository.
