### ISSUE TITLE
🐛 Bug: Discrepancy between docker image sizes on ARM machines 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1097]
### Describe the bug.

Model images on ARM machines report a different size than what is shown on an Intel/AMD machine, even images built for the AMD platform. For example, the `ersiliaos/eos3b5e:lates` image reports the following sizes:

1. On an x86_64 machine, the model image's size is 979 MB.
2. On arm64 (Apple silicon, M3), the model image's size 1.53 GB
3. On the same machine with a shell run under Rosetta 2 and i386 architecture, the image specifically for `platform=linux/amd64` is 1.43 GB. The arch was double checked through docker inspect. 

### Describe the steps to reproduce the behavior

Obtain a linux machine such as by setting up ersilia codespaces, and pull the said model, and inspect the size. Now, obtain a Apple silicon machine and pull the same image first normally, and then with the platform flag as `docker pull --platform=linux/amd64 ersiliaos/eos3b5e`, and inspect the image size.

### Expected behavior.

The images should be comparable in size, or at least we should figure out if we can add any more arm specific optimizations during our builds. 

### Operating environment

Mac Sonoma

**Comment by miquelduranfrigola** [comment]
This is interesting.
Would it help to build those ARM images on GitHub Actions runners that are already ARM (e.g. M1)? GitHub now provides them.

**Comment by DhanshreeA** [comment]
Additional info here (See Additional Info in the linked issue): https://github.com/docker/cli/issues/4980

**Comment by DhanshreeA** [comment]
> This is interesting. Would it help to build those ARM images on GitHub Actions runners that are already ARM (e.g. M1)? GitHub now provides them.

I agree, definitely worth investigating at the very least.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This is not very important right now but have there been any developments? Is the same issue happening with the new Ersilia Pack?

**Comment by DhanshreeA** [comment]
@GemmaTuron yes this is the same within ersilia pack as well. I think it has more to do with docker's support for multi-platform builds rather than Ersilia. I am closing it at present because I don't think we can do anything about it for now.
