### ISSUE TITLE
📑 Feature Request: Create a workflow to add example.csv to model repositories

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1106]
### Is your feature request related to a problem? Please describe.

Refer to issues https://github.com/ersilia-os/ersilia/issues/1100 and https://github.com/ersilia-os/eos-template/issues/40. 

### Describe the solution you'd like.

There are several models that need an example.csv because they do not work with every input. This workflow would for a given model id, based on the model's input shape, sample inputs from the https://github.com/ersilia-os/ersilia-model-hub-maintained-inputs repository and for store this input in an example.csv within the model's repo. 

### Describe alternatives you've considered

Doing it manually, which is inefficient.

**Comment by DhanshreeA** [comment]
This is already done with the example command's random sampling.

**Comment by miquelduranfrigola** [comment]
Yeap. Should we close this issue?
