### ISSUE TITLE
🐛 Bug: conda.sh file not properly located

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1107]
### Describe the bug.

In my local Ubuntu Machine 22.04 LTS I get the following error when trying to use ersilia and fetch models using conda:
`/tmp/ersilia-gciwem71/script.sh: line 5: /home/gturon/miniconda3/envs/ersilia/etc/profile.d/conda.sh: No such file or directory`

The etc/profile.d/conda.sh is in the miniconda3 folder, not inside each environment, so this is where Ersilia should look for it

### Operating environment

Ubuntu 22.04 LTS

**Comment by DhanshreeA** [comment]
I think this no longer persists, right @GemmaTuron? Good to close this?

**Comment by GemmaTuron** [comment]
Not happened to me again, fingers crossed. I'll close it for now
