### ISSUE TITLE
🦠 Model Request: REINVENT 4 LibInvent

### ISSUE THREAD

**Issue by ankitskvmdam** [ersilia-os/ersilia#1108]
### Model Name

REINVENT 4 LibInvent

### Model Description

 REINVENT 4 LibInvent creates new molecules by appending R groups to a given input. If the input SMILES string contains specified attachment points, it is directly processed by LibInvent to generate new molecules. If no attachment points given, the model try to find potential attachment points, and iterates through different combinations of these points. It passes each combination to LibInvent to generate new molecules.

### Slug

reinvent4-libinvent

### Tag

Similarity

### Publication

https://chemrxiv.org/engage/chemrxiv/article-details/65463cafc573f893f1cae33a

### Source Code

https://github.com/MolecularAI/REINVENT4

### License

Apache-2.0

**Comment by miquelduranfrigola** [comment]
Hey @ankitskvmdam what is the status of this one? Thanks!

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola ,

Finished working on this just now. `main.py` runs smoothly without any issues. The model is also functioning effectively. I validated its performance by generating 8000 molecules (1000 molecules per input smiles), which took approximately 12 minutes.

Facing some issue when I am using `ersilia fetch` command.  I also noticed that I am not able to fetch old reinvent models (like `eos694w`). I suspect there is some change from REINVENT that is causing the build to fail. I will look into it soon.

![image](https://github.com/ersilia-os/ersilia/assets/22586210/8a926315-3539-4887-9b7a-8595c8f730f0)


REINVENT updates their dependencies last week (https://github.com/MolecularAI/REINVENT4/commit/915ec4cfa87e32ec5c30094435cfdac9c644d928#diff-d30f07d3b5c96037dfa1d196cb69cd4357dfea99c425a170c8ebab83368ffa3cL246):

![image](https://github.com/ersilia-os/ersilia/assets/22586210/fce58654-60ae-41e7-856e-1c127aa816e5)

**Comment by miquelduranfrigola** [comment]
Thanks for the update! I see... Perhaps @DhanshreeA can assist with this. It is possible that building with Docker doesn't work with cuda.

**Comment by ankitskvmdam** [comment]
Yes, we are not using cuda. For now, I guess I just need to pass the correct index-url for cu121. I noticed, I was passing the index-url for cu113

**Comment by DhanshreeA** [comment]
@ankitskvmdam just checking, any help that you need from me?

**Comment by ankitskvmdam** [comment]
@DhanshreeA Thanks for checking. The issue with the installation of reinvent is fixed.
