### ISSUE TITLE
Markdown Guide for Contribution

### ISSUE THREAD

**Issue by Jaya3112** [ersilia-os/ersilia#112]
Markdown is the markup language which is a requirement for everyone, who wants to contribute. It is used for creating formatted text using a plain-text editor.

**Comment by Jaya3112** [comment]
I would like to work on this issue.

**Comment by GemmaTuron** [comment]
Hello @Jaya3112 

Please can you follow the instructions on the Outreachy project website and create a new issue with your name, to track all your contributions? We need you to complete the initial steps before adding any new contribution, this way mentors know who is working on what and it makes easier for us to follow your work.
Many thanks.

**Comment by GemmaTuron** [comment]
Thanks @Jaya3112 I am closing this issue then!
