### ISSUE TITLE
🦠 Model Request: SQUID 3D shape generative model

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1122]
### Model Name

SQUID 3D shape generation

### Model Description

Equivariant shape-conditioned generation of 3D molecules for ligand-based drug design.SQUID can generate chemically diverse molecules for arbitrary molecular shapes

### Slug

squid

### Tag

Compound generation

### Publication

https://arxiv.org/abs/2210.04893

### Source Code

https://github.com/keiradams/SQUID

### License

MIT

**Comment by miquelduranfrigola** [comment]
I will implement a 3D shape search on MOSES (used to train SQUID) to minimize the chance of not finding a seed. Most likely, I will do this with URSCAT of featmol.

**Comment by GemmaTuron** [comment]
This model has been incorporated
