### ISSUE TITLE
ECS Instance for running Ersilia Models

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1123]
We will start by setting up an ECS instance to run an Ersilia Model

- [x] Share permissions needed for the IAM user (@sucksido )
- [x] Create IAM user (@GemmaTuron )
- [x] Build ECS instance to run MW model (eos3b5e) @sucksido 
- [ ] Stress test (thinking of ~ 30 users submitting 1000 molecules to the model) @sucksido 
- [ ] Develop easy streamlit app @miquelduranfrigola 
- [ ] Write 1 pager summary concepts for users @JHlozek

**Comment by sucksido** [comment]
Hi @GemmaTuron ,

These are the permissions that I will need assigned for me to deploy docker containers into AWS ECS.

AmazonEC2ContainerServiceFullAccess
AmazonEC2ContainerRegistryReadOnly
AmazonEC2ContainerRegistryPowerUser
IAM role with permissions for ECS tasks

Will advise once I need any additional access once i've stared working on it. Ta!

**Comment by sucksido** [comment]
Hi @GemmaTuron , I am currently getting this error when i try to create a new task definition: 
![image](https://github.com/ersilia-os/ersilia/assets/8820397/392783ee-4940-4b3a-9181-7bac55228b60)

**Comment by sucksido** [comment]
and this one when I try to create an ECS instance: 
![image](https://github.com/ersilia-os/ersilia/assets/8820397/965dfd15-77d1-4889-b906-55e5202d4635)

**Comment by sucksido** [comment]
I need access to the following policies: 

```
"Effect": "Allow",
"Action": "ec2:CreateTags",
"Resource": "arn:aws:ec2:eu-central-1:443413310934:instance/*"

"Effect": "Allow",
"Action": "iam:GetRole",
"Resource": "arn:aws:iam::443413310934:role/ecsTaskExecutionRole"

"Effect": "Allow",
"Action": "ec2:CreateTags",
"Resource": "arn:aws:ec2:eu-central-1:443413310934:subnet/*"
```

**Comment by GemmaTuron** [comment]
Hi @sucksido 

I shared with you a list of the available ec2 policies for IAM users. Please let me know which ones I should activate. If we need a custom policy please describe the steps here

**Comment by sucksido** [comment]
@GemmaTuron Cool, i will re-look at the roles and advise

**Comment by sucksido** [comment]
I have all the permission I need for now, busy setting up task definition, services and cluster, I have have EC2 instances triggering but can access the public URL as yet, working on getting that to work, attached is the JSON file of what I defined in the task definition. 
[eos3b5eTest001-revision2.json](https://github.com/ersilia-os/ersilia/files/15295917/eos3b5eTest001-revision2.json)

**Comment by sucksido** [comment]
@GemmaTuron , I need access to the following which will allow me to look at the logs white the task is running: 
![image](https://github.com/ersilia-os/ersilia/assets/8820397/9049ac5a-79ac-4eef-9e33-afac9bc0bb9f)
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:GetLogEvents",
            "Resource": "arn:aws:logs:eu-central-1:443413310934:log-group:/ecs/eos3b5eTest001:log-stream:*"
        }
    ]
}
`

**Comment by sucksido** [comment]
![image](https://github.com/ersilia-os/ersilia/assets/8820397/fc0f696c-448f-4ce7-9325-a5ccf4895455)

**Comment by GemmaTuron** [comment]
Hi @sucksido 

Please make sure the resource field is correct. If I add what you have said it seems it will only have access to this one ecs/eos3b5eTest001 ? shouldn't this be across account?

**Comment by GemmaTuron** [comment]
seems something is not right, it pops this message when I try to add it
`This policy defines some actions, resources, or conditions that do not provide permissions. To grant access, policies must have an action that has an applicable resource or condition.`

**Comment by sucksido** [comment]
it seems like it might be formatting issue, lets try this one: `{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:GetLogEvents",
            "Resource": [
                "arn:aws:logs:eu-central-1:443413310934:log-group:/ecs/*",
                "arn:aws:logs:eu-central-1:443413310934:log-group:/ecs/*:log-stream:*"
            ]
        }
    ]
}
`

**Comment by GemmaTuron** [comment]
Hello @sucksido the warning is still the same - please make sure to revise the policy

**Comment by sucksido** [comment]
Hi @GemmaTuron , let me do that now

**Comment by GemmaTuron** [comment]
This seems to work, I've added the policy!

**Comment by sucksido** [comment]
Thanks, it seems like we are still missing another rule/policy, logs still not loading on my end:
![image](https://github.com/ersilia-os/ersilia/assets/8820397/34b74feb-2d60-45a5-ab95-0a8dfac877ca)

**Comment by sucksido** [comment]
[eos3b5e-task-revision1.json](https://github.com/ersilia-os/ersilia/files/15305630/eos3b5e-task-revision1.json)
New Task Definition File

**Comment by GemmaTuron** [comment]
Hi @sucksido sorry I do not understand this last Json file. Is it a rule?

**Comment by sucksido** [comment]
ECS instsnce running: 
![image](https://github.com/ersilia-os/ersilia/assets/8820397/b193a0e6-bfc3-465b-a833-0e4fa74de63f)

**Comment by GemmaTuron** [comment]
Update:
- eos3b5e deployed in an ECS instance
- Stress testing: python script that will send multiple requests to the model  
- Fargate: serverless environment to autoscale the model (CPU, memory...)

To do:
- [ ] Add script to: https://github.com/ersilia-os/aws-utils
- [ ] Ensure permissions are right for accessing the Logs @GemmaTuron to meet with Success and solve it
- [ ] Check the "real life" scenario for the workshop (models eos9ei3, eos43at, 1000 molecules as input)

Once the script is moved to aws-utils, we will close this issue and move the discussion to that repository

**Comment by sucksido** [comment]
Model URLs:

ersiliaos/eos43at = http://3.75.227.184/
ersiliaos/eos3b5e = http://18.199.86.114/
ersiliaos/eos9ei3 = http://35.159.128.242/

**Comment by GemmaTuron** [comment]
perfect thanks @sucksido
