### ISSUE TITLE
[🐈 Task]: Create a PR Template

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1126]
### Documentation
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by DhanshreeA** [comment]
@Malikbadmus or @dzumii do either of you want to take up this issue since both of you have opened a fair number of PRs by now with excellent documentation - perhaps you could create a useful PR template for future contributors?

**Comment by dzumii** [comment]
Alright, I will take this up
