### ISSUE TITLE
🐕 Batch: Ersilia Pack Development

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1138]
### Summary

Ersilia Packer, a lightweight surrogate for BentoML's pack, using FastAPI.

### Objective(s)

- [x] Ersilia Model Packer
- [x] Ersilia Model Linter
- [x] Ersilia Model Server
- [ ] Add unit tests: This will be covered [here](https://github.com/ersilia-os/ersilia-pack/issues/25).

[Relevant repository](https://github.com/ersilia-os/ersilia-pack)

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA

A lot of work has been done in that front. Please update this issue with all the changes and new features before closing it when it is complete.

**Comment by DhanshreeA** [comment]
[Ersilia Pack](https://github.com/ersilia-os/ersilia-pack) is now in a functional state. We have achieved the objectives of adding three main commands within this tool, namely, 

- ersilia_model_lint: To lint a newly incorporated model
- ersilia_model_pack: To pack a model, in the same sense that we have BentoML to pack models, by creating a bundle with model source and checkpoints, along with creating a model server based on FastAPI. 
- ersilia_model_serve: To serve the model bundled in the previous step. This is mainly a wrapper around the FastAPI run command.

**Comment by GemmaTuron** [comment]
Please open a specific issue for unit testing and link it here

**Comment by DhanshreeA** [comment]
I am closing this issue as we are going to handle unit testing in its separate issue within Ersilia Pack repo.
