### ISSUE TITLE
🐕 Batch: Make Ersilia CLI work with new Packing strategy

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1140]
### Summary

Ersilia CLI needs to evolve with the new packing strategy and use the correct one when fetching and serving a model.

### Objective(s)

- [ ] Adapt Fetch
- [ ] Adapt Serve
- [ ] Adapt accessing the metadata

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA

A lot of work has been done in that front. Please update this issue with all the changes and new features before closing it when it is complete.

**Comment by DhanshreeA** [comment]
Ersilia now has the functionality to both figure out which way a model is packed, or be forced to fetch a model in a way that it is packed with FastAPI, or BentoML. 

The resolution happens by way of a [TemplateResolver](https://github.com/ersilia-os/ersilia/blob/24336e5c6e6e01d8b28c9c34560e9074be5134fd/ersilia/hub/fetch/actions/template_resolver.py#L10) class where Ersilia inspects the file structure of the given model to determine whether to use FastAPI (aka, the new template + ersilia pack format), or to use BentoML (aka, the legacy template + bentoml format) to pack a model while fetching it. 

Alternatively, users can also make this decision for ersilia by setting the following flags: [`--with_fastapi`](https://github.com/ersilia-os/ersilia/[blob/24336e5c6e6e01d8b28c9c34560e9074be5134fd/ersilia/cli/commands/fetch.py#L70), or `--with_bentoml`](https://github.com/ersilia-os/ersilia/blob/24336e5c6e6e01d8b28c9c34560e9074be5134fd/ersilia/cli/commands/fetch.py#L63).

**Comment by GemmaTuron** [comment]
I will close this as completed but documentation is still pending.
