### ISSUE TITLE
🐕 Batch: Design and document endpoints in the new app template within Ersilia Pack

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1141]
### Summary

Design and document endpoints in the new app template within Ersilia Pack

### Objective(s)

- [ ] Come up with all relevant endpoints
- [ ] Add functionality to register endpoints dynamically based on the model

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

I am not entirely clear what you mean by endpoints, can you help me understand?

**Comment by DhanshreeA** [comment]
This is related to having functionality within ersilia pack for a contributor to register different endpoints within a model. As we know, currently ersilia simply supports "running" a model, and not fine-tuning/retraining it. We are addressing that functionality as API endpoints here because we want to be able to achieve this through something like:

`ersilia train -i "data source" -o "checkpoint dest"`, which would in fact be an HTTP endpoint on the actual model server.

**Comment by miquelduranfrigola** [comment]
@DhanshreeA anything you need from my end here?
