### ISSUE TITLE
🐈 Task: Use SPDX License identifiers in the Model Request issue template

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1142]
### Summary

- [x] Replace the model licenses with the actual SPDX License identifiers
- [x] Update the Model Request template with the identifiers
- [x] Update License comment with the [SPDX link](https://spdx.org/licenses/)

**Comment by GemmaTuron** [comment]
yes that would be great towards the FAIR-Impact metrics, good idea @DhanshreeA
