### ISSUE TITLE
🐛 Bug: Numpy versions conflicts

### ISSUE THREAD

**Issue by dzumii** [ersilia-os/ersilia#1163]
### Describe the bug.

Ersilia returns warning messages when ran in an environment with newly released numpy version 2.0.0.
See an example [here](https://github.com/user-attachments/files/15871022/output.3.log)

### Describe the steps to reproduce the behavior

1. Upgrade to numpy version 2.0.0
2. Fetch an ersilia model
3. Serve and run the model

### Operating environment

Codespace

**Comment by DhanshreeA** [comment]
Thank you @dzumii

**Comment by dzumii** [comment]
You are welcome @DhanshreeA
