### ISSUE TITLE
🐛 Bug: Performance Metrics Fail for String Output Model

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#1165]
### Describe the bug.

Using the track flag on models with a non-numeric/string output type causes some performance metrics to fail.

### Describe the steps to reproduce the behavior

1. ersilia -v fetch eos8a5g
2. ersilia -v serve --track eos8a5g
3. ersilia run -i "input file" -o "output file"

### Operating environment

Ubuntu 22.04.1

Related to #1090

**Comment by Malikbadmus** [comment]
The **stats** method in the **Runtracker** class currently does not support models with string or non-numeric output data types., instead we should probably calculate the mode and the frequency of each distinct value? @DhanshreeA

**Comment by DhanshreeA** [comment]
Ah this is to be expected @Malikbadmus, let me think some more about this and get back to you. Most likely we want to rework statistics around model results based on the type of model. For example, class distribution would make sense for a classification model; min-max/mean stats for regression tasks; and perhaps something entirely different for generative models.

**Comment by DhanshreeA** [comment]
Hey @Malikbadmus, for now we think stats are actually not that useful for us. So we can get rid of this method entirely. I think you can keep the code for the stat method and in a comment, link this issue there. However within the track method, remove the line where stats is being called. Do you wish to open a PR for this?
