### ISSUE TITLE
🦠 Model Request: Unit Test Model Compound

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1185]
### Model Name

Unit test model for compounds

### Model Description

Given a SMILES string, the model counts the number of characters and other string metrics. This model is just for unit testing, it is not intended to be used in a real-world scenario. 

### Slug

unit-test-compounds

### Tag

Fingerprint

### Publication

https://ersilia.io

### Source Code

https://github.com/ersilia-os/ersilia

### License

GPL-3.0-or-later

**Comment by DhanshreeA** [comment]
This is now done.
