### ISSUE TITLE
🐈 Task: Inconsistency between current licenses recognized by Ersilia vs those maintained in Airtable

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1188]
### Summary

We recently modified acceptable model licenses to be in [SPDX format](https://github.com/ersilia-os/ersilia/issues/1142) however this has introduced two bugs that drastically affect the model incorporation workflow:

1. Previously incorporated models cannot be successfully edited now, should the need arise, because Ersilia does not recognize those models as having a correct license.
2. Airtable does not have licenses in the SPDX format, so newer models are not accepted by our workflows because Airtable rejects these license identifiers.

The solution here is two fold, and partly stop gap. We will do the following:

- [ ] 1. Restore previous license types within ersilia, however in the future it would be ideal to do away with the older format and work with the updated SPDX format. 
- [x] 2. Update Airtable with SPDX license identifiers (@GemmaTuron has completed this in Airtable)

### Objective(s)

The first task can be easily achieved by taking content from the license.txt file `ersilia/hub/content/metadata` from a commit before this PR was merged. As for the second task, we can either do it manually or through a GitHub action can be implemented to update Airtable with this data, this action is dispatched only when the license.txt file is modified.

**Comment by DhanshreeA** [comment]
@GemmaTuron tagging you in this issue for the second task.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 
Can you confimr if you want me to delete the old license information and switch for the new one? I thought tat is what we decided but now looking at point 1 is like we want to keep the old licenses as well?

**Comment by miquelduranfrigola** [comment]
That would be ideal, @GemmaTuron - let's just be extra careful with back-compatibility with old models.

**Comment by GemmaTuron** [comment]
I thought we said we would just use new ones @miquelduranfrigola ?

**Comment by DhanshreeA** [comment]
Note: As a stop gap, intermittent solution, we decided to maintain both older formats of licenses and the newer format - however we will deprecate the older versions in the future.
