### ISSUE TITLE
🐈 Task: Reflect correct values in information.json 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1196]
### Summary

Presently, when a model is fetched from DockerHub, the `information.json` file, which we rely upon for retrieving general characteristics about a fetched model, is [copied](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/hub/fetch/lazy_fetchers/dockerhub.py#L45) from the container storage to the host storage - however this is incorrect since it is only a representation of the model environment inside the container and not the one on the host machine. 

Eg: If I fetch `eos3b5e` from DockerHub, as per the information.json made available on my machine, the model's size is <1MB, and its service class is `conda`. However, the model size is ~750 MB (the model image size), and the model's service class is `pulled_docker`. 

The `information.json` file is currently being used in the following ways:

1. [In ErsiliaModel.info()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/core/model.py#L545)
2. [In LocalCard._load_data()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/hub/content/card.py#L715)
3. [ModelInformer.__init__()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/hub/fetch/actions/inform.py#L16)
4. [ModelHostedFetcher.get_information()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/hub/fetch/lazy_fetchers/hosted.py#L81) and ModelHostedFetcher.get_metadata()
5. [PulledDockerImageService._get_memory()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/serve/services.py#L525)
6. [StandardCsvRunApi.get_input_type()](https://github.com/ersilia-os/ersilia/blob/e6edabeaad9f1dff80062c5699dfa690e98ff2fb/ersilia/serve/standard_api.py#L111) and StandardCsvRunApi.is_output_type.standardizable()
7. Ersilia test

### Objective(s)

TODO

**Comment by DhanshreeA** [comment]
@dzumii do you wanna look into this?

**Comment by dzumii** [comment]
Yes

**Comment by DhanshreeA** [comment]
@Malikbadmus or @dzumii could you please update the issue Objectives with what we've discussed about regarding how to proceed with this? :) Thank you!

**Comment by Malikbadmus** [comment]
> @Malikbadmus or @dzumii could you please update the issue Objectives with what we've discussed about regarding how to proceed with this? :) Thank you!

@DhanshreeA , I cannot edit the issue to make modifications regarding this.

**Comment by dzumii** [comment]
I am also unable to edit @Malikbadmus i think we can just add it as a comment instead of editing the first comment

**Comment by DhanshreeA** [comment]
This has been resolved.
