### ISSUE TITLE
🐈 Task: In the model request form, sort tags

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1208]
### Summary

The model request issue template has a dropdown menu for the tags. At the moment, these tags are not sorted. They should be sorted alphabetically.

### Objective(s)

Navigating tags is challenging in the current dropdown menu, and it will become even more challenging as we include more tags

### Documentation

This is the model request form: https://github.com/ersilia-os/ersilia/blob/master/.github/ISSUE_TEMPLATE/model_request.yml

**Comment by dzumii** [comment]
@DhanshreeA I will work on this

**Comment by DhanshreeA** [comment]
Hi @dzumii thank you for taking this up. Here's how we want to implement this. The sorting should happen automatically through an action. This action should run when there's any modification to the [tags](https://github.com/ersilia-os/ersilia/blob/master/ersilia/hub/content/metadata/tag.txt) file in ersilia. The action should take the contents of this file, sort them alphabetically, and replace the value for [`options`](https://github.com/ersilia-os/ersilia/blob/f07c7b8eba7127dabc090613af43d1ce8d39a7b4/.github/ISSUE_TEMPLATE/model_request.yml?plain=1#L38) attribute in this YAML key. 

Practically, you can do the following:
1. Create a job in the `test.yml` file after the `test` job. For now don't worry why this is going in this workflow. We will clean up our workflows soon (Ref: #1231) 
2. You could use the example [here](https://stackoverflow.com/a/70711156/1887515) to implement checking whether the tags file was modified. 
3. If the file was modified, read its contents, sort them, update the Issue Template, commit and push this change.

**Comment by dzumii** [comment]
thanks for expantiating @DhanshreeA

**Comment by DhanshreeA** [comment]
This is now fixed with an action that updates the issue template every time the tags file is edited @miquelduranfrigola
