### ISSUE TITLE
Outreachy Documentation Project: <0DUNTAN>

### ISSUE THREAD

**Issue by 0DUNTAN** [ersilia-os/ersilia#121]
Applicant: <applicant github handle>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [x] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [ ] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [ ] I have submitted my final application to the project

**Comment by 0DUNTAN** [comment]
Hi , I am Oduntan Mubarak, A Web Developer and Technical writer, I am an Outreachy '22 Applicant, I would love contribute to the Ersilia Open Source Initiative Project 1 (Improve the documentation and outreach material of the Ersilia Model Hub) and to be added to the community, My email is [moduntan29@gmail.com](mailto:moduntan29@gmail.com), It's also the email for my slack account

**Comment by 0DUNTAN** [comment]
Link to the ReadMe Documentation https://github.com/ersilia-os/ersilia/compare/master...0DUNTAN:patch-1

**Comment by GemmaTuron** [comment]
Hi @0DUNTAN 

Can you create a PR for the readme? If you want to focus in this task the goal is to create new versions of the current readme. Many applicants have already tackled this so perhaps you want to focus on another task from the list for your application

**Comment by 0DUNTAN** [comment]
link to the Strategic plan  blogpost https://docs.google.com/document/d/1n7EAUpP1IMPWJwMh-SJSoqHIsXUUf8O3TCCwhYKqKao/edit?usp=sharing

**Comment by 0DUNTAN** [comment]
Template for a twitter post for release of a new model https://docs.google.com/document/d/1UPZWS05iczyDz_2_JTFjni0qgqLqYfTNuk0U4WGItJc/edit?usp=sharing

**Comment by 0DUNTAN** [comment]
Template short Newsletter for ersilia community https://docs.google.com/document/d/16CZp2Dz5RX1VsAtqRMzwzKiw78j88ZTtAttV2HQ1ycw/edit?usp=sharing

**Comment by 0DUNTAN** [comment]
Hi @GemmaTuron 
This is the Slide of Ersilia’s mission and vision  designed using Canva, Can be accessed by the Link https://www.canva.com/design/DAE-JcieoQ8/uKfXI_7fONeA6jxVjwN9Ng/edit?utm_content=DAE-JcieoQ8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by GemmaTuron** [comment]
Hi @0DUNTAN 

thanks, I will try to give some feedback on the different tasks, and I think you should now focus on the final application:
- the twitter post seems a bit too long, it will have too many characters once the name of the model is added, it should be broken down in parts
- The newsletter is perhaps missing a thank you note
The rest looks good, thanks for the work!

**Comment by 0DUNTAN** [comment]
I am interested in this project (documentation) because, during my internship in Product Management, One of the major barriers to the adoption of new technology is documentation, Technical team build amazing technologies (like Models in the Ersilia Model Hub) but non Technical users are having difficulty using it due to less understanding of this technologies, thereby leading to low adoption. 

My Interaction with Both Technical teams (Managing development teams as a product manager), and nontechnical teams (conducting User interviews, Customer research, customer development) has equipped me with the ability to break down the technical concept into simple language that can be understood by the user, There easing the adoption of this technologies and helping achieve Ersilia mission to strengthen the research capacity against infectious and neglected diseases by democratizing the access to machine learning tools
