### ISSUE TITLE
Outreachy Documentation Project: <Dapper50>

### ISSUE THREAD

**Issue by Dapper50** [ersilia-os/ersilia#122]
Applicant: <Dapper50>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [ ] Create a README file with the name <README_yourname.md> under the /documentation folder
- [ ] Link the #PR in a comment under this issue
- [ ] Incorporate feedback from the mentor
---
### Writing dissemination material
- [ ] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [x] Test one model
- [x] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [x] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [x] Link the #PR in this issue
- [x] Incorporate feedback from the mentor
---
### Scientific content
- [ ] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by Dapper50** [comment]
I found this community through the outreachy projects after constant search for a suitable project without any luck. The moment I came across this project and I read the guidelines and what the project entails I immediately connected with it and I  knew this was what I have been looking for. I joined the slack channel and everyone has been helpful and friendly towards me.  This is my first experience in GitHub and open source but this community has helped me and I could not ask more, I am excited to learn and contribute to the growth of this project.

**Comment by Dapper50** [comment]
Ersilia model

![fullsizeoutput_573](https://user-images.githubusercontent.com/94048274/161634520-b2839363-d76f-4ea5-a4a6-832a2cfd7d6d.jpeg)

**Comment by GemmaTuron** [comment]
Hi @Dapper50 

God job in installing the hub and testing the models! Please pick some of the tasks outlined above to continue your contribution, and record it on the Outreachy website.

**Comment by Dapper50** [comment]
Graphic Material:

https://docs.google.com/presentation/d/1ZASZBscCtZep0jzMKMvaYSyTUYA7GOk9RJBF9yjLfDg/edit?usp=sharing

**Comment by Dapper50** [comment]
@GemmaTuron Thank you so much for the feedback.

**Comment by Dapper50** [comment]
Community:
I commented on an issue from @Shamswaggirl and gave a feedback on the image slide created for the graphic material section.

**Comment by Dapper50** [comment]
> Hi @Dapper50 Thanks for the slide! I really like the questions you answer on the right, could you think a bit more on the answer to "What will the world look like when we have completed our mission ?" - this should be our big vision, like, a strong research community in Xxx working towards xxx...
> 
> I like the vision - purpose - mission in the left, but it is not clear to me where the arrows of mission and vision point to. Perhaps these shouldn't be arrows but boxes?

**Comment by Dapper50** [comment]
@GemmaTuron thank you so much on the feedback on the slide, i have made changes as advised please assist review.

**Comment by GemmaTuron** [comment]
Hi @Dapper50 
Thanks for the changes well done! Please continue working in the next task of your interest

**Comment by Dapper50** [comment]
Created a Tutorial video on how to use the Ersilia Model Hub with PR#1

**Comment by Dapper50** [comment]
@GemmaTuron I have proceeded to create a tutorial video

**Comment by GemmaTuron** [comment]
Hi @Dapper50 

I cannot access the video, can you check permissions? I think it is great if we can focus on having a short video as we don't have much video material yet. Grant me access and we can work on it

**Comment by Dapper50** [comment]
@GemmaTuron Apologies for the mix up I just granted you access to the video.

**Comment by Dapper50** [comment]
@GemmaTuron please assist view tutorial video.

**Comment by GemmaTuron** [comment]
Hi @Dapper50 

The video content is good but it goes so fast! perhaps typing the commands instead of just pasting a screenshot would make it easier to follow!

**Comment by Dapper50** [comment]
@GemmaTuron Thank you for the feedback, I have made changes as requested.
