### ISSUE TITLE
🐈 Task: Drop support for Python 3.7

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1226]
### Summary

Python 3.7 is officially dropped from many packages that Ersilia depends on or makes use of in some capacity. The pressing one currently is poetry which now [does not build ](https://python-poetry.org/blog/announcing-poetry-1.6.0/#other-important-changes) with Python 3.7 and packages built with it may or may not work with Python 3.7 either. 

### Objective(s)

- [ ] Figure out what changes need to be made for dropping this support
- [ ] Removing tests concerned with Python 3.7

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Is this linked to #944 ? When one is updated please reflect here as well

**Comment by DhanshreeA** [comment]
1. `pyproject.toml` needs updating for this in a few places, such as dependencies (validators, sphinx), and in Classifiers (ie supported Python versions)
2. In the `tests_and_cleanup.yml` workflow, `install-ersilia`, and `test-docker` jobs can do away with accounting for Python 3.7

**Comment by P-Mefut** [comment]
hi @DhanshreeA I'll love to give this a go

**Comment by Darkbeast-glitch** [comment]
HI @DhanshreeA  I would love to take this issue. thank you

**Comment by DhanshreeA** [comment]
@P-Mefut and @Darkbeast-glitch - let me review your existing PRs first, then we can consider this! Thanks!

**Comment by DhanshreeA** [comment]
@Darkbeast-glitch I don't see you assigned to any issue, my bad. Please take up this one.

**Comment by Darkbeast-glitch** [comment]
> @Darkbeast-glitch I don't see you assigned to any issue, my bad. Please take up this one.

@DhanshreeA  Thank you ma . will work on that.

**Comment by DhanshreeA** [comment]
Addressed in #1316
