### ISSUE TITLE
Outreachy Documentation Project: <adeolaadedeji>

### ISSUE THREAD

**Issue by adeolaadedeji** [ersilia-os/ersilia#123]
Applicant: <adeolaadedeji>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [ ] Create a README file with the name <README_yourname.md> under the /documentation folder
- [ ] Link the #PR in a comment under this issue
- [ ] Incorporate feedback from the mentor
---
### Writing dissemination material
- [ ] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [ ] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by adeolaadedeji** [comment]
I have been struggling with finding a suitable project with no luck, then i found this community. I read the guidelines/project description and i  knew i could do this.. What really stood out was the opportunity to  learn new skills. I have joined the slack channel and everyone seems friendly and willing to help. I am really excited about this opportunity to learn and contribute to the project...

**Comment by adeolaadedeji** [comment]
https://docs.google.com/presentation/d/10ZLQkj54-aL5jCNXnxWunBvavB_uAIjAfQbwBy67ev8/edit?usp=sharing

**Comment by GemmaTuron** [comment]
Hi @adeolaadedeji 
I cannot access the document, can you revise the permits and let me know once its open?
Thanks!

**Comment by adeolaadedeji** [comment]
Hi Gemma,  i am sorry about that.. The document is open now.

**Comment by GemmaTuron** [comment]
Hi @adeolaadedeji thanks!
A few comments:
- On the first slide, I would remove the green lines, as they are not in our brand colours. Perhaps choose a background color from our palette?  we always prefer plum-green combination
- For the second slide, you have all the messages there, but I think some are repeated. Could you structure in three sections mission -  vision - the Ersilia organisation, making sure each gives only one message?

**Comment by adeolaadedeji** [comment]
Okay @GemmaTuron i will work on it.. Thank you

**Comment by adeolaadedeji** [comment]
Hi @GemmaTuron i have worked on it, kindly review..Thank you

**Comment by adeolaadedeji** [comment]
I checked out @victorabba's and @loweyvana's project and commented on their issues.

**Comment by GemmaTuron** [comment]
Hi @adeolaadedeji 

The content looks good, perhaps you could give a bit of formatting so that it is not only text copied. If you prefer to work on something not related to graphic design choose one of the other tasks to continue

**Comment by adeolaadedeji** [comment]
Hi @GemmaTuron ,thank you for the feedback. I have made adjustments, kindly review while i skim through other tasks.

**Comment by GemmaTuron** [comment]
Hi @adeolaadedeji,

Thanks for the additions in the slide.
As we are more than halfway through the application period, I would encourage you to choose one task and focus on it to prepare your final application.

**Comment by adeolaadedeji** [comment]
Thank you @GemmaTuron
