### ISSUE TITLE
🐈 Task: Clean up GitHub Actions Workflows 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1231]
### Summary

We have a lot of workflows in the repository currently, a lot of which are not even getting used, and some workflows are duplicated. For example, 

1. [Install Ersilia](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/install.yml) and [Run Pytest ](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/test.yml)workflows could go into the same file as parallel jobs since they both have the same triggers. [Test Colab](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/test-colab.yml) could also go in the same file as a parallel job, or sequential to Run Pytest.
2. [Quick Model Test (manual)](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/quick-manual-model-test.yml), [Ersilia model ouptut prediction (Manual)](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/predict-model-input.yml), and [Ersilia model output prediction](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/predict-model.yml) - all seem to be doing the same thing, and they all require a manual trigger, even though the last one was supposed to run on a schedule at some point. 
3. [Ersilia Base Image to DockerHub Upload](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-base-image-to-dockerhub.yml) and [Ersilia Installer to DockerHub upload](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-installer-to-dockerhub.yml) can both go into the same file as parallel jobs since they both have the same workflow trigger, and are independent of each other. There's a slight caveat, the trigger for these jobs depends on a workflow that no longer exists. Tagging and versioning now happen in the [Ersilia Release](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/publish.yaml) workflow. On second thoughts, I think the DockerHub uploads can be bundled in this workflow as sequential jobs after the GH and PyPI releases are successful. 

### Objective(s)

TODO

**Comment by dzumii** [comment]
@DhanshreeA I have started working on this, do you advise i take each on different PRs? So i can easily test and not mess things up too much at a go.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

There is a bunch of PR's linked to this. Can you update of the mentioned issues, which ones are remaining to tackle?

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron we have managed to achieve point 1 in the summary provided above.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This has a deadline for 22nd November. If it is not completed please update it accordingly. I think this needs to happen side y side with the documentation of the CI/CD workflows in GitBook

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This issue has a deadline for Dec 7 but is still on hold. Please update status.
