### ISSUE TITLE
🐈 Task: Refactor script that updates metadata to work with YAML instead

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1233]
### Summary

The Model Request Approval [workflow](https://github.com/ersilia-os/ersilia/actions/runs/10157510160/workflow) tries to parse information from the Model Request Issue to serialize this data into the model's metadata file. This step is important to be carried out at this stage so that we don't lose information from the issue. Since the development of Ersilia Pack, we have moved away from using JSON format for the metadata file in favor of using the YAML syntax since the latter is more user friendly to work with. The [script](https://github.com/ersilia-os/ersilia/blob/master/.github/scripts/update_metadata.py) parsing this information and serializing it in JSON format should be updated to work with YAML instead, and correspondingly, the [eos-template](https://github.com/ersilia-os/eos-template) should do away with keeping a skeleton `metadata.json` file as well. 

### Objective(s)

- [ ]  Refactor the aforementioned script to work with YAML instead
- [ ] Modify eos-template repository to only include the `metadata.yaml` file, and remove `metadata.json`.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This is marked as ready. Is this complete?
