### ISSUE TITLE
Outreachy Documentation Project: Tracy Nuwagaba

### ISSUE THREAD

**Issue by tracycod3r** [ersilia-os/ersilia#124]
Applicant: @tracycod3r
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [ ] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by tracycod3r** [comment]
### Why I am interested in Ersilia
Ersilia is a non profit organisation that supports research for infectious and neglected diseases with a focus on establishing collaborations in low resourced settings where the costs of drug discovery are prohibitive.

I come from a developing country, Uganda and infectious diseases are a major burden because they continue to threaten the health of million of people. Since most infectious diseases prevail in developing countries and most people living in these countries have a low purchasing power, the market for these drugs are unattractive to the pharmaceutical firms. There has been reluctance of pharmaceutical companies to engage in the development of drugs addressing diseases that mainly affect developing countries hence people continue relying on traditional medicines.

The poor economy and technical capabilities in Uganda are major setbacks to the development and research of new drugs. However with Ersilia, scientific progress is accessible to all, providing a friendly and transparent resource to everyone and this fosters the development of new drugs to curb the infectious diseases in low income countries like Uganda.

I would love to be part of the initiative that empowers the health system in low and middle income countries where medical care is most needed and that is why i am interested in Ersilia.

**Comment by tracycod3r** [comment]
Contributions:

1. I have created a README file as one of the Github Documentation tasks #165

**Comment by GemmaTuron** [comment]
Hi @tracycod3r 

Thanks for starting to work on the Ersilia project. The goal of the README task is to add some contributions or suggestions to improve what is there. I don't see major changes in your readme, can you check it and add some ideas of what is missing?
If you are interested in other types of task please check the list and select soemthing else to start working.
Thanks!

**Comment by tracycod3r** [comment]
> Hi @tracycod3r
> 
> Thanks for starting to work on the Ersilia project. The goal of the README task is to add some contributions or suggestions to improve what is there. I don't see major changes in your readme, can you check it and add some ideas of what is missing? If you are interested in other types of task please check the list and select soemthing else to start working. Thanks!

Thank you @GemmaTuron for the update, working on the changes

**Comment by tracycod3r** [comment]
I have created a 1 page blog post for the Ersilia's Strategic Plan 2021-2023
https://docs.google.com/document/d/1YKJzEQTP3TGlECOBcII-pY6eRfmpqWcJgkK2Sg3pYag/edit?usp=sharing

**Comment by tracycod3r** [comment]
I have written a 1 page blog post about Artificial Intelligence and Machine Learning for drug discovery of neglected diseases in low and middle income countries.
https://docs.google.com/document/d/1eY6qhC3aBQVvqeTBzd8LBcrb17XseB_zaXEOZ1S4trc/edit?usp=sharing

**Comment by GemmaTuron** [comment]
> I have created a 1 page blog post for the Ersilia's Strategic Plan 2021-2023 https://docs.google.com/document/d/1YKJzEQTP3TGlECOBcII-pY6eRfmpqWcJgkK2Sg3pYag/edit?usp=sharing

Hi @tracycod3r , the beggining is good but perhaps you could add one line explanation of each goal, otherwise the content is not too relevant. The explanation of goals is more important than naming the values for example

**Comment by GemmaTuron** [comment]
> I have written a 1 page blog post about Artificial Intelligence and Machine Learning for drug discovery of neglected diseases in low and middle income countries. https://docs.google.com/document/d/1eY6qhC3aBQVvqeTBzd8LBcrb17XseB_zaXEOZ1S4trc/edit?usp=sharing

Hi @tracycod3r thanks
I have made comments in the text for your consideration

**Comment by tracycod3r** [comment]
> > I have created a 1 page blog post for the Ersilia's Strategic Plan 2021-2023 https://docs.google.com/document/d/1YKJzEQTP3TGlECOBcII-pY6eRfmpqWcJgkK2Sg3pYag/edit?usp=sharing
> 
> Hi @tracycod3r , the beggining is good but perhaps you could add one line explanation of each goal, otherwise the content is not too relevant. The explanation of goals is more important than naming the values for example

Thanks @GemmaTuron for the feedback. I will make the changes as soon as possible.

**Comment by tracycod3r** [comment]
I have created a short newsletter to be sent out every month to the community.
https://docs.google.com/document/d/1O06cgPllaxfTjXHK136V-yYOASpH0qR_LCsDonck1L4/edit?usp=sharing

**Comment by tracycod3r** [comment]
> > I have created a 1 page blog post for the Ersilia's Strategic Plan 2021-2023 https://docs.google.com/document/d/1YKJzEQTP3TGlECOBcII-pY6eRfmpqWcJgkK2Sg3pYag/edit?usp=sharing
> 
> Hi @tracycod3r , the beggining is good but perhaps you could add one line explanation of each goal, otherwise the content is not too relevant. The explanation of goals is more important than naming the values for example

I have made the changes @GemmaTuron . Kindly review

**Comment by tracycod3r** [comment]
> > I have written a 1 page blog post about Artificial Intelligence and Machine Learning for drug discovery of neglected diseases in low and middle income countries. https://docs.google.com/document/d/1eY6qhC3aBQVvqeTBzd8LBcrb17XseB_zaXEOZ1S4trc/edit?usp=sharing
> 
> Hi @tracycod3r thanks I have made comments in the text for your consideration

Thank you @GemmaTuron for the comments. Making the changes as soon as possible

**Comment by tracycod3r** [comment]
> > I have written a 1 page blog post about Artificial Intelligence and Machine Learning for drug discovery of neglected diseases in low and middle income countries. https://docs.google.com/document/d/1eY6qhC3aBQVvqeTBzd8LBcrb17XseB_zaXEOZ1S4trc/edit?usp=sharing
> 
> Hi @tracycod3r thanks I have made comments in the text for your consideration

I have made the changes @GemmaTuron

**Comment by tracycod3r** [comment]
I have commented on @dchidindu5 project and advised the errors in the blog post for Ersilia strategic plans and the graphic material for Ersilia's mission statement that need to be rectified

**Comment by GemmaTuron** [comment]
Hi @tracycod3r 

Thanks for the work and the support in the community! I suggest you start working towards your final application, finishing off any tasks you are currently tackling!

**Comment by tracycod3r** [comment]
Thank you @GemmaTuron, working towards my final application

**Comment by tracycod3r** [comment]
I have created a slide explaining Ersilia's mission and vision.

Here is the link
https://docs.google.com/presentation/d/1BZv81X4o35wx-80D2LL_W56YnLAnZF83/edit?usp=sharing&ouid=106977232773647805334&rtpof=true&sd=true

**Comment by dchidindu5** [comment]
@tracycod3r Nice interface, maybe you should add some spice to the vision and mission statement. Just a suggestion though

**Comment by tracycod3r** [comment]
Thanks @dchidindu5 will look into it

**Comment by GemmaTuron** [comment]
Thanks @tracycod3r for the slide!
