### ISSUE TITLE
🐛 Bug: pyairtable dependency missing from pyproject.toml

### ISSUE THREAD

**Issue by kartikey-vyas** [ersilia-os/ersilia#1242]
### Describe the bug.

Noticed this while installing and running ersilia inside a github actions worker.

GHA worker was a standard `ubuntu-latest`. Dependencies installed via this set of commands:

```
cd ersilia
conda install -y python=3.10
conda init
python -m pip install -e .[test]
```

During the run we run into this error:
```
08:43:47 | DEBUG    | No need to use Conda!
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

No module named 'pyairtable'
If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /home/runner/eos/current.log
```

### Operating environment

Ubuntu 22.04 (GitHub Actions runner)

**Comment by kartikey-vyas** [comment]
working around this by adding `pip install pyairtable` as an extra command, so no urgency from our side :)

**Comment by DhanshreeA** [comment]
Hey @kartikey-vyas, thank you for filing a bug report here! Could you please tell me which command(s) you ran that produced this error?

**Comment by kartikey-vyas** [comment]
Ah sorry, we just had the workflow calling 

'ersilia serve eos2zmb'
'ersilia run eos2zmb -i input.csv -o output.csv'

**Comment by DhanshreeA** [comment]
This issue is presently creeping up because of the following issue: #1259

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Since #1259 has been closed, is this still an issue? Can you clarify if pyairtable is a dependency or not finally? I think it should not be right?

**Comment by GemmaTuron** [comment]
Hello @DhanshreeA 

Please update this issue

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron we have a final stretch goal of actually removing it entirely by adding a step in our workflows to update the information directly in S3 at the same time that it gets added to Airtable. Without that, there is still the possibility that we look for that information in S3 and don't find it and then fallback on Airtable.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This has a deadline for 22nd Nov. Please if this is not completed change the deadline for the actual completion date

**Comment by DhanshreeA** [comment]
This is now complete. 

In the PR referenced above, I have moved all the Airtable code from main ersilia source to an `airtableops` script in the .github actions directory, importing Ersilia classes as necessary. Additionally, we sync data to the S3 JSON right after an update is made to Airtable, removing any dependency from using Airtable.
