### ISSUE TITLE
🐈 Task: Update citation file with universal DOI and current ersilia version

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1255]
### Summary

The CITATION.cff file which currently serves a metadata source for published versions of ersilia is quite outdated. It is crucial for this file to be updated for Ersilia to be correctly cited. 

### Objective(s)

- [x] Update Citation file to reflect universal DOI
- [x] Update the [publish](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/publish.yaml) workflow to update the version in the citation file as well.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Is this related in any capacity to the open issues around versioning?

**Comment by DhanshreeA** [comment]
This isn't related to the issues around Docker versioning itself. This particular issue is simply for reflecting the zenodo umbrella DOI and ersilia cli's current tag in the citation file.

**Comment by DhanshreeA** [comment]
This is completed [here](https://github.com/ersilia-os/ersilia/commit/5dabeba402c9609d03d2b0fc7ce1c0980a5424f8).
