### ISSUE TITLE
🐛 Bug: Tags not properly processed

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1256]
### Describe the bug.

Since the conversion of the tags for the new model requests into a dropdown list, when they are parsed they are not added in a list format in the metadata.json (at least if only one tag is selected) making the github actions to fail when pushing the model to the repo.

The workflow that parses user input from a Model Request issue is implemented [here](https://github.com/ersilia-os/ersilia/blob/f96af1431ca4b9baa4d21433c53b908524d1488f/.github/scripts/update_metadata.py#L126) , particularly, the line responsible for serializing tag information. 

### Describe the steps to reproduce the behavior

The way to reproduce this would be in two over arching steps:
Step 1. Create a Model Request issue with just one tag selected. You can use the instructions in the [eos-demo](https://github.com/ersilia-os/eos-demo) to populate this issue. 
Step 1.1 Tag a maintainer to approve this issue
Step 1.2 Verify that in the resulting metadata.yml file, the tag is in fact stored as a string and not a list. 

Step 2. Create another Model Request issue as above, but this time select two tags
Step 2.1 Check if the tags are now stored as a list in the metadata.yml file.

To fix this, we simply need to cast the value being stored at this [line](https://github.com/ersilia-os/ersilia/blob/f96af1431ca4b9baa4d21433c53b908524d1488f/.github/scripts/update_metadata.py#L126) to a list.

To check if your fix works, please wait for it to be merged in master, and create another Model Request issue as described above to verify if your fix works.

### Operating environment

Ubuntu 22.04 LTS

**Comment by DhanshreeA** [comment]
Hey @GemmaTuron did you experience this issue during [this](https://github.com/ersilia-os/eos9p4a/commit/210b8bedc402517adadef9514f58dd8246ccb279) commit? Fixing it ASAP.

**Comment by GemmaTuron** [comment]
> Hey @GemmaTuron did you experience this issue during [this](https://github.com/ersilia-os/eos9p4a/commit/210b8bedc402517adadef9514f58dd8246ccb279) commit? Fixing it ASAP.

yes that is what I observed

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Is this fixed? Or we can label it as a good first issue?

**Comment by Faith-Adegoke** [comment]
Hello @DhanshreeA , I have completed the tasks as required. Can you please assign this issue to me?
Thank you.

**Comment by DhanshreeA** [comment]
@Faith-Adegoke sure! Go ahead.

**Comment by dzumii** [comment]
@Faith-Adegoke can you share your progress with us on this issue?

**Comment by Faith-Adegoke** [comment]
I am currently working on it. I am reproducing the issue from my end to confirm that the tag is cast as a string before I cast it as a list as requested. I have done the first step and I am currently on the second step but I'm waiting for @DhanshreeA to approve my model request so I can continue working on it. Thanks.

**Comment by dzumii** [comment]
Ok, thank you

**Comment by DhanshreeA** [comment]
Closed in #1306
