### ISSUE TITLE
🐛 Bug: RDKit not being installed within the test install of ersilia

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1257]
### Describe the bug.

Apparently if you install ersilia as `pip install -e .[test]` (when installing ersilia from source), rdkit fails to get installed, failing a core io module within ersilia.

Refer to pipeline: https://github.com/ersilia-os/model-inference-pipeline/actions/runs/10919478544/job/30307219372

This can be a good first issue to get started with. Please follow the steps below to confirm if you can reproduce this issue. 

### Describe the steps to reproduce the behavior

In a new environment created through either python's virtualenv, or conda, cd to the ersilia repository and install ersilia in the following way:

```
python -m pip install -e .[test]
```
Then run `pip list` to check if `rdkit` got installed in the environment or not.

Please post your findings here in the issue and tag a maintainer to understand the next steps.
### Operating environment

Ubuntu 22.04 LTS (GitHub Actions)

**Comment by mercybassey** [comment]
Hi @DhanshreeA I will like to work on this issue

**Comment by OlawumiSalaam** [comment]
please I will like to work on this issue @DhanshreeA

**Comment by DhanshreeA** [comment]
@OlawumiSalaam has already been assigned an issue, and @mercybassey I can assign you an issue after the models have been run. Thank you.

This issue is still up for grabs!

**Comment by mercybassey** [comment]
Hi @DhanshreeA I have ran the models and have sent my outputs and motivation statement to you via slack

**Comment by mercybassey** [comment]
@DhanshreeA I have ran the models and sent you my outputs via slack. Thank you.

**Comment by mercybassey** [comment]
@DhanshreeA after installing Ersilia with `python -m pip install -e .[test]`, `rdkit` was not installed and did not appear in the list of intalled libraries. 

`(ersilia) mercy@mercy:~/ersilia$ pip list
Package            Version     Editable project location
------------------ ----------- -------------------------
boto3              1.35.33
botocore           1.35.33
certifi            2024.8.30
charset-normalizer 3.3.2
click              8.1.7
docker             6.1.3
dockerfile-parse   2.0.1
emoji              2.13.2
ersilia            0.1.37      /home/mercy/ersilia
exceptiongroup     1.2.2
fuzzywuzzy         0.18.0
h5py               3.11.0
idna               3.10
iniconfig          2.0.0
inputimeout        1.0.4
jmespath           1.0.1
loguru             0.6.0
numpy              1.24.4
packaging          24.1
pip                24.2
pluggy             1.5.0
psutil             6.0.0
pytest             7.4.4
python-dateutil    2.9.0.post0
PyYAML             6.0.2
requests           2.31.0
s3transfer         0.10.2
scipy              1.10.0
setuptools         75.1.0
six                1.16.0
tomli              2.0.2
tqdm               4.66.5
typing_extensions  4.12.2
urllib3            1.26.20
validators         0.21.2
websocket-client   1.8.0
wheel              0.44.0
(ersilia) mercy@mercy:~/ersilia$ `

**Comment by mercybassey** [comment]
> @DhanshreeA after installing Ersilia with `python -m pip install -e .[test]`, `rdkit` was not installed and did not appear in the list of intalled libraries.
> 
> `(ersilia) mercy@mercy:~/ersilia$ pip list Package Version Editable project location
> 
> boto3 1.35.33 botocore 1.35.33 certifi 2024.8.30 charset-normalizer 3.3.2 click 8.1.7 docker 6.1.3 dockerfile-parse 2.0.1 emoji 2.13.2 ersilia 0.1.37 /home/mercy/ersilia exceptiongroup 1.2.2 fuzzywuzzy 0.18.0 h5py 3.11.0 idna 3.10 iniconfig 2.0.0 inputimeout 1.0.4 jmespath 1.0.1 loguru 0.6.0 numpy 1.24.4 packaging 24.1 pip 24.2 pluggy 1.5.0 psutil 6.0.0 pytest 7.4.4 python-dateutil 2.9.0.post0 PyYAML 6.0.2 requests 2.31.0 s3transfer 0.10.2 scipy 1.10.0 setuptools 75.1.0 six 1.16.0 tomli 2.0.2 tqdm 4.66.5 typing_extensions 4.12.2 urllib3 1.26.20 validators 0.21.2 websocket-client 1.8.0 wheel 0.44.0 (ersilia) mercy@mercy:~/ersilia$ `

I'd like to know if there are any next steps on how to resolve this.

**Comment by DhanshreeA** [comment]
Hi @mercybassey so RDKit is installed a little differently in Ersilia through a [setup](https://github.com/ersilia-os/ersilia/blob/master/ersilia/setup/requirements/compound.py) process that Ersilia [carries out](https://github.com/ersilia-os/ersilia/blob/c6b18a7ec51eb11bd87cb2a508f460c725fb419c/ersilia/io/types/compound.py#L104). Technically if you simply install ersilia in a fresh environment and do not run anything, you would still not find RDKit in the list of packages in that environment, until you run a something that requires for Ersilia to deal with compound inputs and outputs (ie SMILES strings). 

1. First I would like you to verify that if install ersilia in a fresh environment, normally and not with the test extra, you do not see RDKit. 
2. Then if you run a model, you'll notice RDKit being installed
3. Then you do a test install -> verify no RDKit
4. This is where it gets interesting. If you try to run an ersilia model when you did the test install, do you see RDKit being installed? This is what we're trying to reproduce.

**Comment by mercybassey** [comment]
@DhanshreeA 

1. Running Ersilia in a fresh environment without test extra does not install RDKit.
2. When I run a model then RDKit `rdkit_pypi` is installed before the run output is shown.
3. When I do a test install `pip install -e .[test]` RDKit is not also installed. (I used the following [guide](https://stackoverflow.com/questions/52131011/pip-installing-dependencies-with-local-project-path-using-pip-install-e). to perform a test install)
4. When I run a model after doing a test install I see RDkit get installed.

**Comment by DhanshreeA** [comment]
@mercybassey interesting. So RDKit is being installed in both cases when you try to run a model, right? Could you please share your environment states both for normal install and test install?

**Comment by mercybassey** [comment]
@DhanshreeA here are the log files for the normal and test install.

- [normal-install.log](https://github.com/user-attachments/files/17292679/normal-install.log)
-  [test-install.log](https://github.com/user-attachments/files/17292681/test-install.log)

**Comment by DhanshreeA** [comment]
I think we can successfully close this issue then. Thanks @mercybassey!
