### ISSUE TITLE
Add a streamlit app for ersilia model

### ISSUE THREAD

**Issue by Amna-28** [ersilia-os/ersilia#126]
**What is your feature request?**
Develop a streamlit app for ersilia model for better user experience

**Is your feature request related to a problem?**
No, it could be just an enhancement

**Describe alternatives you've considered**
with Ersilia model app, the user could select the model to run, choose api, fetch models, display catalog, request a cleanup (delete unused models in local machine) all in one place. 

**Additional context**
This will improve the usability of ersilia.
I was researching and found that multiple tabs could be incorporated into a streamlit app, using which we can also improve the display of catalog ( #12) Links to the github repositories could also be added for each model in the catalog. There are many more possibilities.

screenshot of a simple app is attached below, that I developed while attempting the application tasks.

![Capture2](https://user-images.githubusercontent.com/98670206/161635701-9a4be084-c509-4026-ab03-206383d0472b.PNG)

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola ,
Please assign this task to me if you find it any useful. I would really enjoy working on it.

**Comment by GemmaTuron** [comment]
@Amna-28 great work.

Link this to your issue thread as well please. I will let @miquelduranfrigola comment.
Something "nice to have" if the models work fine on streamlit is to show the representation of the molecular structure of the input (use the rdkit python library for example)

**Comment by Amna-28** [comment]
Thanks @GemmaTuron ,
Sure thing, I will add the link and start working on it.
Thanks for your feedback!

**Comment by Amna-28** [comment]
> 

Hi @GemmaTuron 
Keeping your suggestion in mind, are you talking about something like this?

![image](https://user-images.githubusercontent.com/98670206/161809359-a074a541-3fea-42fe-9839-a06182eb1d9f.png)

**Comment by Amna-28** [comment]
@GemmaTuron Can I consider this as a new idea mentioned in "other" section of the application as:
_Add a comment in this issue with your new idea, tagging the mentor_

can I mark it referencing this issue?

**Comment by miquelduranfrigola** [comment]
Hi, @Amna-28 this is quite awesome!

A few suggestions:
* Not all models have all APIs, so it would be great that the radio buttons in the "select API" are dynamic, depending on the available APIs for the model. If you are using the `ErsiliaModel` class, it has a `get_apis` method that can help.
* It is OK to see the output in JSON format, but I think it is best if you just display the "output" part of it. No need for "input", "key", "text", etc.

What do you think?

**Comment by GemmaTuron** [comment]
I @Amna-28 

Yes this is what I had in mind great job! This can be considered a new idea sure, no need to open an issue though since you are already solving it.

**Comment by Amna-28** [comment]
> 

@miquelduranfrigola Thank you for your suggestions, yes that would be better to just show the output part. Also I will make use of `get_apis` method to display api available in the model selected.

**Comment by Amna-28** [comment]
> I @Amna-28
> 
> Yes this is what I had in mind great job! This can be considered a new idea sure, no need to open an issue though since you are already solving it.

Got it, thank you @GemmaTuron for your continuous support and feedback
