### ISSUE TITLE
🐈 Task: De-register api command from Ersilia CLI

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1263]
### Summary

Ersilia had a command line `api` that enabled to call different APIs like `run`, `calculate` and so on. We do not allow for this any more and the only API is run, so the command `api` is deprecated and should be deleted from the Ersilia CLI. Please before tackling this issue, read more in detail the status of the Ersilia CLI in #1262 

CLI commands are registered here: https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/create_cli.py

### Objective(s)
- Eliminate the Ersilia API CLI
- Check that Ersilia is able to fetch, serve and run models after the api command is deleted

### Steps

1. Make sure you have a functional installation of Ersilia before working on this issue. Do this by following the instructions [here](https://github.com/ersilia-os/ersilia), and running the model mentioned in the instructions. Note: Please install ersilia as an editable install so you can verify your fix as you change the code.
2. After removing the `api` command from the `create_cli.py` script, make sure you are able to run a model as before using the `ersilia run` command.
3. Additionally, make sure when you run `ersilia api run...`, ersilia CLI does not crash and you see an error that says the command does not exist.

To work on this issue, please post your findings from these steps in this issue if you are assigned to it.

**Comment by petkov120** [comment]
Hi at @DhanshreeA is this issue still open, I am an outreachy contributor and I want to know if i could take this task for my contribution or if there are specific task set aside for outreachy contributors in their contribution phase?

**Comment by DhanshreeA** [comment]
Hi @petkov120 thank you for your interest. We need you to follow all getting started instructions before assigning an issue. Please do that if you have not yet done so.

**Comment by adebisi4145** [comment]
Hello @DhanshreeA, I have sent my motivation statement, model output and my system specification to you on slack . Can you please assign this task to me.

**Comment by KimFarida** [comment]
Hi @DhanshreeA  please may i be assigned this issue? 
You gave the go ahead to work a while ago, thank you

**Comment by petkov120** [comment]
Hi @DhanshreeA I already installed all the dependencies and followed the guide given [here](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation), I fetched a model, started it and ran a quick prediction using the my_molecules.csv data which outputted my_predictions.csv.

the contents of the predictions are as follows
| Key                                | Input                                                                                  | RA_score  |
|------------------------------------|----------------------------------------------------------------------------------------|-----------|
| NOQIYRGMEFBZTI-UHFFFAOYSA-N         | CCCN(CCC)Cc1nc(no1)-c1ncn-2c1CN(C)C(=O)c1cc(F)ccc-21                                    | 0.690002  |
| NXUHVWMBPOFLMA-UHFFFAOYSA-N         | COCCN1CCC(CC1)(C(=O)NO)S(=O)(=O)c1ccc(Oc2ccc(OC(F)(F)F)cc2)cc1                          | 0.991563  |
| USRHYDPUVLEVMC-FQEVSTJZSA-N         | CN(C)[C@@H](CCOc1cccc2ccccc12)c1ccccc1                                                  | 0.993406  |
| RHDJRPPFURBGLQ-UHFFFAOYSA-N         | Cc1cccc(Cc2cnc[nH]2)c1C                                                                 | 0.993488  |
| LQFRYKBDZNPJSW-UHFFFAOYSA-N         | CS(=O)(=O)CCC#N                                                                         | 0.982243  |

**Comment by daud99** [comment]
@DhanshreeA Can I have this one. I have completed all the pre-reqs and sent you the motivation letter as well?

**Comment by royalteegee** [comment]
Hi @DhanshreeA 
I have provided my model responses and motivation letter. I would like to be assigned this task

**Comment by DhanshreeA** [comment]
@adebisi4145 please go ahead!

**Comment by DhanshreeA** [comment]
@adebisi4145 can you carry out Step 3? That is, try to run a model as `ersilia api run` and post your updates here regarding what you get?
This is crucial because we do not want ersilia to crash when it is run this way. 

Ideally, please post an output when you run `ersilia api run` before your changes (ie from the master branch), and after your changes so we can compare. Thank you.

**Comment by adebisi4145** [comment]
Thank you @DhanshreeA for the feedback, I didn't think about posting it here because I have done this on my pull request. However, here are the output:

- [before](https://github.com/user-attachments/files/17267087/output1.log)
- [after](https://github.com/user-attachments/files/17267088/output2.log)
