### ISSUE TITLE
🐈 Task: Extend ersilia delete command with an --all flag to delete all models on the user's system.

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1265]
### Summary

Related to #1262 

A functionality to delete all models present on the user's system would be quite useful. The `--all` flag will be added [here](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/delete.py), and we could potentially use the [local](https://github.com/ersilia-os/ersilia/blob/ce552101ee24a54189b2dd4c40948417b08a56e2/ersilia/hub/content/catalog.py#L186) ModelCatalog to go over the list of locally available models to achieve this functionality. 

@miquelduranfrigola please feel free to suggest a better solution to list all locally available models. 

### Objective(s)

- [ ] Add an `--all` flag to the command
- [ ] Write a function [here](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/delete.py) that is invoked when the `--all` flag is set. This function should create a single `ModelDeleter` object, iterate over locally available models, and call `ModelDeleter.needs_delete(model_id)` on each of the model ids.

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA I think it makes sense to use the local catalog to do this

**Comment by MAVRICK-1** [comment]
@DhanshreeA Can you  assign me this issue

**Comment by DhanshreeA** [comment]
Hi @MAVRICK-1 presently we are only assigning issues to Outreachy applicants. If you are not an approved Outreachy applicant, I am afraid we cannot assign you this issue. Thank you for your interest!

**Comment by KimFarida** [comment]
@DhanshreeA or this one please, which ever is available, thank you!

**Comment by royalteegee** [comment]
Hello @DhanshreeA 
I am an Outreachy applicant. My model response and motivation letter have been sent you via dm on slack. Can you assign this issue to me

**Comment by DhanshreeA** [comment]
@royalteegee go ahead!

**Comment by rohitgupta29** [comment]
Hi @DhanshreeA Please assign this issue to me.

**Comment by JoyProg** [comment]
Hi @DhanshreeA please can you assign this to me? I have a working solution

**Comment by daud99** [comment]
Hi @DhanshreeA, Can you assign this issue to me as I have already submitted the Pull Request against the task you have assigned me earlier.

This seems like an exciting one.

(MOTIVATION LETTER+OUTPUT_OF_MODELS) are also shared.

**Comment by Malikbadmus** [comment]
@royalteegee , are you still working on this, or should we assign it to someone else?

**Comment by KimFarida** [comment]
> @royalteegee , are you still working on this, or should we assign it to someone else?

Incase they aren't, once my pr is reviewed, can i tackle this?
Kind of relates to my issue

**Comment by DhanshreeA** [comment]
Sorry @KimFarida since @rohitgupta29 has not been assigned an issue yet, I'll give this one to them. Thank you!

**Comment by DhanshreeA** [comment]
@rohitgupta29 I see you have already created a PR to another existing issue. Do you want to take up that one instead?

**Comment by KimFarida** [comment]
> @rohitgupta29 I have assigned you another issue. Keeping this one open.

Hiii @DhanshreeA can i have it?

**Comment by teddyCodex** [comment]
Hi @DhanshreeA can i work on this since my last PR has been merged?

**Comment by JoyProg** [comment]
Hi @DhanshreeA can I be assigned? I made a request after Rohit and I have a working solution

**Comment by DhanshreeA** [comment]
Sure @JoyProg ! Please @teddyCodex could you pick another issue? :) Thank you!

**Comment by DhanshreeA** [comment]
Addressed in #1317
