### ISSUE TITLE
🐈 Task: Refactor ersilia clear command

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1266]
### Summary

Related to #1262 

Ersilia clear command really uninstalls everything and therefore we want to rename it to `uninstall` to more clearly reflect that. At present it does not remove docker images for models that have been fetched from DockerHub. In addition to fixing that, we want to extend it in a way that ersilia is able to uninstall itself from the user's system.

### Objective(s)

- [ ] Refactor `clear` to `uninstall` in the command's [definition](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/clear.py). This would typically involve refactoring everything from the class name (`Clearer` -> `Uninstaller`), function names, updating the help text for the command, etc.
- [ ] This command can potentially use `ersilia delete --all` (ref: #1265) to delete all models, including the dockerized models as well. 
- [ ] Remove the ersilia installation as well. This could be a bit tricky depending on how ersilia was installed.

For now, the first two objectives are straightforward to address - and we can discuss approaches and edge cases for the last objective pertaining to ersilia uninstall.

**Comment by ProfessionalCaddie** [comment]
Hello @DhanshreeA , I would like to work on this as well as think about the edge cases. Would the uninstall be mostly difficult because of the different operating systems or are there other factors as well?

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA 
Do you think there is a way to wrap all of this into a `pip uninstall ersilia` and/or `conda uninstall ersilia` instead of `ersilia uninstall`? I mean, uninstalling everything (i.e. deleting docker images, removing the `eos` folder, etc.) using the `pip` and `conda` commands (depending on how `ersilia` was initially installed) would make a lot of sense, but I am not sure if it is even possible to do.

**Comment by DhanshreeA** [comment]
> Hi @DhanshreeA Do you think there is a way to wrap all of this into a `pip uninstall ersilia` and/or `conda uninstall ersilia` instead of `ersilia uninstall`? I mean, uninstalling everything (i.e. deleting docker images, removing the `eos` folder, etc.) using the `pip` and `conda` commands (depending on how `ersilia` was initially installed) would make a lot of sense, but I am not sure if it is even possible to do.

I will have to look into this - especially if we have to add anything as package data that we don't usually do during install time.

**Comment by GemmaTuron** [comment]
Hi @ProfessionalCaddie 

Thanks for your interest! We are opening these issues for the Outreachy applicants that are starting next week, so we will assign those to Outreachy applicants only at the moment. The Ersilia maintainers team is only three of us and we cannot provide support to too many new contributors at the same time. I hope you understand! Once the Outreachy application period is complete (November), we will  be back to having space to onboard new open source contributors.

**Comment by daud99** [comment]
@GemmaTuron I'm an approved Outreachy applicant. Can you assign this task to me?

**Comment by GemmaTuron** [comment]
Hello @daud99 

Please follow the guidelines set out on the Outreachy documentation in GitBook. There is a number of tasks to be completed before being assigned a coding task. And then pick only one, as I see you have added comments to more than one, to get started with. Thanks!

**Comment by jubril-adeyi** [comment]
Hi, @GemmaTuron  @DhanshreeA I am an approved outreachy intern and I have already completed the necessary tasks; I have sent my motivation letter to and ran the models and sent the output also,
Could you please assign this task to me

**Comment by DhanshreeA** [comment]
@jubril-adeyi has already been assigned on an issue. This issue is still up for grabs.

**Comment by KimFarida** [comment]
@DhanshreeA i think i'd like this one too, in the case that the first one i asked is gone

**Comment by DhanshreeA** [comment]
@KimFarida go ahead!

**Comment by DhanshreeA** [comment]
No update from @KimFarida so opening this issue up for grabs again.

**Comment by KimFarida** [comment]
> No update from @KimFarida so opening this issue up for grabs again.

Hi @DhanshreeA, i'm on this. Can i be reassigned?
So sorry for not saying anything

**Comment by KimFarida** [comment]
> @KimFarida go ahead!

Didn't even realize i hadn't responded

**Comment by Malikbadmus** [comment]
@KimFarida , you can go ahead.

**Comment by KimFarida** [comment]
> @KimFarida , you can go ahead.

Thank you!

**Comment by KimFarida** [comment]
@DhanshreeA I think I have a workable solution, I was gonna write tests but might as well run the code by you first, so i know what changes to implement. Sorry it took so long to get back.

**Comment by DhanshreeA** [comment]
@KimFarida no worries, I'm looking at it now.
