### ISSUE TITLE
🐈 Task: Remove the ersilia current command

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1267]
### Summary

Related to #1262 

This is a fairly straightforward task. This command is implemented [here.](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/current.py)

### Objective(s)

- [ ] De-register the `current` command from the ersilia cli [here](https://github.com/ersilia-os/ersilia/blob/ce552101ee24a54189b2dd4c40948417b08a56e2/ersilia/cli/create_cli.py#L17)
- [ ] Remove the implementation for this command mentioned above.

**Comment by antil-samarth** [comment]
Hi, this might become first issue/contribution ever so I'm a bit skeptical. Do I have to just de-register (remove it from create_cli.py) or remove the file where it is implemented as well? Sorry if it is a bother.

**Comment by NKD52** [comment]
Hey, I am interested in tackling this task.

**Comment by GemmaTuron** [comment]
Hello @NKD52 
Thanks for your interest. This issue has been opened for Outreachy applicants, if you are an approved outreachy applicant please first complete the designated tasks before starting to contribute code. If you are not, we'll ask you to wait until the Outreachy application period is completed as the core team is very small and we cannot onboard new contributors at this moment while running Outreachy. Thanks for your understanding!

**Comment by daud99** [comment]
@GemmaTuron I'm an approved Outreachy applicant. Can you assign this task to me?

**Comment by GemmaTuron** [comment]
Hello @daud99 

Please follow the guidelines set out on the Outreachy documentation in GitBook. There is a number of tasks to be completed before being assigned a coding task. And then pick only one, as I see you have added comments to more than one, to get started with. Thanks!

**Comment by Ajoke23** [comment]
Hi @DhanshreeA . Could you please assign this task to me. I have sent my motivation statement, model output and my system specification to you on slack

**Comment by daud99** [comment]
Hi @GemmaTuron , I have already completed the task (motivation letter, model output and system specification) to @DhanshreeA .
Thanks for letting me know.

**Comment by jubril-adeyi** [comment]
Hi, @GemmaTuron  I am an approved  outreachy intern and I have already completed the necessary tasks; I have sent my motivation letter to @DhanshreeA  and ran the models and sent the output also, 
Could you please assign this task to me

**Comment by Ajoke23** [comment]
Hi @GemmaTuron, I have received an OK to go ahead and start contributing to issues from @DhanshreeA.

Please, can this issue be assigned to me?
Can I go ahead to start?

**Comment by DhanshreeA** [comment]
Hi @Ajoke23 go ahead!

**Comment by Ajoke23** [comment]
@DhanshreeA Can I go ahead to start contributing to this issues.
@GemmaTuron, I have received an OK to go ahead and start contributing. I requesting to be assigned to this issue?

> ### Summary
> 
> Related to #1262 
> 
> This is a fairly straightforward task. This command is implemented [here.](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/current.py)
> 
> ### Objective(s)
> 
> - [ ] De-register the `current` command from the ersilia cli [here](https://github.com/ersilia-os/ersilia/blob/ce552101ee24a54189b2dd4c40948417b08a56e2/ersilia/cli/create_cli.py#L17)
> - [ ] Remove the implementation for this command mentioned above.
> 
> ### Documentation
> 
> _No response_

**Comment by DhanshreeA** [comment]
@Ajoke23 could you please reconcile your work in a single PR? 😅

**Comment by Ajoke23** [comment]
> @Ajoke23 could you please reconcile your work in a single PR? 😅 I see three PRs linked to this issue, please tell me which two I can close.

Hi @DhanshreeA. I tagged you to the main pull request.
The main pull request is #1268

**Comment by DhanshreeA** [comment]
@Ajoke23 can we close #1282 then?

**Comment by Ajoke23** [comment]
> @Ajoke23 can we close #1282 then?

Yes, you can

**Comment by DhanshreeA** [comment]
Closed in #1284
