### ISSUE TITLE
🐈 Task: Print ersilia catalog in a table natively

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1268]
### Summary

Related to #12 #238 

Previous volunteers to ersilia did some fantastic work in making Ersilia catalog display in a table format on the terminal, however the external dependency used to achieve that functionality caused ersilia environment to be bloated. We do not want this to be the case and therefore want to implement this functionality natively in Python.

**Comment by jubril-adeyi** [comment]
Hi, @DhanshreeA  I am an approved  outreachy intern and I have already completed the necessary tasks; I have sent my motivation letter to and ran the models and sent the output also, 
Could you please assign this task to me

**Comment by DhanshreeA** [comment]
Go ahead @jubril-adeyi!
