### ISSUE TITLE
🐛 Bug: Ersilia example --predefined not working for example generation with Dockerized model

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1269]
### Describe the bug.

From the build logs here: https://github.com/ersilia-os/eos3wzy/actions/runs/10995330286/job/30525876219#step:14:217 it appears that the example being used is not the one specified in the input [example](https://github.com/ersilia-os/eos3wzy/blob/main/model/framework/examples/input.csv) file. However, example files for dockerized models are supposed to get copied into eos/dest/model-repo which is perhaps not happening thereby making `ersilia example....--predefined` not work correctly.

### Operating environment

Ubuntu 22.04 LTS (GitHub Actions)

**Comment by jubril-adeyi** [comment]
Hi, @GemmaTuron @DhanshreeA I am an approved outreachy intern and I have already completed the necessary tasks; I have sent my motivation letter to and ran the models and sent the output also,
Could you please assign this task to me

**Comment by DhanshreeA** [comment]
Hi @jubril-adeyi please only pick an issue labeled as good first issue. Thank you.
