### ISSUE TITLE
🐈 Task: Automatically update CodeMeta upon release

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1276]
### Summary

Ersilia has an automatic release trigger each month. With the release, the version number must be updated in the Citation.cff (already implemented) but also in the codemeta.json

### Objective(s)

Add the necessary code in the GitHub Action to update the Codemeta.json

**Comment by OlawumiSalaam** [comment]
I will like to work on this @DhanshreeA

**Comment by DhanshreeA** [comment]
Sure @OlawumiSalaam go ahead!

**Comment by OlawumiSalaam** [comment]
Thank you.

**Comment by P-Mefut** [comment]
Hi @OlawumiSalaam, Do you mind us sharing ideas here on how to easily go about the problem or you have it covered?

**Comment by P-Mefut** [comment]
```yaml
- name: Update version in codemeta.json
        id: update-codemeta
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          python -c "
          import os
          import json
          
          # Read the current codemeta.json
          with open('codemeta.json', 'r') as file:
              codemeta = json.load(file)
          
          version = os.environ['VERSION']
          
          # Update the version
          codemeta['version'] = version
          
          # Update the downloadUrl
          codemeta['downloadUrl'] = f'https://github.com/ersilia-os/ersilia/archive/refs/tags/v{version}.tar.gz'
          
          # Write the updated codemeta.json
          with open('codemeta.json', 'w') as file:
              json.dump(codemeta, file, indent=4, ensure_ascii=False)
          "
```


here is a script we can add to the `publish.yml` workflow below the update version in `CITATION.cff` to update the `codemeta.json` file upon release every month.

you can take a look so we solve the issue easier and fast.

**Comment by GemmaTuron** [comment]
Hello @P-Mefut 

Please give time to applicants assigned to the issue to solve them. I will delete your comment. If you are an approved applicant pick an issue and wait for the mentor's assignation.

**Comment by P-Mefut** [comment]
Sorry @GemmaTuron, NOTED thanks!
