### ISSUE TITLE
OUTREACHY CONTRIBUTION PERIOD: Mercy Bassey

### ISSUE THREAD

**Issue by mercybassey** [ersilia-os/ersilia#1278]
This issue documents my contribution progress for the Ersilia project.

## Week 1

 - [x] Task 1: Join in the communication channels

 - [x] Task 2: Install the Ersilia Model Hub

 - [x] Task 3: Motivation statement

 - [ ] Task 4: Obtain approval of the introductory tasks to continue contribution

**Comment by GemmaTuron** [comment]
Hello @mercybassey 

We will keep track of Outreachy progress via Slack, please use this tool to communicate with mentors and send the motivation letter. I will close this issue.

**Comment by mercybassey** [comment]
### Motivation Statement

I am a software developer and DevOps enthusiast with a deep passion for technology. I have experience programming in Bash, JavaScript, and Python, and I am also interested in Linux, automation, Infrastructure as Code, and cloud computing. I have always loved technology and programming; I grew up in a tech-savvy environment and learned how to operate a computer at a very early age because my father had one. I have continuously pursued improving my programming skills through books and various resources.

Coming from a low socio-economic background, my journey through university was challenging, as I had to work part-time as a technical writer to support myself through school. I graduated with a second-class lower degree in Computer Science, and securing internship roles has proven difficult. This has been attributed to both my lower academic grades and lack of industry experience, which stemmed from the divided attention I had to give to both work and studies during my early university years. This situation was further compounded by the barriers facing women in the tech industry, especially in my country, where low grades and a lack of industry experience create significant obstacles. This is not something I am proud of, as it has overshadowed my ability to contribute and gain visibility in projects that matter.

In response to these challenges, I was drawn to the Outreachy internship program. I saw this opportunity as a chance to break through the barriers that have held me back. Through Outreachy, I can prove my passion for technology in a supportive environment, where I can demonstrate my value to any team. This internship allows me to showcase my ability to solve complex technical problems, communicate effectively, and collaborate with individuals from diverse backgrounds.

One of the reasons I started learning Python a few years ago was my aspiration to work in the artificial intelligence and machine learning space someday. I am particularly interested in the intersection of Artificial Intelligence and Machine Learning with various sectors, including healthcare and education. The potential of AI and ML to improve lives is immense, and I am eager to contribute to this transformative field.

Beyond programming, DevOps, and cloud computing, I have developed skills in technical writing. For three years, I have documented software and taught developers how to use new tools, build applications with Python and JavaScript, deploy applications to the cloud, and perform continuous integration and continuous delivery. Additionally, I have built modular Python code and integrated tests, as well as done the same with JavaScript, another language I am proficient in. Now, I am ready to take all these skills to the next level in the artificial intelligence space.

My long-term goal is to specialize in Machine Learning Operations (MLOps), bridging my DevOps and programming expertise with Artificial Intelligence and Machine Learning, to not only develop solutions but also ensure they are reliable and efficient in real-world applications. Working at Ersilia is a crucial step towards achieving this goal.

My experiences have been driven by personal projects and a deep passion for technology. Now, I want to apply my skills to projects with real-world impact, which is why I am eager to contribute to Ersilia’s project.
