### ISSUE TITLE
🐛 Bug: Incorrect output from ersilia catalog command for model eos3wzy

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1281]
### Describe the bug.

This model does not have a Docker image yet, and therefore cannot be fetched from DockerHub. However when the `ersilia catalog --local --more` command is run, this is the output obtained:

```JSON
{
        "Identifier": "eos3wzy",
        "Slug": "qupkake",
        "Title": "Predict micro-pKa of organic molecules",
        "Status": "Ready",
        "Input": "Compound",
        "Output": "Other value",
        "Model Source": "DockerHub",
        "Service Class": "conda"
    }
```

### Operating environment

NA

**Comment by Malikbadmus** [comment]
@DhanshreeA ,it seems the issue occurs because the model source defaults to Dockerhub when no specific flag is set during fetching.

**Comment by DhanshreeA** [comment]
> @DhanshreeA ,it seems the issue occurs because the model source defaults to Dockerhub when no specific flag is set during fetching.

Interesting @Malikbadmus were you able to verify this?

**Comment by JoyProg** [comment]
@DhanshreeA I tried to reproduce this bug, but I didn't get the same output - both the Model Source and Service Class are null. Is there another way to fetch the model or has this been resolved? 

Output

   ```
 {
        "Identifier": "eos3wzy",
        "Slug": "qupkake",
        "Title": "Predict micro-pKa of organic molecules",
        "Status": "Ready",
        "Input": "Compound",
        "Output": "Other value",
        "Model Source": null,
        "Service Class": null
    }
```

Steps to reproduce
`fetch eos3wzy`
`ersilia catalog --local --more `

**Comment by Malikbadmus** [comment]
> > @DhanshreeA ,it seems the issue occurs because the model source defaults to Dockerhub when no specific flag is set during fetching.
> 
> Interesting @Malikbadmus were you able to verify this?

Yes @DhanshreeA , since Ersilia automatically fetches a model from Docker when the user specifies no other source,  the Model source is set to default to DockerHub when no flag is set during fetching.

The catalog command displays the correct output when the model is fetched from Github for Amazon S3.

![NEw](https://github.com/user-attachments/assets/5386d70a-cbf9-4440-99a9-56f02b5c7167)

**Comment by DhanshreeA** [comment]
> @DhanshreeA I tried to reproduce this bug, but I didn't get the same output - both the Model Source and Service Class are null. Is there another way to fetch the model or has this been resolved?
> 
> Output
> 
> ```
> {
>      "Identifier": "eos3wzy",
>      "Slug": "qupkake",
>      "Title": "Predict micro-pKa of organic molecules",
>      "Status": "Ready",
>      "Input": "Compound",
>      "Output": "Other value",
>      "Model Source": null,
>      "Service Class": null
>  }
> ```
> 
> Steps to reproduce `fetch eos3wzy` `ersilia catalog --local --more `

@JoyProg how did you fetch this model?

**Comment by JoyProg** [comment]
@DhanshreeA I ran `ersilia fetch eos3wzy `

**Comment by GemmaTuron** [comment]
Hi @JoyProg was the model actually fetched? from which source? IT would be useful to see the logs when you use the -v command

**Comment by GemmaTuron** [comment]
Hello @JoyProg 

Have you had a look at the logs when pasting them? I see the model is not being fetched, there seems to be an issue with your conda? First make sure to have ersilia up and running before tackling any issue. I'd suggest trying again one of the test models suggested to see if the error is repeated. try fetching from S3 if you were doing the fetching from Docker.

**Comment by JoyProg** [comment]
@GemmaTuron, ersilia is up and running, and my Conda setup (with Miniforge distribution) works. The error you see in the log is that it's looking in the wrong directory for the conda.sh file (which exists). Despite this, I've been able to fetch other models and work on other issues. 
Do I need to use that specific directory for the conda.sh file? If so, I'd be more than happy to. How can I adjust the setup to accommodate this requirement?

I also had wrote a method (for a different issue) to find the conda.sh file if you prefer I bypass it temporarily.

I ran this command to fetch the model
`ersilia -v  fetch eos3wzy --from_s3 `

and here's the log 
[fetch-eos3wzy-from-s3.log](https://github.com/user-attachments/files/17382782/fetch-eos3wzy-from-s3.log)

**Comment by GemmaTuron** [comment]
Hi @JoyProg have you tried to fetch other models, not this one, from S3 successfully? it is unclear to me if the other models were fetched via DockerHub only. Thanks!

**Comment by JoyProg** [comment]
@GemmaTuron  yes,  I have fetched other models successfully with and without using any source (e.g. S3, GitHub) flags

**Comment by JoyProg** [comment]
@GemmaTuron alternatively, could you share the command you ran to fetch the model and the logs?

**Comment by Malikbadmus** [comment]
@JoyProg, when you run the command `ersilia -v fetch eos3wzy`, you should get `DockerImageNotAvailableError` as it attempts to retrieve the model via Docker. However, this model does not yet have an associated Docker image. The issue you're encountering is likely due to running an outdated version of Ersilia in your local environment, which doesn’t include the latest changes. To resolve this, please update your Ersilia package to ensure it matches the latest changes on the remote branch.

@GemmaTuron @DhanshreeA ,  I'm encountering a list index out-of-range error when trying to fetch this model from S3,  this looks like the model is returning an empty result list during the fetching process, even though I can fetch it successfully from GitHub,  since the model is calculating pKa values, the input may lack acidic or basic compounds, which would result in no protonation sites being detected, leading to the model returning an empty list and triggering the error.

**Comment by GemmaTuron** [comment]
Hi @Malikbadmus 

thanks for the detailed follow up. Mmmm the problem should not be due to empty values, first because it would then fail randomly independently of the fetching platform and this is not the behaviour I assume? Also because the input molecules we use as example tend to have protonation sites, it would be surprising that so many do not have them.. This must be related to the model failing at Docker Build stage

**Comment by JoyProg** [comment]
Hi @Malikbadmus, thanks. How do I update ersilia? In the documentation, I see how to install, but not how to update. Do I uninstall and reinstall or is there a command I missed?

**Comment by GemmaTuron** [comment]
Hello @JoyProg 

with any package that you install from the cloned git repository via `pip install -e .` rebasing your local to the latest available in GitHub will automatically update the package

**Comment by JoyProg** [comment]
@GemmaTuron thank you. After updating ersilia, fetching the model causes my machine to run out of memory. Even after closing all other applications, the problem persists. I will do some more troubleshooting on my end. I thought to update in case there's a quicker solution.

Also,  I was able to fetch other models, but it is very slow and takes a significant amount of time compared to before.

**Comment by JoyProg** [comment]
Update: I have been able to resolve this issue after updating to the latest version due to issue #1329. When I attempt to fetch the model, I get an error: `AttributeError: 'ModelURLResolver' object has no attribute '_read_json_file'`

**Comment by DhanshreeA** [comment]
> Update: I have been able to resolve this issue after updating to the latest version due to issue [#1329](https://github.com/ersilia-os/ersilia/issues/1329). When I attempt to fetch the model, I get an error: `AttributeError: 'ModelURLResolver' object has no attribute '_read_json_file'`

This particular issue has been resolved in #1349 so ideally, this should work now.

**Comment by DhanshreeA** [comment]
> > > [@DhanshreeA](https://github.com/DhanshreeA) ,it seems the issue occurs because the model source defaults to Dockerhub when no specific flag is set during fetching.
> > 
> > 
> > Interesting [@Malikbadmus](https://github.com/Malikbadmus) were you able to verify this?
> 
> Yes [@DhanshreeA](https://github.com/DhanshreeA) , since Ersilia automatically fetches a model from Docker when the user specifies no other source, the Model source is set to default to DockerHub when no flag is set during fetching.
> 
> The catalog command displays the correct output when the model is fetched from Github for Amazon S3.
> 
> ![NEw](https://github.com/user-attachments/assets/5386d70a-cbf9-4440-99a9-56f02b5c7167)

@Malikbadmus was spot on with this. Ersilia does in fact resolve to using `DockerHub` as the default source when it cannot determine model source otherwise. This especially happens when the model is fetched using `repo_path`. Particularly, in this [line](https://github.com/ersilia-os/ersilia/blob/c4c790a20a0e85f07b3f4e7603559e30caba67b2/ersilia/hub/fetch/fetch.py#L79).

The way ersilia [determines](https://github.com/ersilia-os/ersilia/blob/c4c790a20a0e85f07b3f4e7603559e30caba67b2/ersilia/hub/fetch/fetch.py#L68C1-L77C10) sources:

```python
        sources = {
            self.force_from_github: "GitHub",
            self.force_from_s3: "Amazon S3",
            self.force_from_dockerhub: "DockerHub",
            self.force_from_hosted: "Hosted services",
            self.force_with_bentoml: "Bentoml",
            self.force_with_fastapi: "Fastapi",
            self.hosted_url is not None: "Hosted URL",
            self.local_dir is not None: "Local path",
        }
```
is a bit flawed, since the `local_dir` is never really set, when the user fetches a model using repo_path. The `local_dir` field gets set from the `--from_dir` flag. This issue is present due to legacy flags still continuing in ersilia, for example: #1370, which tackles removing the `repo_path` argument in favor of only keeping `--from_dir`. 


As for the model's docker build failing, that should be addressed in a separate issue within the model's repo.

**Comment by DhanshreeA** [comment]
I am closing this issue, since a [Dockerization](https://github.com/ersilia-os/eos3wzy/issues/2) issue already exists on the model's repo.
