### ISSUE TITLE
🐛 Bug: Error Running eos935d Model: Output File Not Created and Docker AMD64 Warning

### ISSUE THREAD

**Issue by JoyProg** [ersilia-os/ersilia#1287]
### Describe the bug.

When attempting to run the eos935d model, I encountered several issues. The fetch and serve commands took significantly longer to terminate than the other models I tested (eos4wt0 and eos6oli). Also, Docker Desktop displayed a warning, and an error message appeared in the terminal.

Docker Desktop displayed the following warning related to the AMD64 architecture:
`The image may have poor performance or fail if run via emulation`
This warning was tagged with AMD64, which might be important since I'm running on Apple Silicon (M1).

After the model was fetched and the process terminated, I received this error message in the terminal:
```
Detailed error: Standard model run from CSV was not possible for model eos935d Output file ~/eos/dest/eos935d/example_standard_output.csv was not created successfully
Hints: If you fetch this model from Docker Hub, or you are running it through URL, this is the first time run is executed in your local computer. Reach out to Ersilia to get specific help. 
```

Despite the warnings and error messages, an output was eventually generated. However, it would be ideal to resolve this in case there's an underlying issue.

### Describe the steps to reproduce the behavior

1. Activate the conda environment:
`conda activate ersilia`

2. Fetch the model:
`ersilia fetch eos935d`

Wait until the process terminates; the error should be displayed in the terminal, and the warning should appear in Docker Desktop. This issue may be specific to macOS (Apple Silicon), so it's recommended to reproduce it on a Mac.

### Operating environment

macOS Sonoma 14.6.1

**Comment by MissTife** [comment]
@DhanshreeA Hello, am I allowed to work on this?

**Comment by JoyProg** [comment]
I traced the problem to the base image used to build the Docker image for the model. The base image is designed for the linux/amd64 architecture which is not compatible with my system's ARM architecture. The ersilia fetch command is able to force-pull the image on my ARM machine, but Docker displays a warning indicating the architecture mismatch due to the difference between amd64 and arm64.

A **permanent solution** is to rebuild the Docker image for multi-platform compatibility. This would allow the image to run natively on both amd64 and arm64 systems without relying on emulation.

Here's the [Dockerfile in the model's GitHub repo](https://github.com/ersilia-os/eos935d/blob/main/Dockerfile) that shows how the Docker image is built. I wasn't sure about a suitable alternative base image that supports both architectures, so I didn't suggest one.

Thanks @MissTife for revisiting the issue.  @DhanshreeA could this be something worth looking into? Is the suggested solution of a multi-platform build feasible?

**Comment by DhanshreeA** [comment]
@JoyProg we do have [multi platform builds](https://github.com/ersilia-os/eos-template/blob/a3967b30b57375ff67c06c43897af9bbb73b41cf/.github/workflows/upload-bentoml.yml#L113) for our models, however it is possible that for this model the ARM build was not successful for some reason. You can [see](https://hub.docker.com/r/ersiliaos) that most of the model images indeed have both the AMD and ARM flavors. Why this model could not be built for ARM is a separate issue we will need to look into another time.
