### ISSUE TITLE
🐈 Task: Add ersilia base image docker upload to Ersilia Release workflow 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1293]
### Summary

Presently this [workflow](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-base-image-to-dockerhub.yml) that is supposed to build and upload Ersilia's docker images does not work because it relies on a [workflow](https://github.com/ersilia-os/ersilia/blob/c6b18a7ec51eb11bd87cb2a508f460c725fb419c/.github/workflows/ersilia-base-image-to-dockerhub.yml#L4) that does not exist. We replaced the `[Tag to verison]` workflow with a consolidated workflow called [Ersilia Release](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/publish.yaml).

Ersilia Release currently does the following:

- Version Ersilia
- Then run parallel jobs to create a release on GitHub, and on PyPI

We should add another parallel job that carries out the docker build and upload step for Ersilia's image.

**Comment by musasizivictoria** [comment]
@DhanshreeA  this should kindly be my next one to do.
Thanks

**Comment by rohitgupta29** [comment]
Hi @musasizivictoria I have almost completed working on this issue.   
Was unable to mention it yesterday due to an internet issue.  
If you have not started working on it, can you take another issue? :-)

**Comment by rohitgupta29** [comment]
@DhanshreeA : Our Problem Statement for this issue is to include docker build and upload from this [workflow](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-base-image-to-dockerhub.yml) to consolidated workflow called [Ersilia Release](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/publish.yaml), as a parallel job, besides version and releases to Github and PyPi. Is that correct?

**Comment by musasizivictoria** [comment]
> Hi @musasizivictoria I have almost completed working on this issue. Was unable to mention it yesterday due to an internet issue. If you have not started working on it, can you take another issue? :-)

oops!

**Comment by DhanshreeA** [comment]
@rohitgupta29 I am keeping this issue open because this wasn't assigned to you. Apologies!

**Comment by rohitgupta29** [comment]
Thank you @DhanshreeA!

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

I understand this was not completed? Should I put it back on hold? How critical is it?

**Comment by DhanshreeA** [comment]
@GemmaTuron I will reopen the other contributor (@musasizivictoria )'s PR since that contained a correct implementation. However, this is not critical at the moment.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Was the PR re-opened and merged?

**Comment by DhanshreeA** [comment]
Small update - this issue is being deprioritized. We cannot combine Ersilia's base image docker upload with the release workflow because we need the functionality to manually build these images, regardless of the release cycle. So, while I have added fixed the [trigger](https://github.com/ersilia-os/ersilia/blob/e09be0f95f65887ea9a16b4a27094bda01959743/.github/workflows/ersilia-base-image-to-dockerhub.yml#L8) for the base image upload workflow, there is still merit in keeping it independent to be able to build ersilia with out of release versions, like from master.
