### ISSUE TITLE
🐈 Task: Update release date field in CITATION.cff

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1294]
### Summary

At present the [CITATION.cff](https://github.com/ersilia-os/ersilia/blob/master/CITATION.cff) file has an older date, possibly corresponding to a very old release of Ersilia. We should make this field get updated anytime a release is created through the Ersilia Release [workflow](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/publish.yaml). 

The `date released` field should have the current date, ie when the release is published.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA I will work on this.

**Comment by marituhone** [comment]
@DhanshreeA  can i work in this issue?

**Comment by DhanshreeA** [comment]
@marituhone go ahead!

**Comment by OlawumiSalaam** [comment]
@OlawumiSalaam I worked on this issue. I had to close the PR request because you said we are to wait for you to assign issue first. Can I make a PR request for the issue? Thank you.

**Comment by DhanshreeA** [comment]
@OlawumiSalaam I don't see any updates from @marituhone and since your other PR has been merged, I am assigning this issue to you now.

**Comment by DhanshreeA** [comment]
@OlawumiSalaam let's give some time to @marituhone? If they don't come back with any updates, I will assign this issue to you. Thanks!

**Comment by dzumii** [comment]
@marituhone can you share your progress on this issue with us?

**Comment by DhanshreeA** [comment]
@OlawumiSalaam do you want to take this up again since there are no updates from @marituhone?

**Comment by OlawumiSalaam** [comment]
@DhanshreeA Yes I will.
