### ISSUE TITLE
Add model search functionality in the CLI

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#13]
# Background
Ersilia models can be browsed on the web. Although we do not have a good interface now, this can be done through an [Airtable base](https://airtable.com/shrUcrUnd7jB9ChZV). There is no way to search/filter models using the CLI. As of now, the only thing that can be done is: `ersilia catalog`, which simply prints all models on a table.

# Requested feature
We would like to have a search function in the ersilia CLI. For example: `ersilia catalog search --text "antimicrobial"` or `ersilia catalog search --mode "pretrained"`

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola Can I work on this issue?

**Comment by martwebber** [comment]
Hello @miquelduranfrigola, I would like to contribute to this.

**Comment by Riyabelle25** [comment]
Hello, I have experience with Software Development for ML tools, and would love to contribute here! I have set up Ersilia and have been going through the codebase. I would like to tackle this issue, can I start working on a PR for the same?

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola  I have looked into the codebase and worked around a little bit. I found that  catalog already has --search option 
![image](https://user-images.githubusercontent.com/54634163/160295480-33348a6d-ccb1-4bd2-9023-f228fad50ff3.png)
I worked on creating a new cli feature search which searches through the catalog and finds the model with text or model. It works like this 
![image](https://user-images.githubusercontent.com/54634163/160295562-5ffe40fe-7ad8-4ea7-b392-343c61d7fa74.png)
I'm a little confused with what is expected from this feature. Could you please provide a little bit more detail on this feature

**Comment by GemmaTuron** [comment]
Hello @anamika-yadav99, @martwebber, @Riyabelle25  

Thanks for your enthusiasm. Please, before continuing the work on this issue, refer to issue #36 and answer the questions there.
We also advise applicants to tackle one issue at a time, also leaving the opportunity to others to contribute. @Riyabelle25  and @anamika-yadav99 which issue are you most interested in pursuing? You have shown interest in a number of them.

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron I would like to work on this issue #13.

**Comment by miquelduranfrigola** [comment]
Thanks @anamika-yadav99! Thanks, and apologies for a confusing issue description.
The simplest will be to do the following:
`ersilia catalog --text 'antimalarial'`
and
`ersilia catalog --mode 'pretrained'`

**Comment by dauinh** [comment]
Hi @miquelduranfrigola, can I be assigned to work on this issue?
