### ISSUE TITLE
🐈 Task: Update Circle CI test script to remove deprecated api. 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1303]
### Summary

With the removal of the `api` command in ersilia, any workflows that make use of it would naturally fail, one such example being the Circle CI [workflow](https://github.com/ersilia-os/ersilia/blob/master/.circleci/config.yml). We simply need to remove the `api` command here.

**Comment by mercybassey** [comment]
Hi @DhanshreeA can i work on this?

**Comment by DhanshreeA** [comment]
Sure @mercybassey go ahead!
