### ISSUE TITLE
🐈 Task: Bump rdkit version in Ersilia setup

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1304]
### Summary

The [setup module](https://github.com/ersilia-os/ersilia/blob/master/ersilia/setup/requirements/compound.py) in ersilia that installs rdkit when compound inputs (ie SMILES strings) are encountered currently installs rdkit-pypi which has been deprecated in favor of simply 'rdkit'. We need to upgrade this, as well as pin a version, eg, `2023.9.1`.

**Comment by DhanshreeA** [comment]
Sure @daud99 go ahead!

**Comment by daud99** [comment]
@DhanshreeA on it.
