### ISSUE TITLE
🐛 Bug:  ModelURLResolver JSON Reading Method Missing

### ISSUE THREAD

**Issue by P-Mefut** [ersilia-os/ersilia#1329]
### Describe the bug.

This bug occurs when trying to fetch a model using the `Ersilia CLI`. The error trace shows that the process fails due to a missing method in the `ModelURLResolver class`. Specifically, the `_read_json_file` method is not defined, leading to an `AttributeError`.
The error originates in the process of resolving the URL for the hosted model. This can be clearly seen in the log file below.
[fetch_log.txt](https://github.com/user-attachments/files/17413573/fetch_log.txt)
 

### Describe the steps to reproduce the behavior

To reproduce this error, 
1. Pull changes from the Ersilia model Hub repo
2. activate your `ersilia env` and navigate to the `ersilia directory` on your local environment
3. run the `ersilia fetch "model"` command
4. error!

### Operating environment

WSL Ubuntu 20.04.6 LTS

**Comment by P-Mefut** [comment]
Hi @DhanshreeA please check this out!

**Comment by P-Mefut** [comment]
hi @DhanshreeA 

`Ersilia version: ersilia, version 0.1.37`
`Git commit:  b0b300e213e5c556189a1659629b1f316e2d2c0d`

**Comment by DhanshreeA** [comment]
@Abellegese do you want to take this up? 

It is clear from the logs that @P-Mefut has shared that the flow enters this block when evaluating `[do_hosted](https://github.com/ersilia-os/ersilia/blob/e88559cdce8064d522728746aec510bd88155a6e/ersilia/hub/fetch/fetch.py#L225)`. Under a normal fetch, this would happen when the user does not have docker active on their system.

In this file, I see that you are trying to read a JSON file, possibly the local cache, to get metadata about the models. However the method `[_read_json_file()](https://github.com/ersilia-os/ersilia/blob/e88559cdce8064d522728746aec510bd88155a6e/ersilia/hub/fetch/__init__.py#L27)` isn't actually defined in the `ModelURLResolver` class. 

I also see a bunch of other constants (L6-L14 in the file mentioned above) that a) should go into the `[default.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/default.py)` file, b) are not really being used.

**Comment by P-Mefut** [comment]
Hello @DhanshreeA I figured you where working on this since you self assigned it to yourself, is that not the case🤔

**Comment by DhanshreeA** [comment]
Hi @P-Mefut I am letting the maintainers handle this one for now. Thank you!

**Comment by P-Mefut** [comment]
So it's safe to say for the pytest I was working on I can just clone the repo and do the testing since I can't use the fetch command right now

**Comment by miquelduranfrigola** [comment]
Thanks all. This one is quite critical so let's prioritise it.

**Comment by DhanshreeA** [comment]
@P-Mefut this should be fixed now anyway and shouldn't hinder your work.

**Comment by P-Mefut** [comment]
Thank you @DhanshreeA😀
