### ISSUE TITLE
🦠 Model Request: BBBP model tested on marine-derived kinase inhibitors

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1339]
### Model Name

BBBP model tested on marine-derived kinase inhibitors

### Model Description

Developed binary ensemble classifiers to predict the Blood-Brain Barrier (BBB) permeability of small organic compounds. Applied our best models to natural products of marine origin, able to inhibit kinases associated with neurodegenerative disorders.

### Slug

bbbp-marine-kinase-inhibitors

### Tag

Drug-likeness, Permeability

### Publication

https://pubmed.ncbi.nlm.nih.gov/30699889/

### Source Code

https://github.com/plissonf/BBB-Models

### License

MIT

**Comment by miquelduranfrigola** [comment]
It was not possible to use the pickled models (python 2?) so I have decided to retrain the models following the notebooks provided by the author

**Comment by miquelduranfrigola** [comment]
@DhanshreeA I think this model has been successfully incorporated. Please check it and feel free to close the issue.

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola and @DhanshreeA  I will test the model and close the issue

**Comment by GemmaTuron** [comment]
the model works @miquelduranfrigola I will close this issue. Please have a look at my comment on the model testing issue Miquel
