### ISSUE TITLE
🐈 Task: Blacken code in CI/CD

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1356]
### Summary

All code in ersilia should be blackened (formatted) with the `black` tool.
I suggest that we do this in CI/CD. I am quite confident GitHub Actions exist to format code.

### Objective(s)

- Have well formatted code in Ersilia using `black`.
- Do the formatting in GitHub Actions.

### Documentation

N/A

**Comment by daud99** [comment]
@DhanshreeA If you feel like I can look into this.

**Comment by DhanshreeA** [comment]
The action plan is to incorporate `ruff format` in the pipeline, as well as look into using `ruff check --fix` in the codebase to fix several linting errors. We're considering ruff because it is many times faster than Black.

**Comment by daud99** [comment]
@DhanshreeA Ruff sounds like a great choice, especially with the speed boost. Happy to help with the setup if needed!

**Comment by GemmaTuron** [comment]
Is this related to #1417 ? 
Please let's avoid issue duplication.

**Comment by DhanshreeA** [comment]
> Is this related to #1417 ? Please let's avoid issue duplication.

Hi @GemmaTuron yes this is related. I am closing this issue because the other one has more features which we should ideally have.
