### ISSUE TITLE
🐛 Bug: Hard-coded URL in pytest

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1367]
### Describe the bug.

Hi @Abellegese , in this pytest file: https://github.com/ersilia-os/ersilia/blob/master/test/test_url_search.py I see a hard-coded DigitalOcean URL. We should not have it like this since these URLs can change.

### Describe the steps to reproduce the behavior

N/A

### Operating environment

Ubuntu 20.04 LTS

**Comment by miquelduranfrigola** [comment]
Hi @Abellegese and @DhanshreeA - I believe this was already corrected in an online 1-1 meeting with @Abellegese. Not sure if the PR has been merged yet. Please close the issue when it is done!

**Comment by DhanshreeA** [comment]
@Abellegese is this done? Can we close this?

**Comment by Abellegese** [comment]
Hi @DhanshreeA the fix was a part of pytest since its in pytest and didnt push it yet.

**Comment by DhanshreeA** [comment]
@Abellegese is this good to close now?

**Comment by Abellegese** [comment]
Yes @DhanshreeA

**Comment by DhanshreeA** [comment]
@Abellegese the "hard-coded" url still exists [here](https://github.com/ersilia-os/ersilia/blob/41e1e7ede50fcaff4ef25d04c8637109d198df29/test/test_url_search.py#L62) though. Can you mock the return value perhaps?

**Comment by Abellegese** [comment]
Ohh @DhanshreeA yeah my bad. So let create some fix.

**Comment by Abellegese** [comment]
May be use catelog command to get url from metadata. What do you think @DhanshreeA .

**Comment by DhanshreeA** [comment]
This is addressed in the merged PR.
