### ISSUE TITLE
🐈 Task: Merge ersilia sample command with ersilia example command as a flag

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1369]
### Summary

Refer to batch: https://github.com/ersilia-os/ersilia/issues/1262

Ersilia presently has two commands `ersilia example`, and `ersilia sample`, which perform overlapping functionality. 

- `ersilia sample` generates permutations of models and model example inputs, ie it randomly selects a few models from the hub, and generates their example inputs. 
- `ersilia example` generates example inputs for any given model id, or it infers the model id from the presently active model session.

The example command can be extended with a `sample_models` flag to sample a given number of models, and then generate a given number of example inputs for those models.

### Objective(s)

- [ ] De-register the `sample` command [here](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/cli/create_cli.py#L26) and [here](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/cli/cmd.py#L49), and remove its source[ file](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/sample.py).
- [ ] Add a flag `--sample_models` to the example [command](https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/example.py) and implement this functionality if the flag is set by way of using the [`ModelSampler`](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/db/hubdata/samplers.py#L24) class as in the implementation of the `sample` command.

**Comment by mustafaahsan10** [comment]
If it is still an open issue, i would like to contribute

**Comment by staru09** [comment]
Hi is this open to work?
