### ISSUE TITLE
🐈 Task: Remove duplicate flag --repo_path from the fetch command

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1370]
### Summary

Refer to #1262 

The `--repo_path`  flag is a duplicate of the `--from_dir` flag since both expect the local path of a model's directory (repository). Currently the `--from_dir` flag is used only in [setting](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/hub/fetch/fetch.py#L76) the model source, and is not really used elsewhere. Users and contributors mainly use the `repo_path` flag to fetch a locally available model, however for the sake of consistency across nomenclature, we should favor keeping `--from_dir` instead of `--repo_path`, since that is how the other source flags are specified (eg --from_github, --from_dockerhub etc)

### Objective(s)

- [x] Remove the [`--repo_path`](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/cli/commands/fetch.py#L25) flag in favor of only keeping the `--from_dir` flag. 
- [x] For sake of backward compatibility and not breaking the rest of the code, we can set [`repo_path`](https://github.com/ersilia-os/ersilia/blob/bb202b261bb6d4bbe658d207aba7f0c3de495787/ersilia/cli/commands/fetch.py#L108) argument in the `ModelFetcher` class's constructor with the value the user inputs through `from_dir`.

**Comment by snufkinwa** [comment]
Hi, I'd like to contribute to this issue if it's still available.

**Comment by DhanshreeA** [comment]
Hi @snufkinwa thank you for your interest in working on this. We are still finalizing whether we want to address this issue or not.

**Comment by DhanshreeA** [comment]
@miquelduranfrigola @GemmaTuron what do you both think? I know we've been using `repo_path` from quite some time now but it was also developed in the early days of ersilia when we hadn't formalized the CLI to the extent that exists now. So I vote removing this flag and actually using the `from_dir` flag.

**Comment by snufkinwa** [comment]
Let me know! If there are any other first-time issues I can contribute to, I'd love to help.

**Comment by DhanshreeA** [comment]
@snufkinwa I have discussed with @miquelduranfrigola - we do indeed want to get rid of this. If you're still interested in taking this up, I'll be happy to provide support.

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA 

Completely agree with this. We just need to be extra careful with the pipelines/workflows that are using `--repo_path`

**Comment by snufkinwa** [comment]
@DhanshreeA Yes, I'll take this on—thank you for the support! I’m on board with removing `--repo_path`. Just to make sure I’m covering everything, could you let me know which specific pipelines or workflows rely on `--repo_path`? I want to make sure the transition goes smoothly.

**Comment by DhanshreeA** [comment]
Hi @snufkinwa so on a [quick review](https://github.com/search?q=org%3Aersilia-os+--repo_path&type=code&p=1) of where `--repo_path` is used across all the repositories within Ersilia, I see that it is mainly used in our model [test](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model-pr.yml) [workflows](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model.yml). For now I think it's best if you just focus on the fetch.py file (as you've linked above).

**Comment by DhanshreeA** [comment]
This has been addressed in the linked PR.
