### ISSUE TITLE
🐛 Bug: Ersilia catalog command not showing all models fetched

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1373]
### Describe the bug.

Hi @DhanshreeA 

I have several models fetched through DockerHub
When I run `ersilia catalog --local`, some models do not appear. Yet, when I then fetch them, the following message appears:

```
8:05:10 | DEBUG    | Trying to get metadata from: /home/gturon/eos/dest/eos7kpb
⬇️  Fetching model eos7kpb: h3d-virtual-screening-cascade-light
18:05:11 | DEBUG    | Initialized with URL: None
18:05:11 | DEBUG    | Getting model source
18:05:11 | DEBUG    | Model getting fetched from DockerHub
18:05:11 | DEBUG    | Starting fetching procedure
18:05:11 | DEBUG    | Decided to fetch from DockerHub
18:05:11 | DEBUG    | Fetching from DockerHub
18:05:11 | DEBUG    | Pulling model image from DockerHub
18:05:11 | DEBUG    | Image ersiliaos/eos7kpb:latest is available locally
Requested image eos7kpb is available locally. Do you still want to fetch it?
```

Does this mean that the model is ACTUALLY available locally but Ersilia catalog is not picking it?

### Operating environment

Ubuntu 22.04 LTS

**Comment by DhanshreeA** [comment]
There are a couple of things that could have happened here. 

The eos folder has the following structure:

```bash
...
├── dest <--- Useful when model is fetched from source, otherwise has same content as repository
├── repository <--- Stores the model bundle, however it is fetched
├── sessions
└── tmp
```
The `ModelCatalog` class only [looks](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/content/catalog.py#L307) at the `repository` directory, when fetching the local catalog. 

If a model is not displayed by the catalog, it's possible that:
- The bundle directory did not get created despite the model fetching somewhat 'halfway', as in the image got fetched, but it failed to [register](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/fetch/lazy_fetchers/dockerhub.py#L147) with ersilia by creating a bundle. 
- The bundle directory got deleted during model delete, but the image did not.

The second situation is possible under the circumstances when the Docker engine is not active on your system and Ersilia [silently exits](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/delete/delete.py#L217) without actually deleting the image. This of course needs to be addressed as its own issue.

Finally, the ModellPuller the functionality to check first if the image is available locally, [displays the message](https://github.com/ersilia-os/ersilia/blame/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/pull/pull.py#L194) "Requested image <eosid> is available locally. Do you still want to fetch it?" and [waits](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/utils/terminal.py#L81) for user input for upto five seconds, with the default value always being yes. In that time, if you specify 'n', Ersilia will skip pulling the image from DockerHub, and continue fetching the model on the system.

**Comment by DhanshreeA** [comment]
@GemmaTuron, few updates from last time:
> The bundle directory did not get created despite the model fetching somewhat 'halfway', as in the image got fetched, but it failed to [register](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/fetch/lazy_fetchers/dockerhub.py#L147) with ersilia by creating a bundle.

We have [pushed a fix](The bundle directory did not get created despite the model fetching somewhat 'halfway', as in the image got fetched, but it failed to [register](https://github.com/ersilia-os/ersilia/blob/9a8cfcbde99ebd2456fd8d12e0545fcf98a13646/ersilia/hub/fetch/lazy_fetchers/dockerhub.py#L147) with ersilia by creating a bundle.) for this - now models would not exist in this halfway state of being fetched and not fetched because of failure from the StandardModelExample error. 

For the silent exit situation, I have created its own [issue](https://github.com/ersilia-os/ersilia/issues/1395).

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Thansk for the update. Is this issue ready to be closed then?

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Please what is the status of this issue?

**Comment by DhanshreeA** [comment]
Yes, this is good to close because this isn't a catalog issue, rather has to do with fetch and delete commands which are being handled in their specific issues.
