### ISSUE TITLE
🦠 Model Request: Projections against ChemDiv

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1375]
### Model Name

Chemical space 2D projections against ChemDiv

### Model Description

This tool performs PCA, UMAP and tSNE projections taking a 100k ChemDiv diversity set as a chemical space of reference. The Ersilia Compound Embeddings as used as descriptors. Four PCA components and two UMAP and tSNE components are returned.

### Slug

chemical-space-projections-chemdiv

### Tag

Descriptor

### Publication

https://www.chemdiv.com/catalog/diversity-libraries/representative-diversity-libraries-out-of-1-6m-stock/

### Source Code

https://github.com/ersilia-os/compound-embedding

### License

GPL-3.0-or-later

**Comment by GemmaTuron** [comment]
This model has the same issues as #1372 
Please follow ersilia-os/eos2db3#1 for more info

**Comment by DhanshreeA** [comment]
I need someone to confirm what output they get if they run the model again. I am getting the expected output when fetching from DockerHub. 

Attached here for reference: [output_eos2db3.csv](https://github.com/user-attachments/files/18197253/output_eos2db3.csv)

**Comment by miquelduranfrigola** [comment]
Looks good to me. I think we are ready to close.
