### ISSUE TITLE
🦠 Model Request: Projections against Coconut

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#1376]
### Model Name

Projections against Coconut

### Model Description

This tool performs PCA, UMAP and tSNE projections taking the Coconut natural products database as a chemical space of reference. The Ersilia Compound Embeddings as used as descriptors. Four PCA components and two UMAP and tSNE components are returned.

### Slug

chemical-space-projections-coconut

### Tag

Descriptor

### Publication

https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00478-9

### Source Code

https://github.com/ersilia-os/compound-embedding

### License

GPL-3.0-or-later

**Comment by miquelduranfrigola** [comment]
Note: I could not do all of Coconut due to computational constrains. I did 100k samples. This should be sufficient.

**Comment by DhanshreeA** [comment]
Can we close this issue @miquelduranfrigola? The model works, when fetching from DockerHub. Attaching reference output:

```
key,input,pca-1,pca-2,pca-3,pca-4,umap-1,umap-2,tsne-1,tsne-2
WJBSSBFGPKTMQQ-UHFFFAOYSA-N,FC(F)(F)Oc1ccc2nc([nH]c2c1)-c1ccc(OCCOCCOc2ccc(nc2)-c2nc3ccc(OC(F)(F)F)cc3[nH]2)cn1,-0.7112633,0.8127247,-0.47454613,0.4763325,-0.19813196,-0.058237612,0.002980697249046606,-0.36209010331480196
KBPLFHHGFOOTCA-UHFFFAOYSA-N,CCCCCCCCO,-0.62610865,0.8681326,-0.4768249,0.5767763,0.057031,0.009470731,0.6131163510161718,0.55130987632211
HPFLVTSWRFCPCV-UHFFFAOYSA-N,O=C(NCCN1CCN(CC1)c1ncccn1)C12CC3CC(CC(C3)C1)C2,-0.6983994,0.9327282,-0.4218503,0.5212621,0.0038883537,0.115905255,-0.04984543532642856,0.7711701576729834
LBGFKUUHOPIEMA-PEARBKPGSA-N,CCCCCCCCCCCCCCCC(=O)Nc1ccn([C@@H]2O[C@H](CO)[C@@H](O)[C@@H]2C#N)c(=O)n1,-0.54696935,0.8726731,-0.44211844,0.507187,0.09826115,0.076915026,0.557471925136206,-0.16387867618006058
XVOOCQSWCCRVDY-UHFFFAOYSA-N,COc1cc(Br)c(Nc2nc(cs2)-c2c(C)nc3ncccn23)c(Br)c1,-0.752904,0.88906515,-0.46383947,0.5071666,-0.100545205,0.088442,-0.2496783627086539,0.2472669016565068
```

**Comment by miquelduranfrigola** [comment]
This looks good. Ready to close.
