### ISSUE TITLE
Outreachy Documentation Project: <Harshita>

### ISSUE THREAD

**Issue by harshita214** [ersilia-os/ersilia#144]
Applicant: [harshita214](https://github.com/harshita214)
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [X] Create a README file with the name <README_yourname.md> under the /documentation folder
- [X] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [X] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by harshita214** [comment]
Hello @GemmaTuron 

I created a PR https://github.com/ersilia-os/ersilia/pull/178 for the issue 

1. https://github.com/ersilia-os/ersilia/issues/11
2. https://github.com/ersilia-os/ersilia/issues/49

* PR is not yet reviewed/merged and requires mentor's approval

**Comment by harshita214** [comment]
While working on Readme, I saw many readme files and came across the point that a Contributing.md is also required which is a separate readme file. This readme file basically contains the following point

- [ ] How to start
- [ ] Submit a PR - STEPS
- [ ] Architecture- files structure
- [ ] Setup From Source
- [ ] Explanation of Important terms used in Ersilia
- [ ] Technology Stack
- [ ] Coding/PR standards
- [ ] Tutorials/Blogs for more reference
- [ ] Other Ways to contribute
- [ ] Resources

@GemmaTuron I am really keen to know your response on this and to know your feedback.
If all seems good, I am ready to form a Draft "Contributing.md"  to get it reviewed

**Comment by harshita214** [comment]
In India, there is a proverb " पहला सुख निरोगी काया " which means First happiness is a healthy body.  This means whether it be anyone or everyone health and healthcare are a priority for all! So when I came across this project through Outreachy and understood the concept, which became more clear after attending the meet by @GemmaTuron. 

One line "Ersilia aims to provide AI models to enable scientists to make drug discovery much quicker" made me realize the impact of Ersilia. This line made me intrigued to know more and more about Ersilia and eventually to be part of  Ersilia. The reason behind, I understand the gravity of the situation, I know how important drug discovery is! Especially in India, where infants, children, and most importantly women especially all those who are pregnant or suffer from chronic diseases like cancer, etc. die from illnesses that have few or insufficient drugs.

I am as a part community it's my duty to give back to society ,and Ersilia is doing the same noble cause. I will be glad and honored to be part of community and give my best.

**Comment by harshita214** [comment]
Under Graphic material
 

- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x]  Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x]  Create one image/slide to explain Ersilia’s mission and vision
- [x]  Link to the image/slide as a comment under this issue
- [ ]  Incorporate feedback from the mentor

For third checkpoint, click [here](https://bitmesra-my.sharepoint.com/:p:/g/personal/btech25053_20_bitmesra_ac_in/EVGAfhC6ElBJga-59f_KIoIB-If6bTfCIF5c-kP8Y4G8ng?e=EV6FRc)


@GemmaTuron kindly provide feedback for the same 😄

**Comment by harshita214** [comment]
**Twitter Template for The Release of New Models**

<hr>

Did you know our "Model name" is out which can predict in just a single click?! Join the main contributor 
and another main contributor on (Any date) for a Talk and Q/A session to know more about it 🤩

This is another step of Ersilia in helping researchers and towards our aim 💯 

1/3

<hr>

This model is one of the best releases till now due to many reasons like
...
...
Isn't this interesting to know more click here (link) 🔗 

Also, don't forget to check out our codebase on GitHub(link) which is absolutely open for enthusiastic contributors like you!

2/3

<hr>

The main creditors behind this accomplishment are ( Twitter handles of all the persons )

Also checkout our blog and website for more information

**Comment by GemmaTuron** [comment]
Hi @harshita214 

I have merged your readme. You made a lot of work on the installation and instructions, and have a direct way of introducing the project which I think is nice. For a README though, it is a bit too long. I think the information and images from the website do not need to be on the README which should focus on the Hub only. Can you modify it?

**Comment by GemmaTuron** [comment]
> **Twitter Template for The Release of New Models**
> 
> Did you know our "Model name" is out which can predict in just a single click?! Join the main contributor and another main contributor on (Any date) for a Talk and Q/A session to know more about it 🤩
> 
> This is another step of Ersilia in helping researchers and towards our aim 💯
> 
> 1/3
> 
> This model is one of the best releases till now due to many reasons like ... ... Isn't this interesting to know more click here (link) 🔗
> 
> Also, don't forget to check out our codebase on GitHub(link) which is absolutely open for enthusiastic contributors like you!
> 
> 2/3
> 
> The main creditors behind this accomplishment are ( Twitter handles of all the persons )
> 
> Also checkout our blog and website for more information


I like the style, but some re-wording of the first sentence would be good!
Did you know our "Model name" is out which can predict in just a single click?! - predict what?

**Comment by harshita214** [comment]
> Hi @harshita214
> 
> I have merged your readme. You made a lot of work on the installation and instructions, and have a direct way of introducing the project which I think is nice. For a README though, it is a bit too long. I think the information and images from the website do not need to be on the README which should focus on the Hub only. Can you modify it?

Sure yes, I am getting your point, I will do the modifications. Thank you so much for your feedback.
For the installation part can we make a new readme with pictures since I believe Installations are essential and are actually the first step so it will help contributors a lot. On the website, pictures are not there.

**Comment by harshita214** [comment]
> > **Twitter Template for The Release of New Models**
> > Did you know our "Model name" is out which can predict in just a single click?! Join the main contributor and another main contributor on (Any date) for a Talk and Q/A session to know more about it 🤩
> > This is another step of Ersilia in helping researchers and towards our aim 💯
> > 1/3
> > This model is one of the best releases till now due to many reasons like ... ... Isn't this interesting to know more click here (link) 🔗
> > Also, don't forget to check out our codebase on GitHub(link) which is absolutely open for enthusiastic contributors like you!
> > 2/3
> > The main creditors behind this accomplishment are ( Twitter handles of all the persons )
> > Also check out our blog and website for more information
> 
> I like the style, but some re-wording of the first sentence would be good! Did you know our "Model name" is out which can predict in just a single click?! - predict what?

Thanks for the compliment 😄 
Okay I will make the changes and modify it

**Comment by harshita214** [comment]
> Under Graphic material
> 
> * [x]  Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
> * [x]   Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
> * [x]   Create one image/slide to explain Ersilia’s mission and vision
> * [x]   Link to the image/slide as a comment under this issue
> * [ ]   Incorporate feedback from the mentor
> 
> For third checkpoint, click [here](https://bitmesra-my.sharepoint.com/:p:/g/personal/btech25053_20_bitmesra_ac_in/EVGAfhC6ElBJga-59f_KIoIB-If6bTfCIF5c-kP8Y4G8ng?e=EV6FRc)
> 
> @GemmaTuron kindly provide feedback for the same 😄

https://bitmesra-my.sharepoint.com/:p:/g/personal/btech25053_20_bitmesra_ac_in/EVGAfhC6ElBJga-59f_KIoIB-If6bTfCIF5c-kP8Y4G8ng?e=XbF3MO

**Comment by harshita214** [comment]
![image](https://user-images.githubusercontent.com/79797000/162579348-e3d611f2-6f33-4486-af08-d5f38741a599.png)

Made this while thinking about Ersilia. All types of feedback are appreciated :) 

Ps: It's not any task-related, I can delete it as well if it's violating any rule.

**Comment by harshita214** [comment]
For Newsletter, Kindly view this doc file @GemmaTuron 

https://docs.google.com/document/d/1PP-qEORGE4PVUoNxgc4P4wFxYK9KMVv00DqBezvwShg/edit?usp=sharing

**Comment by harshita214** [comment]
Strategic plan 2021-2023 blogpost link 

https://docs.google.com/document/d/1SJE5IWMzxyu2hDj7jwj2Uq0h-KY5PEaEcWxtmvoN9e4/edit?usp=sharing

@GemmaTuron Kindly review it :)

**Comment by GemmaTuron** [comment]
Hi @harshita214 

You have done a lot of work, thank you for your efforts!
- I have left some comments in the Newsletter, but good template
- Strategic goals: thanks for the infographic!
- Mission and Vision: I like how you emphasize that healthcare researchers may not have the tech skills to use AI/ML, not everyone is aware of it. I would avoid generalistic comments such as "Our goal is to work for people" 

If you are working in any other tasks add them here in the comments, otherwise check my feedback and start preparing your final application!

**Comment by harshita214** [comment]
> Hi @harshita214
> 
> You have done a lot of work, thank you for your efforts!
> 
> * I have left some comments in the Newsletter, but good template
> * Strategic goals: thanks for the infographic!
> * Mission and Vision: I like how you emphasize that healthcare researchers may not have the tech skills to use AI/ML, not everyone is aware of it. I would avoid generalistic comments such as "Our goal is to work for people"
> 
> If you are working in any other tasks add them here in the comments, otherwise, check my feedback and start preparing your final application!

@GemmaTuron Thanks for the feedback 
I am happy to contribute :), Yes, I will make all the changes by tomorrow and will revert to you.

For the newsletter, I will make the appropriate changes
Yes I will keep in mind to avoid generalistic comments 

Currently, I am working on the Scientific Content task of writing a Technical card. Apart from it, I am also working on issue #198

**Comment by harshita214** [comment]
**Twitter Template for The Release of New Models**

<hr>

Holla people! 

Ersilia is excited to share that we have released our new model which predicts the detection of cancer cells in just one click! Isn't this intriguing?! Sure it is so join us on 18th April at 17:00 GMT to interact with the main contributor and another main contributor for a Talk and Q/A session to know more about it 🤩

This is another step of Ersilia in helping researchers and toward our aim 💯 

1/3

<hr>

This model is one of the best releases till now due to many reasons like
...
...
Isn't this interesting to know more click here (link) 🔗 

Also, don't forget to check out our codebase on GitHub(link) which is absolutely open for enthusiastic contributors like you!
We are also open to new ideas, funders and researchers 😄 

2/3

<hr>

The main creditors behind this accomplishment are ( Twitter handles of all the persons )

Also, check out our blog and website for more information


@GemmaTuron Modified the template as suggested

**Comment by harshita214** [comment]
https://docs.google.com/document/d/1PP-qEORGE4PVUoNxgc4P4wFxYK9KMVv00DqBezvwShg/edit?usp=sharing

Modified the newsletter

**Comment by harshita214** [comment]
@GemmaTuron I didn't find any comments on Strategic post 
Is there any modification which is needed there also?

**Comment by harshita214** [comment]
**<h1>Technical Card </h1>** 

### **Model ID**: [eos65rt](https://github.com/ersilia-os/eos65rt)

### **Model**: LogP calculation based on fluorescent data

### **Description**: 

<h4> LogP calculation is used for fluorescent data for membrane permeability

Small-molecule fluorescent probes are becoming powerful biomedical reagents to advance cell biology and drug discovery research, as well as cancer diagnostics. For Ersilia it's a really important model and for the medic world also. Especially since this model is used for cancer diagnostics.

When it comes to cell permeability the LogP descriptor is the most significant descriptor 8–11. It has been shown that drugs with good cell permeability exhibit moderate LogP values 12,13. The Lipinski rule of five that is used to evaluate the drug-likeness of compounds indicates a moderate LogP range (− 0.5 < LogP < 5) for sub- stances with good cell permeability 14. Various LogP descriptors have already been developed that can be used to build models for cell permeability.  Another class of algorithms, e.g. MLogP19, calculate LogP by using molecular properties such as 3-D structures or topological indices. The consensus LogP (cLogP) descriptor calculates the average LogP from multiple LogP models with improved accuracy 20.  </h4>

_Hyperparameter tuning in neural network-based models is essential for accurate predictions._

### **Algorithm**:  fingerprint algorithm, deep neural network (DNN)

### **Input** : Compounds

### **Output**: Permeability, Physicochemical property

### **Github Repository**: [here](https://github.com/k-soliman/DeepFl-LogP)
### **Publication**: [here](https://www.nature.com/articles/s41598-021-86460-3.epdf?sharing_token=zmYZd6qpwnDwc8tCOYGGf9RgN0jAjWel9jnR3ZoTv0OXuXXr_ZS6VuKQMyMJiA3PeIcqAJZTcpcNZJHblyChkQ2eTpzGXq23YsIcFlG8ayuEptKCJ1DeyIRGrh9O2d5JvvGGB9qG8cXgAuy_k-e1ncAMkAzpTegmR0XUbnftjv0%3D)

**Comment by harshita214** [comment]
Created a PR @GemmaTuron 
- https://github.com/ersilia-os/ersilia/pull/240

Issue the PR is solving 
- https://github.com/ersilia-os/ersilia/issues/198
- https://github.com/ersilia-os/ersilia/issues/21

**Comment by wintermornings00** [comment]
Great work! @harshita214

**Comment by harshita214** [comment]
Thank you @wintermornings00 :)

**Comment by GemmaTuron** [comment]
Hi @harshita214 

Thanks, I have merged all your PR!

**Comment by sophiee-blip** [comment]
Nice job!

**Comment by harshita214** [comment]
Submitted my final application ✨ 
Closing this Issue 

Thank you @GemmaTuron and @miquelduranfrigola for the guidance ❤️
