### ISSUE TITLE
Set up an Issue Template for Model Requests

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#15]
Create a template for an issue to request a model incorporation in the hub. Important questions to keep in mind are: name of the model, why is it for, license, where is the code living... 
If someone else is working on this, you can create a new template or contribute your ideas to the existing one.

**Comment by ifeoluwafavour** [comment]
I'm interested in this issue and would love to contribute to it to tackle it

**Comment by victorabba** [comment]
I would love to tackle this issue as well.

**Comment by AishaSaman** [comment]
Hi, I am Aisha and I am Outreachy internship applicant. 

I have done few changes in Issue: Model request. Please check them.

**Comment by ifeoluwafavour** [comment]
> I'm interested in this issue and would love to contribute to it to tackle it

I have added the issue template. It is on issue #23

**Comment by GemmaTuron** [comment]
> > I'm interested in this issue and would love to contribute to it to tackle it
> 
> I have added the issue template. It is on issue #23

Hello @ifeoluwafavour thanks for your contribution! please remember to record contributions in the Outreachy website

**Comment by GemmaTuron** [comment]
> I would love to tackle this issue as well.

Hello @victorabba please see issue #23 to continue working on this, thanks!

**Comment by GemmaTuron** [comment]
> Hi, I am Aisha and I am Outreachy internship applicant.
> 
> I have done few changes in Issue: Model request. Please check them.

Hello @AishaSaman I do not find the issue you mention. Could you please link here the number of the issue for me to follow up? thanks!

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron can this issue be closed? I think that people have been redirected to issue #23, correct? Feel free to close issue or nominate assignees.

**Comment by GemmaTuron** [comment]
Hi,

This issue has been tackled in #23, I will close this contribution and answer the discussions there! @AnshuKumari197 please check the new contribution guidelines to continue working!
