### ISSUE TITLE
Outreachy Documentation Project: <Ugochi Juliet>

### ISSUE THREAD

**Issue by julietugo** [ersilia-os/ersilia#150]
Applicant: @julietugo 
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [x] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by julietugo** [comment]
I am interested in this project because Ersilia’s work supports research in infectious and neglected diseases. This work will help us understand how the body's immune system responds to disease, ways to prevent the disease and develop the right treatment. My passion for good health motivates me to join Ersilia in their good work.

**Comment by julietugo** [comment]
Hello @GemmaTuron, here is the link to the blog post about Ersilia's Strategic Plan 2021 -2023 https://docs.google.com/document/d/19PIg4nPzECiMuQEWHo8R3xB57mBn19c55huVI4f6kNk/edit?usp=sharing

**Comment by GemmaTuron** [comment]
Hi @julietugo 

I like how you have summarized our goals and vision, thanks for the work! Please go ahead with your next contributions!

**Comment by julietugo** [comment]
Thanks for the feedback @GemmaTuron. I am working on other contributions.

**Comment by julietugo** [comment]
Hello @GemmaTuron, this is the blog post on a topic focusing on AI/ML for biomedical research - https://docs.google.com/document/d/1QuGJMCME_Y_2q1MqhTnKIq3OScuY4teOEGQ6h4HUBzA/edit?usp=sharing

**Comment by julietugo** [comment]
Hi @GemmaTuron, I created two templates for the Twitter post. A can be used to make announcements of new models, an addition to the team, a new partnership with LMIC institutions, etc. B can also be used to announce new models, and then have a thread explaining further. 

Let me know what you think please, thank you.

**Templates for Twitter post for Ersilia**
A 
It's another big announcement day at Ersilia!
Today is all about new models: We've incorporated a new model into our hub. The new model allows you [function of new model]. This model is called [name of model]. In the coming weeks, we will let you know how this model affects science.
 
B
We're excited to announce the introduction of a new model [name of model]. This model simulates a wide variety [function of model]. Below is a thread that discusses the impact of this new model and how it will interest you as a researcher. 👇

**Comment by GemmaTuron** [comment]
Hi @julietugo !

Good work in using a reference to where we can find AI in society, it helps people understand! Also nice that you checked we are gold-level endorsers of the principles for digital development!
I would suggest focusing on finishing off any tasks you are working on and preparing the final application!

**Comment by julietugo** [comment]
I'll do that, @GemmaTuron. Thank you so much for your comments.

Meanwhile, here is the link to the image on the vision and mission of Ersilia - https://bit.ly/38CZuoA

**Comment by julietugo** [comment]
Here is the link to the technical card - https://bit.ly/3rorzXk

Let me know what you think @GemmaTuron. Thank you. 

The 3 new models that can be incorporated into the Ersilia hub are: chemprop-SARS, chemprop-AMU SARS-CoV-2 in vitro, and Coulomb matrix.

**Comment by julietugo** [comment]
Hi @pauline-banye, thank you so much for your comment. 

For Ersilia, I mentioned them towards the end of the article. And since it'll be (assuming Ersilia decides to use it) posted on the Ersilia website/blog, then the reader will look around the site after reading and click on more links.

**Comment by julietugo** [comment]
Hi @GemmaTuron, here is the [readme file](https://github.com/ersilia-os/ersilia/pull/231) I created

**Comment by julietugo** [comment]
Thank you @GemmaTuron. I'm grateful for your feedback. 

I have moved the [readme](https://github.com/ersilia-os/ersilia/pull/235) file into the documentation folder.

**Comment by GemmaTuron** [comment]
Hi @julietugo 


Thanks I have merged the PR, I think now you should focus on writing the final application, many thanks for all the work!

**Comment by julietugo** [comment]
Thanks for the feedback @GemmaTuron. I have submitted the final application.

**Comment by adeola-dev** [comment]
Hi @julietugo You did a good job with the AI blogpost!

**Comment by julietugo** [comment]
Thank you @adeola-dev.

**Comment by GemmaTuron** [comment]
The Outreachy contribution period has come to an end, so I will close this issue. If you want to continue contributing to Ersilia, please follow the guidelines in the CONTRIBUTING file
