### ISSUE TITLE
Outreachy Documentation Project: <Marvis Chukwudi/marv-tech>

### ISSUE THREAD

**Issue by marv-tech** [ersilia-os/ersilia#153]
Applicant: <applicant github handle>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [ ] Create a README file with the name <README_yourname.md> under the /documentation folder
- [ ] Link the #PR in a comment under this issue
- [ ] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [x] Test one model
- [x] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [ ] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [ ] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [ ] Create one image / slide to explain Ersilia’s mission and vision
- [ ] Link to the image/slide as a comment under this issue
- [ ] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [x] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by marv-tech** [comment]
I recently began my journey in bioinformatics, and one of the major drivers of my interest was harnessing the powers of machine learning in drug discovery and the discovery of microRNA, which sparked medical breakthroughs. Because of the discovery of miRNAs, drugs/vaccines and biomarkers for some terminal diseases, such as cancer, have been developed.
Ersilia's ultimate goal is to facilitate and support research into diseases that have plagued the world for decades, as well as to integrate artificial intelligence into this journey of discovery. My goal is to explore and learn everything I can about this exciting intersection of drug discovery and artificial intelligence, which is why I'm interested in Ersilia.

**Comment by GemmaTuron** [comment]
Hi @marv-tech 

Thanks for your intro! Given your interests perhaps starting in the scientific content section is a good way to start!

**Comment by marv-tech** [comment]
Thank you @GemmaTuron, will get started with the scientific content section as you suggested.

**Comment by marv-tech** [comment]
### TECHNICAL CARD

**Model Name: Ligand-based prediction of hERG blockade**

**Model Use**
CardioTox net is a comprehensive tool for predicting the obstructive actions of small molecules in drugs on specific ion channels (hERGs) that eventually lead to cardiotoxicity, which is simply described as damage to the heart muscle. This model is built on deep learning frameworks and aggregated training.

**Input Feature**
The input features for the study were divided into two categories (base and meta), with the latter based on the output of the processing of the base features. The pioneer feature set, also known as the base feature, included hERG and non-hERG blockers in the form of Simplified molecular-input line-entry system strings (SMILES strings). The output of the first phase of using deep learning models was the second input feature known as meta-features.

**Data Sources**
The datasets used were obtained from a compilation of datasets compiled in the various sources listed below

- DeepHIT authors
- BindingDB database
- ChEMBL bioactivity database
- Dataset derived from the research titled "Deep Learning-Based Prediction of Drug-Induced Cardiotoxicity"
- Dataset used in the study titled "Prospective Validation of a Comprehensive In silico hERG Model and its Applications to Commercial Compound and Drug Databases"
- A publication titled "Compilation and physicochemical classification analysis of a diverse hERG inhibition database"

**Dataset**
Following preprocessing, a total of 12620 molecules were used, with 6643 labelled as hERG blockers and 5977 labelled as hERG non-blockers.

**Neural Networks* 

- Fully Connected Neural Network (FCNND)
- A graph convolutional neural network (GCNN) 
- Fully Connected Neural Network 
- Convolution 1D Neural Network 

**Model Strength**
When compared to state-of-the-art models, CardioTox net outperforms them on the majority of metrics.

*Weakness Strength**
According to the study, model sensitivity could still improve to completely outperform existing models.

**Field of Application** 
This research is extremely useful in the pharmaceutical and drug manufacturing industries.

**Comment by marv-tech** [comment]
![CALC MOLECULAR WEIGHT](https://user-images.githubusercontent.com/57637620/163514498-3327716d-321b-42e4-b531-3d0e44ea6c6f.png)

This image depicts a model's test case.

**Comment by marv-tech** [comment]
![MOLECULAR WEIGHT TEST](https://user-images.githubusercontent.com/57637620/163514687-18507606-5541-4654-9dfc-96c1978b01ef.png)

This image depicts a model's test case 2.

**Comment by GemmaTuron** [comment]
Hi @marv-tech 
Good job on the card, my only comment is that it is perhaps a bit too long (can we make a summary?) and does not have links to the publication or source code.
Can you modify it accordingly? I would suggest next steps:
- Add feedback to model card
- Identify some new models for the hub
- Prepare final application

**Comment by marv-tech** [comment]
### MODEL SUGGESTION

1. [DeepHIT ](https://academic.oup.com/bioinformatics/article/36/10/3049/5727757?login=false)model
2. [deephERG](https://pubs.acs.org/doi/10.1021/acs.jcim.8b00769) model
3. [CardPred](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2814-5) model

**Comment by marv-tech** [comment]
@GemmaTuron I've updated the technical card above; please confirm that all feedback has been properly implemented.

**Comment by marv-tech** [comment]
This is  the link to the one-page blog post on [Strategic plan 2021-2023](https://docs.google.com/document/d/1_I15e99YyGiquqFpt-N18Hw9ex-XjgY0NPPf3qz1FtE/edit?usp=sharing)

**Comment by marv-tech** [comment]
This is a link to an AI/ML related [article](https://docs.google.com/document/d/1jHjso6V3IMuMZ8zsfjhDSqvVtFFITks-7WhUq8age2E/edit?usp=sharing)

**Comment by marv-tech** [comment]
@GemmaTuron I created a graphical image for the technical card [here](https://drive.google.com/file/d/1Xen4wMjoOwXHCBoOABC_-EE_TJ6VGBoD/view?usp=sharing)

**Comment by GemmaTuron** [comment]
Hi @marv-tech 

Good job in identifying cardiotoxicity models. I also like the graphical card. On the article, its good that you add the source references! I think you should now focus on the final application, many thanks  for all the work!

**Comment by marv-tech** [comment]
Thank you @GemmaTuron, I had a great time working with you and wish I could do more.
