### ISSUE TITLE
Outreachy Documentation Project: sfrooti

### ISSUE THREAD

**Issue by sfrooti** [ersilia-os/ersilia#156]
Applicant: sfrooti
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [ ] Link the #PR in a comment under this issue
- [ ] Incorporate feedback from the mentor
---
### Writing dissemination material
- [ ] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [ ] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by sfrooti** [comment]
Hello! I'm Sfurti. I am visual designer & study brand strategy as a junior in college. 

I look forward to contributing & supporting Ersilias mission of establishing collaborations in low-resourced settings, which is something I am extremely passionate about.
I am excited to work with the community because I have always wanted to contribute to such important projects as Ersilia’s but was not really aware of how they worked and how my skillset could be valuable.

PS: I actually was aware of the concept of Invisible Cities before this and I think Ersilia is such a cool and apt name to have!

**Comment by GemmaTuron** [comment]
Hi @sfrooti !

Thanks for your interest! As you can see there are some tasks specifically focused in design, we would be very happy to hear your ideas in these topics given your background!

**Comment by sfrooti** [comment]
Update : 
I spent the last few days taking an in-depth look at Ersilia's website, their work, ethos and general content. I am really in awe of the level of dedication and empathy that exists within this community. Based on this, I made a couple of different mockups for the mission + vision task.

1. For this particular image I tried to keep the visuals as consistent with the current look and feel of Ersilia. The simple and effective design keeps the focus on the text.

![Ersilia - 01 (2)](https://user-images.githubusercontent.com/103095175/162732241-d33f4b2e-6676-438b-8a37-a15fbf345f67.png)

2. I feel that every aspect of a brand should represent the values of that brand, and so based on Ersilias brand values + audience, I have created some graphics that I believe look different than current style still fit Ersilias aesthetic. The colours used are from the secondary colour palette as well as the primary.

![Ersilia - 01 (3)](https://user-images.githubusercontent.com/103095175/162741804-c931ff20-df36-412a-a3ec-40bcc0c4249f.png)

![4](https://user-images.githubusercontent.com/103095175/162741945-8b9b8bf8-f070-4592-b7ba-0af5f28c9cdc.png)

I am eager to hear your thoughts on both of them, and learn more about which kind of direction Ersilia plans to take with it's graphical content. 

While looking around, I also noticed that there was a space for a cohesive brand direction (eg: Updating the brand guidelines to refine the visual outcomes across platforms). I would love to go in-depth on this issue but that would require some time + interactions with you eventually @GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @sfrooti 

Thanks for the work, very nice!
I think given your expertise, the best would be that you work towards making your final application, where you can explain what thoughts or ideas you have and what would you like to work on during the internship. For example, suggest what can be done to have a more cohesive brand direction, giving examples. Also if you can link to other material you have worked on for other projects that would be great.
This will be more meaningful to understand your contribution to the project than making new slides here, I feel, your insights will be much appreciated!
We can discuss this more via slack
