### ISSUE TITLE
Outreachy Documentation Project: Akua Dokua Asiedu

### ISSUE THREAD

**Issue by DokuaAsiedu** [ersilia-os/ersilia#158]
Applicant: @DokuaAsiedu
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [x] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [x] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [x] Test one model
- [x] Add a screenshot under this issue showing the model running in your computer
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [ ] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [x] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by DokuaAsiedu** [comment]
The open source environment fascinates me. Although it has not been long since I was introduced to it, the concept of making source code available to anyone in order to pool contributions from all types of skillsets to a enhance a project is a bold step in my opinion. The reason why I say this is that I am only familiar with environments where everything is done discreetly until it is time for launch to avoid others from taking credit for work. So seeing how this community still protects creators and contributors is very fascinating and draws me into this space. Now, where does Ersilia fit in this? Well it's quite simple really. I believe everyone should have access to healthcare and I support all efforts in making sure that that goal is reached. Even though I am not a health worker and so cannot contribute directly, I can, through this project, help the ones that can. By creating useful documentation that scientists can rely on to make use of the models provided through this project, that will further their research into diseases and infections, I want to contribute what I can and learn along the way. So that is that and I hope to do my best.

**Comment by DokuaAsiedu** [comment]
Here is a link to my blog post summary: https://1drv.ms/w/s!Ao-vQCbQQ9a4nBv1WAYq8BVBtooc?e=toPyAx

**Comment by DokuaAsiedu** [comment]
This is the link to the slide explaining Ersilia's mission and vision: https://1drv.ms/p/s!Ao-vQCbQQ9a4nB3WVqBZBv5D4DkY?e=REpWT6
@GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @DokuaAsiedu 

Thanks for the work, I really like the background of the slide similar to our logo!
The application deadline is close, so please focus on preparing your final application in the Outreachy website!

Thanks

**Comment by DokuaAsiedu** [comment]
> Hi @DokuaAsiedu
> 
> Thanks for the work, I really like the background of the slide similar to our logo! The application deadline is close, so please focus on preparing your final application in the Outreachy website!
> 
> Thanks

Thank you for having a look

**Comment by DokuaAsiedu** [comment]
Twitter Template
Case 1: If model was developed by someone else
Hello everyone 👋!
We are please to announce that we have introduced a new addition to our hub. Credit goes to [name here] who reached out to have [pronoun here] model incorporated into the hub. [Brief description of model here]. Feel free to check it and also don't forget to send us your thoughts and contributions. We would love to hear from you 😊.


Case2: If model was developed in-house
Hello everyone 👋!
We are please to announce that we have introduced a new addition to our hub. Credit goes to [name of Ersillia personnel] who worked tirelessly to develop this model and also [source of dataset] for providing the dataset with which the model was built. [Brief description of model here]. Feel free to check it and also don't forget to send us your thoughts and contributions. We would love to hear from you 😊.

**Comment by Pmaidoo** [comment]
What a great job so far Dokua . keep it up .

**Comment by DokuaAsiedu** [comment]
Screenshot showing model running
![Screenshot from 2022-04-20 12-25-28](https://user-images.githubusercontent.com/43910399/164237062-9b14b878-dc72-4fa6-8a4e-2dcd09b18f15.png)

**Comment by DokuaAsiedu** [comment]
Here's my `ErsiliaModel` class docstring:

```python
class ErsiliaModel(ErsiliaBase):
    '''A subclass of the base Ersilia class. When initialized, it fetches the model specified with the id specified from the Ersilia hub and checks its validity'''
    
    def is_valid():
        '''Returns the validity of the loaded model. A model is valid if its id or slug value has an entry in the model hub
            
        Returns:
            True if the loaded model is valid, False otherwise
        '''
    
    def api(api_name, input, output, batch_size):
        '''Loads an input file, splits it into lines and passes the lines into the specified API task, writing all the results into an output file
        
        Args:
            api_name:    The name of the API to execute
            input:        The path of the input file
            output:        The path of the output file for results
            batch_size:    The number of input lines to process at a time. Defaults to 100
            
        Returns:
            The output data of the API
        '''
        
    def api_task(api_name, input, output, batch_size):
        '''Creates and API instance using the api_name and passes the input through it, returning its result. The result could be a generator, file or specific datatype (dict, dataframe, numby array, etc.)
        
        Args:
            api_name:    The name of the API to execute
            input:        The path of the input file
            output:        The path of the output file for results
            batch_size:    The number of input lines to process at a time. Defaults to 100
            
        Returns:
            The output data of the API
        '''
        
    def update_model_usage_time(model_id):
        '''Records the timestamp at which a model was used
        
        Args:
            model_id:    The id of the model which was executed
        '''
        
    def serve():
        '''Starts (or restarts) the Docker server which hosts the model'''
        
    def close():
        '''Terminates the Docker server'''

**Comment by DokuaAsiedu** [comment]
> What a great job so far Dokua . keep it up .

Thanks so much

**Comment by DokuaAsiedu** [comment]
Here is a technical card for morgan-counts:
![Technical Card](https://user-images.githubusercontent.com/43910399/164286901-4379c121-0279-4565-a2dd-5baff9b5759a.png)

**Comment by DokuaAsiedu** [comment]
### 3 Models I think would be a great addition to the hub:
* Binding Affinity: To help determine how well a potential drug, binds to its target which will have a hand in determining a drug's potency.

* Molecular Electrostatic Potential: To show a representation of the chemically reactive regions in a molecule

* Transporter Function: To give a probability that a drug being delivered to a target will not be distributed to another location.
