### ISSUE TITLE
Tutorial inspiration

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#16]
We are working to develop simple tutorials for the Ersilia Model Hub.
Ca you comment below suggestion one example of a good tutorial from another FOSS project we could get inspiration from?

This is a required step to tackle Issue #17

**Comment by AviatorIfeanyi** [comment]
Does this have to include articles from blog posts?
This is exciting and i would love to collaborate with you on this

Find below an example

https://towardsdatascience.com/how-to-use-machine-learning-for-drug-discovery-1ccb5fdf81ad

**Comment by Ama-tech0001** [comment]
Greetings @GemmaTuron 
During my esearch, I came accross this video on Youtube, I don't know if it can be of help in any way 
https://www.youtube.com/watch?v=SoeQZJLQlMc

**Comment by Ama-tech0001** [comment]
Below are links to some articles that I came across;

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3884843/

https://www.researchgate.net/publication/256200380_Open_source_drug_discovery_-_A_limited_tutorial

https://www.simulations-plus.com/software/admetpredictor/?gclid=Cj0KCQjw0PWRBhDKARIsAPKHFGhoMZIta7SvbRDIVEYQAVqvBB1BU1CPYmbUBRPCro5zjdNiF2fDk_kaAnvpEALw_wcB

https://www.knime.com/blog/tutorials-for-computer-aided-drug-design-using-knime-workflows

**Comment by Ama-tech0001** [comment]
I'm hoping that I got the assignment correctly. In case I'm making a mistake, I'll greatly appreciate any corrections

**Comment by victorabba** [comment]
I think the way forward is to test the model by installing and trying it out after which we can then make a video tutorial on how newbies can install and use the model.

**Comment by AishaSaman** [comment]
Hi, I am Aisha and I am Outreachy internship applicant.

I think this website have really good, simple tutorials for inspiration: 
https://material.io/design/machine-learning/barcode-scanning.html#usage 

Things that inspire me and I found helpful are: 
1. step by step with pictures and videos where necessary for better understanding
2. dos and donts are shown with green and red colors 
3. links to related articles with each topic
4. use cases shown

**Comment by julietugo** [comment]
I believe the 'Getting Started' page of Python is a good example. I would like to write such for Ersilia.

**Comment by kbetty** [comment]
Hello @GemmaTuron I have searched and gone through several tutorials from other FOSS communities and I found one at https://wiki.openmrs.org/display/docs/Developer+Guide so inspiring that we can borrow a leaf as we develop ours for Ersilia Model Hub and  passionate to contribute to  the project.

**Comment by kbetty** [comment]
@GemmaTuron I think we have two separate tutorials to cater for technical contributors and non technical contributors so that we come up with tutorials that will be of great use to our community.

**Comment by adeola-dev** [comment]
Hi @GemmaTuron I found this helpful for the usability of the Firefox FOSS project;
https://itsfoss.com/firefox/ 

And this for the VLC FOSS project;
https://itsfoss.com/install-latest-vlc/
https://www.flexclip.com/learn/vlc.html.

I am open to collaboration with other contributors to this issue

**Comment by GemmaTuron** [comment]
Hello,

@AviatorIfeanyi, you link to a high level introduction to ML for drug discovery, but here we are looking at creating specific tutorials for the Ersilia Model hub, our tool. Please think how to do this and find perhaps more adapted examples before continuing

@Ama-tech0001, the first resources you list are also high level overview of using computer science for drug discovery. The most relevant and similar to what we need is the knime workflow. Good find, get your inspiration from there to work on issue #17 

@victorabba a video tutorial would be fantastic!

@AishaSaman this is a good example, you can use it as a template to work on issue #17

@julietugo the "Getting Started" in python is good but very general, we would like something more detailed to the Ersilia Model Hub

@kbetty, the Developer manual is focused on new developers and contributors. Is not a bad idea but here we were thinking of tutorials for users, not developers. Can you find a  user-oriented example? 

@adeola-dev, you are citing great documentation of installation instructions, but here we are looking at more tutorial-type of examples, can you find one?


But to all of you, thanks for your work you are all citing interesting resources and I encourage you to answer my comments before moving to issue #17

**Comment by Ama-tech0001** [comment]
Thank you for the comments @GemmaTuron  
Can you please check out what I did in issue #17 ?

**Comment by kbetty** [comment]
> @kbetty, the Developer manual is focused on new developers and contributors. Is not a bad idea but here we were thinking of tutorials for users, not developers. Can you find a user-oriented example?

Thanks for the insight. I have gone through several user-oriented guides but the one at https://wiki.openmrs.org/pages/viewpage.action?pageId=589851 out-stands them and I think we can borrow a leaf and we come up with a user guide with clear steps on how to use ersilia.

**Comment by Kheredine** [comment]
Hi @GemmaTuron , I hope this will help
https://youtu.be/yL_NqXZgmks

**Comment by Kcfreshly** [comment]
@GemmaTuron Knime flow as suggested by @Ama-tech0001 looks great, I believe I can create a similar tutorial and possibly include a short tutorial video on how to use the Ersilia Model Hub.

**Comment by Onabel** [comment]
Pictures helps as anchor to direction and it gives a visualization of what to expect as well as a road map. I would like to contribute to this project by creating a picture tutorial for users.

**Comment by julietugo** [comment]
Thank you @GemmaTuron for the feedback. I believe this is what you are looking for - https://towardsai.net/p/l/how-to-discover-antiviral-drugs-with-deep-learning. I can create this kind of tutorial for Ersilia

**Comment by adeola-dev** [comment]
Thanks @GemmaTuron for the feedback. I found the resources cited by @AishaSaman very useful. I could create a simple tutorial using the template.

**Comment by adeola-dev** [comment]
Thank you @GemmaTuron for the feedback. I found the resources cited by @AishaSaman very useful. I could create a simple tutorial using the template.

**Comment by MsChineme** [comment]
Here is Google AutoML. Though works on the cloud, It's an open source platform that enables people with little knowledge of ML to train models specific to their use cases.

Features: 
Image classification
Video intelligence
Auto ML translation
Natural language

Links
https://www.youtube.com/watch?v=kgxfdTh9lz0
https://www.youtube.com/watch?v=aUfIFoMEIgg

**Comment by ps-19** [comment]
@GemmaTuron mam i would love to work on this issue.

**Comment by kbetty** [comment]
@GemmaTuron I have been reading more about the project  to gather information on how best we can  develop a simple tutorials for the Ersilia Model Hub. And as from my findings there are things we need to put into consideration

1.  The users of the tutorial.
2. The limitation users may encounter when using the tutorials during deploying 
3. The main barriers of AI adoption in experimental research.
4. etc

If the factors above are carefully analysed then we will create a hub of ready to use AI model which will be easier for users to adopt.

**Comment by kbetty** [comment]
Getting to know more on this project, I discovered after Ersilia AI models are validated they are published but they lack the Deployment feature which can aid users to use the tool(s) with ease. Of which these users most of them are scientific researcher but lack computer skills and this result into our tools not being adopted by the users. 

So the Tutorial we are developing is address the issue above. And to my understanding based on the research we are creating adding a Deployment feature for users to easily adopt to the tools during their research. 

@GemmaTuron let me know whether am on track with the project?

**Comment by GemmaTuron** [comment]
> Thanks @GemmaTuron for the feedback. I found the resources cited by @AishaSaman very useful. I could create a simple tutorial using the template.

please head to issue #17 to start working on this!

**Comment by GemmaTuron** [comment]
> Getting to know more on the project, I discovered that after Ersilia AI models are validated they are published for use but they lack the Deployment feature which can aid users to use the tool(s) with ease. Of which these users most of them are scientists who are actually not computer experts and this results into our tools not being widely adopted by the users.
> 
> So the Tutorial we are developing/creating is to address the issue above. And to my understanding based on the research have curried out we are creating a Deployment feature to our AI models for users to easily adopt to the tools during their research.
> 
> @GemmaTuron let me know whether am on track as I explore more with the project?

Hi @kbetty, you have done a good research! Indeed, non technical users might face difficulties in using the Hub. We would like one or two slides/text/video showing how can they use it (at the current stage of deployment, which is through CLI)

**Comment by GemmaTuron** [comment]
> @GemmaTuron Here is Google AutoML. Though works on the cloud, It's an open source platform that enables people with little knowledge of ML to train models specific to their use cases.
> 
> Features: Image classification Video intelligence Auto ML translation Natural language
> 
> Links https://www.youtube.com/watch?v=kgxfdTh9lz0 https://www.youtube.com/watch?v=aUfIFoMEIgg

Hi @MsChineme , this is a good find and a very nice example.

**Comment by GemmaTuron** [comment]
> @GemmaTuron mam i would love to work on this issue.

Hello @ps-19, comment with some examples you will use as a template and then go ahead to issue #17 !

**Comment by MsChineme** [comment]
Thank you @GemmaTuron . Do I proceed to the next step, if yes? Please what is the next step?

**Comment by MsChineme** [comment]
> Thank you @GemmaTuron . Do I proceed to the next step, if yes? Please what is the next step?




> > @GemmaTuron Here is Google AutoML. Though works on the cloud, It's an open source platform that enables people with little knowledge of ML to train models specific to their use cases.
> > Features: Image classification Video intelligence Auto ML translation Natural language
> > Links https://www.youtube.com/watch?v=kgxfdTh9lz0 https://www.youtube.com/watch?v=aUfIFoMEIgg
> 
> Hi @MsChineme , this is a good find and a very nice example.

Thank you @GemmaTuron . Do I proceed to the next step, if yes? Please what is the next step?

**Comment by MsChineme** [comment]
> > @GemmaTuron Here is Google AutoML. Though works on the cloud, It's an open source platform that enables people with little knowledge of ML to train models specific to their use cases.
> > Features: Image classification Video intelligence Auto ML translation Natural language
> > Links https://www.youtube.com/watch?v=kgxfdTh9lz0 https://www.youtube.com/watch?v=aUfIFoMEIgg
> 
> Hi @MsChineme , this is a good find and a very nice example.

Thank you @GemmaTuron . Do I proceed to the next step, if yes? Please what is the next step?

**Comment by Rufaida98** [comment]
@GemmaTuron I think it already listed but a video tutorial as i learned a lot from video tutorials or like what you did in ersilia book to download the Ubuntu and other packages for ersilia API which was very straightforward and helpful.

**Comment by kbetty** [comment]
As part of the ground work during my research so that we develop a useful tutorial for users, I discovered a user has two ways of using the product:

1. Using the CLI
2. Using an online platform via cloud services

However, at the our current stage of deployment, the user can so far use the CLI. My idea that am working on is to come up with the skeleton of a useful Table of Content for the tutorial which we can brainstorm on and then add content accordingly.
 
My question is: In the tutorial should we consider the two approaches have mentioned above? cc: @GemmaTuron

**Comment by vaishnavi-sms** [comment]
> We are working to develop simple tutorials for the Ersilia Model Hub. Can you comment below suggestion one example of a good tutorial from another FOSS project we could get inspiration from?
> 
> This is a required step to tackle Issue #17


Hello, I am Vaishnavi, Outreachy applicant.
First, we must install the model and analyze the problems the user might encounter during installation.
Then make a tutorial video which will show everything steps by step, from where to install it to how to use it.

**Comment by vaishnavi-sms** [comment]
> > We are working to develop simple tutorials for the Ersilia Model Hub. Can you comment below suggestion one example of a good tutorial from another FOSS project we could get inspiration from?
> > This is a required step to tackle Issue #17
> 
> Hello, I am Vaishnavi, Outreachy applicant. First, we must install the model and analyze the problems the user might encounter during installation. Then make a tutorial video which will show everything steps by step, from where to install it to how to use it.

I found a series of tutorial videos that explain everything about the app, starting with what it is, how to use it, what plus points are, etc.

Here I am sharing this series I think this will be helpful to make any tutorial video.
https://youtu.be/HCc7wzUH4ts - Introduction and app overview
https://youtu.be/gH2G0niO6cM - Visualize your thoughts 
https://youtu.be/4sp2X4nsBwA - Tell the story through media 
https://youtu.be/z_H7i-ERVQI - Capture everything
https://youtu.be/jq42O1W_Iys - Share for feedback 
https://youtu.be/oANcUP2Q9XA - Meetings with meaning

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron I see a lot of traction here! Can we nominate some assignees? (see right bar).

**Comment by AbiolaAnisere** [comment]
> We are working to develop simple tutorials for the Ersilia Model Hub. Ca you comment below suggestion one example of a good tutorial from another FOSS project we could get inspiration from?
> 
> This is a required step to tackle Issue #17

Hi @GemmaTuron

**Comment by AbiolaAnisere** [comment]
These are a few suggestions of good tutorials I found from different sources. Please provide feedback. Thank you. 

https://www.youtube.com/watch?v=SoeQZJLQlMc

https://material.io/design/machine-learning/barcode-scanning.html#usage

https://towardsai.net/p/l/how-to-discover-antiviral-drugs-with-deep-learning

https://www.youtube.com/watch?v=kgxfdTh9lz0

**Comment by AbiolaAnisere** [comment]
Hi @GemmaTuron, 

These are a few suggestions of good tutorials I found from different sources. Please provide feedback. Thank you. 

https://www.youtube.com/watch?v=SoeQZJLQlMc

https://material.io/design/machine-learning/barcode-scanning.html#usage

https://towardsai.net/p/l/how-to-discover-antiviral-drugs-with-deep-learning

https://www.youtube.com/watch?v=kgxfdTh9lz0

**Comment by kbetty** [comment]
Hello @GemmaTuron,  have just completed Ersilia installation on my machine and am coming up with a simple user tutorial of our model. Hoping to be done by the end of today and will share a PR.

**Comment by AnshuKumari197** [comment]
Hello, @GemmaTuron Can i make tutorial how Ersilia Model Hub will help in future for mankind ?

**Comment by GemmaTuron** [comment]
Hello all,

Thanks for your ideas, sound great! Please follow the new contribution guidelines to make sure we can track each applicant's work and suggestions! 

I will close this issue now to move the discussions to the relevant thread
