### ISSUE TITLE
Check that Git LFS is correctly installed

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#168]
Some large models (e.g. chemprop-antibiotic) require Git LFS to be installed. If Git LFS is not installed, then the model is fetched but only pointers to the checkpoints are given. As a result, users get empty outputs when running predictions with the model.

I would suggest that we add a check in the main `__init__.py` file to check that Git LFS is installed. If it is not, raise an exception. Happy to listen to other suggestions too!

Please respond below if you want to work on this issue and I will assign it to you.

**Comment by mahamtariq58** [comment]
Hi @miquelduranfrigola , I would love to try this issue....

**Comment by Nawarrr** [comment]
I would love to work on this, as I faced this problem yesterday, assign me if it's possible @miquelduranfrigola

**Comment by Nawarrr** [comment]
@miquelduranfrigola  I also think that a warning is a better option, as some models (or maybe in the future if it is managed to make the models smaller) might not need git lfs and they who use it might be aware of that.

**Comment by miquelduranfrigola** [comment]
Hi all, thanks for your interest in this. I am assigning this to the three of you. Feel free to join efforts if you want, or simply PR your individual solutions/suggestions. Thanks!

**Comment by miquelduranfrigola** [comment]
This is already being addressed in the PRs, so closing the issue. Great job.
