### ISSUE TITLE
Create a mock tutorial slide

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#17]
Create one or two slides with a schema of how to use the Ersilia Model Hub and upload them in the folder /tutorials
Feel free to use any tools you want, we recommend checking [carbon](https://carbon.now.sh/) for snippets of code, and also reading our brand guidelines [here](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5).
You can start working on this project even if other applicants are working on it as well, feel free to make your own design.

To answer this issue, please **first go to issue #16** and comment there. Also note this is a medium-sized issue, and requires some technical expertise. To create a tutorial, you probably need to install and run the Hub.

Be creative and have fun!

**Comment by AnshuKumari197** [comment]
Can I make slides in plain text or in code format ?.

**Comment by Annysah** [comment]
Hello @GemmaTuron 👋, I'm Anisat, an Outreachy applicant. 
I would like know if this issue is open to anyone interested in contributing?

**Comment by victorabba** [comment]
@GemmaTuron please where is the folder for the upload located?

**Comment by julian55455** [comment]
@GemmaTuron is the issue open to anyone interested in contributing?if yes,how do i make the slides?

**Comment by GemmaTuron** [comment]
> @GemmaTuron Can I make slides in plain text or in code format ?. Please assign me this work.

Hello Anshu, this issue is related to outreach material so it should be in any format that is easily distributable to a general audience (not code format).

**Comment by GemmaTuron** [comment]
> Hello @GemmaTuron 👋, I'm Anisat, an Outreachy applicant. I would like know if this issue is open to anyone interested in contributing?

Hello Anisat, yes, feel free to start working on this, it won't be assigned to anyone individually as it is up to each applicant's ideas and can be tackled by different people at the same time

**Comment by GemmaTuron** [comment]
> @GemmaTuron is the issue open to anyone interested in contributing? If yes, how do I make the slides?

Hello Julian,
Please prepare the material in any format you would like and upload it to the /tutorials folder (that will be soon created hopefully :) )

**Comment by GemmaTuron** [comment]
> @GemmaTuron please where is the folder for the upload located?

Hello Victor,

I noticed there is no folder so I just created an issue, I hope an applicant will create the folder !

**Comment by Ama-tech0001** [comment]
@GemmaTuron, I did a slide and will love to upload for review. Please how should I do that?

**Comment by GemmaTuron** [comment]
Hello @Ama-tech0001,

To upload documents on a github repository, follow this instructions: https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository
Please make sure you reduce the size of the slides otherwise they won't be able to be uploaded

**Comment by kbetty** [comment]
Hello @GemmaTuron  I have an idea on this task and am wondering whether multiple people can work on the task. Your guidance is really helpful on the subject.

**Comment by GemmaTuron** [comment]
For anyone interested in working in this issue, please first:

Check Issue #16 and comment there where are you getting your inspiration to work on the documents, link any relevant resources and explain your ideas so the rest of the community will see them.
We will not accept contributions to this issue if you do not answer first to issue #16 !

Thanks

**Comment by kbetty** [comment]
@GemmaTuron I made a comment and explained my idea [here](https://github.com/ersilia-os/ersilia/issues/16#issuecomment-1080007598). I am open to collaborating with other contributors on this issue. Am wondering if I can go a head and make a skeleton of the proposed idea. Thanks for your guidance.

**Comment by Ama-tech0001** [comment]
Okay, noted. I already made changes without seeing your last comment, I'll make sure to check Issue #16 right away

**Comment by GemmaTuron** [comment]
> @GemmaTuron I made a comment and explained my idea [here](https://github.com/ersilia-os/ersilia/issues/16#issuecomment-1080007598). I am open to collaborating with other contributors on this issue. Am wondering if I can go a head and make a skeleton of the proposed idea. Thanks for your guidance.

Hello @kbetty , 

great please go ahead, looking forward to seeing it!

**Comment by Annysah** [comment]
> > Hello @GemmaTuron 👋, I'm Anisat, an Outreachy applicant. I would like know if this issue is open to anyone interested in contributing?
> 
> Hello Anisat, yes, feel free to start working on this, it won't be assigned to anyone individually as it is up to each applicant's ideas and can be tackled by different people at the same time

Thank you! @GemmaTuron

**Comment by GemmaTuron** [comment]
Hello All,

I will close this issue and move the discussion to the relevant threads under each applicant's new issues as specified in the Contribution Guidelines in Slack
