### ISSUE TITLE
Outreachy Documentation Project: Shanmugapriya.D

### ISSUE THREAD

**Issue by Shamswaggirl** [ersilia-os/ersilia#170]
Applicant: @Shamswaggirl
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by Shamswaggirl** [comment]
Hello @GemmaTuron,
 I am Shanmugapriya.D from India. I am interested in research and documentation, I have published three research papers in Springer publications. So I am interested in contributing to documentation for Ersilia model hub.

**Comment by Shamswaggirl** [comment]
I have created a 1-page blog post for the strategic plan 2021-2023, please do refer

https://docs.google.com/document/d/1iN4uweFNAvHO4Dfl1UtAt4Qc_eDzWqVA8qvFXMw0Swk/edit?usp=sharing

#142

**Comment by Shamswaggirl** [comment]
Hello @GemmaTuron,
I have made a slide for the mission and vision for EOSI. Please do refer 

https://www.canva.com/design/DAEbEBjwGqw/kOZbPv55ejaA-GEc-RGmnA/view?utm_content=DAEbEBjwGqw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Shamswaggirl** [comment]
Hello @GemmaTuron,
I have created the README file and linked the issue.
https://github.com/ersilia-os/ersilia/pull/182#issue-1196842425

**Comment by Shamswaggirl** [comment]
Hello @GemmaTuron,
I have checked the HUB and created a technical card, please do refer to the card:

https://www.canva.com/design/DAE9RWG-bFI/gVeuxkJVrBTOzKS7_MEUHA/view?utm_content=DAE9RWG-bFI&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by Dapper50** [comment]
Hello @Shamswaggirl great slide on the mission and vision, However i feel like it was straight to the point without much explanation. You can try adding Ersilia's logo and elaborating more on the vision and mission and what they do.

**Comment by Shamswaggirl** [comment]
Thanks, @Dapper50 
I'll update it.

**Comment by harshita214** [comment]
> Hello @GemmaTuron, I have made a slide for the mission and vision for EOSI. Please do refer
> 
> https://www.canva.com/design/DAEbEBjwGqw/kOZbPv55ejaA-GEc-RGmnA/view?utm_content=DAEbEBjwGqw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Hello @Shamswaggirl 
The content is good and is to the point but the background picture is a blur and while reading the colors are aligned with the picture, if possible change the background picture and add the logo of elisia.

**Comment by GemmaTuron** [comment]
Hi @Shamswaggirl,

Good job on these tasks! I have only some minor comments:
- On the mission and vision slide, the sentence "Our mission is to cope with the recent trends like AI/ML to improvise the research" sounds a bit misleading. To cope with can be associated to a more negative idea, something like Our mission is to follow... sounds a bit better? And improve instead of improvise? I am not a native English speaker but I would phrase it as I suggest
- I like the card! good job
Go on with next task thanks!

**Comment by Shamswaggirl** [comment]
Thanks a lot @GemmaTuron ,
I would certainly do the necessary changes.

**Comment by loweyvana** [comment]
> Hello @GemmaTuron, I have checked the HUB and created a technical card, please do refer to the card:
> 
> https://www.canva.com/design/DAE9RWG-bFI/gVeuxkJVrBTOzKS7_MEUHA/view?utm_content=DAE9RWG-bFI&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

Your card is absolutely beautiful! You did this on canva?

**Comment by Shamswaggirl** [comment]
Thanks a lot @loweyvana , yes I did this on Canva.

**Comment by GemmaTuron** [comment]
Hi @Shamswaggirl 

Great job so far, start thinking of your final application.
One minor comment that I realized, thanks to @loweyvana mention of the card again. The best for the Publication would be to use the citation: Duran-Frigola et al, Nature Biotech 2020 rather than the link - no need to change it now just for your information that's how we usually cite scientific publications

**Comment by Shamswaggirl** [comment]
Thanks for the information @GemmaTuron, I'll do my final application process.

**Comment by Shamswaggirl** [comment]
> > Hello @GemmaTuron, I have made a slide for the mission and vision for EOSI. Please do refer
> > https://www.canva.com/design/DAEbEBjwGqw/kOZbPv55ejaA-GEc-RGmnA/view?utm_content=DAEbEBjwGqw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> Hello @Shamswaggirl The content is good and is to the point but the background picture is a blur and while reading the colors are aligned with the picture, if possible change the background picture and add the logo of elisia.

Okay sure, noted and thanks.

**Comment by adeola-dev** [comment]
I really liked the technical card. Good job!

**Comment by Shamswaggirl** [comment]
> I really liked the technical card. Good job!

Thanks alot for your credit @adeola-dev

**Comment by GemmaTuron** [comment]
The Outreachy contribution period has come to an end, so I will close this issue. If you want to continue contributing to Ersilia, please follow the guidelines in the CONTRIBUTING file

**Comment by Shamswaggirl** [comment]
> The Outreachy contribution period has come to an end, so I will close this issue. If you want to continue contributing to Ersilia, please follow the guidelines in the CONTRIBUTING file

Okay, thanks alot @GemmaTuron for the opportunity to contribute for Ersilia.
