### ISSUE TITLE
Customizing ersilia-os's Profile

### ISSUE THREAD

**Issue by Sukriti-sood** [ersilia-os/ersilia#172]
# Organization's profile README

Adding Organization's Profile readme will be a great addition for our Organisation. We can share information about how to engage with our organization by creating an organization profile README. GitHub shows  organization profile README in the "Overview" tab of the organization.

## Example
![moja-global (1)](https://user-images.githubusercontent.com/55010599/162165258-1288382a-6bf0-48f8-860d-709e02926f64.png)

**Comment by miquelduranfrigola** [comment]
@GemmaTuron what are your thoughts on this?

**Comment by Rufaida98** [comment]
@Sukriti-sood it will add a nice gesture to the project and it will make more much approachable 👍

**Comment by miquelduranfrigola** [comment]
Assigning this to @Sukriti-sood for now

**Comment by GemmaTuron** [comment]
Hi @Sukriti-sood 

That is a good idea. Can you focus on creating a template for our organization as part of your final application?
thanks!

**Comment by Sukriti-sood** [comment]
> Hi @Sukriti-sood
> 
> That is a good idea. Can you focus on creating a template for our organization as part of your final application? thanks!

ya, sure.

**Comment by Sukriti-sood** [comment]
In order to create this profile, we must create a .`github `repository, then create a `Readme.md` file under the `profile` folder of the repository. I have created a Readme file for the same [here](https://github.com/Sukriti-sood/Ersilia_Profile). Please provide feedback.

@GemmaTuron @miquelduranfrigola

**Comment by GemmaTuron** [comment]
Hi @Sukriti-sood 
This is super cool thanks!
I will create the repo and add the readme file, I have cloned your repo and will use the template that you have created.
I am closing this issue here as this is completed.
