### ISSUE TITLE
Add workflows and test to check if the writing style guidelines are being followed

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#177]
**What is your feature request?**
Once we get a rigid writing style guidelines, we can add tests or workflow that will run on PRs checking if the writing style guidelines is being followed. This will reduce a lot of work that was supposed to be done manually.

**Is your feature request related to a problem?**
Ersilia deals with a lot of documentation, keeping that in mind maintaining consistency across all the files is very important. And it's manually impossible to check it for every PR. So this should be a great addition.

**Comment by sayantani11** [comment]
I would like to be assigned this.
@GemmaTuron your thoughts?

**Comment by Rufaida98** [comment]
@sayantani11 that will organize the files and the data. Nice idea 👍

**Comment by miquelduranfrigola** [comment]
Hi @sayantani11 this is a fantastic idea.

Do you think you could come up with minimum example of the workflow/test? Doesn't have to be perfect or too complex. Just for us to get an idea of what you have in mind.

**Comment by sayantani11** [comment]
> Hi @sayantani11 this is a fantastic idea.
> 
> Do you think you could come up with minimum example of the workflow/test? Doesn't have to be perfect or too complex. Just for us to get an idea of what you have in mind.

If you see the writing style guideline I added there's a particular styling that supposed to be followed while making a PR related to the docs. This workflows/test will run on this PRs to make sure that the requirements are being satisfied. Verifying these manually will be cumbersome this will helpful. I'll try to make a PR for it asap!

**Comment by miquelduranfrigola** [comment]
I really like the approach. Note that we use [black](https://pypi.org/project/black/) for formatting, which may simplify things a little bit.

**Comment by GemmaTuron** [comment]
Hi @sayantani11 

Thanks for the suggestion, let us know when this is ready to revise and merge!

**Comment by miquelduranfrigola** [comment]
Hi @sayantani11 - I am sorry I overlooked this message. I would prefer to keep the branch as `master` for now, although I am aware that we should rename it to `main` eventually. Renaming it now could potentially affect some scripts by collaborators, so I think we need to plan the renaming well. Will keep you updated.

Is there a specific reason you want this renaming?

**Comment by sayantani11** [comment]
Yeah!! I guess the workflows actually look for a branch named `main`
instead of master. That's the only reason holding this PR. But we can
definitely put it on hold and look into it in the future.

**Comment by miquelduranfrigola** [comment]
Thanks @sayantani11!! Yes let's put it on hold. We will have someone specifically taking care of workflows soon, so we can take over as soon as they are up to speed.

**Comment by GemmaTuron** [comment]
Hi all!
I will close this issue since we are going to work on workflows in general with the support of the fantastic github volunteers.
