### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#183]
Hi @GemmaTuron,

Due to the many PR submitted by Outreachy applicants, there are README files in the repo now. Most of them end up in the `documentation` folder.

I think we need to:
* Make sure that all README files end up in the same folder
* Rename `documentation` to e.g. `outreachy_docs` or something like this.

Can you do so?

**Comment by Deepthi562** [comment]
@GemmaTuron, can I be assigned with this issue? Please let me know what elements I should work on. Thank you.

**Comment by harshita214** [comment]
@miquelduranfrigola @GemmaTuron 
I can work on this issue, Can I be assigned this

**Comment by miquelduranfrigola** [comment]
Hi @Deepthi562 @harshita214 I think it is better if @GemmaTuron takes care of this. Thanks!

**Comment by GemmaTuron** [comment]
Hi, 

Thanks for the help, but I also think it will be best if I reorganize the repo, many thanks!

**Comment by GemmaTuron** [comment]
I have merged the different suggestions into a README and CONTRIBUTING files, and will also add changes on the installation guide on GitHub. As for the original documents contributed, I am preparing an open folder with the outreachy contributions, which will be available through our website.
