### ISSUE TITLE
Modifying Contributing.md 

### ISSUE THREAD

**Issue by harshita214** [ersilia-os/ersilia#198]
**What is your feature request?**

While working on Readme, I saw many readme files and came across the point that a Contributing.md is also very important which is a separate detailed readme file. 

I want to enhance the already present [contributing](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTION.md).md by including the points mentioned below

- [x] How to start (How to Contribute etc.)
- [x] Code of Conduct Link
- [x]  Submit a PR - STEPS
- [ ] Type of PR/Issue (for example: feat - is a new feature ,doc - documentation only changes , fix - a bug fix)
- [x] Sending Feedbacks & Reporting Bugs
- [ ]  Submitting New Ideas
- [ ]  Architecture- Files structure
- [ ]  Setup From Source 
- [ ]  Explanation of Important terms used in Ersilia
- [ ]  Technology Stack
- [ ]  Coding/PR standards
- [ ]  Tutorials/Blogs for more reference
- [ ]  Other Ways to contribute
- [ ]  Resources

**Is your feature request related to a problem?**

A good, well-explained, and well-structured CONTRIBUTING.md file, in Ersilia, provides potential project contributors with a short guide to how they can help with your project. This will not only help Project admins and contributors but also Project consumers, Sponsors, etc. Not only this for contributors this is very important as it helps them understand the whole workflow, from this it will be easier for them. I have tried to cover all the points which should be there in contributing.md. Currently, the ticked points are mentioned, I want to add all the above points mentioned.

I would like to work on this issue and enhance the Contributing.md file

**Comment by GemmaTuron** [comment]
Hi @harshita214 

This is already being tackled by @victorabba and @sayantani11 
Can you check other tasks to work on? thanks

**Comment by harshita214** [comment]
> **What is your feature request?**
> 
> While working on Readme, I saw many readme files and came across the point that a Contributing.md is also very important which is a separate detailed readme file.
> 
> I want to enhance the already present [contributing](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTION.md).md by including the points mentioned below
> 
> * [x]  How to start (How to Contribute etc.)
> * [x]  Code of Conduct Link
> * [x]   Submit a PR - STEPS
> * [ ]  Type of PR/Issue (for example: feat - is a new feature ,doc - documentation only changes , fix - a bug fix)
> * [x]  Sending Feedbacks & Reporting Bugs
> * [ ]   Submitting New Ideas
> * [ ]   Architecture- Files structure
> * [ ]   Setup From Source
> * [ ]   Explanation of Important terms used in Ersilia
> * [ ]   Technology Stack
> * [ ]   Coding/PR standards
> * [ ]   Tutorials/Blogs for more reference
> * [ ]   Other Ways to contribute
> * [ ]   Resources
> 
> **Is your feature request related to a problem?**
> 
> A good, well-explained, and well-structured CONTRIBUTING.md file, in Ersilia, provides potential project contributors with a short guide to how they can help with your project. This will not only help Project admins and contributors but also Project consumers, Sponsors, etc. Not only this for contributors this is very important as it helps them understand the whole workflow, from this it will be easier for them. I have tried to cover all the points which should be there in contributing.md. Currently, the ticked points are mentioned, I want to add all the above points mentioned.
> 
> I would like to work on this issue and enhance the Contributing.md file



> Hi @harshita214
> 
> This is already being tackled by @victorabba and @sayantani11 Can you check other tasks to work on? thanks

Oh okay okay sure!
Also, I saw the issue that @sayantani11 and @victorabba are doing, they have added new contributions.md for contributors, which Now is going to be merged with contributions.md. They have done a great job by adding some sections but still, some sections are left from the above-mentioned list. Can I work Collaboratory with @sayantani11 and @victorabba? If it is alright @GemmaTuron. 

Yes, I am working on my next task.

**Comment by GemmaTuron** [comment]
I @harshita214 

Now that the other applicants have completed their work, Please add your contribution to the contribution.md file to the sections missing, thanks!

**Comment by harshita214** [comment]
@GemmaTuron Sure 
Thank you, I will add the sections 👍

**Comment by harshita214** [comment]
@GemmaTuron 
Done with the task 
Kindly provide your feedback :)

**Comment by GemmaTuron** [comment]
Hi @harshita214 

Good job thanks! As we mentioned in Slack, the mentors will now work in merging all these idead into a final readme and a final contribution.md file, thanks for all the work!
I think you can now focus on writing the final application on the outreachy website, good job!

**Comment by GemmaTuron** [comment]
I have merged the PR and will close this issue now!
