### ISSUE TITLE
Outreachy Documentation Project: <Lylyna Heng>

### ISSUE THREAD

**Issue by lylynaheng** [ersilia-os/ersilia#202]
Applicant: <applicant github handle>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [ ] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [x] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [x] Link the #PR in this issue
- [x] Incorporate feedback from the mentor
---
### Scientific content
- [ ] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [ ] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by lylynaheng** [comment]
I think this is a great project to be a part of because healthcare is a global issue and complex. However, health problem seems to be ahead of us or even out of control like COVID-19. How can we have a better health system? Why can't we have a global health system? What can we do about it?

Well, I don't have any answers to the questions above. First, I don't have the technical skills in the field, but then there is Ersilia Open Source Initiative. I think this is a great way to learn something outside of my domain. Secondly, this project offers the skills that match with my current skills and interests in documentation and graphic or UX/UI design. It is the best for both world where I get to learn about health care, open-source and applying my knowledge in design.

**Comment by lylynaheng** [comment]
#PR

**Comment by lylynaheng** [comment]
A link to the blog post on EOSI – strategic plan 2021 - 2023.

https://scholarjourneys.com/2022/04/11/ersilia-open-source-initiative-strategic-plan-2021-2023-main-points-outreachy-contribution/

**Comment by GemmaTuron** [comment]
Hi @lylynaheng 

Great job on the blogpost thanks!
To prepare your final application I would suggest to focus on one task from the list and then you can go ahead and make the final submission

**Comment by lylynaheng** [comment]
Hi @GemmaTuron 

Thank you for the feedback and I choose to do graphic design for the project. I am more than happy to do UX/UI too, if there is a need for that.

This is a link to Ersilia's mission and vision.

https://bit.ly/3uEKZsU

**Comment by loweyvana** [comment]
BEAUTIFUL.

**Comment by lylynaheng** [comment]
This is the two-slide showing how to use Ersilia Model Hub. I am not sure about how the model works, so I need feedback on that. By the way, @GemmaTuron there is no tutorial folder, only the asset folder.

Here is the link to the slides:
https://bit.ly/3OqAQbo

#PR

**Comment by Shamswaggirl** [comment]
> This is the two-slide showing how to use Ersilia Model Hub. I am not sure about how the model works, so I need feedback on that. By the way, @GemmaTuron there is no tutorial folder, only the asset folder.
> 
> Here is the link to the slides: https://bit.ly/3OqAQbo
> 
> #PR
Hello @lylynaheng,
Nice to meet you, these slides are really good with a neat design but I guess the steps are not detailed, if you improve that it would be great.

**Comment by lylynaheng** [comment]
Hello @Shamswaggirl,

Nice to meet you. Can you clarify the steps? My first draft was including the details of the installation part, but then I changed it because I don't consider it as how to use Model Hub. I need a clarification on that so that I can changes accordingly. 

Thank you!

**Comment by marv-tech** [comment]
Nice work, well done

**Comment by GemmaTuron** [comment]
Hi @lylynaheng 

Thanks for the work, the graphical material looks very nice. For the guide, there are three basic CLI commands:
`ersilia fetch eos0aaa`
`ersilia serve eos0aaa`
`ersilia api predict -i "CCCCC"`

you can check some of the other applicant issues with screenshots to learn more!

I think you can finish off this and prepare your final application on the website! thanks for the work!

**Comment by srcmilena** [comment]
Dear @lylynaheng, 

In your first task, I liked how you brought and mentioned our real situation in this world to the motivation between you and Ersilia. It was very nice to read what you wrote, you said it beautifully said. I hadn't thought of it that way! 
Thank you for sharing. 
Good work so far! Keep it going.

**Comment by sophiee-blip** [comment]
This is really nice, well done!
