### ISSUE TITLE
Outreachy Documentation Project: <pauline-banye>

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#204]
Applicant: <pauline-banye, Pauline B>
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [ ] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [x] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by pauline-banye** [comment]
Why am passionate about the Ersilia documentation project.

I grew up in a country where access to quality diagnostic medical care is either non existent or too expensive to incorporate and I have witnessed incidents where improper diagnosis have led to complications and in one case, death.

Prior to this internship, I had no idea about the Ersilia hub or what they were trying to accomplish but as I read through the documentation and presentations, I was able to gain a broad perspective of Ersilia's mission and I cannot stress how important and life changing it would be to incorporate the use of Ersilia models to improve medical diagnosis.

A high level project like Ersilia requires accurate, clear and easily understandable documentation and tutorials for easy adoption and to reduce the learning curve for scientists in low income countries like mine and I would be honored to contribute to this.

**Comment by pauline-banye** [comment]
link to PR

[Write a more standard README file #11 by Pauline Banye](https://github.com/ersilia-os/ersilia/pull/75)

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

Nice work thanks! Some minor comments only for your consideration:
- the installation requirements could have a link (for example, to git-lfs page)
- When you are inside a code block, we conventionally use # to indicate a comment, for example:
`# to create a conda environment
$ conda create -n ersilia python=3.7`
The  $ can be used to indicate the CLI command, but is not required.
- Double check the license file in the github repo !

**Comment by pauline-banye** [comment]
> Hi @pauline-banye
> 
> Nice work thanks! Some minor comments only for your consideration:
> 
> * the installation requirements could have a link (for example, to git-lfs page)
> * When you are inside a code block, we conventionally use # to indicate a comment, for example:
>   `# to create a conda environment $ conda create -n ersilia python=3.7`
>   The  $ can be used to indicate the CLI command, but is not required.
> * Double check the license file in the github repo !

Thanks so much for the constructive feedback @GemmaTuron ☺️. I'll update and make a PR to fix it.

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

Good job on the graphs! 
Please for this last week finish off the tasks you are working on, add them in a comment here and start preparing your final application in the website!

**Comment by pauline-banye** [comment]
> Hi @pauline-banye
> 
> Good job on the graphs! Please for this last week finish off the tasks you are working on, add them in a comment here and start preparing your final application in the website!

Thank you so much @GemmaTuron. I appreciate your feedback. I'll definitely finish up on the final pending tasks before Sunday and focus on the final application.

**Comment by pauline-banye** [comment]
@GemmaTuron Here's the link to the blog post I created outlining the strategic plan 2021-2023 for Ersilia.

https://medium.com/@paulinebanye/the-ersilia-strategic-plan-2021-2023-ab4b606a4ab0

**Comment by pauline-banye** [comment]
Updated the readme with requested changes from @GemmaTuron which included:

Changing the License from MIT to GNU Affero General Public License
Adjusting comment style in code block to use #
Adding links to installation requirements

Additional update
Added detailed installation instructions for windows systems

[PR #229 ](ttps://github.com/ersilia-os/ersilia/pull/229)

**Comment by loweyvana** [comment]
Nice slide

**Comment by pauline-banye** [comment]
> Nice slide

Thank you very much @loweyvana

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

Thanks, I have merged your PR! 
The blogpost looks good, I like that you included the image you had created thanks!

**Comment by pauline-banye** [comment]
> Hi @pauline-banye
> 
> Thanks, I have merged your PR! The blogpost looks good, I like that you included the image you had created thanks!

Thanks @GemmaTuron I enjoyed writing it 😀

**Comment by pauline-banye** [comment]
Here's the link to the technical card I created. 
I chose the model Mordred: a molecular descriptor calculator. @GemmaTuron 

[Ersilia's technical card](https://drive.google.com/uc?export=view&id=12Q8y69Dij0zfSuUH97jrmSamB7f_9MKO)

**Comment by marv-tech** [comment]
Great job!

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

thanks, nice work on the technical card! All the main fields are there! If only, when mentioning the publication it would be good to cite it in the standard way rather than putting the link, like: Turon et al, 2022 ...

But very good job thanks! I think you should focus  on writing the final application on the Outreachy website, good job!

**Comment by pauline-banye** [comment]
> Hi @pauline-banye
> 
> thanks, nice work on the technical card! All the main fields are there! If only, when mentioning the publication it would be good to cite it in the standard way rather than putting the link, like: Turon et al, 2022 ...
> 
> But very good job thanks! I think you should focus on writing the final application on the Outreachy website, good job!

Thanks so much for your feedback @GemmaTuron 😊. I'll edit and repost.

**Comment by lylynaheng** [comment]
> I worked on creating an image which depicts Ersilia's mission and vision.
> 
> I incorporated two main images. One showing a closeup of medical in a laboratory to outline medical research and another showing a close up of a doctor running analysis on a tablet to showcase the research capacity with machine learning tools.
> 
> In the middle, I placed an xray image of the human body to depict that the intersection between medical research and the machine learning tools for analysis is ultimately to treat the human body.
> 
> Below is the link to my image. I welcome any feedback or corrections @GemmaTuron [Ersilia's mission and vision](https://drive.google.com/uc?export=view&id=11-wk2nSBGiX5Qxl-eVhKUjEDv6i28KG_)

Good job on the design.

**Comment by pauline-banye** [comment]
> Why am passionate about the Ersilia documentation project.

Thanks so much @lylynaheng

**Comment by pauline-banye** [comment]
> > Hi @pauline-banye
> > thanks, nice work on the technical card! All the main fields are there! If only, when mentioning the publication it would be good to cite it in the standard way rather than putting the link, like: Turon et al, 2022 ...
> > But very good job thanks! I think you should focus on writing the final application on the Outreachy website, good job!
> 
> Thanks so much for your feedback @GemmaTuron 😊. I'll edit and repost.

Hi @GemmaTuron I have updated the [Ersilia's technical card](https://drive.google.com/uc?export=view&id=14JrzytG1aYcgl3S0DhIr3DhUlRRnsUrh). I removed the link and cited it in the standard way. 

I have also submitted my final application. I welcome any feedbacks and adjustments you have especially to the timeline I proposed

**Comment by GemmaTuron** [comment]
Thank you @pauline-banye!
I am closing this issue as the Contribution period is finalized, many thanks for your work and support! Looking forward to reading your application.
