### ISSUE TITLE
Error when trying to fetch a model with Ubuntu

### ISSUE THREAD

**Issue by Kcfreshly** [ersilia-os/ersilia#206]
**Describe the bug**
I have successfully installed ersilia on my windows but the models doesn't seem to work.
When I run a model it always brings error messages such as:
_pygit2.GitError: invalid argument: 'password'

**To Reproduce**
1. Go to 'ubuntu '
2.  after setting up ersilia
3. type: ersilia fetch blood-brain-barrier
4. See error: _pygit2.GitError: invalid argument: 'password'

**Expected behavior**
I expected the command to show model was fetched succesfully

**Screenshots**
![Screenshot (38)](https://user-images.githubusercontent.com/95097508/162565444-ef5fede6-926f-45bd-9310-a369a209c678.png)
![Screenshot (39)](https://user-images.githubusercontent.com/95097508/162565446-72249b01-681c-4a3e-972e-58d3acaa9be4.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 

**Additional context**

**Comment by Kcfreshly** [comment]
@miquelduranfrigola and contributors, your feedback will be so appreciated

**Comment by dauinh** [comment]
Hi, [the installation guide for Ersilia](https://ersilia.gitbook.io/ersilia-book/quick-start/installation)  says that for Ubuntu, you should install GitHub CLI and use it to log in as well.  Would it help?

**Comment by miquelduranfrigola** [comment]
Yes, this seems to be a GitHub issue. Please try to install it @Kcfreshly and let us know!

**Comment by Kcfreshly** [comment]
Thanks @dauinh @miquelduranfrigola the GitHub CLI fixed the issue.
Present challenge is that the models brings an empty output when ran...

**Comment by Rufaida98** [comment]
@Kcfreshly try to be sure that you are installed all the necessary packages like miniconda and git lfs and try again

**Comment by Kcfreshly** [comment]
All fixed than you.
