### ISSUE TITLE
Create a contributing guidelines for the project

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#21]
**Is your feature request related to a problem? Please describe.**
From a beginner's perspective, the first thing someone looks for is the contribution guidelines. In order to understand how to make a pull request, check related formats and to look for beginner friendly issues. 

**Describe the solution you'd like**
A readme file about contribution guidelines will be a great addition to make the project more user friendly and will also help in improving participation in the project.

**Describe alternatives you've considered**

**Additional context**

**Comment by sayantani11** [comment]
I am an outreachy applicant, and would love to be assigned this issue.

**Comment by victorabba** [comment]
I would love to be assigned this issue.

**Comment by ASLManasa** [comment]
I am an outreachy applicant, and would love to be assigned this issue.

**Comment by GemmaTuron** [comment]
> I am an outreachy applicant, and would love to be assigned this issue.

Hello @sayantani11 thanks for your initiative.
Please go ahead in creating the guidelines in a .md file and upload it in the /documentation (**not /docs**) folder. Add your name or an identifier to the document.

@victorabba and @ASLManasa this is a collaborative project. You can also add your own contribution guidelines or add a comment to another applicant work if you think there is something missing. Please abide by the code of conduct when working collaboratively

**Comment by Shivani-Parihar99** [comment]
I would also love to work on this issue.

**Comment by GemmaTuron** [comment]
Hello @sayantani11 

Sorry about it, the contribution file would be best placed in the root not in the documentation folder.
Could you change this before I merge your pull request?

@victorabba and @ASLManasa and @Shivani-Parihar99 , once the document is there I will think about missing sections and assign them to you one by one !

**Comment by Shivani-Parihar99** [comment]
@GemmaTuron Okay sure

**Comment by victorabba** [comment]
Okay @GemmaTuron

**Comment by loweyvana** [comment]
Hi, I am an outreachy applicant and would love to contribute to this.

**Comment by ASLManasa** [comment]
okay @GemmaTuron

**Comment by Jaya3112** [comment]
I think if we add some images which can lead people to their destination easily and they can contribute easily. It will be helpful for them. I would love to solve this issue .

**Comment by GemmaTuron** [comment]
@sayantani11 

Please see my comment on issue #44 and finish the changes specified there! For the rest, follow the new contribution guidelines to make it easier for the mentors to follow each applicant's work! thanks
I will close this comment now to avoid duplicating information

**Comment by sayantani11** [comment]
> @sayantani11
> 
> Please see my comment on issue #44 and finish the changes specified there! For the rest, follow the new contribution guidelines to make it easier for the mentors to follow each applicant's work! thanks I will close this comment now to avoid duplicating information

I didn't understand what you meant by merging new contribution file with the contribution guidelines file?
