### ISSUE TITLE
Feature Request: Implement autocompeletion to improve UX of the CLI

### ISSUE THREAD

**Issue by Nawarrr** [ersilia-os/ersilia#211]
### Is your feature request related to a problem? Please describe.

No, It's an enchantment 

### Describe the solution you'd like.

I'm still researching the solutions but there are a couple of implemented solutions online that might work.

### Additional context.

Auto completion would lead to a better UX and satisfaction, specially while writing model names

**Comment by Nawarrr** [comment]
@miquelduranfrigola I would love to work on this, Assign it to me please

**Comment by miquelduranfrigola** [comment]
Hi @Nawarrr this is a nice suggestion.
Before jumping into the coding, could you explain a little bit the approach that you are planning to take?
Thanks!

**Comment by Nawarrr** [comment]
It is harder than I thought and I'm still looking around, I'm currently looking into click's documentation.
If somebody asked to be assigned, please assign him too.
I will comment my approach before I start coding.

**Comment by Nawarrr** [comment]
@miquelduranfrigola I've got completely stuck and have no idea where to start, Incase you can give me a headstart, it would be great,
If anybody else would love to help me ask to be assigned.

**Comment by dauinh** [comment]
Hi @Nawarrr, maybe [this](https://community.platform.sh/t/how-to-enable-commandline-autocomplete-support-for-the-platform-cli-tool/312) would give you an idea of where to start. Or you can start with command correction first?

**Comment by Nawarrr** [comment]
> Hi @Nawarrr, maybe [this](https://community.platform.sh/t/how-to-enable-commandline-autocomplete-support-for-the-platform-cli-tool/312) would give you an idea of where to start. Or you can start with command correction first?

I've checked the link and I think it's for symfony (PHP framework) based apps.
Thanks for helping, means a lot

**Comment by miquelduranfrigola** [comment]
HI @Nawarrr I think this can help: https://click.palletsprojects.com/en/7.x/bashcomplete/

Let's stick to the click python library if possible, so no more dependencies to be installed.

**Comment by Nawarrr** [comment]
I've checked that earlier, I will give it another try, 
That's what stopped me from the begging, avoiding the use of more dependencies.

I will try again and reply to you with my plan before I start coding 
@miquelduranfrigola @dauinh  Thanks for your help

**Comment by Nawarrr** [comment]
I've been messing around with the ways mentioned here : https://click.palletsprojects.com/en/7.x/bashcomplete/ 

I've started by Activating auto completion as mentioned, here is what I've thought about and tried, I've added the activation line to .bashrc using a function that adds another snippet in default.py file (I'm only Experimenting, This is a really bad way to this )
![Activation_command](https://user-images.githubusercontent.com/46817360/163630357-b3ebeac7-fa5d-4fd1-8f8f-d6238d4db630.png)
The line was added correctly to .bashrc as I've checked manually (had to edit a line in __init__.py that calls the function with overwrite=False)
I've thought that it might work as the documentation mentions that it's implemented automaticly in every click cli, but the commands aren't click.Choice so that doesn't work.
I've then tried to provide a "Custom completion" by adding an autocompletion function to the fetch command (This is also really bad practice but I'm just experimenting to find out how to do it) 
![fetch_thing](https://user-images.githubusercontent.com/46817360/163630854-189af099-e022-4d40-b38f-f2b4c976b26d.png)

but it caused getting this error, 
![fetch_error](https://user-images.githubusercontent.com/46817360/163630909-67b26678-bd03-4685-ac3b-dcd53542e999.png)

**Comment by anamika-yadav99** [comment]
@Nawarrr what's the version of click installed in your local?

**Comment by Nawarrr** [comment]
> Contributor
I think it's the exact one installed by ersilia in the documentation, I will check whether it's not the latest

**Comment by anamika-yadav99** [comment]
@Nawarrr if it's <7.0 then auto-complete won't work

**Comment by miquelduranfrigola** [comment]
Hi I am closing this issue now - all progress is well noted and please, feel free to reopen it at any point!
