### ISSUE TITLE
For Third-party Model incorporation into the Hub

### ISSUE THREAD

**Issue by ifeoluwafavour** [ersilia-os/ersilia#23]
Ersilia accepts the incorporation of third-party models and would not mind suggestions.

**Model title**
Suggest a title for your model. For example, 'Antimicrobial activity prediction'

**Model features**
Describe the features of the model. For example, "The Antimicrobial activit prediction model predicts antimicrobial activity in a specimen."

**Use Case**
Give a brief tutorial of how the model is used. Screenshots and/or videos can be included.

**Publication**
Is there a link to a publication? (DOI, PMID, URL). If yes, include the link. 

**Code**
Is code available? If so, please provide link to repository (GitHub, GitLab, BitBucket)

**License**
Please include a license for the model.

**Comment by ifeoluwafavour** [comment]
This issue is in response to issue #15 made by Gemma asking for an issue template to request a model.

I hope to make more meaningful contributions

**Comment by victorabba** [comment]
I would love to contribute to this model.

**Comment by GemmaTuron** [comment]
thanks @ifeoluwafavour for the contribution!

@victorabba if there is something you wish to add to  please do so in this conversation thread. It will remain open for the week for any further contributions. It may be there is no further information to add, if you think that is the case, let me know so I can close the issue and check for other open issues to contribute to.

**Comment by victorabba** [comment]
Their is actually something missing. I will attend to it.

**Comment by victorabba** [comment]
Benefit of the model should be added to the template. 
Benefit: How can the model be of benefit in the field of science?

**Comment by ifeoluwafavour** [comment]
> Benefit of the model should be added to the template. 
> Benefit: How can the model be of benefit in the field of science?

Thank you for contribution @victorabba 
I don't know if I should include it because it would look like my contribution when you added the "benefit of the model" clause

**Comment by GemmaTuron** [comment]
Hello @ifeoluwafavour and @victorabba for your contributions.

I think this is an interesting discussion. The question _How can the model be of benefit in the field of science?_ is perhaps to general. Could you think of a way of rephrasing it so that it is more narrow?
For example, instead of how it can benefit the field of science - why is it relevant to the Ersilia Mission.

**Comment by ifeoluwafavour** [comment]
Okay. Thank you @GemmaTuron 

Can I put it like this:
**Third-party's Relevance to Ersilia's Mission**
State how the third-party model is relevant to [Ersilia's Mission](https://ersilia.io/)

**Comment by SHRIYA1706** [comment]
I would love to add some more points to at what @ifeoluwafavour had contributed.

We can add 'Test Case' and 'Flexibility and limitations' . 

Test Case which would basically include the input and the output format and the parameters to make the model even more clear to users while testing and get an idea of the exact keyword to be tested for. 

Flexibility and limitations would include any boundary condition when this model can be used if required. Also it will include the margin of error if any as limitation if is already being encountered while deploying the model. 

@GemmaTuron I would be glad if you consider this and suggest if I am missing out on something or is there anything you want to add.

**Comment by ifeoluwafavour** [comment]
> suggest

Thank you @SHRIYA1706

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron this discussion is great. We need to nominate one or a few assignees here (right bar).

**Comment by GemmaTuron** [comment]
Hello!

@ifeoluwafavour thanks for the clarification. @victorabba I would like you to also think about my question and answer it here so I can close the issue!
@SHRIYA1706 I think the test case might be a bit too much to ask of contributors simply for suggesting a model, but adding a clause about the limitations of the model would be interesting, thanks.

@victorabba please make your suggestion and then I will close this issue and modify the template accordingly

**Comment by victorabba** [comment]
Benefit of the model: How can the third party model help Ersilia to achieve it's goal?
Tips: 
1 Is it scientifically or medically related?
2 Does it provide a basis for disease prediction?

**Comment by GemmaTuron** [comment]
Hi @victorabba 
Thanks for the answers. I have been doing some thinking, I think relevant questions could be:
- What stage of the drug discovery cascade is your model contributing to?
- Describe the dataset used to train the model. @SHRIYA1706 this is a better way to understand the limitations of the model (i,e data comes from a very specific experiment, pulls from various ones, which size..)

I will cose this issue and modify the template with your suggestions!
