### ISSUE TITLE
Feature Request: Time Tracker in CLI

### ISSUE THREAD

**Issue by ps-19** [ersilia-os/ersilia#234]
### Is your feature request related to a problem? Please describe.

Sometime it takes lot of time to fetch a model. It takes too much time to make prediction sometime it depends mostly on two factors first one is amount of molecules involved in a model second is system configuration of any user. So their is need to add a time tracker to estimate how long a model takes to make predictions.

### Describe alternatives you've considered

Alternatively we need to work on implementing fasted fetching of data and making predictions.

**Comment by ps-19** [comment]
i want to work on this issue.

**Comment by Rufaida98** [comment]
@ps-19 @miquelduranfrigola maybe if you can make the models in compressed so the download will be easier which make the fetch time faster. I'll look for articles to help you 👍

**Comment by miquelduranfrigola** [comment]
Hi @ps-19 these are interesting suggestions.

There is a fantastic approach at the moment to calculating/estimating model download/fetch time #188. As you will see, a metadata file is used to do this estimation. An easy thing to do would be to add, in this metadata file, the average time to make one prediction. With this information in the metadata, we can tell the user the expected time it will take to run their predictions.

What do you think?

**Comment by miquelduranfrigola** [comment]
> @ps-19 @miquelduranfrigola maybe if you can make the models in compressed so the download will be easier which make the fetch time faster. I'll look for articles to help you 👍

Hi @Rufaida98 indeed, we need to do this soon. Could you find an interesting approach? Feel free to open a new issue to tackle this specifically.

**Comment by Rufaida98** [comment]
@miquelduranfrigola alright I will do that 🙏
