### ISSUE TITLE
Outreachy Code Project: <Fortune Max>

### ISSUE THREAD

**Issue by fortune-max** [ersilia-os/ersilia#236]
Applicant: <fortune-max>

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [x] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [ ] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [ ] Select one issue related to improving the CLI and request to be assigned to it.
- [ ] Link the #PR as a comment under this issue.
- [ ] Make any changes required in the PR and tick this box once it has been approved.
- [ ] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [ ] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [ ] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [ ]  Check the models available in the Hub
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Community
- [ ] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [ ] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [ ] I have submitted my final application to the project

**Comment by fortune-max** [comment]
Motivation
My younger sister is studying pharmacy in a university in Nigeria. From her I have learned that the prospects of conducting novel drug research here is pretty difficult. Most of our drugs are imported and packaged here for the same reason. The drug tests are done on subjects who live in different conditions, and are affected by different factors. There is also a prevalence of fake drugs, which has been an ongoing battle. Also some medical problems are more hard-hitting locally than elsewhere but not as much attention is given to them internationally. Reducing the amount of what needs to be done abroad from drug testing/discovery to distribution to patients goes a long way to reduce these problems. As she has some classmates who are into programming (and some who could use this an outlet for their creativity), I think such a project could open a lot of new doors for the upcoming pharmacology/pharmacognosy talent. This would bring a net positive to everyone involved.

**Comment by fortune-max** [comment]
I am not sure if it's a common enough issue but on Mac it seems you have to install hdf5 library perhaps using homebrew as the python dependency (hf5py) requires the library to be present locally first.

Followed the installation instructions here:
https://ersilia.gitbook.io/ersilia-book/quick-start/installation

To fix run:
`brew install hdf5@1.8`

Then on ARM chip Macs:
`ln -s /opt/homebrew/opt/hdf5@1.8/lib/libhdf5.10.dylib /usr/local/lib/libhdf5.dylib`

On Intel chip Macs:
`ln -s /usr/local/opt/hdf@1.8/lib/libhdf5.10.dylib /usr/local/lib/libhdf5.dylib`

**Comment by fortune-max** [comment]
Another Mac specific issue I encountered while setting up.

The .bashrc file is read when starting up ersilia.

As my default shell is zsh, no .bashrc file exists. This causes `ersilia/default.py/bashrc_cli_snippet` function call to fail ([line 119](https://github.com/ersilia-os/ersilia/blob/master/ersilia/default.py#L119)).

It is not immediately obvious this is the cause from the error thrown.

Running `touch ~/.bashrc` fixed this locally for me.

**Comment by fortune-max** [comment]
Running `ersilia fetch molecular-weight` kept failing for me until I ran 
`conda create -n eosbase-bentoml-0.11.0-py37`

 and activated environment
`conda activate eosbase-bentoml-0.11.0-py37`

Kept throwing a source environment not found
`File "/Users/fortune/code/ersilia/ersilia/utils/conda.py", line 297, in clone`
`raise Exception("{0} source environment does not exist".format(src_env))`
`Exception: eosbase-bentoml-0.11.0-py37 source environment does not exist`

**Comment by fortune-max** [comment]
For Apple Silicon, the h5py dependency doesn't work with `pip install` as it has to be built from source and the headers and shared library files are not present.

Before running `pip install -e .` , make sure to install hdf5 with brew

`brew install hdf5@1.8`

Add the necessary flags to your session to allow local compilation of h5py:

`export LDFLAGS="-L/opt/homebrew/opt/hdf5@1.8/lib"`
`export CPPFLAGS="-I/opt/homebrew/opt/hdf5@1.8/include"`

Make the shared library accessible to compiler

`ln -s /opt/homebrew/opt/hdf5@1.8/lib/libhdf5.10.dylib /usr/local/lib/libhdf5.dylib`

Then finally install erisilia dependencies 

`pip install -e .`

**Comment by fortune-max** [comment]
<img width="745" alt="Screenshot 2022-04-16 at 12 09 18" src="https://user-images.githubusercontent.com/31856097/163672703-39057b23-ff54-4371-8b5c-1701cc6e73fc.png">

Screenshot of a model in use to determine molecular weight of aspirin.

**Comment by fortune-max** [comment]
<img width="631" alt="Screenshot 2022-04-16 at 13 39 18" src="https://user-images.githubusercontent.com/31856097/163675301-8cd11e8e-6ac1-4a20-b0d4-5bf00fa0207a.png">
Local catalog of installed models.

**Comment by GemmaTuron** [comment]
Hi @fortune-max 

Thanks for checking the set up and installation of Ersilia. Please, could you report those problems in the form of a bug tracker opening a new issue for each one of them?

**Comment by fortune-max** [comment]
Sure, I'll be glad to help make the setup process go smoother for people sharing a similar environment as I am.

**Comment by fortune-max** [comment]
Hi @GemmaTuron 

Is there a reason the dependencies are being installed system-wide instead of the virtual environment created by conda?

Using `conda install --file requirements.txt` instead of `pip install -e .` is preferable to me and actually works around the h5py installation issue I faced.

See https://ersilia.gitbook.io/ersilia-book/quick-start/installation

**Comment by fortune-max** [comment]
I have attempted to install ersilia's dependencies using conda. Unfortunately a number of them are unavailable from conda's repo alone. I think the best way would be to have the instructions say

`conda install h5py`

Then 

`pip install -e .`

to get around the issue for Mac users. I will detail more of my findings in the issue I open.

**Comment by GemmaTuron** [comment]
Hi @fortune-max 

Thanks for the suggestions we will look into them as soon as possible. Unfortunately we won't be able to provide feedback before the application deadline so please go ahead and make your application listing these contributions so far.

Thanks!

**Comment by fortune-max** [comment]
Sure Gemma,

Glad to have helped. Will add to contributions now.
