### ISSUE TITLE
Bug report for the Ersilia model

### ISSUE THREAD

**Issue by victorabba** [ersilia-os/ersilia#24]
**Describe the bug**
A clear and concise description of what the bug is. Example can be a calculation error or a missing command.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by GemmaTuron** [comment]
hello @victorabba ,

This bug report template is the default in our repository. Can you let me know what is the issue?
thanks!

**Comment by victorabba** [comment]
I don't think their is need for a smartphone field since the model usage is on a PC.

**Comment by miquelduranfrigola** [comment]
Good catch @victorabba . Solved and closing issue.
