### ISSUE TITLE
Feature Request: Improve model search functionality

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/ersilia#241]
### Is your feature request related to a problem? Please describe.

yes, every once in a while there's a typo or user enters a wrong spelling. model search function in such cases return null table which could be confusing for the user. 

### Describe the solution you'd like.

I'm still exploring for a good solution.  perhaps, a simple approximate string matching algorithm which would return the closest matching model name in the ModelSearch function and also on fetch command.

**Comment by anamika-yadav99** [comment]
@GemmaTuron would this be a feature you would like to have?

**Comment by anamika-yadav99** [comment]
_class ErsiliaModel(ErsiliaBase):

    """Child class of ErsiliaBase which serves as the main class for Ersilia Model.
       
       This class provides methods to fetch, serve, api and more.  
       
       
       Attributes:
           model(str):
           save_to_lake(bool, optional): Option to save the calculation to Isaura Lake  
           service_class(str, optional): Service class used. Accepts only [None, conda, venv, system, docker].
           config_json(str, optional): Path to a configuration file.
           credential_json(str, optional): Path to a credentials file.
           verbose(str, optional): Set verbosity.
           fetch_if_not_avalible(bool, optional): Fectches model from the hub if not available in the local.
    """_

**Comment by dauinh** [comment]
Hi @miquelduranfrigola @anamika-yadav99, can i work on this feature as well?

**Comment by dauinh** [comment]
I found [this article](https://towardsdatascience.com/autocorrect-in-google-amazon-and-pinterest-and-how-to-write-your-own-one-6d23bc927c81) to be helpful. Do you think we can do after query autocorrection and implement a Trie to find the correct command?

**Comment by anamika-yadav99** [comment]
Hi @dauinh Thanks for the help. The article was insightful. I'm also thinking of comparing the distance between the input model name and the model names in the hub or local and returning the closest matching model name. This is basically string matching algorithm only. Let's wait for what @miquelduranfrigola and @GemmaTuron have to say on this.

**Comment by dauinh** [comment]
> Hi @dauinh Thanks for the help. The article was insightful. I'm also thinking of somewhere along the similar lines. Compare the distance between the input model name and the model names in the hub or local and then return the closest matching model name. This is basically string matching algorithm only. Let's wait for what @miquelduranfrigola and @GemmaTuron have to say on this.

Oh, i see what you mean... Thank you for clarifying!

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

This sounds fantastic. My only concern is if the search function for close models would slow down the package too much, but we can certainly explore options. Can you add this to your application as a task?

**Comment by miquelduranfrigola** [comment]
This is interesting overall. Because we are using AirTable to store our models, my immediate guess is that there may be some AirTable functionality for fuzzy string matching or something like this in a text-based search. If this is the case, we should certainly take this avenue.

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola  I looked into Airtable API. Unfortunately it doesn't support Fuzzy Search. Fuzzy search can easily be achieved using fuzzywuzzy python library but  I guess, you wouldn't want any more dependency in ersilia. So, I have modified the Search function in Ersilia  to include an algorithm which calculates the distance between the input from cli and data which is imported from hub in model catalog. It doesn't take a lot of time to perform the search through the table. I think similar solution would work for `model fetch` command as well. Shall I proceed with my approach so far?

**Comment by miquelduranfrigola** [comment]
Hi, @anamika-yadav99 thanks. This sounds like a good approach. Let's go for it. I am more interested in the `catalog` command than in the `fetch` command. So let's try with `catalog`, to start with?

**Comment by anamika-yadav99** [comment]
@miquelduranfrigola I'm almost done with the catalog command. I'll raise the PR by tomorrow.

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola I'm sorry for the delay. I was caught in some college work which took longer than expected. I have raised a pr for catalog command. Looking forward to your feedback.

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 this is great. I have approved PR #262 and closing the issue now! Many thanks.
