### ISSUE TITLE
Feature Request: Add a WIP so that contributors can make 'Work in Progress' PRs

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#246]
### Is your feature request related to a problem? Please describe.

As a contributor, there are issues/features that need time to get resolved. Also, if we do end up merging #210 it will be good for the contributors to first have a WIP PR for issues that tackle a lot of documentation changes, in this way they'll also be able to take reviews from the maintainers and fix lint errors. 

### Describe the solution you'd like.

**The feature can be added only by maintainers but suggestions are welcome**  
I am thinking of something related to this https://github.com/marketplace/wip
 

### Describe alternatives you've considered

I am unsure if there's an better alternative or something else, I am still researching on this
And discussions and suggestion from other contributors are also welcome

**Comment by sayantani11** [comment]
@GemmaTuron @miquelduranfrigola

**Comment by miquelduranfrigola** [comment]
This is interesting @sayantani11. Perhaps it would be sufficient to have a label called "WIP"?

**Comment by sayantani11** [comment]
Yep!!!
But WIP PRs shouldn't be running all the tests, to save resources. We
haven't added any advanced workflows yet.... But when we do, WIP PRs should
be running only linters and other tests/workflows later.
Idk, if I am making sense 😅

**Comment by miquelduranfrigola** [comment]
You are making sense as always!
I see your point.
Just as an FYI, we are working with some corporate folks that are helping with the GitHub Actions triggered for specific PR. One feature we are adding is triggering different actions depending on labels. So we can certainly add a "WIP" label and trigger only a subset of bare-minimum tests.

**Comment by GemmaTuron** [comment]
Hi!

We have not added the WIP label yet, but this is on the list for when the PR GitHub Actions are set, so I will close this issue while we wait for the implementation of GitHub Actions.
