### ISSUE TITLE
Bug 🐛: Installation fails on Mac [M1], h5py. Documentation suggestions/fixes

### ISSUE THREAD

**Issue by fortune-max** [ersilia-os/ersilia#248]
### Describe the bug.

The [installation documentation](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) says we install dependencies using `pip install -e .`. I suggest we instead use `conda install h5py && pip install -e .`.

While pip is fine for almost all packages, it requires compilation for numpy which is a dependency of h5py required by ersilia.

If the user hasn't already had numpy previously installed, it will need to be compiled from source if pip is used.

Assuming clang/gcc and necessary include files and shared libraries are present for compilation, there's still one hurdle. On Mac, hdf5 isn't bundled as part of the include headers/shared library and has to be installed to allow a line `#include "hdf5.h"` to work. If you still choose to use pip I have detailed my way of accomplishing same using pip [here](https://github.com/ersilia-os/ersilia/issues/236#issuecomment-1100629081) wherein we actually go ahead and install the library needed.

To get around that, and make setting up easier simply run `conda install h5py` instead.

### Describe the steps to reproduce the behavior

This issue is only specific to miniconda3 as anaconda comes bundled with numpy.

1. Clone ersilia
2. Create a conda virtual environment
3. Make sure numpy is not installed in virtual environment (default in Miniconda3)
4. Make sure hdf5 has not been installed using homebrew (default in Mac [M1])
6. cd into working directory for ersilia
7. activate ersilia virtual environment
8. run `pip install -e .`

### Expected behavior.

Installation of pip packages runs for a while till it hits h5py -> numpy. Then it throws a compilation error that a missing header file couldn't be found => `#include "hdf5.h"`.

### Screenshots.

<img width="1440" alt="Screenshot 2022-04-19 at 12 07 20" src="https://user-images.githubusercontent.com/31856097/163990835-1203e58e-f026-499f-b9f3-7579b9c47d4c.png">
<img width="1440" alt="Screenshot 2022-04-19 at 12 08 00" src="https://user-images.githubusercontent.com/31856097/163990878-8e7f38f2-0028-44bb-ac08-08103f92b75d.png">

### Operating environment

MacBook Air M1 2020. macOS Big Sur 11.5.2.

**Comment by fortune-max** [comment]
Hi @miquelduranfrigola ,

Yes a conda package would solve this issue. Glad to see it's in the works. Thanks for reviewing.

**Comment by miquelduranfrigola** [comment]
I really appreciate your points. Let me close the issue now but feel free to reopen at any point.
