### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by victorabba** [ersilia-os/ersilia#25]
**What is your feature request ?, Is  your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GemmaTuron** [comment]
Hello @victorabba is this responding to any open issue or is a new feature you would like to add?

thanks!

**Comment by victorabba** [comment]
I didn't think we were to make any changes to the issues. However, I would like to suggest that the first question should be ' What is your feature request?' before the second question' Is your feature request related to a problem?
