### ISSUE TITLE
Bug 🐛: Improving Installation Guidelines

### ISSUE THREAD

**Issue by Med16-11** [ersilia-os/ersilia#257]
### Describe the bug.

 GitHub CLI and GitHub LFS installation steps are mentioned at the bottom due to which people start installing the Ersilia Python package before installing these dependencies. This makes the installation process more confusing.

### Describe the steps to reproduce the behavior

1. Go to the README.md file.
2. Click on the installation guide.
3. Scroll down to the bottom, you will see the dependencies there.
4. If you will try to install the model in your system just by setting conda environment without installing dependencies, you will get the error.

### Expected behavior.

Due to this arrangement of steps in the installation process, people often get confused during installation.

### Screenshots.

These are the errors I was receiving while installation

![image (1)](https://user-images.githubusercontent.com/78318301/164971020-86aeb7ec-848c-4c7b-8458-91d329b935ad.png)
![image](https://user-images.githubusercontent.com/78318301/164971031-fb8d4a27-8c78-4d9f-8170-44d540b34116.png)

### Operating environment

Ubuntu on Windows

### Additional context

It's a small problem, we just need to add a line after 4 the point mentioning that do not forget to install dependencies before installing the model hub
![2](https://user-images.githubusercontent.com/78318301/164971151-3dc82402-3166-4b9a-bf2d-960ddc53ac07.PNG)

**Comment by sayantani11** [comment]
Can I take this?

**Comment by Med16-11** [comment]
Hey @sayantani11! 
Actually, I am an Outreachy applicant and I am not sure that I am allowed to assign this issue to anyone. Also, I am working on this issue. 
I think @GemmaTuron can guide us !

**Comment by GemmaTuron** [comment]
Hi @Med16-11 

Thanks for pointing this out. In the ReadMe file it clearly states to go first to the Installation guide to check dependencies,  where Git LFS and others are specified: 
_Some pre-trained models, especially the ones that contain many parameters, require Git Large File Storage (LFS). Make sure this Git extension is [installed](https://git-lfs.github.com/) before proceeding._

We do not want to add to many information on the quickstart at the readme file, this is why we redirect the users to the installation. Do you think this is not sufficiently clear?

**Comment by Med16-11** [comment]
@GemmaTuron Thanks for the clarification. 
It's just that many people were facing this installation problem. I thought maybe, it would be better if we could add any NOTE in the starting. Although the guidelines are clear. I think contributors just need to read it carefully.
