### ISSUE TITLE
Installation steps of Ersilia Model for Windows operating system 

### ISSUE THREAD

**Issue by ifeoluwafavour** [ersilia-os/ersilia#26]
I noticed that there are no installation steps for Ersilia Model on Windows and the steps would be coming soon.

Please, I would like to work with the developers to know how to install Ersilia on Windows and help write the steps.

I have already downloaded Miniconda, activated the Ersilia environment and installed Ersilia. I just need to collaborate with the developers for it to properly work on my system.

Thank you.

**Comment by victorabba** [comment]
I will like to contribute to this issue. I'm currently working on it though.

**Comment by GemmaTuron** [comment]
Hello @victorabba and @ifeoluwafavour 

As you may find in the installation notes, Ersilia only works in Windows Subsystem Linux (WSL). We think attempting to refactor the package to work natively on Windows is too complicated at this step. We would welcome though a proper guide for Windows users on how to install WSL (instead of only this [paragraph](https://ersilia.gitbook.io/ersilia-book/quick-start/installation))

I will assign this task to both of you, to complete it create an .md file in the /docs folder with the name <wsl_yourname.md>.
Follow your writing style and use your experience in installing the WSL system yourselves to get as much detail as possible. 

This is already a medium size task, please take your time to complete it.
Remember to record your contributions to the application page in Outreachy

**Comment by ifeoluwafavour** [comment]
> Hello @victorabba and @ifeoluwafavour 
> 
> As you may find in the installation notes, Ersilia only works in Windows Subsystem Linux (WSL). We think attempting to refactor the package to work natively on Windows is too complicated at this step. We would welcome though a proper guide for Windows users on how to install WSL (instead of only this [paragraph](https://ersilia.gitbook.io/ersilia-book/quick-start/installation))
> 
> I will assign this task to both of you, to complete it create an .md file in the /documentation folder (**not /docs**) with the name <wsl_yourname.md>.
> Follow your writing style and use your experience in installing the WSL system yourselves to get as much detail as possible. 
> 
> This is already a medium size task, please take your time to complete it.
> Remember to record your contributions to the application page in Outreachy

Thank you very much. @GemmaTuron 

I will start working on it now

**Comment by GemmaTuron** [comment]
To other Applicants, this issue will accept **up to 5 assignes**. The next weeks we will work in merging the different versions into one, if you are interested in contributing here ping me and I will assign this task as well.

**Comment by victorabba** [comment]
Thanks @GemmaTuron, I will get to work.

**Comment by martwebber** [comment]
Hello @GemmaTuron, I would love to contribute to this issue.

**Comment by dchidindu5** [comment]
Hello @GemmaTuron I'm interested in working such an issue

**Comment by adeola-dev** [comment]
Hello @GemmaTuron , Iwould love to contribute to this issue

**Comment by camus60** [comment]
@GemmaTuron   I would like to suggest that the current contributors also design a tutorial for running the code on Gitbash, since WSL is only available on newer versions of the windows operating system,but gitbash is available on older and newer versions.

**Comment by Exquisitedesigner** [comment]
@GemmaTuron , I would love to contribute to this as well. I figured out while setting up the repository on my Windows machine that it's a bit tricky and the current Documentation did not give a clear guidance as to how to set this up for a Windows client.

Having a more detailed narration and help to setting this up for a Windows user will go a long way in creating inclusiveness for all major OS users.

More than happy to collaborate with other assignees of this task.

**Comment by GemmaTuron** [comment]
Hello all,

Thanks for your great suggestions. If you go to the Slack channel you will see new contribution guidelines established. Please follow them and add your comments and suggestions under the relevant page. I will close this issue to avoid duplicating information!
