### ISSUE TITLE
Compress models 

### ISSUE THREAD

**Issue by Rufaida98** [ersilia-os/ersilia#261]
**Is your feature request related to a problem? Please describe.**
@miquelduranfrigola This to help issue #234 and #188 

**Describe the solution you'd like**
I found an interesting essays so everyone please feel free to read them and help to contribute ☺️

 https://link.medium.com/XtCGGnB1Lpb

 https://link.medium.com/b1JUyJU0Lpb

**Comment by miquelduranfrigola** [comment]
Hi @Rufaida98 this is very interesting, thanks for sharing. Certainly something we can take into account for our "Lite models" library, @GemmaTuron : https://github.com/ersilia-os/eos-lite-chem

**Comment by Rufaida98** [comment]
@miquelduranfrigola i am happy to be able to help. i will search more about compressed models and hopefully we can integrated to the current models

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola @Rufaida98 I know of a open source surrogate modeling toolbox which might come in handy if there's a plan to create surrogate models. It's
https://smt.readthedocs.io/en/latest/

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 - great suggestion, will look into it ASAP. At the moment, we create surrogate models quite successfully with KerasTuner, using 1, 2 or 3 dense layers. The key here is that we have a big (master) model (https://github.com/ersilia-os/groverfeat) that we can use as a pretrained model, and then the surrogate models are simple concatenations at the end of groverfeat.
