### ISSUE TITLE
Bug 🐛: Repition in issue templates

### ISSUE THREAD

**Issue by Sukriti-sood** [ersilia-os/ersilia#264]
### Describe the bug.

Recent commit has added `bug-report.md` and `feature-request.md` which resulted in having 2 `bug-report` an `feature-request` templates...

### Screenshots.

![Screenshot 2022-05-19 092556](https://user-images.githubusercontent.com/55010599/169201163-f3c43f1e-cfa8-4203-b213-ca6a1c456c35.png)

### Operating environment

Ubuntu

**Comment by miquelduranfrigola** [comment]
Thanks for noticing this @Sukriti-sood.
