### ISSUE TITLE
Bug 🐛: Version conflicts while installing Ersilia

### ISSUE THREAD

**Issue by Amna-28** [ersilia-os/ersilia#269]
### Describe the bug.

I am working on Linux-Ubuntu 64-bit.
While Installing Ersilia, I encountered two dependency-related conflicts: 

1. ersilia and isaura require different versions of h5py and loguru. I get the following error:
    `isaura 0.0.1 requires h5py==3.4.0, but you have h5py 3.7.0 which is incompatible.`
    `isaura 0.0.1 requires loguru==0.5.3, but you have loguru 0.6.0 which is incompatible.`

2. Bentoml and sqlalchemy:
    `bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 1.4.36 which is incompatible.`

### Describe the steps to reproduce the behavior

1. Install Anaconda, Docker, Git and Git-lfs
2. Create Anaconda environment with python version 3.7: 
    `conda create -n ersilia python=3.7`
3. Activate the environment and install ersilia:
    `conda activate ersilia`
    `git clone https://github.com/ersilia-os/ersilia.git`
     `cd ersilia`
     `pip install -e .`
4. Install isaura:
    `git clone https://github.com/ersilia-os/isaura.git`
    `cd isaura`   
    `pip install -e .`

### Screenshots.

![image](https://user-images.githubusercontent.com/98670206/179453949-83533898-95d6-480b-85a9-5474605efe92.png)
![image](https://user-images.githubusercontent.com/98670206/179453972-7a1acb6c-43bd-4e8b-a4bd-3132d65ef50a.png)

### Operating environment

Ubuntu 20.04.3

**Comment by miquelduranfrigola** [comment]
This has been resolved. Thanks @Amna-28 !
