### ISSUE TITLE
Bug 🐛: Error when specifying output file path in Colab only

### ISSUE THREAD

**Issue by ifeoluwafavour** [ersilia-os/ersilia#271]
### Describe the bug.

In Colab, when I specify a file path for a model to save the output pf a prediction or calculation on an input file, an error arises.
 
This method of specifying the output's file path works on the CLI but the error came up in Google Colab.

### Describe the steps to reproduce the behavior

In Google Colab, after installing Ersilia and mounting the drive, I went ahead to run the model.
```
!ersilia fetch eos4u6p
!ersilia serve eos4u6p
!ersilia api predict -i "/content/drive/MyDrive/ersilia-figures/data/eml_canonical.csv" -o "/content/drive/MyDrive/eostest/eml_eos4u6p.csv"
```
Then I got this error:
`TypeError: is_worth_splitting() got an unexpected keyword argument 'path'`

### Expected behavior.

The expected output is the name of the csv file which is `eml_eos4u6p.csv`

### Operating environment

Google Colaboratory

**Comment by miquelduranfrigola** [comment]
Hi @ifeoluwafavour thanks for posting this bug. I have now resolved it. It was not specific to Colab - it was related to writing output in a csv file.

As an FYI, I have included some CircleCI tests to prevent this and similar errors in the future (cc @GemmaTuron):

```
      - run:
          name: Test molecular weight on inputs and outputs
          command: |
              source activate ersilia
              ersilia serve molecular-weight
              ersilia api -i "CCC" > output_one_0.json
              ersilia api -i "CCC" -o output_one_1.json
              ersilia api -i "CCC" -o output_one_3.csv
              ersilia api -i test/inputs/compound_list.csv > output_list_0.json
              ersilia api -i test/inputs/compound_list.csv -o output_list_1.json
              ersilia api -i test/inputs/compound_list.csv -o output_list_2.csv
              rm output_*
```
