### ISSUE TITLE
Bug 🐛: eos77w8

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#273]
### Describe the bug.

When fetching eos77w8 it automatically creates a features.npz folder in the location where you are at. This features should probably be downloaded in the eos folder instead.
@Amna-28 this model was incorporated by you, can you check it?

### Describe the steps to reproduce the behavior

ersilia fetch eos77w8

### Expected behavior.

No folder or file is downloaded in the directory you are located

### Operating environment

Ubuntu 20.04.1 LTS

**Comment by GemmaTuron** [comment]
It also happens with the eos1amr @Amna-28

**Comment by GemmaTuron** [comment]
As an update, this seems to be an issue when locating the path to the features.npz file and happens across all Grover models. We are working to redirect them to the appropriate folder.

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron and @Amna-28 - has the issue been solved?

**Comment by Amna-28** [comment]
Hi @GemmaTuron and @miquelduranfrigola, this issue has been resolved.
