### ISSUE TITLE
Bug 🐛: Mol2Vec Featurizer for eos30gr

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#274]
### Describe the bug.

Mol2Vec featurizer is unable to convert SMILES of well known drugs, like isoniazid and pyrazinamide. Since these are used at fetching time, the model cannot be fetched. 

### Describe the steps to reproduce the behavior

ersilia fetch eos30gr

### Expected behavior.

I would suggest to re-train the model using a differetn featurizer, because it seems we will encounter this error for many molecules. 

### Operating environment

Ubuntu 20.04.1 LTS

### Additional context

This model was originally retrained and incorporated by @miquelduranfrigola and @azycn 
[Model repo ](https://github.com/ersilia-os/eos30gr)

**Comment by miquelduranfrigola** [comment]
This is a very important point. Can you please clarify which is the output given by mol2vec when it is unable to produce a vector? Does the model crash or does it return nan values?

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron what is the status of this?

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola sorry I missed your comment. Molecules that cannot be transformed make the pipeline crash so we should add a try - exception module to skip the molecules that crash.

**Comment by miquelduranfrigola** [comment]
OK, thanks. Do you know a molecule that is correct with RDKIT but actually crashes in Mol2Vec? It will be useful for debugging.

**Comment by GemmaTuron** [comment]
If I'm not wrong, it was isoniazid and pyrazinamide

**Comment by miquelduranfrigola** [comment]
I have been working on this model. Could we try it again?

**Comment by pauline-banye** [comment]
Hi @GemmaTuron ,

I have encountered an error on colab while testing this model. Here is the link to the colab notebook
https://colab.research.google.com/drive/13pkZhqOJC86mAKL8mPrOJThtmqK-PoiY?usp=sharing. 

```
Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos30gr:predict did not produce an output2023-01-17 12:28:17.433289: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading molecules.
Keeping only molecules that can be processed by RDKit.
Featurizing molecules.

```

**Comment by GemmaTuron** [comment]
Thanks @pauline-banye !

The tensorflow is a warning, not an error, so this is not the root of the issue.
It seems despite the modifications we did @miquelduranfrigola the molecules are still having trouble to be standardised? 
I am unable to find this warning snippet on the model, can you guide me @miquelduranfrigola ?
`Loading molecules.
Keeping only molecules that can be processed by RDKit.
Featurizing molecules.`

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

I have tested this model on colab notebook.

I get the following error message:

'''
Error message:

Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos30gr:predict did not produce an output2023-01-17 20:54:12.497324: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading molecules.
Keeping only molecules that can be processed by RDKit.
Featurizing molecules.

'''

colab link:
[https://colab.research.google.com/drive/1WRfihHLAFZTXYNg8gapuFIMYa9no6S1q#scrollTo=jTrufuanccB-](https://colab.research.google.com/drive/1WRfihHLAFZTXYNg8gapuFIMYa9no6S1q#scrollTo=jTrufuanccB-)

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, I tested this on colab and initially encountered this error

Error message:

```
Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos30gr:predict did not produce an output2023-01-17 13:18:55.346775: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading molecules.
Keeping only molecules that can be processed by RDKit.
Featurizing molecules.
```

However I retested the model two more times and the test did not return this error again.  I did not install any new dependencies after the initial test. It seems that this error is intermittent since @Femme-js  experienced the same error. I am currently running a final test  on colab and the CLI, I would update the results once I'm done.

**Comment by pauline-banye** [comment]
### Update on CLI test
@GemmaTuron I had to run the test on the CLI a few more times after running `pip install pandas`, I ended up installing pandas-1.3.5, pytz-2022.7.1 and joblib-1.2.0. 
Current error returned is:
```
Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos30gr:predict did not produce an outputTraceback (most recent call last):
  File "/root/eos/repository/eos30gr/20230118141005_E3D2D0/eos30gr/artifacts/framework/code/main.py", line 9, in <module>
    from mol2vec import features
ModuleNotFoundError: No module named 'mol2vec'

```
[eos30gr_fetch.log](https://github.com/ersilia-os/ersilia/files/10447469/eos30gr_fetch.log)

**Comment by GemmaTuron** [comment]
Thanks @pauline-banye and @Femme-js 

We will have a look into this!

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron - you reopened this issue. What is the current status?

**Comment by GemmaTuron** [comment]
We will get to this model under the "Toxicity" focus.

**Comment by GemmaTuron** [comment]
We have refactored this model, retraining it using a simple QSAR approach (morgan fps +  random forest).
It gives good performance (AUROC 0.98)
