### ISSUE TITLE
Bug 🐛: eos2b6f creates test.pkl file

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#275]
### Describe the bug.

The model [eos2b6f](https://github.com/ersilia-os/eos2b6f) creates a file named test.pkl at the destination folder at fetching time

### Describe the steps to reproduce the behavior

ersilia fetch eos2b6f

### Expected behavior.

If this file is necessary, it should be stored with the model, under eos/repository...
If it is not necessary for running the model it should be deleted

### Operating environment

Ubuntu 20.04.1 LTS

### Additional context

@svolk19-stanford was the model contributor

**Comment by svolk19-stanford** [comment]
The original pkasolver model relies on a package called dimorphite_dl to calculate pka values. The pkasolver model piped output from dimorphite_dl to itself by means of this test.pkl file, which was left over when the run was complete. I added logic to first output this test.pkl file to a predictable location, then delete it after the run is over.
