### ISSUE TITLE
Feature Request: Provide a more informative error message if Git LFS is not installed

### ISSUE THREAD

**Issue by marcostorrework** [ersilia-os/ersilia#277]
### Is your feature request related to a problem? Please describe.

Some models require Git Large File Storage (LFS) to run. One example is the model chemprop-antibiotic.
If LFS is not installed and we try to fetch a model that requires it, it fails with the error "Model API eos4e40:predict did not produce an output", which is not very helpful.
If we run in verbose mode, there is actually an indication of the problem:
`fatal: 'lfs' appears to be a git command, but we were not able to execute it. Maybe git-lfs is broken?`
but this is hidden in hundreds of lines, so it is not easy to see that it is the cause of the problem.

### Describe the solution you'd like.

It would be useful to have a more informative message in such situation, that clearly indicates that the installation of Git-LFS is a requirement.
Nice to have: an error message that shows also in non-verbose mode.

**Comment by GemmaTuron** [comment]
Hi @marcostorrework !
I agree this is a major issue users encounter often, so we should add one check specifically for Git-LFS and make an easy to understand error if that is the case. Let's see if someone from the community can pick this up to work on!

**Comment by Zainab-ik** [comment]
@GemmaTuron I don't know if this has been worked on but I noticed installing outside the ersilia environment poses an error also while fetching.

**Comment by GemmaTuron** [comment]
Hi @Amna-28,

Did you tackle this issue? What is the status?

**Comment by miquelduranfrigola** [comment]
This has been resolved. Closing issue!
