### ISSUE TITLE
Add folder for Tutorials - Outreachy begginers

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#28]
Hello,

Could you create an empty folder in the ersilia project with the name "tutorial" ?
This issue is great if you are a beginner who wants to test how the git fork, branch, and pull requests work. I recommend reading this [tutorial](https://blog.openreplay.com/getting-started-with-open-source-how-to-contribute) first
Please note this issue will only be assigned to one applicant, ping me here if you want to contribute to this.

**Comment by kbetty** [comment]
Hello @GemmaTuron am an outreach applicant and passionate about the project. I am interested to kick off with my contribution with this task. Thanks

**Comment by Riyabelle25** [comment]
Hi @GemmaTuron! I would love to contribute to this project and am an Outreachy applicant. My interests particularly lie in the intersection of ML and Software Dev, so I feel I'll be a natural fit here 👋 
I have started looking at other open issues in this project, do let me know if I can be assigned this issue here as well

**Comment by dchidindu5** [comment]
Hello @GemmaTuron, I'd love to work on this project as soon as possible. Id be willing to devote my time to this

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your interest. @kbetty I have assigned the issue to you. @Riyabelle25 and @dchidindu5 please look for open issues to contribute!
thanks

**Comment by kbetty** [comment]
Hello @Riyabelle25 here is the [PR](https://github.com/ersilia-os/ersilia/pull/32)

**Comment by GemmaTuron** [comment]
thanks @kbetty can you now delete the .keep file inside the folder?

**Comment by kbetty** [comment]
Welcome @GemmaTuron ! Let me make a PR to address the issue ASAP.

**Comment by kbetty** [comment]
Hello @GemmaTuron have come to learn that Git does not care about folders - it cares about files. Therefore, if a folder is empty, Git will not offer you to add it to version control. Here is the documentation at https://www.git-tower.com/learn/git/faq/add-empty-folder-to-version-control

So when I delete that hidden file, Git considers the folder to be deleted as well.

Here is my suggestion:
We can have that file present in that folder for now until a file is added to the folder then I will take on the initiative of removing that hidden file.

Let me know what you think?

**Comment by GemmaTuron** [comment]
Hi @kbetty 

Well done. Directories in GitHub are created once a file is directed to them. When applicants start uploading their contributions we can delete the placeholder.
Please record this contribution in the Outreachy website!

Thanks!

**Comment by kbetty** [comment]
Thanks @GemmaTuron 

> When applicants start uploading their contributions we can delete the placeholder.

I will take the initiative to ensure the placeholder is removed once file(s) are uploaded in the folder.

> Please record this contribution in the Outreachy website!

Sure! This is my first task in open source development and has taught me to something that git does not track empty folders.
