### ISSUE TITLE
[Epic] Auto-test New Model Submissions

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#280]

**Comment by miquelduranfrigola** [comment]
Hello @GrantBirki and @Lehcar : I have slightly modified a previous action by @honeyankit to be potentially used to auto-test new model submissions. You can find it [here](https://github.com/ersilia-os/ersilia/actions/workflows/quick-manual-model-test.yml).

Basically what is different is that we:
* Only do 5 predictions instead of 100
* Run models on verbose mode (`-v`), so there is more log in the GitHub Actions console.

We would need to modify this action a little bit, I assume, to catch the id of the model (probably from the current github repo path, or from the README file). At the moment, the model id is specified manually.

What do you think, does this look good?

**Comment by GrantBirki** [comment]
@miquelduranfrigola I think that looks great! Is this a workflow that would be helpful to have the artifact saved with log output from the logs when the test fails?

**Comment by miquelduranfrigola** [comment]
Yes, I think so! From what I see, the log file is stored at `/home/runner/eos/current.log`. So if we can collect that file, that'd be awesome! Otherwise, we can still see the log in the console with the current action, so that would also be ok for now if the artifact turns out to be difficult.

**Comment by Lehcar** [comment]
> Yes, I think so! From what I see, the log file is stored at `/home/runner/eos/current.log`. So if we can collect that file, that'd be awesome! Otherwise, we can still see the log in the console with the current action, so that would also be ok for now if the artifact turns out to be difficult.

I think it should be pretty straightforward. I'll see if I can add that real quick

**Comment by Lehcar** [comment]
Ok, so it looks like `/home/runner/eos/current.log` is 0 bytes, but `/home/runner/eos/console.log` has data. Here are some options for the upload:

1. [Upload all `.log` files in `/home/runner/eos`](https://github.com/ersilia-os/ersilia/actions/runs/3681361624)
2. [Only upload `/home/runner/eos/console.log`](https://github.com/ersilia-os/ersilia/actions/runs/3681449466)

We could also `tee` the logs from each step: 

```
      - name: Predict output
        run: |
          source activate | tee /tmp/predict-output.log
          echo "Sample model id selected: $MODEL_ID" | tee -a /tmp/predict-output.log
          ersilia -v fetch $MODEL_ID | tee -a /tmp/predict-output.log
          ersilia -v serve $MODEL_ID | tee -a /tmp/predict-output.log
          ersilia sample -n 5 -f input.csv | tee -a /tmp/predict-output.log
          ersilia -v api -i input.csv | tee -a /tmp/predict-output.log
          ersilia close | tee -a /tmp/predict-output.log

      - name: Upload log output
        uses: actions/upload-artifact@v3
        with:
          name: ersilia-predict-logs
          path: /tmp/predict-output.log
```

**Comment by GrantBirki** [comment]
@Lehcar I think your PR looks good! I added a comment as well 👍

**Comment by D1M1TR10S** [comment]
**Top priority:**
Dealing with the metadata JSON file. Inserting it into the Airtable, or creating a metadata file from Airtable.

Should be in the Airtable before they merge the PR. It needs to be in their fork. The data needs to be in Airtable in order to test the model.

/approve will drop the metadata file in with the template.
Workflow: Look at metadata file created a populate Airtable with it's info.

- Users wouldn't be able to access secrets from forks.
- Allow for fetching as long as there's a metadata file in the repo. At fetch they're just getting the Model ID.

When does it get added to Airtable? => Ersilia does the PR.


Given a repo folder, if there's a metadata JSON file there => perform the fetch pipeline. No need to query Airtable.

No need to check for duplicates. Each model has a unique ID.

Metadata file raising an error if there's not enough information. The PR will only go through if the information there is acceptable.

How to get metadata files for repos before approval workflow? Python script to commit metadata files to every single repo. It's not urgently needed but nice to have.

Is there a way to guide users to write good README files? (Converting JSON to markdown) => Jinja template engine (Python) or Numchucks (JS) can populate variables with keys read from a metadata.json file when the repo is first initialized. (Nice to have but not a must.)

Next steps:
- [ ] Populating those metadata.JSON files in the approval workflows @GrantBirki

**Comment by GrantBirki** [comment]
> Populating those metadata.JSON files in the approval workflows

Now done in https://github.com/ersilia-os/ersilia/pull/541

> Write a script to check metadata upon submits

If the metadata from the issue template is not valid, our script will fail to parse it into JSON with the basic JSON Python library

**Comment by GemmaTuron** [comment]
We have [removed](https://github.com/ersilia-os/ersilia/commit/d2f3bbe1ae2e8a068070207428e6e5a4ad1d24a0) the requirement for the airtable record to be there - now models can be fetched from repo if they have a metadata.json file only.

**Comment by GemmaTuron** [comment]
This is done thanks to:
https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model-pr.yml
https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model.yml
