### ISSUE TITLE
[Batch] Managing Dependencies

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#284]
To manage the dependencies of the packages in the Ersilia Repository. 

- [x] #300
- [x] #299

**Comment by honeyankit** [comment]
Enable Dependabot security and version updates.

Supporting Docs:
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

**Comment by GrantBirki** [comment]
I recently made a GitHub Action that combines multiple dependabot PRs into a single one for ease of dependency management. You may find this useful @honeyankit https://github.com/github/combine-prs

**Comment by honeyankit** [comment]
This task is complete.
