### ISSUE TITLE
[Batch] Automate Posts to Twitter

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#286]

**Comment by sayantani11** [comment]
Hi @GemmaTuron @miquelduranfrigola I was trying to work on this!? But there are few things I would like to know:
1. Where will the twitter post fetch content from?
2. Do you want to automate in a way that there will be tweet at a particular interval?
Just wanted to be more clear before I can proceed. Also are we looking for a github action or a python program?

**Comment by miquelduranfrigola** [comment]
Hi people - I am closing this issue since this has evolved in a another much more interesting direction - basically, every time a model is incorporated, we will announce it in slack and open a testing issue.
