### ISSUE TITLE
[Spike] Explore options for the new model submission flow

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#288]

**Comment by GrantBirki** [comment]
## Model Submission Flow: Issues + GitHub Actions

This is a purposed solution for this spike to allow all users (internal or external to @ersilia-os) to be able submit new models with ease.

### Goal ⭐ 

@ersilia-os needs a streamlined way for users to submit model requests and when approved, have a shiny new repository made for their model based on the [eos-template](https://github.com/ersilia-os/eos-template) repo.

### Workflow

This section will walk through the purposed workflow

1. A user opens a GitHub issue using an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). The issue template contains boxes for users to respond to questions that are required. Example questions and responses we can gather from the issue template:
    - Model Name: *My super cool molecule*
    - Repo Name (ensure it is unique): `ersilia-os/<answer>`
    - Model Description: *Lots of details here...*
    - License: *MIT*
    - etc...
2. An organization member of @ersilia-os reviews the issue upon its submission. At this point, the org member would discuss and gather feedback from the community member around the model.
3. Once all looks good, the org member runs the `/approve` command on the issue. This command is only available to org members and official "approves" the request to create the new model submission. Code will be configured in the `ersilia-os/ersilia` repository to run a [slash command dispatch](https://github.com/marketplace/actions/slash-command-dispatch) Action when an org member comments `/approve`. This Action will do the following:
    - Pull the user submitted answers from the issue template they filled out (repo name, description, model name, etc)
    - Create a new repository using the [eos-template](https://github.com/ersilia-os/eos-template) repo by calling the GitHub CLI tool (all in the same Actions workflow). The GitHub CLI tool has confirmed support for [template repository setup](https://cli.github.com/manual/gh_repo_create)
    - The user submitted answers are added to the repo template after it has been initialized
4. 🎉 We have now gone from a user requesting a new model from an issue, to the repo being created!

**Comment by miquelduranfrigola** [comment]
Hi @GrantBirki I think this is fantastic. I need to be 100% sure I have you covered on the eos-template side of things. What is the best way for ersilia to offer "support" for template repository setup?

**Comment by GrantBirki** [comment]
@miquelduranfrigola I think as far as the template goes, it will really just be a "fill in the blanks" situation. We make the issue template have fields which will populate the main `README.md` of the repo we create with the "template repo".

For example, the area's in red will be filled in using the data provided in the issue template.
![image](https://user-images.githubusercontent.com/23362539/193626739-a463d005-e020-47d0-9621-aeab82630d35.png)

> If a section is left blank in the issue template, then it will also be left blank when the new model repo is created from the repo template

**Comment by GrantBirki** [comment]
I think there should just be a really good "contract" between the issue template and the repo template. If we are asking user's to fill out a question in the "issue" then that data should correspond to a section in the README of the template repo we create for them.

**Comment by GrantBirki** [comment]
I found an Action's workflow have been testing it out in my sandbox which will parse and issue template response. This will allow us to funnel that JSON output into a subsequent Action step that we can use to populate our template repository which we will create in the same Actions workflow.

I found a potential bug in the 3rd party Action and opened an issue which is linked above this comment

**Comment by miquelduranfrigola** [comment]
Hi @GrantBirki - all of this is great. I really like the idea of linking the form to the README.

I am now writing a script to generate model identifiers randomly, so users do not have to decide by themselves.

**Comment by miquelduranfrigola** [comment]
Hi @GrantBirki!
The following script generates eos identifiers:
`python .github/scripts/generate_eos_identifier.py`
I hope this is helpful!

**Comment by GrantBirki** [comment]
@miquelduranfrigola I am just now seeing your comment about the eos id script. I'll make sure that this gets baked into our workflows at some point, thanks! ⭐

**Comment by GrantBirki** [comment]
We explored the options, and we built the thing! Closing 🎉
