### ISSUE TITLE
Add folder /documentation - Outreachy Applicants

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#29]
Hello,

Could you create an empty folder in the ersilia project with the name /documentation ?
This issue is great if you are a beginner who wants to test how the git fork, branch, and pull requests work. I recommend reading this  "[tutorial](https://blog.openreplay.com/getting-started-with-open-source-how-to-contribute)" first
Please note this issue will only be assigned to one applicant, ping me here if you want to contribute to this.

**Comment by victorabba** [comment]
I would love to contribute to this issue.

**Comment by GemmaTuron** [comment]
> I would love to contribute to this issue.

Hi @victorabba you are already tagged in a number of issues and assigned to issues #23 and #27, I will give time to other applicants to express their interest as well, please continue working on the open issues you are assigned to

**Comment by Rufaida98** [comment]
Hi I would love to contribute to this issue

**Comment by Rufaida98** [comment]
Hi @GemmaTuron I would love to contribute

**Comment by GemmaTuron** [comment]
> Hi @GemmaTuron I would love to contribute

Hello @Rufaida98 I have assigned this issue to you, thanks!

**Comment by Rufaida98** [comment]
Thank you @GemmaTuron . I will try my best!!

**Comment by Shivani-Parihar99** [comment]
Hi @GemmaTuron, I just summitted the pull request for this issue. When I started working on this issue I did not realized that you assigned it to @Rufaida98. Please review my pull request and please guide me if I have to make any further changes.

**Comment by GemmaTuron** [comment]
Hello @Shivani-Parihar99,
 
Thanks for your contribution. In order to make the most for each applicant we have to respect the assignation procedure. There are tasks that can be tackled by multiple contributors and others that will be assigned to a specific one. This is the reason I haven't merged you pull request, I hope you understand we need to follow the assignment order otherwise applicants will keep working on top of each other's work.
@Rufaida98 please if you are still willing to work in this task let me know else I will reassign it to @Shivani-Parihar99.

**Comment by Rufaida98** [comment]
yes i am working in it as its great opportunity to learn @GemmaTuron .Thank you so much

**Comment by Rufaida98** [comment]
@GemmaTuron sorry to bother but when i try git commit it says to me author identity unknown

**Comment by Rufaida98** [comment]
![Capture git add](https://user-images.githubusercontent.com/92082003/160354994-28c3f409-75ed-41c6-a1f9-79e1f6fec0e4.PNG)
![Capture git add](https://user-images.githubusercontent.com/92082003/160355026-90ba4a6c-2fb9-4566-8e6d-d0d6edc9ea82.PNG)

**Comment by Rufaida98** [comment]
![capture gitcommit](https://user-images.githubusercontent.com/92082003/160355233-e0e51b6d-34c0-4b54-ab33-40f31f1fcba0.PNG)
![Capture git add](https://user-images.githubusercontent.com/92082003/160355253-e3021c22-92d5-4010-a1b7-b19465d3c16c.PNG)

**Comment by Rufaida98** [comment]
Dear @GemmaTuron please check if their an issue with the issue#29

**Comment by Jaya3112** [comment]
Hi @GemmaTuron I would love to contribute

**Comment by ashaby4000** [comment]
Hi @GemmaTuron This issue is closed but I can't find the documentation folder. I will like to fix this issue if you can reassign it

**Comment by Rufaida98** [comment]
@ashaby4000 i am sorry i accidentally add a file because i forgot"/". i pulled another request to put the folder.Thank you for your observation
