### ISSUE TITLE
How to contribute to Outreachy's internship application

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#293]
Hello all,

I am opening this issue to help guide Outreachy internship applicants in their process:

- Join the [Slack workspace](https://join.slack.com/t/ersilia-outreachy/shared_invite/zt-1h2u8vbxh-fkyxlOJE20Bx538hQvpC~A) to stay up to date with all announcements.
- READ the [Contribution Guide](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023), your mentors have prepared a step by step guide on how to proceed.
- DO NOT wait for "good-first-issues" to appear, we will be working collaboratively and opening issues as we need, while we test models from the Hub and try to incorporate new models. 
- If you can, attend the Open Call on Wednesday 12th October at 17:00 CET/SAST (15:00 UTC). Details are on Slack.

**Comment by donaldte** [comment]
Thanks Mentor @GemmaTuron for the guideline.  I'm Tedom Donald an Outreachy applicant I'm happy to be a future contributor of this special project base on AI/ML.

**Comment by ananthavaibhavi** [comment]
Hi @GemmaTuron, thanks for providing this guide. It's a pleasure to learn about ersilia and its contributions towards medical science. I am Vaibhavi an Outreachy applicant and would love to contribute to the cause.

**Comment by ting96haha** [comment]
Hi @GemmaTuron, thanks for the guide. May you assign me to test some models to contribute to the project? Many thanks

**Comment by ting96haha** [comment]
> Hi @ting96haha I think I did on Slack but please can you confirm? I am at a loss with the different github handles and slack names ;)

Yes, you had assigned tasks for me. Thank you very much.

**Comment by cynthiarichard007** [comment]
Hi @GemmaTuron i still having issues installing ersilia after doing everything necessary

**Comment by GemmaTuron** [comment]
Hi @cynthiarichard007 
I am sorry to hear that but without more information I am unable to help.

**Comment by cynthiarichard007** [comment]
Hi @GemmaTuron 
I think I'm done installing ersilia after so many trials but I never give up...... I will be greatful if you assign me a tasks to do, I don't mind making a few contributions before the deadline and I will appreciate it if you give be the privilege to make a contribution as well.
![Uploading 16664409848299099889627393715718.jpg…]()

**Comment by GemmaTuron** [comment]
I'll close this issue as the contribution period is finished
