### ISSUE TITLE
🐛 Bug: Requests.exceptions.ConnectionError for Model eos1579

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#294]
### Describe the bug.
raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

This is the error raised while trying to fetch Model eos1579(Metabokiller)

### Describe the steps to reproduce the behavior

ersilia -v fetch eos1579

### Expected behavior.

Fetch the model successfully

### Screenshots.

![eos1579](https://user-images.githubusercontent.com/46167222/195062569-e5030826-baac-43c7-a7e9-65e09f397917.JPG)

### Operating environment

Ubuntu 22.04.1

**Comment by GemmaTuron** [comment]
Hello @Malikbadmus  can you run the  command in verbose mode to get more information?

`ersilia - v fetch ...`

**Comment by Malikbadmus** [comment]
> Hello @Malikbadmus can you run the command in verbose mode to get more information?
> 
> `ersilia - v fetch ...`

Okay, I'll do that

**Comment by Malikbadmus** [comment]
Hello @GemmaTuron i have run the command in verbose mode and displayed the information.

**Comment by GemmaTuron** [comment]
mmm looks like an internet error (connection disconnected), I tested in my system and the fetch worked.
Can you do the test with a small model I just suggested in this issue #308 ?

**Comment by GemmaTuron** [comment]
Hi,

I am closing this issue as the models assigned to @Malikbadmus to test are:
eos8451
eos157v
eos85a3
eos6o0z
