### ISSUE TITLE
🐛 Bug: EmptyOutputError for Model eos157v

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#295]
### Describe the bug.

Model API eos157v: predict did not produce an output.

The above is the error message gotten while trying to fetch eos157v.

Commands were run in verbose mode(-v in the CLI)

### Describe the steps to reproduce the behavior

ersilia -v fetch eos157v

### Expected behavior.

Fetch the model successfully

### Operating environment

Ubuntu 22.04.1

**Comment by GemmaTuron** [comment]
Hi  @Malikbadmus ! Thanks, if you can paste the whole error log that will be helpful!
I am also linking here @Amna-28 , I think you incorporated this model, any issues we should we aware of?
Thanks both!

**Comment by risper25** [comment]
Hello , @GemmaTuron  and @Malikbadmus ,Am also getting the same error on model eos2r5a.

**Comment by Malikbadmus** [comment]
Hi, @risper25  can you fetch the model again, I've been able to successfully run the model.
@GemmaTuron,  I ran through the whole model again and it was successful this time around, I have dropped the output file into the shared folder.

**Comment by GemmaTuron** [comment]
thanks @Malikbadmus for the update!
I alos wanted to check that you have GitLFS installed as the error at this moment is not very informative #277

**Comment by Amna-28** [comment]
> Hi @Malikbadmus ! Thanks, if you can paste the whole error log that will be helpful! I am also linking here @Amna-28 , I think you incorporated this model, any issues we should we aware of? Thanks both!

Hi @GemmaTuron , Thanks for letting me know. It was happening because of issue #292 which has been resolved. Reinstalling Ersilia will fix this problem

**Comment by risper25** [comment]
Thanks, @Malikbadmus  and @GemmaTuron, I have the GitFS installed, I tried to fetch the model but while fetching I encouter this error **TypeError: expected str, bytes, or os.PathLike object, not NoneType**  #297.

**Comment by GemmaTuron** [comment]
Hi @risper25 

Can you:
- Try eos3b5e
- Use the -v mode and paste the whole error

**Comment by risper25** [comment]
hi @GemmaTuron, I reinstalled my docker and managed to fetch the model.
 Thanks...

**Comment by GemmaTuron** [comment]
Fantastic, thanks @risper25 
I'll close this issue then
