### ISSUE TITLE
🐛 Bug:  RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/ersilia#296]
### Describe the bug.

Hi, 

I'm unable to install the Ersilia python package. I tried running the command below twice
`git clone https://github.com/ersilia-os/ersilia.git`

The resulting error showed

> error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
error: 2427 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Describe the steps to reproduce the behavior

- Create a conda enviroment in your terminal
- Make sure you have git installed
- Activate the conda environment
- try installing the Ersillia python package using `git clone https://github.com/ersilia-os/ersilia.git`

### Expected behavior.

To create an Ersillia folder in my local machine

### Screenshots.

![image](https://user-images.githubusercontent.com/54579707/194959840-a979ffac-249c-4cfc-bb13-98276c22fe0f.png)

### Operating environment

Windows 11 (running on anaconda prompt)

**Comment by Zainab-ik** [comment]
### Solution
The Ersilia folder happens to have a large size and the default git config buffer size is not sufficient to handle it.
therefore, the post-buffer size needs to be increased and can be done using 
`git config --global http.postBuffer 524288000`

Thereafter, you can clone the repository again with `git clone https://github.com/ersilia-os/ersilia.git`

### Screenshot result
![image](https://user-images.githubusercontent.com/54579707/194963660-807d37de-db0b-48b1-b855-d9a337001bb1.png)

Thanks.

Let me know if there are alternate solutions.
Thanks

**Comment by GemmaTuron** [comment]
Thanks @Zainab-ik ! 
We hadn't encountered this issue before but it's useful to know. One question, are you running Ersilia simply on the anaconda distribution for windows?

**Comment by Zainab-ik** [comment]
@GemmaTuron  I think I'm running it on anaconda distribution for windows.
I'd like to ask if I need to download all the packages I have on windows on my WSL ubuntu too or linux to be able to run the command or I can just do them on the anaconda prompt?
Thanks

**Comment by GemmaTuron** [comment]
You need to go to your WSL and install anaconda or miniconda there, and then clone ersilia's repository and install it. You do not need any other packages beforehand aside from Conda in the WSL.

**Comment by Zainab-ik** [comment]
Alright, I'd do that from my WSL

**Comment by Zainab-ik** [comment]
I did this on my WSL and it worked although it was slow. I guess the error is due to ersillia incompatibility with windows.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik , indeed Ersilia cannot run in windows, which is a limitation but we do not have the capacity currently to implement compatibility, we rather redirect people to WSL or Google Colab.
I will close the issue since this is solved
