### ISSUE TITLE
🐛 Bug: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/ersilia#297]
### Problem

After installing the Ersilia python package, I tried to check that the CLI work on my terminal by checking the Ersilia CLI options and model catalogue using the
 

 see ersilia CLI options

> ersilia --help

see ersilia's model catalog

> ersilia catalog

### Describe the steps to reproduce the behavior

- Install Ersilia python package
- Check that the CLI works on your terminal

### Expected behavior.

The code is suppose to show me the available commands in Ersilia and the corresponding model catalogue.

### Error message 
`ersilia --help`
![image](https://user-images.githubusercontent.com/54579707/194966214-cf939c1d-88ad-42df-8e6e-57e9e026b6fc.png)

`ersilia catalog`
![image](https://user-images.githubusercontent.com/54579707/194966364-ae728705-8c73-4914-852f-150fc10c48eb.png)

### Operating environment

Windows 11

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik can you also share which operating environment are you using? The Hub works on UNIX systems, so windows users need a virtual machine or WSL

**Comment by ZakiaYahya** [comment]
@Zainab-ik how you resolved this error "TypeError: expected str, bytes or os.PathLike object, not NoneType"? i'm getting the same error when fetching the ersilia model using fetch command.

**Comment by Zainab-ik** [comment]
@GemmaTuron I have both vagrant virtual machine and Ubuntu on my system. However, I run the installation commands and instructions on my anaconda prompt. 
Do I go over all the installation instructions again on my ubuntu?

**Comment by Zainab-ik** [comment]
@ZakiaYahya I'm yet to resolve it, can you share what operating system you used also.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik, 

Yes, you need to install Ersilia on your Ubuntu subsystem. I also work on Windows and what is best for me is the combination of Windows Susbsytem Linux + Visual Studio Code to access it. Let me know when you try if it works!

@ZakiaYahya also can you share which system are you working on?

**Comment by ZakiaYahya** [comment]
@GemmaTuron  and @Zainab-ik i'm working on ubuntu 18.04 tweminal installed on WSL.

**Comment by Zainab-ik** [comment]
I have both WSL and VS code, I'd integrate both and give feedback.
Thank you @GemmaTuron

**Comment by GemmaTuron** [comment]
Thanks  @Zainab-ik, let me know if it works in the WSL ;)

**Comment by muskansawa** [comment]
I am getting a similar error in mac as well , sharing the whole error in a new issue

**Comment by risper25** [comment]
I am getting also this error in mac too

**Comment by ikeadeoyin** [comment]
I am getting this error message as well.

**Comment by tarikkaoutar** [comment]
@GemmaTuron kindly i have the same error how you solved this problem thanks
