### ISSUE TITLE
Model request

### ISSUE THREAD

**Issue by victorabba** [ersilia-os/ersilia#30]
Ersilia accepts the incorporation of third-party models and would not mind suggestions.

Model title
Suggest a title for your model. For example, 'Antimicrobial activity prediction'

Model features
Describe the features of the model. For example, "The Antimicrobial activit prediction model predicts antimicrobial activity in a specimen."

Use Case
Give a brief tutorial of how the model is used. Screenshots and/or videos can be included.

Benefit: What benefit can the model offer in the field of science?

Publication
Is there a link to a publication? (DOI, PMID, URL). If yes, include the link.

Code
Is code available? If so, please provide link to repository (GitHub, GitLab, BitBucket).

License
Please include a license for the model.

**Comment by GemmaTuron** [comment]
Hello @victorabba, 
please comment on the same issue instead of opening a new one to make it easier to follow. Can you add this to issue #23 and explain what is missing and why have you added it?
thank you!
