### ISSUE TITLE
Manage Security Dependency

### ISSUE THREAD

**Issue by honeyankit** [ersilia-os/ersilia#300]
Follow the steps to enable the Dependabot security updates:
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by honeyankit** [comment]
@miquelduranfrigola @GemmaTuron: I do not have [permission](https://github.com/ersilia-os/ersilia/pulse) to enable the security update on this repo. There is just on button click to enable it. Please follow this guide and enable dependabot security update.

**Comment by GemmaTuron** [comment]
Hi @honeyankit 
Are you referring to this:
Dependabot security updates
Allow Dependabot to open pull requests automatically to resolve Dependabot alerts.
It appears Enabled on settings for this repo, the change I have done is adding you as security manager so it should work now!

**Comment by honeyankit** [comment]
@GemmaTuron : I do not see any `settings` section 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/5500812/195413906-e6676dab-3e42-46e9-b3cb-c3b41684956a.png">


**This is what it should look like:**
<img width="759" alt="image" src="https://user-images.githubusercontent.com/5500812/195413188-239f6c39-2fc8-47c4-a1c0-35cecb2f3b11.png">

**Comment by GemmaTuron** [comment]
@honeyankit let's have a look together in the meeting
