### ISSUE TITLE
🐛 Bug:  ERROR: Command errored out with exit status 1:  error: command 'gcc' failed: No such file or directory

### ISSUE THREAD

**Issue by Hauwarh** [ersilia-os/ersilia#309]
### Describe the bug.

I'm unable to install the Ersilia python package, after using this commands 
`git clone https://github.com/ersilia-os/ersilia.git`
`cd ersilia`
`pip install -e .`
I got this errors

![image](https://user-images.githubusercontent.com/101065854/195181197-465006bf-1a8e-4449-a04e-ac250a20005e.png)

![image](https://user-images.githubusercontent.com/101065854/195181591-2572add1-f8b4-4222-8d61-46416ea9fd7f.png)

### Describe the steps to reproduce the behavior

- create a conda environment
- clone from github
- install with `pip install -e .`

### Expected behavior.

To install the Ersilia tool

### Operating environment

WSL Ubuntu 22,04 LTS

**Comment by Hauwarh** [comment]
Looking through the issue again, I realized I didnt activate ersilia's conda environment 😅
I activated it using `conda activate ersilia` and tried installed installing it. It started installing but threw some errors again
![image](https://user-images.githubusercontent.com/101065854/195184364-5f94a103-70d0-4ff5-accc-2a7e3ccb7fe9.png)
![image](https://user-images.githubusercontent.com/101065854/195184614-c27ad785-3c53-4073-a8e2-5d20a2e9cdac.png)

**Comment by alaminumar** [comment]
``i think you skipped a `step`
```
# create a conda environment
conda create -n ersilia python=3.7
# activate the environment
conda activate ersilia.

but it seems you've realized that.

As for your second issue. I also had the same problem, I retried a second time and it worked

**Comment by Hauwarh** [comment]
Yes I was able to run it again.
Thank you.
