### ISSUE TITLE
🐛 Bug: ersilia --help producing traceback error instead of the expected output

### ISSUE THREAD

**Issue by EstherIdabor** [ersilia-os/ersilia#312]
### Describe the bug.

installing the Ersilia python package and running pip install -e happened fine without producing any error, however running the ersilia --help to see the CLI options produce the error below:

Traceback (most recent call last):                                                                                                                                        
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master                                                                               ws.require(__requires__)                                                                                                                                              

File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require                                                                                     needed = self.resolve(parse_requirements(requirements))  
                                                                                                             
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve                                                                                     raise VersionConflict(dist, req).with_context(dependent_req)                                                                                                        pkg_resources.ContextualVersionConflict: (urllib3 1.25.8 (/usr/lib/python3/dist-packages), Requirement.parse('urllib3>=1.26.0'), {'docker'})

 
![Screenshot (103)](https://user-images.githubusercontent.com/70244748/195243221-6da5d49b-52e1-4fe5-b597-4791d631169a.png)

### Describe the steps to reproduce the behavior

ersilia --help

### Expected behavior.

output the CLI options without any traceback errors

### Operating environment

windows 10,  WSL Ubuntu 20.04.4 LTS

**Comment by EstherIdabor** [comment]
Hi @GemmaTuron, Please I am stuck here, and would glad to use some help

**Comment by GemmaTuron** [comment]
Hi @EstherIdabor 
This is just the test I was asking in #313 .
It seems an installation issue, can you paste here the commands you followed to install Ersilia?

**Comment by GemmaTuron** [comment]
I'd suggest:

1. Make sure you are on WSL or a UNIX system with conda and git-lfs installed
2. Updating pip (@Zainab-ik can have more insight on this)
3. Deleting the conda environment and creating it anew
4. Cloning Ersilia's repository again
5. Run the `pip install -e .`

**Comment by EstherIdabor** [comment]
Hi @GemmaTuron I've been on it all day trying to figure out what could be wrong, the installation up to that point went on fine, and I followed every single instructions on the ersillia book, and every was alright. However researching on the problem made me realize the pip install -e I ran lead to the install of some packages with different versions than what is required for instance it installs urllib1.25.8 and is required to parse is 1.26.0. leading to a VersionConflict error,

**Comment by EstherIdabor** [comment]
I'm on a Unix system with conda and git-lfs installed, I created a new conda and tried to clone the repo again but got an error, fatal:  destination path 'ersilia' already exists and is not an empty directory

> I'd suggest:
> 
> 1. Make sure you are on WSL or a UNIX system with conda and git-lfs installed
> 2. Updating pip (@Zainab-ik can have more insight on this)
> 3. Deleting the conda environment and creating it anew
> 4. Cloning Ersilia's repository again
> 5. Run the `pip install -e .`

I'm on a Unix system with conda and git-lfs installed, I created a new conda and tried to clone the repo again but got an error, fatal:  destination path 'ersilia' already exists and is not an empty directory

**Comment by EstherIdabor** [comment]
Hi @GemmaTuron I am now able to get past ersillia--help and ersillia catalogue, firstly I have Ubuntu 18.04 which I wasn't using before now, I was using Ubuntu 20.04.4 LTS, I switched over to 18.04 and started the whole process of installing ersillia from the beginning, ensuring I miss no step and now it's not showing me any error.

Thank you

**Comment by Zainab-ik** [comment]
@EstherIdabor , regarding the pip and getting the CLI to work on terminal. Has everything been resolved. And which version of ubuntu are using exactly, the 18.04 or 20.04.

**Comment by Zainab-ik** [comment]
> I'd suggest:
> 
> 1. Make sure you are on WSL or a UNIX system with conda and git-lfs installed
> 2. Updating pip (@Zainab-ik can have more insight on this)
> 3. Deleting the conda environment and creating it anew
> 4. Cloning Ersilia's repository again
> 5. Run the `pip install -e .`

@GemmaTuron I'd take her through

**Comment by EstherIdabor** [comment]
> @EstherIdabor , regarding the pip and getting the CLI to work on terminal. Has everything been resolved. And which version of ubuntu are using exactly, the 18.04 or 20.04.

Yes it has, I am now using 18.04, thank you

**Comment by EstherIdabor** [comment]
To anyone who will encounter this error, I suggest you reinstall Ubuntu and start all over from the beginning without missing a step, and everything should work just fine.

**Comment by Zainab-ik** [comment]
that's great @EstherIdabor

**Comment by GemmaTuron** [comment]
Fantastic, thanks @EstherIdabor and @Zainab-ik
I'll close this issue then!
