### ISSUE TITLE
🐛 Bug: Errors on testing dummy model eos3b5e

### ISSUE THREAD

**Issue by AnneO1** [ersilia-os/ersilia#323]
### Describe the bug.

I successfully installed ersilia I until encountered these errors while running the dummy model.
On `ersilia -v fetch eos3b5e` I got warnings and error: `ERROR: Could not find a version that satisfies the requirement rdkit-pypi (from versions: none)
ERROR: No matching distribution found for rdkit-pypi`'
And on continuing: `ersilia serve eos3b5e` , I get the error `TypeError: expected str, bytes or os. PathLike object, not NoneType`

### Describe the steps to reproduce the behavior

1. activate the ersilia environment
2. ersilia -v fetch eos3b5e
Error:
3. ersilia -v serve eos3b5e
Error:

### Expected behavior.

Fetch  and serve the model.

### Screenshots.

On fetch:
![ersilia -v fetch eos3b5e warningerror](https://user-images.githubusercontent.com/115647922/195404561-0fce7489-b509-4b8b-a67e-71e3d2f968cd.PNG)

On serve:
![ersilia serve eos3b5e erroroutput](https://user-images.githubusercontent.com/115647922/195404651-bd46f778-0ced-4b4b-8b35-1ea1e2007ce7.PNG)

### Operating environment

WSL Ubuntu 20.04 

### Additional context

Installed Isaura
Installed docker

**Comment by DhanshreeA** [comment]
Could you give more details about your python and pip versions?

What's happening here is tht while fetching a model, ersilia creates a new conda environment for each model it fetches and installs their required dependencies. It is possible your conda installation is working with a python/pip version that could not install the missing requirements for protobuf and bentoml.  And since this model is not successfully fetched, you cannot serve it. :(

**Comment by AnneO1** [comment]
@mamabear25 and @DhanshreeA I decided to do a fresh installation and will provide updates incase the same issue recurs.

**Comment by Zainab-ik** [comment]
@AnneO1 do you have docker installed? I'm getting a similar error, I want to install docker and try again.

**Comment by AnneO1** [comment]
@mamabear25  and @DhanshreeA, after new installation am still unable to fetch for model `eos3b5e`.
conda 22.9.0
pip 22.2.2
Python 3.7.13

**Comment by Zainab-ik** [comment]
@AnneO1 The error persists also.
@GemmaTuron Help us look through

**Comment by GemmaTuron** [comment]
Hello !

@AnneO1 can you please confirm
`ersilia --help` is working? This will let us know if there is a base problem when installing ersilia.
If that works, please, fetch the model and collect the full error log so I can understand what is going on. @Zainab-ik same for you please.

**Comment by GemmaTuron** [comment]
To collect the logs you need to add at the end of the bash command the following:

`ersilia -v fetch eos3b5e > my.log 2>&1 `

This will create a my.log file with all the information we need

**Comment by AnneO1** [comment]
@GemmaTuron My `ersilia --help` is working, see image. See attached log file after running `ersilia -v fetch eos3b5e > eos3b5e.log 2>&1`.

![help](https://user-images.githubusercontent.com/115647922/195666464-253c77ee-90a3-42ff-ae4e-55bed3b2dd84.PNG)

[eos3b5e.log](https://github.com/ersilia-os/ersilia/files/9779182/eos3b5e.log)

**Comment by Zainab-ik** [comment]
> Hello !
> 
> @AnneO1 can you please confirm `ersilia --help` is working? This will let us know if there is a base problem when installing ersilia. If that works, please, fetch the model and collect the full error log so I can understand what is going on. @Zainab-ik same for you please.

@GemmaTuron My `ersilia --help` still works also, attached is an image.
![image](https://user-images.githubusercontent.com/54579707/195687665-1762a891-8c1e-4046-b692-c3d7f179a4f6.png)
also, this is the log file of the model `eos3b5e` 
[my.log](https://github.com/ersilia-os/ersilia/files/9779878/my.log)

**Comment by Zainab-ik** [comment]
@GemmaTuron @AnneO1 I've been able to fetch the dummy model successfully, I opened a new terminal and activated the ersilia conda environment with `conda activate ersilia` and fetched it in this log file using `ersilia -v fetch eos3b5e > eos3b5e.log 2>&1`
[eos3b5e.log](https://github.com/ersilia-os/ersilia/files/9780698/eos3b5e.log)
and it fetched successfully, I proceeded to serve using `ersilia -v serve eos3b5e`. While I got the correct output here 
![image](https://user-images.githubusercontent.com/54579707/195712273-f601c334-aa84-4274-8b66-3f0b4a530586.png)
I got an error stating 
![image](https://user-images.githubusercontent.com/54579707/195712475-d867f026-ff0e-4fed-9a9c-0548c5f4b261.png)

I proceeded to calculate using ` ersilia -v api calculate -i "CCCCCC"` I got an output similar to @GemmaTuron 's 
![image](https://user-images.githubusercontent.com/54579707/195713188-79f41e32-ee72-4e0d-8c0a-3e0d547ef179.png)
and still got the Isaura error message. 
I opened the Isaura directory and did pip install once again to avoid future issues.

**Comment by Zainab-ik** [comment]
> @GemmaTuron @AnneO1 I've been able to fetch the dummy model successfully, I opened a new terminal and activated the ersilia conda environment with `conda activate ersilia` and fetched it in this log file using `ersilia -v fetch eos3b5e > eos3b5e.log 2>&1` [eos3b5e.log](https://github.com/ersilia-os/ersilia/files/9780698/eos3b5e.log) and it fetched successfully, I proceeded to serve using `ersilia -v serve eos3b5e`. While I got the correct output here ![image](https://user-images.githubusercontent.com/54579707/195712273-f601c334-aa84-4274-8b66-3f0b4a530586.png) I got an error stating ![image](https://user-images.githubusercontent.com/54579707/195712475-d867f026-ff0e-4fed-9a9c-0548c5f4b261.png)
> 
> I proceeded to calculate using ` ersilia -v api calculate -i "CCCCCC"` I got an output similar to @GemmaTuron 's ![image](https://user-images.githubusercontent.com/54579707/195713188-79f41e32-ee72-4e0d-8c0a-3e0d547ef179.png) and still got the Isaura error message. I opened the Isaura directory and did pip install once again to avoid future issues.

@AnneO1 I employ you to try it once again, refresh your system and rerun the process.

**Comment by EstherIdabor** [comment]
Hi @Zainab-ik  just to be clear, all the fetch, serve and predict or calculate is done in the ersillia directory right? and the ersillia conda environment?

**Comment by GemmaTuron** [comment]
> Hi @Zainab-ik just to be clear, all the fetch, serve and predict or calculate is done in the ersillia directory right? and the ersillia conda environment?

These are two independent things @EstherIdabor :
- > The directory you are at when running commands, which does not need to be /ersilia, but where you have your files stored (could be Desktop or a folder in Desktop)
- > The conda environment of ersilia, which needs to be active to run ersilia successfully. 

Let me give an example:
`(base) gturon@sotira:~/github/ersilia-os/ersilia$ `  # I am now in the ersilia directory, but the conda environment is not active
`(base) gturon@sotira:~/github/ersilia-os/ersilia$  conda activate ersilia`  
`(ersilia) gturon@sotira:~/github/ersilia-os/ersilia$  `   #now conda is active, but I don't have my input files in the ersilia github!
`(ersilia) gturon@sotira:~/github/ersilia-os/ersilia$  cd ` 
`(ersilia) gturon@sotira:~$  cd Desktop/test` #I navigate to the folder where my data is stored 

I will now run the commands from this directory. The Fetch and Serve can be run from any directory as long as the ersilia conda environment is active. To calculate or predict you must specify the path to your files, or easier, be in the specific folder where they are at.

**Comment by GemmaTuron** [comment]
> Hi @Zainab-ik please what did you do differently this time around? I'm still geting thesame error

Hi @EstherIdabor, can you open an issue with your specific problem and the log file? if it is already open please link it here so we can find it

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik just to be clear, all the fetch, serve and predict or calculate is done in the ersillia directory right? and the ersillia conda environment?

You do it in the Ersillia environment not the directory.
Just `conda activate ersilia` after opening your WSL and then run your model. Just make sure you have git LFS and isaura installed in the ersilia environment. 
You can check for them by doing `git-lfs --version`.

**Comment by AnneO1** [comment]
Hi @GemmaTuron, I am still stuck at this issue. I followed the instructions you gave(git-lfs installed: git-lfs/2.9.2) am just still not sure what I am missing. I even changed the network still, am unable to fetch. I have attached the log file.

[eos3b5e.log](https://github.com/ersilia-os/ersilia/files/9791754/eos3b5e.log)

**Comment by UChisom** [comment]
Hi @AnneO1 If you haven't activated your git-lfs after installing it.
 
Use the command `git-lfs install` to do so. Then refresh and try.

If that doesn't solve it, I'd suggest reinstalling Ersilia, quit the CLI, log back in, then try fetching again.

**Comment by AnneO1** [comment]
> 



> Hi @AnneO1 If you haven't activated your git-lfs after installing it.
> 
> Use the command `git-lfs install` to do so. Then refresh and try.
> 
> If that doesn't solve it, I'd suggest reinstalling Ersilia, quit the CLI, log back in, then try fetching again.
@UChisom, Thanks. Try it all, my git-lfs is initialized, still same logged output.

**Comment by GemmaTuron** [comment]
Hi @AnneO1 !

This is related to internet connection, as you have this in the log:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f93c8269650>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/rdkit-pypi/

This must be due to VPN, proxy or similar, I am sorry I cant be more helpful on this error. @Zainab-ik also experienced similar issues #352 . Let's see if we can figure it out, otherwise we will simply move to google colab

**Comment by Zainab-ik** [comment]
@AnneO1 let's try to figure it out together. I'd try to check my network settings also and change it if it's going to work.

**Comment by Zainab-ik** [comment]
@GemmaTuron we'd update you on our progress.

**Comment by carcablop** [comment]
> Hi @AnneO1 If you haven't activated your git-lfs after installing it.
> 
> Use the command `git-lfs install` to do so. Then refresh and try.
> 
> If that doesn't solve it, I'd suggest reinstalling Ersilia, quit the CLI, log back in, then try fetching again.

I agree with the solution, although in my case it worked for me using the following command and with the ersilia environment activated:
sudo apt install git-lfs

As I indicate in this bug #376 : https://github.com/ersilia-os/ersilia/issues/376

**Comment by GemmaTuron** [comment]
Thanks @carcablop !
Please can you add this useful tip to #359 ?

**Comment by AnneO1** [comment]
Hi @GemmaTuron, 
Hi Everyone, thanks so much for all the help. Finally my environment is working. After a whole week of troubleshoot, I let my system rest for a day then I did the following:
1. Settings-> Network & Internet -> Proxy -> Turned OFF(disable) automatically detect settings on Proxy Setup.
2.  Changed my network
3. Force reboot the my Linux system

Successfully tested dummy model eos3b5e.

**Comment by GemmaTuron** [comment]
I'm glad to hear this!

@Zainab-ik see the proxy setup settings disabling

**Comment by carcablop** [comment]
> Thanks @carcablop ! Please can you add this useful tip to #359 ?

Yes @GemmaTuron I'll do it.
