### ISSUE TITLE
🐛 Bug: Error on Model eos85a3

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#324]
### Describe the bug.

The model was fetched and served successfully, but an error is being raised while predicting the model.

See the below screenshot for the error log.

### Describe the steps to reproduce the behavior

ersilia -v api predict  -i input.csv  -o eos85a3.csv

### Expected behavior.

Model test run successfully

### Screenshots.

![New error](https://user-images.githubusercontent.com/46167222/195430023-58b444de-76d7-4f61-9cbe-9e7bf667d925.JPG)

### Operating environment

Ubuntu 22.04.1

**Comment by dchidindu5** [comment]
Have you tried predicting other models to see if an error is generated?

**Comment by GemmaTuron** [comment]
Hi @Malikbadmus 

I can't say much with this screenshot, I'd like to see the full error log. You can get it by adding the following snippet to your bash command `> my.log 2>&1`

so:

`ersilia -v api predict -i input.csv -o eos85a3.csv > my.log 2>&1`

**Comment by Malikbadmus** [comment]
Thank you so much @GemmaTuron and @dchidindu5, I've been able to resolve the issue.

The problem was that the input file was not in my working directory, and I didn't specify a path to the file in my command.

**Comment by DhanshreeA** [comment]
For the future: this issue is similar to issue https://github.com/ersilia-os/ersilia/issues/326 :)

**Comment by GemmaTuron** [comment]
Perfect, thanks @Malikbadmus for letting me know, I guess the explanations on issue #326 and Slack were helpful!
I'm closing this issue .
