### ISSUE TITLE
🐛 Bug: Error encountered 'ersilia -v api calculate eos3b5e'

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#327]
### Describe the bug.

Hi @GemmaTuron , I encountered a type error whilst  attempting to calculate the molecular weight of the model eos3b5e.

> TypeError: No registered converter was able to produce a C++ rvalue of type std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type NoneType

### Describe the steps to reproduce the behavior

Operating System - windows 10, Ubuntu 20.04.

Steps taken 
- [x] Install the hub
- [x] Fetch model eos3b5e
- [x] Serve model eos3b5e
- [ ] Calculate the molecular weight failed using the 'ersilia -v api calculate eos3b5e' command

### Expected behavior.

Molecular weight of the model should be calculated successfully

### Screenshots.

![error](https://user-images.githubusercontent.com/63536707/195507432-2aa2b236-132a-4b84-9690-0fe1d97dbd51.png)

### Operating environment

Ubuntu 20.04

**Comment by Malikbadmus** [comment]
Hello @pauline-banye, check your api key, most of the models make use of api 'predict'.

But from your screenshot, I can see that you're testing the dummy model @GemmaTuron assigned to us.

Your command is missing -i element, and you should replace the model name with the single molecule "CCCCC".

ersilia -v api calculate -i "CCCCCC"

**Comment by GemmaTuron** [comment]
Thanks @Malikbadmus 

Indeed @pauline-banye the problem here seems that you are not giving the input:
`ersilia -v api calculate -i "CCCCCC"`

The -i flag refers to the input (what we will calculate the molecular weight of), "CCCC" is a simple molecule of only 4 Carbons

**Comment by pauline-banye** [comment]
Thanks @Malikbadmus @GemmaTuron. Trying it out now

**Comment by DhanshreeA** [comment]
@GemmaTuron Maybe we can make the error prompts or the stack trace more intuitive for these kinds of errors? I believe this could be handled upfront in the code for parsing arguments to the `ersilia` command.

**Comment by Zainab-ik** [comment]
@pauline-banye try checking your error log if it states Isaura data lakes not installed and reinstall it in your ersilia environment. I came across a similar also.

**Comment by Zainab-ik** [comment]
> @pauline-banye try checking your error log if it states Isaura data lakes are not installed and reinstall it in your ersilia environment. I came across a similar error also while running ` ersilia -v api calculate -i "eml_canonical.csv" -o "eos3b5e.csv" > my.log 2>&1` check log here [my.log](https://github.com/ersilia-os/ersilia/files/9780854/my.log) It's yet to be resolved though. @GemmaTuron any suggestion for the error?

I've resolved the type error in the log above, realized my input_csv was named wrongly and I adjusted the file path also. Now I have `eos3b5e.csv`. 
@pauline-banye You can also try it.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik if isaura is not installed it is not a proble to run ersilia, in principle they are two independent modules and it is a "nice to have" but not a hard requirement.
@pauline-banye please provide an update if you have revised your input and output files and got a log file also.

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik if isaura is not installed it is not a proble to run ersilia, in principle they are two independent modules and it is a "nice to have" but not a hard requirement. @pauline-banye please provide an update if you have revised your input and output files and got a log file also.

Noted @GemmaTuron

**Comment by pauline-banye** [comment]
Hi everyone, please excuse my delayed response. I'm running through all your suggestions.

@GemmaTuron I was able to fetch & serve the test model successfully. Thanks for  the update. Yes I do have a log file and updates regarding the errors I've encountered. I created this [issue](https://github.com/ersilia-os/ersilia/issues/336), which includes screenshots and my.log file.

Thanks @Zainab-ik ! Yes I do have isaura data lakes installed.

**Comment by GemmaTuron** [comment]
Great @pauline-banye !

I am closing this issue as resolved then!
