### ISSUE TITLE
🐛 Bug: Error encountered 'ersilia -v api predict eos7w6n

### ISSUE THREAD

**Issue by zheeburg** [ersilia-os/ersilia#329]
### Describe the bug.

All was almost done for about 30 minutes till i got the error `.csv not found`

### Describe the steps to reproduce the behavior

ersilia -v fetch eos7w6n
ersilia -v serve eos7w6n
ersilia -v api predict -i eml_canonical  -o eos7w6n
.csv

### Screenshots.

![eos7w6n 3](https://user-images.githubusercontent.com/41709695/195520960-5d412036-f3cf-4c92-b453-a88945907406.JPG)
![eos7w6n 5](https://user-images.githubusercontent.com/41709695/195520968-e31947e8-f590-4a14-834c-743219e703d3.JPG)
![eos7w6n](https://user-images.githubusercontent.com/41709695/195520973-2afa05d4-6f2a-4b26-9113-6f15d7f514f1.JPG)
![eos7w6n 5](https://user-images.githubusercontent.com/41709695/195521510-3ce53c84-5c59-4653-bda4-eada062fb0f5.JPG)

### Operating environment

Ubuntu 20.04.1 LTS

**Comment by GemmaTuron** [comment]
Hi @zheeburg 

First let me confirm the command you run was:
`ersilia -v api predict -i eml_canonical -o eos7w6n.csv`  (as stated in the issue)

OR

`ersilia -v api predict -i eml_canonical.csv  -o eos7w6n.csv` (note the .csv in the input file)

Please double check that before we dig more into the error

**Comment by zheeburg** [comment]
Oh yes, Thanks so much Mentor
That was the mistake I made.

> Hi @zheeburg
> 
> First let me confirm the command you run was: `ersilia -v api predict -i eml_canonical -o eos7w6n.csv` (as stated in the issue)
> 
> OR
> 
> `ersilia -v api predict -i eml_canonical.csv -o eos7w6n.csv` (note the .csv in the input file)
> 
> Please double check that before we dig more into the error
