### ISSUE TITLE
🐛 Bug: IndexError encountered 'ersilia -v api predict -i "eml_canonical.csv" -o "eos8d8a.csv" > my.log 2>&1'

### ISSUE THREAD

**Issue by ICEY57** [ersilia-os/ersilia#330]
### Describe the bug.

When I tried to ran the model 'eos8d8a' to predict, the 'fetch', 'card', 'serve' commands ran correctly, but an error occurred at the API 'predict' command.
Here is the error log file.
[my.log](https://github.com/ersilia-os/ersilia/files/9775955/my.log)

### Expected behavior.

It should have created a new csv file named 'eos8d8a.csv', but in fact the terminal reminded an IndexError:list index out of range.

### Screenshots.

![image](https://user-images.githubusercontent.com/51103860/195579158-37ccc5ac-8338-444a-9357-6eeab5f1ad87.png)

### Operating environment

Ubuntu-22.04.1

**Comment by GemmaTuron** [comment]
Hi @ICEY57 

Quick question: did you specify python 3.7 when creating ersilia's conda environment? I see in your commands python 3.9

**Comment by UChisom** [comment]
Hi @GemmaTuron , I'm curious.

Is Ersilia only compatible with Python 3.7 for now?

Referring to the installation guide in the Gitbook, pre requisite 2: python and conda states that: __We have tested our tools on Python 3.7 and above__

_I used version 3.7 though_

**Comment by Femme-js** [comment]
@UChisom you can try recreating the conda environment with Python 3.7 version, if you hadn't done this before. 

>> conda create -n ersilia python=3.7

**Comment by UChisom** [comment]
@Femme-js  mine works fine, thanks.

I'm asking for curiousity :)

**Comment by ICEY57** [comment]
Problems solved. It seems that recreate the python 3.7 version environment helps. @GemmaTuron @Femme-js thanks for help

**Comment by ICEY57** [comment]
I guess maybe Ersilia only compatible with Python 3.7 for now @UChisom
