### ISSUE TITLE
🐛 Bug:  calculate api exits without any output

### ISSUE THREAD

**Issue by mamabear25** [ersilia-os/ersilia#332]
### calculate api exits without any output

running the calculate api doesn’t output anything, it just exits.

### Describe the steps to reproduce the behavior

1. ersilia fetch -v eos8a4x
2. ersilia -v serve eos8a4x
3. ersilia -v calculate -i "eml_canonical.csv" -o "eos8a4x" > my.log 2>&1

### Screenshots.

<img width="1440" alt="Screenshot 2022-10-13 at 12 09 44" src="https://user-images.githubusercontent.com/102018576/195581462-836cc34a-1d87-495a-a759-5b08c0561f59.png">

### Operating environment

macOs Monterey Version 12.5.1

**Comment by Zainab-ik** [comment]
Hi @mamabear25, I think you didn't add .csv at the end of your output doc. 
should be ersilia -v calculate -i "eml_canonical.csv" -o "eos8a4x.csv" > my.log 2>&1. You should probably try this

**Comment by Zainab-ik** [comment]
> ### Describe the bug.
> ### calculate api exits without any output
> running the calculate api doesn’t output anything, it just exits.
> 
> ### Describe the steps to reproduce the behavior
> 1. ersilia fetch -v eos8a4x
> 2. ersilia -v serve eos8a4x
> 3. ersilia -v calculate -i "eml_canonical.csv" -o "eos8a4x" > my.log 2>&1
> 
> ### Expected behavior.
> #### calculated outputs should be saved or printed to the screen
> ### Screenshots.
> <img alt="Screenshot 2022-10-13 at 12 09 44" width="1440" src="https://user-images.githubusercontent.com/102018576/195581462-836cc34a-1d87-495a-a759-5b08c0561f59.png">
> 
> ### Operating environment
> macOs Monterey Version 12.5.1
> 
> ### Additional context
> _No response_

also include your error file

**Comment by mamabear25** [comment]
it's now working @Zainab-ik

**Comment by mamabear25** [comment]
it's not working @Zainab-ik

**Comment by GemmaTuron** [comment]
Hi @mamabear25 
I think you are missing the api command?

ersilia -v api calculate ...

**Comment by GemmaTuron** [comment]
can you attach the log of this last run?

**Comment by GemmaTuron** [comment]
and @mamabear25 I still miss the .csv on the output file.. so you are not creating any file actually. Hope this helps!

**Comment by mamabear25** [comment]
@GemmaTuron I've fixed the issue... 
I removed the quotes around the csv file, and ran it this way

`ersilia -v api calculate -i eml_canonical.csv -o "eos8a4x.csv"
`
