### ISSUE TITLE
Ersilia Installation documentation omission

### ISSUE THREAD

**Issue by Motunrayo321** [ersilia-os/ersilia#333]
Hello @GemmaTuron, after installing and testing Ersilia, I observed a few omissions in the commands for testing the 'eos3b5e' model on the site.

Command: ersilia serve
Correct command: ersilia serve 'eos3b5e'

Command: ersilia -v api calculate eos3b5e
Correct command: ersilia -v api calculate -i "CCCCCC"

Running the stated commands lead to an error message stating the usage.

![Outreachy Winter 2023 - Ersilia Book - Google Chrome 10_13_2022 9_45_33 PM (2)](https://user-images.githubusercontent.com/104320678/195711201-6f10f1a6-3b63-4670-aa0d-275c968cc68c.png)

**Comment by GemmaTuron** [comment]
Thanks @Motunrayo321 

This is now changed in the docs.

**Comment by Motunrayo321** [comment]
Thank you very much @GemmaTuron.

**Comment by Motunrayo321** [comment]
Hello, since this issue has been solved, do I still need to include it in issue 359?

**Comment by GemmaTuron** [comment]
No, that's fine @Motunrayo321 ! Thanks
