### ISSUE TITLE
🐛 Bug: Google Colab: JSONDecodeError when Fetching Models

### ISSUE THREAD

**Issue by ZakiaYahya** [ersilia-os/ersilia#335]
### Describe the bug.

Hi @GemmaTuron, Fetching ersilia models in google colab fails giving ModuleNotFoundError: No module named 'google.protobuf' error. Somehow i solved that issue by by running this command pip install protobuf==3.20.1. But now it's another error while fetching giving json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0).
Here's my colab link for access: 
https://colab.research.google.com/drive/1MylbYTz1-ZZAYcqWJvPxyfqbcT8AUN3t?usp=sharing

Error Screenshot:
![colab_error](https://user-images.githubusercontent.com/54974236/195796284-75775950-9cbf-4116-b98b-80b8830d05da.png)

### Operating environment

Google Colab

**Comment by Malikbadmus** [comment]
Hello @ZakiaYahya , I was able to solve this error by using  `import csv` , since I figured that JSON decoders are being ran against a csv file.

But now I'm generating another error while fetching .

raise Exception("{0} environment does not exist".format(environment))

**Comment by ZakiaYahya** [comment]
@Malikbadmus, oh right. where have you been use "import csv"?

**Comment by Malikbadmus** [comment]
@ZakiaYahya , before the fetch command.

**Comment by ZakiaYahya** [comment]
@Malikbadmus i have tried it by  import csv before fetching but still got the same JSONDecodeError

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya !

The error was on the google protobuf package, which clashed with ersilia's requirements of protobuf = 3.19
We think we solved this, so you can re -test and let me know if we can close this issue!

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron.
Yes the problem is resolved, it is not giving protobuf or JSONDecodeError anymore, and the model is fetched successfully.
