### ISSUE TITLE
🐛 Bug: Error while fetching models eos157v & eos8451

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#336]
### Describe the bug.

Good day @GemmaTuron , I have experienced more issues while fetching models with the fetch command

`ersilia -v fetch eos157v`
`ersilia -v fetch eos8451`

[my.log](https://github.com/ersilia-os/ersilia/files/9784675/my.log)

I encountered multiple package conflicts during this process
![package conflicts](https://user-images.githubusercontent.com/63536707/195818107-f53cdef3-708e-4f08-b5c3-562fee89cd8d.png)

### Describe the steps to reproduce the behavior

To replicate the error:

- activate ersilia environment
- `ersilia -v fetch eos157v`

### Expected behavior.

Models are fetched successfully

### Screenshots.

![fetch-error](https://user-images.githubusercontent.com/63536707/195816125-c0e3ff48-1c4f-4d25-8e48-4e06208cf456.png)

![no fetch](https://user-images.githubusercontent.com/63536707/195816139-0eb68a36-00ee-4c62-b9dd-44a9619dc085.png)

### Operating environment

Ubuntu 20.04

**Comment by pauline-banye** [comment]
I was going through the thread on the slack workspace and it was suggested that ersilia be reinstalled. Trying that fix now

**Comment by GemmaTuron** [comment]
@pauline-banye 
Sorry I haven't been able to get to this yet, finish the other models assigned to you and then move to colab while I try to see what happened!
