### ISSUE TITLE
🐛 Bug: ersilia -v fetch eos3b5e returns TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by EstherIdabor** [ersilia-os/ersilia#337]
### Describe the bug.

@GemmaTuron 
i am unable to fetch the dummy model eos3b5e and hence test the model as ersilia -v fetch eos3b5e is throwing a typeError as well as other addition error contained in
[error.log](https://github.com/ersilia-os/ersilia/files/9787385/error.log)

### Describe the steps to reproduce the behavior

I ensured I ran ersilia --help to make sure ersilia is installed and there is no error of installation. i also ran git-lfs --version to ensure git LFS is installed
and then ran :
ersilia -v fetch eos3b5e > error.log 2>&1

### Expected behavior.

To fetch the model eos3b5e without errors

### Screenshots.
A screensshot of the error below
![Screenshot (111)](https://user-images.githubusercontent.com/70244748/196060633-cc329182-c6eb-47e0-87c1-e24375472f18.png)

_No response_

### Operating environment

Ubuntu 18.04.5

### Additional context

ersilia --help 
ersilia catalog  
are both working fine
![Screenshot (108)](https://user-images.githubusercontent.com/70244748/195875900-29d8b592-8e9a-4431-a81a-e39122e363d1.png)

**Comment by EstherIdabor** [comment]
Hi @GemmaTuron this is the issue and I have been on it yet still thesame output

**Comment by Malikbadmus** [comment]
Hello @EstherIdabor, use this command `conda activate ersilia`  to activate conda and then proceed with your fetch command.

**Comment by EstherIdabor** [comment]
Hi @Malikbadmus thanks for the response, I did that, the log shows the result of the fetch which is a typeerror

**Comment by GemmaTuron** [comment]
Hello @EstherIdabor !

You are facing the same issues as @Zainab-ik and @AnneO1, it is not related to Ersilia but it depends on your network configuration. See for example #323 
The error lines that indicate that are the messages:
`NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa5c16ce450>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/rdkit-pypi/`

I hope we can solve this together, but you need to first check if you are using a VPN or similar.

**Comment by EstherIdabor** [comment]
Ok thank you @GemmaTuron
