### ISSUE TITLE
🐛 Bug:  `ersilia -v fetch eos2re5` returns `TypeError: expected str, bytes or os.PathLike object, not NoneType`

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#339]
### Describe the bug.

`eos2re5` runs but after a certain point time throws a type error after almost 30 mins

### Screenshots.

[eos2re5.txt](https://github.com/ersilia-os/ersilia/files/9788370/eos2re5.txt)

### Operating environment

WSL Ubuntu 18.04.5 LTS

**Comment by GemmaTuron** [comment]
Hi @sayantani11 !

This model has some known issues due to python 2.7 installation, so I'd suggest we skip it for the moment ;)
