### ISSUE TITLE
🐛 Bug:  `eos526j` fails with an `EmptyOutputError`

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#340]
### Describe the bug.

eos526j runs but fails with an EmptyOutputError , and the model API `predict` did not produce an output.

### Expected behavior.

:+1: Model eos526j fetched successfully!

### Screenshots.

[eos526j.txt](https://github.com/ersilia-os/ersilia/files/9788540/eos526j.txt)

### Operating environment

WSL Ubuntu 18.04.5

**Comment by Zainab-ik** [comment]
@sayantani11 according to your log file, I see an error stating `maybe git LFS is broken`, try downloading it again and run your commands.
There's also an error about `pip dependency` I believe @GemmaTuron  will give justice to that.

**Comment by GemmaTuron** [comment]
Hi @sayantani11 !

Good catch @Zainab-ik , lines 9 and 10 seem to indicate there is an issue with Git LFS, can you check it is installed and recognized in the ersilia conda environment?

fatal: 'lfs' appears to be a git command, but we were not
able to execute it. Maybe git-lfs is broken?

**Comment by GemmaTuron** [comment]
Hi @sayantani11 !

I know you don't have this model assigned but I wanted to confirm if your `git-lfs` was working properly, if you can try a fetch for the model again and let me know that would be great.
We will then close the issue if solved!

**Comment by sayantani11** [comment]
> Hi @sayantani11 !
> 
> I know you don't have this model assigned but I wanted to confirm if your `git-lfs` was working properly, if you can try a fetch for the model again and let me know that would be great. We will then close the issue if solved!

I took time to run it again, `git-lfs` being broken was the only problem here. So, we can close this.
