### ISSUE TITLE
🐛 Bug: Fetching model eos97yu got "EmptyOutputError"

### ISSUE THREAD

**Issue by RoseZhen2022** [ersilia-os/ersilia#344]
### Describe the bug.

Failed to fetch model eos97yu, it shows:
EmptyOutputError
Error message:
Model API eos97yu:predict did not produce an output

By the way, I have successfully fetched and calculated test model eos3b5e.

### Describe the steps to reproduce the behavior

ersilia -v fetch eos97yu | tee -a eos97yu.log 2>&1

### Expected behavior.

Expect to fetch the model and do the prediction 

### Screenshots.

[eos97yu.log](https://github.com/ersilia-os/ersilia/files/9791387/eos97yu.log)

### Operating environment

macOS Monterey

### Additional context

I have run this model multiple times and have reinstalled git-lfs, still can't be resolved.

**Comment by Malikbadmus** [comment]
Hello @RoseZhen2022 , check that you have Git-LFS installed.

This problem usually occur if you don't have Git-LFS installed.

**Comment by RoseZhen2022** [comment]
> Hello @RoseZhen2022 , check that you have Git-LFS installed.
> 
> This problem usually occur if you don't have Git-LFS installed.

Thank you for your suggestion. Actually, I have installed git-lfs, and to make sure it works I installed it again. But the model was still fetched failed.

**Comment by Malikbadmus** [comment]
Hello @RoseZhen2022 , look through issue #346  and see if the solutions there work for you.

**Comment by GemmaTuron** [comment]
Hello  @RoseZhen2022 

I think I am missing part of the error. Could you please run it again without the tee command, directly saving the log file and pasting it here? It might be missing a few lines. Let's check!
thanks

**Comment by RoseZhen2022** [comment]
> Hello @RoseZhen2022
> 
> I think I am missing part of the error. Could you please run it again without the tee command, directly saving the log file and pasting it here? It might be missing a few lines. Let's check! thanks

Thank you for your replay @GemmaTuron. I just run it without tee command and here is new log.
 
[eos97yu.log](https://github.com/ersilia-os/ersilia/files/9795366/eos97yu.log)

**Comment by GemmaTuron** [comment]
Thanks @RoseZhen2022 !
I agree the log does not give obvious errors...
Can you move this model to the Google Colab testing? You can also specify the -verbose option there and see if we can reproduce the error

Thanks!

**Comment by GemmaTuron** [comment]
I am tagging here @miquelduranfrigola to have a look at the CLI error as well

**Comment by RoseZhen2022** [comment]
Hi @GemmaTuron , I changed operating system to Ubuntu 22.04.1 LTS and set the environment again. It works well  and I have added the output csv file to the drive, so I would like to close this issue.
