### ISSUE TITLE
🐛 Bug: Fetching eos4u6p model repeatedly fails

### ISSUE THREAD

**Issue by Cee-tech21** [ersilia-os/ersilia#346]
### Describe the bug.

Running the fetch command triggers download of relevant packages but eventually the process fails and self terminates with the following series of messages:

>      Something went wrong with Ersilia...
>      EmptyOutputError
>      Error message:
>      Model API eos4u6p:predict did not produce an output

Running the serve command also leads to above outcome.

### Describe the steps to reproduce the behavior

Run the following commands in sequence:

   `ersilia -v fetch eos4u6p | tee -a eos4u6p_fetch.log 2>&1`
`
   ersilia -v serve eos4u6p | tee -a eos4u6p_serve.log 2>&1
`

### Expected behavior.

I expected the model eos4u6p to be downloaded.

### Screenshots.

[eos4u6p_fetch.log](https://github.com/ersilia-os/ersilia/files/9791768/eos4u6p_fetch.log)

### Operating environment

Linux Mint 19

**Comment by Malikbadmus** [comment]
Hello @Cee-tech21 , this problem usually occur if you don't have Git-LFS installed.

Check to make sure you have it installed.

**Comment by Cee-tech21** [comment]
> Hello @Cee-tech21 , this problem usually occur if you don't have Git-LFS installed.
> 
> Check to make sure you have it installed.
![git-lfs-version](https://user-images.githubusercontent.com/88627491/195982246-50735e43-58ec-4427-8e08-ca3e8702a168.png)

Hola @Malikbadmus 
git-lfs is installed. Please see attached screenshot

**Comment by UChisom** [comment]
Hi @Cee-tech21 , since you've installed `git-lfs`, did you also activate (initialize) it after your installation?
If no, you can do so by running `git-lfs install` command and retry fetching

**Comment by Cee-tech21** [comment]
Installed `git-lfs` again in the ersilia environment and was able to fetch and predict!
