### ISSUE TITLE
The Installation guide for intalling ersilia model did not specify the Conda Environment that should be used

### ISSUE THREAD

**Issue by dchidindu5** [ersilia-os/ersilia#35]
While reading through the conda documentation, I found out that the Conda environment is made up of two versions (miniconda and anaconda).
Both are recommended but with different features and functionalities.

I'm suggesting that both versions should be outlined in the "Ersilia Installation Guide" so that users can make their choices.

**Comment by sejalsingh417** [comment]
I would like to contribute, please assigned it to me

**Comment by GemmaTuron** [comment]
Hi @dchidindu5 

Thanks for noting this. I currently cannot give access to edit the GitBook where the Installation guide is, but can you write down here the paragraph you would like to add? I will later add it to our Installation guide. You can link this issue directly in the outreachy website to record your contribution.

@sejalsingh417 please add your comments once @dchidindu5 has provided a first template, this can be a collaborative isse. I have assigned it to both of you.

**Comment by dchidindu5** [comment]
Can you please reassign me the project? i mistakenly clicked on something

**Comment by sejalsingh417** [comment]
We should make two versions in the installation guide, first one is for the Anaconda and second is for the Miniconda

**Comment by dchidindu5** [comment]
Making two versions, don't you think the guide will be so bulky and
confusing.

From my own initiative, the goal should be to tell the user the most
convenient conda package that should be used.
Conda has it's own documentation and there's a link to that in the Ersilia
book documentation.

**Comment by GemmaTuron** [comment]
Hello @dchidindu5 and @sejalsingh417 
Please see the new contribution structure, I will close this issue for the moment to let you focus on the tasks specified there.
Go to the slack channel for information!

**Comment by dchidindu5** [comment]
That sounds great
