### ISSUE TITLE
🐛 Bug: Model `eos6m4j`: CLI - `descriptors did not produce an output`

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/ersilia#350]
### Describe the bug.

While fetching the model `eos6m4j`, my system suddenly shut down and the error log is not informative enough. 
The model `eos6m4j` repeatedly shut down my system while fetching using the `ersilia -v fetch eos6m4j > eos6m4jEE.log 2>&1`.

### Describe the steps to reproduce the behavior

- open WSL

- activate ersilia environment

- run `ersilia -v fetch eos6m4j > eos6m4jEE.log 2>&1`.

### Expected behavior.

Fetch model succesfully

### Screenshots.

[eos6m4jE.log](https://github.com/ersilia-os/ersilia/files/9794100/eos6m4jE.log)
Error log file of model `eos6m4j`

### Operating environment

Ubuntu 20.04.1 LTS Windows 11

### Additional context

All packages installed
Connected to internet

**Comment by Zainab-ik** [comment]
@GemmaTuron, Kindly go through. Thank you

**Comment by Yayeks** [comment]
I tried running this in the early hours of the morning when I hadn't been assigned a model. My system went off to while downloading and extracting packages.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik I don't know what can be the root of this issue, I have run it on my WSL system and also in my linux machine without trouble both times.
Focus on trying to understand the internet issues as we are discussing in #352 and see if we can get over those.

**Comment by Zainab-ik** [comment]
@GemmaTuron I'd make do with that.

**Comment by GemmaTuron** [comment]
Hi  @Zainab-ik !

I am unable to reproduce this, so I am guessing it might have to do with the connection (MolMap is quite a large model)
Let's close this issue and mark it in purple in the excel file so that I know this model can be problematic

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron, can this issue be reopened so I can update with recent error?

**Comment by Zainab-ik** [comment]
Thanks @GemmaTuron

**Comment by Zainab-ik** [comment]
The model `eos634j` was rerun after going through the process stated in #372. The `molmap` model is quite a large one as seen here
![eos6m4j size 2](https://user-images.githubusercontent.com/54579707/197709146-e005237a-1f64-4ca2-94aa-b110ed964392.png)

After fetching using the `ersilia -v fetch eos6m4j`, going through the log output on the terminal, 
The following error was noticed:

1. `Value error and urllib3 exceptions`
![error 1 eos6m4j](https://user-images.githubusercontent.com/54579707/197709949-db5fbd72-c7d6-4ab2-8e8e-0230a3c7c4cf.png)

2. `Protocol error: urllib3 exceptions` 
![error 2 eos6m4j](https://user-images.githubusercontent.com/54579707/197710474-bc9d3b1d-ab34-4c80-b7b4-3f0665c0a52c.png)

3. `ChunkedEncodingError; requests exceptions` 
![error 3 eos6m4j](https://user-images.githubusercontent.com/54579707/197710689-972c055f-24ac-4c53-b7f8-e6cb6df646da.png)

4. `Requests dependency warning` 
![error 4 eos6m4j](https://user-images.githubusercontent.com/54579707/197710863-defeb1a2-df1a-4b28-9565-dd6c72a88530.png)

5. `Ersilia exception class: EmptyOutputError` 
![final error 2 eos6m4j](https://user-images.githubusercontent.com/54579707/197711206-5ff888b8-1dc3-4604-98da-1a68b14c6302.png)

The model fetched for 2hrs 10min and along the log output, the API is described to be a `descriptor`
![eos6m4j API](https://user-images.githubusercontent.com/54579707/197711776-808466f3-af15-450e-9d3e-1612d6cd15c8.png)

Final detailed error: `Model API eos6m4j: descriptors did not produce an output`

P.S: another process of rerun would be done to get a log output and attach.
@GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik !

Can you check which urllib version you have on the ersilia conda environment and on the eos6m4j conda environment?

**Comment by Zainab-ik** [comment]
Alright @GemmaTuron, I'd get back.

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik !
> 
> Can you check which urllib version you have on the ersilia conda environment and on the eos6m4j conda environment?

![image](https://user-images.githubusercontent.com/54579707/197951171-931db990-4b97-42e3-aa05-fa76584274b6.png)
@GemmaTuron I have version 1.25.11 on the ersilia conda enviroment.

**Comment by GemmaTuron** [comment]
and if you activate conda environment eos6m4j (is automatically created when fetching the model)?

**Comment by Zainab-ik** [comment]
> and if you activate conda environment eos6m4j (is automatically created when fetching the model)?

@GemmaTuron I do not understand the question.

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron, I've been able to fetch the model `eos6m4j` successfully. Attached is the log output 
[my.log](https://github.com/ersilia-os/ersilia/files/9867695/my.log)

However, this model has 2 APIs: _Descriptors & Fingerprints_
![image](https://user-images.githubusercontent.com/54579707/197979657-89f7fb95-6195-46b6-b509-30eba26407de.png)

I need to proceed to generate output. However, I'd like to clarify;
Are these APIs used the same way we use _Predict and Calculate_?
And can I get an explanation on both APIs?
When generating output, do I use both together or separately?
Thank you @GemmaTuron

**Comment by UChisom** [comment]
Hi @Zainab-ik 

According to @GemmaTuron explanation a while ago on slack, when you encounter two APIs, you should serve and predict each individually. Then save the output file with the model name and API you used for that instance.

Hope this helps!

**Comment by Zainab-ik** [comment]
> > > and if you activate conda environment eos6m4j (is automatically created when fetching the model)?
> > 
> > 
> > @GemmaTuron I do not understand the question.
> 
> When you fetch a model, it creates an environment for itself. Activate that environment and check the version of the package in there.

I've done this and I've been able to fetch.

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik
> 
> According to @GemmaTuron explanation a while ago on slack, when you encounter two APIs, you should serve and predict each individually. Then save the output file with the model name and API you used for that instance.
> 
> Hope this helps!

Yh @UChisom , it does helps. What I do not understand is in the last code, do I still use `predict` instead of `descriptors` and what if both APIs take different kind of input.

**Comment by UChisom** [comment]
Okay great! @Zainab-ik 

You should use `descriptors` first, then `fingerprints` next. This should be proper since they are both APIs of the model

**Comment by Zainab-ik** [comment]
> Okay great! @Zainab-ik
> 
> You should use `descriptors` first, then `fingerprints` next. This should be proper since they are both APIs of the model

Thank you @UChisom

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron @UChisom, I've been able to generate outputs with both APIs. 
Thank you.
