### ISSUE TITLE
🐛 Bug: Convert model input file from csv to a smiles list 

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#351]
### Describe the bug.

Hi @GemmaTuron 

I encountered an error on [colab](https://colab.research.google.com/github/ersilia-os/ersilia/blob/master/notebooks/ErsiliaOnColaboratory.ipynb#scrollTo=2rHDJCpBUC73), whilst converting the model prediction output - [eos6o0z.csv](https://drive.google.com/file/d/1s63GHwJ4ETjjUdBaZ6GSKb6q9A89TSkk/view?usp=sharing) to a smiles list.

### Describe the steps to reproduce the behavior

To replicate this error
- [x] Install [Ersilia](https://github.com/ersilia-os/ersilia) on Google Colab.
- [x] Connect Colab to the google drive and specify the path to the input file [eos6o0z.csv](https://drive.google.com/file/d/1s63GHwJ4ETjjUdBaZ6GSKb6q9A89TSkk/view?usp=sharing)
- [ ] Convert eos6o0z.csv from csv to a smiles list to pass to Ersilia Models

### Expected behavior.

Eos6o0z.csv file converted successfully

### Screenshots.

**Initial steps successful**
![colab1 err](https://user-images.githubusercontent.com/63536707/196028824-d5fa233a-7db4-4b86-801b-60e69679166c.png)

**Error encountered during conversion**
![colab err](https://user-images.githubusercontent.com/63536707/196028737-d6365c29-0e85-485a-bbb1-70ffc8d9c871.png)

### Operating environment

Windows 10. Brave browser version 1.44.105

**Comment by Malikbadmus** [comment]
Hello @pauline-banye, the data you're attempting to convert to smiles to read into python contains a wrong column name.

`smiles = df["CAN_SMILES"].tolists()`  change the CAN_SMILES to the column that contain your SMILES string in this case can_smiles.

so what you should have is smiles = `df["can_smiles"].tolist()`

**Comment by GemmaTuron** [comment]
Thanks @Malikbadmus 
Indeed this notebook is coded for a specific input file, in this case the problem is that python recognizes lowercase and uppercase, so we are asking it to find the column "CAN_SMILES" (which is the short version of canonical smiles") when we actually have a column named "can_smiles" it seems?
You can run:
`import pandas as pd #package for working with tables`
`df = pd.read_csv(path)`
`df.columns`
This will output the column names.

To select a single column (in this case we only have one):
`df["columnname"]`

**Comment by Cee-tech21** [comment]
hola @GemmaTuron and @pauline-banye I am not sure which file/data we need to use for the conversion to smiles list. 
Is it the eml_canonical.csv file we should pass to `pd.read_csv(path)`

**Comment by pauline-banye** [comment]
Hii @Cee-tech21, I'm passing the eml_canonical.csv

**Comment by pauline-banye** [comment]
@Cee-tech21 it's the eml_canonical.csv we need to specify  as the path
