### ISSUE TITLE
🐛 Bug: Model `eos3d3r`: Type error while fetching

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/ersilia#352]
### Describe the bug.

The model `eos3d3r` repeatedly fails while fetching using the `ersilia -v fetch eos3d3r > eos3d3rE.log 2>&1` .
It produces an error stating:

> TypeError: expected str, bytes or os.PathLike object, not NoneType
@GemmaTuron 

### Describe the steps to reproduce the behavior

- open WSL
- activate ersilia environment
- run `ersilia -v fetch eos3d3r > eos3d3rE.log 2>&1`

### Expected behavior.

Fetch model successfully.

### Screenshots.

[eos3d3rE.log](https://github.com/ersilia-os/ersilia/files/9794116/eos3d3rE.log)
Log file of model

### Operating environment

Ubuntu 20.04.1 LTS Windows 11

**Comment by GemmaTuron** [comment]
Hello @Zainab-ik 

As you can see in the log you get repeated times the following notification for the initial packages installed (pandas, rdkit and 
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f233b707fd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pandas/

If you search a bit the internet you will see this is related to your internet setup, either a VPN or a proxy network error. Do you know if you are using any of these?

**Comment by GemmaTuron** [comment]
I also wanted to share this, maybe it helps!
https://stackoverflow.com/questions/52815784/python-pip-raising-newconnectionerror-while-installing-libraries

**Comment by Zainab-ik** [comment]
@GemmaTuron Thank you, I don't use VPN but it's most likely due to Proxy network, according to the article, it suggests changing the network settings. So I'd do that and rerun my model.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 
As we have discussed in Slack, for this issue and also #350 #349 let's use Google Colab

**Comment by Zainab-ik** [comment]
@GemmaTuron I was able to run this in colab and uploaded my CSV to the drive. It still doesn't work in the CLI though.

**Comment by Zainab-ik** [comment]
This works on CLI now,, check issue #372
