### ISSUE TITLE
🐛 Bug: How to use the excel file to test the different modules

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#353]
### Describe the bug.

I have successfully fetched the sample model, served it and run the calculate
How do i use the excel file to proceed to and test my models

### Operating environment

Ubuntu 22.04 in windows 11 virtual box

**Comment by pauline-banye** [comment]
Hi @angelnagaba you need to run 

`ersilia -v api calculate -i "eml_canonical.csv" -o <name-of-model-csv> > my.log >2&1`

**Comment by pauline-banye** [comment]
@angelnagaba you need to test the csv file on colab.

**Comment by GemmaTuron** [comment]
Hi @angelnagaba thanks for the question and @pauline-banye  for the contribution.
On the first stage, you will fetch and run predictions for the models that are assigned to you. The predictions should be for the eml_canonical.csv (the essential medicine list by the WHO). Once this is working, you should:

- Upload the predictions in the shared folder
- In the corresponding cells of the excel file, annotate the time to fetch and predict the models. You can see some examples from your peers!
Links to the shared folders and files are in the contribution guidelines
