### ISSUE TITLE
🐛 Bug: Failed to Fetch model eos97yue

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#354]
### Describe the bug.

When i run the command to fetch the model this is the message i get

- InvalidModelIdentifierError

Error message:
Could not identifiy model identifier or slug eos97yue:
[my.log](https://github.com/ersilia-os/ersilia/files/9794287/my.log)

### Describe the steps to reproduce the behavior

Fetch the model eos97yue

### Expected behavior.

Successfully fetch the model

### Operating environment

Ubuntu 22.04 in windows 11 virtual box

**Comment by GemmaTuron** [comment]
Hi  @angelnagaba !

In this case is easy:
the error "Could not identifiy model identifier or slug eos97yue:" is simply telling you the name is not correct. All ersilia models are identified by eos+4 letters/numbers
in your case it is `eos97yu`
I might have made a typo on slack!

**Comment by angelnagaba** [comment]
Thank you
