### ISSUE TITLE
🐛 Bug:  Model eos92sw

### ISSUE THREAD

**Issue by thormiwa** [ersilia-os/ersilia#355]
### Describe the bug.

While Trying to fetch the eos92sw Model using this command `ersilia -v fetch eos92sw` i get this error 

`Something went wrong with Ersilia...

EmptyOutputError

Error message:
Model API eos92sw:predict did not produce an output`

### Describe the steps to reproduce the behavior

1. After Activating Ersilia with `conda activate ersilia`
2. Run `ersilia -v fetch eos92sw` and watch the Log

### Screenshots.

<img width="1440" alt="Screenshot 2022-10-16 at 12 54 32" src="https://user-images.githubusercontent.com/70862950/196033996-e3bd0438-a74a-48b8-b881-93b31051dd11.png">

### Operating environment

Mac M1

**Comment by GemmaTuron** [comment]
Hi @thormiwa 

Please save the log of the error and attach it here so that I can see what went wrong, the screenshot is only a snippet

**Comment by thormiwa** [comment]
Hi @GemmaTuron. This is the log file
[eos92sw.log](https://github.com/ersilia-os/ersilia/files/9795106/eos92sw.log)

**Comment by GemmaTuron** [comment]
One question @thormiwa did you collect the log with the `| tee` command?

**Comment by thormiwa** [comment]
@GemmaTuron Yes this was the command i ran `ersilia -v fetch eos92sw | tee -a eos92sw.log 2>&1`

**Comment by GemmaTuron** [comment]
Ok, try and do it without the |tee because I think it is not saving the full full error output ;)

**Comment by thormiwa** [comment]
@GemmaTuron 
[eos92sw-1.log](https://github.com/ersilia-os/ersilia/files/9795228/eos92sw-1.log)

**Comment by GemmaTuron** [comment]
Thanks @thormiwa !

I see a similar pattern with #338 and #343, so we are getting close. @miquelduranfrigola we need to have a closer look at these models, they all use sqlalchemy and also throw the chardet-urllib dependency warning.

@thormiwa can I ask you to go on and test the model in google colab see if we get the same error? (you can also use the -v flag there)

**Comment by thormiwa** [comment]
@GemmaTuron it actually ran correctly on google colab...i will update on the excel sheet and also the drive😂

**Comment by GemmaTuron** [comment]
Thanks @thormiwa !

We'll do some debugging on our side to see what is going on, will post here questions as I come across them, see if we can identify the problem.

**Comment by Femme-js** [comment]
Hi @GemmaTuron ! 

I was able to fetch this model successfully on my CLI. 
[eos92sw.log](https://github.com/ersilia-os/ersilia/files/9841357/eos92sw.log)

Neither I am getting any dependency warnings here. 

Versions:
requests==2.28.1
urllib3==1.25.11
chardet==5.0.0
charset-normalizer==2.1.1

**Comment by thormiwa** [comment]
Hi @GemmaTuron After installing lfs correctly i just had to fetch, serve and predict and it ran successfully :). I will add the files to the drive and also check through other issues to support folks who might have similar error. Can i close the issue now?
