### ISSUE TITLE
🐛 Bug: Download did not work fetching models eos2ta5 and eos6m4j

### ISSUE THREAD

**Issue by UChisom** [ersilia-os/ersilia#356]
### Describe the bug.

I tried to fetch two models - `eos2ta5` and `eos6m4j` and they both raised errors stating `Exception: Download from ersilia-os/eos2ta5 did not work`. 

### Describe the steps to reproduce the behavior

- `ersilia -v fetch eos2ta5`

### Expected behavior.

Successfully fetched model

### Screenshots.

[eos2ta5.pdf](https://github.com/ersilia-os/ersilia/files/9794909/eos2ta5.pdf)
[eos6m4j.pdf](https://github.com/ersilia-os/ersilia/files/9794911/eos6m4j.pdf)

### Operating environment

Ubuntu 22.04.1 LTS

### Additional context

I successfully ran the dummy model and another actual test model

**Comment by UChisom** [comment]
@GemmaTuron  please see issue

**Comment by GemmaTuron** [comment]
Hi  @UChisom I see the following two notices:
eos2ta5:
RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 913 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF fatal:
fetch-pack: invalid index-pack output

eos6m4j
7915 bytes of body are still expected| 12.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF fatal:
fetch-pack: invalid index-pack output

Both indicate there is an internet issue! see my comment #357 and lets decide what to do

**Comment by UChisom** [comment]
Hi @GemmaTuron thanks for the responses! I'll follow through on the different solutions you linked and revert with updates.

Frankly, I'd appreciate any workaround for internet connectivity as well😊

**Comment by GemmaTuron** [comment]
Hi @UChisom 

Yes, I know internet can be a pain. Please try to get a but more information on the error and see if there is a way to solve them, and add it on the documentation issue as detailed as you can (#359 )
Meanwhile to continue with model testing, let's use google colab. Your internet will only be needed to connect to google, and model fetch etc will depend on google's own internet.

**Comment by UChisom** [comment]
Thanks @GemmaTuron 🙂

**Comment by UChisom** [comment]
Thanks @GemmaTuron 

That's fine
