### ISSUE TITLE
🐛 Bug: Empty output error while fetching eos4tcc

### ISSUE THREAD

**Issue by UChisom** [ersilia-os/ersilia#357]
### Describe the bug.

The model `eos4tcc` raised an `Emtpy output error` while I tried to fetch it. In the log file, it ran into a CONDAHTTPERROR from which the program continued to download packages and fetch the model. Eventually it produced an Empty output error

### Describe the steps to reproduce the behavior

- `ersilia -v fetch eos4tcc`

### Expected behavior.

Successfully fetched model

### Screenshots.

[eos4tcc error.pdf](https://github.com/ersilia-os/ersilia/files/9794965/eos4tcc.error.pdf)

### Operating environment

Ubuntu 22.04.1 LTS

### Additional context

I successfully ran the dummy model and another test model already. I have git lfs installed as well.

**Comment by UChisom** [comment]
@GemmaTuron please see issue

**Comment by GemmaTuron** [comment]
Hi @UChisom 

If you look at your error log, you will see the following message:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url
<https://conda.anaconda.org/pytorch/linux-64/pytorch-1.12.0-py3.7_cuda11.3_cudnn8.3.2_0.tar.
bz2> Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

This means your internet connection likely dropped while fetching. Specially if other models work that must have been the problem. If you think your internet connection is unstable and will make it difficult to work on the Ersilia CLI let me know so we can find a workaround, but maybe try fetching this model once more.

**Comment by GemmaTuron** [comment]
What might work for you @UChisom  is try and increase the buffer or download sizes, see https://stdworkflow.com/877/error-rpc-failed-curl-56-gnutls-recv-error-54-error-in-the-pull-function

**Comment by Femme-js** [comment]
Hi @UChisom !

This is the same error that I ran into with two of my models. 
[](https://github.com/ersilia-os/ersilia/issues/338)

**Comment by GemmaTuron** [comment]
Hi @Femme-js ,
Actually if you look at the error logs on #338 I don't see the same messages, so this is not the same error I think...

**Comment by UChisom** [comment]
Thanks @GemmaTuron I'll work on the solutions you've linked and get back to you.

I'll fetch them once more, and I'm really hopeful for any workaround to strengthen my internet stability 😊

_We could continue on this thread_

**Comment by GemmaTuron** [comment]
Hi  @UChisom try and do some reading on the internet as there are a few solutions proposed such as increasing buffer size.
In parallel, test the models in Colab which won't be restricted by your internet ;)

**Comment by UChisom** [comment]
Hi @GemmaTuron I have now tested the model and opened the associated issues in #372 .

They still didn't work out

**Comment by GemmaTuron** [comment]
Hi @UChisom I am closing this error as this is originally related to connectivity issues.
Let's continue the conversation on the open issues!
