### ISSUE TITLE
🐛 Bug: Error while cloning Ersilia from Github (ERROR: No matching distribution found for bentoml==0.11.0)

### ISSUE THREAD

**Issue by Balofire** [ersilia-os/ersilia#358]
### Describe the bug.

After satisfying all the pre-requisites for the installation of the Ersilia Tool and cloning it from Github using `git clone https://github.com/ersilia-os/ersilia.git,` I ran into the errors; **"ERROR: Could not find a version that satisfies the requirement bentoml==0.11.0 (from ersilia) (from versions: none)"** and **"ERROR: No matching distribution found for bentoml==0.11.0"**, when running `pip install -e .` .

### Describe the steps to reproduce the behavior

1. Create conda environment using `conda create -n ersilia python=3.7`
2. Activate the environment using `conda activate ersilia`
3. Clone the Ersilia Python Package from Github using `git clone https://github.com/ersilia-os/ersilia.git
cd ersilia`
4. Install with pip,  `pip install -e .`

### Expected behavior.

I expected the package to install successfully so I could check with `ersilia --help` and the dummy test model eos3b5e.

### Screenshots.

![Screenshot (3)](https://user-images.githubusercontent.com/102294666/196045994-681a4a09-087b-44c3-bcf5-df9c27b81879.png)

### Operating environment

 Ubuntu 20.04.5 LTS

### Additional context

This was all after I had succesfully installed the tool and had run into an error while trying to execute the dummy test model **eos3b5e.** I followed the installation steps again in a bid to correct that previous issue and now I'm battling with the one above.

**Comment by GemmaTuron** [comment]
Hello @Balofire 
If you check the error explanation you see this is related to an internet connection, not to ersilia. Could be due to a vpn or proxy you are using? 
Also you can try to increase the buffer or download size
https://stdworkflow.com/877/error-rpc-failed-curl-56-gnutls-recv-error-54-error-in-the-pull-function

@Zaniab-ik is experiencing similar issues #352

**Comment by Zainab-ik** [comment]
@Balofire check your network settings and check out this article [Here](https://stackoverflow.com/questions/52815784/python-pip-raising-newconnectionerror-while-installing-libraries)

**Comment by ZakiaYahya** [comment]
@Balofire i've encountered the same problem while installing ersilia model. I did these steps and i got rid of these error, plz follow theses steps and check whether it's working for you or not, do this inside the ersilia environment, 
sudo apt-get update
sudo apt-get upgrade
sudo apt install python3-pip
 pip3 --version                                                                                                                                                                                                                          after that deactivate the ersilia conda environment &
 rerun the terminal. 
I hope this works for u too.

**Comment by GemmaTuron** [comment]
This is a system issue and not related to Ersilia. I'll close this issue
