### ISSUE TITLE
🐛 Bug: Model eos4e41 not Fetching: "Something went wrong with Ersilia..."

### ISSUE THREAD

**Issue by Jona-Bvunza** [ersilia-os/ersilia#360]
### Describe the bug.

Find attached the log file
[anti_bio.log](https://github.com/ersilia-os/ersilia/files/9795707/anti_bio.log)

### Describe the steps to reproduce the behavior

Ran the "ersilia -v fetching eos4e41 " command in Ubuntu 20,04 LTS WSL 2. tried to fetch for 30 mins + and finally gave the output attached in the log file. 
 "ersilia -v serve eos4e41" reported that no model is present and requested to fetch again. 

### Operating environment

Ubuntu 22.04 LTS

**Comment by GemmaTuron** [comment]
Hello @Jona-Bvunza 

Please install git lfs and make sure it is recognized in ersilia's conda environment

See line: `git: 'lfs' is not a git command. See 'git --help'.`
And you can check my suggestion for this error on #359 and add any comments you might have!

**Comment by Jona-Bvunza** [comment]
thanks Gemma, will try another predict today and get back to you
