### ISSUE TITLE
🐛 Bug: Model eos9f6t not Fetching: "Something went wrong with Ersilia..."

### ISSUE THREAD

**Issue by Jona-Bvunza** [ersilia-os/ersilia#361]
### Describe the bug.

Find the attached log file
[9f6t.log](https://github.com/ersilia-os/ersilia/files/9795716/9f6t.log)

### Describe the steps to reproduce the behavior

Ran "ersilia -v  fetch eos9f6t",  and after 2hrs + reported "Something went wrong with Ersilia... EmptyOutputError Error message:
Model API eos9f6t:predict did not produce an output"
Ran "ersilia -v serve eos9f6t " command, gave a "model not fetched " and requested to fetch.... Find attached log file

### Operating environment

Ubuntu 22.04 LTS

**Comment by GemmaTuron** [comment]
Hello @Jona-Bvunza 

This seems to be an internet connection, check the error in your log file on line 1198
`pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.`

A quick search popped some possible solutions:
https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port

**Comment by GemmaTuron** [comment]
Also, seeing issue #360 , first make sure git-lfs is working and then try this model again as well

**Comment by Jona-Bvunza** [comment]
Thanks, @GemmaTuron. I was able to solve the issue by installing git-lfs using `conda install -c conda-forge git-lfs` . The model was fetched successfully and ran predictions for the test smiles.
