### ISSUE TITLE
🐛 Bug: Cannot test/calculate model eos54ij

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#363]
### Describe the bug.

When i run the API it shows isaura not installed 
KeyError: 'calculate'
[my.log](https://github.com/ersilia-os/ersilia/files/9797135/my.log)

### Describe the steps to reproduce the behavior

- I fetched 
- Successfully served 
- It failed on Calculate

### Operating environment

Ubuntu 22.04 in windows 11 virtual box

**Comment by GemmaTuron** [comment]
Hello @angelnagaba !

The error is to use the api "calculate". When you serve the model, you get the api's that can be used with the model, it is probably predict.
Can you complete a documentation improvement on issue #359 suggesting a more informative error message for when users select a non existing API?

And close the issue if the correct api works !

thanks

**Comment by GemmaTuron** [comment]
Hi @angelnagaba 

I'd like to close this issue if it is solved, can you let me know?
Thanks!

**Comment by angelnagaba** [comment]
Hi @GemmaTuron I haven't progressed with fetching but I opened another issue. #379

**Comment by GemmaTuron** [comment]
Thanks  @angelnagaba !

Let's work on #379 , you 'll see my coments there. I'm closign this one to avoid duplicating information ;)
