### ISSUE TITLE
🐛 Bug: eos3xip - EmptyOutputError

### ISSUE THREAD

**Issue by Hauwarh** [ersilia-os/ersilia#364]
### Describe the bug.

I ran into this error while trying to fetch model eos3xip
The log file is below
[eos3xip.log](https://github.com/ersilia-os/ersilia/files/9797318/eos3xip.log)

### Operating environment

WSL Ubuntu 22,04 LTS

**Comment by GemmaTuron** [comment]
Thanks @Hauwarh !

Can you please add:
- What conda distribution are you using
- What python
- What pip version
And if you collected the error log with `|tee`, please do it again without the` |tee -a `(save it directly), as I think it is hiding part of the log. 
I am adding here the successful log file I got on my Linux to compare.
[eos3xip.log](https://github.com/ersilia-os/ersilia/files/9800808/eos3xip.log)

**Comment by Hauwarh** [comment]
Thank you @GemmaTuron 

- Im usiing miniconda and the version conda 22.9.0
- The python version in the WSL is python 3.9 while the python version in the ersilia env is python 3.7
- The pip version in the WSL is pip 21.2.4 while the pip version in the ersilia env is pip 22.2.2

**Comment by GemmaTuron** [comment]
Hi  @Hauwarh 

Your log file seems like it's missing some information (you can use mine to compare) I see an error in line 38 on your file (please, do have a look and try to understand what goes on on your log files).
Have you used the `|tee` comand to get the file? If so, please do it again without the `|tee` command

**Comment by Hauwarh** [comment]
I tried running it without the |tee command. Right now there is nothing in my log file and it's been that way for hours.

**Comment by GemmaTuron** [comment]
Ok thanks @Hauwarh !

Let's try to run it in Google Colab and see if you get the same error, paste a link to the colab notebook here ;)
And change the issue title adding the name of the model at the beginning please so I don't get lost

**Comment by GemmaTuron** [comment]
I'll close this issue due to inactivity
