### ISSUE TITLE
Feature request: eos9be7 needs input adapter for two molecules. 

### ISSUE THREAD

**Issue by Jona-Bvunza** [ersilia-os/ersilia#368]
### Describe the bug.

eos9be7 is fetching successfully in google colab, but not predicting. Its repporting the following massage, 

AttributeError                            Traceback (most recent call last)
[<ipython-input-4-908e9577c1d6>](https://localhost:8080/#) in <module>
      3 model = ErsiliaModel("eos9be7")
      4 model.serve()
----> 5 output = model.predict(input=smiles, output="pandas")
      6 model.close()

AttributeError: 'ErsiliaModel' object has no attribute 'predict'  

### Operating environment

google colab

**Comment by GemmaTuron** [comment]
Hi @Jona-Bvunza 

Quick check, 
If you run `!ersilia serve eos9be7` does it show predict as the api for the model?

**Comment by Jona-Bvunza** [comment]
No, eos9be7 has "calculate" as its api. However i have tried replacing `output = model.predict(input=smiles, output="pandas")` with `output = model.calculate(input=smiles, output="pandas")`  but i am getting an `AssertionError` with a message below, 

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-11-4b9e6c7d0fe9>](https://localhost:8080/#) in <module>
      3 model = ErsiliaModel("eos9be7")
      4 model.serve()
----> 5 output = model.calculate (input=smiles, output="pandas")
      6 model.close()

12 frames
[/usr/local/lib/python3.7/site-packages/ersilia/core/model.py](https://localhost:8080/#) in _method(input, output, batch_size)
    124     def _set_api(self, api_name):
    125         def _method(input=None, output=None, batch_size=DEFAULT_BATCH_SIZE):
--> 126             return self.api(api_name, input, output, batch_size)
    127 
    128         setattr(self, api_name, _method)

[/usr/local/lib/python3.7/site-packages/ersilia/core/model.py](https://localhost:8080/#) in api(self, api_name, input, output, batch_size)
    327         else:
    328             return self.api_task(
--> 329                 api_name=api_name, input=input, output=output, batch_size=batch_size
    330             )
    331 

[/usr/local/lib/python3.7/site-packages/ersilia/core/model.py](https://localhost:8080/#) in api_task(self, api_name, input, output, batch_size)
    334         api_runner = self._get_api_runner(output=output)
    335         result = api_runner(
--> 336             api=api_instance, input=input, output=output, batch_size=batch_size
    337         )
    338         if output is None:

[/usr/local/lib/python3.7/site-packages/ersilia/core/model.py](https://localhost:8080/#) in _api_runner_return(self, api, input, output, batch_size)
    206                 )
    207             for r in self._api_runner_iter(
--> 208                 api=api, input=input, output=tmp_output, batch_size=batch_size
    209             ):
    210                 continue

[/usr/local/lib/python3.7/site-packages/ersilia/core/model.py](https://localhost:8080/#) in _api_runner_iter(self, api, input, output, batch_size)
    173 
    174     def _api_runner_iter(self, api, input, output, batch_size):
--> 175         for result in api.post(input=input, output=output, batch_size=batch_size):
    176             assert (
    177                 result is not None

[/usr/local/lib/python3.7/site-packages/ersilia/serve/api.py](https://localhost:8080/#) in post(self, input, output, batch_size)
    298         self.logger.debug("Posting to {0}".format(self.api_name))
    299         self.logger.debug("Batch size {0}".format(batch_size))
--> 300         unique_input, mapping = self._unique_input(input)
    301         results_ = {}
    302         for res in self.post_unique_input(

[/usr/local/lib/python3.7/site-packages/ersilia/serve/api.py](https://localhost:8080/#) in _unique_input(self, input)
    275         mapping = collections.defaultdict(list)
    276         unique_input = []
--> 277         for i, inp in enumerate(self.input_adapter.adapt_one_by_one(input)):
    278             key = inp["key"]
    279             if key not in mapping:

[/usr/local/lib/python3.7/site-packages/ersilia/io/input.py](https://localhost:8080/#) in adapt_one_by_one(self, inp)
    167 
    168     def adapt_one_by_one(self, inp):
--> 169         data = self.adapter.adapt(inp)
    170         for d in data:
    171             yield d

[/usr/local/lib/python3.7/site-packages/ersilia/io/input.py](https://localhost:8080/#) in adapt(self, inp)
    139 
    140     def adapt(self, inp):
--> 141         data = self._adapt(inp)
    142         data = [self.IO.parse(d) for d in data]
    143         return data

[/usr/local/lib/python3.7/site-packages/ersilia/io/input.py](https://localhost:8080/#) in _adapt(self, inp)
    136         inp = self._try_to_eval(inp)
    137         if self._is_python_instance(inp):
--> 138             return self._py_input_reader(inp)
    139 
    140     def adapt(self, inp):

[/usr/local/lib/python3.7/site-packages/ersilia/io/input.py](https://localhost:8080/#) in _py_input_reader(self, inp)
    119     def _py_input_reader(self, inp):
    120         reader = PyInputReader(input=inp, IO=self.IO)
--> 121         data = reader.read()
    122         return data
    123 

[/usr/local/lib/python3.7/site-packages/ersilia/io/readers/pyinput.py](https://localhost:8080/#) in read(self)
     58 
     59     def read(self):
---> 60         if self.is_single_input():
     61             return [self._data]
     62         else:

[/usr/local/lib/python3.7/site-packages/ersilia/io/readers/pyinput.py](https://localhost:8080/#) in is_single_input(self)
     43                 if type(one_element) is tuple:
     44                     one_element = list(one_element)
---> 45                 assert type(one_element) is list
     46                 one_inner_element = one_element[0]
     47                 if type(one_inner_element) is tuple:

AssertionError:

**Comment by GemmaTuron** [comment]
Hi @Jona-Bvunza 

If you go to the [Ersilia Model Hub Website](https://ersilia.io/model-hub) and search for the model `eos9be7` you will see the following explanation: _This model calculates a novel distance measure between two molecules, the Fréchet ChemNet distance (FCD)_
Therefore, you need TWO molecules as input. This means we will also need to improve the input adapters in the python package so that they accept two lists of molecules not one.

Please leave this issue as open and change the title to **eos9be7 needs input adapter for two molecules**

**Comment by Jona-Bvunza** [comment]
Ok, noted.

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola  and @brosular 

I am unable to pass molecules in the CLI for that model in any of the formats specified in https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/inputs
Can you please have a look and get back to me?

**Comment by GemmaTuron** [comment]
Thanks @girishatechie for this thorough comment and review, very helpful!
if you pass the csv file that you give an example, does the model function or it throws the same error?

**Comment by girishatechie** [comment]
Thank you! :) @GemmaTuron 

I tried to pass the CSV File, that I had given as an example above, which has a compound pair of list of molecules, that can be given as one single input, to the Model. Here's the file: 
[smiles_testing.csv](https://github.com/ersilia-os/ersilia/files/11092395/smiles_testing.csv)

However, while running predictions, the model throws a similar Assertion Error at the same line, indicating that the expression returns false, while testing. 
According to me, this is because we need to update the code to accept 2 SMILES Columns, as a single input. It won't work with the same template, because when I passed this new file as input, instead of the previous one, it was able to successfully accept it and was even able to extract the smiles, from both the columns, i.e smiles_1 and smiles_2 in the file, after making minor code changes. However, while running the actual predictions, since at that step, we're only passing a single SMILES Column as input, hence it isn't able to run successfully and find out the output, when I pass the new .CSV file, as input. The new file contains 2 SMILES Columns, which need to be passed as a single input and this isn't compatible with the current format. 

Hence, The expression evaluates to false at this particular step:
`output = model.api(input=smiles, output="pandas")`

**Comment by GemmaTuron** [comment]
Can you paste a log with the whole error you are getting?

**Comment by girishatechie** [comment]
The logging module doesn't generally function properly with Colab, hence it's not able to redirect everything to a log file, when I try to import the logging module and execute it. Is it fine if I paste the whole error along with the input commands?

**Comment by GemmaTuron** [comment]
yeah, you can copy the printed error and paste it into a .txt file manually for example

**Comment by girishatechie** [comment]
Fine, I'll just paste it manually into a .txt file and attach it here

**Comment by GemmaTuron** [comment]
thanks @girishatechie very helpful!

**Comment by GemmaTuron** [comment]
thanks, indeed we need to modify the input function to accept the pair of molecules - I cant tackle it right now but I'll leave this issue open

**Comment by GemmaTuron** [comment]
This has been solved by @miquelduranfrigola and @ZakiaYahya
