### ISSUE TITLE
🐛 Bug: Model eos9ei3; predict did not produce expected result, throws error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by EstherIdabor** [ersilia-os/ersilia#370]
### Describe the bug.
@GemmaTuron 

fetching model eos9ei3 happened succesfully as well as the serve command. on predict it produces a uniCodeError; UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

attached is the error log

[eos9ei3.log](https://github.com/ersilia-os/ersilia/files/9803340/eos9ei3.log)
 

### Describe the steps to reproduce the behavior

ersilia -v fetch eos9ei3 > eos9ei3.log 2>&1  sucessfully fetched the model
ersilia -v serve eos9ei3 Successful Available API predict

ersilia -v api predict -i "eml_canonical.csv" -o "eos9ei3.csv" > eos9ei3.log 2>&1

### Expected behavior.

successfully predict the model

### Operating environment

windows 10 ubuntu18.04.5

### Additional context

fetch command and serve model was successful

**Comment by GemmaTuron** [comment]
Thanks @EstherIdabor !

Two questions:

- Are you running the predict api from the folder where the .csv file is? otherwise you need to specify the path. We have discussed this in other issues and slack, you need to navigate through the CLI to where the file is
- Can you confirm if you get the same error when you use only a molecule as input?
`ersilia -v api predict -i "CCCCC" -o "eos9ei3.csv" > eos9ei3.log 2>&1`

**Comment by Zainab-ik** [comment]
The eml_canonical.csv, can you try running with the quote attached to it.

**Comment by Zainab-ik** [comment]
> The eml_canonical.csv, can you try running with the quote attached to it.

And have you tried @GemmaTuron suggestions.

**Comment by EstherIdabor** [comment]
> Thanks @EstherIdabor !
> 
> Two questions:
> 
> * Are you running the predict api from the folder where the .csv file is? otherwise you need to specify the path. We have discussed this in other issues and slack, you need to navigate through the CLI to where the file is
> * Can you confirm if you get the same error when you use only a molecule as input?
>   `ersilia -v api predict -i "CCCCC" -o "eos9ei3.csv" > eos9ei3.log 2>&1`

@GemmaTuron thanks!!, It actually worked with the “CCCC” molecule, there are in thesame folder

**Comment by EstherIdabor** [comment]
> The eml_canonical.csv, can you try running with the quote attached to it.

It's actually attached

**Comment by EstherIdabor** [comment]
> > The eml_canonical.csv, can you try running with the quote attached to it.
> 
> And have you tried @GemmaTuron suggestions.

Thanks Zainab, I tried @GemmaTuron  second statement and it worked

**Comment by GemmaTuron** [comment]
Hi @EstherIdabor !
Great, so the problem does not seem to be with the model. Are you indicating the path to the eml_canonical.csv file ?
Where has the output file been saved? This will indicate the folder you are in.

You either need to launch the code from the folder where it is stored or pass the full path to the CLI. For example, in my case could be:
`~/Desktop/ersiliatest/eml_canonical.csv`

**Comment by EstherIdabor** [comment]
Hi @GemmaTuron , finally gotten it, I downloaded the test file with my phone and it was saved as an .xls extension I transferred it to my laptop and tried changing the extension to CSV along that line I think it was  compromised, I downloaded it again with my laptop and transferred it to my working directory and it worked perfectly

**Comment by EstherIdabor** [comment]
Thank you @GemmaTuron
