### ISSUE TITLE
🐛 Bug: Difficulty installing ersilia model due error in checking the latest pip version and bentoml==0.11.0 requirement not being met

### ISSUE THREAD

**Issue by faith-zuby** [ersilia-os/ersilia#373]
### Describe the bug.

I'm receiving the following errors while trying to install the ersilia model hub:
1. An error that states that it could not find a version that satisfies the requirement betoml==0.11.0
2. An error that states no matching distribution found for bentoml==0.11.0
3. And a warning that states there was an error in checking the latest version of pip

### Describe the steps to reproduce the behavior

1. open the wsl command line or ubuntu for windows
2. create the ersilia environment, then git clone the git link
3. cd ersilia then type pip install -e .
it was at this point i received the error
![Screenshot 2022-10-17 013935](https://user-images.githubusercontent.com/115516015/196288333-86919af6-d543-48fe-b079-4528e42b0b13.jpg)

### Screenshots.

![Screenshot 2022-10-17 013935](https://user-images.githubusercontent.com/115516015/196287059-b8055252-7c45-4fba-9952-04cd6b1e2e11.jpg)

### Operating environment

wsl

**Comment by carcablop** [comment]
Hello @faith-zuby. Maybe you should also check your internet connection. This connection should be stable.

**Comment by ZakiaYahya** [comment]
@faith-zuby  i've encountered the same problem while installing ersilia model. I did these steps and i got rid of these error, plz follow theses steps and check whether it's working for you or not, do this inside the ersilia environment,
sudo apt-get update
sudo apt-get upgrade
sudo apt install python3-pip
pip3 --version after that deactivate the ersilia conda environment &
rerun the terminal.
I hope this works for u too.

**Comment by GemmaTuron** [comment]
Thanks @ZakiaYahya  for the suggestions

I'd suggest also upgrading pip since the last line in your screenshot is showing that the pip version cannot be found

**Comment by faith-zuby** [comment]
Thank you for your support and @ZakiaYahya it actually worked thank you so much
