### ISSUE TITLE
🐛 Bug: Model API eos526j:predict did not produce an output

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#374]
### Describe the bug.

When fetching the model eos526j I  have the following error:
Something went wrong with Ersilia...

EmptyOutputError

Error message:
Model API eos526j:predict did not produce an output

Checking the log file, the first error found is a pip dependency: 
''' ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 1.4.36 which is incompatible.'''
Although the error shows me that sqlalchemy is incompatible, in the following lines of the log it tells me that the version of sqlalchemy was correctly installed to this version: sqlalchemy-1.3.24.

### Describe the steps to reproduce the behavior

1. I run the command: `ersilia` -v fetch eos526j > eos526j_fetch_3.log `2>&1`
Sytem: Ubuntu 20.04.3 LTS 
Python 3.9.12 
conda 22.9.0
pip 21.2.4 from /home/carcablop/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
[eos526j_fetch_4.log](https://github.com/ersilia-os/ersilia/files/9804770/eos526j_fetch_4.log)

### Operating environment

Ubuntu 20.04.3 LTS

**Comment by carcablop** [comment]
**I tried again to install Git-lfs. Just like I do below.: **
```

(base) carcablop@carcablop-VirtualBox:~$ conda install git-lfs -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
(base) carcablop@carcablop-VirtualBox:~$ git-lfs install
**Git LFS initialized.**
(base) carcablop@carcablop-VirtualBox:~$ conda activate ersilia
(ersilia) carcablop@carcablop-VirtualBox:~$ git clone https://github.com/ersilia-os/isaura.git
Clonando en 'isaura'...
remote: Enumerating objects: 358, done.
remote: Counting objects: 100% (358/358), done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 358 (delta 234), reused 233 (delta 115), pack-reused 0
Recibiendo objetos: 100% (358/358), 61.87 KiB | 833.00 KiB/s, listo.
Resolviendo deltas: 100% (234/234), listo.
(ersilia) carcablop@carcablop-VirtualBox:~$ cd isaura/
(ersilia) carcablop@carcablop-VirtualBox:~/isaura$ pip install -e .
Obtaining file:///home/carcablop/isaura
  Preparing metadata (setup.py) ... done
Requirement already satisfied: h5py==3.7.0 in /home/carcablop/miniconda3/envs/ersilia/lib/python3.7/site-packages (from isaura==0.0.1) (3.7.0)
Requirement already satisfied: loguru==0.6.0 in /home/carcablop/miniconda3/envs/ersilia/lib/python3.7/site-packages (from isaura==0.0.1) (0.6.0)
Requirement already satisfied: numpy>=1.14.5 in /home/carcablop/miniconda3/envs/ersilia/lib/python3.7/site-packages (from h5py==3.7.0->isaura==0.0.1) (1.21.6)
Installing collected packages: isaura
  Running setup.py develop for isaura
**Successfully installed isaura-0.0.1**
```


Even though I reinstalled the required packages according to the documentation, I still get the same error.

I share the last log that I made, 
[eos526j_fetch_5.log](https://github.com/ersilia-os/ersilia/files/9804989/eos526j_fetch_5.log)
I can see that in line 631 I have an error that isaura is not installed, but in the previous steps that I made, it can be seen that isaura was installed correctly.

What could be the problem, I must be in the same directory of isuara or ersilia to execute the fetch? In the first example with the os3b5e model, I had no problem, nor did I have a problem with the eos2v11 model, they executed correctly.

**Comment by carcablop** [comment]
This is my version of sqlalchemy:
```
(eos526j) carcablop@carcablop-VirtualBox:~$ python
Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.24'
```

**Comment by EstherIdabor** [comment]
@carcablop you do not have to be in the ersilia directory to fetch the models, as long as the ersilia environment is activated you can fetch the models. You can try sudo apt-get update, sudo apt-get upgrade, sudo apt install python3-pip. And then rerun the terminal, this might be helpful as it helped me resolve issues with pip install.

**Comment by GemmaTuron** [comment]
Hi @carcablop you need to check GIT LFS installation:
see line 18
`git: 'lfs'no es un comando de git. Mira 'git --help'.`

**Comment by carcablop** [comment]
> Hi @carcablop you need to check GIT LFS installation: see line 18 `git: 'lfs'no es un comando de git. Mira 'git --help'.`

Thank you @GemmaTuron. I alredy solved that problem.

**Comment by carcablop** [comment]
> @carcablop you do not have to be in the ersilia directory to fetch the models, as long as the ersilia environment is activated you can fetch the models. You can try sudo apt-get update, sudo apt-get upgrade, sudo apt install python3-pip. And then rerun the terminal, this might be helpful as it helped me resolve issues with pip install.

Thank you so much @EstherIdabor. I'm going to do what you suggest, and I'll comment on what comes out.

**Comment by GemmaTuron** [comment]
Hi  @carcablop 

You solved the git-lfs issue? Can you post the log of the error you are getting now if git lfs is working properly?
Thanks!

**Comment by carcablop** [comment]
Hello @GemmaTuron. I'm sorry I didn't answer before and share the last log, I focused on advancing in Colab and the last stage. Of course, I don't have git-lfs errors anymore, this is already solved for me. I share the last log I generated on Ocubre 18. Thank you. 
[eos526j_fetch_181003.log](https://github.com/ersilia-os/ersilia/files/9843167/eos526j_fetch_181003.log)

**Comment by carcablop** [comment]
Now the error I have with pip dependencies, when I try to update it, I try to run "sudo apt-get update", it throws me the following error:  "Error GPG ..The public key is not available. 
![erro_clavepublica](https://user-images.githubusercontent.com/17841081/197309131-7f69e2dc-b458-4ff7-9501-7544e2a1f297.png)
I have tried to fix it from terminal with this command:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "my_public_key`
The command is executed successfully and when I update again, the GPG Error follows. 
When I fetch this same model in Google Colab, I get a pip warning about pip:
![imagen](https://user-images.githubusercontent.com/17841081/197310851-17b4cf52-d00f-40fe-94b8-0fee87b7ae46.png)

I will inquire more about this and I will follow the thread of the bug #377 of @Zakia-Yahya.
Thanks

**Comment by GemmaTuron** [comment]
Hi @carcablop thanks, can you try this:

`sudo gpg --keyserver pgpkeys.mit.edu --recv-key  23F3D4EA75716059`
`sudo gpg -a --export 23F3D4EA75716059 | sudo apt-key add -`
`sudo apt-get update`

Make sure I copied the key from your error correctly before running!
And I would also suggest updating conda and pip. As you can see in the error log, your conda version is quite old (4 vs current 22).
The pip message on colab we know about it and still havent figured out how to silence it, but it is not a problem in principle, thanks for reporting.

**Comment by carcablop** [comment]
Thank you so much @GemmaTuron. When I execute the command. I have the following issue:
![imagen](https://user-images.githubusercontent.com/17841081/197432951-f54d6f5b-038b-4113-974f-1f0858bf928e.png)

I try to do it in root mode. It seems that if the key is brought, but then when I update I continue with the problem.

![imagen](https://user-images.githubusercontent.com/17841081/197433335-dc405380-8673-41bf-9ba7-c75183f69564.png)

![imagen](https://user-images.githubusercontent.com/17841081/197433384-0480f76d-10a8-4a5b-ad56-39b25ca78c0b.png)

![imagen](https://user-images.githubusercontent.com/17841081/197433518-227156c9-4df2-4a7f-9fd1-b7ac2361cf70.png)

I already tried it, I also try it with the YPPA Manager.

**Comment by GemmaTuron** [comment]
Hi @carcablop !

I see you are using a virtual box, which I have little experience with. Maybe try to generate the key first as explained [here](https://packaging.ubuntu.com/html/getting-set-up.html)?
Alternatively you could simply use the new release of Ubuntu 22... I can't provide much more guidance since this is not related to Ersilia but system configuration with linux.
Let's give it one last try before we continue!

**Comment by carcablop** [comment]
Hello @GemmaTuro. Thank you very much for your help, I carried out all the steps as described in the provided guide, and everything was executed successfully, I configured the keys and updated them in the Launchpad, but the problem persists, I keep getting the same error. I don't know what could have been the origin of the problem, before this virtual machine worked well for me and I had used it for other projects, I didn't even have problems with the previous models, everything was after I tried with the eos526j model. To continue, I installed another new machine with Ubuntu 22, and everything works fine there, I have ersilia installed and the models run successfully, even the eos526j that had problems was able to run fetch successfully. I attach the log.
I didn't do it with WSL because it also generated an error that I couldn't solve at the time.:
![imagen](https://user-images.githubusercontent.com/17841081/197652174-c0edf806-85f5-450a-a30d-9a56de65af16.png)

![imagen](https://user-images.githubusercontent.com/17841081/197652410-44e86b4e-06ff-41a8-855b-77e28e46f48b.png)
And I have virtualization enabled.

I think I better continue on the new machine that I have installed with ubuntu 22.

**Comment by carcablop** [comment]
I share my new log from Ubuntu 22 virtual machine for the eos526j model executed successfully
[fetch_eos526jlog.log](https://github.com/ersilia-os/ersilia/files/9856106/fetch_eos526jlog.log)

When it tries to predict just one molecule, this was the log it threw at me
[logeos526j.log](https://github.com/ersilia-os/ersilia/files/9856109/logeos526j.log)

**Comment by GemmaTuron** [comment]
Hi @carcablop !

Great to hear you were able to solve the problems.
For one molecule is then working? in the log I don't see any error, was the output printed on the screen?

**Comment by carcablop** [comment]
> For one molecule is then working? in the log I don't see any error, was the output printed on the screen?

Hello @GemmaTuron.
It was tried for a single molecule, but that was the result and nothing was printed on the screen, due to some possible error, the console was simply closed, the output.csv file was not generated either. I thought that since the model has flaws, since Google Colab had also experienced it for a single molecule, and following the thread of problem #377 I understand that this model needs to be debugged because it has not yet been possible to convert that .json output to csv. I did NOT keep trying because I thought I would be in debugging and so no output was thrown at me.
I could try again.

**Comment by GemmaTuron** [comment]
Ok thanks @carcablop , let's pause it here!

**Comment by carcablop** [comment]
Moving this discussion to #560
