### ISSUE TITLE
🐛 Bug: Failed to fetch model eos30gr

### ISSUE THREAD

**Issue by Motunrayo321** [ersilia-os/ersilia#375]
### Describe the bug.

I encountered an unidentified error while trying to fetch model eos30gr.
There is no specific error message that can be used to debug.
The exception message read "Download from {0}/{1} did not work"
I also was not able to get a log file of the error because it kept running for over 4 hours so I will add a screenshot instead.

### Describe the steps to reproduce the behavior

ersilia -v fetch eos30gr

### Expected behavior.

Model eos30gr fetched successfully!

### Screenshots.

![fetch_eos30gr](https://user-images.githubusercontent.com/104320678/196302690-1a627c46-5591-4281-bf19-994b1f2d2385.png)

### Operating environment

Windows 10 Pro (WSL installed with Ubuntu 22.04)

**Comment by GemmaTuron** [comment]
Hi @Motunrayo321 
Let's leave this model for the moment as it has a known bug #274 
I'll mark that on the excel file

**Comment by Motunrayo321** [comment]
Alright then, thank you.
