### ISSUE TITLE
🐛 Bug: Google Colab Runntime needs to be refreshed

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#378]
### Describe the bug.

It has been reported in several issues that running Ersilia on Google Colab crashes sometimes.
I am listing here a few of the issues where this has been reported 
#372 
#366 
#347 

The common error message in all of them seems to be with tqdm though I am not sure this is the source cause:
```
import tqdm as _tqdm
ModuleNotFoundError: No module named 'tqdm'
```
It is known that ipywidgets (needed by tqdm) was not supported by Googlecolab, but in principle it is now, but this might be related. 

**The temporal bugfix is to delete and disconnect runtime everytime and this solves the error**

### Describe the steps to reproduce the behavior

I can't consistenly reproduce the steps, as the same code will run sometimes ok and others not

### Operating environment

Google Colab

**Comment by Malikbadmus** [comment]
@mamabear25 , use this instead.
`from google.colab import runtime
runtime.unassign()`

**Comment by mamabear25** [comment]
@malikbadmus I just tried it, same output....
[my collab](https://colab.research.google.com/drive/1OGqkjbXbD31HMhLyh9Kyjy4Pc7IX55El#scrollTo=agMWePaubXjW)

**Comment by GemmaTuron** [comment]
I will close this issue since the latest template versions do not give problems.
