### ISSUE TITLE
🐛 Bug: emptyoutput error. Fetch consistently fails 

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#379]
### Describe the bug.

Fetch consistently fails even after working on my  internet settings. 
[my.log](https://github.com/ersilia-os/ersilia/files/9807423/my.log)

### Describe the steps to reproduce the behavior

Fetch the model 

### Expected behavior.

Fetch model successfully 

### Operating environment

Ubuntu 22.04 VM

**Comment by zheeburg** [comment]
Can you check if you imputed the correct command in the file name and format for output? (Model.csv)

**Comment by GemmaTuron** [comment]
Hi @angelnagaba !

Let's move this testing to Colab and see if we can make it work , to avoid internet issues!

**Comment by angelnagaba** [comment]
Hello let me do this

**Comment by GemmaTuron** [comment]
Hi  @angelnagaba!
We have identified an issue with this model, see #386 --> I'd ask you to try and report if you get the same error consistently!

Thanks!

**Comment by GemmaTuron** [comment]
I'll close this issue because it's repeated in #386
