### ISSUE TITLE
🐛 Bug: "eos7a04 - Google Colab - No module named dataclasses

### ISSUE THREAD

**Issue by alaminumar** [ersilia-os/ersilia#382]
### Describe the bug.

tried to fetch eos7a04 in google Colab but it's giving me the above error .

### Screenshots.

![Screenshot (92)](https://user-images.githubusercontent.com/110132616/196484146-97103647-bf04-4ead-b668-a11657557880.png)

### Operating environment

Ubuntu 20.04 LTS

**Comment by Femme-js** [comment]
Hi @alaminumar ! Can you get the logs for above error?

Please re-execute the command with verbose -v

**Comment by alaminumar** [comment]
@Femme-js will do

**Comment by alaminumar** [comment]
Link to the colab. https://colab.research.google.com/drive/1iXX7R80k-b2lW2xjDsCDM4wKaWIYB1YF?usp=sharing

**Comment by GemmaTuron** [comment]
Hi @alaminumar !

thanks, I think the dataclasses package has been updated and is causing trouble in a few models, see #387 
Please change the title of the issue to:
"eos7a04 - Google Colab - No module named dataclasses" and mark it in purple on the excel.

**Comment by GemmaTuron** [comment]
I'm gonna leave it open so we see which things we need to work on ;)

**Comment by DhanshreeA** [comment]
Also resolved with updating miniconda installer script as in #367

**Comment by GemmaTuron** [comment]
Hi, this model is solved with the current Colab template where we specify the PythonPath for py3.7 installation, like in #367
