### ISSUE TITLE
Traceback error while trying to fetch model on Google Colab

### ISSUE THREAD

**Issue by zheeburg** [ersilia-os/ersilia#385]
### Describe the bug.

![58864390-090E-4FB2-8F4D-F969C864E5BC](https://user-images.githubusercontent.com/41709695/196605893-3bb6fcdf-600b-4e77-8c8a-c45b1687f178.jpeg)

### Operating environment

Ubuntu 20.4.1

**Comment by Zainab-ik** [comment]
@zheeburg for a traceback error, try deleting your runtime and disconnect. Then run your code all over from the start. I think the problem should've resolved.

**Comment by GemmaTuron** [comment]
Hi @zheeburg !

Traceback error is simply the indication that something went wrong, as the name suggests is giving you pointers as to where you can trace the origin of the error.
Please, update your issue with the relevant information or we can't provide support.

**Comment by GemmaTuron** [comment]
Hi @zheeburg 

Why are you closing this issue? Please report if the model worked, if it didn't, what error is it showing?

**Comment by zheeburg** [comment]
I upgraded to the latest version of the protobuf and I used the package as shown below
`!pip install --upgrade protobuf`

Then, I installed matplotlib-inline
`pip install matplotlib-inline`
 
 Also cleared all my codes and started all over again
I stopped getting the Traveback error and continued debugging.
Thanks everyone.

**Comment by GemmaTuron** [comment]
Hello @zheeburg 

Did the model run successfully? can you paste a link to colab where it shows the model?
thanks

**Comment by GemmaTuron** [comment]
I'll close this issue due to inactivity
