### ISSUE TITLE
🐛 Bug: Errors with Flask and Docker after running ''ersilia --help''

### ISSUE THREAD

**Issue by Balofire** [ersilia-os/ersilia#388]
### Describe the bug.

After following all of the installation steps again, I've  run into a traceback errors that either mention flask or docker, after running `ersilia --help`, even though both have already been installed and upgraded in the ubuntu terminal.

### Describe the steps to reproduce the behavior

1. Activate conda environment with; `conda activate ersilia`
2. Clone ersilia from Github with `git clone https://github.com/ersilia-os/ersilia.git
cd ersilia`
3. Install with `pip install -e .`
4. Run `ersilia --help`

### Expected behavior.

I expected to see ersilia CLI options.

### Screenshots.

![Screenshot (6)](https://user-images.githubusercontent.com/102294666/196672713-dac374eb-1e0c-4e6f-b673-51ffb9c5100a.png)
![Screenshot (7)](https://user-images.githubusercontent.com/102294666/196672723-5f3058ef-b9f1-4596-a347-34ae9e1b587b.png)

### Operating environment

 Ubuntu 20.04.5 LTS

### Additional context

These errors happened after re-installing ersilia to try and fetch the dummy model and others assigned to me.

**Comment by GemmaTuron** [comment]
Hi @Balofire,

Let's see if we can find where the problem is:

- Which command have you used to CREATE the conda environment? Did you specify python version 3.7?
- Which conda version are you using?
- Which Python do you have on your system?
- Have you updated pip and conda to the latest versions?

**Comment by Balofire** [comment]
I used `conda create -n ersilia python=3.7` to create the conda environment, I have python 3.9.12 on my system but in ubuntu it's 3.7.13. I haven't updated pip and conda though.

**Comment by GemmaTuron** [comment]
hey @Balofire !

Great, let's make sure you have pip and conda updated and try to pull ersilia and install again. Eliminate the conda environment and create it anew just in case.

**Comment by GemmaTuron** [comment]
Hello @Balofire,
It seems there is an issue with Docker. Docker is not required to run ersilia at the moment, have you tried to install it?

**Comment by Balofire** [comment]
Yes, I have it installed, and of I try re- installing it, it says requirement already satisfied. But occasionally it says something about a daemon?

**Comment by GemmaTuron** [comment]
I'm sorry @Balofire I am not an informatics expert and this is related do systems setup not to ersilia directly.
I'd suggest doing everything without docker as is not a requirement

**Comment by Balofire** [comment]
Ok so should I uninstall docker then start the process again

**Comment by GemmaTuron** [comment]
I will close this issue due to inactivity
