### ISSUE TITLE
🐛 Bug: eos7a04 Invalid model identifier

### ISSUE THREAD

**Issue by Motunrayo321** [ersilia-os/ersilia#390]
### Describe the bug.

I encountered an InvalidModelIdentifierError while trying to fetch model eos7a04.
The error message seems to imply that this model does not exist.
I followed the given link and confirmed that it indeed does exist.

![eos7a04_exists](https://user-images.githubusercontent.com/104320678/196682963-fff68737-9e32-4a5d-9bec-ecc11d4b76dc.png)

I also checked for approved and ready models and here it is.

![eos7a04_ready](https://user-images.githubusercontent.com/104320678/196684054-ce5ef439-0b03-44cb-86ba-ef36571b7e11.png)

### Describe the steps to reproduce the behavior

ersilia -v fetch eos7a04

### Expected behavior.

Model eos7a04 fetched successfully!

### Screenshots.

I am unable to retrieve the log file but here is a screenshot of the error.

![fetch_eos7a04](https://user-images.githubusercontent.com/104320678/196684536-58856c29-b3b0-4baa-9b96-6201429f2be6.png)

### Operating environment

Windows 10 Pro (WSL installed with Ubuntu 22.04)

**Comment by Zainab-ik** [comment]
Could be due to internet bug or not cloning completely from github, try rerunning again.

**Comment by Motunrayo321** [comment]
@Zainab-ik I have tried it several times, and internet connection doesn't seem to be the problem.

**Comment by GemmaTuron** [comment]
Hi @Motunrayo321!

I just double checked and the identifier is correct. Your issue is on your fetching command, form what I see in the screenshot:
`ersilia -v fetch 7a04`

where it should be

`ersilia -v fetch eos7a04`

**Comment by GemmaTuron** [comment]
Hi @Motunrayo321 

Can you please let me know when you have time if the issue is solved?

**Comment by Motunrayo321** [comment]
Hello @GemmaTuron, sorry for the delay. The issue has been solved. I have added the outputs to the google drive as well.
