### ISSUE TITLE
🐛 Bug:  `eos2thm` fails with an `EmptyOutputError` locally but works fine on Colab

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#391]
### Describe the bug.

The problem is similar to the one I faced in fetching `eos1579` , but in that case the same problem was seen in both Colab & my local machine, but here the fetching & serving was very well done in Colab. I went through the logs, but it seems to show the similar error. I am still trying to figure out but will be thankful with some help.

### Expected behavior.

👍🏼Model eos2thm fetched successfully!

### Screenshots.

[eos2thm.txt](https://github.com/ersilia-os/ersilia/files/9824323/eos2thm.txt)

### Operating environment

Ubuntu 18.04.5 LTS WSL2

### Additional context

There's one thing I noticed whenever this happens is `Status Code 500`. I am trying to digging this if this can be a reason.

**Comment by Femme-js** [comment]
@sayantani11 I am also having the same issue #338

**Comment by GemmaTuron** [comment]
Hi @sayantani11 

That is a very good indication that the problem we are facing is due to the setup on your local machine, if the model runs in colab the packages etc itself are well indicated. Can you paste the log file when you try it on your local machine or point me to the issue where it is?

**Comment by GemmaTuron** [comment]
> @sayantani11 I am also having the same issue #338

I see @Femme-js !

Ok, I'll need some time to look at what can be the problem and suggest a  few things to try.

For both of you, let's mark these models in the excel file in purple and I am tagging this issue for further work on it!

**Comment by sayantani11** [comment]
> Hi @sayantani11
> 
> That is a very good indication that the problem we are facing is due to the setup on your local machine, if the model runs in colab the packages etc itself are well indicated. Can you paste the log file when you try it on your local machine or point me to the issue where it is?

I did upload the log file, guess there were some errors while uploading
Here it is:
[eos2thm.txt](https://github.com/ersilia-os/ersilia/files/9824317/eos2thm.txt)

**Comment by GemmaTuron** [comment]
> > Hi @sayantani11
> > That is a very good indication that the problem we are facing is due to the setup on your local machine, if the model runs in colab the packages etc itself are well indicated. Can you paste the log file when you try it on your local machine or point me to the issue where it is?
> 
> I did upload the log file, guess there were some errors while uploading Here it is: [eos2thm.txt](https://github.com/ersilia-os/ersilia/files/9824317/eos2thm.txt)

Thanks I can see it now!
Seems like the Git LFS error is persisting
When you run git-lfs --help (or any other git lfs command, I am not sure which ones are available) inside ersilia's conda environment, do you get the correct output?

**Comment by GemmaTuron** [comment]
Hi @Femme-js and @sayantani11 !

Updates on this model:
- @sayantani11 please check your git lfs installation and let's make sure this error is not persisting anymore. I am suspecting you might have tried installing the windows version of git in your linux wsl. See this issue which can help you find the proble: https://github.com/git-lfs/git-lfs/issues/2898
- @Femme-js after several trials on different servers I have run into a problem due to memory, and I think this can be what is causing you issues as well. 

> > > Hi @sayantani11
> > > That is a very good indication that the problem we are facing is due to the setup on your local machine, if the model runs in colab the packages etc itself are well indicated. Can you paste the log file when you try it on your local machine or point me to the issue where it is?
> > 
> > 
> > I did upload the log file, guess there were some errors while uploading Here it is: [eos2thm.txt](https://github.com/ersilia-os/ersilia/files/9824317/eos2thm.txt)
> 
> Thanks I can see it now! Seems like the Git LFS error is persisting @sayantani11 ! let's try to solve this When you run git-lfs --help (or any other git lfs command, I am not sure which ones are available) inside ersilia's conda environment, do you get the correct output?

-Hi@sayantani11,
We are creating an informative error for when Git LFS is not properly installed (see issue #277 ) but let's try to solve it for you meanwhile. I am suspecting you might have tried installing the windows version of git in your linux wsl. See this issue which can help you find the proble: https://github.com/git-lfs/git-lfs/issues/2898

**Comment by GemmaTuron** [comment]
@Femme-js still working on the model to identify what is going wrong.
The warning for chardet urllib is in #408 but that is not the root of the problem

Seems a memory error. Can you run `ulimit` on your bash and let me know your memory limit?

**Comment by sayantani11** [comment]
> > Thanks I can see it now! Seems like the Git LFS error is persisting @sayantani11 ! let's try to solve this When you run git-lfs --help (or any other git lfs command, I am not sure which ones are available) inside ersilia's conda environment, do you get the correct output?
> 
> Hi @sayantani11, We are creating an informative error for when Git LFS is not properly installed (see issue #277 ) but let's try to solve it for you meanwhile. I am suspecting you might have tried installing the windows version of git in your linux wsl. See this issue which can help you find the problem: [git-lfs/git-lfs#2898](https://github.com/git-lfs/git-lfs/issues/2898)

when i do `git-lfs` it shows all the available commands.. and works fine

**Comment by GemmaTuron** [comment]
Hi @sayantani11 !
This is annoying but is clear from the log error pasted above and in the issue #369 that ersilia is unable to find the git-lfs. Can you try once again the following as suggested in the issue above? Make sure you are inside the WLS:
(from: https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu):
`curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
`sudo apt-get install git-lfs`
`git lfs install`

After that, reboot the system, fetch the model and paste the log here, hopefully it will not have the git-lfs command error anymore!

**Comment by Zainab-ik** [comment]
> Hi @sayantani11 ! This is annoying but is clear from the log error pasted above and in the issue #369 that ersilia is unable to find the git-lfs. Can you try once again the following as suggested in the issue above? Make sure you are inside the WLS: (from: https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu): `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash` `sudo apt-get install git-lfs` `git lfs install`
> 
> After that, reboot the system, fetch the model and paste the log here, hopefully it will not have the git-lfs command error anymore!

In relation to this, inside your WSL, activate your ersilia environment and do the installation there, also initialize in the ersilia environment. 
Then reboot your system and follow @GemmaTuron suggestion.

**Comment by sayantani11** [comment]
> Hi @sayantani11 ! This is annoying but is clear from the log error pasted above and in the issue #369 that ersilia is unable to find the git-lfs. Can you try once again the following as suggested in the issue above? Make sure you are inside the WLS: (from: https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu): `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash` `sudo apt-get install git-lfs` `git lfs install`
> 
> After that, reboot the system, fetch the model and paste the log here, hopefully it will not have the git-lfs command error anymore!

So I did all the above suggested solutions but the fetch still failed -
[eos2thm.txt](https://github.com/ersilia-os/ersilia/files/9847613/eos2thm.txt)

**Comment by GemmaTuron** [comment]
Hi @Femme-js , I am assigning this one to you as well to work together with #338

**Comment by GemmaTuron** [comment]
This has been solved by @HellenNamulinda
