### ISSUE TITLE
🐛 Bug: eoseos526j - Colab - not predict. System crashes.

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#392]
### Describe the bug.

When I trying to make the prediction in google colab of the eos526j model. This took approximately 5 hours until the system collapsed and locked up. In other words, it stayed in an infinite loop and the prediction did not return any results.

I changed the input to a single molecule:  `smiles = "CC(=O)Nc1nnc(S(N)(=O)=O)s1"`  but that throws me the following error: 
TypeError: 'NoneType' object is not subscriptable

![imagen](https://user-images.githubusercontent.com/17841081/196841391-73b46607-3820-4126-a21d-cad4df47f6e9.png)

I share my link: 
https://colab.research.google.com/drive/1XqeFJt0Vu-SdwxRPqS_6b17FWh3y66n_#scrollTo=VjHC0EuxXL86

### Describe the steps to reproduce the behavior

Predict APi on the eos526j model. for a single molecule of acetazolamide.

### Operating environment

Ubuntu 20.04.3 LTS

**Comment by GemmaTuron** [comment]
thanks @carcablop !

There is an issue with the input adapter for this model clearly, see #377 . We will tackle soon hopefully, I am going to close this issue to avoid duplication of information. Mark it in purple on excel please.

**Comment by carcablop** [comment]
Thanks @GemmaTuron. I'll check out #377.
