### ISSUE TITLE
🐛 Bug: Docker for Windows error: "Hardware assisted virtualization and data execution protection must be enabled in the BIOS"

### ISSUE THREAD

**Issue by Ng-ethe** [ersilia-os/ersilia#393]
### Describe the bug.

[Docker for Windows error: "Hardware assisted virtualization and data execution protection must be enabled in the BIOS"]

### Describe the steps to reproduce the behavior

I installed Docker as per the instructions in the Ersilia workbook. I choose the option to use it with WSL instead of Hyper-V. However, after launching Docker it gives that error. I've tried some recommendations given on StackOverflow described below:

[](https://stackoverflow.com/questions/39684974/docker-for-windows-error-hardware-assisted-virtualization-and-data-execution-p)

1. SOLUTION A (If Hyper-V is totally disabled or not installed)

  Open PowerShell as administrator and
  
  Enable Hyper-V with
  
  `dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All`

3. SOLUTION B (If Hyper-V feature is already enabled but doesn't work)

  Enable Hypervisor with
  
  `bcdedit /set hypervisorlaunchtype auto`
  
  Now restart the system and try again.

3. SOLUTION C

  If the problem persists, probably Hyper-V on your system is corrupted, so
  
  Go in Control Panel -> [Programs] -> [Windows Features] and completely uncheck all Hyper-V related components. Restart the system.
  
  Enable Hyper-V again. Restart.

4. Open PowerShell as administrator or CMD prompt as administrator

    Run this command in PowerShell-> `bcdedit /set hypervisorlaunchtype auto`
    
    Now restart the system and try again.

### Screenshots.

![image](https://user-images.githubusercontent.com/58877986/196846017-dcad5d58-23a6-4ec3-9616-a157b13b57fe.png)

### Operating environment

windows 10

**Comment by Zainab-ik** [comment]
@Ng-ethe installing docker is not a necessary prerequisites for running your models. However, if you want to install, enable WSL from power shell by using `WSL`, it simply enables it. Also, it's just `pip install docker`, you need not yet it running.
I believe @GemmaTuron can provide a more better explanation.

**Comment by Zainab-ik** [comment]
Also, kindly edit your title name to include the error you encounter so others can assist.

**Comment by GemmaTuron** [comment]
Hi @Ng-ethe !

Thanks for such detailed explanations, it really helps. I am unsure about whether you are installing docker IN your WSL only or in your windows system. @Zainab-ik suggestion seems a good try!
Also, Docker is currently not required to run ersilia (will be in the future ;) ) so you can skip this step if it's giving you trouble.

**Comment by Ng-ethe** [comment]
> Also, kindly edit your title name to include the error you encounter so others can assist.

Okay, done.

**Comment by Ng-ethe** [comment]
> pip install docker


This worked thank you.
