### ISSUE TITLE
🐛 Bug: Unable to predict eos9ei3 due to OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by ting96haha** [ersilia-os/ersilia#394]
### Describe the bug.

The model "eos9ei3" is unable to be predicted successfully due to OSError: Unable to open file (file signature not found). I had searched the error online and this error message probably suggests the file is either corrupted or not in the HDF5 format. 

### Describe the steps to reproduce the behavior

The error occurs in the `ersilia -v api predict -i "eml_canonical.csv" -o "eos9ei3.csv" > error.log 2>&1` command line.

### Expected behavior.

Successfully predict the model

### Screenshots.

![error_h51](https://user-images.githubusercontent.com/45352206/196851494-79d3eda5-0e06-400e-a760-77a7e2562381.png)

### Operating environment

Arch Linux 

### Additional context

Please look at the log file for further information. 
[error.log](https://github.com/ersilia-os/ersilia/files/9826058/error.log)

**Comment by Zainab-ik** [comment]
@ting96haha I suggest you check if you have the input file in the same directory you are working and if the input file is the correct one.

**Comment by ting96haha** [comment]
> @ting96haha I suggest you check if you have the input file in the same directory you are working and if the input file is the correct one.

Yes, I confirmed it is in the same directory. I tested with the other models and they worked perfectly.

**Comment by GemmaTuron** [comment]
Hi @ting96haha !

Thanks, can I ask you to do a check?
There is a command that will generate, in principle, an example input file for the model. This is still work in process, but it's worth a try in this case.
That command will give you an example file that you can then use to check the input format and also use it with the predict command to see it it runs ;)

`ersilia example eos9ei3 -n 10 -f myexample.csv`  -- will give you 10 molecules as example in the "right" format

**Comment by ting96haha** [comment]
> Hi @ting96haha !
> 
> Thanks, can I ask you to do a check? There is a command that will generate, in principle, an example input file for the model. This is still work in process, but it's worth a try in this case. That command will give you an example file that you can then use to check the input format and also use it with the predict command to see if it runs ;)
> 
> `ersilia example eos9ei3 -n 10 -f myexample.csv` -- will give you 10 molecules as example in the "right" format

Hi @GemmaTuron, thank you for the advice. I used the example file from the `ersilia example eos9ei3 -n 10 -f myexample.csv` , and it provides me the example file as follows. It can generate 10 molecules as the input example. 

[myexample.csv](https://github.com/ersilia-os/ersilia/files/9829064/myexample.csv)

After that, I used the example file as the input file through this command line `ersilia -v api predict -i "myexample.csv" -o "eos9ei3.csv" > example_error.log 2>&1` and it produces the error file in the attachment below (example_error.log): 

[example_error.log](https://github.com/ersilia-os/ersilia/files/9829086/example_error.log)

If I check with single molecule (the first entry in the myexample.csv file) from the example file with the command line `ersilia -v api predict -i "NCCNS(=O)(=O)c1ccc(Cl)c2ccncc12" -o "eos9ei3.csv" > example_error2.log 2>&1`, the corresponding output error file is provided in the attachment below (example_error2.log):

[example_error2.log](https://github.com/ersilia-os/ersilia/files/9829172/example_error2.log)

The error message looks similar as previous approach, which is OSError: Unable to open file (file signature not found). Is there any other way to troubleshoot the model? Thanks for providing me this useful information and I really appreciate it.

**Comment by ting96haha** [comment]
> Thanks @ting96haha very detailed! I think this model is requiring only .h5 files, which is a format used to store large data... but difficult to read by a human, so we need to improve the input adapter for this... I'm gonna mark it for further checking, you can mark it in purple on excel!

Thank you for the clarification! I will mark it in purple on excel.

**Comment by GemmaTuron** [comment]
Update:

I am able to fetch and run predictions for eos9ei3 when I use a single molecule as input: `ersilia -v api predict -i "CCCC"`, getting the following output: 
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "outcome": [
            1.605723
        ]
    }
}

Passing a .csv file with a list of SMILES works as well, but when I try to pass a list of molecules directly the model cannot process them `ersilia -v api predict -i ["CCCC","C
[eos9ei3_list.txt](https://github.com/ersilia-os/ersilia/files/10217548/eos9ei3_list.txt)
CCOC"]`

**Comment by pauline-banye** [comment]
Operating system - WSL on windows 10  
Conda version - conda 4.12.0
Python version - Python 3.7.13

Model predicted successfully
Link to [colab](https://colab.research.google.com/drive/1zcCqLGMA9J6Ak3dZm1ir5F1zZ5XSahd0#scrollTo=1cg9EqzVnJSs)
Link to [eos9ei3_output.csv](https://github.com/ersilia-os/ersilia/files/10233268/eos9ei3_output.csv)

**Comment by GemmaTuron** [comment]
Hi @pauline-banye !

I am reopening this issue because I am unsure if you tried to pass a .csv file (which also worked for me) or a list of smiles (which did not). Can you clarify? Something like: `ersilia -v api predict -i ["CCCC","CCCOC"]`

**Comment by pauline-banye** [comment]
> Hi @pauline-banye !
> 
> I am reopening this issue because I am unsure if you tried to pass a .csv file (which also worked for me) or a list of smiles (which did not). Can you clarify? Something like: `ersilia -v api predict -i ["CCCC","CCCOC"]`

Hi @GemmaTuron, good morning from Nigeria, I passed the eml_canonical.csv file.

This is the code I ran to predict the model. `ersilia -v api predict -i "eml_canonical.csv" -o "eos9ei3.csv" > eos9ei3-CLI.log 2>&1`. 

I was able to fetch, serve and predict successfully in both Colab and the CLI. Would you like me to test it with a list of smiles?

**Comment by GemmaTuron** [comment]
yes please ;)

**Comment by pauline-banye** [comment]
> yes please ;)

Sure, I'm on it!  @GemmaTuron

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, I was able to predict successfully by passing a list of smiles as well. I tested it with `['CCCC', 'CCCOC']` and the first 3 smiles from the eml_canonical.csv.

[eos9ei3_smile-list.csv](https://github.com/ersilia-os/ersilia/files/10235238/eos9ei3_smile-list.csv)
[eos9ei3_list.csv](https://github.com/ersilia-os/ersilia/files/10235240/eos9ei3_list.csv)

**Comment by GemmaTuron** [comment]
oh this is great work thanks @pauline-banye ! 
Definitely we need to improve the input adapters for the CLI. The google colab command `model.api()` runs on the python package version of Ersilia which might differ a bit from what is used in the CLI.
Can you share the link to the file you are looking at for the ersilia API?

Thanks

**Comment by pauline-banye** [comment]
> oh this is great work thanks @pauline-banye ! Definitely we need to improve the input adapters for the CLI. The google colab command `model.api()` runs on the python package version of Ersilia which might differ a bit from what is used in the CLI. Can you share the link to the file you are looking at for the ersilia API?
> 
> Thanks

@GemmaTuron I'm so sorry but I have been searching for the file and I can't seem to find it anywhere 🤦‍♀️. I can't remember if it was from a file or an error from Colab/the CLI. I would try to replicate it and would provide an update if or when I can.

**Comment by GemmaTuron** [comment]
Hello @miquelduranfrigola 

As you mentioned in our last meeting, using the instructions provided in https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/inputs we cannot pass a list of smiles on the CLI, so if the only way to predict more than one molecule is by inputing a .csv file we should make this clear in the documentation.

**Comment by GemmaTuron** [comment]
This model is working - see its github actions run and the model testing on https://github.com/ersilia-os/eos9ei3/issues/6
