### ISSUE TITLE
🐛 Bug: Failed to fetch model "eos2lm8" due to "Model API eos2lm8:predict did not produce an output"

### ISSUE THREAD

**Issue by ting96haha** [ersilia-os/ersilia#400]
### Describe the bug.

The model cannot be fetched successfully due to empty output error. The error message while fetching the model is "Model API eos2lm8:predict did not produce an output" 

### Describe the steps to reproduce the behavior

The error occurs in the `ersilia -v fetch eos2lm8 > eos2lm8_fetch.log 2>&1` command line.

### Expected behavior.

Successfully fetch the model 

### Screenshots.

![error_eos2lm8](https://user-images.githubusercontent.com/45352206/196997812-ee7cb6f8-50cb-49ab-b522-53ab0b07f9e2.png)

### Operating environment

Arch Linux

### Additional context

Please refer to the log file for  detailed information 
[eos2lm8_fetch.log](https://github.com/ersilia-os/ersilia/files/9831755/eos2lm8_fetch.log)

**Comment by ting96haha** [comment]
> 

Hi, @GemmaTuron, although the model cannot be fetched in local machine, I successfully fetched and predict on the Google Colab. Would you guide me through the reason behind this phenomena? Many thanks

**Comment by GemmaTuron** [comment]
If it works in Google Colab but not on your local system it points at a problem in your set up
In this case, I see on line 18 the error:
23:33:26 | DEBUG    | Cloning from github to /home/ting/eos/dest/eos2lm8
Skipping object checkout, Git LFS is not installed.

You need Git Large File Storage as explained in the prerequisites for ersilia, make sure it is recognized in your system (usually requires a reboot after installation)

**Comment by ting96haha** [comment]
> If it works in Google Colab but not on your local system it points at a problem in your set up In this case, I see on line 18 the error: 23:33:26 | DEBUG | Cloning from github to /home/ting/eos/dest/eos2lm8 Skipping object checkout, Git LFS is not installed.
> 
> You need Git Large File Storage as explained in the prerequisites for ersilia, make sure it is recognized in your system (usually requires a reboot after installation)

Thank you very much. I had reinstall the Git Large File Storage again for ersilia. After that, I can fetch the model within 3 mins. Thank you for your help.
