### ISSUE TITLE
🐛 Bug: Model eos9be7 - ERROR: Cannot install fcd==1.0 and fcd==1.1 

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#401]
### Describe the bug.

I successfully installed ersilia until I encountered these errors when running the eos9be7 model.
On `ersilia -v fetch eos9be7` I got warnings and error:
`ERROR: Cannot install fcd==1.0 and fcd==1.1 because these package versions have conflicting dependencies.`

### Describe the steps to reproduce the behavior

1. conda activate ersilia
2.  ersilia -v fetch eos9be7   
Error:

### Expected behavior.

Fetch the model.

### Screenshots.

<img width="983" alt="Captura de Tela 2022-10-20 às 09 25 04" src="https://user-images.githubusercontent.com/95102911/197015209-47a8b296-7ab0-48e5-9254-85cc6882a65d.png">

### Operating environment

MacOS M1

### Additional context

All steps of Ersilia Model Hub installed.

**Comment by GemmaTuron** [comment]
I'm going to close
#401, #402 #403 and keep the conversation only in #404. Please add all the info including log files there (conda version, pip version etc)
