### ISSUE TITLE
🐛 Bug: Model eos9be7 - ASM Builds for BoringSSL currently not supported on: macosx-11.1-arm64

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#402]
### Describe the bug.

I successfully installed ersilia until I encountered these errors when running the eos9be7 model.
On` ersilia -v fetch eos9be7` I got warnings and error:
```
error: subprocess-exited-with-error
python setup.py bdist_wheel did not run successfully.
exit code: 1
[5263 lines of output]
ASM Builds for BoringSSL currently not supported on: macosx-11.1-arm64
```

### Describe the steps to reproduce the behavior

1. conda activate ersilia
2. ersilia -v fetch eos9be7
Error:

### Expected behavior.

Fetch the model.

### Screenshots.

<img width="590" alt="Captura de Tela 2022-10-20 às 09 25 26" src="https://user-images.githubusercontent.com/95102911/197018069-e35e5928-7454-4fa4-a7ab-ec487743b32c.png">

### Operating environment

MacOS M1

### Additional context

All steps of Ersilia Model Hub installed.

**Comment by GemmaTuron** [comment]
Hi @natividadesusana 

Same as for #403 and #404 I am not sure if you get different errors after trying different things or is all the same error.

**Comment by natividadesusana** [comment]
Right!!
Thank you!!
