### ISSUE TITLE
🐛 Bug: Model eos9be7 - error: legacy-install-failure

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#403]
### Describe the bug.

I successfully installed ersilia until I encountered these errors when running the eos9be7 model.
On `ersilia -v fetch eos9be7` I got warnings and error:
```
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
x Encountered error while trying to install package.
-> grpcio
note:
This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

### Describe the steps to reproduce the behavior

1. conda activate ersilia
2. ersilia -v fetch eos9be7
Error:

### Expected behavior.

Fetch the model.

### Screenshots.

<img width="683" alt="Captura de Tela 2022-10-20 às 09 26 41" src="https://user-images.githubusercontent.com/95102911/197022679-b5704d6e-1d9d-498d-880e-e7f7dc53fc32.png">

### Operating environment

MacOS M1

### Additional context

All steps of Ersilia Model Hub installed.

**Comment by GemmaTuron** [comment]
Hi @natividadesusana is this related to #404 as well? when do you get one or the other error? I'd like to close one of the two issues to avoid duplicating information
Please add the log files.
Thanks!

**Comment by natividadesusana** [comment]
Right!!
Thank you!!
