### ISSUE TITLE
🐛 Bug:  Model eos4e41 - ERROR: No matching distribution found for scikit-learn==0.22.2

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#405]
### Describe the bug.

I successfully installed ersilia until I encountered these errors when running the eos9be7 model.
On `ersilia -v fetch eos4e41` I got warnings and error:
```
ERROR: Could not find a version that satisfies the requirement scikit-learn==0.22.2 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.1.0rc1, 1.1.0, 1.1.1, 1.1.2)
ERROR: No matching distribution found for scikit-learn==0.22.2
```

### Describe the steps to reproduce the behavior

1. `conda activate ersilia`
1. `ersilia -v fetch eos4e41`
Error:

### Expected behavior.

Fetch the model.

### Screenshots.

<img width="879" alt="Captura de Tela 2022-10-20 às 16 45 04" src="https://user-images.githubusercontent.com/95102911/197044330-621f6105-a3ac-4c09-9a26-9a4bc4258b0e.png">

### Operating environment

MacOS M1

### Additional context

All steps of Ersilia Model Hub successfully installed.

**Comment by Zainab-ik** [comment]
@natividadesusana There are 2 instances for this error, either an internet connection or a pip package needs updating. I suggest you rerun the process all over again in a new terminal and check your pip version using `pip --version`.
i believe @GemmaTuron can do justice to the issue

**Comment by GemmaTuron** [comment]
Hi @natividadesusana 

I need the full log of the error to be able to provide support. Thanks

**Comment by ZakiaYahya** [comment]
@natividadesusana if get the pip version error too along with this error then follow thw folllowing steps,
Do this inside the ersilia environment,
sudo apt-get update
sudo apt-get upgrade
sudo apt install python3-pip
pip3 --version after that deactivate the ersilia conda environment &
rerun the terminal.
I hope this works for u too.

**Comment by GemmaTuron** [comment]
Hi @natividadesusana,

I see in issue #411 that you have trouble in ersilia's installation itself, so I'm gonna close this issue until #411 is solved and then we can go onto testing models
