### ISSUE TITLE
🐛 Bug: Colab_model eos2b6f  prediction no output

### ISSUE THREAD

**Issue by RoseZhen2022** [ersilia-os/ersilia#406]
### Describe the bug.

It can be fetched successfully. When doing prediction, it just keep running till time out. Then I need to fetch it again and do the prediction and still keep running. I couldn't get any error message, it seems the prediction didn't finish.

### Describe the steps to reproduce the behavior

1. !ersilia -v fetch eos2b6f
2. model = ErsiliaModel("eos2b6f")
3. model.serve()
4. output = model.predict(input=smiles, output="pandas")

### Expected behavior.

predict successfuly

### Screenshots.

![model eos2bof_colab](https://user-images.githubusercontent.com/115380880/197048830-a4139716-487e-460e-a2c0-0ed7398d1d41.png)

### Operating environment

google colab

### Additional context

In my local environment, it can be fetched and predicted successfully. But the prediction needs very long time, more than 6 hours.

**Comment by RoseZhen2022** [comment]
As someone kindly suggested in the Slack, I changed the input to a single molecule, it can be predicted successfully. I have no idea how to do next.

**Comment by GemmaTuron** [comment]
Hi  @RoseZhen2022 !

If the model can predict one molecule it simply means it needs time to do all of them, so don't worry
I am closing this as solved and you can mark in excel that the model works
