### ISSUE TITLE
🐛 Bug: getting error while  running "sudo apt install build-essential" on ubuntu on windows 

### ISSUE THREAD

**Issue by PranjuP** [ersilia-os/ersilia#407]
### Describe the bug.

getting error while  running "sudo apt install build-essential" on ubuntu on windows, it is failing with error code 404 with the following error statement "E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-100.113_amd64.deb  404  Not Found [IP: 91.189.91.38 80]"
Here is a snap of the error window:
[
![bug](https://user-images.githubusercontent.com/98308195/197096009-fe3077eb-9a82-4859-b99f-f039e6ea6068.PNG)
](url)

### Describe the steps to reproduce the behavior

1. to run "sudo apt install build-essential" on ubuntu on windows

### Expected behavior.

it should install successfully

### Screenshots.

![image](https://user-images.githubusercontent.com/98308195/197096149-1a3d2786-f2a8-43a2-bde8-b81757d555a4.png)

### Operating environment

	Microsoft Windows 10 Home Single Language(Version	-10.0.19042 Build 19042
)

**Comment by Zainab-ik** [comment]
I presume you are trying to download the GCC Compiler which gave you an error, make sure to enable WSL in your PowerShell to be sure you are running it in the correct terminal. However, I believe you can proceed with other steps.

**Comment by Malikbadmus** [comment]
Hello @PranjuP, @Zheeburg suggested a solution to your issue, so basically check that your system clock is in sync with your host environment.
you can find more about this here.

https://github.com/ersilia-os/ersilia/issues/359#issuecomment-1286572578

**Comment by GemmaTuron** [comment]
Hi @PranjuP, 
I'm sorry this is related to installing ubuntu, not to Ersilia's specific installation so I can't provide much support. Please check the suggestions above and see if you can get over it.
