### ISSUE TITLE
🐛 Bug: Unable to predict eos2lm8 due to Index Error: list index out of range 

### ISSUE THREAD

**Issue by ting96haha** [ersilia-os/ersilia#409]
### Describe the bug.

The model "eos2lm8" is unable to be predicted successfully due to Index Error: list index out of range from the api.py file. 

### Describe the steps to reproduce the behavior

The error occurs in the `ersilia -v api predict -i "eml_canonical.csv" -o "eos2lm8.csv" > error_eos2lm8.log 2>&1` command line.

### Expected behavior.

Successfully predicted with the model eos2lm8

### Screenshots.

![error_msg_eos2lm8](https://user-images.githubusercontent.com/45352206/197199565-7b3dc8b8-54cd-4e22-a533-21b344cfb688.png)

### Operating environment

Arch Linux

### Additional context

I had tried the method that you suggested in Issue #394, to generate 10 molecules as example in the "right" format as the input file but I got the same error as Index Error: list index out of range as the attachment below. 

[error_eos2lm8.log](https://github.com/ersilia-os/ersilia/files/9839021/error_eos2lm8.log)

**Comment by GemmaTuron** [comment]
Thanks @ting96haha !

Can you check what is the output that you get when you run the following command?
`ersilia example molecular-weight -n 10 -f myexample.csv`

This will generate an example file that you can pass as input. Paste the file here as well so we can see what is the exact input (this command is work in progress, so might not work for some models, let's try)

**Comment by ting96haha** [comment]
> Thanks @ting96haha !
> 
> Can you check what is the output that you get when you run the following command? `ersilia example molecular-weight -n 10 -f myexample.csv`
> 
> This will generate an example file that you can pass as input. Paste the file here as well so we can see what is the exact input (this command is work in progress, so might not work for some models, let's try)

Hi, @GemmaTuron , this is the output file of the example, from `ersilia example molecular-weight -n 10 -f myexample.csv` 
[myexample.csv](https://github.com/ersilia-os/ersilia/files/9860616/myexample.csv)

After I obtain the example file, I tried to run it with the command line `ersilia -v api predict -i "myexample.csv" -o "eos2lm8.csv" > error_eos2lm8_10_25Oct.log 2>&1` The output error log file is shown as attachment below which have the same error message as the initial approach that use "eml_canonical.csv" as input file: 
[error_eos2lm8_10_25Oct.log](https://github.com/ersilia-os/ersilia/files/9860620/error_eos2lm8_10_25Oct.log)

However, if I tried it with single molecule from the myexample.csv file with the command line: `ersilia -v api predict -i "CCOCCn1c(nc2ccccc12)C1CCN(CCc2ccc(cc2)C(C)(C)C(O)=O)CC1" -o "eos2lm8_25Oct.csv" > eos2lm8.log 2>&1` it successfully predicted and produced an output file as follows: 
[eos2lm8_25Oct.csv](https://github.com/ersilia-os/ersilia/files/9860661/eos2lm8_25Oct.csv)

The corresponding log file from the command `ersilia -v api predict -i "CCOCCn1c(nc2ccccc12)C1CCN(CCc2ccc(cc2)C(C)(C)C(O)=O)CC1" -o "eos2lm8_25Oct.csv" > eos2lm8.log 2>&1` is attached here too for further investigation: 
[eos2lm8.log](https://github.com/ersilia-os/ersilia/files/9860717/eos2lm8.log)

I am not sure why it can work with single molecule but cannot work with more molecules. May I know is there any other ways to test this models' predict function?

**Comment by GemmaTuron** [comment]
Hi @ting96haha !

Thanks for checking all this. It is due to the input adapter format for the model, I'll need to check it and make the necessary adaptors.. for the moment mark it in purple in the excel and change the issue title to "eos2lm8: input adapter for lists"

**Comment by ting96haha** [comment]
> Hi @ting96haha !
> 
> Thanks for checking all this. It is due to the input adapter format for the model, I'll need to check it and make the necessary adaptors.. for the moment mark it in purple in the excel and change the issue title to "eos2lm8: input adapter for lists"

sure, no problem. I shall mark it in purple now

**Comment by GemmaTuron** [comment]
Update on this model:

At prediction time, it is not able to accept a smiles input, with the following errors:
`ersilia -v api predict -i "CCC","CCNC"`
[eos2lm8_list.txt](https://github.com/ersilia-os/ersilia/files/10217385/eos2lm8_list.txt)

When I pass a single molecule instead of a list
`ersilia -v api predict -i "CCCC"`
[eos2lm8_single.txt](https://github.com/ersilia-os/ersilia/files/10217380/eos2lm8_single.txt)

@miquelduranfrigola you incorporated this model, do you have an idea of what might be the source of this error?

**Comment by GemmaTuron** [comment]
This has been solved by @pittmanriley !
