### ISSUE TITLE
📑 Feature Request: Improving issues with Ersilia's current readme.md file. 

### ISSUE THREAD

**Issue by Femme-js** [ersilia-os/ersilia#410]
### Is your feature request related to a problem? Please describe.

While exploring the github repository of Ersilia and going through the readme.md, I found that Table of Contents have second content as 'Installation' but later in the file, the heading of content is replaced by 'Quick Start Guide'. Neither it is linked to the content under 'Table of Contents:' heading. 

### Describe the solution you'd like.

Fixing the link under Table of Contens in readme file.

**Comment by GemmaTuron** [comment]
Hi @Femme-js !
Good catch, can you directly create a PR solving this?
Thanks
