### ISSUE TITLE
 🐛 Bug: eos9be7 input data error

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#411]
### Describe the bug.

I'm getting an error when trying to install ersilia model hub:

Error: bentoml 0.11.0 has requirement urllib3<=1.25.11, but you'll have urllib3 1.26.12 which is incompatible.

### Describe the steps to reproduce the behavior

1. sh  /Users/natividadesusana/Downloads/Miniforge3-MacOSX-arm64.sh 
2. conda activate base
3. conda create --name ersilia
4. conda activate ersilia
5. git clone https://github.com/ersilia-os/ersilia.git
6. cd ersilia
7. pip3 install -e .
8. ersilia --help

### Expected behavior.

see ersilia CLI options.

### Screenshots.

<img width="793" alt="Captura de Tela 2022-10-21 às 19 44 23" src="https://user-images.githubusercontent.com/95102911/197301885-fe71b474-8f1d-4bf2-8a0e-3a089eb72a10.png">

<img width="790" alt="Captura de Tela 2022-10-21 às 19 43 50" src="https://user-images.githubusercontent.com/95102911/197301522-006e68c7-d5a4-485d-b071-07de6ca4562f.png">

### Operating environment

MacOS 2016, Intel Core i5

**Comment by GemmaTuron** [comment]
Hi @natividadesusana 

LEt's see if we can resolve this. I'd suggest:
- Update pip and conda
- Delete ersilia's environment and create it anew specifying **the python version**
See it this solves the issue!

**Comment by natividadesusana** [comment]
Hi @GemmaTuron I'm happy to say the installation is now successful. Thank you so much for your attention!!

I proceeded to the next steps running ersilia serve and then ersilia api calculate but then I have a problem, could you please help me?
Attached are the steps I took.

![2](https://user-images.githubusercontent.com/95102911/197419713-875b1299-de18-44f3-88b0-be7610691aff.jpeg)

![1 (1)](https://user-images.githubusercontent.com/95102911/197419651-17a9c860-346c-4d35-b9b7-06944ff47217.jpeg)


I'm getting this error when running `ersilia -v api calculate -i "CCCC`" or `ersilia -v api calculate -i "chemnet-distance.csv" -o "eos9be7.csv" > error.log 2>&1`
Could you please help me? Thank you!

![1](https://user-images.githubusercontent.com/95102911/197419604-c960c921-af48-4796-9f48-916c8e56fca2.jpeg)

[ersilia-output.txt](https://github.com/ersilia-os/ersilia/files/9847596/ersilia-output.txt)

**Comment by GemmaTuron** [comment]
Thanks @natividadesusana !

3 things to do next:
1. Update your urllib3, chardet and charset_normalizer as explained in #408 to eliminate the error
2. Try the predict with a list of molecules, as you can see you have what is called an Assertion Error, which tries to make sure the input is in the right format, in this case, `assert type(data) is list`. So you can try to pass -i ["CCCCC", "CCCCNOC"] ans let's see what happens. Do not fetch the model again, but you probably need to serve it again.
3. Change the title of the issue to something more informative, like "eos9be7 input data error"

Thanks!

**Comment by natividadesusana** [comment]
Hi @GemmaTuron, thank you so much for your help, I was able to fix all the bugs!
Then I served the model and then tried the prediction by running `ersilia api predict -i ["CCCCC", "CCCCNOC"]` and I got this:


![2a452e49-cad5-4c3f-9cf4-b126f9901739](https://user-images.githubusercontent.com/95102911/197625080-826c94d0-c07b-4102-894f-305a140749f1.jpg)

**Comment by GemmaTuron** [comment]
Hi @natividadesusana great that you are able to run the models
In the bash command we need to pass the string, so actually the input format should be:
`-i "['CCCC', 'CCCCNOC']"`
Let's try that!

**Comment by GemmaTuron** [comment]
and please change the title of the issue so that is more informative

**Comment by natividadesusana** [comment]
Hi @GemmaTuron ,

If I try `ersilia api predict -i "['CCCCC', 'CCCCNOC']"` or `ersilia api predict -i "['CCCC', 'CCCCNOC']"` I have a problem:

![511ead6f-079b-490e-9ea2-03b38bb88f16](https://user-images.githubusercontent.com/95102911/197787009-bafa205a-34ff-4c49-96ff-d41c216d7268.jpg)

**Comment by natividadesusana** [comment]
Hi @GemmaTuron, thank you so much!
Do I need to follow any more steps for this model? Or do I keep testing the other models now?
Mark with purple to close the issue right?

**Comment by GemmaTuron** [comment]
Hi @natividadesusana,

I am leaving this issue open so we can work on the input adapters. You should mark it in purple and explain the issue on excel.

**Comment by natividadesusana** [comment]
Okay thanks @GemmaTuron!

**Comment by GemmaTuron** [comment]
update on this model:

The API is calculate, so command should be run as:
`ersilia -v api calculate -i TEXT`

the TEXT is a list of lists according to the service file (https://github.com/ersilia-os/eos9be7/blob/main/src/service.py) but when I try any variation of list of lists with molecule pairs, for example:
`ersilia -v api calculate -i  [[CCCC,CCOC],[CCNC, CCOCC]]`
I get the error:
`Error: Got unexpected extra argument (CCOCC]])`

@brosular incorporated this model but it should have added proper documentation for its use. On the README file I can only see the following:
_Input: A pair of SMILES lists. Ideally, one list represents training data and the other list represents a generated_ (nothing else here...)

**Comment by DhanshreeA** [comment]
@GemmaTuron are we waiting for @brosular to rectify this or this model fix up for grabs?

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA !
If you have a suggestion of how to tackle this go ahead ;)

**Comment by GemmaTuron** [comment]
This is now solved by @ZakiaYahya !
