### ISSUE TITLE
🐛 Bug: Model eos2mhp

### ISSUE THREAD

**Issue by Dorothy2020** [ersilia-os/ersilia#413]
### Describe the bug.
When I fetched the dummy model eos3b5e, it works fine using the command eos3b5e
But fetching the eos2mhp model using the command ersilia -v fetch eos2mhp I get the following error:
EmptyOutputError

Detailed error:
Model API eos2mhp:predict did not produce an output

Hints:
- Visit the fetch troubleshooting siteI

### Describe the steps to reproduce the behavior

1. After Activating Ersilia with conda activate ersilia
2. Run ersilia fetch eos2mhp and then watch the log

### Screenshots.

[eos2mhp.log](https://github.com/ersilia-os/ersilia/files/9844972/eos2mhp.log)

### Operating environment

Ubuntu 20.04

### Additional context
1. Activated the environment using conda activate ersilia
2. Then fetched the model using the command ersilia -v fetch eos3b5e > my.log 2>&1
3. serve the model using command ersilia serve eos3b5e

Screenshoot for the successfull dummy model
![Screenshot from 2022-10-22 10-43-37](https://user-images.githubusercontent.com/79142184/197356828-b8393427-f198-44c2-8c51-0c4c36d2d39d.png)

**Comment by GemmaTuron** [comment]
Hello @Dorothy2020 ,

Can you please share:
- Conda version
- Pip version
- Python version

And check issue #408 to avoid the warning on the charset normalizer?

**Comment by Dorothy2020** [comment]
> 

@GemmaTuron 
Conda Version:22.9.0
Pip version :pip 22.2.2
Python version :Python 3.7.13

**Comment by GemmaTuron** [comment]
I have temporarily closed down model eos2mhp due to excessive download and fetch trials. Will let you know when we can work on it again!

**Comment by Dorothy2020** [comment]
Okay thank you.
