### ISSUE TITLE
🐛 Bug: EmptyOutPutEror Message during fetching:Model eos2lm8

### ISSUE THREAD

**Issue by Dorothy2020** [ersilia-os/ersilia#415]
### Describe the bug.

Something went wrong with Ersilia...

EmptyOutputError

Error message:
Model API eos2lm8:predict did not produce an output

### Describe the steps to reproduce the behavior

1. Activate ersilia by using command conda activate ersilia
2. Fetch the model using command ersilia -v fetch mode_name

### Screenshots.

![Screenshot from 2022-10-23 18-17-27](https://user-images.githubusercontent.com/79142184/197400342-92f04039-c974-4fd2-8900-a423cde44330.png)

### Operating environment

Ubuntu 20.04

**Comment by GemmaTuron** [comment]
Please see comments on #415 before proceeding.

**Comment by Dorothy2020** [comment]
Thank you @GemmaTuron I'm on it

**Comment by Dorothy2020** [comment]
Hello, @GemmaTuron I have gone through it but no solution yet.

**Comment by GemmaTuron** [comment]
Hi @Dorothy2020 

Without the error log I cant help.

**Comment by Dorothy2020** [comment]
@GemmaTuron  I'm giving you the link for the error log

**Comment by GemmaTuron** [comment]
Hi @Dorothy2020, I'm sorry but I don't see any link, are you adding it in another issue? if so please link it here.

**Comment by GemmaTuron** [comment]
This model has now been tested on Windows and Unix systems without issues so I'll close that
