### ISSUE TITLE
🐛 Bug: Laptop Hangs for a long time  and stops fetching :Model eos9ei3

### ISSUE THREAD

**Issue by Dorothy2020** [ersilia-os/ersilia#416]
### Describe the bug.

1.Laptop hangs for a long time and stops fetching

### Describe the steps to reproduce the behavior

1. Activated ersilia using commnad conda activate ersilia
2. Fetched the model using command ersilia -v fetch eos9ei3

![Screenshot from 2022-10-24 05-45-20](https://user-images.githubusercontent.com/79142184/197443315-fee8a473-b952-4666-98a5-d25a2a20ed7f.png)

### Operating environment

Ubuntu 20.04

**Comment by EstherIdabor** [comment]
Hi @Dorothy2020  any time you open an issue make it as descriptive as possible, so help can be provided adequately. 
For instance you didn't include the step you took before the error happened and what the expected behaviour is and for the error log, you are supposed to attach the file while describing the error and not the path to the file.

**Comment by GemmaTuron** [comment]
Hello @Dorothy2020,

Have you completed the checks before?
ersilia --help

and running eos3b5e

**Comment by Dorothy2020** [comment]
@GemmaTuron yes I did

**Comment by Dorothy2020** [comment]
@GemmaTuron this is the error log file for model eos9ei3 
/home/dorothy/Documents/ersilia/eos9ei3.log

**Comment by GemmaTuron** [comment]
HEllo @Dorothy2020,

The log shows the run has been aborted, which means you stopped it before it could complete...

**Comment by Dorothy2020** [comment]
Let me try it again

**Comment by Dorothy2020** [comment]
@GemmaTuron the model has been fetched successfully
**Steps taken:**
1. Closed all the tabs that were causing the laptop to hang.
2. Activated ersilia environment by using :conda activate ersilia
3. Fetched the model using command :ersilia  -v fetch eos9ei3
4. Serve the model using command:ersilia serve eos9ei3
5. During the fetching time  I found this error : "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 1.4.36 which is incompatible".

**Operating environment**
Ubuntu 20.04.5
conda 22.9.0
Python 3.7.13

![Screenshot from 2022-10-24 17-34-01](https://user-images.githubusercontent.com/79142184/197552287-bd627e3b-2df9-48f1-adb5-0b254195af1b.png)

**Comment by GemmaTuron** [comment]
Hi @Dorothy2020 

Good! If you check down in the log you will see how the system automaticlly updates sqlalchemy after finding the dependency issue.

**Comment by GemmaTuron** [comment]
I will close this issue due to inactivity. 
This is one of the models that appears to have long run times. Perhaps a candidate for distillation?
