### ISSUE TITLE
🐛 Bug: Error while fetching models (eos69p9,eos7pw8,eos3ae6)

### ISSUE THREAD

**Issue by pravina5** [ersilia-os/ersilia#420]
### Describe the bug.

I was to fetch models after the installation of Ersilia. I got some errors related to grpcio build failing and No modules bentoml found. 

Previously I had faced a problem with grpcio package so I downloaded it explicitly using :
```conda install grpcio ```

I have seen that bentoml also exists. Not sure why I am getting No module found. Attaching the log files for better understanding. The Errors are more or less the same in the logs for all the models that I have tried.

[eos7pw8.log](https://github.com/ersilia-os/ersilia/files/9850167/eos7pw8.log)
[eos69p9.log](https://github.com/ersilia-os/ersilia/files/9850168/eos69p9.log)
[eos3ae6.log](https://github.com/ersilia-os/ersilia/files/9850190/eos3ae6.log)

### Describe the steps to reproduce the behavior

I ran these commands to fetch the model :

- ``` cd ersilia```
- ```conda activate ersilia```
- ```ersilia -v fetch modelno > my.log 2>&1```

### Expected behavior.

Successfully fetch model after running command .

### Screenshots.

<img width="1440" alt="Screenshot 2022-10-24 at 12 01 50 AM" src="https://user-images.githubusercontent.com/48323089/197481370-9b3376f6-8f47-4f86-a88c-71b678b8cd1d.png">

<img width="932" alt="Screenshot 2022-10-24 at 12 09 02 AM" src="https://user-images.githubusercontent.com/48323089/197481810-4cb3810b-a555-46bf-a1e3-3f5ea9b53995.png">

### Operating environment

System Version: macOS 12.1 (M1 chip) , Kernel-Version: Darwin 21.2.0

### Additional context

I am using the following versions of the packages :
- conda 22.9.0
- Python 3.8.13
- pip 21.2.4
- Bentoml version 0.11.0

**Comment by GemmaTuron** [comment]
Hello @pravina5 

Have you completed the necessary checks before?
Running ersilia --help and testing the model eos3b5e

**Comment by pravina5** [comment]
Hello Mentor Gemma

I had ran ```ersilia --help ``` and ```ersilia catalog ``` which worked for me . But for Model eos3b5e I got the same errors .

<img width="1437" alt="Screenshot 2022-10-24 at 3 51 15 PM" src="https://user-images.githubusercontent.com/48323089/197505464-af5095bd-a294-467a-90a6-a2c7ece6b061.png">

**Comment by GemmaTuron** [comment]
HEllo @pravina5 ,

I'd ask you to please look at your error files and check other issues that have already been solved, since many of your peers have been doing a lot of progress in the tasks assigned to them.
As you can see if you try to understand the log files, you don't have git lfs installed.
`git: 'lfs' is not a git command. See 'git --help'.`

Make sure you install it appropriately as explained in the requisites to run ersilia before attempting any more models

**Comment by pravina5** [comment]
Thanks Mentor Gemma closing the issue .
