### ISSUE TITLE
🦠 Model Request: Tox21 - NR-ER-LBD

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#424]
### Model Title

Tox21 - NR-ER-LBD (TDC dataset)

### Publication

Hello @Malikbadmus!

As part of your Outreachy contribution, we have assigned you the dataset "Tox21 NR ER LBD" from the Therapeutics Data Commons to try and build a binary classification ML model. 
Please copy the provided Google Colab template and use this issue to provide updates on the progress. We'll value not only being able to build the model but also interpreting its results.

**Comment by Malikbadmus** [comment]
Thank You @GemmaTuron.

**Comment by Malikbadmus** [comment]
I'll be alighting the steps taken to create a predictive model based on the dataset provided.

The steps can be summarized below as:

1. Data Preprocessing
2. Data Analyzing/Visualization
3. Model Training and Validation
4. Model testing

**Comment by Malikbadmus** [comment]
**Data Upload**

Tox21(Toxicology in the 21st century ) contains qualitative toxicity measurements for 7,831 compounds, I'll be working on the NR-ER-LBD which is from the Nuclear Receptor Signaling pathway and is among the 12 assays available in Tox21 Dataset.


The first thing I did in this step is to install the TDC( Therapeutics Data Commons) package, Then I imported Tox21 and retrieve the specific assay that I want to work with.

Then I proceed to split the dataset into three(3), one for training another for validating, and the last one for testing the model, after which the three(3) datasets were saved in my google drive.

**Comment by Malikbadmus** [comment]
**Data Analyzing and Visualizing**

When Building an ML Model, the dataset used is split into three (3) parts. The first dataset is exposed to the model and is used to "Learn" or "Teach" the Model, the other dataset is unexposed to the model and is used to evaluate and test the performance of the model.

The "Tox21 NR ER LBD"  datasets have three variables.

1. Drug-ID
2. Drug
3. Y(Bioactivity)

Datasets from TDC(Therapeutics Data Commons) have already undergone the Data splitting process. When "Tox21 NR ER LBD" was downloaded from their database they were composed of the following.

- Train Datasets:  It comprises 4,868 molecules. 253 of these molecules' bioactivity were active(cardiotoxic) and 4,615 show inactive bioactivity(not cardiotoxic). 
- Validation Datasets: These comprise 696 molecules. 37 shows active bioactivity(cardiotoxic), 659 molecules bioactivity were inactive(not cardiotoxic).
- Test Datasets: There are 1391 molecules in this dataset, 60 show active bioactivity(cardiotoxic), 1,331 molecules bioactivity were inactive(not cardiotoxic).

**Comment by GemmaTuron** [comment]
Great @Malikbadmus,

Please share the link to the notebook when you are ready!

**Comment by Malikbadmus** [comment]
> Great @Malikbadmus,
> 
> Please share the link to the notebook when you are ready!

Many thanks @GemmaTuron. You can find the link below.

https://colab.research.google.com/drive/1ZAKGb2SYzwIsILXDZVFmRCgzNGu3eZSS?usp=sharing

**Comment by Malikbadmus** [comment]
**Data Preprocessing**

The lazy-Qzar package as its name implies simplified most of the steps, we would have gone through in our modeling journey.

The goal of our data is to predict the reactions of molecules when introduced to an infectious agent.

The column named "Y" in our Datasets is our target variable (i.e., the variable which we want to predict), by analyzing our target variable we can see that it has only two possible values, which is 0.0 and 1.0, the resulting prediction problem is therefore a binary classification problem. The remaining features of our Datasets (Drug) will serve as input variables for our model.

**Comment by Malikbadmus** [comment]
### f

**Comment by Malikbadmus** [comment]
___

### Model Testing and Validation


**Model Testing**

The Validate Datasets and Test Datasets were set aside to obtain predictions from our Learning Model, they will also serve as unbiased data, as they were not used in the fitting process and therefore have not been Memorized by the Model.

From this new Data, we Separate our Input Data (Molecules) and the target data to predict (Bioactivity), we then pass the Molecules into the Model to obtain predictions and then compare it with our True value.

The process of comparison and evaluating of Model is called Model Evaluation, and there are several tools both visual and numeric that are available to grade the performance of a Model.


___

### Model Evaluation

**Comment by Malikbadmus** [comment]
@GemmaTuron , the Updated link.

https://colab.research.google.com/drive/1fe_EMFwUwSDOmXLlpnB-7NrNTxt1Hnu0?usp=sharing

**Comment by Malikbadmus** [comment]
###The performance of the Model Evaluation Analysis

**Comment by GemmaTuron** [comment]
Hi @Malikbadmus 

Good start! can you tell me a bit more what do you think about your model performance? If I am a researcher doing experiments n the lab and you hand me these results, would you warn me about anything?

Also, a tip: think about how long are you letting the model train for

**Comment by Malikbadmus** [comment]
Also, please can you expatiate, does the time taken to train a model affects its predictive ability?

**Comment by Malikbadmus** [comment]
@GemmaTuron , I got the analysis of my model evaluation wrong, it has been fixed now, the precision value and recall value have also been correctly calculated.

**Comment by Malikbadmus** [comment]
> Hi @Malikbadmus
> 
> Good start! can you tell me a bit more what do you think about your model performance? If I am a researcher doing experiments n the lab and you hand me these results, would you warn me about anything?
> 
> Also, a tip: think about how long are you letting the model train for

From the Perfomance evaluation of the model, we can be rest assured that when the model Proclaims a Drug as being Toxic, that Drug is definitely Toxic, but the model is also very poor in predicting Drugs that are Toxic.

Also, please can you expatiate, does the time taken to train a model affects its predictive ability?

**Comment by Malikbadmus** [comment]
The AUROC value of 0.63 is low. I'm suspecting that this is because of training my Model on an Imbalanced dataset (6,605 to 350), the model prediction will lean more towards being Nontoxic.

The positive from this is that the model the Model precision is 100%

**Comment by Malikbadmus** [comment]
@GemmaTuron , I retrained my model again on the same Datasets and the result I"m getting are different. Why is that?

https://colab.research.google.com/drive/16fRFdsajWY0xuzsU2ZuEk_JEueGfhqid?usp=sharing#scrollTo=EQPNRJ6YBuKK

**Comment by thormiwa** [comment]
@Malikbadmus It is like that because your model is making different predictions each time it is trained, even when it is trained on the same data set each time.

**Comment by Malikbadmus** [comment]
@thormiwa, why does it do that though? 

The learning algorithm is the same, the dataset the same, no noise or unwanted data was introduced to the Dataset the second time, i just want to understand the underlying reason.

**Comment by Malikbadmus** [comment]
@GemmaTuron, I use the predict function to bypass the for loop I would have needed for the Confusion matrix, Precision and recall value.

I then used the predict_proba to set up my AUROC, i.e. I predicted my Test Data twice.

Would there be any backlash from this?. is it a good practice? I analyzed the value gotten in both cases and they corresponded to each other.

**Comment by thormiwa** [comment]
> @thormiwa, why does it do that though?
> 
> The learning algorithm is the same, the dataset the same, no noise or unwanted data was introduced to the Dataset the second time, i just want to understand the underlying reason.

@Malikbadmus it is training data randomly, It is called stochasticity in Machine learning. it is like when the learning algorithm is run on the same data, it learns a slightly different model. In turn, the model may make slightly different predictions and even sometimes a different AUROC value. I noticed the same case when i trained my model as well.

**Comment by ZakiaYahya** [comment]
@Malikbadmus it's due to the fact that every time we train our model, **it initialize with random weights**, due to which the same model trained on same set of data can produce different results.

**Comment by GemmaTuron** [comment]
> @GemmaTuron, I use the predict function to bypass the for loop I would have needed for the Confusion matrix, Precision and recall value.
> 
> I then used the predict_proba to set up my AUROC, i.e. I predicted my Test Data twice.
> 
> Would there be any backlash from this?. is it a good practice? I analyzed the value gotten in both cases and they corresponded to each other.

Predicting twice with the same model and same data shouldn't be an issue, but good practice is to save your initial prediction and stick to that for the analysis, as for more complex models, for example if you are chaining different models, it can be important.

**Comment by GemmaTuron** [comment]
@Malikbadmus 
I think you did a very good job already, and this issue is ready to be closed when you want. Focus the remaining time in writing your final application, and include this part of your contribution to outreachy!

**Comment by Malikbadmus** [comment]
oh @GemmaTuron , @ZakiaYahya and @thormiwa . Many thanks for this!!. I'm reading up on Random weight Initialization.

I'm really learning a lot from this. Thank you guys!!

**Comment by Malikbadmus** [comment]
> > @GemmaTuron, I use the predict function to bypass the for loop I would have needed for the Confusion matrix, Precision and recall value.
> > I then used the predict_proba to set up my AUROC, i.e. I predicted my Test Data twice.
> > Would there be any backlash from this?. is it a good practice? I analyzed the value gotten in both cases and they corresponded to each other.
> 
> Predicting twice with the same model and same data shouldn't be an issue, but good practice is to save your initial prediction and stick to that for the analysis, as for more complex models, for example if you are chaining different models, it can be important.

Oh..I get it. Thanks!

**Comment by Malikbadmus** [comment]
> @Malikbadmus I think you did a very good job already, and this issue is ready to be closed when you want. Focus the remaining time in writing your final application, and include this part of your contribution to outreachy!

Many thanks @GemmaTuron. This has truly been a very rich learning experience for me. Let me just add a final note on this, and then we can close this issue.

**Comment by Malikbadmus** [comment]
### Conclusion

Training a good AI/ML model will involve trying to achieve balance between Precision and Recall,  a good model should be able to classify your data accurately.

When you have an Imbalanced data set like the ***Tox21 - NR-ER-LBD (TDC dataset)***  that I worked on. One of the method you can consider is reducing your threshold.

when I reduced my threshold to ***0.3***, and I was able to get a recall value of  close to ***46%*** up from the ***7%*** I got earlier, but it was a trade-off with my precision as it went down to 67% from 100%.

And even though ML Models cannot make perfect prediction, a Model that is able to identify more Toxic Substances will represent an opportunity cost in Precision. we will have to choose which is more acceptable, Classifying a Toxic Drug as Harmless or Classifying a Harmless Drug as Toxic.

Another way to to deal with Imbalanced Dataset is by increasing the size of the underrepresented  class in the Train Data sets, that way your Model can have more range in learning.

**Comment by pauline-banye** [comment]
Very well written @Malikbadmus 👍 . Impressive analysis.

**Comment by Malikbadmus** [comment]
Many thanks @pauline-banye

**Comment by Malikbadmus** [comment]
I'm glad to be of help @Zainab-ik , @GemmaTuron the issue can be closed now.

**Comment by GemmaTuron** [comment]
Good job @Malikbadmus
