### ISSUE TITLE
🦠 Model Request: Tox21 SR-HSE

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#427]
### Model Title

Tox21 SR-HSE (TDC dataset)

### Publication

Hello @mamabear25!

As part of your Outreachy contribution, we have assigned you the dataset "Tox21 SR-HSE" from the Therapeutics Data Commons to try and build a binary classification ML model.
Please copy the provided Google Colab template and use this issue to provide updates on the progress. We'll value not only being able to build the model but also interpreting its results.

**Comment by mamabear25** [comment]
Thanks @GemmaTuron, On it!

**Comment by GemmaTuron** [comment]
Hello @mamabear25 
Hope you are doing fine,please note that today was the last day to try out the models and explain the results you are getting, I'd suggest:

- Finish up your contribution and post the results here
- Close the issue
- Link this issue to your outreachy contribution profile
- Move on to prepare final applications
