### ISSUE TITLE
🐛 Bug: Empty Output error when fetching model  eos2b6f

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#439]
### Describe the bug.

Fetching the model flags empty output error. I will attach the log file later as this has been updated 
![image](https://user-images.githubusercontent.com/41667860/197550534-9a7dae49-7ba2-4815-8775-9aafdfc8ab7c.png)
Fetch however works well in colab but predict has been in an endless loop for the past two hours 

### Describe the steps to reproduce the behavior

Fetch Model eos2b6f 

### Expected behavior.

Fetch Model Successfully
Predict Model successfully in google colab 

### Screenshots.

![image](https://user-images.githubusercontent.com/41667860/197551363-fe791bd1-25f2-437d-b9ac-08e725b02e97.png)

### Operating environment

Ubuntu 22.04 VM

**Comment by mahamtariq58** [comment]
@angelnagaba  Did you check the model API?

**Comment by angelnagaba** [comment]
Hello, this error happens at the Fetch stage

**Comment by GemmaTuron** [comment]
@angelnagaba 

I have asked many times before, please without the log error I can't provide help. And when you get the log error try to read through it and identify what can be the problem.

**Comment by angelnagaba** [comment]
I tried again today and successfully fetched the model, however predict has an issue. Heres is my log
[my.log](https://github.com/ersilia-os/ersilia/files/9858990/my.log)

**Comment by GemmaTuron** [comment]
Hi @angelnagaba,

As always, try to use one single molecule as input first and check what is the printed output in the CLI. This will tell you if the predict is working and then the issue will be with the file

**Comment by GemmaTuron** [comment]
Hi @angelnagaba 

To close this thread, please revise that you provided the correct path to the model since it seems it cannot locate the SMILEs (input NoneType), or try to predict a single molecule to check the model works.

**Comment by GemmaTuron** [comment]
I will close this issue due to inactivity
