### ISSUE TITLE
Guidelines for onboarding of new contributors

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#44]
**Is your feature request related to a problem? Please describe.**
As a contributor for quite sometime now, I can tell from my experience the initial experience can be stressful. On the other hand, a lot of new contributors are sometimes shy to open up about their issues and problems to the project maintainers, or discuss about in the public communication channels.

**Describe the solution you'd like**
In this situation, it will be great if we could introduce a readme file, specifically designed for the new contributors with all the relevant links or resources. This makes the process of contribution easy and smooth for new onboarding contributors and also encourages more future contributions.

**Comment by sayantani11** [comment]
Please assign me this issue. Would like to work on it.

**Comment by GemmaTuron** [comment]
Hi @Sayantani11, 

Good initiative. Please do it by creating a CONTRIBUTION.md file in the root of the repository. I might add things in this file as well!

**Comment by Rufaida98** [comment]
@sayantani11 nice initiative

**Comment by Jaya3112** [comment]
For new contributors, it is quite difficult and stressful to contribute because they do not know how to approach any problem smoothly. They have to hustle a lot to solve any issue. So if we provide some images that can direct them in a correct then it will be very easy for them to do their contribution. I want to add more to the  CONTRIBUTION.md file which will help new contributors. Please assign me this issue. I would like to work on it.

**Comment by loweyvana** [comment]
@sayantani11 nice initiative. If you don't mind i would like to work with you on this. Being a new contributor, I must say i had a difficult time getting familiar here and I, therefore, think I can be of help to those coming after me. I could
-add demo gifs and/or demo screenshots to make the process easier and smoother.

**Comment by Rufaida98** [comment]
@sayantani11 can you make a folder and anyone ads file like I want to add resources file which contain helpful resources for contributors is it possible?

**Comment by Jaya3112** [comment]
> For new contributors, it is quite difficult and stressful to contribute because they do not know how to approach any problem smoothly. They have to hustle a lot to solve any issue. So if we provide some images that can direct them in a correct then it will be very easy for them to do their contribution. I want to add more to the CONTRIBUTION.md file which will help new contributors. Please assign me this issue. I would like to work on it.

@sayantani11 can I work on this issue. I have mentioned my idea above.

**Comment by miquelduranfrigola** [comment]
Thanks @sayantani11 for an awesome initiative. A CONTRIBUTION.md file has been created in #70

We really want to make things easy for everyone. As you might have noticed, we do have a GitBook account, which is quite awesome and can be synchronized with this GitHub repository. I think I will add the book as part of the repo, so you can all edit it. **What do you think?** Would that help?

In any case, I love @Jaya3112, @loweyvana and @Rufaida98 ideas, so I am leaving the issue open and assigning the issue to them as well.

**Comment by loweyvana** [comment]
> Thanks @sayantani11 for an awesome initiative. A CONTRIBUTION.md file has been created in #70
> 
> We really want to make things easy for everyone. As you might have noticed, we do have a GitBook account, which is quite awesome and can be synchronized with this GitHub repository. I think I will add the book as part of the repo, so you can all edit it. **What do you think?** Would that help?
> 
> In any case, I love @Jaya3112, @loweyvana and @Rufaida98 ideas, so I am leaving the issue open and assigning the issue to them as well.

souunds like a plan. Thanks for assigning me.

**Comment by ElizabethMawutin** [comment]
Hello @miquelduranfrigola can i also work on this project?
i have some ideas i would love to see added to the contribution file. 
Thank you.

**Comment by Jaya3112** [comment]
thankyou @miquelduranfrigola  for this opportunity

**Comment by yokwejuste** [comment]
Hey I'm Steve YONKEU, same as I'm having issues starting my journey at Ersilia, i would like to work on this issues already as a start

**Comment by GemmaTuron** [comment]
Hello all,

Please see the new contribution schema we have put together to make it easier to contribute tasks and follow everyone's work. I will close this issue now and ask you to focus on the tasks in the issue template, if you want to work on contribution guidelines check there to see the procedure
@sayantani11 before closing this issue, I would ask you to merge your NEW_CONTRIBUTION.md file with the already existing CONTRIBUTION.md so that there is only one file. 
Thanks!

**Comment by sayantani11** [comment]
> Hello all,
> 
> Please see the new contribution schema we have put together to make it easier to contribute tasks and follow everyone's work. I will close this issue now and ask you to focus on the tasks in the issue template, if you want to work on contribution guidelines check there to see the procedure @sayantani11 before closing this issue, I would ask you to merge your NEW_CONTRIBUTION.md file with the already existing CONTRIBUTION.md so that there is only one file. Thanks!

I am not able to understand  the merging part, can you elaborate?

**Comment by Jaya3112** [comment]
@GemmaTuron I have added some more text along with images. Please review it and if you want to give any suggestion please do the needful.

**Comment by GemmaTuron** [comment]
> > Hello all,
> > Please see the new contribution schema we have put together to make it easier to contribute tasks and follow everyone's work. I will close this issue now and ask you to focus on the tasks in the issue template, if you want to work on contribution guidelines check there to see the procedure @sayantani11 before closing this issue, I would ask you to merge your NEW_CONTRIBUTION.md file with the already existing CONTRIBUTION.md so that there is only one file. Thanks!
> 
> I am not able to understand the merging part, can you elaborate?

Hi @sayantani11 sure!

Your document  NEW_CONTRIBUTION.md has some interesting and well written parts that are not included in the CONTRIBUTION.md. 
I would like you to identify those and add them to the CONTRIBUTION.md. After, you can delete the NEW_CONTRIBUTION so that there is only one document

**Comment by GemmaTuron** [comment]
Hi @sayantani11 
Please can you tackle this work that was assigned to you? So we can close this issue!

Many thanks

**Comment by harshita214** [comment]
Hello @sayantani11 
I am also interested to work on this issue collaboratively with you and add more sections which are not yet been added to the contribution.md

@GemmaTuron  Can I do that and work on issue

**Comment by sayantani11** [comment]
This issue is done!!!
