### ISSUE TITLE
🐛 Bug: Contextual Version Conflict when running ersilia --help or ersilia catalog

### ISSUE THREAD

**Issue by Ng-ethe** [ersilia-os/ersilia#446]
### Describe the bug.

I successfully installed `ersilia` and got the confirmation on the CLI as shown in the screenshots. However on running` ersilia --help` I keep getting version conflict errors. I tried running `sudo apt-get update` and then rerunning the help command but the error persists. I have redone the installation process several times now (about six)  to ensure I am not missing anything in the steps. The current version conflict raised was with docker which I installed with `pip install docker` as advised by one of the mentors since installing it manually did not work. 

I tried to `pip install` docker again after this version conflict error and do an update but all the requirements were already satisfied. I have tried to do some research on how to solve version conflict errors but with no success yet. Any recommendations?

### Describe the steps to reproduce the behavior

1. follow the guridelines for prerequisites and installing ersilia from the Ersilia Gitbook provided.

### Expected behavior.

I want to access the ersilia help menu and catalog after successfully installing ersilia.

### Screenshots.

![image](https://user-images.githubusercontent.com/58877986/197922899-dc7f92ee-d410-4f52-8c23-95c58a4d28cc.png)

![image](https://user-images.githubusercontent.com/58877986/197922959-5762639f-1a80-4118-befa-b9295b25fde7.png)

### Operating environment

wsl 1 distro: Ubuntu on windows 2004.2022.1.0

**Comment by EstherIdabor** [comment]
Hi @Ng-ethe I encountered the same error, I fixed mine by changing to a different operating system(ubuntu 18.04.5) and starting the installation from the beginning again, in addition I did `sudo apt-get update`, `sudo apt-get upgrade` `sudo apt install python3-pip`. you can try it out.
