### ISSUE TITLE
🐛 Bug: Time-out on colab when fetching model EOS7W6N

### ISSUE THREAD

**Issue by zheeburg** [ersilia-os/ersilia#447]
### Describe the bug.

Model couldn’t fetch successfully. While doing predictions, it simply continue to run till break. Then, at that point, I really want to get it once more and do the predictions again but still yet continue to run. I was unable to get any mistake message, it appears to be thatbthe predictions didn't wrap up.

### Describe the steps to reproduce the behavior

!ersilia -v fetch eos7w6n
model = ErsiliaModel("eos7w6n")
model.serve()
output = model.predict(input=smiles, output="pandas")

### Operating environment

UBUNTU 20.04.1

**Comment by GemmaTuron** [comment]
Hello @zheeburg

I don't understand how did you run predictions if the model did not fetch successfully? Also, do you have any error logs?
