### ISSUE TITLE
Fix typo in the Readme file

### ISSUE THREAD

**Issue by kbetty** [ersilia-os/ersilia#45]
The Readme file contains a typo in the word `acknowledgement` and there is a need to be fixed. cc: @GemmaTuron

**Comment by kbetty** [comment]
Have added a PR at https://github.com/ersilia-os/ersilia/pull/46 to address the issue.

**Comment by Rufaida98** [comment]
@kbetty should i fix it and address it as an issue?

**Comment by kbetty** [comment]
Thanks @Rufaida98 for showing the interest on the issue. You may need to take a look at the comment I made [here](https://github.com/ersilia-os/ersilia/issues/45#issuecomment-1081417751).

**Comment by GemmaTuron** [comment]
Thanks @kbetty your contribution is merged

**Comment by kbetty** [comment]
@GemmaTuron should I record this task in the Outreachy website?
