### ISSUE TITLE
🦠 Model Request: Tox21 NR-PPAR-gamma

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#451]
### Model Title

Tox21 NR-PPAR-gamma (TDCommons)

### Publication

Hello @Dorothy2020!

As part of your Outreachy contribution, we have assigned you the dataset "Tox21 NR-PPAR-gamma" from the Therapeutics Data Commons to try and build a binary classification ML model.
Please copy the provided Google Colab template and use this issue to provide updates on the progress. We'll value not only being able to build the model but also interpreting its results.

**Comment by Dorothy2020** [comment]
Thanks @GemmaTuron working on it

**Comment by Dorothy2020** [comment]
Hello @GemmaTuron kindly see my progress though I'm having errors while plotting both the bar chart and piechart maybe you can help me with suggestions. thank you. https://colab.research.google.com/drive/1SBru9jRgQwOxcMkJbswVudqyLWrVjzh5?usp=sharing

**Comment by EstherIdabor** [comment]
Hi @Dorothy2020, your model doesn't look like it's performing well, a hint on how to make it perform better will be to increase the training time and try resampling your data.
Also while reporting on the performance of your model you should include the auroc value and comment on it.

**Comment by Dorothy2020** [comment]
> Hi @Dorothy2020, your model doesn't look like it's performing well, a hint on how to make it perform better will be to increase the training time and try resampling your data. Also while reporting on the performance of your model you should include the auroc value and comment on it.

@EstherIdabor thank you for this

**Comment by GemmaTuron** [comment]
Hi @Dorothy2020 ,

I am missing a bit of interpretation of the results you are getting, and what could you do to improve the model. Please comment on this issue thread, link it to your outreachy contribution profile and go onto preparing the final application

**Comment by Dorothy2020** [comment]
> Hi @Dorothy2020 ,
> 
> I am missing a bit of interpretation of the results you are getting, and what could you do to improve the model. Please comment on this issue thread, link it to your outreachy contribution profile, and go on preparing the final application

Hello, @GemmaTuron I have updated the result and recommendations and now it looks at least better.  Here is the link https://colab.research.google.com/drive/1SBru9jRgQwOxcMkJbswVudqyLWrVjzh5?usp=sharing, Thank you.

**Comment by Dorothy2020** [comment]
Hello @GemmaTuron Kindly assist me in closing the issue. Thank you

**Comment by Dorothy2020** [comment]
Hello kindly check my updated GitHub issue. Thank you
