### ISSUE TITLE
🐛 Bug: Ersilia fails to initialize if `.bashrc` is not present in home dir

### ISSUE THREAD

**Issue by leoank** [ersilia-os/ersilia#452]
### Describe the bug.

The issue is in the call to `bashrc_cli_snippet(overwrite=False)` function on line 54 of the root `__init__.py` file. This function will throw error if no `.bashrc` file is found in the home dir.

### Describe the steps to reproduce the behavior

Use the library on windows or a linux system with no `.bashrc` in home dir

### Expected behavior.

Library should have initialized properly

### Operating environment

Windows, Arch

**Comment by miquelduranfrigola** [comment]
Hello @leoank - I have updated this and now Ersilia doesn't crash if no bashrc or bash_profile is available.
