### ISSUE TITLE
🐛 Bug: Fail to initialize on windows

### ISSUE THREAD

**Issue by leoank** [ersilia-os/ersilia#453]
### Describe the bug.

The library fails to initialize with an error at line 4 of the root `__init__.py` file.
It complains that the `_version` object doesn't exist.

### Describe the steps to reproduce the behavior

Try to initialize the library on windows. 

### Expected behavior.

The library should have initialized without any errors.

### Operating environment

Windows

**Comment by EstherIdabor** [comment]
Hi @leoank your bug is not very descriptive as I cant understand what failed to initialize. if its the ersilia model you are not supposed to be running it on on a windows without WSL(windows subsystem  Linux)  installed,

**Comment by leoank** [comment]
Hey @EstherIdabor, I am trying to use `ersilia` as a library in my own project. Whenever I try to import my own library that in turn imports ersilia. It results in an error. The error points to the line 4 of the root `__init__.py` of `ersilia`. It can be easily solved by wrapping line 4 in a `try` block.

**Comment by EstherIdabor** [comment]
Ok. @GemmaTuron will better understand

**Comment by GemmaTuron** [comment]
Hi @leoank 

We haven't run into this error before when importing ersilia. Can you open a PR? 
Thanks :)

**Comment by GemmaTuron** [comment]
Hi @leoank !

Checking the status of this! If it is solved, please link the PR that solved it or explain what did you do to solve it and close the issue.
Thanks!
