### ISSUE TITLE
🐛 Bug: Loop when fetching eos4e41 model

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#454]
### Describe the bug.

The search for the eos4e41 model took about 1 hour 20 mins, with the same information appearing in an infinite loop as shown in the first attached photo.

In the end the following error:
```
Traceback (most recent call last):
TypeError: 'NoneType' object is not subscriptable
```

### Describe the steps to reproduce the behavior

1. ersilia -v fetch eos4e41
then loop and error

### Expected behavior.

Find the model to serve.

### Screenshots.

Loop for 1 hour and 20 minutes:
<img width="1023" alt="Screenshot 2022-10-26 at 13 51 13" src="https://user-images.githubusercontent.com/95102911/198091530-55f1825b-33f1-4d7f-be2a-b6a10d04faf0.png">

Final error:
<img width="945" alt="Screenshot 2022-10-26 at 13 28 20" src="https://user-images.githubusercontent.com/95102911/198091586-bc2a132d-fa82-4855-bcab-88dc4655b983.png">

Error log:
[error.log](https://github.com/ersilia-os/ersilia/files/9872162/error.log)

### Operating environment

MacOS, Intel Core i5

### Additional context

All Ersilia Model Hub installation successfully completed!

**Comment by natividadesusana** [comment]
Then I try to test to serve the model and a new loop starts for another 1 hour:
>> [error.log](https://github.com/ersilia-os/ersilia/files/9873149/error.log)


I also tried to make a prediction and even though I tried to serve the model, the message was the following:
>> ![unnamed](https://user-images.githubusercontent.com/95102911/198118389-f894b66d-bfe2-4170-90d3-221971205d78.png)

**Comment by GemmaTuron** [comment]
Hi @natividadesusana 

If a model is not fetched correctly it does not mke sense to serve or predict as the model is not in your computer.
This error seems to be due to incorrect ersilia configuration. have you successfully run other models?

**Comment by natividadesusana** [comment]
Hi @Gemma,
How strange, everything is installed correctly and I searched according to the ersilia model hub documentation.
But today I did a new search on the same in the model and everything seems to have worked well.
I leave the log here for verification.

[model-eos4e41.log](https://github.com/ersilia-os/ersilia/files/9880491/model-eos4e41.log)
