### ISSUE TITLE
🐛 Bug: Exception: Environment Does Not Exist

### ISSUE THREAD

**Issue by Celinezzzzz** [ersilia-os/ersilia#455]
### Describe the bug.

I was testing models on Colaboratory. When I was fetching the 2nd model, I got an error message "Exception: environment does not exist".

### Describe the steps to reproduce the behavior

**Operating System:**
Windows 10 WSL Ubuntu 20.04 LTS
**Conda Version:**
Miniconda3
**Python Version:**
Python 3.9

**Steps that I have taken:**
1. Completed the pre-requisites according to the [Guideline](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation) 
- WSL, Ubuntu, gcc complier, miniconda, Github CLI, Git LFS
2. Installed the Ersilia Model Hub
_create -n ersilia python=3.7
git clone https://github.com/ersilia-os/ersilia.git
cd ersilia
pip install -e ._
3. Test Ersilia with a simple modedl
_ersilia --help
ersilia catalog
ersilia -v fetch eos3b5e
ersilia serve eos3b5e
ersilia -v api calculate -i "CCCC"_
![image (1)](https://user-images.githubusercontent.com/99721409/198228442-4fa89b40-7e72-4201-8779-df858cdbf702.png)

4. Model Testing on CLI
(Models for testing: eos3xip, eos77w8, eos5smc)
_ersilia -v fetch eos3xip > my_eos3xip_fetch 2>&1
ersilia serve eos3xip
ersilia -v api predict -i "eml_canonical.csv" -o "eos3xip.csv" > my_eos3xip_predict 2>&1_ 

Results: Models all run successfully on CLI. I have saved the error logs for each models during fetch and predict/calculate period. I also record the fetch time and predict time in Test Excel Spreadsheet. I saved the output of three models as csv files and uploaded to shared google drive folder.

5. Model Testing on Colab

Results: 
I encountered a few errors when I test models on Colab:  
In the colab template, it includes "CAN_SMILES" which wasn't present in the input file. So I changed the smiles = df["CAN_SMILES"].tolist() to smiles = df["can_smiles"].tolist() and it worked.

The 1st model eos3xip works fine, I was able to fetch, serve and predict, and saved output as cvs file.

I encountered another error when I test the 2nd model eos77w8. The error message I got is "Exception: eos77w8 environment does not exist". I then tried it with the 3rd model eos5smc and the 1st model eos3xip, but I still got the same error message.

I disconnected and deleted runtime, and re-run the code, which solved the problem. I then record the runtime for fetching and predicting, and saved output as cvs file.

But I am not sure what is causing this issue. Are we supposed to disconnect and delete runtme everytime after testing a model? 
@GemmaTuron 

### Screenshots.

![image](https://user-images.githubusercontent.com/99721409/198222261-d71b6419-dbf3-472a-86c2-18f26ec5b72c.png)

[my_eos5smc_fetch.log](https://github.com/ersilia-os/ersilia/files/9877293/my_eos5smc_fetch.log)
[my_eos5smc_predict.log](https://github.com/ersilia-os/ersilia/files/9877294/my_eos5smc_predict.log)
[my_eos77w8_fetch.log](https://github.com/ersilia-os/ersilia/files/9877295/my_eos77w8_fetch.log)
[my_eos77w8_predict.log](https://github.com/ersilia-os/ersilia/files/9877296/my_eos77w8_predict.log)
[my_eos3xip_fetch.log](https://github.com/ersilia-os/ersilia/files/9877298/my_eos3xip_fetch.log)
[my_eos3xip_predict.log](https://github.com/ersilia-os/ersilia/files/9877299/my_eos3xip_predict.log)
[eos5smc_251022_CLI.csv](https://github.com/ersilia-os/ersilia/files/9877306/eos5smc_251022_CLI.csv)
[eos77w8_251022_CLI.csv](https://github.com/ersilia-os/ersilia/files/9877307/eos77w8_251022_CLI.csv)
[eos3xip_251022_CLI.csv](https://github.com/ersilia-os/ersilia/files/9877308/eos3xip_251022_CLI.csv)
[eos5smc_25102022_Colab.csv](https://github.com/ersilia-os/ersilia/files/9877310/eos5smc_25102022_Colab.csv)
[eos3xip_25102022_Colab.csv](https://github.com/ersilia-os/ersilia/files/9877311/eos3xip_25102022_Colab.csv)
[eos77w8_25102022_Colab.csv](https://github.com/ersilia-os/ersilia/files/9877312/eos77w8_25102022_Colab.csv)

### Operating environment

Ubuntu 20.04 LTS

**Comment by aldeav** [comment]
@Celinezzzzz  Runtime needs to be disconnected before fetching another model so you will have to do the following Runtime > Disconnect and Delete runtime.

**Comment by aldeav** [comment]
@Celinezzzzz You need to terminate the current session, disconnect, and restart the runtime before fetching another model. You can try doing: Runtime > Disconnect and Delete runtime.

**Comment by GemmaTuron** [comment]
Hi @Celinezzzzz 

Yes, you need runntime disconnection, but this is a reported issue already so don't try the models again it's fine.
