### ISSUE TITLE
🐛 Bug: Model eos9f6t does not produce output

### ISSUE THREAD

**Issue by natividadesusana** [ersilia-os/ersilia#458]
### Describe the bug.

When fetching the eos9f6t model an error occurred in the eos9f6t API model warning that the prediction does not produce output.

```
Detailed error:
Model API eos9f6t:predict did not produce an output
```

### Describe the steps to reproduce the behavior

1. `ersilia -v fetch eos9f6t`

### Expected behavior.

Search model.

### Screenshots.

- eos9f6t model error log:

[model-eos9f6t.log](https://github.com/ersilia-os/ersilia/files/9881470/model-eos9f6t.log)

### Operating environment

MacOS, Intel Core i5

**Comment by GemmaTuron** [comment]
Hi @natividadesusana 

Thanks, as specified in the Slack channel the mentors are currently too busy reviewing contributions for the next stage and we are unable to provide feedback on model fetching issues this week.

**Comment by natividadesusana** [comment]
Ok, thanks for your attention @GemmaTuron!!
