### ISSUE TITLE
📑 Feature Request: Documentation Enhancement

### ISSUE THREAD

**Issue by Femme-js** [ersilia-os/ersilia#466]
### Is your feature request related to a problem? Please describe.

While working with ersilia, and building models, I felt a need to have a bit more detailed explanation about QSAR modeling and QSAR models in general. 

### Describe the solution you'd like.

I have written a short blog/description about QSAR modeling and Ersilia's AutoML tools to facilitate QSAR modeling. 

'''
**QSAR Modelling with Ersilia**

Quantitative structure-activity relationship models are the tools to predict the physicochemical and biological properties of chemical compounds from their chemical structure. QSAR modeling is one of the major computational in medicinal chemistry whose main goal is to establish a quantitative relationship between descriptors and the target property capable of predicting the activities of novel compounds. 

Ersilia Open Sorce Initiative provides two major tools for Automate machine learning and on-demand modeling. ZairaChem for advanced and more accurate modeling, and LazyQSAR for quick baseline modeling.

ZairaChem is capable of producing State of the art results, without any need for data preprocessing and hyperparameter tuning. Model validation test results can be automatically served for better assessment. 
Lazy-QSAR is an AutoML library to build QSAR models fastly, and quickly build binary classification and regression models.

'''

### Additional context.

If this seems a potential feature integration, we can enhance the description and integrate it with Ersilia's current documentation.

**Comment by Femme-js** [comment]
Hi @GemmaTuron ! 

While contributing to Stage-3, I felt there are some bridges that can be filled through Ersilia's current gitbook. One of them is to provide a basic introduction about QSAR modeling in general, which can help new contributors exploring datasets more easily and better interpret the AutoML tools they are using.

I am interested in contributing to this issue with the help of description or short blog that we can indicate with Ersilia's gitbook.

Looking forward to your feedback.

**Comment by GemmaTuron** [comment]
Hi @Femme-js !

Thanks for this contribution. We have started working on documenting our automated tools, particularly ZairaChem, in the GitBook (https://ersilia.gitbook.io/ersilia-book)
We will incorporate a bit of background as you suggest!
