### ISSUE TITLE
set up conda environment

### ISSUE THREAD

**Issue by Rufaida98** [ersilia-os/ersilia#47]
@miquelduranfrigola @GemmaTuron I want to address an issue not related to fixing a bug but something i encountered while trying to install ersilia CLI. As related to issue #36 i installed the Ubuntu because my system is windows 10 and downloaded all the packages needed but still it didnt work and it was due to my conda environment.

So if someone faced the same problem instead of using:
"conda create -n ersilia python=3.7"
please use:
"source ~/anaconda3/etc/profile.d/conda.sh"
Then activate the environment as per in Ersilia book. it worked and i hope it helps others.Thank you

**Comment by ifeoluwafavour** [comment]
Thank you very much for this @Rufaida98 

It is very helpful

**Comment by miquelduranfrigola** [comment]
Thanks @Rufaida98! Can you please provide the full sequence of commands that worked for you? At what stage did you create the ersilia conda environment? Thanks!

**Comment by tracycod3r** [comment]
Thanks @Rufaida98

**Comment by Rufaida98** [comment]
@ifeoluwafavour @tracycod3r you are very welcome

**Comment by Rufaida98** [comment]
@miquelduranfrigola right away

**Comment by Rufaida98** [comment]
![Capture step1](https://user-images.githubusercontent.com/92082003/160691713-417ec032-37fa-4944-987d-89ea7e753dc5.PNG)
![Capture step2](https://user-images.githubusercontent.com/92082003/160691723-a6ecd95b-75f2-4b47-9cb2-46af4f221e07.PNG)

**Comment by Rufaida98** [comment]
@miquelduranfrigola one more i did install anaconda and miniconda package

**Comment by miquelduranfrigola** [comment]
OK I see, thanks @Rufaida98. This is not necessarily an ersilia issue (sourcing conda in some systems does not happen when opening a terminal). I am closing the issue for now (thanks for your feedback!). I suggest editing the bashrc: [https://askubuntu.com/questions/849470/how-do-i-activate-a-conda-environment-in-my-bashrc](https://askubuntu.com/questions/849470/how-do-i-activate-a-conda-environment-in-my-bashrc)
