### ISSUE TITLE
🐛 Bug: Unable to Fetch eos4tcc Model

### ISSUE THREAD

**Issue by chosenking1** [ersilia-os/ersilia#472]
### Describe the bug.

[eos4tcc.log](https://github.com/ersilia-os/ersilia/files/9911837/eos4tcc.log)
After trying for a week am still unable to fetch the model my log file has been attached

@GemmaTuron 

### Describe the steps to reproduce the behavior

Activate Ersilia
run ersilia -v fetc
h eos4tcc > eos4tcc.log 2>&1

### Operating environment

WSL Ubuntu 20.04

**Comment by GemmaTuron** [comment]
Hi  @chosenking1,

I am sorry you are facing trouble, at this moment all the mentors are busy supporting the final applications for Outreachy and I can't provide support. I haven't seen you assigned models for testing on the excel file and I don't know if you were able to successfully do the tests that Ersilia is propely installed.. I'd ask you to follow the contribution guidelines and join the Slack channel.

**Comment by chosenking1** [comment]
> Hi @chosenking1,
> 
> I am sorry you are facing trouble, at this moment all the mentors are busy supporting the final applications for Outreachy and I can't provide support. I haven't seen you assigned models for testing on the excel file and I don't know if you were able to successfully do the tests that Ersilia is propely installed.. I'd ask you to follow the contribution guidelines and join the Slack channel.

Yes I filled the Spreadsheet i go by Christian on there, The other three models worked on the cli
