### ISSUE TITLE
[Batch] Workflow to Create a Docker Image and Store it in Dockerhub

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#477]
Workflow to Create a Docker Image and Store it in Dockerhub

- [x] #494
- [x] #495
- [ ] #496

**Estimated timeline:** 2 weeks (2/17 deadline)

**Comment by GrantBirki** [comment]
Questions for @miquelduranfrigola to get the ball rolling:

- On what conditions should we be building and publishing a new Docker image to Dockerhub?
- What Dockerfile should we be building? (Got a link to the desired one is this repo?)

**Comment by miquelduranfrigola** [comment]
I think we can trigger the dockerfile building action when we do a new Ersilia release. At the moment, we submit to PyPi when we have a new tag. I think we can do the same: https://github.com/ersilia-os/ersilia/actions/workflows/python-publish.yml

**Comment by GemmaTuron** [comment]
Update on this task:

- [ ] Ersilia runs as a Docker Container
- [ ] There is a pipeline that automatically updates models to the dockerhub

**Comment by GemmaTuron** [comment]
The pipeline is being developed by @honeyankit in https://github.com/ersilia-os/ersilia/issues/494

**Comment by honeyankit** [comment]
I was on PTO, there is no update on this issue since https://github.com/ersilia-os/ersilia/issues/494#issuecomment-1353525978.

Estimated time to complete: ~ 2 Weeks

**Comment by miquelduranfrigola** [comment]
Hello @honeyankit - The current `Dockerfile` to containerize ersilia is here: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/easyinstallimage

I think it works smoothly but of course, please let me know if you encounter any issues!

**Comment by honeyankit** [comment]
> Hello @honeyankit - The current `Dockerfile` to containerize ersilia is here: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/easyinstallimage
> 
> I think it works smoothly but of course, please let me know if you encounter any issues!

I will start looking it. Thank you for sharing!

**Comment by GemmaTuron** [comment]
The tasks are being tackled in #546, I will close this issue.

- [ ] Dockerfile for the Ersilia repo: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/model-deploy/base
- [ ] Workflow to create Docker image of ersilia: https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-base-image-to-dockerhub.yml -- creates both ARM64 and AMD64 images
- [ ] Conditions to update docker image of Ersilia is set to every time a new version of Ersilia is created. The image will be named latest
