### ISSUE TITLE
[Batch] Automate Posts to Slack

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#478]
- [x] https://github.com/ersilia-os/eos-template/pull/5

**Comment by GrantBirki** [comment]
https://api.slack.com/messaging/webhooks

**Comment by GrantBirki** [comment]
@GemmaTuron

> open an issue on the model repo and assign two people there

What two folks should we use for review on this issue? Do you have a candidate pool or GitHub team we can pull from for required reviewers? A GitHub team would be ideal as I can write some code to poll the team and randomly assign two reviewers on each issue

Should we also assign the person who created the model request to the issue?

> In parallel, post the issue on Slack

Do you have a general format for what the message should look like that we will be posting to Slack?

---

Thanks! 😃

**Comment by D1M1TR10S** [comment]
Should be done by Monday (2/6) – @megamanics

**Comment by GemmaTuron** [comment]
@GemmaTuron to modify the Slack message and this can be closed
