### ISSUE TITLE
📑 Feature Request: Google Colab workflow

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#488]
### Is your feature request related to a problem? Please describe.

Many users use Google Colab to run models. It would be great to make sure, as part of the CI/CD workflow, that Ersilia can run in Google Colab.

### Describe the solution you'd like.

Run the following notebook as part of a GitHub action: https://github.com/ersilia-os/ersilia/blob/master/notebooks/ErsiliaOnColaboratory.ipynb

@GemmaTuron please check that the current notebook is working

**Comment by GemmaTuron** [comment]
Follow up on this.
We are working in this notebook: https://github.com/ersilia-os/ersilia/blob/master/AutomatedTests.ipynb

Next tasks:

- [ ] Change the api call from the python package so it can both "predict" and "calculate" 
- [ ] Incorporate automated selection of model id
- [ ] Automatically select input type (probably, taking it from the self-test at fetch time)
- [ ] Move the notebook to the right folder /notebooks and eliminate redundancy with https://github.com/ersilia-os/ersilia/blob/master/notebooks/test-collab-notebook.ipynb

We will tackle these tasks with @miquelduranfrigola this week.

**Comment by GemmaTuron** [comment]
This issue is being tackled in https://github.com/ersilia-os/github-partners/issues/5
I'll close this one!
We currently have three notebooks:

- ersilia-on-colab (for end users)
- test-colab-notebook-on-python-api 
- test-colab-notebook-cli
