### ISSUE TITLE
Creating Dockerfile for the ersillia repo

### ISSUE THREAD

**Issue by honeyankit** [ersilia-os/ersilia#494]
## Context
Create a Dockerfile to build ersillia Docker image. You can reference the digital ocean [Dockerfile](https://github.com/ersilia-os/ersilia/blob/honeyankit/cleanup-dockerworkflow/dockerfiles/digital-ocean/Dockerfile)

## Exit Criteria
To have a Dockerfile to build ersillia Docker image

## Contact 
- @honeyankit

**Comment by honeyankit** [comment]
Draft PR: https://github.com/ersilia-os/ersilia/pull/506

**Comment by honeyankit** [comment]
> ModuleNotFoundError: No module named 'setuptools'

The reason for the above issue is "Activating a Conda environment in your Dockerfile".

**Comment by GemmaTuron** [comment]
@honeyankit 
Can you shortly update us on this issue?

**Comment by honeyankit** [comment]
@GemmaTuron : I was on PTO, there is no update on this issue since https://github.com/ersilia-os/ersilia/issues/494#issuecomment-1353525978

**Comment by D1M1TR10S** [comment]
Needs link to the new Dockerfile from @miquelduranfrigola. Should solve this error.

**Comment by GemmaTuron** [comment]
-hi @honeyankit 
Everything about docker is in the /dockerfiles folder on the ersilia repo. In this case, i think you need to have a look at the dockerfile on /easyinstallimage: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/easyinstallimage

**Comment by GemmaTuron** [comment]
This is completed: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/model-deploy/base
