### ISSUE TITLE
Create action workflow to build and push the ersillia docker image to the DockerHub registry

### ISSUE THREAD

**Issue by honeyankit** [ersilia-os/ersilia#495]
## Context
Use the Dockerfile in the issue# https://github.com/ersilia-os/ersilia/issues/494 to create action workflow to build and push the ersillia docker image to the DockerHub registry. 

Note: 
- This task is dependent on the issue #494 
- Docker Hub Secrets are already added to ersilia repo: [slack context](https://github.slack.com/archives/C040GAGQC9J/p1668155438990429)

## Exit Criteria
Action workflow to build and push the ersillia docker image to the DockerHub registry.

## Contact
- @honeyankit

**Comment by GemmaTuron** [comment]
This is completed: https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/ersilia-base-image-to-dockerhub.yml
