### ISSUE TITLE
Identify and integrate the conditions to build and push the new ersillia Docker image to the DockerHub

### ISSUE THREAD

**Issue by honeyankit** [ersilia-os/ersilia#496]
## Context

Determine and incorporate the conditions for creating and publishing the new Ersilia Docker image to DockerHub. We don't want the action workflow to continuously create and upload new Ersilia docker images to DockerHub but at the same time we also want latest Ersilia docker image to be present in the Docker Hub. Therefore, we must determine the conditions needed to create and upload the Ersilia Docker image to DockerHub.

## Exit Criteria
Integrate the conditions to build and push the new Ersilia Docker image to the DockerHub.

## Contact
- @honeyankit

**Comment by miquelduranfrigola** [comment]
Hi @honeyankit , I see two conditions:

* Ersilia installation test successfully passed. For this, we can basically use the same workflow that is triggered in a [PR](https://github.com/ersilia-os/ersilia/actions/workflows/pr_check.yml)
* A new tag is created. We had some discussion about tags vs releases. In practice, we create tags relatively infrequently (on average, on a monthly basis), so I think we can use tags. For this, we can get inspiration from the action to [submit Ersilia to PyPi](https://github.com/ersilia-os/ersilia/actions/workflows/python-publish.yml). If you think release is more advisable than tag, then let's go for it.

Is there anything else we may be missing here?

Thanks!
