### ISSUE TITLE
🦠 Model Request: Adverse Drug Reaction Prediction using Open TG-GATES

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#502]
### Model Name

Adverse Drug Reaction prediction

### Model Description

Prediction of adverse drug reactions using chemical induced gene expression profile

### Slug

adr-prediction

### Tags

classification

### Publication

https://www.frontiersin.org/articles/10.3389/fddsv.2021.768792/full

### Code

https://github.com/attayeb/adr has model checkpoints

**Comment by DhanshreeA** [comment]
This study has developed models for adverse drug reactions (ADR) based on drug induced gene expression profiles. This is a multi label set up, ie one gene expression profile can have different types of adverse drug reactions. They have built total 14 models each corresponding to an ADR. They have used the intersection of two datasets for this task, namely [Open TG-GATES](https://dbarchive.biosciencedbc.jp/en/open-tggates/desc.html)  and a standardized [FAERS](https://datadryad.org/stash/dataset/doi:10.5061/dryad.8q0s4). Open TG-GATES is in-vitro and in-vivo toxicogenomic profiling on humans (in-vitro) and rats (both), whereas FAERS is FDA's adverse event reporting system. Interestingly, they have used FAERS as a way for building a labeled data set by classifying subsets of drugs as having positive or negative association to an adverse reaction  (by performing a Lasso regression and keeping the threshold for treated vs control at 92%)  and then using gene expression profiles those drugs from Open TG-GATES as input for further predictive modeling for newer drugs.
The Open TG-GATES data is present as CEL files (They use an R package called affy for working with these), and the FAERS dataset can be loaded into a SQL server.

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA, this is great.

As discussed, let's leave this issue open but on hold for now. The reason for deprioritising this model is that the input is gene expression data, which will not be straightforward to harmonize with the rest of input of the hub (currently, SMILES strings). One possibility is to add an extra mapping step through the [Connectivity Map](https://clue.io/), but this will require substantial amount of validation.

As soon as we have more models that require gene expression as input, we will go back to this issue.

**Comment by DhanshreeA** [comment]
Have requested help from the authors for a minimal Python based setup for testing out these models here: https://github.com/attayeb/adr/issues/1

**Comment by GemmaTuron** [comment]
There are no plans to include this model so I would close the issue. By the time we go back to adding other kinds of inputs in Ersilia we will find newer literature
