### ISSUE TITLE
🦠 Model Request: Prediction of clinically relevant drug‐induced liver injury from structure using machine learning

### ISSUE THREAD

**Issue by nataliyah123** [ersilia-os/ersilia#508]
### Model Name 
Drug-induced liver injury prediction

### Model Description

Prediction of clinically relevant drug-induced-liver-injury (DILI), based solely on drug structure using binary classification methods. The results presented here are useful as a screening tool both in a clinical setting, in the assessment of DILI as well as in the early stages of drug development to rule out potentially hepatotoxic candidates.

### Slug

dili-pred

### Tag

Metabolism, Toxicity, Cytotoxicity

### Publication

https://pubmed.ncbi.nlm.nih.gov/30325042/,

### Source Code

https://github.com/cptbern/QSAR_DILI_2019

### License

None

**Comment by GemmaTuron** [comment]
Hi @nataliyah123 !
I ahve been doing some reading on DILI. There is this benchmark dataset from [TDCommons](https://tdcommons.ai/single_pred_tasks/tox/#dili-drug-induced-liver-injury) that uses FDA-approved drugs. Do you know if there is overlap between it and the data you are using in this model?
I am also linking here an interesting paper that cites more datasets, I'm not sure if they are open but would be interesting to investigate: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7702310/#R6

**Comment by nataliyah123** [comment]
hi @GemmaTuron 
I have attached the notebooks and dataset. Thanks a lot for the datasets links and will let you know.

**Comment by GemmaTuron** [comment]
Hi @nataliyah123 

The notebooks look good, but before deciding next steps can you please:

- Check which datasets were used in the publication and whether these are overlapping with the ones in TDCommons (please note that SMILES might be given in different formats, so make sure to standardise the datasets before comparing them or you wont find matches)
- Write a short summary of the performances you have obtained with the different methods and compare to the ones obtained in the original publication

**Comment by Femme-js** [comment]
Hi @nataliyah123 !

Can you share the the attachment for the training set here?

**Comment by nataliyah123** [comment]
hi @Femme-js Data and notebooks are all attached in the top comment. The file smileandactivity2.csv which I made for Zairachem is the new one, I just attached

**Comment by AdedejiAdewole** [comment]
hello, how can I work on this please

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 
Do we want to finish the work on this model ¿

**Comment by GemmaTuron** [comment]
@leilayesufu 
If you finish your other tasks or are stuck, can start having a look at this model!

**Comment by GemmaTuron** [comment]
I've removed the notebooks from the issue as it disrupts the workflow:
## Notebooks
[Autogluon](https://colab.research.google.com/drive/1AJTG5oSExB-2_ODR6t1pol2Fb2PvHf9x#scrollTo=COSZxxxOs8t2)
[AutoML](https://colab.research.google.com/drive/1dPTDhgcUS4fZy4yKlGHy-9D2tKwJfaqd?usp=sharing)
[Dataset](https://github.com/cptbern/QSAR_DILI_2019)
[smilesandactivity2.csv](https://github.com/ersilia-os/ersilia/files/10683193/smilesandactivity2.csv)

**Comment by GemmaTuron** [comment]
there were many modifications on the issue template that cause multiple fails in the workflows

**Comment by GemmaTuron** [comment]
Hi @leilayesufu 
I have tried too many times to change the model request back to its original form. I'll close this issue and please open a new one with the information provided, it'll be much easier. Thanks!

**Comment by GemmaTuron** [comment]
I am reopening this issue to check the new pipeline created by @GrantBirki when the approve command fails

**Comment by GemmaTuron** [comment]
And that works just fine @miquelduranfrigola and @GrantBirki thanks!
