### ISSUE TITLE
Add "Back to top button" to the README file

### ISSUE THREAD

**Issue by busiratazeez** [ersilia-os/ersilia#51]
**Is your feature request related to a problem? Please describe.**
Scrolling up and down is exhausting when exploring the readme file

**Describe the solution you'd like**
I want to incorporate a button to scroll back to the top page after every sub-section of the readme file
@GemmaTuron @miquelduranfrigola kindly assign this issue to me

**Comment by GemmaTuron** [comment]
This is a good idea @ashaby4000 
I have assigned it to you

**Comment by ashaby4000** [comment]
Thanks @GemmaTuron kindly check the PR
