### ISSUE TITLE
🐛 Bug: Remove flask functionality from RLM Stability Model

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#512]
### Describe the bug.

Hi @GemmaTuron , 
### Update on the RLM Stability model.

- [x] I have tried to remove all flask related functionalities and run the model with the functions on the original repository.
- [x] I removed all flask related dependencies and installed alternatives. 
- [x] I downloaded, imported and loaded the model file `gcnn_model.pt`
![model](https://user-images.githubusercontent.com/63536707/209381578-d03cf830-19e6-4af6-95d4-963f9cbb1713.png)
- [ ] Tried to run the model unsuccessfully. I kept running into various errors and I eventually decided to debug using colab because it's easier to trace where the errors were coming from. 
![err2](https://user-images.githubusercontent.com/63536707/209385862-cc07d375-d60e-4f12-82bf-59ad478c5312.png)

linked below is the link to the colab file I am testing with and the test repo containing the codes excluding the ones I have removed. However I am still in the process of debugging using both the colab file and the repo and currently researching on how to properly implement the code to return the proper output.

[test RLM colab](https://colab.research.google.com/drive/1j6N02bvzlL-h5G8k4dpY3jLl8UowhkvS#scrollTo=D77UxhIf8O01)
[test RLM repo](https://github.com/pauline-banye/testrlm.git)

### Operating environment

Windows 10 WSL

**Comment by pauline-banye** [comment]
### Current update

Had a lot of bugs converting the model to pure python functions and I'm finally not returning any errors but I'm unsure about the returned output.  
`<rdkit.Chem.rdchem.Mol object at 0x00000212B6F54510>
{'args': {}}`
![rlm be](https://user-images.githubusercontent.com/63536707/209581934-07dcf047-1989-4fa9-827c-10132fb945e8.png)
could you please review this @GemmaTuron @miquelduranfrigola

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 
Great work, the RdKit output is a molecule that needs to be converted into a SMILES (`Chem.MolToSmile`)

**Comment by pauline-banye** [comment]
> Hi @pauline-banye Great work, the RdKit output is a molecule that needs to be converted into a SMILES (`Chem.MolToSmile`)

Hi @GemmaTuron, hope you had an awesome holiday? Thank you! It really feels good to make some headway. 

I'll work on the conversion, I'm currently attempting to fix bug on the model. Noticed an error when I passed eml_canonical, the current code only accepts one input smiles. The original flask code did not have this limitation when the eml_canonical file is passed from the frontend.

![value error](https://user-images.githubusercontent.com/63536707/209639245-5907a490-d291-4933-83a8-3e5a09d4f0d0.png)

**Comment by DhanshreeA** [comment]
I wanted to jump in on this as well! I tried setting up the ncats/adme environment as per the instructions in the original repo and it seems like conda defaults to using Python3.8 even though in the environment file the Python dependency is specified as "python>=3.7". This is likely happening because fpsim2 does not seem to be compatible with Python3.7

Since we use a base bentoml 3.7 environment, I am wondering if this is going to be an issue going forward? @GemmaTuron

**Comment by carcablop** [comment]
Hi @DhanshreeA.
When I was setting up the conda environment with python 3.7, I started getting messages at the time of installing some dependencies like these:
![imagen](https://user-images.githubusercontent.com/17841081/210662930-47010327-b333-4d62-8bfb-16677534155b.png)
![imagen](https://user-images.githubusercontent.com/17841081/210662974-71f8b6a9-90ef-41bd-afe9-6c3a982a8b2c.png)

When you tried it, did you get these types of messages/errors?. 
I thought that the problem could be related to my system, but what you said above makes me think that it may be related to what you say.
Have you managed to install the environment completely as indicated by the original repository, and tested the application, without errors?

**Comment by pauline-banye** [comment]
Hi @GemmaTuron could you grant me access to the eos5505 repo? I forked and cloned it but couldn't push the codes due to gitlfs. Then I tried cloning directly and pushing the changes to a new branch but I receive a `fatal: unable to access 'https://github.com/ersilia-os/eos5505.git`

**Comment by pauline-banye** [comment]
> Hi @DhanshreeA. When I was setting up the conda environment with python 3.7, I started getting messages at the time of installing some dependencies like these: ![imagen](https://user-images.githubusercontent.com/17841081/210662930-47010327-b333-4d62-8bfb-16677534155b.png) ![imagen](https://user-images.githubusercontent.com/17841081/210662974-71f8b6a9-90ef-41bd-afe9-6c3a982a8b2c.png)
> 
> When you tried it, did you get these types of messages/errors?. I thought that the problem could be related to my system, but what you said above makes me think that it may be related to what you say. Have you managed to install the environment completely as indicated by the original repository, and tested the application, without errors?

It is interesting that you came across these errors, however I did not encounter these. Could you confirm the branch you cloned the repo from? The development branch is the functional branch.

**Comment by pauline-banye** [comment]
Hi @DhanshreeA, Thank you so much for your suggestions however I am still encountering the LFS issue and I am yet to find a workaround. I uploaded the errors and steps I tried on this [issue](https://github.com/ersilia-os/eos5505/issues/1#issue-1520105886)

**Comment by DhanshreeA** [comment]
> Hi @DhanshreeA, Thank you so much for your suggestions however I am still encountering the LFS issue and I am yet to find a workaround. I uploaded the errors and steps I tried on this [issue](https://github.com/ersilia-os/eos5505/issues/1#issue-1520105886)

Perhaps @GemmaTuron can give you direct write access to the model repo for this?

**Comment by pauline-banye** [comment]
> > Hi @DhanshreeA, Thank you so much for your suggestions however I am still encountering the LFS issue and I am yet to find a workaround. I uploaded the errors and steps I tried on this [issue](https://github.com/ersilia-os/eos5505/issues/1#issue-1520105886)
> 
> Perhaps @GemmaTuron can give you direct write access to the model repo for this?

Possibly, I'm trying to upload in batches now. The model and codes separately. Let me see how it goes. It could also be the chemprop. If you're free, could we possibly go over this and try to identify what isn't necessary for this repo @DhanshreeA?

**Comment by pauline-banye** [comment]
@DhanshreeA It did not make any difference, I took out the model from the checkpoints folder and I removed some of the codes in the framework folder

**Comment by GemmaTuron** [comment]
> Hi @DhanshreeA, Thank you so much for your suggestions however I am still encountering the LFS issue and I am yet to find a workaround. I uploaded the errors and steps I tried on this [issue](https://github.com/ersilia-os/eos5505/issues/1#issue-1520105886)

Hi @pauline-banye ,

You should first upload the code to your forked repository https://github.com/pauline-banye/eos5505 (this should be independent or Ersilia permits). we will test this repo and once we are sure it works merge it into Ersilia's repositories. Are you failing to upload the code on your forked repository or you are pushing directly to Ersilia?

**Comment by GemmaTuron** [comment]
I will close this issue as the model dev has been taking place in #510
