### ISSUE TITLE
🐛 Bug: Typo in logging statements

### ISSUE THREAD

**Issue by pavithranair** [ersilia-os/ersilia#519]
### Describe the bug.

Typo in the logging statements in [model.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/core/model.py) and [throw_ersilia_exception.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/utils/exceptions_utils/throw_ersilia_exception.py).

### Expected behavior.

Replace "if" with "is" in [model.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/core/model.py) and replace "fill" with "will" in [throw_ersilia_exception.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/utils/exceptions_utils/throw_ersilia_exception.py).

### Screenshots.

![image](https://user-images.githubusercontent.com/66196840/210409873-b693f4e8-f692-4aa2-8113-c793cda4cb06.png)
![image](https://user-images.githubusercontent.com/66196840/210409973-bef0ac48-cf94-40f5-8b90-ff8d9024a70b.png)

### Operating environment

Ubuntu 18.04.2 lts

**Comment by DhanshreeA** [comment]
Related PR: https://github.com/ersilia-os/ersilia/pull/520

**Comment by GemmaTuron** [comment]
Hi @pavithranair thanks for catching this, the PR can be merged

**Comment by GemmaTuron** [comment]
Thanks @pavithranair I don't know why the checks were failing, but it looks fine now!
I've merged the PR
