### ISSUE TITLE
🦠 Model Request:  STOUT (SMILES-TO-IUPAC-name translator)

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#523]
### Model Name

IUPAC NAME GENERATOR

### Model Description

Translator from SMILES to IUPAC names. This model uses a deep learning neural machine translation (NMT) approach that allows conversion from a SMILE to an IUPAC (International Union of Pure and Applied Chemistry) name and vice versa.

### Slug

smiles-to-iupac-name-translator, iupac-name-generator

### Tags

neural machine translation, iupac names, smiles to iupac names, deep neural networks

### Publication

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8077691/

### Code

https://github.com/Kohulan/Smiles-TO-iUpac-Translator

### License

MIT 2.0

**Comment by carcablop** [comment]
Hello @GemmaTuron and @miquelduranfrigola.
I have tested the model in my windows subsystem for linux, ubuntu 20.04, with python 3.7, and it has run successfully.
I have created a small script that allows me to read an input .csv file and write the output with IUPAC names to a .csv file. I have used the input file eml_canonical.csv, the time to predict is 1 hour. This is the output: 
[out_predictions.csv](https://github.com/ersilia-os/ersilia/files/10348197/out_predictions.csv)
This is the log: 
[log_stout_eml_canonical_input.txt](https://github.com/ersilia-os/ersilia/files/10348199/log_stout_eml_canonical_input.txt)

**Comment by carcablop** [comment]
The model also does the conversion from IUPAC names to SMILES. Would Ersilia be interested in making this translation?

**Comment by GemmaTuron** [comment]
> The model also does the conversion from IUPAC names to SMILES. Would Ersilia be interested in making this translation?

yes, do you think these should be separated into two different models or the same predict function can guess what is the input (IUPAC or SMILES) and give the correct output?

**Comment by carcablop** [comment]
> > The model also does the conversion from IUPAC names to SMILES. Would Ersilia be interested in making this translation?
> 
> yes, do you think these should be separated into two different models or the same predict function can guess what is the input (IUPAC or SMILES) and give the correct output?

Hi @GemmaTuron 
No need to separate them into different models. The model has another function that does the conversion from IUPAC name to SMILES. I would just call the corresponding function and return another .csv file with the IUPAC name to SMILES conversions.

**Comment by carcablop** [comment]
Hi @GemmaTuron and @miquelduranfrigola 
I get this error when I try to fetch the eos4se9 model.
![imagen](https://user-images.githubusercontent.com/17841081/211127121-ed8caff6-498d-45a5-8086-4358bda767ee.png)

**Comment by carcablop** [comment]
Hi @GemmaTuron 
I have the same error about GIT LFS to push the changes to my eos4se9 model repository. Could you please help me with that. Thank you. 
![imagen](https://user-images.githubusercontent.com/17841081/211579039-b6669eab-66b7-4e3e-a764-efa7ff59e0a6.png)

**Comment by GemmaTuron** [comment]
Hi @carcablop 
Unfortunately as we have discussed before, if you fork a github repository that did not have git-lfs objects already you cannot push them either. I have solved it for the next eos-template derived models, but yours was created before the last fixes so the only solution is to clone the repository and do a pull request directly to it

**Comment by carcablop** [comment]
Hi @GemmaTuron 
I have cloned the repository from the original eos4se9 repository.
Then I have added the changes, I have done the commit and then the push to the origin main: I get the git-lfs error, the maximum size to load the checkpoints is 100MB and I have 112MB
This is the ouput of the git-error:
`> git push origin main:main
remote: error: Trace: d8ca092ddfe711e79c408e351709d466fd80d4d1036a222abea15596505b8b1d        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File model/checkpoints/translator_forward/variables/variables.data-00000-of-00001 is 112.87 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File model/checkpoints/translator_reverse/variables/variables.data-00000-of-00001 is 113.00 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
To https://github.com/ersilia-os/eos4se9.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ersilia-os/eos4se9.git'
`

**Comment by GemmaTuron** [comment]
Git - LFS objects are not being recognized because they are not included in the .gitattributes file. You need first to modify the gitattributes and add the objects to track (.data), push the gitattributes file first, and then try to upload the objects
So:

1. Clone the repo
2. Add .data to the gitattributes (if I am not wrong this is the file that is giving problems)
3. Add all the code except the .data objects and push changes
4. Add the .data objects and push again

**Comment by carcablop** [comment]
Hi @GemmaTuron. 
Step until 3: https://github.com/ersilia-os/eos4se9/commits/main

**Comment by carcablop** [comment]
update:
I add the .data objects in the .gitatributes  file like this: 
`*.data filter=lfs diff=lfs merge=lfs -text`
When I push I get the same error 
![imagen](https://user-images.githubusercontent.com/17841081/211863418-ffcd18bd-3345-4923-afec-478dcd7ff670.png)

**Comment by carcablop** [comment]
Hi @GemmaTuron.
The changes are already in the repository. https://github.com/ersilia-os/eos4se9/commits/main
for the .data, with the command that @DhanshreeA  recommends me to use 
`git lfs track .\model\checkpoints\translator_forward\variables\variables.data-00000-of-00001`
1.First push changes to the .gitatributes
2. push the .data files

**Comment by miquelduranfrigola** [comment]
Thanks @carcablop - great progress. Tracking Git LFS can be confusing. Thanks @DhanshreeA for assisting here.

**Comment by carcablop** [comment]
Hi @GemmaTuron 
The model eos4se9 fetch sucessfully in the Cli and predict. This is the output with "eml_canonicals.csv".  
[eos4se9_output.csv](https://github.com/ersilia-os/ersilia/files/10397129/eos4se9_output.csv)
It takes to predict : 1 hour 20min.
