### ISSUE TITLE
📑 Feature Request: Progress bar for model fetching

### ISSUE THREAD

**Issue by pavithranair** [ersilia-os/ersilia#528]
### Is your feature request related to a problem? Please describe.

While I was fetching some models, I noticed that there is no indicator of progress. As model fetching can usually take a few minutes, I think it would be helpful to indicate to the user that the model fetch is indeed in progress.  

### Describe the solution you'd like.

Some sort of visual representation of progress, such as a progress bar. I noticed that there was a similar issue opened quite a while back, #6.  However, in this issue, there were discussions about showing progress in terms of the total time required. Though this would be an ideal approach it seems quite tricky to implement as you would need a GitHub Access Token.

As an alternative, a progress bar that shows progress in terms of the number of steps completed would be much more straightforward.

**Comment by pavithranair** [comment]
Hi!

This is the solution I came up with it #529. Let me know if I should modify anything.

**Comment by GemmaTuron** [comment]
Thanks @pavithranair, we have had many discussions about the best way to implement this (for example in google colab we have a timer that lets you know how long did the model take to fetch) but as you say there is not a straightforward way of getting an exact progress bar. 
@miquelduranfrigola did we reach a final decision on that feature?

**Comment by miquelduranfrigola** [comment]
This is more difficult than it seems. As soon as we decide between Git LFS and AWS S3 buckets as a main storage solution for model weights/checkpoints, we will decide.

**Comment by GemmaTuron** [comment]
I'll close this issue as we have a temporal solution developed by @pavithranair 
When we are ready to move to S3 buckets we will discuss this again
