### ISSUE TITLE
📑 Feature Request: Remove SQLAlchemy dependency

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#530]
Ersilia has a dependency of SQLalchemy <=1.14 due to the BentoML version that we are using (0.11). To bypass this, we have decided instead of bumping ersilia to BentoML v>1.0 to fork BentoML 0.11 and make it slim, removing dependencies we don't need and services we don't use, like Yatai.

- [x] Fork BentoML v0.11
- [ ] Remove SQLalchemy dependency
- [x] Remove other unnecessary services

@leoank will start with the fork and first dependency removal

**Comment by GemmaTuron** [comment]
I have forked BentoML in Ersilia's org, we need to bump to the right commit to get v0.11
https://stackoverflow.com/questions/39542634/how-do-i-fork-an-older-version-of-a-github-project

**Comment by GemmaTuron** [comment]
Update:

We have downloaded v0.11 and created our own repo: https://github.com/ersilia-os/bentoml-ersilia

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron and @leoank :

I have made progress. I could not get rid of the SQLalchemy dependency but, at least, I have removed the strong requirements for older version in BentoML 0.11.0.

You can see the current trimmed BentoML 0.11.0 at: https://github.com/ersilia-os/bentoml-ersilia

In turn, now ersilia uses bentoml-ersilia: https://github.com/ersilia-os/ersilia/blob/master/setup.py

This means that, in practical terms, we can install ersilia in any python version >= 3.7, which I think is great progress.

I am not experiencing any issue with SQLalchemy at the moment, so I am not sure we need to remove it if we allow for flexibility in the versions.

It is virtually impossible to detach BentoML from Yatai, so I believe we will always have the Protobuf issue...

**Comment by GemmaTuron** [comment]
Good, thanks @miquelduranfrigola for the update

We will close this issue as completed then.
