### ISSUE TITLE
🦠 Model Request: IUPAC Name To SMILES Translator

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#534]
### Model Name

Translator from IUPAC Name to Smiles

### Model Description

Translator from IUPAC names to SMILES. This model uses a deep learning neural machine translation (NMT) approach that allows conversion from an IUPAC (International Union of Pure and Applied Chemistry) name to SMILES

### Slug

iupac-name-to-smiles-translator

### Tags

neural machine translation, iupac names, iupac names to smiles translation, deep neural networks, prediction of smiles from iupac names

### Publication

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8077691/

### Code

https://github.com/Kohulan/Smiles-TO-iUpac-Translator

### License

MIT 2.0

**Comment by carcablop** [comment]
Hi @GemmaTuron 
I have tried to push some changes to my model repository, and when I try to push I get errors like: "cannot upload new objects to repository".
This is the error:
![imagen](https://user-images.githubusercontent.com/17841081/211948142-025dcfef-b8ca-450b-babb-70d130e845d7.png)

These are the files I'm trying to upload:
![imagen](https://user-images.githubusercontent.com/17841081/211948300-2f484065-6527-4c74-ab0f-d21208098401.png)

I haven't tried to upload the .data files yet.

**Comment by carcablop** [comment]
Update @GemmaTuron 
This is the input file iupac_names with which he tested the code: 
[iupac_names_small.csv](https://github.com/ersilia-os/ersilia/files/10397195/iupac_names_small.csv)

And this is the output file of the IUPAC_NAMES2SMILES predictions.
[smiles2iupac.csv](https://github.com/ersilia-os/ersilia/files/10397196/smiles2iupac.csv)

**Comment by GemmaTuron** [comment]
Hi  @carcablop

this results look great! For the errors in pushing: you should be able to push all the code (not sure about git-lfs objects though). Try pushing all the code and merging the fork and then we see about the git lfs objects if there are any

**Comment by carcablop** [comment]
Hi @GemmaTuron 
 I open a pull request https://github.com/ersilia-os/eos5ecc/pull/1 of the model. 
Although an error was generated when passing the test, which I don't quite understand what it is about.
Thanks so much.

**Comment by GemmaTuron** [comment]
The tests are still in development so they might fail, don't worry about it yet.
I've merged the commit, and added the model to airtable with the slug iupac2smiles  
The issue is that we cannot accept TEXT inputs through ersilia (there are checks for SMILES), so we need to work on this feature. I'll add this as stuck in Projects and let you know once it works

**Comment by GemmaTuron** [comment]
This model needs #603  to work

**Comment by GemmaTuron** [comment]
Does the #603 advances make it possible to incorporate this model now?

**Comment by GemmaTuron** [comment]
We will not focus on including new types of input at the moment. I will close this issue.
