### ISSUE TITLE
🐛 Bug: The model hub website is not working to search for models.

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#539]
### Describe the bug.

The Ersilia model hub website is failing to fetch models The following error appears: 
`"Something went wrong!
 Unable to fetch Airtable records. Unknown field name: "End Date".`
![imagen](https://user-images.githubusercontent.com/17841081/212209051-4390ab0f-8f85-47a0-a178-9b18512b84d6.png)

### Describe the steps to reproduce the behavior

1 Go to this URL: https://www.ersilia.io/model-hub  

### Operating environment

Ubuntu 20.04.3 LTS

**Comment by GemmaTuron** [comment]
Thanks,
We did some updated to the backend of the EMH and this caused a small conflict which is solved now
