### ISSUE TITLE
Correct grammar in the Roadmap section in the ReadME file

### ISSUE THREAD

**Issue by kbetty** [ersilia-os/ersilia#54]
Within the Road map section there is a need to correct as improvement to the read me file. cc: @GemmaTuron

**Comment by kbetty** [comment]
Have made the PR at https://github.com/ersilia-os/ersilia/pull/55 to address the issue.

**Comment by GemmaTuron** [comment]
Hello @kbetty 

Thanks, please check the comment I left on the PR and try to find the error existing in our README!
