### ISSUE TITLE
Model template upgrade

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#545]
We are upgrading the model template so that it requires less input from users.

In particular:

- [x] No API names, unless otherwise specified. The default model template will only have a `run.sh` file.
- [x] CSV files by default
- [x] Simple checks to make sure that the number of output lines matches the number of input lines

**Comment by GemmaTuron** [comment]
The last requirement is updated here: 705e17c2c4650e2d4c94ad6170465bc3af26792f
