### ISSUE TITLE
📑 Feature Request: Containerize every model in the Ersilia Model Hub

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#546]
### Is your feature request related to a problem? Please describe.

Managing dependencies through conda does not always provide the right level of isolation. We need to have each model containerized and stored in the DockerHub.

Folks at DigitalOcean have already made great progress in this front, so it should be possible to do.

### Describe the solution you'd like.

We can containerize each model, either following BentoML syntax or DigitalOcean solution.

**Comment by miquelduranfrigola** [comment]
These are the necessary steps

- [ ] Build docker images based on Digital Ocean Dockerfiles: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/model-deploy . There is a `build` method in the `DockerManager`. Both the `base` and the `model` images can be created.
- [ ] Method to push a given image to the `ersiliaos` DockerHub container registry. There is a class for that purpose in https://github.com/ersilia-os/ersilia/blob/master/ersilia/publish/dockerhub.py
- [ ] At fetch time, offer the possibility to pull the image from the DockerHub (instead of downloading and building the conda environment as per usual).
- [ ] At serve time, use a docker container if available.
- [ ] At delete time, remove the images and the containers from the local docker registry.

**Comment by miquelduranfrigola** [comment]
There are a few relevant aspects related to fetch and serve:

- [ ] Transfer **all** necessary information to the `bentoml.yml` file, so that we can have everything we need accessible from the same URL, including output types, etc. This is crucial for input and output adapters. Anything accessible in the `bentoml.yml` will be then accessible through the `/metadata` endpoint. This will completely remove the need for fetching a model from GitHub, work with `dest` and `repository` folders, etc.
- [ ] Correspondingly, at `serve` time, we need to gracefully access metadata (if available), else we just read the data from the local filesystem (`dest` and `repository`) as we have been doing up to now.
- [ ] Several functions in Ersilia now check for the presence of a `dest` or `repository` file. These functions should now check whether a model is available simply as a docker container, too. Another possibility would be to create some placeholders in the `~/eos` subfolder structure.

**Comment by miquelduranfrigola** [comment]
Note: we may also consider adding a "Deploy to Digital Ocean" button in the `eos-template`. This would be quite elegant. It can be done as follows: https://docs.digitalocean.com/products/app-platform/how-to/add-deploy-do-button/

**Comment by miquelduranfrigola** [comment]
We will consider the following models to get started:

- [ ] eos3be5: Molecular weight (easy and lightweight)
- [ ] eos4e40: Antimicrobial activity (heavier)
- [ ] eos9f6e: Synthetic feasibility
- [ ] eos4u6p: Chemical checker signatures

In addition, we may include a model related to a different input (text). @Femme-js is working on this at the moment.

**Comment by miquelduranfrigola** [comment]
Related to my latest comment - please let's not worry about the text-based input for now. Let's just focus on the 4 listed models.

**Comment by miquelduranfrigola** [comment]
**Progress update**: There is now a functional GitHub Actions workflow doing the build and push.

Provisionally, this workflow can be seen in: https://github.com/ersilia-os/eos7kpb/blob/main/.github/workflows/upload-model-to-dockerhub.yml, although we have to migrate it eventually to the `eos-template`.

Remaining tasks:

- [ ] Provide functionality for multiple architectures.
- [ ] Update description and README to DockerHub.
- [ ] Versioning.

**Comment by miquelduranfrigola** [comment]
We need to update the base ersilia image before as a github action

**Comment by miquelduranfrigola** [comment]
Also, we need to update README and description in Dockerhub. This can be done, for example, with the following Action: https://github.com/marketplace/actions/docker-hub-description

**Comment by miquelduranfrigola** [comment]
Substantial progress:

- We have created a workflow that uploads models to DockerHub. I is now available from the template.
- Versioning is automatically managed and reflected in DockerHub.
- The README file is automatically uploaded to DockerHub.

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 

Can we:
- Review the checklists in this issue and see if they are completed or missing
- Revise old issues about Docker and decide if we can close them given these new updates: #477 #494 #496

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 
to test the workflow, I have:
- Added the upload-to-dockerhub.yml file to the eos2gw4 model (eos compound embeddings). 
- Run the workflow: took [15 min](https://github.com/ersilia-os/eos2gw4/actions/runs/5046160145/jobs/9051313479) to build and push the image
- Download the image from our [public Docker profile](https://hub.docker.com/r/ersiliaos/eos2gw4)
- Run it locally in my DockerHub (installation of DockerHub is a whole another issue!)
The workflow works fine :)

We now need to work on 
- [ ] Ersilia light package to run only docker containers
- [ ] Add docker option in Ersilia (half done)
- [ ] Add workflows to all repos
- [ ] Add instructions for end users and developers as well for Docker

**Comment by GemmaTuron** [comment]
We have completed the workflow to
- Dockerize models and upload to DockeRHub
- Upload them to S3 for download outside GitLFS

We will now work on modifying each model available in the Hub (See projects for an Update)

**Comment by miquelduranfrigola** [comment]
This is mostly done now!

1. Ersilia can fetch from dockerhub
2. Serving from DockerHub and locally installed models works indistinctly
3. Models can also be uploaded to S3

I am closing the issue, with some notes:

1. We have created a light package, [ersilia-client](https://github.com/ersilia-os/ersilia-client) to query deployed models.
2. Most models are not yet containerized.
