### ISSUE TITLE
🐛 Bug: Web scraping models

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#556]
### Describe the bug.

I am opening this issue to discuss about the models based on web scraping (those for which the model is not provided nor the dataset so we have done a website redirect and just run predictions on their servers).
This is a dangerous approach since:
- Users might not be aware they are posting inputs online
- We have 0 control over the functionality of the website.
For example, I was just checking eos3d3r ([CardPred](http://bioanalysis.cau.ac.kr:7050/)) but their server does not work when you input a molecule, so now the model in the Hub does not work either and there is nothing we can do about it

### Operating environment

Ubuntu 20.04 LTS

**Comment by miquelduranfrigola** [comment]
I completely agree with your view here, @GemmaTuron, although sometimes it will be necessary to do it, as more and more models are moving towards providing REST APIs for accessing them.

Regular maintenance is the only solution.

Another solution is getting the **surrogate** models as soon as possible, so at least we have the approximate version of them in a persistent mode

**Comment by GemmaTuron** [comment]
I would go for surrogate models and that's it, perhaps using Ersilia Compound Embeddings?

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 
Can we decide what to do? This is also linked to #731 
I'll close this issue and leave the discussion in the mentioned one
