### ISSUE TITLE
[Idea] Templated README files

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#558]
Is there a way to guide users to write good README files? (Converting JSON to markdown) => Jinja template engine (Python) or Numchucks (JS) can populate variables with keys read from a metadata.json file when the repo is first initialized. (Nice to have but not a must.)

**Comment by miquelduranfrigola** [comment]
Hi @GrantBirki! There is a method now in Ersilia that, given a model identifier, creates a README file and pushes it to the repository in the `ersilia-os` organization: https://github.com/ersilia-os/ersilia/blob/master/ersilia/publish/thereadme.py

I think this is all we need. As you suggested, we can now run a very simple python script that we can run for all models to update their README file. Something this simple did work:

```python
from ersilia.publish.thereadme import ReadmeUpdater

ru = ReadmeUpdater("eos4e40")
ru.update()
```

As soon as we are happy with the README file template (at the moment it is very sketchy), we will run this code for all the old models. For the new ones, we can incorporate this step at merge time (i.e. after we have approved the metadata written by the user).

I hope this sounds good!

**Comment by megamanics** [comment]
@miquelduranfrigola 

1. yes you are correct Add `[skip ci]` or `[skip actions]` to the commit message to skip the workflow run.
2. Also in subsequent run if If there are no updates there will be change to the file output by the script hence no commit will be added due to unchanged files.

**Comment by GrantBirki** [comment]
I had no idea you could skip CI by adding [text into a commit message](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), who knew!

**Comment by D1M1TR10S** [comment]
Problem: At merging time, when the action is triggered, we need to update the README. Since they're making a change to the repo, they're making a change to the action, Which could cause an infinite loop.

Solution: Add "skip CI" to their commit message will prevent an infinite loop.
