### ISSUE TITLE
🦠 Model Request: GeoGNN Molecular Representation Prediction

### ISSUE THREAD

**Issue by karthikjetty** [ersilia-os/ersilia#561]
### Model Name

GeoGNN Molecular Representation Prediction

### Model Description

GeoGNN uses Graph Neural Networks to represent atoms, bonds, and bond angles in a molecule which can be used to predict properties of molecules

### Slug

GEM-representation-learning

### Tag

GNN

### Publication

https://www.nature.com/articles/s42256-021-00438-4

### Source code

https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/pretrained_compound/ChemRL/GEM

### License

N/A

**Comment by karthikjetty** [comment]
Currently working on reproducing the results from the research paper. Looks like it will take about 1-2 days for the model to run on my computer. While this is happening, I will go ahead and start uploading parts of the model onto Ersilia.

**Comment by GemmaTuron** [comment]
Hi @karthikjetty 

Please provide more details on which results are you trying to reproduce. I thought the model weights were provided, do we need to retrain them?
Also please specify the steps you have taken to incorporate the model in the Ersilia framework.

Thanks!

**Comment by karthikjetty** [comment]
> Hi @karthikjetty
> 
> Please provide more details on which results are you trying to reproduce. I thought the model weights were provided, do we need to retrain them? Also please specify the steps you have taken to incorporate the model in the Ersilia framework.
> 
> Thanks!

The model weights were provided, however I am finetuning them. In addition, the model does not currently have an easily accessibly predict function in the library–as a result, I am working on taking the pretrain.py function provided in the library. So, I am currently modifying the pretrain.py function to just have a predict functionality for inputted models.

**Comment by karthikjetty** [comment]
>Hi [@karthikjetty](https://github.com/karthikjetty)
>Please provide more details on which results are you trying to reproduce. I thought the model weights were provided, do >we need to retrain them? Also please specify the steps you have taken to incorporate the model in the Ersilia framework.
>Thanks!

The model weights were provided, however I am finetuning them. In addition, the model does not currently have an easily accessibly predict function in the library–as a result, I am working on taking the pretrain.py function provided in the library. So, I am currently modifying the pretrain.py function to just have a predict functionality for inputted models.

**Comment by karthikjetty** [comment]
In the model/framework/code/GEM folder, I have added several files that show my train of thought in how I plan on getting through the models. The four files I have created are "pred_using_pretrain_single_compound.py", "run_inference_simple.py", "run_inference_test_hardcode".py, and "run_inference.py".

I am currently working through "pred_using_pretrain_single_compound.py", where I am trying to simply get a prediction of the graphs for a single molecule. In the file "pred_using_pretrain_single_compound.py", I use the tasks in tox21 simply as a baseline to get a graph out of the model (although I should not necessarily be using the tox21 dataset tasks because the model wasn't finetuned to perform on those tasks).

So, now I have graphs1 and graphs2. The first corresponds to the graph that has the atoms as nodes and the bonds as edges. The second graph has the bonds as nodes and bond angles as edges.

I will keep looking for a function that combines the two. 

Meanwhile, I was wondering what I should do to get the embeddings of the model. This is my primary concern at this point, since I'm not really sure where to start with getting the embeddings.

Below, I've uploaded a screenshot of warnings I get when trying to do predictions. These warnings don't have an implication on the model, but I am still confused where they are coming from.

<img width="939" alt="Screenshot 2023-02-14 at 3 53 52 AM" src="https://user-images.githubusercontent.com/66660580/218686394-bbd5cf8b-3977-4dbe-9a24-03fa592185b2.png">

The bigger issue, I am facing, is described in this screenshot below. Essentially, I am trying to enter both of the graph representations of an atom into the model (which is what the research paper described as the input). 

<img width="873" alt="Screenshot 2023-02-14 at 3 55 47 AM" src="https://user-images.githubusercontent.com/66660580/218686920-502810d0-17bf-46f3-9a9c-8c1cf0c05b82.png">

However, the model doesn't take these as inputs (saying it's the wrong number of arguments). I have tried only entering one argument, but I get the error in the image below. 
<img width="918" alt="Screenshot 2023-02-14 at 3 58 35 AM" src="https://user-images.githubusercontent.com/66660580/218687564-38ec629e-2be7-4090-8be6-679070825348.png">


I think there are some functions I need to either 1) combine the two graphs or 2) use another input. 


I am attempting to get these predictions to essentially get the model running on my system. While I work through this bug, I think I can also simultaneously work on getting the embedding layer of the model. However, I'm not exactly sure how to get the embedding layer from the model (or what I should be extracting to receive the embedding layer). I understand why we might want the embedding layer, but I'm not sure how to extract it from the variable "model".

**Comment by karthikjetty** [comment]
I am currently parsing through featurizes.py and model.py in model/framework/code/GEM/src as well as model/framework/code/pahelix/featurizers to see where the inputs of the functions to see if there are some missing parameters.

**Comment by karthikjetty** [comment]
I was able to print the model and got the following output. 

DownstreamModel(
  (compound_encoder): GeoGNNModel(
    (init_atom_embedding): AtomEmbedding(
      (embed_list): LayerList(
        (0): Embedding(124, 32, sparse=False)
        (1): Embedding(22, 32, sparse=False)
        (2): Embedding(17, 32, sparse=False)
        (3): Embedding(14, 32, sparse=False)
        (4): Embedding(15, 32, sparse=False)
        (5): Embedding(7, 32, sparse=False)
        (6): Embedding(14, 32, sparse=False)
      )
    )...

It goes on a lot more to describe each embedding layer. I'm still not sure how to extract the last embedding layer however.

**Comment by DhanshreeA** [comment]
Hi @karthikjetty you could potentially just rebuild a new model from GeoGNNModel's children nodes minus the last fully connected layer (this also includes bias!)
I think the PaddlePaddle maintainers are also quite active so you could just create an issue within their repo and confirm if this approach is right?

**Comment by karthikjetty** [comment]
> Hi @karthikjetty you could potentially just rebuild a new model from GeoGNNModel's children nodes minus the last fully connected layer (this also includes bias!) I think the PaddlePaddle maintainers are also quite active so you could just create an issue within their repo and confirm if this approach is right?

I made an issue in their repo but have yet to receive confirmation from them about the correct approach. I'm not sure what you mean by children nodes?

**Comment by GemmaTuron** [comment]
Hi @karthikjetty,

Can you please provide an update on the model status?

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron - perhaps we put this model on hold?

**Comment by GemmaTuron** [comment]
We have decided to archive this model for the time being. I'll close this issue and archive the eos1bba repo
