### ISSUE TITLE
🦠 Model Request: Prediction of human microsomal stability

### ISSUE THREAD

**Issue by carcablop** [ersilia-os/ersilia#565]
### Model Name

PredMS: human liver microsomal stability

### Model Description

PredMS classifies compounds as metabolically stable (≥50% remaining at 30 min) or unstable (<50% remaining at 30 min) in human liver microsomes. The model was trained on an in-house dataset of 1917 compounds (1049 stable and 868 unstable), and validated on a external test dataset of 61 compounds.

### Slug

pred-ms

### Tag

Metabolism,Microsomal Stability,Human,ADME

### Publication

https://academic.oup.com/bioinformatics/article/38/2/364/6369504

### Source Code

https://bitbucket.org/krictai/predms/src/master/

### License

None

**Comment by carcablop** [comment]
Hi @GemmaTuron 
I have tested the original model following the installation steps and I find errors when creating the environment and installing the packages
In the original model the environment is created from the environment.yml file. In my system it was not possible to install the environment in this way, my system and my conda environment start to fail, more specifically when trying to install numpy and pandas, and all the libraries of my windows subsystem for linux tell me that they are not there available. I would like to investigate this behavior further as this is the second time it has happened to me when I try to install packages in this way with a .yml file.
Attached error log. 
[log_predms_fail.txt](https://github.com/ersilia-os/ersilia/files/10453135/log_predms_fail.txt)

So I delete the environment and try to install the dependencies manually, only to realize that the version of pandas it's trying to install is incompatible with numpy.
Attached log.
[numpy_pandas_fail.txt](https://github.com/ersilia-os/ersilia/files/10453163/numpy_pandas_fail.txt)

Finally, I opted to re-install everything again and pandas to the newer version. This did not fail and I was able to successfully run the model on my local with the conda environment installed python 3.7.
List dependencies installed: 
`pip install numpy==1.16.1
pip install keras==2.3.1
pip install protobuf==3.10.0
pip install scikit-learn==0.20.2
pip install scipy==1.2.0
pip install sklearn==0.0
pip install tensorflow-gpu==2.0.0
pip install tqdm==4.31.0
pip install joblib
pip install mordred
pip install rdkit
pip install pandas`

**This is the output file with the predictions.**
[results.txt](https://github.com/ersilia-os/ersilia/files/10453207/results.txt)

**Comment by GemmaTuron** [comment]
Hi @Carolina, this looks good thanks for the work!

**Comment by GemmaTuron** [comment]
\approve

**Comment by GemmaTuron** [comment]
@carcablop where did you find that the license was an MIT license?
Also, I've been working on the metadata files. For the PR to be accepted, they will have to fulfill some requirements. I am adding [here](https://github.com/carcablop/eos5ged/pull/1) a metadata.json file with the correct information format. I just need the confirmation of the license,'cause I haven't found any.

**Comment by carcablop** [comment]
Hi @GemmaTuron 
This model does not provide a license. It was my mistake to have added MIT as license.

**Comment by carcablop** [comment]
Hello @GemmaTuron . 
Progress update. 
In this work, to calculate the microsomal stability of a smile, they first calculate the molecular descriptors using the python package [mordred ](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0258-y). Molecular descriptors return the numerical value that represents the characteristic of a molecule based on its structure. From these descriptors a data subset with 200 descriptors is created, which are passed as input to the model.

The model runs successfully for the input data provided by the author as an example, but for the input file "eml_canonical.csv" the model fails for some molecules such as "CC(=O)O", generating the following error from `KeyError: "['AATS5i', 'GATS5m', 'GATS5i', 'GATS5p', 'GATS5s', 'MATS5d', 'AATSC5p', 'MATS5p', 'AATS5p', 'MATS5i', 'AATSC5i', ' GATS5pe', 'AATS5v', 'GATS5se', 'MATS5s', 'GATS5d'] not in index"` ,
[key_error.txt](https://github.com/ersilia-os/ersilia/files/10485786/key_error.txt)
 when trying to select a subset of data with the 200 selected descriptors for the model.
Which brings me to review the data set for molecular descriptors. What I find is that for those molecular descriptors, the model returns these values as NaN, of type object, returning a string like this: `"invalid value encountered in double_scalars`". And in the model, to avoid such errors as: `ValueError: Input contains NaN, infinity or a value too large for dtype('float32').` implement the function to generate a data subset of molecular descriptors with values of type "float64" and "int". Therefore, it does not take into account for that data set the descriptors that return null values, generating the error that it does not find those columns in that data subset of the 200 descriptors selected by the author of the model.
Tests were performed on the app provided by the model author, passing the molecule "CC(=O)O" as input, generating a message of smile string is invalid. https://predms.netlify.app/

As a possible alternative to run the model successfully, it is proposed to create a function that converts Null values to zeros and avoid the key error when trying to create the data subset for the 200 molecular descriptors.
It remains to consult with the author of the model if these changes can be made in the model or not.
These are the outputs obtained with the changes in the model: 

[results.txt](https://github.com/ersilia-os/ersilia/files/10485789/results.txt)

**Comment by GemmaTuron** [comment]
@carcablop 

I have created this new repository that has all the updated workflows. As you will see I've already formatted the metadata.json file with the necessary inputs so you don't need to change anything there.
Just fork and transfer the code and data from the deleted repo to this new one.

**Comment by GemmaTuron** [comment]
@carcablop 
when this model is ready let me know and I'll add it to the testing list!

**Comment by carcablop** [comment]
Hi Gemma.
Update the model.
I wrote by email to the author of the model, due to the problems that appear for some smiles of the "eml_canonical" file, which the model predms indicate that they are not valid. The author did not respond to the doubts and suggestions that had been raised in the previous meets and previous comments, in any case, the modifications were made, that is, for those smiles where the descriptors are invalid, I converted those null values to zero (changes made here: https://github.com/carcablop/eos7akz/blob/main/model/framework/code/predms.py#L44 and the model run successfully, but the output varies a lot with the last change, this was done by comparing the probability of the "valid" smiles that is calculated with the initial model (without changes) vs the probability of the same smile with the change made (0.8 and with the change the probability is 0.5). The output of the model tested within ersilia is attached
[eos7akz.csv](https://github.com/ersilia-os/ersilia/files/10540814/eos7akz.csv)
These are the changes I've made, updated in my repository: https://github.com/carcablop/eos7akz/commit/1543bcd0a7e02d12a7dac59aa81774347a16cc48
Therefore, it is proposed to retrain the model.

**Comment by carcablop** [comment]
Hello @GemmaTuron 
The training and validation data used by PredMS are internal data that was obtained from the Korea Research Institute of Chemical Technology (Daejeon, Korea). I attach a screenshot.  
![imagen](https://user-images.githubusercontent.com/17841081/215817715-dbe09e72-381d-4672-b832-07a48876539d.png)

To request the data from the author, a reasonable justification must be given.:
![imagen](https://user-images.githubusercontent.com/17841081/215819474-d2ac0c4a-aab0-4739-9e7b-ffd03c484e7f.png)

**Comment by GemmaTuron** [comment]
Hi @carcablop !

Thanks, this is disappointing because if we did not get an explanation of how the missing values are treated I doubt we will be able to get the training data... we might have to skip this model then. I'm very sorry about that!

**Comment by GemmaTuron** [comment]
Since we have not been able to solve the missing values issue, I will close this model request and archive the repository, to avoid confusions.
So sorry about the work @carcablop, many thanks for your efforts!
