### ISSUE TITLE
🦠 Model Request: Test model

### ISSUE THREAD

**Issue by ersilia-contributor** [ersilia-os/ersilia#569]
### Model Name

Test Model

### Model Description

Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum 

### Slug

test-model

### Tags

Malaria,P.falciparum,IC50

### Publication

https://ersilia.io

### Code

https://ersilia.io

### License

MIT

**Comment by GemmaTuron** [comment]
this test is complete
