### ISSUE TITLE
Grammatical error in https://www.ersilia.io/  site

### ISSUE THREAD

**Issue by SHRIYA1706** [ersilia-os/ersilia#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SHRIYA1706** [comment]
In 'our strategy' section at the content of the foster in-country research there should be working on instead of working in infectious and neglected diseases.

**Comment by miquelduranfrigola** [comment]
Solved and closing issue. Thanks for the catch!
