### ISSUE TITLE
🦠 Model Request: Test Model 2

### ISSUE THREAD

**Issue by ersilia-contributor** [ersilia-os/ersilia#570]
### Model Name

Tes model 2

### Model Description

Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum 

### Slug

test-model-2

### Tags

Malaria,P.falciparum,IC50

### Publication

https://ersilia.io

### Code

https://ersilia.io

### License

MIT

**Comment by GemmaTuron** [comment]
this test is complete
