### ISSUE TITLE
🦠 Model Request: Finetuned ImageMol for SARS-Cov2 assays from NCATS OpenData

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#572]
### Model Name

SARS-CoV-2 Anti viral screening

### Model Description

Representation Learning Framework that utilizes molecule images for encoding molecular inputs as machine readable vectors for downstream tasks such as bio-activity prediction, drug metabolism analysis, or drug toxicity prediction. The approach utilizes transfer learning, that is, pre-training the model on massive unlabeled datasets to help it in generalizing feature extraction and then fine tuning on specific tasks. This model will be fine tuned on 13 assays concerned with a number of target categories ranging from viral entry to toxicity in humans. These interactions are formulated as binary classification tasks

### Slug

sars-cov-2-antiviral-screen

### Tag

SarsCov2,classification

### Publication

https://www.nature.com/articles/s42256-022-00557-6

### Source code

https://github.com/HongxinXiang/ImageMol

### License

MIT License

**Comment by DhanshreeA** [comment]
The data statistics for SARS-CoV-2 assays are as follows:
![image](https://user-images.githubusercontent.com/7213136/213671215-bf4a1d0e-a626-4144-86a7-489c0f9c2139.png)

**Comment by DhanshreeA** [comment]
Need clarity on fine tuning strategy similar to this: https://github.com/ersilia-os/ersilia/issues/571#issuecomment-1398176443

**Comment by DhanshreeA** [comment]
Waiting for the authors to get back with fine tuned models for these assays as reproducing the results from the paper has been challenging because the exact choice of hyper parameters is not known, and takes some experimentation when considering different possible values from the range of values the authors have provided in their supplementary materials.

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron could you please add me to this repository? the authors have finally shared the models and since this repo is old, it doesn't have the mock.csv tracked in LFS. Alternatively, you could just update the mock.csv in this repo.

**Comment by GemmaTuron** [comment]
Great to hear that. Also added #571 , you should be good to edit both!
If it is easier, we can also approve a new repository which will have all the checks on it, depending on how much you already worked in the previous repo that might be the most straightforward, let me know

**Comment by DhanshreeA** [comment]
I have completed both 😬 and need to only commit the code, so I guess we
can just use these two repos.

**Comment by GemmaTuron** [comment]
cool, if you can copy the latest workflow files in your fork, then they will be merged and triggered in the future prs, automatically updating airtable etc, would be super helpful!

**Comment by DhanshreeA** [comment]
Cool, I'll do that!

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron, quick question: In the interpretation field, I think it will be good to describe what each of the 13 assays is according to the data description above. What do you think? Same for

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA !

Maybe just list the assay names and mention each column is one of the results? Something that is quick but gives people a good sense of what they are looking at!

**Comment by DhanshreeA** [comment]
Associated PR: https://github.com/ersilia-os/eos4cxk/pull/1
Model is ready to be tested by other volunteers.
