### ISSUE TITLE
🦠 Model Request: Test New Template

### ISSUE THREAD

**Issue by ersilia-contributor** [ersilia-os/ersilia#574]
### Model Name

Test Model

### Model Description

Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum 

### Slug

lorem-ipsum

### Tag

ESKAPE

### Publication

https://ersilia.io

### Source Code

https://ersilia.io

### License

GPL-3.0

**Comment by GemmaTuron** [comment]
this test is completed
