### ISSUE TITLE
🦠 Model Request: MolTrans: Molecular Interaction Transformer for drug--target interaction prediction

### ISSUE THREAD

**Issue by karthikjetty** [ersilia-os/ersilia#588]
### Model Name

MolTrans

### Model Description

Using Deep Learning for Drug-Target Interaction Prediction

### Slug

MolTrans

### Tag

Transformer

### Publication

https://academic.oup.com/bioinformatics/article/37/6/830/5929692

### Source Code

https://github.com/kexinhuang12345/moltrans

### License

Apache (I believe)

newline

**Comment by GemmaTuron** [comment]
I will close this issue as the Hub is not ready to implement these kind of models yet. We will come back to it in the future
