### ISSUE TITLE
issue #57 -1.  In 'our strategy' section at the content of the foster in-country research there should be working on instead of working in infectious and neglected diseases.  2. Can I know what are we planning to include in the volunteer part in the footer section to know if I can contribute or help in any way if possible.

### ISSUE THREAD

**Issue by SHRIYA1706** [ersilia-os/ersilia#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by miquelduranfrigola** [comment]
Thanks @SHRIYA1706. Can you try to do a PR to address this issue? That'd be good practice!
As for the planning, we are working on a communication through Slack. Stay tunned!
