### ISSUE TITLE
📑 Feature Request: Improving Contributing MD

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#592]
### Is your feature request related to a problem? Please describe.

The [contribution file](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md) could be much more exhaustive, using as templates some of the suggestions by @DhanshreeA 
https://scikit-learn.org/stable/developers/contributing.html
https://pandas.pydata.org/docs/development/index.html

### Describe the solution you'd like.

Our current interns and contributors to modify the Contributing.md with the information they would have found useful to have

Please let me know here if you can help us out in this issue and I'll assign it to you :)

### Describe alternatives you've considered

I can try to work on it but I think actual contributors will do a much better job of covering the things they needed to see

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron I would love to contribute to this. Can you point me to some documentation we may already have about the ersilia code base? I have some understanding of it from debugging issues within model incorporation but a high level overview would be much appreciated. :)

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA and all,

As we just discussed,the best documentation is on GitBook. Here, we are looking at a contributing.md that explains the basic contribution workflow:

- How to open issues and what should go in each type of issue
- How does git actions work and what do contributors need to look for - for example, wait when doing a PR or a push to make sure it is not failing the tests
-etc

So actually a quite "high level" documentation

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

Going through the above discussion, I would like to add **'Landing your pull request'** and describe it in detail in contributing.md. 

Should I open another issue for it, or you can assign one to me?

**Comment by GemmaTuron** [comment]
@Femme-js 

Sounds good, go ahead and make a PR to modify the contributing.md

**Comment by GemmaTuron** [comment]
I'll close this comment due to inactivity, I've made minor changes to the file, including a comment from @Femme-js
