### ISSUE TITLE
Improving the search engine in https://airtable.com/shrUcrUnd7jB9ChZV/tblZGe2a2XeBxrEHP

### ISSUE THREAD

**Issue by SHRIYA1706** [ersilia-os/ersilia#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SHRIYA1706** [comment]
When searching for some keywords it is showing 0 of 0 when no result is found. What we can do is we can show the best match results or related suggestions when any keyword is searched for which is not directly present, like some synonyms or some related symptoms and diseases as suggestions to help them get a related close model.

**Comment by miquelduranfrigola** [comment]
This is of course a good idea. There must be some built in function in Airtable to do so. Do you know of any?

**Comment by anamika-yadav99** [comment]
@SHRIYA1706  @miquelduranfrigola One easier way to achieve this would be adding tag words in the card. Later we could add those tag words in the $ersilia catalog --help . This would also help search using the tag words.

**Comment by miquelduranfrigola** [comment]
I think this solution is plausible @anamika-yadav99! I am adding a "tag" field in the Airtable right now. As soon as I have filled tags for a reasonable number of models, I will open an issue to include a tag-filtering option in the ersilia catalog command.
