### ISSUE TITLE
🦠 Model Request: Parallel Artificial Membrane Permeability Assay (PAMPA) 5

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#601]
### Model Name

Parallel Artificial Membrane Permeability Assay (PAMPA) 5

### Model Description

Cell membrane permeability is important for determining oral absorption and bioavailability of drug molecule. Parallel artificial membrane permeability assay (PAMPA) is a low-cost alternative to cellular models for early ADME screening.

### Slug

parallel-artificial-membrane-permeability-assay-5

### Tag

ADME

### Publication

https://www.sciencedirect.com/science/article/pii/S0968089621005964

### Source Code

https://github.com/ncats/ncats-adme/tree/development

### License

None

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

What is the difference between this and the pampa issue #602  and the issue #585?

**Comment by pauline-banye** [comment]
Hi @GemmaTuron from what I can tell, there's barely any difference between both. The other seems to be a slightly updated version of this one.

However I have been working on both today and the results returned from this more consistent with what is being returned from NCATS. I suggest we go with this one instead of the other.

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

I see the issue #585 is also refering to PAMPA 5.0, so I am confused as to which model are you incorporating in each.
When you say the results are consistent or not, can you provide examples?
