### ISSUE TITLE
🦠 Model Request: Parallel Artificial Membrane Permeability Assay (PAMPA) 7

### ISSUE THREAD

**Issue by pauline-banye** [ersilia-os/ersilia#602]
### Model Name

Parallel Artificial Membrane Permeability Assay (PAMPA) 7

### Model Description

Cell membrane permeability is important for determining oral absorption and bioavailability of drug molecule. Parallel artificial membrane permeability assay (PAMPA) is a low-cost alternative to cellular models for early ADME screening. PAMPA 7 improves upon the previous PAMPA 5 assay with the addition of new membrane types.

### Slug

parallel-artificial-membrane-permeability-assay-7

### Tag

ADME

### Publication

https://pubmed.ncbi.nlm.nih.gov/16922646/

### Source Code

https://github.com/ncats/ncats-adme/tree/development

### License

None

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

Can you please share which outputs are you getting here that are inconsistent?

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, 
I executed the codes multiple times. Everytime I run the codes, it returns different results. These are the outputs from 4 different iterations. 
[out.csv](https://github.com/ersilia-os/ersilia/files/10861400/out.csv)
[out1.csv](https://github.com/ersilia-os/ersilia/files/10861401/out1.csv)
[out2.csv](https://github.com/ersilia-os/ersilia/files/10861403/out2.csv)
[out3.csv](https://github.com/ersilia-os/ersilia/files/10861405/out3.csv)

Output from the original code.
[ADME_Predictions_2023-03-01-144439.csv](https://github.com/ersilia-os/ersilia/files/10861660/ADME_Predictions_2023-03-01-144439.csv)

**Comment by pauline-banye** [comment]
> I see, what I aslo identify is that the probability that you are getting is always almost 1, which means you are mixing the probability of 1 and the probability of 0 in the same result. Let's first make sure that you are returning the right value (only probability of 1) - can you point me to the code that actually converts all the results the model gives to probability of 1?

Hi @GemmaTuron, here is an example of the file which has the code that converts the model results to a probability of 1. It checks if the predicted class is equal to 1. If it is, then the probability is added to the outputs list as it is. If the predicted class is not equal to 1, then 1 minus the probability is added to the outputs list.  This is from the [main.py](https://github.com/ersilia-os/eos81ew/blob/main/model/framework/code/main.py) in the PAMPA 5 model.

```
OUTPUT_COLUMN_NAME = "Predicted Class (Probability)"

outputs = []
for x in list(output_df[OUTPUT_COLUMN_NAME]):
    c = int(x.split(" ")[0])
    p = float(x.split("(")[1].split(")")[0])
    if c == 1:
        outputs += [p]
    else:
        outputs += [1-p]
```
This is the piece of code that assigns the classes based on the set threshold of 0.5. This is from the PAMPA 5 [predictor.py file](https://github.com/ersilia-os/eos81ew/blob/main/model/framework/predictors/pampa50/pampa_predictor.py).

It creates a column in the dataframe with values generated from the model's predictions. Predictions  greater than or equal to 0.5, are considered to have low permeability whereas predictions with less than 0.5 are considered have moderate or high permeability.
```
self.predictions_df['Prediction'] = pd.Series(
       pd.Series(np.where(
           gcnn_predictions>=0.5, 
           'low permeability', 
           'moderate or high permeability'
            )
          )
        )
```

**Comment by GemmaTuron** [comment]
Are these codes equal in the Pampa7 model? Because I don't see that the probabilities are being outputed correctly.
Please try printing the different items in the output function (x, p, c) and checking those make sense
The predictor.py file is the original one or was modified at some point by you?

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, the predictor.py file I am working with is the original file from NCATS with minor edits to remove the code to calculate nearest neighbors (it was dependent on FPSim2 and returned multiple errors). 

The only other edits were to remove unused imports, adjust the paths and cleared out the commented codes.

**Comment by pauline-banye** [comment]
> Are these codes equal in the Pampa7 model? Because I don't see that the probabilities are being outputed correctly. Please try printing the different items in the output function (x, p, c) and checking those make sense The predictor.py file is the original one or was modified at some point by you?

The x is the predicted class and probability returned in this format `1 (0.9897897)`.  c and p are just splits of x, the predicted class and the probability.
```
output of x: 1 (0.9999861717224121)
output of c: 1
output of p: 0.9999861717224121
```

**Comment by GemmaTuron** [comment]
yes, that makes sense.
Can you provide for a list of compounds all these values and compare them to the NCATS results? To be sure that we are getting the right numbers
Then we'll see about the variations

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, 
I tested the model with this input csv file.
[input.csv](https://github.com/ersilia-os/ersilia/files/10869893/input.csv)

This is the result the model returned in my local environment.
```
100%|███████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 56.16it/s]PAMPA 7.4: 0.21582412719726562 seconds to predict 11 molecules
                                               smiles Predicted Class (Probability)                    Prediction
0                          CC(=O)Nc1nnc(S(N)(=O)=O)s1                       1 (1.0)  low or moderate permeability
1                                         CCCOCCCCCCC        1 (0.9999990463256836)  low or moderate permeability
2                                           CCCCOCCCC        1 (0.9999992847442627)  low or moderate permeability
3                             CC(=O)N[C@@H](CS)C(=O)O        1 (0.9999997615814209)  low or moderate permeability
4                               CC(=O)Oc1ccccc1C(=O)O        1 (0.9999998807907104)  low or moderate permeability
5                                             CC(=O)O        1 (0.9999967813491821)  low or moderate permeability
6                              O=c1ncnc2[nH][nH]cc1-2                       1 (1.0)  low or moderate permeability
7                                          CCCCNCCCCC        1 (0.9999997615814209)  low or moderate permeability
8       Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1                       1 (1.0)  low or moderate permeability
9                      CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1                       1 (1.0)  low or moderate permeability
10  C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...                       1 (1.0)  low or moderate permeability
```
[out.csv](https://github.com/ersilia-os/ersilia/files/10869739/out.csv)

This is the result from the original NCAT codes.
[ADME_Predictions_2023-03-02-104303.csv](https://github.com/ersilia-os/ersilia/files/10869861/ADME_Predictions_2023-03-02-104303.csv)

**Comment by GemmaTuron** [comment]
The model is incorporated!
