### ISSUE TITLE
🐛 Bug: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by karthikjetty** [ersilia-os/ersilia#605]
### Describe the bug.

After installing Ersilia onto my local computer, I was not able to fetch any models onto my local computer. In fact, I was also not able to run "Ersilia catalog". My computer would take several minutes to try to do these tasks, but eventually I would get the following error: "[Errno 60] Operation timed out". I did not have this issue until I switched networks–I am currently using a network in India which might be causing this issue, despite trying several different wifi networks. 

### Describe the steps to reproduce the behavior

Follow the steps to download Ersilia, and run any command, and I would get an Operation timed out error. I was not able to run any command on my local device. 

### Screenshots.

I have attached a log file with the problem I was having. 

[time_out.log](https://github.com/ersilia-os/ersilia/files/10846748/time_out.log)

### Operating environment

macOS Monterey

### Additional context

The problem ended up being that the following link, among many others were not running on my local device: [https://raw.githubusercontent.com/ersilia-os/ersilia/master/config/read_only_keys.json](link).

I'm not sure why these links were not working–must have been a firewall. So, I looked for ways to get the above link working on my local device. I used the VPN on the Opera browser set to Americas to see if the link worked there, and the link worked. So, the problem should be fixed by using a VPN. I will update this issue when I find a VPN for my computer to run the Ersilia commands.

**Comment by masroor07** [comment]
I faced the same issue. After setting up Ersilia on my local system, it was quite difficult to fetch a model. Took me around 3-4 attempts when was finally able to  fetch the model. Probably it takes too much time to fetch the data using the api, we can use something to dedlay the interrupt maybe!

**Comment by karthikjetty** [comment]
It also depends on your internet connection or VPN you use! I switched VPNs a couple times before I found one that gave me a fast enough internet connection to fetch models.

**Comment by masroor07** [comment]
That should't be the case and can be solved probably.

**Comment by GemmaTuron** [comment]
Hi @masroor07  and @karthikjetty 

Thanks for reporting this. Internet connection issues are completely unrelated to Ersilia's code and depend mostly on the urllib package. Some models are simply large and require up to 10 minutes to download, if the internet connection is broken during this period there is not much we can do to solve it at this moment.
For the VPN settings, this is depending on each user and we have not encountered many issues before, @karthikjetty only found those when he moved location, so we will have to live with it. I'll add a warning in the documentation regarding internet connection.

What steps are we taking to solve internet connection for our users:
1. Deploy ersilia in google colab: this is fully functional and uses google's system, so you only require internet to stay connected to google.
2. Provide online inference for selected models through digital ocan - work in progress
3. Provide precalculations as a data lake - work in progress

All these options are great for users, but Ersilia developers need to be able to install and run the code in their own systems and identify the internet networks that allow them to do so. It can take a while but it's a set up that is only needed once. Thanks for your understanding!

I'll close this issue.
