### ISSUE TITLE
Ersilia on M1 & M2 chips (ARM64)

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#610]
Models on ARM64 platforms using Python 3.7 give segmentation fault. A possible solution would be to only allow Docker usage in those platforms, but this is not ideal, since the Conda-only functionality is for now the most popular.

I am simply copy-pasting here part of the discussion we had through Slack with the Harvard team:

I have managed to run ersilia on ARM64 (we have purchased a MacBook Pro with M2 chip for this purpose; should be similar for M1).
The following command should work now:

```bash
ersilia -v fetch molecular-weight
```

The **problem** with segmentation fault was the following:

- M1 chips do not work with Python 3.7 (they return segmentation fault)
- We therefore installed Ersilia with a higher version. For M1 chips, I think 3.8 is sufficient. For M2, I used 3.10.
- However, each individual model has its own Conda environment, which means that, even if Ersilia installed in an environment with, say, Python 3.10, the model will be run in a separate environment corresponding to the specified version for the model. The reason for this is that it is impossible to have a one-size-fits-all environment, it is much easier to maintain one environment per model.
- In practical terms, this means that the model molecular-weight, for example, will still be installed in Python 3.7, because it was developed a long time ago. You can see a line FROM bentoml/model-server:0.11.0-py37 specifying py37  in the model’s Dockerfile (https://github.com/ersilia-os/eos5axz/blob/main/Dockerfile) [Note: We always use Dockerfiles to list down the dependencies of models, even if we are not using docker in this particular case].

The **solution** I’ve found is:

- At model fetching time, we check if we are on an ARM64 platform.
- If true, then we check if Python version in the model’s Dockerfile is below 3.10 (to be inclusive with M1 & M2 chips). If true, we overwrite the string to py310.
- Then, Ersilia will install this model in a conda environment based on Python 3.10 instead of 3.7, which makes it M1/M2 compatible.

Other possible solutions would have been:

- To update all model dockerfiles to 3.10 and above. This was impractical (we have almost 100 models) and dangerous.
- To only allow use of Docker in M1/M2 computers. That is, to avoid Conda when we are on M1/M2 chips and provide a higher level of isolation through docker containers. I still think this option is interesting, and I am working to enable swift usage of Docker too, but in my opinion the little hack that we have now is a good solution too.

**Comment by AdedejiAdewole** [comment]
Hello, I'm having this same segmentation fault error when trying to fetch a model, I installed Ersilia with python 3.8 on my macOS Monterey (intel chip) but this didn't solve the issue as the models were developed with python 3.7, can you explain more how I can change the model's python version?

**Comment by AdedejiAdewole** [comment]
Yeah same here but I'm running on macOS Monterey, I'm also not sure how to implement it.

**Comment by GemmaTuron** [comment]
Hi @karthikjetty and @AdedejiAdewole 

This issue is related to M1 and M2 chips. I currently don't have a Intel mac to test but a few weeks earlier I successfully installed it as reported in #591 

To do:
- Make sure you are following the steps in 591
- Use the faulthandler package to get more information (as described in the issue). Without more information than segmentation fault we are unable to provide guidance.
We are working on this but our capacity for testing is limited to the devices we currently have at Ersilia

@AdedejiAdewole in your case, for the outreachy contribution, please focus on the other tasks for week 1 and run ersilia on google colab to get familiar with its commands. This will allow you to continue on the contribution process while we troubleshoot this.

**Comment by karthikjetty** [comment]
Following the steps in #591, I get the following .log file as I try to import eos3b5e using fault handler. 
[fault_handler.log](https://github.com/ersilia-os/ersilia/files/10934630/fault_handler.log)
