### ISSUE TITLE
🐛 Bug: TestingErsilia

### ISSUE THREAD

**Issue by AdedejiAdewole** [ersilia-os/ersilia#614]
### Describe the bug.

I completed Ersilia setup on my MacOS but the last step to test if it was successful gives an error.
 

### Expected behavior.

I expected outputs of the command options for ersilia.

### Screenshots.

![IMG_5274](https://user-images.githubusercontent.com/50617984/223361860-a8149009-0ea3-448d-a6cc-ace89d0fe68e.jpg)

### Operating environment

macOS Monterey

**Comment by GemmaTuron** [comment]
Hello @AdedejiAdewole 

Please:

1. Use the Outreachy Contribution github issue to describe ALL progress report and bugs that you encounter.
2. Do not use screenshots. Copy the code manually so we can read it better, thanks!
I'll close this issue and let you move the discussion to the appropriate issue
