### ISSUE TITLE
🐛 Bug: Segmentation fault error

### ISSUE THREAD

**Issue by AdedejiAdewole** [ersilia-os/ersilia#617]
### Describe the bug.

The "ersilia --help" command returns a "segmentation fault:11" error. Does this error occur as a result of the python version used to install dependencies? How can I fix this error to proceed with the week's task?

### Operating environment

macOS

**Comment by masroor07** [comment]
that could probably be the case! maybe you missed on something during the installation?

**Comment by AdedejiAdewole** [comment]
I don't think so, I have gone through it multiple times and even done the installation again but it's the same issue

**Comment by GemmaTuron** [comment]
Hello @AdedejiAdewole 

Please, use the Outreachy Contribution github issue to describe ALL progress report and bugs that you encounter.

I'll close this issue and let you move the discussion to the appropriate issue
