### ISSUE TITLE
🐛 Bug: Error Occurs while Fetching Model: Ersilia exception class: ModelPackageInstallError

### ISSUE THREAD

**Issue by ZakiaYahya** [ersilia-os/ersilia#618]
### Describe the bug.
Hello @GemmaTuron and @DhanshreeA.
I have installed Ersilia successfully on my system, i have verified it by running ersilia --help and ersilia -catalog commands and it run successfully as well. But when i tries to fetch model eos3b5e, it throughs exception error i.e. ModelPackageInstallError. 
i'm attaching the error log file here:
[Error.txt](https://github.com/ersilia-os/ersilia/files/10909494/Error.txt)

### Screenshots.

Here's the screenshot of the error as well:
![Fetch_Error](https://user-images.githubusercontent.com/54974236/223427007-3be3e2ad-b5af-480a-ad13-9673f25b1e12.png)

### Operating environment

Window 10 pro , WLS ubuntu 18.04

**Comment by GemmaTuron** [comment]
Hello @ZakiaYahya 

Please:
1. Use the Outreachy Contribution github issue to describe ALL progress report and bugs that you encounter.
2. Do not use screenshots. Copy the code manually so we can read it better, thanks!
I'll close this issue and let you move the discussion to the appropriate issue
