### ISSUE TITLE
✍️ Contribution period: Zainab Ashimiyu-Abdusalam

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/ersilia#624]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [x] Suggest a new model and document it (1)
- [x] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by Zainab-ik** [comment]
### Ersilia Installation successful
![image](https://user-images.githubusercontent.com/54579707/223723781-639a52cb-53fc-4618-bef9-40ebca7b0c3c.png)

### Model fetch successful
![image](https://user-images.githubusercontent.com/54579707/223724035-7fb8e13b-8dd2-4f90-a5d2-d61b995b1188.png)

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

Welcome to Ersilia, great to have you here. Please let us know which system are you using, and whenever possible, refrain from pasting screenshots as they are more difficult to review by mentors!
Thanks

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik
> 
> Welcome to Ersilia, great to have you here. Please let us know which system are you using, and whenever possible, refrain from pasting screenshots as they are more difficult to review by mentors! Thanks

Thank you @GemmaTuron 

it's great to here also. All comments noted. I'd update the last comment.

**Comment by Zainab-ik** [comment]
### **Motivation Statement** 

Hi everyone, my name is **Zainab** and I was a graduate intern at the _**Nigeria Institute of Medical Research**_. Also, I had a BSc. in Pharmacology, Therapeutics, and Toxicology. I'm interested in Ersilia because it's at the intersection of Machine Learning and drug discovery. I came across **_Ersilia_** while browsing through the Outreachy available project. 

What drew me to Ersilia was the intersection of Artificial Intelligence (AI) and my background study, Pharmacology. I developed a passion for Computational Pharmacology and had my thesis along the line of _**predicting the antiviral properties of a natural plant using computational tools**_. I also belong to CaresAI, a cancer drug discovery research group with AI methodology as a focus point.

I also resonate with Ersilia's mission of tailoring their models to researchers from the LMIC (Low-Middle Income Countries) which thereby improves the quality of their research and outcome. I am a lover of open science and Ersilia is just the right open-science project for me looking at my background and my skill set.  

Ersilia projects span malaria, and infectious diseases and these are my core research interest. My skill set includes; ML, Python,  Linux, bioinformatics tools, etc. Contributing to Ersilia would be a way of giving back to the community and that's what open source is about. 

> Learning while giving back

I intend to take on more AI in drug discovery projects and working with Ersilia will improve my skills and give me confidence. Furthering my studies in Computational Pharmacology is a career progression that I believe Ersilia is going to be a great propeller in achieving.

Thank you for reading my motivation letter, I'm excited to contribute to Ersilia while also collaborating with my peers to make science accessible to all.

**Comment by Zainab-ik** [comment]
Hi, @GemmaTuron,
Week 1 contribution completed. Kindly review. Thanks.

**Comment by GemmaTuron** [comment]
Thanks @Zainab-ik ,

Welcome to the contribution period!

**Comment by Zainab-ik** [comment]
> Thanks @Zainab-ik ,
> 
> Welcome to the contribution period!

Thanks, @GemmaTuron.

**Comment by Zainab-ik** [comment]
### ** Week 2 **
**Task 1 - Select a model**
Model Selected -  [SARS-CoV2 activity (Image Mol)](https://github.com/HongxinXiang/ImageMol)

The Image Mol model takes in molecular images as the dataset. Having worked in the molecular lab, Seeing results generated as images being used in training a model would be interesting and therefore choose this model. I'm interested in its application for running unlabeled images of drug-like molecules since data annotation for compounds is tedious. 
The therapeutic effect of a drug can be evaluated by different means with the molecular properties, drug synthesis and low toxicity level being important factors of the therapeutics determination. The **_Image Mol_** model can also enhance the drug discovery's molecular docking process since the binding can be viewed.
Lastly, having worked with SARS-CoV-2 molecules previously, using the molecular images of its target protein with the corresponding compound of interest, this is a good model to cement that knowledge. I also get to learn about computer vision.
You can read more about the model [here](https://www.nature.com/articles/s42256-022-00557-6)
Thank you.

@GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik !

This model has two versions: one for TRAINING the model, and one for simply running predictions on pre trained models (FInetuning section on the readme)
the training requires CUDA-GPU, but the finetuning does not. Do not install the CUDA - GPU environment because it won't work in most systems, follow the instructions to run predictions only.
I hope this helps! I think Ahmed was working on this model as well!

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik !
> 
> This model has two versions: one for TRAINING the model, and one for simply running predictions on pre trained models (FInetuning section on the readme) the training requires CUDA-GPU, but the finetuning does not. Do not install the CUDA - GPU environment because it won't work in most systems, follow the instructions to run predictions only. I hope this helps! I think Ahmed was working on this model as well!

Thank you @GemmaTuron, I'd make an update.

**Comment by Zainab-ik** [comment]
### **Model Installation Process (contd)**

As stated above, I ran into a couple of errors while installing the Torch packages. 
1. The error above was resolved by installing _Torch_ separately.

To download the other Pytorch packages such as the `torch-cluster, torch-scatter, torch-sparse, torch-spline-conv`
I encountered an error showing;
```
ERROR: Failed building wheel for torch-sparse
ERROR: Failed building wheel for torch-cluster
ERROR: Failed building wheel for torch-scatter
ERROR: Failed building wheel for torch-spline-conv
```
while trying to install the packages. This occurred due to package version clashes. From my understanding, I noticed the _PyTorch_ packages are sensitive to the package version. To download a certain package, you might need to downgrade or upgrade a certain package it depends on. 

**How to resolve the Error**
Since the packages are **_PyTorch Geometric (PyG)_** packages, I read the installation guide from the **_PyG_** website [here](https://pytorch-geometric.readthedocs.io/en/latest/index.html).
I installed the packages from the source directly via `conda` using `conda install pyg -c pyg` since `pip install` keep throwing this error, 
```
(imagemol) zainab_ik@DESKTOP-E8NO3DG:~$ pip install torch-spline-conv
Collecting torch-spline-conv
  Using cached torch_spline_conv-1.2.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vgddfgna/torch-spline-conv_6514989605ba443d8a0107c604ef6a92/setup.py", line 8, in <module>
          from torch.utils.cpp_extension import BuildExtension
      ModuleNotFoundError: No module named 'torch.utils.cpp_extension'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
 and I was able to install the packages together. 
I ran the required installation code again `pip install torch-cluster torch-scatter torch-sparse torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.4.0%2Bcu101.html` and my output is; 
```
Requirement already satisfied: torch-cluster in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (1.6.0)
Requirement already satisfied: torch-scatter in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (2.1.0)
Requirement already satisfied: torch-sparse in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (0.6.16)
Requirement already satisfied: torch-spline-conv in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (1.2.0)
Requirement already satisfied: scipy in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (from torch-sparse) (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in ./miniconda3/envs/imagemol/lib/python3.7/site-packages (from scipy->torch-sparse) (1.21.5)
```
I confirmed the packages using the `grep torch` and my output is;
![image](https://user-images.githubusercontent.com/54579707/225323682-f8c53f96-0fad-4c80-915a-b23013e6ad64.png)
Finally, I was able to download all the _**PyTorch**_ packages. 

@GemmaTuron, I'd love to ask if installation via either `conda` or `pip` doesn't matter since the installation process of the model specified `pip`.

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik !
> 
> This model has two versions: one for TRAINING the model, and one for simply running predictions on pre trained models (FInetuning section on the readme) the training requires CUDA-GPU, but the finetuning does not. Do not install the CUDA - GPU environment because it won't work in most systems, follow the instructions to run predictions only. I hope this helps! I think Ahmed was working on this model as well!

currently working on the running prediction models as stated.

**Comment by Zainab-ik** [comment]
### **Finetuning Models**  

 _**Running Predictions of the SARS-CoV2 activity with the ImageMol**_ 
The SARS-Cov2 dataset comprises of different activity datasets namely ; 
- ACE2 enzymatic activity
- SARS CoV Pseudotyped particle entry (VeroE6 tox counterscreen)
- Human fibroblast toxicity
- Spike-ACE2 protein-protein interaction (TruHit Counterscreen)
- SARS-CoV Pseudotyped particle entry
- 3CL enzymatic activity
- MERS Pseudotyped particle entry (Huh7 tox counterscreen)
- TMPRSS2 enzymatic activity
- SARS-CoV-2 cytopathic effect (host tox counterscreen)
- HEK293 cell line toxicity
- MERS Pseudotyped particle entry
- SARS-CoV-2 cytopathic effect (CPE)
- Spike-ACE2 protein-protein interaction (AlphaLISA)

Since the Model has been installed and the environment activated. You can finetune the model by running;
```
python finetune.py --gpu ${gpu_no} \
                   --save_finetune_ckpt ${save_finetune_ckpt} \
                   --log_dir ${log_dir} \
                   --dataroot ${dataroot} \
                   --dataset ${dataset} \
                   --task_type ${task_type} \
                   --resume ${resume} \
                   --image_aug \
                   --lr ${lr} \
                   --batch ${batch} \
                   --epochs ${epoch}
```
You simply edit the code to fit the certain dataset you want to use.

1. I'd be starting with the _**ACE2 enzymatic activity**_  dataset.

**Comment by Zainab-ik** [comment]
### **Finetuning Models**  

 _**Running Predictions of the SARS-CoV2 activity with the ImageMol**_ 
The SARS-Cov2 dataset comprises of different activity datasets namely ; 
- ACE2 enzymatic activity
- SARS CoV Pseudotyped particle entry (VeroE6 tox counterscreen)
- Human fibroblast toxicity
- Spike-ACE2 protein-protein interaction (TruHit Counterscreen)
- SARS-CoV Pseudotyped particle entry
- 3CL enzymatic activity
- MERS Pseudotyped particle entry (Huh7 tox counterscreen)
- TMPRSS2 enzymatic activity
- SARS-CoV-2 cytopathic effect (host tox counterscreen)
- HEK293 cell line toxicity
- MERS Pseudotyped particle entry
- SARS-CoV-2 cytopathic effect (CPE)
- Spike-ACE2 protein-protein interaction (AlphaLISA)

Since the Model has been installed and the environment activated. You can finetune the model by running;
```
python finetune.py --gpu ${gpu_no} \
                   --save_finetune_ckpt ${save_finetune_ckpt} \
                   --log_dir ${log_dir} \
                   --dataroot ${dataroot} \
                   --dataset ${dataset} \
                   --task_type ${task_type} \
                   --resume ${resume} \
                   --image_aug \
                   --lr ${lr} \
                   --batch ${batch} \
                   --epochs ${epoch}
```
You simply edit the code to fit the certain dataset you want to use.

1. I'd be starting with the _**ACE2 enzymatic activity**_  dataset.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

Great, I was going to point to the path being maybe incorrect, good catch!
Thanks for trying the finetuning of the dataset, fantastic work. Since the ACE2 is not implemented in the Hub, can you simply try to run predictions with the model you fine tuned for a few molecules and with that, tick off the taskst from week 2 and focus on week 3?

Good job!

**Comment by Zainab-ik** [comment]
Thanks @GemmaTuron, I'd work on that.

**Comment by Zainab-ik** [comment]
## **Running Predictions for a few molecules using the SARS-CoV-2 finetuned Model**
Running prediction is the same as evaluating the models with few molecules for the ImageMol Model. The Model takes in a smiles list with Index numbers and labels (0,1) as input accompanied by the corresponding Image since it's an Image Model.

While working with the `Essential Medicine List (eml_canonical.csv)`, I had to download the corresponding images for a few smile lists to run predictions. However, I encountered a 
> ValueError: Only one class is present in y_true. ROC AUC score is not defined in that case.
This is due to some reasons;
1. The default batch size for prediction is 128, and I was running just five molecules
2. The Model does not process the corresponding images
3. I had to replicate the molecules into a folder just like the rest of the bioassays because it was throwing a `directory error.`

### **Debugging phase**
 I tried the following to bypass the errors and make predictions on a few molecules.
1. I used an already processed dataset among the SARS-CoV-2 bioassays. However, I reduced it to just a few 30 to 40 molecules.
2. I edited the `default batch size` in the `evaluate.py` script from 128 to a lesser value to enable prediction on a few molecules. The default batch size of 128 disables predictions on molecules less than 128. 

### **Outcome of running predictions on few molecules**
1. Using the above code for running prediction.
![ersilia last prediction](https://user-images.githubusercontent.com/54579707/226746700-8836bdf1-6547-4667-9e52-8891511a369e.png)
This was done on 128 molecules while debugging.

2. On 50 and lesser molecules while tuning the hyper-parameters like the _batch size_

- ![image](https://user-images.githubusercontent.com/54579707/226748011-ddbf39a0-f1d9-428e-bfa5-f95b33a2ae2d.png)
- ![image](https://user-images.githubusercontent.com/54579707/226748156-704e4fee-6247-405d-a6ce-999ba646989b.png)
This result shows that a higher percentage of the molecules have an inhibitory activity towards the ACE2 activity in the SARS-CoV-2 with _rocauc_ of 75%. The only evaluation metric is the AUC value. 

@GemmaTuron Kindly review. Also, while going through the Ersilia Model Hub, the model `eos4cxk` has a similar implementation to SARS-CoV-2 ImageMol Model.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik ! 

Good job on working that model out!
With that I think you can tick off all week 2 tasks as completed (since the model is not yet implemented in the EMH for comparison) and we can move onto week 3 tasks, looking forward to seeing your model suggestions!

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron,
Thank you very much. I'm looking forward to reviewing literature and suggesting models.

**Comment by Zainab-ik** [comment]
## Week 3 Task     --- Model Proposal [1]

### Model Title
hERG blocker: Virtual screening of DrugBank database for hERG blockers using topological Laplacian-assisted AI models

### Model Description
This model integrated molecular embedding with deep neural network algorithms and gradient boosting tree to predict potential hERG blockers. The blockage of the hERG channel causes cardiotoxicity and leads to the withdrawal of drugs from clinical trials. Therefore, It's important for a therapeutic compound to be screened for cardiotoxicity in the drug development pipeline. This model was trained using 8641 compounds, mostly either FDA-approved, experimental, or investigational drugs, from the DrugBank database. This model was further tested on large datasets and delivered an accuracy of `0.981`. The molecular feature was generated using transformer NPL techniques.

### Model Identifier
-  Slug: `hERG blocker`

### Model Characteristics
- Input: `compound - smiles format.`
- Task: `classification`
- Tag: `Toxicity, hERG, cardiotoxicity, `
- Output: `Score(0,1), Probability`

### References
- [Source Code](https://github.com/WeilabMSU/hERG-prediction)
- [Publication](https://arxiv.org/abs/2211.00861v1)
- [Document](https://github.com/ersilia-os/ersilia/files/11057138/2211.00861v1.pdf)


### License
The model contained within this package is licensed under an MIT license.

**Comment by Zainab-ik** [comment]
## Model Proposal [2]

### Model Title

### Model Description

### Model Identifier
- Slug: 

### Model Characteristics
- Input:
- Task:
- Tag:
- Output:

### References
- [Source Code](url)
- [Publication](url)

### License

**Comment by Zainab-ik** [comment]
## Model Proposal [3]

### Model Title

### Model Description

### Model Identifier
- Slug: 

### Model Characteristics
- Input:
- Task:
- Tag:
- Output:

### References
- [Source Code](url)
- [Publication](url)

### License

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik !

Good model suggestion to start with! Can you add it to our [list](https://airtable.com/shroQLlkcmDcC0xzm)?
Looking forward to the next models!

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron!

I've completed the model suggestion. Kindly review.
Also, your mentorship is really appreciated. Thank you for the exposure to the AI world of drug discovery. It's a career path I want to pursue as a Research scientist, which is very insightful.

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik !

Thanks for the model suggestions!
The generative model is interesting but would be probably difficult to incorporate as is to the Hub, so we'll leave it for the moment!
Can you add the COVID19 model to the list?
Thanks!

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron,

Thanks you.

**Comment by GemmaTuron** [comment]
@Zainab-ik 

Would you be able to tackle this issue to test the model just incorporated by @emmakodes?
Thanks!

**Comment by Zainab-ik** [comment]
> @Zainab-ik
> 
> Would you be able to tackle [this issue](https://github.com/ersilia-os/eos8lok/issues/2) to test the model just incorporated by @emmakodes? Thanks!

I'd do that.

**Comment by Zainab-ik** [comment]
Hi @GemmaTuron!

I have submitted my final application. I look forward to making more meaningful contributions to this field. 
It's been a wonderful experience and your mentorship is really appreciated for the successful contribution.
Many thanks.

I'd be closing this issue now.
