### ISSUE TITLE
🐛 Bug: Comment on New Model request form

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#626]
### Describe the bug.

When we approve a new model request using the /approve command, the  repository is updated and the record is created in the airtable, but the nice reply to the contributor in the issue does not appear.
It fails at the last step, which uses a Git Action created by @GrantBirki .
See this workflow: https://github.com/ersilia-os/ersilia/actions/runs/4364036742/jobs/7630862860

The only thing I am aware that changed is that I moved @GrantBirki from owner to external contributor since the period of work with GitHub finished --- might this be the source? 

### Describe the steps to reproduce the behavior

Check the workflow run https://github.com/ersilia-os/ersilia/actions/runs/4364036742/jobs/7630862860

### Expected behavior.

A comment to be created in the model request issue

### Operating environment

Ubuntu 20.04 LTS

**Comment by GrantBirki** [comment]
Taking a look 👀

**Comment by GrantBirki** [comment]
It looks like the `GrantBirki/comment` Action is failing and its pointing to this section in the readme -> https://github.com/GrantBirki/comment#error-resource-not-accessible-by-integration-

**Comment by GrantBirki** [comment]
While looking at the workflow, I have a few suggestions and will open a pull request

**Comment by GrantBirki** [comment]
I'm also looking into https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by GemmaTuron** [comment]
Thansk for checking this so fast!
It's solved now https://github.com/ersilia-os/ersilia/issues/580
