### ISSUE TITLE
code problems

### ISSUE THREAD

**Issue by Rufaida98** [ersilia-os/ersilia#63]
@miquelduranfrigola @GemmaTuron I hope if there are more code problems that can tackles the contributors skills in python to improve 
their skills .What do you think folks? we can do a discussion here

**Comment by miquelduranfrigola** [comment]
Definitely, @Rufaida98. We are currently putting up a second batch of issues. Stay tunned!
If you have ideas, please feel free to list them in this threat.

**Comment by miquelduranfrigola** [comment]
Hi @Rufaida98 I am adding you as an assignee to moderate this thread if you don't mind, in case more people are contributing.

**Comment by Rufaida98** [comment]
@miquelduranfrigola no problem at all. HAPPY to help!

**Comment by itsIapetus** [comment]
Hey, I am an Outreachy applicant, and I would love to work on this issue and create a pull request in the same.
Can I go ahead with this?

Thank You

**Comment by suryaremanan** [comment]
Hi @miquelduranfrigola , can you please assign me an issue so that I can start contributing as soon as possible? I'd like to stick to the code projects. Thank You.

**Comment by GemmaTuron** [comment]
Hi all,

We have created new contribution guidelines to make it easier for all of you to follow tasks, please head to the Slack channel for instructions! 
I will close this issue to avoid duplicating too many conversations. If you have suggestions link them in your own issue, which will make it easier for us to follow each applicant work!
