### ISSUE TITLE
🐛 Bug:  Conda activate ersilia command  in The Pre-requisite 5 step  throws an Error

### ISSUE THREAD

**Issue by samuelmaina** [ersilia-os/ersilia#630]
### Describe the bug.

Problem: 

One instruction is misplaced in the installation steps  (_https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation_). **The Pre-requisite 5: The Isaura data lake** has **conda activate ersilia**  command will throw an error ( **EnvinmentNameNotFound: Could not find conda environment: ersilia. You can list all discoverable environments with 'conda info --envs`** ) since  there is no command to  create a conda environment for ersilia

Proposed Solution:
Remove the **conda activate ersilia**  from the  **The Pre-requisite 5: The Isaura data lake** step

### Expected behavior.

There should be no error should be thrown in Pre-requisite 5 when when downloading The Isaura data lake

### Screenshots.

![error](https://user-images.githubusercontent.com/55924723/224024727-d7ba5cd3-c92a-451b-88de-48487d6a95b9.png)

### Operating environment

Ubuntu 20.04.1 (Operating Environment not a factor)

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Thanks for pointing this out. Of course ersilia won't show as a conda environment if it has not been created yet. I've made a note in the docs.
For the moment, please do not worry about isaura. These are accessory packages not needed at this stage
