### ISSUE TITLE
✍️ Contribution period: Bhaswati Roy

### ISSUE THREAD

**Issue by BhaswatiRoy** [ersilia-os/ersilia#632]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Isaakkamau** [comment]
Hello @BhaswatiRoy, Why have you marked all your week one steps complete? I guess you should write a motivation letter here before marking the 4th step as complete

**Comment by BhaswatiRoy** [comment]
Hello @Isaakkamau 
I was unaware of the fact that we've to write the motivation letter under this issue, I thought I've to wite in slack channel. 
Sorry for the wrong markings, I'll definitely update the statement here by tomorrow

**Comment by BhaswatiRoy** [comment]
## Motivation Statement - 

Hello,
I am Bhaswati Roy, a prefinal year CSE student interested in the field of Machine Learning and Data Analysis. I worked as a Machine Learning intern in a startup and also built multiple projects around the same. I am familiar with Python, C++, and SQL.
I am enthusiastic about Technical Writing and Software Documentation and have contributed to the following organizations to solve their documentation issues -
- Moja Global
- OpenMinded
- OpenRefine
- MDAnalysis
- NumPy
- LFortran
- PyMC
- ExpressLRS
- Iterative

I have also been a recipient of different scholarships like the Google Women Engineering Scholarship and the Harvard WECode Scholarship.
My initial Outreachy application is approved and I am interested in the project "Extension of the Ersilia Model Hub, a FOSS platform featuring pre-trained AI/ML models for biomedical". I am excited to work with Ersilia, and I believe this will be a great opportunity for me to graduate as a better developer. 
Looking forward to contributing to Ersilia.

LinkedIn: https://www.linkedin.com/in/bhaswatiroy31/
GitHub: https://github.com/BhaswatiRoy

**Comment by GemmaTuron** [comment]
Hi @BhaswatiRoy ,

Welcome, please let us know as well which system are you using. You should use this specific issue for all the work you do for the contribution period, so it is easier to follow.
In Slack the messages get lost fast

**Comment by BhaswatiRoy** [comment]
> Hi @BhaswatiRoy ,
> 
> Welcome, please let us know as well which system are you using. You should use this specific issue for all the work you do for the contribution period, so it is easier to follow. In Slack the messages get lost fast

I am using Windows 10

**Comment by GemmaTuron** [comment]
Hi @BhaswatiRoy 

We (outreachy mentors) haven't seen much activity in the last days. Just a kind reminder that there are ~10 days left to complete the Outreachy contribution period. If you are still interested in applying, we encourage you to continue the work and report it here. We are also available on the Slack channel for further discussions.
If you have decided not to apply to the internship with Ersilia, please close this issue to facilitate tracking of the active contributors to the mentors.
Many thanks!

**Comment by BhaswatiRoy** [comment]
Sorry, I can't continue further due to some issues.
Thanks for the cooperation
