### ISSUE TITLE
✍️ Contribution Period: Hawawou 

### ISSUE THREAD

**Issue by Hawawou** [ersilia-os/ersilia#637]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Hawawou** [comment]
**Motivation statement**
My name is Hawawou, I'm from Cameroon and I'm a final-year student in computer engineering. My skill set includes Linux, python, and Django and I started learning machine learning a couple of months ago with much interest in neural networks. 

While browsing through the outreachy projects, I came across Ersilia and it caught my attention as I am from a country that has many infectious diseases and I have seen many people die mostly due to lack of proper medication or insufficient funds to get the proper medication and Ersilia's goal to accelerate drug discovery and generate low revenue drug will go a long way to help population like those in my country and other low-income countries. I am excited to contribute to a project which brings change and impact to people's lives and even if I do not get selected, I would definitely continue contributing to Ersilia's projects as I am passionate about bettering people's lives in any way I can.
 
So working with Esilia will be an opportunity for me to improve my knowledge while working on real-world problems which can later permit me to help in the advancement of infectious disease research in my country.
Thank you for considering my application

**Comment by GemmaTuron** [comment]
Hi @Hawawou 

Please let us know which system are you using and whether you faced any issues while installing ersilia

**Comment by Hawawou** [comment]
Hi @GemmaTuron I use Linux and did not face any difficulty installing ersilia

**Comment by GemmaTuron** [comment]
Hi @Hawawou, 

great, let's move onto week 2 tasks then!
