### ISSUE TITLE
✍️ Contribution period: Medhavi Singh

### ISSUE THREAD

**Issue by Med16-11** [ersilia-os/ersilia#638]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Med16-11** [comment]
![Screenshot from 2023-03-12 02-12-24](https://user-images.githubusercontent.com/78318301/224510717-1a2b0962-a078-458c-a0e0-05c8726cd80c.png)

Successfully Installed Ersilia on my local system.

**Comment by Med16-11** [comment]
## Motivational Letters to mentors

Greetings mentors,
I am Medhavi Singh, a prefinal year computer science student from India. I am interested in working with Ersilia since the last year. Hey @GemmaTuron , I am not sure if you remember me or not but I was one of the contributors for the 2022 May Internship round and at that time you helped me in making my first contribution. Previous year also my initial application for Outreachy got selected and I applied for Ersilia but unfortunately, I didn't get selected. This year I am applying again for this amazing organization and will give my best. I have been following Ersilia on Twitter for the whole year and I have seen the growth of this organization. 
The zeal and enthusiasm of this community are motivating me to apply again. I have seen @miquelduranfrigola and @GemmaTuron  giving their absolute best whether it is giving talks about Ersilia or supporting contributors as a mentor.  
I have long admired Ersilia's commitment to social and environmental justice, and I am particularly drawn to the organization's focus on empowering communities to create sustainable change. I am excited about the prospect of contributing to Ersilia's efforts to build more equitable and resilient societies, and I believe that my skills in different fields of computer science would enable me to make a meaningful impact in this role.
I am particularly impressed by Ersilia's innovative approach to addressing complex social and environmental challenges, and I am excited about the possibility of working alongside a team of passionate and dedicated individuals who share my commitment to creating positive change.
Thank you for considering my application. I look forward to the opportunity to learn more about how I can contribute to Ersilia's mission.

Sincerely,
Medhavi Singh

**Comment by GemmaTuron** [comment]
Hi @Med16-11 

Welcome to the Contribution period!

**Comment by Med16-11** [comment]
Hello @GemmaTuron ! 
I am updating my progress of Week 2 till now.
I tried installing the "NCATS Rat Liver Microsomal Stability" Model on my system. but faced some problems and raised an issue for the same.  Here is the link: https://github.com/ncats/ncats-adme/issues/81
The conclusion of the discussion is that my system is facing some space-related issues since the models need enough space and some models are pretty big. I am currently trying to install the model on another system and also exploring other models in case I won't be able to run this one.

**Comment by GemmaTuron** [comment]
Hi @Med16-11 !

Of coruse no problem, the timelines are indicative and there is still time to catch up, I recommend checking the issues some others have been working on the NCATS models to get more info and hopefully avoid common bugs.
Looking forward to your contribution!
