### ISSUE TITLE
✍️ Contribution period: OMOJOLA JOSHUA DAMILOLA 

### ISSUE THREAD

**Issue by 1awesomeJ** [ersilia-os/ersilia#639]
### Week 1 - Get to know the community

- [ ] Join the communication channels
- [ ] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by GemmaTuron** [comment]
Hi @1awesomeJ 

We (outreachy mentors) haven't seen much activity in the last days. Just a kind reminder that there are ~10 days left to complete the Outreachy contribution period. If you are still interested in applying, we encourage you to continue the work and report it here. We are also available on the Slack channel for further discussions.
If you have decided not to apply to the internship with Ersilia, please close this issue to facilitate tracking of the active contributors to the mentors.
Many thanks!

**Comment by 1awesomeJ** [comment]
![Screenshot_20230323-153019](https://user-images.githubusercontent.com/109356020/227235853-ea29f8a0-4959-41cf-85b4-788d16aca774.jpg)
I have actually closed this issue since sir.

I don't know why it's still visible
