### ISSUE TITLE
✍️ Contribution period: <Sakshi Chapke> 

### ISSUE THREAD

**Issue by sakshi4chapke** [ersilia-os/ersilia#641]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by sakshi4chapke** [comment]
I am writing to express my strong interest in joining the Ersilia team and contributing to the development of the Ersilia Model Hub. I am pursuing graduation from IIT Roorkee and am motivated to apply my skills and knowledge to meaningful projects that make a positive impact on society.

Throughout my academic journey, I have gained a good foundation in programming, data structures, and algorithms, and I am continuously learning and improving my skills. Additionally, I have had the opportunity to work on several projects that have provided me with hands-on experience in various areas of technology.

Moreover, I am passionate about using technology to address critical societal challenges, and the Ersilia Model Hub's focus on accelerating drug discovery for infectious and neglected diseases using AI/ML models aligns with my values and interests. I believe that my passion for using technology to make a positive impact would make me a valuable addition to the Ersilia team. I am confident that I can contribute to the team's efforts to advance the development.

Thank you for considering my application. I look forward to the opportunity.

**Comment by GemmaTuron** [comment]
Hi @sakshi4chapke 

Welcome to Ersilia, great to have you here!

**Comment by GemmaTuron** [comment]
Hi @sakshi4chapke 

We (outreachy mentors) haven't seen much activity in the last days. Just a kind reminder that there are ~10 days left to complete the Outreachy contribution period. If you are still interested in applying, we encourage you to continue the work and report it here. We are also available on the Slack channel for further discussions.
If you have decided not to apply to the internship with Ersilia, please close this issue to facilitate tracking of the active contributors to the mentors.
Many thanks!

**Comment by sakshi4chapke** [comment]
Sorry, I am not able to contribute due to health issues. But I like to contribute at Ersilia in future.
