### ISSUE TITLE
✍️ Contribution period: Iman Ngwepe-Ntshibida 

### ISSUE THREAD

**Issue by Iam-Iman** [ersilia-os/ersilia#644]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by GemmaTuron** [comment]
Hi @Iam-Iman 

Please provide the log files otherwise we cannot provide support

**Comment by Iam-Iman** [comment]
MOTIVATION LETTER

I am Iman Ngwepe-Ntshibida. A Data Science Women Techsters Fellow at Tech4Dev, academic background is in Analytical Chemistry.

I would appreciate this opportunity of being chosen as one of your interns at Ersilia, as this will allow me to marry Data Science with "Science" as I believe that is what your organization stands for.

In my 6 months program, I have managed to complete several Data related courses and I think putting that knowledge in practice will be a great way to show case what I can be capable of and bring value into your company.

Your consideration, will be a stepping stone in me pivoting into the Data industry and making meaningful contributions to the Scientific field in my own person capacity.

As a person who is well versed in over 5+ official languages from my home country (South Africa) and who does not stay in her home town, goes to show that I enjoy learning from and working with people of different backgrounds, and easily adapt to new environments as I am naturally curious person. 

Thank you, Iman

My LinkedIn : https://www.linkedin.com/in/iman-morongwa-ngwepe-ntshibida

**Comment by Iam-Iman** [comment]
Thank you for keeping in touch. However I have been experiencing laptop issues and I thought I would be able to resolve them on time, unfortunately, I could not. Thank you for the wonderful opportunity of letting us have a peak into the Ersilia world, I learned a lot.
