### ISSUE TITLE
✍️ Contribution period: Malika Chhibber

### ISSUE THREAD

**Issue by MalikaChhibber** [ersilia-os/ersilia#645]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by MalikaChhibber** [comment]
I am writing to express my keen interest in joining the Ersilia team and contributing to the development of the Ersilia Model Hub. Currently, I am pursuing my graduation from BITS Pilani.

As part of my academic thesis with MIT Media Labs, I have gained hands-on experience in working on AI/ML Models and implementing them. I am extremely enthusiastic about leveraging AI and ML to create a positive impact on society. Furthermore, I possess a strong understanding of Data structures and algorithms, Machine Learning, and Artificial Intelligence.

In my opinion, the Ersilia Model Hub has the potential to aggregate all the biomedical models, which would facilitate deploying and predicting with models. I fully endorse and support Ersilia's idea of providing data science tools to lower-income countries for infectious disease research, especially in the wake of the COVID-19 pandemic, which highlights the need for a global approach to combat such crises. I am eager to contribute my skills and knowledge to the Ersilia team.

Thank you for considering my application. I am looking forward to the opportunity.

**Comment by MalikaChhibber** [comment]
I have been trying to join the communication channels on Slack, but it seems like the link has expired. I will be grateful if you can look into same.

**Comment by MalikaChhibber** [comment]
![Error](https://user-images.githubusercontent.com/85909394/226107371-f364c710-ef76-4c11-bc5d-7a3aeb3b927e.jpg)

I have encountered thus error while running Ersilia, kindly look into same sir.

**Comment by AhmedYusuff** [comment]
Hi @MalikaChhibber , Check this https://github.com/ersilia-os/ersilia/issues/591

**Comment by GemmaTuron** [comment]
Hi @MalikaChhibber 

We (outreachy mentors) haven't seen much activity in the last days. Just a kind reminder that there are ~10 days left to complete the Outreachy contribution period. If you are still interested in applying, we encourage you to continue the work and report it here. We are also available on the Slack channel for further discussions.
If you have decided not to apply to the internship with Ersilia, please close this issue to facilitate tracking of the active contributors to the mentors.
Many thanks!
