### ISSUE TITLE
✍️ Contribution period: Raymond Oluoch 

### ISSUE THREAD

**Issue by rOluochKe** [ersilia-os/ersilia#649]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by rOluochKe** [comment]
## CLI Output
![prediction](https://user-images.githubusercontent.com/8114528/226627059-04eac452-bead-4be0-8a2e-9795a8c1e64a.PNG)

**Comment by GemmaTuron** [comment]
Hi @rOluochKe 

Welcome to Ersilia, please have a look at the contribution tasks, week two focuses on installing an open source ML model (outside ersilia). we provide a few options!
you can also read through other contributor issues to catch up. Looking forward to seeing your contributions

**Comment by rOluochKe** [comment]
> Hi @rOluochKe
> 
> Welcome to Ersilia, please have a look at the contribution tasks, week two focuses on installing an open source ML model (outside ersilia). we provide a few options! you can also read through other contributor issues to catch up. Looking forward to seeing your contributions

Hi @GemmaTuron 

Thank you for the warm welcome, I am doing catch up and I am trying to finish before the end of the contribution period.
