### ISSUE TITLE
Rohan Outreachy 23✍️ Contribution period: <Rohan Singh> 

### ISSUE THREAD

**Issue by rohansingh1108** [ersilia-os/ersilia#650]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by rohansingh1108** [comment]
Hello, How to test the simplest model as of written in the third step?

**Comment by GemmaTuron** [comment]
Hi @rohansingh1108 

Welcome to Ersilia - once you install the Hub in your system, please test the model molecular-weight and let us know if it ran successfully and in which system!
And then you'll be ready to go onto the rest of the tasks :)
