### ISSUE TITLE
🦠 Model Request: S2DV inhibitory effect prediction on HBV

### ISSUE THREAD

**Issue by emmakodes** [ersilia-os/ersilia#655]
### Model Name

Inhibition of Hepatits B virus

### Model Description

The model adopts a natural language processing technique to analyze compound SMILES strings, enabling an accurate representation of the relationship between compounds and their substructures. This technique helps the model predict inhibitory effects on HBV, verified by wet-lab experiments. This model provides a new perspective on the prediction of compound properties for anti-HBV drugs to improve hepatitis B diagnosis and human health in the future.

### Slug

s2dv-hbv

### Tag

ChEMBL

### Publication

https://pubmed.ncbi.nlm.nih.gov/35062019/

### Source Code

https://github.com/NTU-MedAI/S2DV

### License

Apache-2.0

**Comment by emmakodes** [comment]
> Hi @emmakodes ! Great, I've modified a few fields, I'll approve it and a repo will be created that you can fork and work on!

Thanks @GemmaTuron I am currently working on it.

**Comment by emmakodes** [comment]
Hello @GemmaTuron I have successfully created a pull request for the model.
I ran the model within the Ersilia CLI and I have the following prediction output
[output_eos8lok.csv](https://github.com/ersilia-os/ersilia/files/11075842/output_eos8lok.csv)

**Comment by GemmaTuron** [comment]
Thanks @emmakodes !

The PR is merged and the model has been successfully tested by @zainab-ik!
Let's see if you can tackle the second one while working on the final application, good job!

**Comment by emmakodes** [comment]
Thank you so much @GemmaTuron I have just made a pull request for the second model(S2DV HepG2 toxicity)
