### ISSUE TITLE
🦠 Model Request: S2DV HepG2 toxicity

### ISSUE THREAD

**Issue by emmakodes** [ersilia-os/ersilia#656]
### Model Name

S2DV HepG2 toxicity

### Model Description

The model adopts a natural language processing technique to analyze compound SMILES strings, enabling an accurate representation of the relationship between compounds and their substructures. This technique helps the model predict liver toxicity, verified by wet-lab experiments.

### Slug

s2dv-hepg2-toxicity

### Tag

ChEMBL, Toxicity

### Publication

https://pubmed.ncbi.nlm.nih.gov/35062019/

### Source Code

https://github.com/NTU-MedAI/S2DV

### License

Apache-2.0 license

**Comment by GemmaTuron** [comment]
Let's focus first on #655 and if that works we will continue with this one

**Comment by emmakodes** [comment]
Okay noted @GemmaTuron

**Comment by emmakodes** [comment]
Hello @GemmaTuron here is the output prediction after I run S2DV HepG2 toxicity model within the Ersilia CLI
[output_eos2fy6.csv](https://github.com/ersilia-os/ersilia/files/11093550/output_eos2fy6.csv)

and here is the pull request: https://github.com/ersilia-os/eos2fy6/pull/1

**Comment by samuelmaina** [comment]
Hello @emmakodes, I  having an error of returning  null for all the  output of the a model. The model is being fetched correctly, but the predictions produce None all the time and when I look at the  API schema it looks like this 
```
{
    "run": {
        "input": {
            "key": {
                "type": "string"
            },
            "input": {
                "type": "string"
            },
            "text": {
                "type": "string"
            }
        },
        "output": {
            "outcome": {
                "meta": [
                    "fingerprint"
                ],
                "type": null
            }
        }
    }
}
```
The metadata.json look like :
```
{
    "Identifier": "eos6aun",
    "Slug": "rxn-fingerprint",
    "Status": "In progress",
    "Title": "RXNFP - chemical reaction fingerprints",
    "Description": "Predicts and  shows fingerprints for chemical reactions",
    "Mode": "Pretrained",
    "Input": [
        "Compound"
    ],
    "Input Shape": "Single",
    "Task": [
        "Generative"
    ],
    "Output": [
        "Fingerprint"
    ],
    "Output Type": [
        "Float"
    ],
    "Interpretation": "This model receives smiles as input and returns as output the fingerprint scores for each smiles,the fingerprint scores are used to give . ",
    "Tag": [
        "Fingerprint",
        "Chemical Reactions Maps"
    ],
    "Publication": "https://chemrxiv.org/engage/chemrxiv/article-details/60c753a0bdbb89acf8a3a4b5",
    "Source Code": "https://github.com/rxn4chemistry/rxnfp/tree/master/",
    "License": "MIT"
}
```
I don't need to modify the service.py since I am returning a Float.When I run the model but itself everything works fine. What could be the problem?

**Comment by emmakodes** [comment]
> Hello @emmakodes, I having an error of returning null for all the output of the model. The model is being fetched correctly, but the predictions produced are None all the time. The API schema it looks like this
> 
> ```
> {
>     "run": {
>         "input": {
>             "key": {
>                 "type": "string"
>             },
>             "input": {
>                 "type": "string"
>             },
>             "text": {
>                 "type": "string"
>             }
>         },
>         "output": {
>             "outcome": {
>                 "meta": [
>                     "fingerprint"
>                 ],
>                 "type": null
>             }
>         }
>     }
> }
> ```
> 
> The metadata.json look like :
> 
> ```
> {
>     "Identifier": "eos6aun",
>     "Slug": "rxn-fingerprint",
>     "Status": "In progress",
>     "Title": "RXNFP - chemical reaction fingerprints",
>     "Description": "Predicts and  shows fingerprints for chemical reactions",
>     "Mode": "Pretrained",
>     "Input": [
>         "Compound"
>     ],
>     "Input Shape": "Single",
>     "Task": [
>         "Generative"
>     ],
>     "Output": [
>         "Fingerprint"
>     ],
>     "Output Type": [
>         "Float"
>     ],
>     "Interpretation": "This model receives smiles as input and returns as output the fingerprint scores for each smiles,the fingerprint scores are used to give . ",
>     "Tag": [
>         "Fingerprint",
>         "Chemical Reactions Maps"
>     ],
>     "Publication": "https://chemrxiv.org/engage/chemrxiv/article-details/60c753a0bdbb89acf8a3a4b5",
>     "Source Code": "https://github.com/rxn4chemistry/rxnfp/tree/master/",
>     "License": "MIT"
> }
> ```
> 
> I don't need to modify the service.py since I am returning a Float.When I run the model but itself everything works fine. What could be the problem?

Hello @samuelmaina  it would have been nicer you post above on the issue of 'eos6aun' model since it is a different model from this model.

You are working on the model right?

What I am thinking is it seems the model is not accepting the right input

**Comment by samuelmaina** [comment]
@emmakodes it's a new model and I want to incorporate it.Let me try your suggestions out.I will post the issue in the model issue if the problem persists.
Thanks.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

please move this discussion to the right issue

**Comment by samuelmaina** [comment]
I will move it.Sorry.
