### ISSUE TITLE
🦠 Model Request: REDIAL-2020

### ISSUE THREAD

**Issue by Pradnya2203** [ersilia-os/ersilia#657]
### Model Name

REDIAL-2020

### Model Description

Predicts Anti-SARS-CoV-2 Activities (Live Virus Infectivity, Viral Entry, Viral Replication, In vitro Infectivity, Human Cell Toxicity) and also perform Similarity Search

### Slug

redial-2020

### Tag

SARS-CoV-2

### Publication

https://www.nature.com/articles/s42256-021-00335-w#Sec9

### Source Code

https://github.com/sirimullalab/redial-2020/tree/v1.0

### License

MIT License

**Comment by GemmaTuron** [comment]
the contribution period has concluded, I'll put this model in waiting until the new internship starts and we will continue its incorporation in the Hub

**Comment by GemmaTuron** [comment]
This model is incorporated!
