### ISSUE TITLE
🦠 Model Request: Malformer

### ISSUE THREAD

**Issue by Isaakkamau** [ersilia-os/ersilia#658]
### Model Name

Malformer

### Model Description

The MOLFORMER's design is based to learn about a model trained on a small molecules which are represented as SMILES string. The Model architecture has an efficient linear attention mechanism and relative positional embeddings with the goal of learning a meaningful and compressed representation of chemical molecules.

### Slug

Malformer

### Publication

https://arxiv.org/abs/2106.09553

### Source Code

https://github.com/IBM/molformer

### License

Apache

**Comment by GemmaTuron** [comment]
At this moment we will not work on incorporating this model, though we have included in our model suggestion list for the future
