### ISSUE TITLE
🐛 Bug:  Models eos157v eos9sa2 eos85a3 eos5smc eos8451 and more fetch fails with EmptyOutputError

### ISSUE THREAD

**Issue by MAX-KP** [ersilia-os/ersilia#677]
### Describe the bug.

fetching of eos157v eos9sa2 eos85a3 eos5smc eos8451 repeatedly fails with the following error message logged:
Ersilia exception class:
EmptyOutputError

Those models fail to fetch both on my local computer and on colab.

### Describe the steps to reproduce the behavior

Run the following command:
   ersilia fetch eos****

### Expected behavior.

👍🏼model eos**** fetched successfully!

### Screenshots.

![Screenshot 2023-05-12 165153](https://github.com/ersilia-os/ersilia/assets/103497653/1e22447a-f964-47f4-acc9-ebeeca5d40a2)

![Screenshot 2023-05-12 165402](https://github.com/ersilia-os/ersilia/assets/103497653/c3a33ea0-f2d3-4eb3-a7ef-22a86395676b)
![Screenshot (14)](https://github.com/ersilia-os/ersilia/assets/103497653/b77ae316-da47-41d2-be96-075f75639ed4)
![Screenshot (15)](https://github.com/ersilia-os/ersilia/assets/103497653/cc47c467-cd45-4f60-a8a8-e6e0c603d85e)

### Operating environment

wsl2 ubuntu 22.04 and Colab and ubuntu 22.04

**Comment by GemmaTuron** [comment]
Hi @MAX-KP 

Thanks, we are aware of some models that present bugs. We aim to tackle these int he coming months as we move our infrastructure to Docker containers to facilitate portability, I'll post updates here when we get to each specific model

**Comment by GemmaTuron** [comment]
We have updated all the models, they are available for fetching through Ersilia. We recommend using Docker to ensure compatibility for all systems. If you first install Docker in your system Ersilia will automatically recognise it and use it for model download. We are writing the documentation for that.
We also recommend pulling all the new code and reinstalling Ersilia to have the latest changes available.
