### ISSUE TITLE
[🐕 Batch]: FastAPI for easy deployment

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#693]
We need to add an extra FastAPI Swagger interface in order to have better input-output functionalities.

**Comment by miquelduranfrigola** [comment]
Working on it now, at the moment, there are three open fronts that go in similar directions:

- [ ] [ersilia-client](https://github.com/ersilia-os/ersilia-client)
- [ ] [ersilia-api](https://github.com/ersilia-os/ersilia-api)
- [ ] In the ersilia repository, the `dockerdaemonservice.py` file

These repositories are not redundant and each of them serves a different purpose.

**Comment by Greyisheep** [comment]
Are you still working on this? Would like to work with you

**Comment by miquelduranfrigola** [comment]
Hello @Greyisheep - apologies for a **very** slow response. We will work on this issue as soon as we have capacity. For now, I've put it "on-hold" since it is a quite challenging one. If you are still interested, I will definitely reach out to you.

**Comment by DhanshreeA** [comment]
@miquelduranfrigola is working on this within https://github.com/ersilia-os/ersilia-pack
