### ISSUE TITLE
Data precalculation GDI project design questions

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#703]
In this thread, I answer some relevant questions from the GDI team @ersilia-os/gdi-volunteers 

**Q1: What is the maximum acceptable level of latency for predictions to be returned to a user?**

A1. Assuming you mean querying the **precalculated** predictions, I would say that returning results (for 1000 molecules) within 1-5 seconds would be great.

**Q2: How many molecules would a scientist typically query at once?**

A2. Typical usage would be 10-100 molecules. Some scientists may query up to 1000 at once.

**Q3: Can you describe a couple of different use cases that a scientist would end up in. e.g. just needing a couple of predictions as a starting point vs. needing to do a big search over 1000s of molecules. How would they use the CLI in these kinds of cases?**

A3. Sure, let me describe three examples:

1. **One model, multiple molecules.** Imagine a scientist has one model of interest (for example, [eos4e40](https://github.com/ersilia-os/eos4e40) for antimicrobial activity). In this case, the scientist will have a collection of compounds (typically, around 100) that he/she wants to prioritise for experimentation. Compounds with the highest eos4e40 score are the most interesting. Therefore, the scientist will query the 100 compounds in the eos4e40 model. Now, there are two scenarios:
(a) All molecules are available in the data lake (all precalculations are ready): In this case, we simply query the data lake and return the results.
(b) Some molecules are not available in the data lake: In this case, we can retrieve the results that are available from the data lake, and for the rest we run the model normally. Then, we assemble results and deliver them to the user.
In general, I would say that the user should be agnostic to this. In other words, he/she doesn't need to know which molecules are in the data lake and which ones are not. Therefore, the same CLI should be used in cases (a) and (b). I suggest something like this (after serving with `ersilia serve eos4e40`: `ersilia run -i my_input.csv -o my_output.csv`, as we have it now, perhaps with an `--only-lake` option in case they only want to query molecules from the lake and leave the unavailable molecules blank: `ersilia run -i my_input.cv -o my_output.csv --only-lake`. As a matter of fact, a long time ago I wrote a [rudimentary class](https://github.com/ersilia-os/ersilia/blob/master/ersilia/lake/interface.py) to separate `done` and `todo`molecules within the CLI, `done` corresponding to the ones that are already available in the lake, and `todo` corresponding the ones that are still missing. Perhaps this helps, but please feel free to suggest better options!

2. **One molecule, multiple models.** Imagine a scientist who has isolated a compound from a medicinal plant. They don't know what this compound may be good for, so they would like to screen the compound against multiple models (antimalarial, antituberculosis, anti-HIV, etc.) to get an initial idea of their potential therapeutic uses. In this case, the user will run models one by one and stack results at the end. Therefore, in practice, the same logic that we discussed in point 1 will apply.

3. **Global analysis of one model.** Imagine a scientist who want to understand how "easy" it is to discover an antimicrobial drug. In this case (and to simplify), what the scientist needs to know is what proportion of molecules tend to have high scores in this particular model (eos4e40). What the scientist can do is download all precalculatd data for eos4e40 and simply measure how many molecules are above his/her threshold of choice. Imagine he/she finds 2000 molecules with a high score (>0.8), and let's say we have 2M compounds. Then, the "hit rate" (as we call it) is 0.1% - so the scientist will know that he/she is facing a challenging task!

**Q4. Is there an existing ontology/categorisation for the set of 2M molecules? ie can we group together molecules in a logical manner to build some sort of storage pattern/schema this might help us partition the data in a smart way to optimise efficiency.**

A4. This is a great point. Typically, we assign a unique identifier to each molecule, called [InChiKey](https://www.herongyang.com/Molecule/Name-InChIKey-InChI-Hash-String.html (27 characters). Ersilia already does this automatically, so for each input molecule (usually represented as a SMILES string), we get a fixed-length InChIKey that can be used to index.

In terms of ontology/categorization, there are many options out there, most of them to do **similarity searches**. The most typical are the so-called chemical fingerprints, typically 1024 or 2048-dimensional bit vectors that can be search with Jaccard similarities, or dice similarity, etc. There are plenty of methods for doing similarity search. A well-used one is [FPSim2](https://github.com/chembl/FPSim2). People have used these methods to define clusters, which is what you are asking for, but the problem is that these clusters are data dependent (they are defined based on the current corpus of molecules), and we cannot anticipate if these clusters are still good if we increase the size from, say, 2M to 10M molecules.

Rather, since InChIKeys are like fixed-length checksum strings, one could partition them just by "levels". For example, we could partition the InChIKey `BQJCRHHNABKAKU-KBQPJGBKSA-N` into `BQ/JC/...`. I hope this makes sense.

**Q5. Currently the output for the user/scientist is a file that’s downloaded in the user’s local machine. Are we happy if moving forward this is how the output is received by the user?**

A5. Yes, I think so. This would be perfectly fine, unless you have better ideas!

**Comment by raul-bermejo** [comment]
thanks for all the informative answers @miquelduranfrigola, this is great! A few follow-up comments and questions:

1. In A3/1, you mentioned: ‘we can retrieve the results that are available from the data lake, and for the rest we run the model normally. Then, we assemble results and deliver them to the user’. I imagine the last bit will be challenging as we’ll have to union two outputs from essentially two different files, and I imagining the compute will happen on the user level? In any case, I agree that we should aim to abstract whether the output lives in the data lake or not from the user.

2. Regarding the --only-lake option in A3/1, I think that’s a great idea to potentially trade off efficiency when not having a full output is ok. For simplicity sake, I’d say let’s try to aim for this once we have finished the steel-thread? I imagine the most likely scenario is that the user will want the output for all molecules.

3. Regarding A3/2 (One molecule, multiple), in your experience how frequent is this scenario vs. one model, multiple molecules? Based on my naive understanding of the CLI, this would be currently quite time consuming for the scientist given the CLI workflow (fetch, serve, run) right? Perhaps this would be a use case where the data lake would be extremely useful. However, if the scenario’s not frequent enough, we will take this into consideration when designing the schema (more details below).

4. Great to know about categorisation options in A4! We’ve been discussing schema options and this is definitely something to take into account. Based on the current CLI workflow of ersilia fetch <model_id> , ersilia serve <model_id>, … etc, I think it’d make most sense to set the bucketing/db schema based on model then molecule. If we’re going ahead with flat files, then in every model bucket we could have one/multiple parquet files with all the compound outputs for that model. We could potentially incorporate the similarity of the InChiKey in the partition schema, but let’s discuss that in our next catch-up!

5. For this project, can we assume that the input to output relationship is 1:1? In the Ersilia Model Hub: Inputs page I saw that in some cases there might be multiple molecules involved to produce one output, but I imagine that’d bring a lot more complexity to a caching design.

**Comment by miquelduranfrigola** [comment]
Thanks @raul-bermejo - great stuff. Let me try to answer:

1. I think the assemblage will happen on the user level - I agree that this may be a bit challenging. At the moment, I am not too worried about computing time, so if we have something that is functional but slow, that will be fine.

2. Agree. Let's deprioritize this.

3. Great points. Thankfully, the most common case is **one model, multiple molecules**.

4. Perfect! Fully agree that the first level of categorization should be the model id. Let's discuss this in our next catch-up!

5. Yes, let's assume 1:1 relationship. Sorry I didn't even mention the exceptions to this. They are quite rare and less used, so I did not want to complicate things.

**Comment by anisaistadi** [comment]
Hi @miquelduranfrigola, we want to run experiments and wonder how to get the complete 2M list of molecules.

CC @kartikey-vyas

**Comment by GemmaTuron** [comment]
Hi @anisaistadi 

This Reference File contains a list of about 2M molecules: https://github.com/ersilia-os/groverfeat/tree/main/data

**Comment by raul-bermejo** [comment]
hi @GemmaTuron and @miquelduranfrigola, I think you mentioned this at some point but is there a reference table/file of the models that have been uploaded into the Ersilia Hub? 

Just in case we want to mock up some precalc data and want to be as close to the actual scenario as possible. Thanks!

**Comment by GemmaTuron** [comment]
Hi @raul-bermejo 

This [airtable](https://airtable.com/shrNc3sTtTA3QeEZu) contains all the models in the Hub.

**Comment by miquelduranfrigola** [comment]
Thanks @raul-bermejo 

I would advice to start with the following two models, which are quite representative:
* eos3b5e
* eos4e40

**Comment by anisaistadi** [comment]
Hi @GemmaTuron & @miquelduranfrigola,

I noticed that the Reference Library lists only SMILES. Wondering if there’s an InChiKey that goes along with it? And if not, are there more InChiKeys apart from the ones on the Input page (drug_molecules.tsv)?

thanks in advance!

**Comment by GemmaTuron** [comment]
Hi @anisaistadi 
Each smiles has an InChIKey associated, which can be obtained by a simple function from the RdKIT package. If it would be helpful to have a reference_smiles.csv with a smiles column and an inchikey column I can create that, let me know

**Comment by anisaistadi** [comment]
Hi @GemmaTuron, I’ll take you up on that offer. A csv with the inchikey column would be super helpful. Thank you!

**Comment by GemmaTuron** [comment]
Hi @anisaistadi 

You can download the file [here](https://drive.google.com/file/d/1uaCk99iqBvCZK5BOlH0CLKZCacd6paq2/view?usp=sharing). In case you need to reproduce that, here is a function to do so:

```
!pip install rdkit
from rdkit import Chem

def smiles_to_inchikey(smiles):
    """From SMILES to InChIKey"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        inchi = None
        inchikey = None
    else:
        inchi = Chem.rdinchi.MolToInchi(mol)[0]
        inchikey = Chem.rdinchi.InchiToInchiKey(inchi)
    return inchikey, inchi
```

**Comment by GemmaTuron** [comment]
Hi all,

I'll close this as complete!
