### ISSUE TITLE
Duplicate issues in `eos-template`

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#704]
In the `eos-template`, the [test-model workflow](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model.yml), at the end, creates an issue for tte model to be manually curated. The proble is that, when we run this action more than once (this happens quite often through a `workflow_dispatch`), a new issue is created every time, which is inconvenient.

Therefore, it would be great to have a condition to ensure that an issue is only created once.

In turn, a [post2slack workfllow](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/post2slack.yml) is created when an issue is opened. Preventing multiple issue creation will also prevent us from sending multiple messages to Slack.

**Comment by GemmaTuron** [comment]
That would be very helpful since now I am manually closing the extra issues that are created

**Comment by honeyankit** [comment]
>  That would be very helpful since now I am manually closing the extra issues that are created

PR is up for review
