### ISSUE TITLE
Accept input submissions from external users

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#718]
## Background

For model pre-calculations, at some point, it will be great to accept submissions from external users. These might be collaborators or spontaneous contributors that may want to see predictions on their molecules of interest.

Overall, the approach has the advantage of allowing us to grow our data lake organically, based on user interest. Considering that many users do not have the capacity to run models locally, this could be quite beneficial for many of them.

## What we need

In brief, we need a way of accepting submissions for pre-calculation as input files. 

Obviously, we need to have some control over submitted inputs. We do not expect massive requests.

Ideally, we do not want to create and manage user login, and/or API keys. It would be nice if users have a GitHub account - it is a first step and incentive towards having them engaged. 

## Suggested solution

- We could create a repository (named, for instance, **ersilia-inputs**) for accepting user inputs.
- In this repository, users will be able to upload a file and do a PR.
- Then, we can inspect the file (first manually, in the future perhaps with automation) and merge the PR.
- When we merge the PR, an action is triggered to make the calculations corresponding to the input file and store them in the data lake.
- At the end of the action, we can eliminate the file, so that the repository does not grow unnecessarily.

To me, this sounds like a low-hanging fruit solution to accept user inputs without having to manage logins, or set up a server. We would leverage GitHub infrastructure and capability, which is very consistent with everything else we do.

## When?

This is **not a priority** at the moment. Let's wait until we have the data lake pipeline established.

**Comment by honeyankit** [comment]
@miquelduranfrigola: Your solution is good. I am providing some optimization on top of that:

**User Submission:** Users can create a Pull Request (PR) with their input file in the existing repository where the model calculates the input. This simplifies the process for the users, and they can use the PR description to provide any additional context or explanation about the data they are submitting. This will also eliminate the need to creating additional repository (`ersilia-input`).

**Initial Validation:** The creation of a PR triggers a GitHub action that validates the input file. This action should check for things like the `right data format, the size of the data, or any other requirement you want to enforce for your input files`. If the validation fails, the action can automatically comment on the PR with a description of the error, and the user can then fix the issue and update their PR.

**Data Calculation:** Once the PR is reviewed and merged, another GitHub action is triggered to calculate the input file and update the data lake with the new results. This action can provide status via some notifications to the user to let them know when the calculations are complete and where they can find the results `(sending notification is purely optional)`.

**Input Cleanup:** After the calculations are completed, you can either set up the action to automatically delete the input file from the repository or use another scheduled GitHub action to periodically delete input files from the repository. I am more inclined towards keeping the files for 1 day or 2, just in case you want to re-run the calculation.  

This solution has some additional benefits of no need for a separate repository, automates the validation using GitHub actions.

**Comment by miquelduranfrigola** [comment]
Thanks @honeyankit this is excellent feedback. Thank you so much.

I really like the fact that users can directly submit inputs into the model repository itself. This is much better than my initial idea.

I do have a question, though. It is likely that we will have to update this action(s), which may become difficult to maintain as we have more and more models. Would it make sense to write the action as a separate GitHub repository, and then have a simple workflow file in the model respositories?

**Comment by honeyankit** [comment]
> update this action(s), which may become difficult to maintain as we have more and more models

I am answering based on my assumption that the users can provide input to any model's repo to check the result. If this is the case then then it will make sense to have all the actions workflow at a common place and use them in a simple workflow as you suggested. This way maintaining it will be easy.

**Comment by miquelduranfrigola** [comment]
Thanks @honeyankit 

I've never done it. Since this looks relatively complex, I will do a writeup and, hopefully, we will be able to assemble a small team to tackle this. I would greatly appreciate it if you could have a look at my writeup once I am done. I will then summarize it here.

**Comment by honeyankit** [comment]
@miquelduranfrigola sure. I will review it and up for the work.

**Comment by miquelduranfrigola** [comment]
**Update**: This is now managed by the GitHub SBV team and mostly discussed in the corresponding project board. I am closing this issue for now, but please feel free to reopen.
