### ISSUE TITLE
🐛 Bug:  Not able to Install or Update Ersilia. due to mistyping of is_installed() instead of _is_installed() in ersilia/setup/requirements/bentoml.py

### ISSUE THREAD

**Issue by samuelmaina** [ersilia-os/ersilia#721]
### Describe the bug.

One is not able to install or update ersilia.
There is a mistyping of the _is_installed function name in  the function declaration. The function is declared is_installed() but it is being called _is_installed() which throws an error as can be seen from the code (ersilia/setup/requirements/bentoml.py):
```
 def is_installed(self):
        try:
            import bentoml

            return True
        except ImportError:
            return False

  def is_bentoml_ersilia_version(self):
        if not self._is_installed():
            return False
        pass
```

### Describe the steps to reproduce the behavior

Create conda  env : `conda create -n ersilia python=3.7`
Download ersilia: `git clone https://github.com/ersilia-os/ersilia.git`
Install packages: `pip install -e .`

### Expected behavior.

Download and install ersilia successfully.

### Screenshots.

![image](https://github.com/ersilia-os/ersilia/assets/55924723/dee071a6-8c1d-43f1-9742-ab1e36c3908f)

### Operating environment

Ubuntu 20.04.1 (Operating Environment not a factor)

**Comment by samuelmaina** [comment]
Have made a PR on this  issue. You can check it out at https://github.com/ersilia-os/ersilia/pull/722

**Comment by miquelduranfrigola** [comment]
Fantastic. This has been solved. Thanks @samuelmaina
