### ISSUE TITLE
🐛 Bug: On Apple M1/M2 chips, model is pulled successfully but docker run doesn't work

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#725]
### Describe the bug.

After some exception handling, I was able to make `ersilia fetch` work for docker images that were only successfully built with linux/amd64. Using the `--platform linux/amd64` option solved the issue in `docker pull`

Now, the `fetch` command does a test on model serve that is not successful: 

```
18:47:30 | DEBUG    | Using URL: http://0.0.0.0:63752/info
18:47:31 | DEBUG    | Writing file /Users/mduranfrigola/eos/repository/eos74bo/20230626184705/apis_list.txt
18:47:31 | DEBUG    | ['run']
18:47:31 | DEBUG    | Stopping and removing container 8edccf6ef825df8388e2200057ae43285585364d72a715d6a7233d364e4534a2
18:47:31 | DEBUG    | Stopping all containers related to model eos74bo
18:47:31 | DEBUG    | Stopping and removing container eos74bo_9766
Unable to find image 'ersiliaos/eos74bo:latest' locally
latest: Pulling from ersiliaos/eos74bo
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
Error response from daemon: No such container: fa059e9f-cfd8-466f-bef1-5a5bb4c806ec
Error response from daemon: No such container: fa059e9f-cfd8-466f-bef1-5a5bb4c806ec
Unable to find image 'ersiliaos/eos74bo:latest' locally
latest: Pulling from ersiliaos/eos74bo
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
Error response from daemon: No such container: 3549fa88-badc-4ec1-9a39-370fd2220759
Error response from daemon: No such container: 3549fa88-badc-4ec1-9a39-370fd2220759
Unable to find image 'ersiliaos/eos74bo:latest' locally
latest: Pulling from ersiliaos/eos74bo
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
Error response from daemon: No such container: 04aa82d2-6da9-4025-8df2-d15732d9598c
Error response from daemon: No such container: 04aa82d2-6da9-4025-8df2-d15732d9598c
👍 Model eos74bo fetched successfully!

```

### Describe the steps to reproduce the behavior

`ersilia -v fetch eos74bo`

### Expected behavior.

Fetch successful, running with the appropriate architecture or forcing the platform as needed.

### Operating environment

MacOSX

**Comment by honeyankit** [comment]
@miquelduranfrigola How the `docker run` is invoked. Adding `docker run --platform linux/amd64` should solve the issue.
  
Also how these docker images are build? We might need to provide `--platform linux/amd64` during the building of the docker image as well. I can have a look if you provide me the Dockerfile and Action CI workflow.

**Comment by miquelduranfrigola** [comment]
Thanks @honeyankit !

You pointed me to the right direction. I have solved the issue using the `--platform linux/amd64` .

I will close the issue for now and we will open it later if necessary.
