### ISSUE TITLE
[Project]: Test models automatically

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#729]
### Summary
In this project we want to develop a `test` command that, given a model, will take make sure that it is functioning correctly. This project emerges from the discussion: https://github.com/ersilia-os/ersilia/discussions/700

### Scope
Epic 🐅

### Objective(s)
The command should work like this:

```
ersilia test eos3b5e
```

In the background, the model should be doing the following:

- Check model metadata/information
- Test behaviour of model with different inputs
- Test the consistency of model outputs
- Get performance metrics of the model

To get started, we have created a placeholder class named `ModelTester`.

In addition, we have the [maintained inputs repository](https://github.com/ersilia-os/ersilia-model-hub-maintained-inputs) that we can use to store the inputs we want to use for model testing.

### Team
| Role & Responsibility | Username(s) | 
|--|--|
| DRI / Lead Developer | @username |
| Reviewer / Backup Developer | @usernames |
| Project Manager | @usernames |
| Others | @usernames |

### Timeline
- [x] 30/06/2023: Meeting to organize tasks.
- [x] TBD

**Comment by GemmaTuron** [comment]
@miquelduranfrigola isn't this already completed?
Now improvements are taking place in #929

**Comment by miquelduranfrigola** [comment]
Yes. Let's close this. Thanks.
