### ISSUE TITLE
[Project]: Low-dependencies Ersilia installation

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#730]
### Summary

We want to provide a run modality of Ersilia that does not depend on local installation. Instead, Ersilia is run as a docker container. Then, there will be a client that will manage, in docker:
- The Ersilia container
- The model containers
The client will have bare-minimum Python requirements.

### Scope

Batch 🐕

### Objective(s)

* Create an ersilia image that can be used to centralize the ersilia commands
* Write a lightweight ersilia client cli
* Mount disks accordingly to manage the `~/eos` repository seamlessly

### Team

| Role & Responsibility | Username(s) | 
|--|--|
| DRI / Lead Developer | @miquelduranfrigola  |

### Timeline

- [ ] 06/06/2023: New CLI for the ersilia client
- [ ] 09/06/2023: Working version
- [ ] 10/06/2023: Documentation

### Documentation

We can start with a docker image as shown here: https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/installer
Correspondingly, a workflow creates an `ersiliaos/shell` image that can be pulled an run. This image starts a container that has ersilia already installed.

**Comment by honeyankit** [comment]
> Write a lightweight ersilia client cli

@miquelduranfrigola @GemmaTuron I am trying to understand here, what is the use of the ersilia client here?

**Comment by miquelduranfrigola** [comment]
Thanks @honeyankit 

I am working on a prototype as we speak. Will provide more information very soon 🙏

**Comment by DhanshreeA** [comment]
@miquelduranfrigola whenever you get some time, please add more documentation to this issue: eg, source for the client, current status and such. Thank you!

**Comment by miquelduranfrigola** [comment]
Hello @DhanshreeA 

I think we can close this issue since hopefully this is now covered with [ersilia-client](https://github.com/ersilia-os/ersilia-client) and [ersilia-pack](https://github.com/ersilia-os/ersilia-pack)
