### ISSUE TITLE
🦠 Model Request: Bidd Molecular fingerprint maps 

### ISSUE THREAD

**Issue by samuelmaina** [ersilia-os/ersilia#736]
### Model Name

Molecular fingerprint maps based on broadly learned knowledge-based representations

### Model Description

Molecular representation of small molecules via ingerprint-based molecular maps (images). Typically, the goal is to use these images as inputs for an image-based deep learning model such as a convolutional neural network. The authors have demonstrated high performance of MolMap out-of-the-box with a broad range of tasks from MoleculeNet.

### Slug

bidd-molmap-fps

### Tag

Fingerprint

### Publication

https://www.nature.com/articles/s42256-021-00301-6

### Source Code

https://github.com/shenwanxiang/bidd-molmap

### License

GPL-3.0

**Comment by GemmaTuron** [comment]
@samuelmaina next time please make sure to fill all the required inputs or the approve command will not work. You were missing the tags

**Comment by GemmaTuron** [comment]
This model is incorporated
