### ISSUE TITLE
🐛 Bug: ersilia example command generating file with wrong format

### ISSUE THREAD

**Issue by pittmanriley** [ersilia-os/ersilia#737]
### Describe the bug.

I am testing eos7ack and created an input file using the command `ersilia example eos7ack > input.csv`. The file looks like this: 
```
[
    "C[C@@](Cc1ccc(O)c(O)c1)(NN)C(O)=O",
    "COc1ccc(CCC(=O)c2c(O)cc(O[C@@H]3O[C@H](CO)[C@@H](O)[C@H](O)[C@H]3O[C@@H]3O[C@@H](C)[C@H](O)[C@@H](O)[C@H]3O)cc2O)cc1O",
    "[O-][N+](=O)c1cccc2c[nH]nc12",
    "OC(=O)c1ccc(\\C=C2\\SC(=S)N(C2=O)c2cccc(c2)C(F)(F)F)cc1",
    "N[C@@H](Cc1ccc(cc1)N(CCCl)CCCl)C(O)=O"
]
```

And when I run the model on this input, I get the following output, where the input and outputs are said to be null. I'm not sure why this is happening, but I think it has to do with the format of the file with the brackets.
[output.csv](https://github.com/ersilia-os/eos7ack/files/11951039/output.csv)

### Describe the steps to reproduce the behavior

1. conda activate ersilia 
2. ersilia -v fetch eos7ack 
3. ersilia example eos7ack > input.csv 
4. ersilia run -i input.csv

### Screenshots.

Here is a part of the output file: 

```
{
    "input": {
        "key": null,
        "input": null,
        "text": null
    },
    "output": {
        "outcome": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ]
    }
}
```

### Operating environment

macOS version 12.3.1 and M1 chip

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 
We need to re check the example command

**Comment by miquelduranfrigola** [comment]
Hi both,

I don't think the `example` command is wrong.

This instruction: `ersilia example eos7ack > input.csv` will **pipe** the output of `ersilia example eos7ack` to an `input.csv` file. Therefore, in practice, we are **not** specifying a file in the `example` instruction. This is why it is returning it as a JSON serializable string (a list, in this case).

The intended usage is `ersilia example eos7ack -f input.csv` 

On a separate note, I would advice to use the `-n` flag to specify the number of molecules.

`ersilia example eos7ack -f input.csv -n 5` will give you 5 molecules.

**Comment by miquelduranfrigola** [comment]
Hi @pittmanriley and @GemmaTuron 

Is this solved now?

**Comment by pittmanriley** [comment]
Hi @miquelduranfrigola, yes it is solved. Thank you!
