### ISSUE TITLE
📑 Feature Request: Filter Empty Lines

### ISSUE THREAD

**Issue by febielin** [ersilia-os/ersilia#738]
### Is your feature request related to a problem? Please describe.

AssertionErrors thrown when input files have additional lines. 

### Describe the solution you'd like.

I imagine two possibilities:
1. Ersilia is capable of identifying additional empty lines and automatically filter them out such that they do not trigger an error.
2. Ersilia detects empty lines and prompts the user to edit their file (e.g. "Empty lines detected in the input file, which may compromise output. Do you want to proceed? [Y/n] - this will give users a chance to double-check their file before running it).

**Comment by miquelduranfrigola** [comment]
Hey @febielin 

I hope this is sufficient for now.

If ersilia finds an empty line, it throws the following error:

```
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
EmptyInputError

Detailed error:
Some items in your input appear to be empty!

Hints:
Please make sure that no empty lines are present in your input. If you are using a file as input and you can't find the empty line, look at the end of the file! It is possible that it contains an extra empty line.

If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /Users/mduranfrigola/eos/current.log
 ```
 
 Please check the commit 0e08d4644285100e7d3c1ef913aa4cab48011b55 to see the changes I have introduced

**Comment by DhanshreeA** [comment]
@miquelduranfrigola is this issue good to close?

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 

can you confirm if we can close this issue?

**Comment by miquelduranfrigola** [comment]
Sorry this remained overlooked.
