### ISSUE TITLE
🐛 Bug: Remove progress bar during model fetch in GitHub Actions?

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#742]
### Describe the bug.

So this is not exactly a bug, but it might be a good idea to remove the progress bar (or make that feature configurable?) during GitHub Action runs because right now it increases the overall logged lines and makes reading logs awfully painful. 

### Operating environment

GitHub Actions/Ubuntu 22.04.2

**Comment by DhanshreeA** [comment]
For example jobs such as 'Build and Push' or 'Upload model to dockerhub'  (eg https://github.com/ersilia-os/eos2re5/actions/runs/5472620443/jobs/9965024551#step:7:1) end up producing several lines of logs, that especially don't render well on the UI.

**Comment by miquelduranfrigola** [comment]
Completely agree, noted.

**Comment by miquelduranfrigola** [comment]
Hi @DhanshreeA this has been resolved in the commit f7a1aa23c122666969eb3d28d0b4d6800178c651
