### ISSUE TITLE
📑 Feature Request: Migrate from Dockerfile to YAML in the configuration of models

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#743]
### Is your feature request related to a problem? Please describe.

Having model configuration as `Dockerfile` in the model repositories (see [template](https://github.com/ersilia-os/eos-template)) is confusing, since many times docker is not used for installation. I have realized that many contributors are confused by this fact and, therefore, we need to find a more intuitive solution.

### Describe the solution you'd like.

Possibly, having a `config.yml` file would be the ideal solution. This should not cause a lot of friction since, at fetch time, we can incorporate the commands of this file into a Dockerfile internally, and proceed as usual.

**Comment by russelljeffrey** [comment]
Hi @miquelduranfrigola,
Based on what I understood, I think somebody has already resolved this type of issue in [here](https://stackoverflow.com/questions/72792408/how-to-convert-a-docker-compose-file-to-kubernetes-yaml-file). The answer takes you to a github repo that can convert docker file to YAML file in bash(shell). You can find the github repo [here](https://github.com/Shachar297/Nexus-Registry). Let me know if it works.

**Comment by GemmaTuron** [comment]
This issue is linked to that one: https://github.com/ersilia-os/ersilia/issues/749 and that one: https://github.com/ersilia-os/ersilia/issues/746
I'll keep the discussion just here for simplicity and close the other issues - this feature incorporation has been deprioritized and will be worked out in the next Ersilia big release

**Comment by DhanshreeA** [comment]
Marking this issue as duplicate and closing it since we are more proactively addressing this in #1159
