### ISSUE TITLE
🐛 Bug: GitHub Actions workflows stopped working on Python 3.11

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#753]
### Describe the bug.

This is a critical error. All workflows (including model workflows) suddently stopped working in GitHub Actions. This seems to be related to Python 3.11.

https://github.com/ersilia-os/ersilia/actions/runs/5644209284/job/15287529225

### Operating environment

GitHub Actions Ubuntu

**Comment by miquelduranfrigola** [comment]
**Update**: The error traces to Ersilia's BentoML: https://github.com/ersilia-os/bentoml-ersilia

It stops working with Python 3.11.

**Comment by GemmaTuron** [comment]
we have temporarily bypassed that by forcing Py 3.10:
```
      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10 
```
commit to eos-template: https://github.com/ersilia-os/eos-template/commit/c933492c534d179038520b3fd807cce8f7889872

**Comment by miquelduranfrigola** [comment]
Yes, thanks @GemmaTuron 

In theory, https://github.com/ersilia-os/bentoml-ersilia also works now with Python 3.11. The issue was caused by unforeseen behaviour of the `@dataclass` decorator.
