### ISSUE TITLE
🦠 Model Request: SmilesPE

### ISSUE THREAD

**Issue by russelljeffrey** [ersilia-os/ersilia#754]
### Model Name

SmilesPE: tokenizer algorithm for SMILES, DeepSMILES, and SELFIES

### Model Description

The Smiles Pair Encoding method generates smiles substring tokens based on high-frequency token pairs from large chemical datasets. This method is well-suited for both QSAR activities as well as generative models. The model provided here has been pretrained using ChEMBL.

### Slug

smiles-pe

### Tag

Chemical language model, Chemical notation, ChEMBL

### Publication

https://pubs.acs.org/doi/abs/10.1021/acs.jcim.0c01127

### Source Code

https://github.com/XinhaoLi74/SmilesPE

### License

Apache-2.0

**Comment by russelljeffrey** [comment]
Hello @GemmaTuron. 
Thank you for mentioning that. I have read the docs before and as shown [here](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-incorporation-workflow#7.-assist-with-curation-and-publication) in an example, the tag is written based on the name of the model (As I understood). I read most parts of the Ersilia gitbook that is in regards to model contribution. Can you please provide a link (if any available) so that I can understand how they are predefined? Thank you.

**Comment by GemmaTuron** [comment]
Hello @russelljeffrey 

The Slug is the model short name, not the tag. The one you suggest feels too long, so I would only write smiles-tokenizer
All the information related to how to fill in these fields can be found in the Ersilia GitBook under [model contribution](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-template)

**Comment by russelljeffrey** [comment]
Thank you @GemmaTuron for your explanations. All of the required modification will be done very soon.

**Comment by russelljeffrey** [comment]
Hi again @GemmaTuron . The slug and tag have been modified according to the link you provided.

**Comment by GemmaTuron** [comment]
Hello @russelljeffrey 
The slug is the short name and the tags are the key words that will help identify the model, and they must be from the list provided in the above link, please have a look and suggest a few that might fit.

**Comment by russelljeffrey** [comment]
Hi @GemmaTuron ,
The tag and Slug were corrected.

**Comment by GemmaTuron** [comment]
I have updated the fields according to the guidelines in the documentation (i.e, description must be at least 200 characters, and slug is should not have caps). I have removed the hERG Tag, why did you choose it @russelljeffrey?
Before starting the model incorporation, can you confirm that you are able to run Ersilia models in your system?

Thanks

**Comment by russelljeffrey** [comment]
Hi @GemmaTuron . The reason I chose hERG in the tag was that authors used hERG in the article as one of the benchmark datasets, and thank you for updating the discrimination.  Yes ersilia can fully function on my system since I use a dedicated GitHub codespace.

**Comment by GemmaTuron** [comment]
Hi @russelljeffrey 

Are you still active on this model? Let me know the status and add here if you have any comments

**Comment by russelljeffrey** [comment]
Hello @GemmaTuron . Yes I'm still active and I believe the implementation will be finished until the end of this week. The implementation of tokenizer is complete but testing is still needed. So I will soon test the model to make sure it's ready to be used.

**Comment by GemmaTuron** [comment]
This model is completed!
