### ISSUE TITLE
🦠 Model Request: Chembl Sampler

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#762]
### Model Name

ChEMBL Molecular Sampler

### Model Description

A simple sampler of the ChEMBL database using their API. It looks for similar molecules to the input molecule and returns a list of 1000 molecules by default. This model has been developed by Ersilia.

### Slug

chembl-sampler

### Tag

Similarity, ChEMBL

### Publication

https://academic.oup.com/nar/article/40/D1/D1100/2903401

### Source Code

https://github.com/ersilia-os/chem-sampler/blob/main/chemsampler/samplers/chembl/sampler.py

### License

GPL-3.0

**Comment by miquelduranfrigola** [comment]
@GemmaTuron I have tested this model and it works. Cleaning the issue now. Feel free to re-open.
