### ISSUE TITLE
🦠 Model Request: Stoned Sampler

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#765]
### Model Name

Stoned Sampler

### Model Description

The STONED sampler uses small modifications to molecules represented as SELFIES to perform a search of the chemical space and generate new molecules

### Slug

stoned-sampler

### Tag

Generative

### Publication

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8153210/

### Source Code

https://github.com/aspuru-guzik-group/stoned-selfies

### License

Apache-2.0

**Comment by GemmaTuron** [comment]
@simrantan, when you finish your tasks could you work in this model incorporation?

**Comment by miquelduranfrigola** [comment]
This model now works. I am closing the issue. Feel free to reopen anytime, @GemmaTuron
