### ISSUE TITLE
Update AirTable key access

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#766]
AirTable has sent a notice about key deprecation: https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824?utm_ID=rec2agl0dkXWWOAhl&utm_campaign=it_ss_api_key_deprecation_notice&utm_content=email_1a-api-key-deprecation-notice-reminder&utm_extra5=developer&utm_medium=email&utm_source=lifecycle_team

We need to act correspondingly.

**Comment by GemmaTuron** [comment]
@miquelduranfrigola is this done?

**Comment by miquelduranfrigola** [comment]
Not yet. Marking it as critical.

**Comment by miquelduranfrigola** [comment]
OK, I have replaced the Ersilia API Key with Personal Access Tokens as part of our GitHub Secrets, following [this tutorial](https://airtable.com/developers/web/guides/personal-access-tokens?utm_ID=reck2IIeNSn9P0fla&utm_source=lifecycle_team&utm_medium=email&utm_campaign=it_ss_api_key_final&utm_content=email_1a-users&utm_extra5=1mo-api-users) from AirTable.

This seems to work in our GitHub Actions out of the box: https://github.com/ersilia-os/ersilia-stats/actions/runs/7697107929

PyAriTable seems to handle this change out of the box. The GitHub secret is still called `AIRTABLE_API_KEY`, though, which I don't really like since it should now be called `AIRTABLE_PAT` or `AIRTABLE_PERSONAL_ACCESS_TOKEN`. However, modifying this would imply changing all GitHub Actions workflows for each of the models, which I don't think we want to do yet.
