### ISSUE TITLE
🦠 Model Request: Test Model Bentolite

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#770]
### Model Name

Test model bentlite

### Model Description

Prediction of the antimalarial potential of small molecules. This model was originally trained on proprietary data from various sources, up to a total of >7M compounds. The training sets belong to Evotec, Johns Hopkins, MRCT, MMV - St. Jude, AZ, GSK, and St. Jude Vendor Library. In this implementation, we have used a teacher-student approach to train a surrogate model based on ChEMBL data (2M molecules) to provide a lite downloadable version of the original MAIP

### Slug

test-model-bentolite

### Tag

Malaria,P.falciparum

### Publication

https://example.com

### Source Code

https://example.com

### License

GPLv3

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 

Shall I close this issue and eliminate the repository?

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 

Could I close this issue and eliminate the repository?

**Comment by GemmaTuron** [comment]
@miquelduranfrigola and  @DhanshreeA is this model still needed for testing or we can clean this up?

**Comment by miquelduranfrigola** [comment]
We can clean this up, @GemmaTuron - thanks for staying on top of this.

**Comment by GemmaTuron** [comment]
I will DELETE the repo - let me know if that would be a problem or I'll do it today

**Comment by miquelduranfrigola** [comment]
Go ahead

**Comment by GemmaTuron** [comment]
Done, I'll close this issue
