### ISSUE TITLE
Removing BentoML dependency

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#771]
I am opening this issue to discuss and report on our progress towards removing hard requirement for BentoML in Ersilia. While this library has been very useful thus far, it is causing dependency issues. We need to allow a modality that does not require BentoML.

We are approaching this in two steps:

- [x] Ersilia can be installed without BentoML. In this case, models fetched from DockerHub (`--from_dockerhub`) or hosted (`--from_hosted`) will still work.
- [x] @ZakiaYahya is working on a [BentoLite](https://github.com/ersilia-os/bentolite) repository that contains a light version of BentoML, ideally without `protobuf`, `chardet` and `SQLAlchemy` dependencies, which are typically the more problematic ones.

We will use this thread to share progress on this front.

**Comment by miquelduranfrigola** [comment]
**Update**

After working a lot on BentoLite, we have decided to discontinue its development for now. It is too difficult to get rid of hard dependencies such as protobuf, py_zipkin, and others.

A better strategy may be:
1. Enable compatibility with newer versions of BentoML - this may resolve dependency clashes.
2. Develop Ersilia's own deployment library, based on FastAPI or Flask only.

**Comment by GemmaTuron** [comment]
Should we then close this issue @miquelduranfrigola ?

**Comment by miquelduranfrigola** [comment]
Yes, let me close it. It was impossible to solve.
