### ISSUE TITLE
🦠 Model Request: MolPMofit

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#784]
### Model Name

Molecular Prediction Model Fine-Tuning (MolPMoFiT)

### Model Description

Using self-supervised learning, the authors pre-trained a large model using one millon unlabelled molecules from ChEMBL. This model can subsequently be fine-tuned for various QSAR tasks. Here, we provide the encodings for the molecular structures using the pre-trained model, not the fine-tuned QSAR models. 

### Slug

molpmofit

### Tag

Descriptor, Embedding

### Publication

https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00430-x

### Source Code

https://github.com/XinhaoLi74/MolPMoFiT

### License

None

**Comment by GemmaTuron** [comment]
For this model, we would use the pretrained model - the one named ChembL (without the SP), available in the [Pre-trained Models Download](https://github.com/XinhaoLi74/MolPMoFiT#pre-trained-models-download)
The goal here is just to get the embedding, the encoding of the SMILES; not the downstream QSAR prediction (which needs tuning with specific datasets)

**Comment by GemmaTuron** [comment]
@carcablop if you can update your work on this model I can provide follow up to get the embeddings

**Comment by carcablop** [comment]
Hi @GemmaTuron 
Thanks you so much for approval the model. I'm going to update the model and share you.

**Comment by carcablop** [comment]
Hello @GemmaTuron 
These have been the changes that I have made to the model to obtain the embeddings.
[eos9zw0](https://github.com/carcablop/eos9zw0)
Running it from my location, outside of Ersilia, I have the following results for the first molecules.

[prueba_1.csv](https://github.com/ersilia-os/ersilia/files/13454280/prueba_1.csv)

The error that initially appeared in the environment configuration was related to the version of numpy,:
_`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (24316,) + inhomogeneous part.`_
I changed the numpy version to 1.23.1 and the error no longer appeared.

Please can you take a look at obtaining the embeddings? The model returns for each smiles a list of arrays, where each array corresponds to a vector related to the character of that smile. The function that calculates the embeddings returns a matrix where each row corresponds to a vector of embeddings of each character of the smiles, and has a dimension of 400. So I only print the first 100 elements of the vector,

Thank you, and apologise for the delay in this task.

**Comment by GemmaTuron** [comment]
Hi @carcablop no problem! thanks for the work and the nice explanations as always, I'll have a look during this week :)

**Comment by GemmaTuron** [comment]
Hi @carcablop 

Good job! We were wondering with @miquelduranfrigola why you were keeping only the first 100 numbers of the embedding instead of the 400? And then you are missing making the mean of all the tokens of each smiles to get one embedding of 400 (or 100) length:
```
# my model
def my_model(smiles_list):
    list_embeddings=[]
    tokenizer = MolTokenizer()
    for smile in smiles_list:
        smile_tokenizer=tokenizer.tokenizer(smile)
        indices = [qsar_db.vocab.itos.index(token) for token in smile_tokenizer]
        embes = embs_v1[indices][:, :].numpy() # embes=embs_v1[indices][:, :100].numpy()
        embes = np.mean(embes, axis=0)
        list_embeddings.append(embes)

    return list_embeddings
```

Also, the writing of the output needs to be modified:
```
# write output in a .csv file
with open(output_file, "w") as f:
    writer = csv.writer(f)
    writer.writerow(["emb-{0}".format(i) for i in range(400)])  # header
    for o in outputs:
        writer.writerow(list(o))
```

But very good job, I am not familiar with the FastAI library and its not an easy one!

**Comment by carcablop** [comment]
Thanks you so much @GemmaTuron. Request a PR to incorporate the model: [](https://github.com/ersilia-os/eos9zw0/pull/1)

**Comment by GemmaTuron** [comment]
The model is incorporated, thanks for the fantastic work @carcablop !
