### ISSUE TITLE
🐛 Bug: Action `predict-model-input.yml` fails for model `eos3b5e`

### ISSUE THREAD

**Issue by raul-bermejo** [ersilia-os/ersilia#808]
### Describe the bug.

Trying to run [predict-model-input.yml](https://github.com/ersilia-os/ersilia/actions/runs/6332980186/workflow) for the `eos3b5e` returns the following error
```
KeyError: 'Input'
Error: Process completed with exit code 1.
```
See full log here:  [logs_5943.zip](https://github.com/ersilia-os/ersilia/files/12744694/logs_5943.zip)

### Describe the steps to reproduce the behavior

1. Go to [predict-model-input.yml](https://github.com/ersilia-os/ersilia/actions/workflows/predict-model-input.yml)
2. Input `eos3b5e`
3. Press 'Run Workflow'

### Expected behavior.

Example of expected behaviour for a different model:

![Screenshot 2023-09-28 at 12 04 00 pm](https://github.com/ersilia-os/ersilia/assets/71199946/d53645c8-6e6c-48c2-9463-cdca99567182)

### Screenshots.

![Screenshot 2023-09-28 at 10 31 10 am](https://github.com/ersilia-os/ersilia/assets/71199946/cba67f30-3a64-405f-a73b-cf65c3c08782)

### Operating environment

GH managed runner: Ubuntu 22.04.3 LTS

### Additional context

I found the same error occurs for other models such as:
- `eos65rt`
- `eos4avb`
- `eos77w8`

**Comment by GemmaTuron** [comment]
Thanks @raul-bermejo 
This action is a bit old so it might be we need to update it! Bringing @carcablop on the discussion in case she has a suggestion, I'll try to find time this week to look at this!

**Comment by miquelduranfrigola** [comment]
Hi @raul-bermejo - I think the issue is solved, now: https://github.com/ersilia-os/ersilia/actions/runs/6414662406/job/17415400528

It had to do with a missing empty field in AirTable (Input). I will close the comment but feel free to reopen it if you experience any problems!
