### ISSUE TITLE
✍️ Contribution period: Aml

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [ersilia-os/ersilia#819]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Hi Guys!
if you wonder how I took the decision to join your project so fast! It's because I was contributing to Ersilia's last outreachy contribution period.
Here's a link to my issue: https://github.com/ersilia-os/ersilia/issues/621

**Comment by DhanshreeA** [comment]
Hi @Aml-Hassan-Abd-El-hamid welcome back! Please go ahead and tick off the tasks completed from week 1, and proceed with the remaining tasks, like installing ersilia and testing out the simplest model. Thanks.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Thank you very much @DhanshreeA

**Comment by DhanshreeA** [comment]
Hi @Aml-Hassan-Abd-El-hamid I see that you have ticked off ersilia installation and motivation letter from week 1 tasks. Can you confirm if you have a working installation of ersilia on your system? In addition, could you please add a motivation letter here.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
I chose to work with STOUT,
I installed the model following the instructions from its readme, 

I ran into 2 errors while trying to install that model,

1- during the installation, while I was using `conda install -c decimer stout-pypi`, I ran into the same issue last continuation period and I knew that the solution was to run `pip install STOUT-pypi`

2- While trying to import `translate_forward, translate_reverse`, I ran into `jvm dll not found: define/path/or/set/java_home/variable/properly`, I know that @ZakiaYahya ran into the same error last contribution period and she solved it by  by installing OpenJDK manually using "sudo apt install default-jre" command, so I followed the same procedure and fixed the issue.

**Comment by HellenNamulinda** [comment]
Hello @Aml-Hassan-Abd-El-hamid,
You are yet to complete week 2 tasks. Were you able to make predictions using the STOUT model?
Is there any assistance we can offer to support you?

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
I'm sorry to say that but due to personal reasons I wasn't able to continue the contribution period work, I'll close this issue.
