### ISSUE TITLE
contribution Period: Angel_Nagaba

### ISSUE THREAD

**Issue by angelnagaba** [ersilia-os/ersilia#824]
## Week 1 - Get to know the community

- [X] Join the communication channels
Done, Joined the slack channel community 
- [X] Open a GitHub issue (this one!)
Done, issue created
- [x] Install the Ersilia Model Hub and test the simplest model
Successfully installed Ersilia Model hub following the instructions provided on this [link](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation)
In summary, i followed the following steps; 
### Installing the development enviroment 
1. Installed an oracle VirtualBox since my computer runs Windows os. I followed the steps below;

-  I downloaded the setup from this [site ](https://www.virtualbox.org/wiki/Downloads) , 
- I then created an ubuntu Virtual machine from the virtualbox (Click add new and go ahead to create the Virtual Machine) 
<img width="709" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/b2ddda96-abfa-48bb-b372-3b62946d777c">

- To Open the ubuntu VM such that ubuntu can install, Click the created Virtual machine and click Start, I encountered an error that i am still figuring out. 
<img width="190"  class="center" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/0c395666-3122-416c-b4da-1e479bb05de7"> 

To solve the error, Instead did a headless start which runs the Virtual machine in the background ( I am still working on figuring out the error for a normal start of the virtual machine)

### Install the gcc compiler
This can be installed using the command
`sudo apt install build-essential`
<img width="370" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/ddc326ad-2b86-49e6-89c6-6f64657df258">

### Install Python and Conda 
I achieved this by installing Anaconda and it catered for both. I used the instructions on this [page](https://docs.anaconda.com/free/anaconda/install/index.html) 
In Summary, 

- download anaconda for Linux from this [Link](https://repo.anaconda.com/archive/Anaconda3-2023.09-0-Linux-x86_64.sh)
- Open your terminal
- Perform Hash Verification to verify the data integrity of the installer file. Navigate to the Downloads folder and run the command 
`shasum -a 256 file_name ` It returns a generated character string, Copy the string and navigate to this [website ](https://docs.anaconda.com/free/anaconda/reference/hashes/Anaconda3-2023.07-1-Linux-x86_64.sh-hash/) to verify that the generated hash exists on the site. Please note that my generated Hash no matches the number on the site. 

<img width="543" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/8bf14c3e-b54b-49a3-8871-28cd6840dd4e">

<img width="701" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/3f9477ab-95ca-4eed-9bd1-b96a2db00751">

The proceed and install anaconda using the command below; 
`bash ~/Downloads/Anaconda3-2020.05-Linux-x86_64.sh` Follow through the steps on the terminal and proceed with the installation, use the enter keyboard key to navigate the terms and conditions

When complete, test to see whether conda has been intalled correctly by running the command 
`conda` `python3`

I encountered an error where conda command was not being recognized and i solved it by manually adding conda to the environment variables with the command below 
`export PATH=~/anaconda3/bin:$PATH`

### Install Git and GitHub CLI
Because Ersilia models are built on their github organisation, they are essential to easily run the models. These are pretty much straight forward to install using the command below, The installation was smooth
`conda install gh -c conda-forge` 

You can proceed and login using the github command line with the following command 
`gh auth login`

###I then Installed git Lfs 
This is helpful since some pre-trained models require Git Large File storage. I installed using this command
`conda install git-lfs -c conda-forge`  and then activated it using the command `git-lfs install` This too was straight forward

### The Isaura Data Lake 
This can be installed using the command `python -m pip install isaura==0.1`  It is advisable to install the correct version in this case version0.1. Isaura helps you to store/cache your model predictions on your local machine. 
I used this command `python -m pip install isaura==0.1`
<img width="370" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/31e443e5-d267-45e3-b944-46e9a9d1da41">
### Install Ersilia 
First I began by setting up the conda environment again using the commands below;
`conda create -n ersilia python=3.7`
`conda activate ersilia`
Then install Ersilia by fetching from Github Using the following commands 
`git clone https://github.com/ersilia-os/ersilia.git`
`cd ersilia`
`pip install -e .`

Check whether ersilia has been installed correctly 
`ersilia --help`
`ersilia catalog`

- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and Run an ML Model 

- [x] Select a model from the suggested list 
- [ ] Install the model in your system 
- [ ] Run Predictions for the EML
- [ ]  Compare results with the Ersilia Model Hub implementation!
- [ ]  Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by DhanshreeA** [comment]
Hi @angelnagaba thanks for such detailed updates! A quick suggestion, you could elaborate the steps you followed (or even any issues you ran into) as additional comments within this issue instead of editing and adding everything to the description.

**Comment by DhanshreeA** [comment]
@angelnagaba Could you run the simplest model using the ersilia CLI provided in the setup instructions?

**Comment by angelnagaba** [comment]
- [x] Write a motivation statement to work at Ersilia

My name is Angel Nagaba, I am a software engineering graduate from Makerere University Kampala Uganda. I currently work as a business intelligence trainee. I have been interested in open source but never been sure how to contribute as a data science enthusiast, Finding out about this project really excited me. 

Contributing to this project will not only help me to learn and improve my skills in python and data science but also contribute to the cause of ersilia model hub. 
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by angelnagaba** [comment]
## Motivational Statement
My name is Angel Nagaba, I am a software engineering graduate from Makerere University Kampala Uganda. I currently work as a business intelligence trainee. My decision to contribute to ersilia was largely influenced by my skillset in Python and git as well as my deep interest in Machine Learning and Data Science. I was looking for a project that would help me grow and improve my skills as well as expose me to real-life machine learning application. This project is particularly interesting to me because of my interest in data science for health. To me this is a foundation to understand the application of Data and Machine learning to global health and how it can transform the world. 

Additionally, I have been interested in open source but never been sure how to contribute as a data science enthusiast, Finding out about this project really excited me and the opportunity to learn and contribute towards something that I am passionate about is truly exciting.

I believe that by the end of this contribution period, I will have learned and improved my skills in python and data science, chemistry and molecular biology, and computational pharmacology. I look forward to learning and applying these skills to achieve the overall cause of ersilia model hub

**Comment by DhanshreeA** [comment]
Hi @angelnagaba thank you for the updates. You can go ahead and start with Week 2 tasks.

**Comment by angelnagaba** [comment]
### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

**Comment by angelnagaba** [comment]
### Failure to activate ersilia after re-installing conda 
<img width="394" alt="image" src="https://github.com/ersilia-os/ersilia/assets/41667860/6ef192c8-fc32-4abf-9b79-f3f774bc0353">

I solved this by re-creating the ersilia conda environment with the command. `conda create -n ersilia python=3.7` This was because conda was previously uninstalled and there was need to recreate the conda ersilia environment

**Comment by angelnagaba** [comment]
### Docker Error when Fetching models. 
I have tried to install ersilia in WSL and VM, however in both cases i still get an error warning when i try to fetch models even though the models are eventually fetched successfully. Kindly help out resolving this @DhanshreeA

**Comment by Kadeniyi23** [comment]
Good afternoon, 

Well done on your tasks. However are you doing the week 2 tasks according to the guidelines [here](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023). Please let me know if I'm doing it wrong?

**Comment by angelnagaba** [comment]
> Good afternoon,
> 
> Well done on your tasks. However are you doing the week 2 tasks according to the guidelines [here](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023). Please let me know if I'm doing it wrong?

Thanks for the headsup, I have been using the old tutorial. Let me align. I think you are doing it right

**Comment by DhanshreeA** [comment]
Hi @angelnagaba this is tricky! Without knowing the state of your sudo configuration it's hard to say what's going on. I have a few questions:
1. Are you running into this sudo error (unrecognized user name AND error initializing plugin sudoers_audit) on both the VM and WSL?
2. Can you show the contents of your `/etc/hosts` file? And from `/etc/sudo.conf`, and `/etc/sudoers`?

**Comment by DhanshreeA** [comment]
Hi @angelnagaba just following up, do you have any updates on this?

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
