### ISSUE TITLE
🐛 Bug: Error when running 'ersilia -v api run -i <input>' command

### ISSUE THREAD

**Issue by PromiseFru** [ersilia-os/ersilia#825]
### Describe the bug.

When I run the following command:

```
ersilia -v api run -i "CCCC"
```

I encounter the following error:

```
Traceback (most recent call last):

File "/home/Ersilia/ersilia/ersilia/io/readers/file.py", line 321, in read_input_columns
if len(h) == 1:
TypeError: object of type 'NoneType' has no len()
```

### Describe the steps to reproduce the behavior

1. Run the command: `ersilia -v api run -i "CCCC"`
2. Observe the error.

### Expected behavior.

I expect that running the `ersilia -v api calculate -i "CCCC"` command should calculate the molecular weight of the input molecule ("CCCC") and display the result in the CLI as follows:

```
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}
```

### Operating environment

Ubuntu 20.04.6 LTS (Focal Fossa)

### Additional context

I found that modifying line 321 in `/ersilia/io/readers/file.py` from:

```python
if len(h) == 1:
```

to:

```python
if h is not None and len(h) == 1:
```

resolves the issue.

**Comment by DhanshreeA** [comment]
Hi @PromiseFru I suspect you ran into this issue while running the `eos3b5e` model. Just a quick tip, while creating issues here, it's useful for the maintainers if you mention the model id/ model name.

Additionally, you should not need to modify anything within the Ersilia CLI codebase. For resolving this issue, please refer to the wonderful discussion here: https://github.com/ersilia-os/ersilia/issues/820. If you are still unable to get the model to work, please use your Contribution Period issue to log any errors you encountered.
