### ISSUE TITLE
🐛 Bug: Key error when running 'ersilia -v api calculate -i <input>' command

### ISSUE THREAD

**Issue by leilayesufu** [ersilia-os/ersilia#826]
### Describe the bug.

When I ran the following command:
 
`ersilia -v api run -i "CCCC"`

I came across a KeyError with the message: `KeyError: 'calculate'`.

### Describe the steps to reproduce the behavior

1. Set up Ersilia using [the installation guide](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation)
2. Test a very simple model
    `ersilia -v fetch eos3b5e`
    `ersilia serve eos3b5e`
    `ersilia -v api calculate -i "CCCC"`

### Expected behavior.

I expected that running the `ersilia -v api calculate -i "CCCC"` command should calculate the molecular weight of the input molecule ("CCCC") and display the result in the CLI as seen below:

`{
  
  "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}`

### Operating environment

Ubuntu 22.04.2 LTS

### Additional context

To make predictions, ersilia uses a standard API run.
So, instead of `ersilia -v api calculate -i "CCCC"`, use `ersilia -v api run -i "CCCC"`

I think the  docs need to be updated to reflect this.

**Comment by DhanshreeA** [comment]
Hi @leilayesufu I believe this issue is no longer relevant, thank you for your efforts!
