### ISSUE TITLE
✍️ Contribution period: Rabius

### ISSUE THREAD

**Issue by R-sany** [ersilia-os/ersilia#829]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by R-sany** [comment]
![outreachy-logo](https://github.com/ersilia-os/ersilia/assets/112888846/d15870ad-95b3-4c53-b1d6-767f9ebc20d8)

### Outreachy Winter 2023 Contribution
_Md Rabius Sany Apu_



 _Electronics Engineer,  ML Enthusiast_

**Comment by R-sany** [comment]
### Week 1 - Get to know the community

- ### Join the communication channels

3rd October. It started. I joined Ersila's community Slack channel. For next couple of weeks, I will be working with the mentors alongside fellow contributors. 

- ### Open a GitHub issue (this one!)

To track the contributors progress, Ersila provided this beautiful repo. Liked it.

> A thousand mile journey begins with one step , Lao Tzu.

**Comment by carcablop** [comment]
Hello @R-sany 
Welcome to Ersilia. Be sure to complete the installation steps and run a model. The complete guide can be found here: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation and report here your progress.
Thanks.

**Comment by R-sany** [comment]
> Hello @R-sany Welcome to Ersilia. Be sure to complete the installation steps and run a model. The complete guide can be found here: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation and report here your progress. Thanks.

**Comment by R-sany** [comment]
- Install the Ersilia Model Hub and test the simplest model

**Comment by R-sany** [comment]
- ### Write a motivation statement to work at Ersilia

When I first hear the word "Ersilia", I felt an immediate warmth and care. Maybe because it's symbolized a strong, yet caring figure.  In the face of AI inequality, its fighting against the dominance and nurturing those in need. Opening a doorway to freedom and equality. 
In next few paragraphs I'll try my best to demonstrate my intention to join this beautiful Community.

### Who I am ?

My name is Rabius. I born in a small country called Bangladesh, one of the most densely populated but beautiful country.  As a lower tier country, I've seen poverty, hunger and courage to survive. It shaped me who I am right now.

**Comment by R-sany** [comment]
- ### Write a motivation statement to work at Ersilia

When I first hear the word "Ersilia", I felt an immediate warmth and care. Maybe because it's symbolized a strong, yet caring figure.  In the face of AI inequality, its fighting against the dominance and nurturing those in need. Opening a doorway to freedom and equality. 
In next few paragraphs I'll try my best to demonstrate my intention to join this beautiful Community.

### Who I am ?

My name is Rabius. I born in a small country called Bangladesh, one of the most densely populated but beautiful country.  As a lower tier country, I've seen poverty, hunger and courage to survive. It shaped me who I am right now.

**Comment by R-sany** [comment]
- ### Submit your first contribution to the Outreachy site

✅Submitted the first Contribution to the Outreachy site.

**Comment by R-sany** [comment]
### Week 2 - Install and run an ML model

- ### Select a model from the suggested list

**Comment by DhanshreeA** [comment]
Hi @R-sany just following up are you stuck anywhere? Do you need more support?

**Comment by R-sany** [comment]
Thank you so much @DhanshreeA for checking on me. Actually, I'm going through an emotional toll. I've been constantly rejected throughout the year. So, I've a fear that. this will be like previous failures. Painful and heartbroken. I'll start working again after my heads clears ups a bit.

**Comment by R-sany** [comment]
- ###  Install the model in your system

:rotating_light:Installing CUDA 10.1
```
I don't have a dedicated GPU, Skipped this as CUDA is not supported
```
:white_check_mark:Successfully created new conda environment 
```
conda create -n imagemol python=3.7.3

conda activate imagemol
```

:white_check_mark:Successfully Installed some required paackages
```
conda install -c rdkit rdkit
```
:white_check_mark:Successfully Installed Torch 1.4.0 CPU version
```
I downloaded and installed with the following link and command as its much reliable.
```
```
Download Link: download.pytorch.org/whl/cpu/torch-1.4.0+cpu-cp37-cp37m-linux_x86_64.whl
```   
```
pip install torch-1.4.0+cpu-cp37-cp37m-linux_x86_64.whl
```
:white_check_mark:Successfully Installed Torch Vision 0.5.0 CPU version
```
I downloaded and installed with the following link and command
```
```
Download Link: download.pytorch.org/whl/cpu/torchvision-0.5.0+cpu-cp37-cp37m-linux_x86_64.whl
```
```
pip install torchvision-0.5.0+cpu-cp37-cp37m-linux_x86_64.whl
```
:white_check_mark:Successfully Downloaded wheels of torch-cluster torch-scatter torch-sparse torch-spline-conv CPU version
```
Download Link: https://pytorch-geometric.com/whl/torch-1.4.0%2Bcpu.html
```
:white_check_mark:Successfully installed wheels of torch-cluster torch-scatter torch-sparse torch-spline-conv CPU version
```
pip install torch_cluster-1.5.3-cp37-cp37m-linux_x86_64.whl
``` 
```
pip install torch_scatter-2.0.4-cp37-cp37m-linux_x86_64.whl
```
```
pip install torch_sparse-0.6.1-cp37-cp37m-linux_x86_64.whl
```
```
pip install torch_spline_conv-1.2.0-cp37-cp37m-linux_x86_64.whl
```
:white_check_mark:Successfully downloaded and installed requirements to be on safe side

```
pip install -r requirements.txt
```
:white_check_mark:Downloaded pre-train data and putted it into ./datasets/pretraining/data/
 
:white_check_mark:processed dataset
```
python ./data_process/smiles2img_pretrain.py --dataroot ./datasets/pretraining/ --dataset data
```
 :rotating_light:pre-train ImageMol using single CPU on toy dataset:
```
python pretrain.py --ckpt_dir ./ckpts/pretraining-toy/ \
                   --checkpoints 1 \
                   --Jigsaw_lambda 1 \
                   --cluster_lambda 1 \
                   --constractive_lambda 1 \
                   --matcher_lambda 1 \
                   --is_recover_training 1 \
                   --batch 16 \
                   --dataroot ./datasets/toy/pretraining/ \
                   --dataset data \
                   --gpu 0 \
                   --ngpu 1
```
```
This error occurred due to cuda() function
```
```
Solution:
changed cuda() to cpu() function in pretrain.py
```
:white_check_mark:pre-train ImageMol using single CPU on toy dataset 
```
python pretrain.py --ckpt_dir ./ckpts/pretraining-toy/ \
                   --checkpoints 1 \
                   --Jigsaw_lambda 1 \
                   --cluster_lambda 1 \
                   --constractive_lambda 1 \
                   --matcher_lambda 1 \
                   --is_recover_training 1 \
                   --batch 16 \
                   --dataroot ./datasets/toy/pretraining/ \
                   --dataset data \
                   --gpu 0 \
                   --ngpu 1
```
Pretrain_toy_log: [ImageMol_pretrain_toy.log](https://github.com/ersilia-os/ersilia/files/12906703/ImageMol_pretrain_toy.log)

**Comment by DhanshreeA** [comment]
Hi @R-sany thank you for the updates so far. Just following up, could you run the model further especially on the EML file?

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
