### ISSUE TITLE
✍️ Contribution period:  Tshifhumulo Mapasa

### ISSUE THREAD

**Issue by Tshifhumulo10** [ersilia-os/ersilia#834]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by DhanshreeA** [comment]
Hi @Tshifhumulo10 can you confirm if you were able to run Ersilia with the simplest model and obtain the desired output as mentioned in the instructions?

**Comment by Tshifhumulo10** [comment]
> Hi @Tshifhumulo10 can you confirm if you were able to run Ersilia with the simplest model and obtain the desired output as mentioned in the instructions?

Hi @DhanshreeA  thank you for checking up. I was able to run Ersilia with the simplest model and obtained output as mentioned in the instructions.  I was able to do so after reading the instruction given by @HellenNamulinda,  instrichttps://github.com/ersilia-os/ersilia/issues/820#issuecomment-1744307345

**Comment by Tshifhumulo10** [comment]
**Retrospection**

1.  joined the Slack community, and I was so intrigued by the collaboration, and I am happy to be part of the community. 
2.  Opened the issue, and I was very motivated when I saw  that other interns had already completed this week to-do list.
3.  installed the Ersilia model hub and tested the simplest model and below are the steps that I took:  

- I am using Windows operating system, so I downloaded Windows Subsystem for Linux (WSL) with an Ubuntu distribution as instructed https://www.outreachy.org/outreachy-december-2023-internship-round/communities/ersilia-open-source-initiative/#improvement-of-the-ersilia-model-hub-a-foss-platfo:~:text=If%20you%20are%20working%20with%20Windows%2C%20we%20recommend%20installing%20a%20Windows%20Subsystem%20for%20Linux%20(WSL)%20with%20an%20Ubuntu%20distribution.

-Installed the gcc compiler:
![Screenshot 2023-10-06 001743](https://github.com/ersilia-os/ersilia/assets/115041717/d704d52b-5fe4-4553-86d4-7097da23ddc4)

- Installed miniconda in ubuntu:
![Screenshot 2023-10-06 004604](https://github.com/ersilia-os/ersilia/assets/115041717/61da8ae0-83aa-4e05-a6d3-d1c3e8d14cf1)

- Installed Git and GitHub CLI: 
![Screenshot 2023-10-06 005320](https://github.com/ersilia-os/ersilia/assets/115041717/3a7c4930-e068-4f13-a18d-d8bc7b361c20)

-Used GitHub CLI to login github:
![Screenshot 2023-10-06 005505](https://github.com/ersilia-os/ersilia/assets/115041717/d9015a35-7887-4bc0-bde8-bb89e470c69b)

- Installed Git LFS from Conda:
![Screenshot 2023-10-06 010632](https://github.com/ersilia-os/ersilia/assets/115041717/b2538dc7-7b99-455b-8241-fcf3470b7e96)

- Activated Git LFS:
![Screenshot 2023-10-06 010727](https://github.com/ersilia-os/ersilia/assets/115041717/892040db-22d5-429d-b518-2f9a4c23e52d)

-  Installed Isaura data lake:
![Screenshot 2023-10-06 012032](https://github.com/ersilia-os/ersilia/assets/115041717/697e3432-8836-4d95-9d72-bf2bb03c7b77)

- Installed Docker:
![Screenshot 2023-10-06 013232](https://github.com/ersilia-os/ersilia/assets/115041717/8f39b7c9-3276-40d6-9ab6-84b69411f109)

- Installed the Ersilia tool:
![Screenshot 2023-10-06 013022](https://github.com/ersilia-os/ersilia/assets/115041717/ce183773-05a8-4e31-8c68-d97ffeb6d9fb)

-  Installed  the Ersilia Python package:
![Screenshot 2023-10-06 013357](https://github.com/ersilia-os/ersilia/assets/115041717/04deda0a-a8fe-4621-9295-62ce068bb806)

- Fetched a model:
![Screenshot 2023-10-06 014525](https://github.com/ersilia-os/ersilia/assets/115041717/fb5cdcc0-50c8-41db-8005-7e3c05ace1ff)

- Served a model: 
![Screenshot 2023-10-06 015701](https://github.com/ersilia-os/ersilia/assets/115041717/a6b6e81b-a5c4-4726-bfa5-3295f7017cbd)

- Run the model: 
![Screenshot 2023-10-06 015813](https://github.com/ersilia-os/ersilia/assets/115041717/c8378ad6-ef94-48bc-bace-2708bd3b94e9)

- Output:
![Screenshot 2023-10-06 015924](https://github.com/ersilia-os/ersilia/assets/115041717/6b875555-7f53-45d8-a89f-0c3443b7d819)

**Comment by Tshifhumulo10** [comment]
**Motivation statement to work at Ersilia**           

I am drawn to the Ersilia project for several compelling reasons. First and foremost, I believe in the transformative power of data. In the words of Clive Humby, "Data is the new oil," and I've witnessed firsthand how harnessing data can drive innovation and impact lives positively.

With a background in Biochemistry and Microbiology, I ventured into the world of data science through intensive coursework. As I navigated through various projects and opportunities, I was pleasantly surprised to stumble upon Ersilia. What immediately struck me was the project's harmonious blend of cutting-edge technology and domain expertise.

Having spent time working in a laboratory, I understand the tangible difference Ersilia's projects make in the scientific community and beyond. I am passionate about being part of a team that bridges the gap between data scientists and experimental researchers, making AI/ML expertise accessible to scientists worldwide. This aligns perfectly with my values of transparency, knowledge sharing, and collaboration.

Ersilia's dedication to advancing technology in machine learning, cloud computing, and data privacy promises to keep me at the forefront of technological progress—a prospect that excites me greatly. Furthermore, the project's unique fusion of chemistry, molecular biology, and computational pharmacology, combined with a deep commitment to global health, presents a compelling challenge and an opportunity to create meaningful change.

Lastly, the focus on open-source initiatives aimed at generating low-cost drugs is a testament to Ersilia's commitment to making a positive societal impact. I am honored and eager to contribute my skills and enthusiasm to this noble cause. I am deeply motivated to join the Ersilia project because it embodies the values and interests of innovation, collaboration, technology, and making a tangible difference in the world through data-driven solutions. I eagerly anticipate the opportunity to contribute to this remarkable endeavor.

**Comment by DhanshreeA** [comment]
Hi @Tshifhumulo10 thank you for the updates. Please record this as your first contribution on the Outreachy website, and proceed with the tasks from week 2.

**Comment by Tshifhumulo10** [comment]
> Hi @Tshifhumulo10 thank you for the updates. Please record this as your first contribution on the Outreachy website, and proceed with the tasks from week 2.

Hi @DhanshreeA, I will do just that.

**Comment by DhanshreeA** [comment]
Hey @Tshifhumulo10 all good? Do you need any help?

**Comment by Tshifhumulo10** [comment]
> Hey @Tshifhumulo10 all good? Do you need any help?

Hey @DhanshreeA, thank you for checking up. I have been trying to use "NCATS Rat Liver Microsomal Stability" but it took forever to load, So I have switched to STOUT.

**Comment by Tshifhumulo10** [comment]
# Week 2

1. Select a model from the suggested list

From the suggested list, I was drawn to the “NCats Rat Liver Microsomal Stability” because I have always been fascinated about how drugs operate. However, it was taking forever to install, so I switched to STOUT.
Manually translating the SMILES to their IUPAC names can be challenging, thus STOUT is pivotal for such endeavor. I have chosen STOUT model because I understand the impact that these models can make for chemists and researcher in saving their time, reducing errors and increasing the credibility of their work since these models have an accuracy of 90%. 


 2. Install the model in your system

-  First I created a new environment called STOUT and that environment included python =3.8
 `conda create --name STOUT python=3.8 `

- I  sets the environment as the current Python environment for your session, allowing me to work within that specific environment	
 `conda activate STOUT`

-  I installed the package from a specific Conda channel named "decimer”
 `conda install -c decimer stout-pypi`

- Install STOUT from the git repository
`pip install git+https://github.com/Kohulan/Smiles-TO-iUpac-Translator.git
`
- I imported the translate_forward and transalate reverse from STOUT. Translate forward is used translate SMILES to IUPAC name and Translate reverse is used to translate IUPAC names to Smiles 

- I translated the SMILES to IUPAC names using the code below :
```
SMILES = "CN1C=NC2=C1C(=O)N(C(=O)N2C)C"
IUPAC_name = translate_forward(SMILES)
print("IUPAC name of "+SMILES+" is: "+IUPAC_name)
```
**Output:**
![Screenshot 2023-10-12 152106](https://github.com/ersilia-os/ersilia/assets/115041717/fb848d71-8832-4f73-9af4-0b49c74b0789)


- I translated the IUPAC names to SMILES using the code below:
```
IUPAC_name = "1,3,7-trimethylpurine-2,6-dione"
SMILES = translate_reverse(IUPAC_name)
print("SMILES of "+IUPAC_name+" is: "+SMILES)
```
**Output:**
![Screenshot 2023-10-12 152044](https://github.com/ersilia-os/ersilia/assets/115041717/acf77776-93b6-43d6-8f1c-f4733d02ba1d)

**Comment by Tshifhumulo10** [comment]
3. Run predictions for the EML

- Downloaded [EML]([Essential Medical List](https://github.com/ersilia-os/ersilia/blob/master/notebooks/eml_canonical.csv) csv by Ersilia and copied it to my directory. 
-
- Imported pandas and STOUT

```import pandas as pd
from STOUT import translate_forward, translate_reverse
```

- Read the data into a dataframe, before converting 10 SMILES into a list. 
```df=pd.read_csv('eml_canonical (3).csv')
name_smiles = list(df['smiles'].head(10))
```
- Translated the SMILES to IUPAC names 

```IUPAC_nm=[]
for i in name_smiles:
    IUPAC_name = translate_forward(i)
    IUPAC_nm.append(IUPAC_name)
    DF=pd.DataFrame({"SMILES": name_smiles,"Predicted IUPAC": IUPAC_nm})
for i in range(0, 10):
    #print("IUPAC name of " + DF.loc[ i, "SMILES"] + " is: " + DF.loc[i, "Predicted IUPAC"])
```
-OUTPUT
![Screenshot 2023-10-13 133959](https://github.com/ersilia-os/ersilia/assets/115041717/6d282b2c-c29d-46d7-8df1-a9735f99e935)

- Translated the  IUPAC names to SMILES
```
Smiles_nm=[]
for a in IUPAC_nm:
    SMILES = translate_reverse(IUPAC_name)
    Smiles_nm.append(SMILES)
    DF1= pd.DataFrame({"SMILES": name_smiles,"Predicted Smiles" :Smiles_nm})
for i in range(0, 10):  
    print("SMILES of "+DF1.loc[i, "Predicted IUPAC"]+" is: "+ DF1.loc[i, "Predicted Smiles"])
```

OUTPUT:
![Screenshot 2023-10-13 140519](https://github.com/ersilia-os/ersilia/assets/115041717/e907a0c5-9e06-4ee9-b4d5-c308692536d1)

**Comment by Tshifhumulo10** [comment]
4. Compare results with the Ersilia Model Hub implementation!

-  I got the name of the [model](https://github.com/ersilia-os/eos4se9) from the [Ersilia Model Hub implementation](https://github.com/ersilia-os)
`eos4se9`

- I retrieved the name of the SMILES [Downloaded [Essential Medical List] (https://github.com/ersilia-os/ersilia/blob/master/notebooks/eml_canonical.csv)]

![Screenshot 2023-10-15 134626](https://github.com/ersilia-os/ersilia/assets/115041717/cd621d26-e71e-481d-be2f-22cae1fbf062)

- I fetched the model 
 `ersilia -v fetch eos4se9 `

- I served the model
 `ersilia -v serve eos4se9 `

- Run the SMILES

1.`ersilia -v api run -i 'Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1'`

*Output:*
![Screenshot 2023-10-15 135038](https://github.com/ersilia-os/ersilia/assets/115041717/59a0afe9-9360-41f9-8165-621caa86b752)

2. `ersilia -v api run -i 'C[C@]12CC[C@H](O)CC1=CC[C@@H]3[C@@H]2CC[C@@]4(C)[C@H]3CC=C4c5cccnc5'`

*Output:*
![Screenshot 2023-10-15 135525](https://github.com/ersilia-os/ersilia/assets/115041717/e5d3ae4b-6851-4685-a9d9-742b7af32e4a)


3. `ersilia -v api run -i 'CC(=O)Nc1sc(nn1)[S](N)(=O)=O'`
*Output*
![Screenshot 2023-10-15 135802](https://github.com/ersilia-os/ersilia/assets/115041717/37ca7797-1899-4e5c-95dc-f81d1e55b445)

4.  `ersilia -v api run -i 'CC(O)=O'`
*Output*
![Screenshot 2023-10-15 135953](https://github.com/ersilia-os/ersilia/assets/115041717/3d3c7591-be05-4530-b0e0-8d73e398dc21)

5.  `ersilia -v api run -i 'CC(=O)N[C@@H](CS)C(O)=O'`
*Output*
![Screenshot 2023-10-15 140203](https://github.com/ersilia-os/ersilia/assets/115041717/1f3b8a34-7408-43c4-b842-cb5d09177a45)

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
