### ISSUE TITLE
✍️ Contribution period: Ajoke Yusuf 

### ISSUE THREAD

**Issue by Ajoke23** [ersilia-os/ersilia#842]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [x] Suggest a new model and document it (1)
- [x] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by Ajoke23** [comment]
October 2, 
- I joined the slack communicate channel to express my interest in contributing to the success of Ersilia project
- I read the code and conduct

**Comment by DhanshreeA** [comment]
Hi @Ajoke23 thank you for the updates. I see that some items from the week 1 tasks are still pending. Please tell us if you'd like any support in completing them.

**Comment by Ajoke23** [comment]
> Hi @Ajoke23 thank you for the updates. I see that some items from the week 1 tasks are still pending. Please tell us if you'd like any support in completing them. 

Yes, I need support. I am finding it hard to fetch model eos3b5e. I am getting errors regarding connections and I have asked on the snack channels, people gave suggestions and I have tried all that but it isn't working yet.
I went online and saw some related post on the issue on ersilia's repository but none of the suggestion has worked. I am still trying my best to figure it out. I will appreciate any help from you

**Comment by leilayesufu** [comment]
Hi, have you been able to fetch it?

**Comment by Ajoke23** [comment]
**MOTIVATION STATEMENT **

I'm Ajoke Yusuf, a Data Scientist, Machine Learning enthusiast, and SDG 3 advocate. I'm a resourceful, goal-oriented individual who possesses strong analytical and problem-solving skills with an unending quest for knowledge. I pride myself on being a fast learner and honed strong skills in problem-solving and research.
After receiving the Outreachy email, one of my aims before choosing a project is to check out the project whose aim, and mission align with my goal and career objective as an impact maker and an SDG 3 advocate.
I went through each of the projects and I came across Ersilia's project whose mission statement is:
 "On a mission to make science accessible to all"
As an Engineering graduate living in Nigeria, I developed an interest in the biomedical field due to the increasing mortality rate of infectious diseases in Nigeria and sub-Saharan Africa.
Based on statistics, according to  UNICEF (United Nations International Children Emergency Funds):
infectious disease is the major cause of the mortality rate in children ≤ 5 years
This was cited from [here](https://data.unicef.org/topic/child-survival/under-five-mortality/).
 
Research from NIH (National Library of Medicine) & NCBI (National Centre for Biotechnology Information) confirms that: 
"The infrastructure and level of support for surveillance, research, and training on emerging infectious diseases in Africa are extremely limited".  Link [here](https://www.ncbi.nlm.nih.gov/books/NBK99567/#:~:text=At%20a%20time%20when%20increasing, %2C%20yellow%20fever%2C%20and%20trypanosomiasis))

As a Data Scientist, skilled at Python, Machine learning, I possess strong analytical and research skills. I believe that contributing to this project will help me garner knowledge and technical skills that will help in advancing and improving health research in Nigeria. 
If accepted for the 3 months internship, I'll commit myself to bringing suggestions, undergoing research, and collaborating with the Ersilia team while learning and honing skills in Artificial Intelligence and Machine Learning. This period of internship will help propel my research and problem-solving skills which will be useful in the long run for the  advancement of technology in the health sector,  improving and making a sustainable impact in health research in Nigeria
As a young lady living in Nigeria, an underdeveloped and low-income country, I have experienced challenges encountered in having accessibility tools for prevalent infectious diseases in my community and country (Nigeria) at large. After the internship, I plan on utilizing the skills gained to improve and sustain health research tools, solve prevalent health infectious diseases issues in Nigeria, and reduce the mortality rate caused by infectious diseases. Thus, propelling sustainable research skills that will leave a long-lasting impact in the health sector in my community, Nigeria,  sub-Saharan Africa, and eventually, globally.

**Comment by Ajoke23** [comment]
**MOTIVATION STATEMENT **

I'm Ajoke Yusuf, a Data Scientist, Machine Learning enthusiast, and SDG 3 advocate. I'm a resourceful, goal-oriented individual who possesses strong analytical and problem-solving skills with an unending quest for knowledge. I pride myself on being a fast learner and honed strong skills in problem-solving and research.
After receiving the Outreachy email, one of my aims before choosing a project is to check out the project whose aim, and mission align with my goal and career objective as an impact maker and an SDG 3 advocate.
I went through each of the projects and I came across Ersilia's project whose mission statement is:
 "On a mission to make science accessible to all"
As an Engineering graduate living in Nigeria, I developed an interest in the biomedical field due to the increasing mortality rate of infectious diseases in Nigeria and sub-Saharan Africa.
Based on statistics, according to  UNICEF (United Nations International Children Emergency Funds):
infectious disease is the major cause of the mortality rate in children ≤ 5 years
This was cited from [here](https://data.unicef.org/topic/child-survival/under-five-mortality/).
 
Research from NIH (National Library of Medicine) & NCBI (National Centre for Biotechnology Information) confirms that: 
"The infrastructure and level of support for surveillance, research, and training on emerging infectious diseases in Africa are extremely limited".  Link [here](https://www.ncbi.nlm.nih.gov/books/NBK99567/#:~:text=At%20a%20time%20when%20increasing, %2C%20yellow%20fever%2C%20and%20trypanosomiasis))

As a Data Scientist, skilled at Python, Machine learning, I possess strong analytical and research skills. I believe that contributing to this project will help me garner knowledge and technical skills that will help in advancing and improving health research in Nigeria. 
If accepted for the 3 months internship, I'll commit myself to bringing suggestions, undergoing research, and collaborating with the Ersilia team while learning and honing skills in Artificial Intelligence and Machine Learning. This period of internship will help propel my research and problem-solving skills which will be useful in the long run for the  advancement of technology in the health sector,  improving and making a sustainable impact in health research in Nigeria
As a young lady living in Nigeria, an underdeveloped and low-income country, I have experienced challenges encountered in having accessibility tools for prevalent infectious diseases in my community and country (Nigeria) at large. After the internship, I plan on utilizing the skills gained to improve and sustain health research tools, solve prevalent health infectious diseases issues in Nigeria, and reduce the mortality rate caused by infectious diseases. Thus, propelling sustainable research skills that will leave a long-lasting impact in the health sector in my community, Nigeria,  sub-Saharan Africa, and eventually, globally.

**Comment by Ajoke23** [comment]
**WEEK 2**

**Comment by HellenNamulinda** [comment]
Hello @Ajoke23,
From your updated comment [here](https://github.com/ersilia-os/ersilia/issues/842#issuecomment-1748461269), it appears you were able to fetch the model and also completed all the week 1 tasks.
Well done :clap:!

Please proceed to week 2 tasks and update each in a comment for faster follow-up. Incase you need any help, kindly let us know.

**Comment by Ajoke23** [comment]
> Hello @Ajoke23,
> From your updated comment [here](https://github.com/ersilia-os/ersilia/issues/842#issuecomment-1748461269), it appears you were able to fetch the model and also completed all the week 1 tasks.
> Well done :clap:!
> 
> Please proceed to week 2 tasks and update each in a comment for faster follow-up. Incase you need any help, kindly let us know.

Yes, I was able to fetch the model successfully. Thanks a lot @HellenNamulinda

**Comment by Ajoke23** [comment]
> Hello @Ajoke23,
> You are yet to complete week 2 tasks. Is there any way we can support you?

Hi @HellenNamulinda I had lot of challenges doing the week 2 task based on my model of interest, STOUT. But I have been able to figure it out and I will update it soonest. Thank you

**Comment by DhanshreeA** [comment]
Hi @Ajoke23 thank you for the updates. Let us know how it goes! :)

**Comment by Ajoke23** [comment]
### **WEEK 3**

**Comment by Ajoke23** [comment]
Week 4
I have successfully completed recorded my final contribution to Outreachy website. The final contribution contains Project Timeline, all the links to the contribution made i.e task completed and bug found

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
