### ISSUE TITLE
🐛 Bug: Broken Link Found

### ISSUE THREAD

**Issue by Ajoke23** [ersilia-os/ersilia#846]
### Describe the bug.

In Ersilia documentation on installation which can be found in this link: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation. In Pre-requisite 3, second paragraph, the **GitHub CLI** text in yellow color, when one clicks on the link, it returns page not found which may imply a broken link or changes have been made to the link.
![github cli](https://github.com/ersilia-os/ersilia/assets/71567200/0e881ed9-5b78-4c72-9021-20ad692225e5)
This is the screenshot of what I get when I click on the **GitHub CLI** text in yellow color in the second paragraph of Pre-requisite 3

### Describe the steps to reproduce the behavior

1. Go to:  https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation
2. Scroll down to Pre-requiste 3 
3. Click on GitHub CLI text in yellow color to see the error
4. Check if it's the correct link been posted
5. If it's the wrong link, the the correct link when one click on Github CLI should be inputted
6. If changes has been made to the link, then the GitHub CLI should be in black text which denote it's a text not a link text

### Expected behavior.

I expected that when anyone clicks on the **GitHub CLI** text (the one in Yellow color) in the second paragraph of Pre-requisite 3, it would take them to a page that explains the installation of GitHub CLI.
Also, **Github CLI**(in yellow text) is a mistake, then the text should be in a black color 

### Screenshots.

![Ersilia](https://github.com/ersilia-os/ersilia/assets/71567200/0df9910e-496c-4cde-8ab9-64ba505ed0db)

### Operating environment

Ubuntu 22.04.2 LTS

**Comment by miquelduranfrigola** [comment]
Thanks @Ajoke23 - I have updated the link.
