### ISSUE TITLE
✍️ Contribution period: Aderemi Damilola

### ISSUE THREAD

**Issue by aderemi1224** [ersilia-os/ersilia#855]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by aderemi1224** [comment]
I am extremely interested in expressing my enthusiasm for contributing to the
aforementioned project. As a young woman with limited medical experience but a
strong passion for research, I am genuinely excited about the opportunity to
participate in this endeavor. The significance of biomedical research in enhancing
human health cannot be overstated, as it presents a remarkable opportunity to
revolutionize and improve the healthcare industry as a whole. I firmly believe that
my involvement in this project will allow me to make a meaningful impact by
actively contributing to the advancement of medical knowledge and ultimately
benefiting the broader community.
In the past few months, as I embarked on my career as a researcher, I had the
privilege of working on two health-related projects.
Firstly, I conducted an analysis on the sodium content of food from different
vendors and its correlation with hypertension. This involved testing the sodium
levels in various food samples and investigating the relationship between these
variables.
Additionally, I engaged in a breast cancer survival prediction study. Using a
comprehensive open-source dataset from Kaggle, I meticulously analyzed clinical
and genetic variables to assess the chances of survival. Furthermore, I developed a
predictive model that leveraged the analyzed data to accurately predict the
likelihood of survival for individuals affected by this disease.
I view this internship as a remarkable opportunity to collaborate with esteemed
researchers, learn from their expertise, and further my own growth and
development. Moreover, I am eager to contribute my skills and insights to the
advancement of the health sector.

**Comment by aderemi1224** [comment]
I decided to choose the NCATS Rat Liver Microsomal Stability model for this project. I will be contributing to this project because i see it as an opportunity to contribute to improving human health. The understanding of how drugs are metabolized and it's stability in the liver of a rat can help provide an insight on the behavior/impact in the human body.

**Comment by aderemi1224** [comment]
WEEK 1- October 6th 2023
Having showed interest in the Erscilia Project, i joined the communication channel where i introduced myself to other outreachy applicant that are interested in contributing in Erscilia Open Source Initiative Project.  I join the google meet session hosted by @GemmaTuron, @DhanshreeA and @miquelduranfrigola where i was able to have better understanding of what the project entails and how to go about it. I also went to watch previous youtube videos by Erscilia to understand the vision and mission.

I opened a git issue

I then i went ahead to read the Erscilia book which contain details about the Erscilia model hub.

**Comment by aderemi1224** [comment]
**October 9th**
**Motivational Statement**
I am extremely interested in expressing my enthusiasm for contributing to the
aforementioned project. As a young woman with limited medical experience but a
strong passion for research, I am genuinely excited about the opportunity to
participate in this endeavor. The significance of biomedical research in enhancing
human health cannot be overstated, as it presents a remarkable opportunity to
revolutionize and improve the healthcare industry as a whole. I firmly believe that
my involvement in this project will allow me to make a meaningful impact by
actively contributing to the advancement of medical knowledge and ultimately
benefiting the broader community.
In the past few months, as I embarked on my career as a researcher, I had the
privilege of working on two health-related projects.
Firstly, I conducted an analysis on the sodium content of food from different
vendors and its correlation with hypertension. This involved testing the sodium
levels in various food samples and investigating the relationship between these
variables.
Additionally, I engaged in a breast cancer survival prediction study. Using a
comprehensive open-source dataset from Kaggle, I meticulously analyzed clinical
and genetic variables to assess the chances of survival. Furthermore, I developed a
predictive model that leveraged the analyzed data to accurately predict the
likelihood of survival for individuals affected by this disease.
I view this internship as a remarkable opportunity to collaborate with esteemed
researchers, learn from their expertise, and further my own growth and
development. Moreover, I am eager to contribute my skills and insights to the
advancement of the health sector.

**Comment by aderemi1224** [comment]
**Week 2 - October 11, 2023**
- I selected my model: [NCATS Rat Liver Microsomal Stability](https://github.com/ncats/ncats-adme). I chose this model for the project. because i see it as an opportunity to contribute to improving human health. The understanding of how drugs are metabolized and it's stability in the liver of a rat can help provide an insight on the behavior/impact in the human body. As rats are commonly used as a model organism for drug metabolism studies, with the goal of extrapolating the results on human as shown by this research [Characterization of rat and human liver microsomal cytochrome P-450 forms involved in nifedipine oxidation, a prototype for genetic polymorphism in oxidative drug metabolism.](https://www.sciencedirect.com/science/article/pii/S002192581989213X).
- I tried installing the model in my system but after 4 hours of running this code here is the output
-
(base) C:\Users\PC>cd C:\Users\PC\Documents\Project\Ersilia\ncats-adme

(base) C:\Users\PC\Documents\Project\Ersilia\ncats-adme>cd server

(base) C:\Users\PC\Documents\Project\Ersilia\ncats-adme\server>conda env create --prefix ./env -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: /
The forward slash keeps rotating.

**Comment by HellenNamulinda** [comment]
> **Week 2 - October 11, 2023**
> 
> * I selected my model: [NCATS Rat Liver Microsomal Stability](https://github.com/ncats/ncats-adme). I chose this model for the project. because i see it as an opportunity to contribute to improving human health. The understanding of how drugs are metabolized and it's stability in the liver of a rat can help provide an insight on the behavior/impact in the human body. As rats are commonly used as a model organism for drug metabolism studies, with the goal of extrapolating the results on human as shown by this research [Characterization of rat and human liver microsomal cytochrome P-450 forms involved in nifedipine oxidation, a prototype for genetic polymorphism in oxidative drug metabolism.](https://www.sciencedirect.com/science/article/pii/S002192581989213X).
> * I tried installing the model in my system but after 4 hours of running this code here is the output
> 
> `(base) C:\Users\PC>cd C:\Users\PC\Documents\Project\Ersilia\ncats-adme`
> 
> `(base) C:\Users\PC\Documents\Project\Ersilia\ncats-adme>cd server`
> 
> '(base) C:\Users\PC\Documents\Project\Ersilia\ncats-adme\server>conda env create --prefix ./env -f environment.yml` `Collecting package metadata (repodata.json): done` `Solving environment: /`
> 
> The forward slash keeps rotating

For the challenge you are facing, it would be better to share the steps and the commands you used(read from the [documentation on the repository](https://github.com/ncats/ncats-adme#admencats)). These will help to guide you better.

**Comment by aderemi1224** [comment]
Thank you so much @HellenNamulinda, here is the result of the model that i tested.
`{
"input": {

    "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
    "input": "CCCC",
    "text": "CCCC"

},
"output": {
    "mw": 58.123999999999995

}
}`

**Comment by aderemi1224** [comment]
Good morning @HellenNamulinda, please i have been  stucked here for almost a week now. 
`(base) C:\Users\adere\OneDrive\Documents\Project\Ersilia\ncats-adme\server>conda env create --prefix ./env -f environment.yml
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: - `

**Comment by DhanshreeA** [comment]
Hi @aderemi1224 couple of questions regarding your issue above:
The original repo does mention that it takes several minutes for the environment to be created since there are a lot of dependencies to be installed. The amount of time it takes for you specifically could depend on several factors such as your internet speed, and if any firewall is blocking conda from reaching its index servers. I suggest you try installing each of the conda dependencies individually using the channels mentioned within the environment.yml file, and then install the pip packages within the environment.yml file. Let us know how it goes.

**Comment by DhanshreeA** [comment]
I also recommend looking into literature survey for week three and posting your model suggestions here. All the best!

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
