### ISSUE TITLE
✍️ Contribution period: Tamandeep Singh

### ISSUE THREAD

**Issue by tamandeeps** [ersilia-os/ersilia#864]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by tamandeeps** [comment]
There is some issue running the simplest model, however I have successfully installed ersilia model hub. Trying to debug that and then will post results.

**Comment by tamandeeps** [comment]
While fetching the model 
<img width="443" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/51912faa-9016-4f42-81c6-469678afcfd5">
Docker is already installed in my system and I am successfully able to check docker version, wrong DEBUG field is being shown here

**Comment by tamandeeps** [comment]
I got to know about one issue with setting up Ersilia. The issue is mainly causing in India locations due to I guess specificallly jiofiber network connections. I was trying to serve the simplest model as a starting point but there was network connection error. ISP was blocking a URL: raw.githubusercontent.com and I solved this problem by using VPN but I need to look for some permanent solution for this. 
![image](https://github.com/ersilia-os/ersilia/assets/90107053/da162b99-0a7e-4dcd-a0d2-80b75925be57)

**Comment by joiboi08** [comment]
Hi @tamandeeps, for a more permanent solution I changed my DNS to Cloudfare DNS.
https://github.com/ersilia-os/ersilia/issues/832#issuecomment-1749097468

**Comment by DhanshreeA** [comment]
Hey @tamandeeps as @joiboi08 recommends, usually updating your DNS to Cloudflare or Google DNS is a simple workaround for this.

**Comment by DhanshreeA** [comment]
> While fetching the model <img alt="image" width="443" src="https://user-images.githubusercontent.com/90107053/273865699-51912faa-9016-4f42-81c6-469678afcfd5.png"> <img alt="image" width="358" src="https://user-images.githubusercontent.com/90107053/273866034-e3849cdd-e0bf-42e9-896e-106d9a71b35a.png">
> 
> Docker is already installed in my system and I am successfully able to check docker version, wrong DEBUG field is being shown here

Hi @tamandeeps just following up, any updates here? I see that you have docker installed but I would also recommend running the following command to verify if the installation works correctly (since this is what Ersilia uses as well to verify your docker installation)

```bash
docker run --platform <your-platform-here> --name my_hello_world hello-world
```
The docker platform that ersilia looks for are `linux/arm64` and `linux/amd64`. Could you confirm if your system is running either of these platforms, or which platform it is running?

**Comment by tamandeeps** [comment]
Hi @DhanshreeA 
<img width="773" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/11941faf-e46c-4229-a4e6-be8c3c25588d">
my system is running amd64

**Comment by tamandeeps** [comment]
My motivation statement to work for Ersilia

Hi all, I wouldn't bore you all by talking about my qualifications and degrees, but let me just describe what I was doing before with AI, so when I first started in this field, there were lot of interesting problems to solve in AI, mostly related to computer vision and NLP, I started working on YOLOv3 like social distancing detector and then working on transformers for pollution prediction, and then I started understanding how these recommendation systems work, like I am watching a reel in instagram and I couldn't get off from it for more than hour, it is making me keep watching reels by recommending best reels and one day it hit me what a useless using of ML is that, throwing all humanity to attention deficit order and tech companies making money out of it, then following I found out that how big tech companies are also working for deep fakes which I feel one of the scariest thing ever developed so all these intellectual knowledge is being used in such stuff, I feel like such powerful theories of ML AI is being discovered and where they are putting it, it's just not a good thing to do, it's like I am learning quantum physics and then indulge in making next gen nuclear weapons, we can do better than this. After that I started researching about orgs which does use AI for good of humankind, so I came across this org, I wanted to do some contributions which helped make this world a little better, before enrolling to outreachy, I knew about this org, I emailed to hello@ersilia.org also to become part of it, but I got response from Gemma that she was travelling, I couldn't find channel links also. But now as I am progressing to work for this org, it's quite exciting and I knew deep in my heart that biological problems do interest me, and now I have found the perfect intersection.

**Comment by tamandeeps** [comment]
I first chose the model smiles to IUPAC converted as it was based on transformers, I found it simple to start with as I have already worked with transformers before, I have one paper published: PM2.5 prediction using transformers,, but when I started going through the steps there were lot of issues with my conda which I encountered, I am attaching screenshots below. 
![image](https://github.com/ersilia-os/ersilia/assets/90107053/e61fc7f9-ec21-4733-a171-f31e7e61c215)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/3014c905-c399-41bf-ad38-2a2cc679be52)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/87f2f154-7fee-4589-82a6-6a1b1c59009f)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/fb4b4b00-3b5d-4a3e-b11c-1171e45c3fe2)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/b34773c6-735d-46bd-8b9d-b5ebfcd741d4)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/e7d633e7-01b1-4d7d-a5f3-3666f0874d5b)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/6cdcc173-4e04-4296-a68e-581fc22c0d22)
![image](https://github.com/ersilia-os/ersilia/assets/90107053/40f79297-da73-4904-8618-2eebfb6b2ec1)

**Comment by tamandeeps** [comment]
I think there is some issue going on with conda, I tried running the first model given : ncats-adme and while creating the environment as mentioned in readme file `conda env create --prefix ./env -f environment.yml`
<img width="856" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/bd368473-669d-4c96-895b-aa85e9379484">
Issue is with the conda, I tried uninstalling and installed again lot of times but the error persists. 
<img width="850" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/27c2da6f-4f0c-45ea-b9fd-1a6fb67b5f07">

**Comment by tamandeeps** [comment]
Hi everyone, after trying so many times with conda, I was able to resolve issues with my conda, I think my WSL got corrupted, I had to reinstall everything. I am able to successfully run the model smiles to IUPAC
<img width="674" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/0bb052a1-ed51-41fe-952e-c79ca7f2bf6b">
<img width="671" alt="image" src="https://github.com/ersilia-os/ersilia/assets/90107053/d1a288f3-c12f-47b1-b2e1-c5627463c310">

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
