### ISSUE TITLE
✍️ Contribution period: <Kellen_Kinya> 

### ISSUE THREAD

**Issue by kellenkinya** [ersilia-os/ersilia#867]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [x] Suggest a new model and document it (1)
- [x] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by kellenkinya** [comment]
**Task 1:  ** Joined the community and introduced myself to my peers and the mentors. 
**Task 2 : ** Opened a github issue
**Task 3 : ** My operating system is windows 10 so I had to first install WSL in PowerShell running  as an administrator , then downloaded and installed ubuntu on windows, the next step was to install all the third part prerequisites needed for the ersilia model to run found in this  [link](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation) .

**Comment by kellenkinya** [comment]
**Task 3:**  Able to download and install the models locally through the fetch command. Once this step is done the  model is ready for use. then I served the model and made both individual and multiple predictions.

**Comment by kellenkinya** [comment]
**What I learnt on the predictions:**  The higher the score, the more synthetically accessible the molecule is predicted to be.  [This journal] (https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-1-8) by PubMed central gave me some more information on the SA scores.

**Comment by kellenkinya** [comment]
Unable to  make predictions today, I was running into **object of NoneType has no len** .
As discussed in the slack channel [(https://ersilia-outreachy-w23.slack.com/archives/C05V51PS6FJ/p1696451488224489)]
**Steps I took to solve**

 Uninstalled conda, switched from python 3.7 to python 3.10.

  Removed the initial ersilia directory I had cloned since I had modified the code in the repo
 `rm -rf ersilia` followed by `git` clone `https://github.com/ersilia-os/ersilia.git`
 

 Created a new conda  environment and activated it.
  `conda create -n ersilia python=3.10
   conda activate ersilia`

**Comment by kellenkinya** [comment]
The adjustments worked and I  was able to
1. Check all the available models in the website `ersilia catalog`
2. Fetch different models and  installed them locally using the **fetch command**  using the **slug** or **ersilia identifier**
3. Serve the model
4. Make several predictions by either running single models or multiple models in batch mode.
One of the predictions :
<img width="895" alt="2023-10-12 (3)" src="https://github.com/ersilia-os/ersilia/assets/124606031/a286e0af-19be-483a-b24f-74e988cf9c50">

**Comment by kellenkinya** [comment]
**Why I want to work at ersilia**
After getting an approval than my initial outreachy application as been approved and the next step was to find a project or project that I am interested in. I had to take sometime to go through the list, read what all the organizations stand for and what they do. In the it was just ersilia for me. A non-profit organization with a mission to **equip laboratories in Low and Middle Income Countries with state of the art AI/ML tools for infectious and neglected disease research**. Getting a chance to intern at ersilia gives me an opportunity to do good for the humanity, that what I do or assist in  as an impact in the world, it helps people, especially from lower income countries, I come from a lower middle  income income country, Kenya and I hope in the long run ersilia grows and spreads to Kenya.

I graduated last year with a degree in Actuarial Science , then ventured into machine learning and data science, most of the projects I have worked on in ML are about analyzing sales, or revenues or prices of items, but to see real application of ML in biomedical and experimental research transcends it all and all I can think of is finally I found my purpose and my path. I  want to apply my data science skills in medical research, intern, volunteer or work on medical research institute, disease and discovery  centers, do open source contributions in disease and drugs research and one day when my time comes to leave this world  let them that remain and know me say **She gave her all in disease and drugs research to help the people** and that's how we make living more beautiful and help reduce peoples pain.

That's why I would like to work with ersilia, A opportunity for the internship will:

- hhhhhhhhhhh

**Comment by kellenkinya** [comment]
**Motivation to work in ersilia should have:**

- **Current Skills**
-**Your reasons to work in ersilia project**
-**How this would advance my career**
-**What are my plans during and after the internship**

**Comment by kellenkinya** [comment]
# Week 2 tasks:

**Comment by kellenkinya** [comment]
# Week 2 tasks
## Task 1: Select a model

**Comment by kellenkinya** [comment]
## Was running into a timeout error 
```
 File "/home/kellen/ncats-adme/server/env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.


failed
```

**Comment by kellenkinya** [comment]
The error was caused by slow internet connection 
### What I did
Closed the terminal, gave it some time and retried the steps again

**Comment by carcablop** [comment]
Hi @kellenkinya 
Welcome to Ersilia!. 
Thank you very much for all the effort. Regarding the error when you try to get the predictions, we are working on solving the problem, we have found that the isaura package is causing conflict with ersilia, so please do not install it.

**Comment by carcablop** [comment]
> The adjustments worked and I was able to
> 
>     1. Check all the available models in the website `ersilia catalog`
> 
>     2. Fetch different models and  installed them locally using the **fetch command**  using the **slug** or **ersilia identifier**
> 
>     3. Serve the model
> 
>     4. Make several predictions by either running single models or multiple models in batch mode.
> 
> 
> **One of the predictions :** <img alt="2023-10-12 (4)" width="100" src="https://user-images.githubusercontent.com/124606031/274662238-d9a10c25-2223-42c1-b8a0-7659b32245c5.png">

Please, here you must be within the created environment of 'ersilia'. In the shared image you are working on the base conda environment, not on the ersilia environment that you had created in the previous steps.
Follow the steps to run a basic ersilia model, do not attach images, please attach only the output logs when you run a model like this, all within the created ersilia environment:
ersilia -v fetch eos3b5e > my.log 2>&1
ersilia -v serve eos3b5e
ersilia -v run -i "CCC" > my.log 2>&1

Please make sure you execute the steps correctly before continuing with the following tasks.
Thank you

**Comment by kellenkinya** [comment]
Thank you for the corrections.

**Comment by kellenkinya** [comment]
` my.log 2>&1`

**Comment by DhanshreeA** [comment]
> **What I learnt on the predictions:** The higher the score, the more synthetically accessible the molecule is predicted to be. [This journal](https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-1-8) by PubMed central gave me some more information on the SA scores.

Hi @kellenkinya normally it is a good practice to mention the model you've used. I'm assuming this is the mode `eos2r5a` ([Retrosynthetic accessibility score](https://github.com/ersilia-os/eos2r5a)

**Comment by DhanshreeA** [comment]
> ## Was running into a timeout error when trying to run the application on ADMW@NCATS model.
> 
> ```
>  File "/home/kellen/ncats-adme/server/env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> 
> 
> failed
> ```

@kellenkinya Did your restarting of the terminal work, or is this still and issue? Quick piece of advice, it's often helpful to share the entire stack trace for better insights into the error.

**Comment by kellenkinya** [comment]
> > **What I learnt on the predictions:** The higher the score, the more synthetically accessible the molecule is predicted to be. [This journal](https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-1-8) by PubMed central gave me some more information on the SA scores.
> 
> Hi @kellenkinya normally it is a good practice to mention the model you've used. I'm assuming this is the mode `eos2r5a` ([Retrosynthetic accessibility score](https://github.com/ersilia-os/eos2r5a)

Yes it was

**Comment by DhanshreeA** [comment]
> > ## Was running into a timeout error when trying to run the application on ADMW@NCATS model.
> > ```
> >  File "/home/kellen/ncats-adme/server/env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
> >     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> > pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> > 
> > 
> > failed
> > ```
> 
> @kellenkinya Did your restarting of the terminal work, or is this still and issue? Quick piece of advice, it's often helpful to share the entire stack trace for better insights into the error.

Hi @kellenkinya just following up, any updates here?

**Comment by kellenkinya** [comment]
Sorry for a late update.
1. First I cloned the repo
`git clone --recursive https://github.com/ncats/ncats-adme.git`
2. Then I was able to set up my environment by running 
`conda env create --prefix ./env -f environment.yml` and then typed 
`pip install typed-argument-parser'
3. The next step was to change the working environment  into the server directory which is inside the  ADME_RLM repo then type `python app.py` to install the model into  the server.

**Comment by kellenkinya** [comment]
The 3rd step is taking sometime on my end , It ran for many hours yesterday and I had some power issues so it stopped and I have to run it again today, I am hoping to have managed this step before the day end and made predictions

**Comment by kellenkinya** [comment]
`(C:\Users\Admin\ncats-adme\server\env) C:\Users\Admin\ncats-adme\server>python app.py
Loading RLM graph convolutional neural network model
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Finished loading RLM model files
Loading PAMPA graph convolutional neural network model
Model File Exists Locally
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Finished loading PAMPA 7.4 models
Loading PAMPA graph convolutional neural network model
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Finished loading PAMPA 5.0 models
Loading PAMPA BBB graph convolutional neural network model
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Finished loading PAMPA BBB models
Loading Solubility graph convolutional neural network model
Model File Exists Locally
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Finished loading Solubility models
Loading human liver cytosol stability random forest models
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 75.50it/s]
Finished loading human liver cytosol stability models
Loading CYP450 random forest models
100%|██████████████████████████████████████████████████████████████████████████████████| 64/64 [00:02<00:00, 28.23it/s]
cyp2c9_subs-model_39: 100%|███████████████████████████████████████████████████████| 18.6M/18.6M [00:00<00:00, 2.16GB/s]
cyp2c9_subs-model_40: 100%|████████████████████████████████████████████████████████| 18.3M/18.3M [00:00<00:00, 641MB/s]
cyp2c9_subs-model_41: 100%|███████████████████████████████████████████████████████| 18.6M/18.6M [00:00<00:00, 2.44GB/s]
cyp2c9_subs-model_42: 100%|████████████████████████████████████████████████████████| 18.3M/18.3M [00:00<00:00, 675MB/s]
cyp2c9_subs-model_43: 100%|███████████████████████████████████████████████████████| 18.4M/18.4M [00:00<00:00, 2.41GB/s]
 69%|████████████████████████████████████████████████████████▍                         | 44/64 [08:42<03:57, 11.88s/it]
 17%|█████████████▊                                                                     | 1/6 [08:44<43:44, 524.98s/it]
Traceback (most recent call last):
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 710, in _error_catcher
    yield
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 835, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(9322106 bytes read, 10090047 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 936, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 907, in read
    data = self._raw_read(amt)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 835, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Admin\ncats-adme\server\env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\urllib3\response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(9322106 bytes read, 10090047 more expected)', IncompleteRead(9322106 bytes read, 10090047 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 27, in <module>
    from predictors.cyp450.cyp450_predictor import CYP450Predictor
  File "C:\Users\Admin\ncats-adme\server\predictors\cyp450\__init__.py", line 87, in <module>
    cyp450_models_dict = load_models()
  File "C:\Users\Admin\ncats-adme\server\predictors\cyp450\__init__.py", line 81, in load_models
    cyp450_models_dict[model_name][f'model_{model_number}'] = download_file(base_url, model_name, model_number, cyp450_models_dict)
  File "C:\Users\Admin\ncats-adme\server\predictors\cyp450\__init__.py", line 24, in download_file
    cyp450_rf_pkl_file_request = requests.get(cyp450_rf_pkl_url)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Users\Admin\ncats-adme\server\env\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(9322106 bytes read, 10090047 more expected)', IncompleteRead(9322106 bytes read, 10090047 more expected))`

**Comment by kellenkinya** [comment]
After some research I found at the error might be due to

- Network issue: the script is unable to complete the download.
I have closed the terminal and checked my connections, let me now retry `python app.py` and will document how it goes

**Comment by kellenkinya** [comment]
After running python app.py overnight and still not able to install all the models into the server I decided to comment on **[CYP450 isozymes - CYP2C9, CYP2D6, CYP3A4](https://opendata.ncats.nih.gov/public/adme/models/current/static/cyp450/)**
models which were the ones taking long to open.
**Steps I took**
- Changed the working directory to ncat_adme then into the server
- Opened app.py `notepad app.py`  and commented on `from predictors `
-

**Comment by kellenkinya** [comment]
> I Encountered the above error, After some research I found at the error might be due to
> 
> * Network issue: the script is unable to complete the download.
>   I have closed the terminal and checked my connections, let me now retry `python app.py` and will document how it goes.
>   Any other help on how to solve is highly appreciated.

It worked

**Comment by kellenkinya** [comment]
# Running ADME@NCATS
## WHY CHOOSE ADME@NCATS
## STEPS

1. Clone the github repository contain the codes for the application and the model 
```
git clone --recursive https://github.com/ncats/ncats-adme.git
```
2. Change the working directory

**Comment by kellenkinya** [comment]
### Making Predictions
After all the models have been loaded into ncats server to assess them I opened my chrome browser and typed `http://127.0.0.1:5000/`

<img width="960" alt="2023-10-19" src="https://github.com/ersilia-os/ersilia/assets/124606031/0b948ea9-d4b8-4b16-bd7a-93e507a6259e">

**Comment by kellenkinya** [comment]
I then navigated to predict and chose PAMPA pH 7.4  and PAMBA pH 5 models. Then uploaded the Essential Medicine List csv  file which I had previously downloaded from ersilia repo and the processed the file.

<img width="960" alt="2023-10-19 (10)" src="https://github.com/ersilia-os/ersilia/assets/124606031/2e093405-ea99-4315-83f4-8748c10cd753">

**Comment by kellenkinya** [comment]
### 
<img width="960" alt="2023-10-19 (2)" src="https://github.com/ersilia-os/ersilia/assets/124606031/997c29c0-1326-4c9a-a003-970c45ffa701">
PAMBA pH 5 model prediction

**Comment by kellenkinya** [comment]
### Compare results with ersilia models.
ON https://ersilia.io/model-hub, filtered using permeabilty and found **Parallel Artificial Membrane Permeability Assay (PAMPA) 7**

**Comment by kellenkinya** [comment]
### Compare results with ersilia models.
ON https://ersilia.io/model-hub, filtered using permeabilty and found **Parallel Artificial Membrane Permeability Assay (PAMPA) 7** 

1. Fetch the model  using EOS model ID
```
 ersilia -v fetch eos9tyg > my.log 2>&1
```
2. Serve the model 
``` 
ersilia -v serve  eos9tyg

**Comment by kellenkinya** [comment]
### Predictions

**Comment by kellenkinya** [comment]
And for  **Rat Liver Microsomal Stability**
1. Fetch the model  using EOS model ID
```
 ersilia -v fetch eos5505
```
2. Serve the model 
``` 
ersilia -v serve  eos5505
```
And the output was
```
 Serving model eos5505: ncats-rlm

   URL: http://0.0.0.0:41705
   PID: -1
   SRV: pulled_docker

👉 To run model:
   - run

   These APIs are also valid:
   - predict

💁 Information:
   - info

**Comment by kellenkinya** [comment]
```
(ersilia) kellen@DESKTOP-EQ55Q8H:~/ersilia$ ersilia -v api predict -i /mnt/c/Users/Admin/Downloads/eml_canonical.csv -o output_2.csv
21:44:11 | DEBUG    | Getting session from /home/kellen/eos/session.json
21:44:11 | DEBUG    | Getting session from /home/kellen/eos/session.json
21:44:11 | WARNING  | Lake manager 'isaura' is not installed! We strongly recommend installing it to store calculations persistently
21:44:11 | ERROR    | Isaura is not installed! Calculations will be done without storing and reading from the lake, unfortunately.
21:44:14 | DEBUG    | Is fetched: True
21:44:14 | DEBUG    | Schema available in /home/kellen/eos/dest/eos5505/api_schema.json
21:44:14 | DEBUG    | Setting AutoService for eos5505
21:44:14 | INFO     | Service class provided
21:44:14 | DEBUG    | Using port 47395
21:44:14 | DEBUG    | Starting Docker Daemon service
21:44:14 | DEBUG    | Creating temporary folder /tmp/ersilia-fozp9pgv and mounting as volume in container
21:44:14 | DEBUG    | Image ersiliaos/eos5505:latest is available locally
21:44:14 | DEBUG    | Using port 50889
21:44:14 | DEBUG    | Starting Docker Daemon service
21:44:14 | DEBUG    | Creating temporary folder /tmp/ersilia-53hg2jig and mounting as volume in container
21:44:14 | DEBUG    | Reading card from eos5505
21:44:14 | DEBUG    | Trying to get metadata from: /home/kellen/eos/dest/eos5505
21:44:16 | DEBUG    | Reading shape from eos5505
21:44:16 | DEBUG    | Trying to get metadata from: /home/kellen/eos/dest/eos5505
21:44:17 | DEBUG    | Input Shape: Single
21:44:17 | DEBUG    | Input type is: compound
21:44:17 | DEBUG    | Input shape is: Single
21:44:17 | DEBUG    | Importing module: .types.compound
21:44:17 | DEBUG    | Checking RDKIT and other requirements necessary for compound inputs
21:44:17 | DEBUG    | InputShapeSingle shape: Single
21:44:17 | DEBUG    | Stopping sniffer for finding delimiter
21:44:17 | DEBUG    | Expected number: 1
21:44:17 | DEBUG    | Entity is list: False
21:44:17 | DEBUG    | Resolving columns
21:44:17 | DEBUG    | Stopping sniffer for resolving column types
21:44:17 | DEBUG    | Done with sniffing the file
21:44:17 | DEBUG    | Input: {1: 100, 2: 100}
21:44:17 | DEBUG    | Key: {}
21:44:17 | DEBUG    | Input: [1]
21:44:17 | DEBUG    | Candidate header is ['drugs', 'smiles', 'can_smiles']
21:44:17 | DEBUG    | Matching for input is [1]
21:44:17 | DEBUG    | Has header True
21:44:17 | DEBUG    | Schema {'input': [1], 'key': None}
21:44:17 | DEBUG    | Standardizing input single
21:44:17 | DEBUG    | Writing standardized input to /tmp/ersilia-7i7ahwyp/standard_input_file.csv
21:44:17 | DEBUG    | Reading standard file from /tmp/ersilia-7i7ahwyp/standard_input_file.csv
21:44:17 | DEBUG    | File has 443 lines
21:44:17 | DEBUG    | No file splitting necessary!
21:44:17 | DEBUG    | Reading card from eos5505
21:44:17 | DEBUG    | Trying to get metadata from: /home/kellen/eos/dest/eos5505
21:44:19 | DEBUG    | Reading shape from eos5505
21:44:19 | DEBUG    | Trying to get metadata from: /home/kellen/eos/dest/eos5505
21:44:20 | DEBUG    | Input Shape: Single
21:44:20 | DEBUG    | Input type is: compound
21:44:20 | DEBUG    | Input shape is: Single
21:44:20 | DEBUG    | Importing module: .types.compound
21:44:20 | DEBUG    | Checking RDKIT and other requirements necessary for compound inputs
21:44:20 | DEBUG    | InputShapeSingle shape: Single
21:44:20 | DEBUG    | API eos5505:predict initialized at URL http://0.0.0.0:41705
21:44:20 | DEBUG    | Schema available in /home/kellen/eos/dest/eos5505/api_schema.json
21:44:20 | DEBUG    | Posting to predict
21:44:20 | DEBUG    | Batch size 100
21:44:20 | DEBUG    | Stopping sniffer for finding delimiter
21:44:20 | DEBUG    | Expected number: 1
21:44:20 | DEBUG    | Entity is list: False
21:44:20 | DEBUG    | Resolving columns
21:44:20 | DEBUG    | Stopping sniffer for resolving column types
21:44:20 | DEBUG    | Done with sniffing the file
21:44:20 | DEBUG    | Input: {1: 100, 2: 100}
21:44:20 | DEBUG    | Key: {}
21:44:20 | DEBUG    | Input: [1]
21:44:20 | DEBUG    | Candidate header is ['drugs', 'smiles', 'can_smiles']
21:44:20 | DEBUG    | Matching for input is [1]
21:44:20 | DEBUG    | Has header True
21:44:20 | DEBUG    | Schema {'input': [1], 'key': None}
21:44:20 | DEBUG    | Standardizing input single
21:44:20 | DEBUG    | Writing standardized input to /tmp/ersilia-6x2vc0s_/standard_input_file.csv
21:44:20 | DEBUG    | Reading standard file from /tmp/ersilia-6x2vc0s_/standard_input_file.csv
21:44:21 | DEBUG    | Schema available in /home/kellen/eos/dest/eos5505/api_schema.json
21:44:29 | DEBUG    | Status code: 200
21:44:29 | DEBUG    | Schema available in /home/kellen/eos/dest/eos5505/api_schema.json
21:44:33 | DEBUG    | Status code: 200
21:44:38 | DEBUG    | Status code: 200
21:44:43 | DEBUG    | Status code: 200
21:44:48 | DEBUG    | Status code: 200
21:44:48 | DEBUG    | Done with unique posting
21:44:51 | DEBUG    | Data: outcome
21:44:51 | DEBUG    | Values: [0.049]
21:44:51 | DEBUG    | Datatype: numeric_array
output_2.csv
```

**Comment by kellenkinya** [comment]
## Week 3 Rundown

**Comment by kellenkinya** [comment]
### Week 3 

# Model 1:

**Comment by kellenkinya** [comment]
[](https://www.mdpi.com/1420-3049/28/3/1490)

**Comment by kellenkinya** [comment]
https://github.com/smu-tao-group/ADMET_XGBoost

**Comment by kellenkinya** [comment]
https://github.com/DrugLT/ImDrug

**Comment by kellenkinya** [comment]
https://github.com/XuanLin1991/DeepGS

**Comment by kellenkinya** [comment]
https://github.com/mjwen/bondnet

**Comment by kellenkinya** [comment]
https://github.com/3dem/model-angelo

**Comment by kellenkinya** [comment]
https://github.com/dockstring/dockstring

**Comment by kellenkinya** [comment]
https://github.com/kexinhuang12345/DeepPurpose

**Comment by kellenkinya** [comment]
https://github.com/PaddlePaddle/PaddleHelix

**Comment by kellenkinya** [comment]
https://github.com/mattragoza/liGAN

**Comment by kellenkinya** [comment]
https://github.com/dmamur/elembert

**Comment by kellenkinya** [comment]
https://github.com/fouticus/pipgcn

**Comment by kellenkinya** [comment]
https://github.com/DSPsleeporg/smiles-transformer

**Comment by kellenkinya** [comment]
https://github.com/Lambard-ML-Team/SMILES-X

**Comment by kellenkinya** [comment]
https://github.com/jbr-ai-labs/lipophilicity-prediction

**Comment by kellenkinya** [comment]
https://github.com/VEK239/StructGNN-lipophilicity

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
