### ISSUE TITLE
Hello @aderemi1224,

### ISSUE THREAD

**Issue by aderemi1224** [ersilia-os/ersilia#869]
Hello @aderemi1224,
You seem to have a Windows machine.

Did you install ersilia following the recommended steps for Windows users? [Including using WSL](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation#1.-install-on-windows)? 
It would be better that after testing the simple model, you share some of your results here.

_Originally posted by @HellenNamulinda in https://github.com/ersilia-os/ersilia/issues/855#issuecomment-1759817910_

**Comment by aderemi1224** [comment]
Thank you so much @HellenNamulinda, here is the result of the model that i tested.
`{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}`

**Comment by DhanshreeA** [comment]
Hi @aderemi1224, it's best to post such discussions in your original contribution issue. I'm closing this one.
