### ISSUE TITLE
✍️ Contribution period: <Ritu Gothwal> 

### ISSUE THREAD

**Issue by gothwalritu** [ersilia-os/ersilia#873]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by gothwalritu** [comment]
**My Motivation to join Ersilia**

I have a doctoral degree in Environmental Engineering, I developed mathematical predictive models for the transport of antibiotic and antibiotic resistance in aquatic environment. I am from India and pursued my doctoral degree in India as well. After my doctoral degree I got married and moved to another country. So, I could not work for almost five years due to work permit issue, covid and maternity break.  Recently, I did a certification in data analytics and visualization and started my job search in the Industry. During an interaction with an industry professional I  learnt about the Outreachy program. I applied for it and I was approved for the initial contribution phase. I was asked to join a project and after research I got interested in "Ersilia" project as this one was inline with my knowledge and aspirations. I have a good interdisciplinary knowledge in predictive modelling, applied statistics, programming, biotechnology, chemistry, environmental sciences etc, as I have applied all that in my research. I want to work in the area where  research, data science, antibiotic resistance and chemistry meets. 

I have worked with International Water Research Institute, which is a non-profit research for development organization and manages land and water sector in under developed and developing countries. I know the joy and challenges to contribute in such research projects and now, I want to be part of this work so that as I can utilize my skills, knowledge and experience in some meaningful way to give back to society and humanity.

**Comment by gothwalritu** [comment]
**Week 1 progress: Task Completed** 
- Joined Ersilia Community and introduced myself to the mentors, volunteers and peers.
- As mentioned in the instruction I opened a github issue.
- Installed all the prerequisites and Erisila Model Hub as mentioned in the Ersilia book.
- Written a motivation statement to work at Ersilia.
-  Familiarized myself with the structure of repository on GitHub. 
- Read the code of conduct.

**Comment by gothwalritu** [comment]
Week 2 progress: Task completed

- After the installation of model hub, I learnt the about the model usage.
- Explored the available models and their structure for its identification.
- gone through the case example to run predictions of "Retrosynthetic accessibility score" using AI/ML model.
- Learnt about how to fetch the model, to get the model info, to serve the model and make predictions.
- Explored all the models from the suggested list to chose one.

**Comment by gothwalritu** [comment]
**Choosing model "metabokiller", identifier: eos1579.**

I am choosing this model because I am interested in cancer research. The cancer is spreading in India like a pandemic and every other household having a family member who is suffering from cancer. Finding its solution through research is crucial to tackle this issue.

**Comment by gothwalritu** [comment]
**### MetaBokiller** 

Model Setup

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
