### ISSUE TITLE
✍️ Contribution period: <Arineitwe Fred> 

### ISSUE THREAD

**Issue by arinetf3321** [ersilia-os/ersilia#878]
### Week 1 - Get to know the community

- [ ] Join the communication channels
- [ ] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [ ] Select a model from the suggested list
- [ ] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by arinetf3321** [comment]
Motivation Statement

Dear Outreachy-Ersilia,

I am writing to express my deep-seated passion and unwavering commitment to contribute my skills and expertise to the Ersilia Model Hub Project titled Improvement of the Ersilia Model Hub, a FOSS platform of AI/ML models for biomedical research.

Ersilia Model Hub Project, like any ambitious project, offers an opportunity to explore, create, and bring new ideas to life. I firmly believe that it is in these endeavors that I find the true essence of human potential. My motivation for working on Ersilia Model Hub Project is rooted in the following principles:

Enhancing connections. Just as the threads of Ersilia Model Hub are woven together to create a complex and vibrant system, I am eager to collaborate with a diverse team of individuals, each bringing their unique talents to build a harmonious AI system.

Enriching Innovation. Ersilia Model Hub encourages innovation, and I see it as a canvas for fresh ideas, where I can contribute my knowledge and creativity to make this project an exemplar of Artificial Intelligence / Machine Learning (AI/ML) model in our ever-evolving world of infectious and neglected diseases.

Amplifying Impact. The interconnectedness represented by Ersilia Model Hub holds the power to bring about meaningful change. I am dedicated to ensuring that the project resonates with others and fosters a sense of unity and shared purpose.

Advancing Endurance. Much like the intricate web of threads that compose Ersilia Model Hub, I am committed to persevering through challenges and setbacks. I see each obstacle as an opportunity to learn and grow, ultimately leading to a more refined and resilient project.

Maximizing Inspiration. I aspire to inspire not only myself but also others by my unwavering dedication to Ersilia Model Hub. I believe that by setting an example of commitment and determination, I can encourage others to embark on similar journeys of exploration and creation.

I am excited by the vision of Ersilia Model Hub, and I am ready to invest my time, energy, and expertise to help bring this project to fruition. The prospect of contributing to a project that embodies the beauty of  infectious and neglected diseases is not only motivating but also a source of great personal fulfillment.

Thank you for considering my application to work on Ersilia Model Hub Project entitled Improvement of the Ersilia Model Hub, a FOSS platform of AI/ML models for biomedical research. I am eager to be a part of the team that will make this vision a reality and look forward to discussing how I can contribute further.

Sincerely,

Arineitwe Fred.

**Comment by arinetf3321** [comment]
First Contribution,
Setting up Ersilia Hub Model and testing the simplest model for molecular weight (mw) of chemical compound.

Setting up Platform to run Ersilia Model Hub:

- Installing ubuntu 22.0 on my computer.
- Installing gcc compiler using sudo apt install build-essential.
- Installing Python and Conda using the sequence of steps.
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh

- Installing Git and GitHub CLI using conda install gh -c conda-forge.

- Authenticating installed system with github using gh auth login.
- Installing Git Large File Storage(LFS) using conda install git-lfs -c conda-forge.
- Activation of of LFS using git-lfs install. 
- Installation of Isaura data lake using:
conda activate ersilia
python -m pip install isaura==0.1
- Installation of the Docker
- Installation of the Ersilia using:
conda create -n ersilia python=3.7
conda activate ersilia

- Installation of python package using:
git clone https://github.com/ersilia-os/ersilia.git
cd ersilia
pip install -e .
After successful execution of the above steps, there followed testing of the Ersilia model-eos3b5e.

Testing the Ersilia Hub Model-eos3b5e was done using the following steps:
ersilia -v fetch eos3b5e
ersilia serve eos3b5e
ersilia -v api run -i "CCCC"
The steps were a success
![result-ersilia-model-testing](https://github.com/ersilia-os/ersilia/assets/124032819/8ff17f1a-57e8-44a3-9f2c-ed20f4d9e15c)
 and below was the result
Result:
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}
Where
"input": This section contains the input information for the query:

"key": This is a unique identifier or reference to a specific molecular structure, identified by the provided key "IJDNQMDRQITEOD-UHFFFAOYSA-N."
"input" and "text" both have the value "CCCC," represent a chemical compound, that is a molecular formula.
"output": This section contains the result or output of running the model:

"mw": This stands for "molecular weight." The value "58.123999999999995" represents the calculated molecular weight of the chemical compound with the formula "CCCC."
The molecular weight is a fundamental property in chemistry, representing the sum of the atomic weights of all the atoms in a molecule. In this case, the Ersilia hub model has calculated the molecular weight for the given chemical compound, which is approximately 58.124 units.

This information can be valuable in various chemical and scientific applications, such as drug discovery, chemical analysis, and more, as it provides insights into the mass of the molecule and its properties.

Thank you..

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
