### ISSUE TITLE
🐛 Bug: eos3cf4 not fetching correctly (also breaks zairachem default config)

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/ersilia#879]
### Describe the bug.

Upon a fresh install of zairachem, this eos3cf4 model does not fetch correctly (error log attached), which breaks zairachem.
[eos3cf4_log.txt](https://github.com/ersilia-os/eos3cf4/files/13030322/eos3cf4_log.txt)

The error is consistent across three different machines (2 CentOS and 1 Ubuntu).
I've tried with and without Isaura and docker installed as well as on different versions of the ersilia model hub (v0.1.1, v0.1.24, v0.1.27) and the result is the same.

I have been able to clone a previous copy of the model from the start of 2023 and then the latest ersilia model hub version can still serve it and run predictions.

I opened an issue on the model repo itself but perhaps this is the better forum.

### Describe the steps to reproduce the behavior

1. ersilia fetch eos3cf4

### Expected behavior.

Model fetches without error and can subsequently be served.

### Operating environment

Ubuntu 20.04.6 LTS / CentOS Stream 7

**Comment by DhanshreeA** [comment]
Originally posted here: https://github.com/ersilia-os/eos3cf4/issues/7 by @JHlozek 

I can fetch it successfully through Docker (haven't tried without Docker so far, or running predictions for that matter). @JHlozek I might be missing something here, but can you help me understand what do you mean that it breaks zairachem?

**Comment by JHlozek** [comment]
Thanks @DhanshreeA

This model is one of the set of 5 descriptor models used in the default install of zairachem, so I just mean that when eos3cf4 breaks, then zairachem breaks with it.

I'm not sure what's wrong then because I can fetch other models without issue. :/
I wonder if it is something more specific to the ersilia install within the zairachem installation process.

**Comment by GemmaTuron** [comment]
Hello @JHlozek,

Did you look into the log file? I see this line that seems like you might have messed up with some cached file:
```
Traceback (most recent call last):
  File "/home/Jason/anaconda3/envs/eos3cf4/lib/python3.8/site-packages/molfeat/store/loader.py", line 100, in _load_or_raise
    artifact_dir = store.download(modelcard, download_path, **kwargs)
  File "/home/Jason/anaconda3/envs/eos3cf4/lib/python3.8/site-packages/molfeat/store/modelstore.py", line 239, in download
    raise ModelStoreError(
molfeat.store.modelstore.ModelStoreError: The destination artifact at /home/Jason/.cache/molfeat/ChemGPT-4.7M/model.save has a different sha256sum (6d6bcb252f3d2f0919967d235b03ae27f95fc43bdd20202ae580c0db7195ec8f) than the Remote artifact sha256sum (e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855). The destination artifact has been removed !
```
maybe an incomplete fetching created that?

**Comment by JHlozek** [comment]
Hi @GemmaTuron

After some more digging into molfeat, the problem seems to be in that library rather than with the model hub.

I could reproduce the error in a separate environment using only installed molfeat code/functions to fetch ChemGPT (attached).
![molfeat_chemgpt](https://github.com/ersilia-os/ersilia/assets/89945519/5ec47afb-f008-478f-aa1d-76622b9bbe6c)

It didn't matter if the cache was cleared or not.
I'll open an issue on the molfeat repository tomorrow for some insight.

**Comment by GemmaTuron** [comment]
I've tried different versions of MolFeat with the same error (and different models as well). If we go lower than 0.9, then we have compatibility issues with Pydantic and other packages that will take time to debg
I've opened an issue in the molfeat repo to see if they can provide some insight

**Comment by JHlozek** [comment]
Great! I saw that there was a similar issue opened here that I added to yesterday: https://github.com/datamol-io/molfeat/issues/84

Hopefully they'll be able to look into it and respond soon.

**Comment by JHlozek** [comment]
The molfeat guys have looked into the issue and pushed changes that fix this bug (https://github.com/datamol-io/molfeat/issues/84#issuecomment-1806450177).

I'm going to close this issue here.

**Comment by GemmaTuron** [comment]
Fantastic thanks for the update @JHlozek !
