### ISSUE TITLE
Create a writing style guidelines for ersilia

### ISSUE THREAD

**Issue by sayantani11** [ersilia-os/ersilia#88]
**What is your feature request?**
A writing style guide that will have every document follow a standard style.

**Is your feature request related to a problem?**
Ersilia deals a with a lot of documentation, keeping that in mind it will be great if we introduce a writing style guideline. In that way we can maintain a standard format for every document. This will also help when we have new contributors in the future.

**Comment by sayantani11** [comment]
I would like to work on this issue!

**Comment by GemmaTuron** [comment]
Hi @sayantani11,

I have assigned this issue to you, but before continuing working on it, check the new guidelines in the Slack channel and follow them! thanks

**Comment by camus60** [comment]
@GemmaTuron @sayantani11 I would like to contribute to this issue

**Comment by GemmaTuron** [comment]
Hi @camus60 

Thanks for your interest, to make contributions more ordered some issues will for the moment only be assigned to one person! Then we will ask input from other interested applicants.
I see you already have a github issue with the tasks, could you go over there and start working in some of these?
Thanks!

**Comment by Dapper50** [comment]
Hi @GemmaTuron, Please i would love to work on this issue.

**Comment by miquelduranfrigola** [comment]
I am closing this issue and I suggest that we all move to the fantastic issue #177 opened by @sayantani11.
