### ISSUE TITLE
✍️ Contribution period: Tsion Zeleke

### ISSUE THREAD

**Issue by TsionZerihun** [ersilia-os/ersilia#880]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [x] Run predictions for the EML
- [x] Compare results with the Ersilia Model Hub implementation!
- [x] Install and run Docker!

### Week 3 - Propose new models

- [x] Suggest a new model and document it (1)
- [x] Suggest a new model and document it (2)
- [x] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by TsionZerihun** [comment]
# Task 1-3
## Install  pre-requisite && ersilia :heavy_check_mark:
- *output*
```
@DESKTOP-92JJ0KD:~$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

@DESKTOP-92JJ0KD:~$ git version
git version 2.17.1

DESKTOP-92JJ0KD:~$ git-lfs install
Git LFS initialized.
@DESKTOP-92JJ0KD:~$ git lfs --version
git-lfs/3.4.0 (GitHub; linux amd64; go 1.20.6; git d06d6e9e)

(ersilia) @DESKTOP-92JJ0KD:~$ conda list isaura
# Name                    Version                   Build  Channel
isaura                    0.1                      pypi_0    pypi

@DESKTOP-92JJ0KD:~$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.3


@DESKTOP-92JJ0KD:~/ersilia$ ersilia --help
Usage: ersilia [OPTIONS] COMMAND [ARGS]...

  🦠 Welcome to Ersilia! 💊
   ...

robel@DESKTOP-92JJ0KD:~/ersilia$ ersilia catalog
[
    {
        "Identifier": "eos1086"
    } 
   ...

```

**Comment by TsionZerihun** [comment]
## Test the simplest model **eos3b5e**  :heavy_check_mark:
- ### *I successfully fetched and run model*
```
(ersilia) @DESKTOP-92JJ0KD:~$ ersilia -v fetch eos3b5e
⬇️  Fetching model eos3b5e: molecular-weight...
 ---
...👍 Model eos3b5e fetched successfully!

(ersilia) @DESKTOP-92JJ0KD:~$ ersilia serve eos3b5e
🚀 Serving model eos3b5e: molecular-weight
       URL: http://127.0.0.1:42699...
---
...💁 Information:
   - info

```
- ### *However, I faced an error when running prediction*
```
@DESKTOP-92JJ0KD:~$ ersilia -v run -i "CCC"  > my.log 2>&1
```
Check attached error log file for more detail.
[model_eos3b5e_error.log](https://github.com/ersilia-os/ersilia/files/13115534/model_eos3b5e_error.log)

- ### *I tried removing Isaura  based on this [discussion](https://github.com/ersilia-os/ersilia/issues/839)*
```
@DESKTOP-92JJ0KD:~$ python -m pip uninstall isaura
Found existing installation: isaura 0.1
Uninstalling isaura-0.1:
       ...
  Successfully uninstalled isaura-0.1
```

- ### *I was able to successfully run prediction after uninstalling isaura and rerunning*
```
@DESKTOP-92JJ0KD:~$ ersilia -v api run -i "CCCC"
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}
```
Check attached prediction success log file for more detail.
[model_eos3b5e_sucess.log](https://github.com/ersilia-os/ersilia/files/13118376/model_eos3b5e_sucess.log)

**Comment by TsionZerihun** [comment]
# Key takeaways from completing above tasks
> ### - Learned two new terms
>
> - *[Isura](https://github.com/ersilia-os/isaura):* after facing issues running model when isura was install, I went on to see what this particular python package did. Its purpose is to cache previously calculated properties.
#####  I will make sure to reinstall Isaura if caching is necessary when running future models.*
> - *"CCCC"*: "IUPAC name for C-C-C-C  is Hex-2-ene, and contains-only carbon chain"
> ### - Summary
>
> - The above task runs the model [eos3b5e](https://github.com/ersilia-os/eos3b5e) with the molecule we provide which is "CCCC" , and determines its molecular weight in g/mol.

**Comment by TsionZerihun** [comment]
### Self Introduction
I'd like to introduce myself as a person who is enthusiastic about automation and its impacts. In addition to studying computer science, I completed a 1 year intensive software engineering program with a focus on backend development at ALX.
Over the past few years, I have worked in various sectors, including full-stack development and data analysis, utilizing my research and analytical skills to improve smallholder farmers' lives.

### How I was Introduced to Machine Learning
I was first introduced to ML when working on a project on developing a REST API for a Y-Maze test. It was based on a pretrained model aiming to automate laboratory researchers' tasks. The project initially seemed intimidating, but with intensive research, I learned a lot and am grateful for the exposure.
### Ersilia 
It was fascinating to see that Ersilia has already begun the path of utilizing currently released technologies to help the world. I think that technology has the potential to change people's lives in different sectors, but that potential is not fully utilized. There is yet to be discovered. Research centers and labs are not as fully automated as they could be.
It was quite exciting when I ran the previous (ersila week 1) task with minimal commands and setups. I was able to run a test, which might have taken a significant amount of time, energy, and skill. Ersilia, in my opinion, is achieving what most software engineers and I hope to achieve, which is using various technologies to improve the world and serve as an inspiration for future innovations.
I believe we are in the perfect time where initiatives and ideas can be easily brought to light, but many people still lack knowledge and tools. Growing open-source projects like Ersilia can assist individuals learn and contribute to the community.
### Conclusion
It would be a great pleasure to join a nonprofit organization that aims to assist experts in discovering new drugs for treating infectious and neglected diseases using the latest technologies, making it convenient and time-saving.
My long-term goal is to work on a project that improves people's lives. I have the vision to enhance my country and the world by coming up with new solutions to various problems.
I would love to be a part of the team so that I can give back to the community. I'm eager to contribute to and learn from Ersilia!

Best,
*Tsion Zeleke*

**Comment by TsionZerihun** [comment]
# Task 1-3
## Select a model from the suggested list  :heavy_check_mark:
- ###  *I selected Rat Liver Microsomal Stability(RLM) from NCATS*
> - ***Microsomal Stability*** :The metabolism of a new chemical entity(drugs) or time dependent decrease of a test compound(drugs) in the incubation mixtures containing liver microsomes
> 
#####  So it uses rats microsomes to tests its microsomal stability which helps in screening of drug candidates in the early stage of drug development*

**Comment by TsionZerihun** [comment]
## Install the model in your system :heavy_check_mark:
- ### *I turned on my base environment again just in case the new installation might affect ersilia's initital env.*
```
(ersilia) robel@DESKTOP-92JJ0KD:~$ conda activate base
(base) robel@DESKTOP-92JJ0KD:~$ 
```
```
(base) robel@DESKTOP-92JJ0KD:~$ git clone --recursive https://github.com/ncats/ncats-adme.git
Cloning into 'ncats-adme'...
remote: Enumerating objects: 3640, done.
remote: Counting objects: 100% (958/958), done.
remote: Compressing objects: 100% (320/320), done.
remote: Total 3640 (delta 663), reused 824 (delta 625), pack-reused 2682
Receiving objects: 100% (3640/3640), 84.95 MiB | 172.00 KiB/s, done.
Resolving deltas: 100% (2102/2102), done.
Checking out files: 100% (663/663), done.
Encountered 9 files that should have been pointers, but weren't:
        server/predictors/pampabbb/scaler.pkl
        server/train_data/cyp450.h5
        server/train_data/hlc.h5
        server/train_data/hlm.h5
        server/train_data/pampa.h5
        server/train_data/pampa50.h5
        server/train_data/pampabbb.h5
        server/train_data/rlm.h5
        server/train_data/solubility.h5
(base) robel@DESKTOP-92JJ0KD:~$ ls
bentoml  eos  ersilia  miniconda3  model_eos3b5e_error.log  model_eos3b5e_sucess.log  ncats-adme
```
- ### *I commented out other models Since the slack instruction mentioned that the wxy command will download every model at once, which would take a lot of time*
```python=
---
 #from predictors.hlm.hlm_predictor import HLMPredictior
 #from predictors.pampa.pampa_predictor import PAMPAPredictior
 #from predictors.pampa50.pampa_predictor import PAMPA50Predictior
 #from predictors.pampabbb.pampa_predictor import PAMPABBBPredictior...
---
...def predict(): ...
---
 for model in models:
        response[model] = {}
        error_messages = []

        # if model.lower() == 'hlm':
        #     predictor = HLMPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        if model.lower() == 'rlm':
            predictor = RLMPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        # elif model.lower() == 'pampa':
        #    predictor = PAMPAPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        #elif model.lower() == 'pampa50':
        #    predictor = PAMPA50Predictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        # elif model.lower() == 'pampabbb':
        #    predictor = PAMPABBBPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        elif model.lower() == 'solubility':
            predictor = SolubilityPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        # elif model.lower() == 'hlc':
        #    predictor = LCPredictor(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
        # elif model.lower() == 'cyp450':
        #    predictor = CYP450Predictor(kekule_mols = working_df['mols'].values, smiles=working_df[smi_column_name].values)
        else:
            break...

```

**Comment by TsionZerihun** [comment]
## - Run predictions for the EML :heavy_check_mark:
- ### *I Opened localhost:500 &rarr; Predict &rarr; uncheck all except RLM &rarr; Text File &rarr; Browse file &rarr; Process File*
- ### *I downloaded the csv file with the list of drugs to be tested from [here](https://github.com/ersilia-os/ersilia/blob/master/notebooks/eml_canonical.csv)*
- ### *It was mind blowing to see 443 drugs being tested for stability in Rats Liver within minutes* 💥 
 Here is the csv of the prediction which is around 9 pages

[ADME_Predictions_2023-10-26-201225.csv](https://github.com/ersilia-os/ersilia/files/13180612/ADME_Predictions_2023-10-26-201225.csv)

**Comment by TsionZerihun** [comment]
## - Compare results with the Ersilia Model Hub implementation! :heavy_check_mark:
- ### *I Opened localhost:5000 &rarr; Predict &rarr; uncheck all except RLM &rarr; Text File &rarr; Browse file &rarr; Process File*
- ### *I downloaded the csv file with the list of drugs to be tested from [here](https://github.com/ersilia-os/ersilia/blob/master/notebooks/eml_canonical.csv)*
- ### *It was mind blowing to see 443 drugs being tested for stability in Rats Liver(Microsome) less than minutes* 💥 
 Here is the csv of the prediction which is around 9 pages

[ADME_Predictions_2023-10-26-201225.csv](https://github.com/ersilia-os/ersilia/files/13180612/ADME_Predictions_2023-10-26-201225.csv)

**Comment by TsionZerihun** [comment]
## Compare results with the Ersilia Model Hub implementation! (Cont'd)
- ### I opened the two models in excel and filtered the ADME model unstable predictions which are 189 in total
    * ![Capture](https://github.com/ersilia-os/ersilia/assets/101357449/959ac238-28a6-42bc-81ec-3352f1f33531)
- ### Next I did the below 3 steps 
    * Bring only the prediction column from the two cells
    * From the ADME predicted cell I remove the "parenthesis" and "1"(stability value ADME predicted) using excel `=Remove()` formula
    * Check the diff between the the models `
    * Filtered diff's by substracting ADME value with ersilia  
    * Checked using `=COUNTIF()` how many of the diffs are > 0.1, which turned out be be 8 out of 189
    * ![comparison](https://github.com/ersilia-os/ersilia/assets/101357449/aca116e4-a393-46ec-ac97-854996dce2e0)

    
 - ### Summary of comparison
    * The above comparison shows that the two prediction have almost 98% similarly. (with 2% of the diffs being >=0.1 
      *similar in terms of prediction the drugs instability probability 

I  have attached comparison file below 
[ADME_Ersilia_Comparsion.xlsx](https://github.com/ersilia-os/ersilia/files/13191878/ADME_Ersilia_Comparsion.xlsx)

**Comment by TsionZerihun** [comment]
# Install and run Docker! :heavy_check_mark:
- ### I was able to install and run hello-world image from docker
```console
@DESKTOP-92JJ0KD:/home/robel# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:88ec0acaa3ec199d3b7eaf73588f4518c25f9d34f58ce9a0df68429c5af48e8d
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

@DESKTOP-92JJ0KD:/home/robel#
```

**Comment by TsionZerihun** [comment]
# Optional Task: 
- #### I noticed that there was an optional task given to replace the entire NCATS-ADME server with a  Python script. And tried to follow this steps to achieve it
- ### *Clean code*
    * I Clean app.py file by removing codes used for other models
    * I replaces the new(cleaned) app.py file and run `python app.py` to check if it still works which it does. Here is a preview of the file
```diff

- from predictors.hlm.hlm_predictor import HLMPredictior
- from predictors.pampa.pampa_predictor import PAMPAPredictior
- from predictors.pampa50.pampa_predictor import PAMPA50Predictior
- from predictors.pampabbb.pampa_predictor import PAMPABBBPredictior
- from predictors.solubility.solubility_predictor import SolubilityPredictior
- from predictors.liver_cytosol.lc_predictor import LCPredictor
- from predictors.cyp450.cyp450_predictor import CYP450Predictor
```
```diff
-       # if model.lower() == 'hlm':
-        #     predictor = HLMPredictior(kekule_smiles = working_df['kekule_smiles'].values, --smiles=working_df[smi_column_name].values)
        if model.lower() == 'rlm':
            predictor = RLMPredictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'pampa':
-            predictor = PAMPAPredictior(kekule_smiles = working_df['kekule_smiles'].values, -smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'pampa50':
-            predictor = PAMPA50Predictior(kekule_smiles = working_df['kekule_smiles'].values, smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'pampabbb':
-            predictor = PAMPABBBPredictior(kekule_smiles = working_df['kekule_smiles'].values, -smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'solubility':
-            predictor = SolubilityPredictior(kekule_smiles = working_df['kekule_smiles'].values, -smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'hlc':
-            predictor = LCPredictor(kekule_smiles = working_df['kekule_smiles'].values, -smiles=working_df[smi_column_name].values)
-        elif model.lower() == 'cyp450':
-            predictor = CYP450Predictor(kekule_mols = working_df['mols'].values, smiles=working_df[smi_column_name].values
```
```diff
  if model.lower() != 'cyp450':
                # for all models except cyp450, calculate the nearest neigbors and add additional column to response_df
                try:
                    sim_vals = get_similar_mols(response_df[smi_column_name].values, model.lower())
                    sim_series = pd.Series(sim_vals).round(2).astype(str)
                    response_df['Tanimoto Similarity'] = sim_series.values
                    columns_dict['Tanimoto Similarity'] = { 'order': 3, 'description': 'similarity towards nearest neighbor in training data', 'isSmilesColumn': False }
                except Exception as e:
                    app.logger.error('Error calculating similarity')
                    app.logger.error(f'error type: {type(e)}')
                    app.logger.error(e)
-            else:
-                # for cyp450 models, a similarity value is calculated using a global dataset that is representative of all six cyp450 endpoints
-                try:
-                    sim_vals = get_similar_mols(response_df[smi_column_name].values, model.lower())
-                    sim_series = pd.Series(sim_vals).round(2).astype(str)
-                    response_df['Tanimoto Similarity'] = sim_series.values
-                    columns_dict['Tanimoto Similarity'] = { 'order': 7, 'description': 'similarity towards nearest neighbor in training data that was obtained by combining the compounds from all six individual datasets', 'isSmilesColumn': False }
-                except Exception as e:
-                    app.logger.error('Error calculating similarity')
-                    app.logger.error(f'error type: {type(e)}')
-                    app.logger.error(e)
```
- ### I went to the model folder and removed all other models except for RLM
```console
@DESKTOP-92JJ0KD:~/ncats-adme/server/models$ ls
rlm
(base) robel@DESKTOP-92JJ0KD:~/ncats-adme/server/models$
```
I decide to hold the task because
    1. I figured I would prioritize the things that are required of me now that I have limited time and come back to this later.
    2. I wanted to check with my mentors regarding my approach and understanding of the question before moving forward because I'm not sure if I'm taking the proper approach or if I have understood the task correctly.

# Planned to do
   ### - Update the code to take arguments and run, instead of serve using flask
   ### - Update the code to take arguments for the output's location.

**Comment by TsionZerihun** [comment]
## *Step I followed to select Model suggestion*
- ### APPROACH-1: Find models related to a particular pathogen.
    1. I looked for highly infectious disease which are neglected or are emerging but not given much attention
    2. I selected this 5 (dengue, Trachoma,  mycetoma, Schistosomiasis) disease.
    3. I started searching ML models associated with them, but after obtaining some models for mycetoma and schistosomiasis, I noticed that they had already been added to Ersilia's model hub.
    - **Mycetoma**
        > ![mycetoma](https://github.com/ersilia-os/ersilia/assets/101357449/4ad9cb29-f62f-4d39-94a8-5f3288692a19)
    -  **Schistosomiasis**
        > ![schitosomiasis](https://github.com/ersilia-os/ersilia/assets/101357449/34ea8bf4-c02f-4f91-91a4-688f6b32ba1e)
    - Finally, I narrowed down my search to denga and Trachoma
   
- ### APPROACH-2: Look for drug-related models
    -  #### It was interesting to see the different ways a model can assist/speedup in drug discovery. Which includes predicting:
        - The drugs activity against the organism that caused the disease(Pathogens). 
        - The drugs toxicity to the cells(Cytotoxicity)
        - The pharmacological properties of the lead molecules(drug)
        - The binding affinity of potential molecules to the target protein
        - Predict Genetic changes in pathogenic microorganisms and many more
- ### Filtering searches: I selected models using the filtering strategy listed below.
    * Have free to use open source code 
    * Work with smiles notation when accepting molecules or drugs (inputs are small molecules compounds,)
    * Ensure that the documentation is clear and preferably dated 2020 or later if it was cited.
    * Model is not already included in the Erailia [Model hub](https://airtable.com/shrNc3sTtTA3QeEZu/tblZGe2a2XeBxrEHP), and [backlog](https://airtable.com/appgxpCzCDNyGjWc8/shrTpe45mLKqaHXsc)
    * Can be installed and used smoothly
- ### Finally I started looking for model leveraging the resources recommendation (i.e paper with code and others) [here](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/incorporate-models)

**Comment by TsionZerihun** [comment]
## Suggest a new model and document it: First Model  :heavy_check_mark:
- ### About the model
    > **Name**: Drug Combination (Graph Set) Generation 
        - Deep Generative Models for given Hierarchical Disease Network Embedding
    > **Source code**: https://github.com/Shen-Lab/Drug-Combo-Generator/tree/master
    > **Publication**: https://pubmed.ncbi.nlm.nih.gov/32657357/
    > **Description**: Drug-combo-generator is a  deep generative model for drug combination design, by jointly embedding graph-structured domain knowledge and iteratively training a reinforcement learning-based chemical graph-set designer.

- ### Why it would be relevant to Ersilia:
   -  Combination drug therapy involves combining drugs to enhance efficacy, treating various diseases like tuberculosis, HIV, and various cancers. Since infections are heterogeneous, the bacteria can be in different stages of development, you may require more than one dug.
    - This could be important for Ersilia, as it focuses on **infectious and neglected diseases**. Targeting infectious diseases at multiple states is made easy with this model. Using the medication combination generator has the following advantages:
      - One drug may target one pathway, another drug another pathway. 
      - Sometimes drugs enhance the efficacy of each other – this is called synergy. Synergistic combinations of drugs can help in terms of: - 
        - Allowing to use lower drug doses
        - Minimizing side effects
        - Clearing the infection more efficiently.
        - Overcome resistance in antibiotics, anti-microbials, and anti-cancer drugs.

- ### Model implementation :
    - I was able to install the model smoothly using this installation guide (https://github.com/Shen-Lab/Drug-Combo
Generator/tree/master/Methods/RL)
    - The model shown above finished every item on the checklist below and I would suggested it.
        - Have free to use open source code:heavy_check_mark:
        - Work with smiles notation when accepting molecules or drugs (inputs are small molecules compounds,):heavy_check_mark:
        - Ensure that the documentation is clear and preferably dated 2020 or later if it was cited.:heavy_check_mark:
        - Model is not already included in the Erailia Model hub, and backlog:heavy_check_mark:
        - Can be installed and used smoothly

**Comment by TsionZerihun** [comment]
## Suggest a new model and document it: Second Model  :heavy_check_mark:
- ### About the model
    > **Name**: DeepDTA: deep drug-target binding affinity 
    > **Source code**: https://github.com/XuanLin1991/DeepGS
    > **Publication**: https://arxiv.org/abs/2003.13902
    > **Description**:  Modeling of protein sequences and compound 1D representations (SMILES) with convolutional neural networks (CNNs) to predict the binding affinity value of drug-target pairs.

- ### Why it would be relevant to Ersilia:
   -  The strength of the interaction between a drug and its target is known as binding affinity. Drug-target affinity prediction, a crucial step in virtual screening, directly impacts drug development progress. 
    - This could be important for Ersilia, to identifying or filter out convenient target drugs by providing information on the strength of the interaction between a drug–target (DT) pair

**Comment by TsionZerihun** [comment]
## Suggest a new model and document it: Third Model  :heavy_check_mark:
- ### About the model
    > **Name**: DrugChat: deep drug-target binding affinity 
    > **Source code**: https://github.com/ucsd-ai4h/drugchat
    > **Publication**: https://www.techrxiv.org/articles/preprint/DrugChat_Towards_Enabling_ChatGPT-Like_Capabilities_on_Drug_Molecule_Graphs/22945922
    > **Description**:   Towards Enabling ChatGPT-Like Capabilities on Drug Molecule Graphs

- ### Why it would be relevant to Ersilia:
    - We have seen since the release of Chat GPT, accessibility to most resources has been tremendously improved 
     - This model attempt towards enabling ChatGPT-like capabilities on drug molecule graphs, by developing a prototype system DrugChat. This could be important for Ersilia in pharmaceutical research by: 
        - Accelerating drug discovery
        - Enhancing our understanding of structure-activity relationships
        - Guiding lead optimization
        - Aiding drug repurposing
        - Reducing the failure rate, and streamlining clinical trials.

**Comment by TsionZerihun** [comment]
## Suggest a new model and document it: Second Model  :heavy_check_mark:

- ### Additional Models
    - I also found some interesting additional models.
         > **Name**: toxAIcity
         > **Source code**: https://github.com/subhasishgoswami/toxAIcity
         > **Description**:   A Long short-term memory based classifier to classify new drug candidates if toxic using Simplified molecular-input line-entry system notation.


         > **Name**: ChemCPA
         > **Source code**: https://github.com/theislab/chemCPA
         > **Description**:   Predicting Cellular Responses to Novel Drug Perturbations at a Single-Cell Resolution

- ### Out of scope models related to neglected and infectious models.
    - While I filtered neglected diseases and looked for models related to to them, I found this interesting models but decided not to include them in my suggestion because the did not accept smiles as input
        - Changas
            > **Name**: Chagas detection
            > **Source code**: https://github.com/csbl-br/chagas_detection
            > **Description**:   Chagas detection is a tool for the detection of **T. cruzi trypomastigote **forms in blood smear images. In particular, it provides a machine learning based method for the detection of parasites in images acquired using a mobile phone camera
        - leptospirosis 
           > **Name**: lepto-classifier
           > **Source code**:  https://github.com/sf-deng/lepto-classifier
            > **Description**:   A SVM-based binary classifier to detect leptospirosis diseases in dogs

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
