### ISSUE TITLE
🐛 Bug: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by patient74** [ersilia-os/ersilia#881]
### Describe the bug.

https://github.com/ersilia-os/ersilia/blob/e5ef485f51cf9b86f6ae3b93bd889d77e6abd90b/ersilia/io/readers/file.py#L320C22-L320C22

In line 320,

`h = None`

the variable h is assigned a `None` value but on next line `h` is passed as a parameter to `len()` .  This can lead to the **TypeError** as `len()`  can only be used for collections.
I tried assigning an empty list to `h` (`h = []`) which seems to solve the problem.

### Describe the steps to reproduce the behavior

After following the installing instructions on Ersilia book, I followed the instructions for [model usage](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/antibiotic-activity-prediction) to fetch and run the **retrosynthetic-accessibility model (eos2r5a)**.
I was able to `fetch` and `serve` the model successfully but while running the model using,

`ersilia api run -i "C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]"`

I got the error,

>  File "/home/patient74/.local/lib/python3.8/site-packages/ersilia/io/readers/file.py", line 321, in read_input_columns
>     if len(h) == 1:
> TypeError: object of type 'NoneType' has no len()

### Operating environment

Ubuntu 20.04.5 LTS in WSL

**Comment by joiboi08** [comment]
I think this happens because it tries to catch a header row but since it is nonexistent, it gives that error.


Could you please try running the input from a csv file with a filled header row?

**Comment by patient74** [comment]
@joiboi08 I tried running an input csv file,

```
C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]
CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
```

as mentioned in [model usage](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/antibiotic-activity-prediction) but I am still getting the same error if `h` is assigned a `None` value .

I don't get an error when I replace `h` with an empty list (`h = []`)

**Comment by joiboi08** [comment]
I'll try this locally and get back to you

**Comment by joiboi08** [comment]
Hi @patient74 

Sorry about the time I am facing some local outages.

I ran it successfully on my local setup. 
Here is the log file :
[logfile.log](https://github.com/ersilia-os/ersilia/files/13178102/logfile.log)

We faced this issue earlier too and accordingly, 
- I am running Python `version 3.10` 
- I have NOT installed Isaura Datalakes. 
If you have installed it as part of the setup mentioned in the Gitbook, please try uninstalling it and trying again.

**Comment by patient74** [comment]
@joiboi08 Thanks for running it in your local setup. As you mentioned I have Isaura installed having followed the instruction in Ersilia book. But I do think assigning `None` to a variable with a possibility of that variable being used as a parameter to `len()` can lead to errors

**Comment by joiboi08** [comment]
This was actually raised as a PR [here](https://github.com/ersilia-os/ersilia/pull/827) and while it solved the problem it was advised not to change the codebase.

**Comment by patient74** [comment]
Thanks @joiboi08 I was not aware of that PR. Based on the recommendations there, I think I will close this issue here.
