### ISSUE TITLE
🦠 Model Request: MoLeR with Enamine Building Blocks

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#890]
### Model Name

Extending molecular scaffolds with building blocks

### Model Description

MoLeR is a graph-based generative model that combines fragment-based and atom-by-atom generation of new molecules with scaffold-constrained optimization. It does not depend on generation history and therefore MoLeR is able to complete arbitrary scaffolds. The model has been trained on the GuacaMol dataset. Here we sample the 300k building blocks library from Enamine.

### Slug

moler-enamine-blocks

### Tag

Chemical graph model,Compound generation

### Publication

https://arxiv.org/abs/2103.03864

### Source Code

https://github.com/microsoft/molecule-generation

### License

MIT

**Comment by GemmaTuron** [comment]
This model is now incorporated
