### ISSUE TITLE
📑 Feature Request: Improve the Model request form

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#899]
### Is your feature request related to a problem? Please describe.

The model request has certain fields which need to be filled in with specific words (for example, tags, licenses...) those can be found as .txt files in the metadata. If those are not written properly, later checks will fail causing a lot of back and forth between user and maintainer

### Describe the solution you'd like.

Could we provide a dropdown list in the "Model Request" issue so that users only select from those approved words?

**Comment by DhanshreeA** [comment]
@GemmaTuron I can take this up, or just let me know if you need anything from me here.

**Comment by GemmaTuron** [comment]
Yeah, we can put this on low priority list - making dropdowns is not that straightforward if we want the github action to parse the model request properly so I don't want to enter a debugging cycle for a nice to have

**Comment by DhanshreeA** [comment]
This dropdown is now enabled in the new Model Request issue template.

**Comment by GemmaTuron** [comment]
really? ❤️

**Comment by DhanshreeA** [comment]
yes it was relatively straightforward, and I bundled it with other issue template changes I was making anyway. :) @GemmaTuron
