### ISSUE TITLE
🐛 Bug: Model Description Parsing from Model Request Issue

### ISSUE THREAD

**Issue by HellenNamulinda** [ersilia-os/ersilia#901]
### Describe the bug.

There is an automated update of the metadata file when the model repo is created from the model request issue.

The bug occurs when the Model Description field contains a comma. Instead of being parsed as a string, it is parsed as a list.
This causes the metadata check in GitHub actions to fail, when updating the Airtable.

### Describe the steps to reproduce the behavior

1. Open a new Model Request.
2. Enter a Model Description that contains a comma. 

3. Once this is approved (/approve), the description field  in the metadata file is saved as a list instead of a string ;
Forexample;  [eos5xng](https://github.com/ersilia-os/ersilia/issues/898), description is saved as [ a list](https://github.com/ersilia-os/eos5xng/blob/main/metadata.json#L6C7-L6C7)

Also for [eos30f3](https://github.com/ersilia-os/ersilia/issues/750), model description is [a list](https://github.com/ersilia-os/eos30f3/blob/main/metadata.json#L6)
  

### Expected behavior.

I expect the Model Description provided in the model request issue to be parsed as a string, maintaining its original format, and not be converted to a list.

### Operating environment

GitHub Actions

### Additional context

The problem with parsing the Model Description as a list affects subsequent metadata checking, particularly when checking the length of the Model Description, and raising [an error](https://github.com/ersilia-os/ersilia/blob/master/ersilia/hub/content/card.py#L144)` if len(new_description) < 200`. 

Additionally, the `issue-template-parser` GitHub Action, which is used in our workflow, automatically [interprets input fields as lists if they contain commas](https://github.com/GrantBirki/issue-template-parser#example-). 

To address this,  we might have to implement a manual conversion of the "model_description" field to a string before saving it to metadata in our workflow logic. This ensures that the Model Description is consistently treated as a string regardless.

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

What is the status of this? In the isse-template-parser there is an option to resolve this: `When csv_to_list is 'false', the value will not change`

With that, we should be able to simply avoid the conversion to list in the description field?

**Comment by GemmaTuron** [comment]
Can we apply this to only the description? because for the other fields we do want to have a list.

IF we cannot, I do not see a major problem currently, since the `metadata.json `file needs to be manually edited before making the PR, so this issue can be manually taken care of. A bit dirty, but functional. Do you agree @miquelduranfrigola ?

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,

The issue arises from the fact that metadata fields including Description are [populated](https://github.com/ersilia-os/ersilia/blob/master/.github/scripts/update_metadata.py#L89C40-L89C73) from the input of the new model submission request.  If someone forgets to manually edit the Description field in metadata.json, an error occurs.

Instead of setting `csv_to_list to false`, which would affect all fields, we can handle the value of the description field from the [update_metadata.py](https://github.com/ersilia-os/ersilia/blob/master/.github/scripts/update_metadata.py#L105) script.

We can modify
```
  if self.metadata["Description"] == "":
            self.metadata["Description"] = self.json_input["model_description"]
```
to 

```
if self.metadata["Description"] == "":
    # Check if model_description is a list
    if isinstance(self.json_input["model_description"], list):
        # Join the list elements into a single string separated by commas
        self.metadata["Description"] = ", ".join(self.json_input["model_description"])
    else:
        # If it's already a string, just assign it directly
        self.metadata["Description"] = self.json_input["model_description"] 
```

If the adjustment is okay, I have made [a PR](https://github.com/ersilia-os/ersilia/pull/965).

**Comment by DhanshreeA** [comment]
I like @HellenNamulinda 's solution better, but I need some more context. @HellenNamulinda I don't remember running into this issue, but I totally see this happening. However the template-parser README states that it should only happen for single line statements. Are we sure it's happening everywhere? The examples you have provided do not contain single lines for the Description field in the metadata.json. Could you please share links to the actions that failed because the description was converted to a list? (I'm sorry I tried looking but could not find them!)

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA !

If you want, you can play with it since your approve command should work now that you are managing Ersilia's organisation - you can open a test model request and see what happens - will be quicker than trying to find an example from previous models

**Comment by DhanshreeA** [comment]
Resolved here: https://github.com/ersilia-os/ersilia/pull/965
