### ISSUE TITLE
🐕 Batch: Pre-submission lintern

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#903]
### Summary

Often, small errors like a short title in the metadata will cause the model incorporation workflows to fail. It would be good to identify these errors earlier using a lintern.

Ideally, we would have a command like:
```bash
ersilia lint --repo_path $PATH_TO_WIP_MODEL
```

### Objectives

We can potentially check several things in a model repository, including:
- The `metadata.json` file
- The `Dockerfile`
- The `model/framework` and `model/checkpoints` folders
- The `LICENSE`

I would start with the `metadata.json` file. Most of the heavy lifting has already been done here: https://github.com/ersilia-os/ersilia/blob/master/ersilia/hub/content/card.py

A potential approach would be:
1. Create a module called `lintern.py` under `hub/content/`
2. Write a class called `Lint` with an arbitrary number of methods, including `metadata`.
3. Write a CLI command that primarily uses the `Lint` class to check that everything is correct in the `--repo_path` folder.

Do the test as part of an earlier workflow. These are not mutually exclusive

**Comment by GemmaTuron** [comment]
Is this lint check better suited for ersilia-maintenance? has any work in this direction been done or could this be an entry-level task @miquelduranfrigola and @DhanshreeA ?

**Comment by miquelduranfrigola** [comment]
Given that we have plans to simplify the CLI commands, I would definitely not include a `lint` command. However, lint functionalities are included (and could be further expanded) in both the `test` command as well as the `ModelInspector` class (used in [ersilia-maintenance](https://github.com/ersilia-os/ersilia-maintenance)).

We can certainly think of more "tests" or "inspections" to do and come up with a good entry-level task. This is a good idea.

**Comment by DhanshreeA** [comment]
Plus to add to @miquelduranfrigola 's point, ersilia pack also has a lint built in for newer model contributions.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 
Please if this is a good entry level task, open the appropriate issues in `ersilia-maintenance` repository or wherever appropriate.

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola and @DhanshreeA 

Should we close this model then?

**Comment by miquelduranfrigola** [comment]
I'll let @DhanshreeA decide

**Comment by DhanshreeA** [comment]
Yes, I think it's good to close this issue. We need to only focus on ersilia inspect, test, and the lint command within ersilia-pack (which can be added as a pipeline step on its own)

**Comment by miquelduranfrigola** [comment]
This makes sense, @DhanshreeA - thanks
