### ISSUE TITLE
🦠 Model Request: NPBERT-Antimalaria

### ISSUE THREAD

**Issue by leilayesufu** [ersilia-os/ersilia#904]
### Model Name

Predicting Antimalarial Activity in Natural Products Using Pretrained Bidirectional Encoder Representations from Transformers

### Model Description

 This model uses a molecular encoding scheme based on Bidirectional Encoder Representations from Transformers (BERT), employing a pretrained encoding model called NPBERT. Four machine learning algorithms—k-Nearest Neighbors (k-NN), Support Vector Machines (SVM), eXtreme Gradient Boosting (XGB), and Random Forest (RF) were employed to create prediction models. The results indicate that SVM models outperform others, and the proposed NPBERT molecular encoding scheme is more effective than existing methods.

### Slug

NPBERT-Antimalaria

### Tag

Malaria, P.falciparum

### Publication

https://pubs.acs.org/doi/full/10.1021/acs.jcim.1c00584

### Source Code

https://github.com/mldlproject/2021-NPBERT-Antimalaria

### License

None

**Comment by leilayesufu** [comment]
@GemmaTuron I couldn't access the complete article.

**Comment by GemmaTuron** [comment]
Hi @leilayesufu 
I've asked for it on the slack channel, you can start working on the code meanwhile

**Comment by GemmaTuron** [comment]
try to run the BERT model with their pretrained checkpoints

**Comment by leilayesufu** [comment]
@GemmaTuron I tried running the code as seen here https://github.com/mldlproject/2021-NPBERT-Antimalaria/tree/main/training/NPBERT_pretrained_model/save_model 
I got the following error 
`Traceback (most recent call last):
  File "extract_feature.py", line 41, in <module>
    tokenizer=btokenizer
  File "/home/leila/miniconda3/envs/BERT/lib/python3.7/site-packages/transformers/pipelines/__init__.py", line 340, in pipeline
    framework = framework or get_framework(model)
  File "/home/leila/miniconda3/envs/BERT/lib/python3.7/site-packages/transformers/pipelines/base.py", line 66, in get_framework
    model = AutoModel.from_pretrained(model, revision=revision)
  File "/home/leila/miniconda3/envs/BERT/lib/python3.7/site-packages/transformers/models/auto/modeling_auto.py", line 729, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **kwargs
  File "/home/leila/miniconda3/envs/BERT/lib/python3.7/site-packages/transformers/modeling_utils.py", line 984, in from_pretrained
    pretrained_model_name_or_path,
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./save_model or `from_tf` set to False`
 This suggests that the pretrained model files are not present in the save_model directory. I tried to download the files from the link provided but it's a broken link

**Comment by GemmaTuron** [comment]
The model is on hold since the checkpoints are not provided. I've opened an issue on their repository asking for them.

**Comment by DhanshreeA** [comment]
@GemmaTuron did they ever get back?

**Comment by GemmaTuron** [comment]
no, I'll do a follow up!

**Comment by DhanshreeA** [comment]
This will not be implemented since we do not have the checkpoints and the authors haven't responded.
