### ISSUE TITLE
Create custom action to run model

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#910]
Create a GitHub action to run the eos3b5e model with inputted data and return results

**Comment by miquelduranfrigola** [comment]
Typically, the following steps are performed, given a model identifier (`eos3b5e`) and an input file (`my_input.csv`).

## Fetch the model from the Ersilia Model Hub

The model needs to be fetched. There are multiple ways to fetch the model. I would recommend that we simply pull the Docker image of the model (available at https://hub.docker.com/r/ersiliaos/eos3b5e); this can be done with the `--from_dockerhub` command. The `-v` flag runs ersilia in verbose mode.
```
ersilia -v fetch eos3b5e --from_dockerhub
```

## Run predictions

Once the model is fetch, we have to serve it to run predictions.
```
ersilia serve eos3b5e
ersilia run -i my_input.csv -o my_output.csv
ersilia close
```

## Delete model (optional)

We may want to delete the model from our system (basically, remove the docker image) when we are done:

```
ersilia delete eos3b5e
```
