### ISSUE TITLE
Ersilia to provide output validation script

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#911]
Ersilia will provide a script that validates the output from the action that runs the model

**Comment by GemmaTuron** [comment]
@miquelduranfrigola here do you simply refer to a validation of whether the output is a float, a string...?

**Comment by miquelduranfrigola** [comment]
> @miquelduranfrigola here do you simply refer to a validation of whether the output is a float, a string...?

Yes indeed - but this is now done by Ersilia already, so no need to check it again.
