### ISSUE TITLE
Create issue template v2

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#914]
Update the already created issue template to change the selected model from being hardcoded as `eos3b5e` to a select field where the user can select from any valid model.

**Comment by miquelduranfrigola** [comment]
This is interesting. Where would you need the list of valid models to be stored?

To get started, I would also be OK with having a text box where users input their model identifier of interest.

Generally, model identifiers can be found in this AirTable base: https://airtable.com/appgxpCzCDNyGjWc8/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg
