### ISSUE TITLE
Update submission action

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#915]
update the action based on the submission of an issue to no long be hardcoded to `eos3b5e` as the default model but to use the model selected in the issue.

**Comment by miquelduranfrigola** [comment]
Thanks @seanmarcia 

For testing purposes, these would be 3 model identifiers to check:
* `eos3b5e`
* `eos4e40`
* `eos5axz`

**Comment by DhanshreeA** [comment]
@miquelduranfrigola I need more context, what kind of issues and which action are being referred to here?

**Comment by miquelduranfrigola** [comment]
No worries for now, @DhanshreeA - I suggest you join the upcoming meeting with the GitHub team and we take it from there. This issue is one of several labeled as "GitHub SBV Actions". This is the corresponding project dashboard: https://github.com/orgs/ersilia-os/projects/9

**Comment by DhanshreeA** [comment]
@miquelduranfrigola I think I understand more now after the meetings we have had so far. I'll join the next meeting with GitHub team.
