### ISSUE TITLE
Outreachy Code Project: Name: Anamika Yadav 

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/ersilia#92]
Applicant: https://github.com/anamika-yadav99

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [x] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [x] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [x] Select one issue related to improving the CLI and request to be assigned to it.
- [x] Link the #PR as a comment under this issue.
- [x] Make any changes required in the PR and tick this box once it has been approved.
- [x] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [x] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [x] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [x] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [x]  Check the models available in the Hub
- [x] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [x] Add your card as a comment to this issue
- [x] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [x] Link in the comments any other PR you have contributed to.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by camus60** [comment]
@anamika-yadav99  Is this the format that issue is meant to have going forward?

**Comment by mahamtariq58** [comment]
![Uploading Screenshot from 2022-04-03 16-22-23.png…]()

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 
You have done some good work on the CLI! Can you link the relevant issues / PR's that you have contributed to? This way we can better follow your work!
Thanks

**Comment by anamika-yadav99** [comment]
@GemmaTuron I'll have completed most of these tasks. Can I do it after a couple of days? I have my exams going on currently.

**Comment by anamika-yadav99** [comment]
I have fetched and run chemprop-antibiotic model
![image](https://user-images.githubusercontent.com/54634163/162616415-a18c27c5-a9c2-4e75-a220-0b0a327e302a.png)

**Comment by anamika-yadav99** [comment]
Fetched 3 models 
![image](https://user-images.githubusercontent.com/54634163/162616739-32f2fab4-f051-4f52-b281-c9333740d97e.png)

**Comment by anamika-yadav99** [comment]
I was assigned issue #13 to add model search functionality in CLI : `$ersilia catalog --text "chemprop-antibiotic" `  and  ' $ersilia catalog --mode "pretrained"` to cli.
![image](https://user-images.githubusercontent.com/54634163/162616993-8cc89eac-3144-4c74-ad3c-b9ba6f6e42f2.png)

I have completed the task and the issue was closed.
Pull Request successfully merged  : #41

**Comment by anamika-yadav99** [comment]
Discussion on issue #60 Improving the search engine in https://airtable.com/shrUcrUnd7jB9ChZV/tblZGe2a2XeBxrEHP. I had suggested to add tag word to the model card which could be used to search for model related to they tag keywords. Later these keywords could also be added to `$ersilia --help`.
https://github.com/ersilia-os/ersilia/issues/60#issuecomment-1083385391

**Comment by anamika-yadav99** [comment]
issue #9 Make ersilia conda-installable
Added conda recipe which is used to build conda package . Then uploaded a package from my end to test the package. Raised PR  for the same.
PR #89  successfully merged.

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 thanks for documenting all of this so nicely

**Comment by anamika-yadav99** [comment]
**Add a screenshot showing that you are able to run predictions using ersilia as a Python library (find more information [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.**
![image](https://user-images.githubusercontent.com/54634163/163684579-67a8ff34-b8b6-4867-b03f-18af8fa8bd1b.png)

**Comment by Amna-28** [comment]
> **Link in the comments any other PR you have contributed to.**
> 
> 1. issue [Make ersilia conda-installable #9](https://github.com/ersilia-os/ersilia/issues/9)
>    Added conda recipe which is used to build conda package . Then uploaded a package from my end to test the package.
>    Raised PR  for the same.
>    **PR [added conda recipe  #89](https://github.com/ersilia-os/ersilia/pull/89)  successfully merged.**
> 2. Currently working on [Better model catalog display #12](https://github.com/ersilia-os/ersilia/issues/12) Implementing the suggestions mentioned in the comment
>    [Better model catalog display #12 (comment)](https://github.com/ersilia-os/ersilia/issues/12#issuecomment-1096002423)

Hi @anamika-yadav99 , you have done a great job over all. I really like your approach in solving issue #13 _add model search functionality in CLI_ . Well done!

**Comment by anamika-yadav99** [comment]
> > **Link in the comments any other PR you have contributed to.**
> > 
> > 1. issue [Make ersilia conda-installable #9](https://github.com/ersilia-os/ersilia/issues/9)
> >    Added conda recipe which is used to build conda package . Then uploaded a package from my end to test the package.
> >    Raised PR  for the same.
> >    **PR [added conda recipe  #89](https://github.com/ersilia-os/ersilia/pull/89)  successfully merged.**
> > 2. Currently working on [Better model catalog display #12](https://github.com/ersilia-os/ersilia/issues/12) Implementing the suggestions mentioned in the comment
> >    [Better model catalog display #12 (comment)](https://github.com/ersilia-os/ersilia/issues/12#issuecomment-1096002423)
> 
> Hi @anamika-yadav99 , you have done a great job over all. I really like your approach in solving issue #13 _add model search functionality in CLI_ . Well done!

Thanks Amna. You did an amazing job with the streamlit app yourself. The app looks great!

**Comment by anamika-yadav99** [comment]
**Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.**
I came across a lot of models which might play crucial part in drug discovery but since I have a better understanding  of 
**DeepDTA: deep drug–target binding affinity prediction:** 
https://academic.oup.com/bioinformatics/article/34/17/i821/5093245. 

**AtomNet: A Deep Convolutional Neural Network for Bioactivity Prediction in Structure-based Drug Discovery:**
https://arxiv.org/abs/1510.02855

**ChemBO: Bayesian Optimization of Small Organic Molecules with Synthesizable Recommendations:**
https://arxiv.org/abs/1908.01425

**Comment by anamika-yadav99** [comment]
### Write a docstring for the ErsiliaModel class. Use the Google Python Style guide.

_class ErsiliaModel(ErsiliaBase):

    """Child class of ErsiliaBase which serves as the main class for Ersilia Model.
       
       This class provides methods to fetch, serve, api and more.  
       
       
       Attributes:
           model(str):
           save_to_lake(bool, optional): Option to save the calculation to Isaura Lake  
           service_class(str, optional): Service class used. Accepts only [None, conda, venv, system, docker].
           config_json(str, optional): Path to a configuration file.
           credential_json(str, optional): Path to a credentials file.
           verbose(str, optional): Set verbosity.
           fetch_if_not_avalible(bool, optional): Fectches model from the hub if not available in the local.
    """_

@GemmaTuron Will this be all or should I also write for the methods in ErsiliaModel Class?

**Comment by dauinh** [comment]
Hi @anamika-yadav99, I think that your CLI feature suggestion is a really nice idea

**Comment by Amna-28** [comment]
> > > **Link in the comments any other PR you have contributed to.**
> > > 
> > > 1. issue [Make ersilia conda-installable #9](https://github.com/ersilia-os/ersilia/issues/9)
> > >    Added conda recipe which is used to build conda package . Then uploaded a package from my end to test the package.
> > >    Raised PR  for the same.
> > >    **PR [added conda recipe  #89](https://github.com/ersilia-os/ersilia/pull/89)  successfully merged.**
> > > 2. Currently working on [Better model catalog display #12](https://github.com/ersilia-os/ersilia/issues/12) Implementing the suggestions mentioned in the comment
> > >    [Better model catalog display #12 (comment)](https://github.com/ersilia-os/ersilia/issues/12#issuecomment-1096002423)
> > 
> > 
> > Hi @anamika-yadav99 , you have done a great job over all. I really like your approach in solving issue #13 _add model search functionality in CLI_ . Well done!
> 
> Thanks @Amna-28 . You did an amazing job with the streamlit app yourself. The app looks great!

Thank you so much @anamika-yadav99

**Comment by anamika-yadav99** [comment]
![image](https://user-images.githubusercontent.com/54634163/164374659-cdc13750-cb91-467c-b4a7-4c799bdb7a90.png)

**Comment by anamika-yadav99** [comment]
**Comment under this issue explaining why you are interested in this project.**

I’m a 3rd year undergraduate student from New Delhi, India. I’m currently pursuing engineering from GGS Indraprastha University, New Delhi. I’m a big supporter of open science and open source. I’m intrigued by the support and opportunities open source could provide to the scientific community and people. I have always wanted to work on projects which build tools for the scientific research community. It’s one of the driving forces to pursue this project. None the less, this project is aimed for developing country. 
I'm passionate about the application of ML in healthcare, drug discovery, genetic engineering etc . I wish to further pursue post grad in one of the fields like computational biology, biotechnology, AI+health(not sure, still exploring) but somewhere along the lines. This project gives me an opportunity to work closely with the ML papers in drug discovery.
I'm fluent in python and very well familiar with implementing ML papers, ML Toolboxes. This project is apt for  my skillset and interest.
