### ISSUE TITLE
🐛 Bug: Use PyPI Token in publishing workflows

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#922]
### Describe the bug.

We currently use PyPI Username and Password as authentication mechanism in publish workflows. The recommended authentication method is using an API Token https://pyfound.blogspot.com/2020/01/start-using-2fa-and-api-tokens-on-pypi.html

### Operating environment

NA

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA 

The current workflow still fails: https://github.com/ersilia-os/ersilia/actions/runs/7272748115/job/19815410180

**Comment by miquelduranfrigola** [comment]
**Update** I have resolved the `poetry` installation issue @DhanshreeA 
Just using this action from the marketplace: https://github.com/marketplace/actions/python-poetry-action

**Comment by miquelduranfrigola** [comment]
Hello @DhanshreeA - anything I should do here?

**Comment by DhanshreeA** [comment]
@miquelduranfrigola I think this was resolved during the Airtable chaos recently?

**Comment by miquelduranfrigola** [comment]
Yeap
