### ISSUE TITLE
🐛 Bug: Pandas requirement

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#928]
### Describe the bug.

The tracking module requires pandas to work, which we have tried to avoid using so far
Should we modify the tracking module or install pandas as a requirement with Ersilia?

### Operating environment

Ubuntu 20.04 LTS

**Comment by GemmaTuron** [comment]
This is related to #925

**Comment by GemmaTuron** [comment]
Would probably solve #896 as well
@miquelduranfrigola maybe we need to add pandas to Ersilia's requirements

**Comment by miquelduranfrigola** [comment]
Yes, @GemmaTuron - it is possible that we have to install `pandas` eventually. For now, though, it is only a requirement of the `test.py` module (I think), so perhaps we can just install it when tests are to be performed?

**Comment by GemmaTuron** [comment]
Pandas needed for the tracking module as well @miquelduranfrigola  - and for the API with Python

**Comment by GemmaTuron** [comment]
actually pandas does seem to be included in requirements?
```
pandas = [
    {version="1.2.4", python="3.7.*"},
    {version="~1.3.0", python=">=3.8"},
]
```

**Comment by GemmaTuron** [comment]
Ersilia now installs pandas automatically.
If we could remove pandas requirement from
- Tracking
- Testing
We'd be back to a more clean install - what do you think @miquelduranfrigola and @DhanshreeA ? do we need to bother?

**Comment by miquelduranfrigola** [comment]
I am always in favor of not using pandas. I do not remember where pandas is being used at the moment. Low priority at the moment, but perhaps we could consider this as part of this issue #900

**Comment by GemmaTuron** [comment]
The testing and tracking modules are using Pandas. I am unsure about the tracking, but the testing should be easy as I'd prefer it uses JSON anyway

**Comment by DhanshreeA** [comment]
I need more context to look into this but since this issue has been open for quite some time now and seems to be spanning more than one issue I am putting it on high priority. Also personally I want to look into the track command because I've not used it so far and have little to no insight into it.

**Comment by GemmaTuron** [comment]
The tracking command is for integration with Splunk

**Comment by DhanshreeA** [comment]
Also related to #1054
