### ISSUE TITLE
Outreachy Documentation Project: <Simran1604>

### ISSUE THREAD

**Issue by Simran1604** [ersilia-os/ersilia#93]
**What is your feature request?**
There are some spelling and grammatical errors in the readme.md file which can be resolved and also there is as of now no information or links to direct the new commers to the contribution guidelines in the readme file. Including that information can be quite helpful.

**Is your feature request related to a problem?**
As I landed on the repository and went through the readme.md file, I searched for some information or direction to contributing in this codebase in the file but couldn't get it. Someone who is new to the repository will find it easier to navigate to that information from the readme page than looking for the new_contributors.md and contributing.md file in the repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by Simran1604** [comment]
I will like to work on this issue, pls assign this to me.

**Comment by victorabba** [comment]
I developed a contributing guideline which is stored in the contribution.md file. I will like to add that to the readme file and make additional charges as well.

**Comment by GemmaTuron** [comment]
Hello @Simran1604 

Currently @sayantani11 is working in merging the contribution and new_contribution files. Several applicants are working on the README file, creating new versions that go into the /documentation project.
Please, to start contributing, create a new github issue using the appropriate template (see the instructions in the project outreachy website) and start checking the tasks there. It includes tasks for the README files so you can add your ideas there!

**Comment by GemmaTuron** [comment]
> I developed a contributing guideline which is stored in the contribution.md file. I will like to add that to the readme file and make additional charges as well.

Hello @victorabba 
Please can you first go to the github issue you have created and add all your work there before working on new issues?

**Comment by GemmaTuron** [comment]
Hi 
I am closing this issue since each applicant will continue his/her work on the relevant follow up issues.
