### ISSUE TITLE
🐛 Bug: Model repo created and not eliminated if action fails

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#930]
### Describe the bug.

When approving a new model, the workflow might fail if, for example, the contributor changed a field in the form. When it gets an approve command, the repo will be created  and just sit there unused, as the metadata won't be committed, the model di will not be updated on airtable nor the user will receive a response in the issue.
We should add a check that if the action fails, it looks for the created repository and deletes it.
Not prioritary, but nice to have

### Operating environment

Ubuntu 20.04 LTS

**Comment by miquelduranfrigola** [comment]
I see. Do you have an example of this? A link would suffice

**Comment by miquelduranfrigola** [comment]
Interesting. I agree, this would be nice to have. Let me quickly tag @GrantBirki and see if he has an idea on how to address this.

**Comment by GemmaTuron** [comment]
This is now sloved with the user and Ersilia's admins getting a warning about the failure of the workflow and pointing to the repo to be eliminated, thanks!
