### ISSUE TITLE
Outreachy Code Project: <Maham Tariq  , Github : https://github.com/mahamtariq58>

### ISSUE THREAD

**Issue by mahamtariq58** [ersilia-os/ersilia#94]
Applicant: https://github.com/mahamtariq58

Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the Ersilia Model Hub, a FOSS platform offering pre-trained AI/ML models for research”.

Please tick the tasks as you complete them. To make a final application it is not required to have completed all tasks. This project requires knowledge of the Python programming language. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable.

---
### Initial steps
- [x] Record your application for the project in the Outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications.
- [ ] Comment under this issue explaining why you are interested in this project.
---
### Installation of the Ersilia Model Hub
- [x] Install the `ersilia` library.
- [x] Add a screenshot under this issue showing that you are able to run one model (for example, the chemprop-antibiotic model)
- [x] Fetch at least 3 models from the Ersilia Model Hub. You can find these models with the `ersilia catalog` command. Add a screenshot of the *local* catalog (`ersilia catalog –local`)
---
### CLI
- [ ] Check if there are open issues related to the command line interface. Continue with the next tasks if they are open.
- [ ] Select one issue related to improving the CLI and request to be assigned to it.
- [ ] Link the #PR as a comment under this issue.
- [ ] Make any changes required in the PR and tick this box once it has been approved.
- [ ] Suggest at least one missing feature in the CLI (one sentence is enough, for example: “Add command to estimate memory usage of a particular model”).
---
### Python library
- [ ] Add a screenshot showing that you are able to run predictions using `ersilia` as a Python library (find more information  [here](https://ersilia.gitbook.io/ersilia-book/quick-start/antibiotic-activity-prediction)). Ideally, use a Jupyter notebook.
- [ ] Create a simple [Streamlit](https://streamlit.io/) app using the `ersilia` Python library. The app can have an input and an output box, and perhaps a few models to select. Add a screenshot of the app as seen in your browser.
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Scientific content
- [ ]  Check the models available in the Hub
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [ ] Add a comment in this issue with your new idea, tagging the mentor 
- [ ] Get feedback from the mentor and act accordingly
- [ ] Link in the comments any other PR you have contributed to.
---
### Community
- [ ] Look up two other projects and comment on their issues with feedback on one of their tasks
- [ ] If you have feedback from your peers, answer it in this issue.
---
### Final application
- [ ] I have answered all comments from mentors and contributors
- [ ] All PR or issues assigned to me are complete
- [ ] I have submitted my final application to the project

**Comment by mahamtariq58** [comment]
![Screenshot from 2022-04-03 16-22-23](https://user-images.githubusercontent.com/11984160/161425658-7dadbd2e-0141-4e53-8682-2c49ee740ca9.png)

**Comment by mahamtariq58** [comment]
![Screenshot from 2022-04-03 16-22-23](https://user-images.githubusercontent.com/11984160/161426286-071a66e1-ef3d-4d4e-8d75-adc0f16b375a.png)
![Screenshot from 2022-04-03 16-41-50](https://user-images.githubusercontent.com/11984160/161426288-cf2f66af-43cb-459f-a906-efafb2f9cb2b.png)

**Comment by GemmaTuron** [comment]
Hi @mahamtariq58
Thanks, good work on running our software! Please check the next tasks and start working in the ones that are most interesting to you

**Comment by mahamtariq58** [comment]
Thank you @GemmaTuron .. Sure
