### ISSUE TITLE
[Project]: Incorporate the REINVENT generative model in the Ersilia Model Hub

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#942]
### Summary

REINVENT is one of the most successful reinforcement learning models in chemistry. Version 4 of REINVENT has been released recently: [MolecularAI/REINVENT4](https://github.com/MolecularAI/REINVENT4)

As we populate our generative chemistry tool ([ChemSampler](https://github.com/ersilia-os/chem-sampler)), it is becoming increasingly clear that REINVENT should be amongst our collections of generative tools.

We have used REINVENT (Version 2) in the past, with great success in the context of Open Source Malaria. See, for example, [this repository](https://github.com/ersilia-os/osm-series4-candidates-2). In our experience, the best way to use REINVENT is through Jupyter Notebooks, including tinkering with parameters and a lot of visual exploration. Unfortunately, ChemSampler is more geared towards automation and, therefore, we should come up with new settings to run REINVENT robustly without much intervention from the user.

This is a highly interesting project for many reasons:
1. It tackles the task that has the highest demand at Ersilia, namely, generative AI for chemistry.
2. It uses reinforcement learning, which is underrepresented in our hub currently.
3. If successful, this would be a publishable project in standalone form.

### Scope

Initiative 🐋

### Objective(s)

1. Incorporate a generic REINVENT4 model in the Ersilia Model Hub.
2. Incorporate at least 5 fine-tuned REINVENT4 models in the Ersilia Model Hub (to be determined, for example: malaria, tuberculosis, hiv, synthetic accessibility...)
3. Sufficient usage documentation.
4. Write a scientific publication.

### Team

| Role & Responsibility | Username(s) | 
|--|--|
| DRI / Lead Developer | @ankitskvmdam |
| Supervisor | @miquelduranfrigola  |

### Timeline

TBD

### Documentation

* REINVENT: https://github.com/MolecularAI/REINVENT4
* ChemSampler: https://github.com/ersilia-os/chem-sampler
* ChemSampler GitBook: https://ersilia.gitbook.io/ersilia-book/chemistry-tools/sampling-the-chemical-space
* Other generative models at Ersilia: [eos9taz](https://github.com/ersilia-os/eos9taz), [eos4qda](https://github.com/ersilia-os/eos4qda)

**Comment by miquelduranfrigola** [comment]
Hi @ankitskvmdam,

Let's use this issue to update on progress related to this project.

Some takeaways today's meeting (29/01/2024):
- We will meet every Monday at 1pm CET.
- I will add you in Ersilia's Slack workspace.
- Let's work on REINVENT 4, if possible.
- Let's not get distracted by the OSM project, previously conducted by Ersilia using REINVENT 2.
- Overall objective for the first week is to get familiar with REINVENT and test at least one of their notebooks. Please pay especial attention to computational demands (including the need for GPU).

**Comment by ankitskvmdam** [comment]
@miquelduranfrigola Here are some molecules produced by the ‘reinvent 4 mol2mol_medium_similarity.prior’.

![COc1ccc(S(=O)(=O)N(CCC(=O)NO)CCc2cccc(OC)c2)cc1](https://github.com/ersilia-os/ersilia/assets/22586210/c7558573-4156-4f8d-b2ae-757f87e95049)
![COc1ccc(S(=O)(=O)N(CCC(=O)NO)CCc2ccc( N+ (=O) O- )cc2)cc1](https://github.com/ersilia-os/ersilia/assets/22586210/535bfa37-8940-4c63-acba-74ae8499eba3)
![COCOCCO](https://github.com/ersilia-os/ersilia/assets/22586210/7f6a2fa1-7fe4-4006-acb4-051027dba64b)
![C=CCOCCOC](https://github.com/ersilia-os/ersilia/assets/22586210/3e6306c7-084c-4702-bd1f-2f40ea445780)
![O=S(=O)(c1cccc2cnccc12)N1CCNCC1](https://github.com/ersilia-os/ersilia/assets/22586210/0797e689-7342-4409-b030-7ccf1d99c7cf)
![O=S(=O)(c1cccc2cnccc12)N1CCCN(c2ccccc2)CC1](https://github.com/ersilia-os/ersilia/assets/22586210/42507a61-4111-473b-bbf7-961e30b8f2d3)


To view more you can visit: https://github.com/ankitskvmdam/eos694w/blob/main/notebook/Playground.ipynb

**Comment by miquelduranfrigola** [comment]
Hello @ankitskvmdam this is going the right direction!

Generally speaking, output molecules are very similar to the input ones. This is OK, but it means we need to generate more candidates.

May I ask how many **unique** molecules are you able to generate, on average? Can we obtain ~100 molecules or so? If so, what is the computational cost?

Also, in the [notebook](https://github.com/ankitskvmdam/eos694w/blob/main/notebook/Playground.ipynb) I have noticed one instance where the output is **equal** to the input (second row of the image). In my opinion, we should discard these cases. So, we need to be sure that:
* All output molecules are different (similarity < 1) than the input.
* All output molecules are uniqut.
I hope this makes sense?

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola , 

Yes it makes sense.

I have updated the code, now we are only saving unique molecules.

I have also created a notebook to test the performance: https://github.com/ankitskvmdam/eos694w/blob/main/notebook/TestPerformance.ipynb

On average it generated 97 unique molecules (if we ask for 100). Sometimes it generates invalid molecule and sometimes molecule similar to the input, in both cases we are discarding them.

Also, on average it takes 33 seconds to generate 100 molecules.


Update the format in which we are writing the output. Visit https://github.com/ankitskvmdam/eos694w/blob/main/notebook/output/meph.smi to check. The format is as follows:

1. The first row is the header.
2. The second row is for generated smiles.
3. The third row is for input smiles.

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam,

The `TestPerformance.ipynb` notebook is perfect; very useful.

In the ouput file, we do not need the third row (input smiles repeated). We can talk about it later today. In the case of <100 unique molecules being generated, let's add empty values at the end until reaching the 100 columns.

In today's meeting, I suggest we do the following:
1. Make sure we have everything ready to incorporate model `eos694w` in the hub. I know you had issues with versioning, but @DhanshreeA and I will take care of it if necessary.
2. Evaluate critically the molecules generated.
3. Decide the next REINVENT model to include, hopefully adding more nuance to the task 😃

**Comment by ankitskvmdam** [comment]
Hi, @miquelduranfrigola,

Other Reinvent4 Models:

1. LibInvent: This model helps you find R-groups that can be attached to specific scaffolds. It requires one scaffold per line and each scaffold marked with two asterisks ("*") to indicate the attachment points. Example scaffold smile `[*:1]Cc2ccc1cncc(C[*:2])c1c2`
2. LinkInvent: This model helps you in identifying a linker or scaffold that can connect two different fragments. It requires each line to specify a pair of "warheads" separated by a pipe symbol ("|"). Each warhead needs to be marked with an asterisk ("*") to indicate the connection points. Example warhead smile: `Oc1cncc(*)c1|*c1ccoc1`
3. Molecular optimization: Mol2mol mmp, Mol2mol scaffold, Mol2mol scaffold_generic. All these models will generate new molecules similar to the provided molecules.

**Comment by ankitskvmdam** [comment]
Sure, I will explore them.

**Comment by miquelduranfrigola** [comment]
Perfect. The second most interesting one would be LibInvent. But for this, we'll have to:
1. Given a molecule, get its scaffold (using for example RDKit or Datamol)
2. Given a scaffold, identify its attachment points (i.e. the asterisk). @Inyrkz has done some interesting work on this, so I am looping him in.

**Comment by Inyrkz** [comment]
You may find something helpful [here](https://github.com/ersilia-os/eos8bhe/blob/main/model/framework/code/mol_gen.py)

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola, here is the [notebook](https://github.com/ankitskvmdam/eos694w/blob/explore-different-prior/notebook/Playground.ipynb) in which I explore `mol2mol_medium_similarity.prior` (for reference), `mol2mol_scaffold.prior` and `mol2mol_scaffold_generic.prior`

Performance:

|Model|Input Smile|Unique Model Generated|Loss|Time (in seconds)|
|-|-|-|-|-|
|`mol2mol_medium_similarity`|3|287|13|144|
|`mol2mol_scaffold`|3|280|20|46|
|`mol2mol_scaffold_generic`|3|257|43|43|

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola,

I have generated some molecules using `libinvent.prior`. 
On average it takes around 10 seconds to generate ~438 molecules (loss 62). 

![CCCH20CH20CCCCH1CH21CC1SC(O)NC1O](https://github.com/ersilia-os/ersilia/assets/22586210/7acfe8ef-116c-49bf-97eb-98ab35ae8984)
![COc1cccc(CCH20CH20c2ccc3cncc(CH21CH31)c3c2)c1](https://github.com/ersilia-os/ersilia/assets/22586210/3f3f38d5-8ac9-4db4-addb-04108bfa09a4)
![OC(NCCO)c1cccc(CH20CH20c2ccc3cncc(CH21c14ccccc4)c3c2)c1](https://github.com/ersilia-os/ersilia/assets/22586210/59b7c768-4fbd-4dce-b937-c595db0fb6bd)
![CCCH20CH20CCCCH1CH21CC](https://github.com/ersilia-os/ersilia/assets/22586210/dd14c6f2-d32c-4d87-babe-841cab562327)
![Cc1cc0(CH20c2ccc3cncc(CH21c14cccc(F)c4)c3c2)cc(C(O)O)c1OCc1ccccc1](https://github.com/ersilia-os/ersilia/assets/22586210/d2bc2747-b2f8-49b1-9422-b6b5b22af26e)

**Comment by DhanshreeA** [comment]
The model workflows, including the docker build work. Okay to close this now? @miquelduranfrigola @ankitskvmdam

**Comment by ankitskvmdam** [comment]
@DhanshreeA Reinvent4 has one more  interesting model/prior which we want to incorporate.

So far we have added/created pr to incorporate three models/priors. 

So, I think we can keep this open for now.

**Comment by miquelduranfrigola** [comment]
Hi @ankitskvmdam the LibInvent predictions are very interesting.
The key here is to generate the scaffolds with the * in a robust way. I assume you've used @Inyrkz's approach?
Let's discuss this in our meeting. Great stuff.

**Comment by ankitskvmdam** [comment]
@miquelduranfrigola, I am exploring his approach to find the scaffold. The above shared result I got but explicitly providing attachment points.

I have using this notebook to explore how to extract core structure of a given molecule: https://github.com/ersilia-os/eos2401/blob/main/model/framework/code/scaffold_decorator.ipynb

This one is shared by @Inyrkz (Thanks!)

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam - let's start with this approach or a variation of it.

**Comment by ankitskvmdam** [comment]
@miquelduranfrigola I did some experiments to extract the scaffold of the given molecule and add attachment points to it. 


#### Notebook

Link to the notebook: [Google Colab Notebook](https://colab.research.google.com/drive/1BaZ2lSWsZwJg3yZbWpDKKJJAhN-SPi_y#scrollTo=ZXKqgQbD2I9b). Could you kindly review the logic implemented there?

#### Result

![CCOCC](https://github.com/ersilia-os/ersilia/assets/22586210/ec2c80b5-43b4-4989-be45-f52a0454ce41)
![CO](https://github.com/ersilia-os/ersilia/assets/22586210/d2d68e3f-4906-49cf-b54d-1af51be57055)
![OC=O](https://github.com/ersilia-os/ersilia/assets/22586210/817dd14c-28da-4392-89f2-0503a9a7bc09)
![c1ccccc1](https://github.com/ersilia-os/ersilia/assets/22586210/02ba107f-040c-4ecf-8d73-3df749c0e697)
![CC(C)(C)C1=CC(O)=CC=C1O](https://github.com/ersilia-os/ersilia/assets/22586210/9646a97f-c75b-4d09-a3f6-53e5cbd4493a)
![CC(C)(C)c1nc(c(s1)-c1ccnc(N)n1)-c1cccc(NS(=O)(=O)c2c(F)cccc2F)c1F](https://github.com/ersilia-os/ersilia/assets/22586210/df8925ec-346a-4eff-b09c-1315fd0b8fce)

**Comment by miquelduranfrigola** [comment]
Hello @ankitskvmdam ,

I have revised the notebook. It looks pretty good! Let's go ahead with this solution. I would say that, for each molecule, we should try to get at least 3 pairs of linking points, and then, for each pair of linking point, we can generate 200 derivatives. How does this sound? This should give us up to 600 molecules per input. Feel free to suggest other options, especially if generation takes too long.

Thank you so much!

**Comment by ankitskvmdam** [comment]
Here is my proposal, hope it will make sense. I am thinking to target 1000 new molecules.

We can first find all the potential attachment points, In the example molecule (shown below), there are 13 such points.

![CC(C)(C)c1nc(c(s1)-c1ccnc(N)n1)-c1cccc(NS(=O)(=O)c2c(F)cccc2F)c1F](https://github.com/ersilia-os/ersilia/assets/22586210/1f7ad28b-64f8-47ed-b41e-9cb22bac9603)

Initially, we can pick each attachment point and target to generate at least 300 new molecules. Roughly 25 per attachment point according to current example. If we have more or less then we can adjust the number of new molecules per attachment point.

After that, we pair wise.  we can try to find 600 new molecules using all the pairs. According to our example we can have 156 unique pair, meaning 4 molecules per pair. 

Same we can do for triplets. At this point we first calculate the actual number of outputs (I noticed almost 30 to 40% of the output molecules for some molecule are invalid). Assume so far we have actually generated 700 molecules (77% of 900). So for triplet we can target around 500 new molecules in the hope that it could generate 300 new molecules.

Why 1000 molecules?

I generated 500 molecules using libinvent, and it was quick. I will do more performance testing, and If generating 1000 molecules proves to be computationally inefficient then we can adjust the target.

**Comment by miquelduranfrigola** [comment]
This makes a lot of sense, @ankitskvmdam - please go ahead with your suggested approach, as long as timing is reasonable.

To test robustness, I would suggest that you try a few edge cases, such as very simple molecules where one or even none attachment point is available.

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola ,

I created a notebook to test the robustness of the approach. Here is the [notebook](https://github.com/ankitskvmdam/REINVENT4_NOTEBOOK/blob/master/notebooks/Scaffold_new.ipynb). At the end of the notebook, I printed the number of molecules I would like to generate using LibInvent.

I have also tested generating molecules using this approach, and it is not taking much time.

**Comment by miquelduranfrigola** [comment]
Awesome, thanks. Let's discuss in our meeting

**Comment by miquelduranfrigola** [comment]
@ankitskvmdam I have checked the notebook and it generally looks very good. The number of molecules to be generated is very reasonable too.

**Comment by ankitskvmdam** [comment]
@miquelduranfrigola Thanks! Should I proceed with this approach? Should I open a model request?

**Comment by miquelduranfrigola** [comment]
Yes please open a model request and we proceed like this

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola !

I experimented with REINVENT's linkinvent. My findings:

1. The output count varies inconsistently. While attempting to generate 500 new molecules, the results ranged from approximately 100 to 400. This variability seems to be due to the position of attachment points in warheads.
2. It is feasible to specify two or three warheads. However, when providing three warheads along with random attachment points, the output yields only around 3 or 4 new molecules, even when requesting 1000 new molecules. This discrepancy might be attributed to incorrect combinations of warheads.
3. In ideal case it takes 40 seconds to generate 500 new molecules.

The challenging part is extracting warheads from an input SMILES string. I'm not sure how to do this, particularly because certain molecules, such as benzene, serve as a scaffold for the entire structure, complicating the extraction of warheads or even impossible. Ideally, if users could provide the warheads themselves, the process would be considerably more straightforward.

Below are some input-output examples for reference.

![OC(NC(C)(C)C)C(O)NC(C1N2C(CC1)C(C(NC(C)C(O)C(O)N)O)C2O)n1cc(O)cc()c1_C(O)CSC](https://github.com/ersilia-os/ersilia/assets/22586210/08271a27-3985-4488-9242-d5f855dfdc09)



![CC(NC(c1nc()sc1)O)(C(O)N1C(C(O))C(C)(C)SC1)C(C)(C)Cn1cc(O)cc()c1_C(O)CSC](https://github.com/ersilia-os/ersilia/assets/22586210/77ce6fb8-324f-449e-b594-602aca287b08)

![CCNC(N1C(Cn2nc(Cl)c3nc()nc_3c2)CC2C1CC2)Oc1c()cncc1O_o1ccc()c1](https://github.com/ersilia-os/ersilia/assets/22586210/f680cc24-ec78-4b32-8874-a9d47866ce00)

![C1(CCN)(n2cc(C(N)O)c(N)n2)CN(C(C)C)C1c1c()cncc1O_o1ccc()c1](https://github.com/ersilia-os/ersilia/assets/22586210/885a3bb0-a488-428b-a011-cc97f946842f)

![C1CCC(C(NC(O)C2NCCC2)Cc2ccc(OCCc3c(C)oc(C)n3)cc2)N1C(C(C(C)(C)C)NC()O)Oc1(O)cncc()c1_CSCCO_OC](https://github.com/ersilia-os/ersilia/assets/22586210/c9334033-d168-4e85-9873-cd8d2b028653)

![c1(O)n(C)c(C(C(C)C)NC(O)C)nc2c1cc()cc2c1(O)cncc()c1_CSCCO_OC](https://github.com/ersilia-os/ersilia/assets/22586210/a9c4ca2a-0e0e-44bd-b50c-3d9e8e641a0d)

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam this is very helpful.

I agree that allowing for warhead specification would be helpful. In that case, I suggest we do as we did before with libinvent: if users specify warheads (using the asterisk), then we use them. The way to specify more than one warhead could be via the dot symbol. For example: `CCC*.CCO*`. The dot is accepted as a separator for SMILES strings.

In any case, the linkers that we get are actually quite large, resulting in very large moelcules... Two questions: 
1. Is the size of the linker smaller if the warheads are bigger?
2. Is there a way to ask REINVENT to penalize molecules that are too large?

As for extraction of warheads, I agree it can be tricky or even impossible at times. Generally, the warheads that we are finding (according to your figure) are quite small. I would generally prefer the warheads to contain at least one ring (ideally more). Do you think this library could be helpful to select warheads? https://github.com/UCLCheminformatics/ScaffoldGraph I might have mentioned it already. My intuition would be that, starting from "level 2" of the scaffold network, we will start having big enough warheads.

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola,

Yes, I will proceed with the same approach as I used for libinvent. 

1. I need to check whether there is any correlation between warheads size and linker size. However, I guess the size of the linker is random.

2. I believe there's no way to penalize REINVENT. We are simply passing in the input warheads for which we want the linker and REINVENT returns output molecules all at once.


I think we can use the tool (Scaffold Graph) to get the warheads. I will create an example using the tool.

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam . Let's proceed as you suggest!

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola 

Here is the result when I provided little bit bigger warheads.

![1715619818 7690287](https://github.com/ersilia-os/ersilia/assets/22586210/723aadbc-410a-4f0b-8054-8475f3d98645)

![1715619821 740518](https://github.com/ersilia-os/ersilia/assets/22586210/bd71c05e-f423-4162-930a-0db6381bb650)

![1715619827 3184965](https://github.com/ersilia-os/ersilia/assets/22586210/6e56b981-67af-4bbb-8ca5-2f212938aaf6)

![1715620022 0696263](https://github.com/ersilia-os/ersilia/assets/22586210/e676f438-9ea1-45a5-be9c-eb5c206315e1)

![1715620028 5311615](https://github.com/ersilia-os/ersilia/assets/22586210/f2436f6a-b3e4-4acb-9043-d93dd5f5d04b)

![1715620034 4487696](https://github.com/ersilia-os/ersilia/assets/22586210/8be75234-66c2-4d66-8292-7f20fb626e36)


The size of linker is random. Also, I went through REINVENT's code around Sampling, and didn't find any option to specify linker size.

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam I thinks this is overall very interesting, and we are ready to wrap it up, in my opinion. Based on what I am observing, these cases might be interesting for bifunctional molecules like PROTACS. Great work.
Tomorrow we can discuss it in detail.

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola,

Over the weekends, I worked extracting the warheads from using the input smiles. You can find the notebook [here](https://colab.research.google.com/drive/12v9CRJtzO8X3KkfCQ9NdEXznQ6ZZmOrp?usp=sharing).

Here is the output from the notebook.

![image](https://github.com/ersilia-os/ersilia/assets/22586210/e35b88c9-5509-4070-b580-6cc749b04fe6)

![image](https://github.com/ersilia-os/ersilia/assets/22586210/955ad288-dc4d-4dc5-bb8c-c2eb85da56ff)

![image](https://github.com/ersilia-os/ersilia/assets/22586210/38bb3076-5a97-4a2d-8c5c-25bdec9a1d31)

![image](https://github.com/ersilia-os/ersilia/assets/22586210/0ff36744-cedc-4641-bd32-10b585fded87)

![image](https://github.com/ersilia-os/ersilia/assets/22586210/3a9af6c8-6c50-44ef-8708-df10c2797259)

![image](https://github.com/ersilia-os/ersilia/assets/22586210/24a9e0af-e441-49ef-a339-2b3550a39504)

**Comment by miquelduranfrigola** [comment]
Hey @ankitskvmdam this perfect. Is it deterministic or you can get more than one pair? Both options would be fine.

**Comment by ankitskvmdam** [comment]
We can obtain more than one pair if the molecule is large/contains numerous fragments. However, in the notebook, we are only selecting the pair that possesses the highest molecular weight, which implies it will be deterministic.

**Comment by miquelduranfrigola** [comment]
@ankitskvmdam I am closing this issue since now we are mostly working on REINVENT with 3D shape similarity (https://github.com/ersilia-os/ersilia/issues/1128). Please feel free to reopen the issue as you see fit.
