### ISSUE TITLE
:bug: Unnecessary `.gitbook.yaml` file in Ersilia?

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#945]
I have noticed a `.gitbook.yaml` file in Ersilia's root. It refers to a (now inexistent) `.book` folder.
I don't think we are synchronizeing GitBook to the Ersilia repo. Are we, @GemmaTuron ? If not let's remove this file.

**Comment by GemmaTuron** [comment]
I think we can delete it

**Comment by miquelduranfrigola** [comment]
Done
