### ISSUE TITLE
[Spike]: Create a :bulb: Model Idea template

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#948]
Current Model Requests are great to incorporate models for which we already have relatively deep knowledge. However, sometimes we just want to make a quick model suggestion and start a discussion around the model.

I would suggest a simple template that accepts:

1. A quick description of the model.
2. Up to 3 links to code and publications.

We currently lack a comfortable way of keeping a backlog of models. This system may help in this direction.

Please le me know what you think.

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 

Isn't this repetitive with what we have in Airtable?

**Comment by miquelduranfrigola** [comment]
Yes, but in this way everybody could contribute ideas, and discussion could happen around the model could happen inside the issue (before incorporation), which is not somehting we can do using Airtable or Slack.

**Comment by jona42-ui** [comment]
This is efficient for model selsction process

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola 
I really not think opening more issues in ersilia will be helpful. Typically people who want a model will contact us via email or slack, so we might want to keep these communication channels only?

**Comment by DhanshreeA** [comment]
We discarded this idea a while ago, @GemmaTuron. I am closing this issue.
