### ISSUE TITLE
🐕 Batch: Improve Ersilia's Open Source Community documents

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#949]
### Summary
According to [these guidelines](https://socialimpact.github.com/developers/intro-to-open-source/) from GitHub we should have a `CONTRIBUTING.md` and `DEVELOPMENT.md` file in our repository.

### Documentation

**Comment by jona42-ui** [comment]
hello @miquelduranfrigola @DhanshreeA 
I can work on this, I am not sure if its an administrative task.
But i have an ask, will this not be a duplication of the dev and contribution manuals already  existent or we just need to keep everything in one place(repo)?

Thamks

**Comment by anshikavashistha** [comment]
May I work on this @miquelduranfrigola @DhanshreeA?

**Comment by miquelduranfrigola** [comment]
@DhanshreeA feel free to decide - in my opinion this is low priority at the moment but I'll follow your lead here.

**Comment by DhanshreeA** [comment]
Hi both @jona42-ui and @anshikavashistha, thank you for offering to help. Sure, we can revisit this issue as part of your Outreachy contribution once the existing tasks are finished, and we still have time remaining. :)

**Comment by DhanshreeA** [comment]
> hello @miquelduranfrigola @DhanshreeA I can work on this, I am not sure if its an administrative task. But i have an ask, will this not be a duplication of the dev and contribution manuals already existent or we just need to keep everything in one place(repo)?
> 
> Thamks

Hi @jona42-ui this is more along the lines of supplementing what we currently have to make it more exhaustive and Ersilia specific, rather than general contribution and development guidelines.

**Comment by jona42-ui** [comment]
hello @DhanshreeA 
I think it's time I embark on this. Feel free to sign me this if it's okay.
For first spec, I would ask for specific requirements of the CONTRIBUTING.md and DEVELOPMENT.md files as AirTable contains quite alot.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Is this done?

**Comment by GemmaTuron** [comment]
Hello!

This Batch remains open for working on Ersilia's documentation. Please, only tackle it if you have already installed Ersilia and completed minimum one contribution to the code, so you can write with knowledge. Related to this batch, there are two tasks:

- [ ] Improve the CONTRIBUTING.md file
- [ ] Create a DEVELOPMENT.md file following best practices set out by GitHub

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron I do not understand the last objective, what would this look like? If you could point me somewhere that would be helpful!

**Comment by GemmaTuron** [comment]
Sorry I had not updated the tasks. the third one is on my, I have not converted it in an issue because I think is unnecessary given the number of issues open and that I alone will complete it. I'll mark it here when done

**Comment by KimFarida** [comment]
I have a quick question concerning documentation please @DhanshreeA @GemmaTuron according to thr handbook you must've actually contributed to an issue in general to contribute to the docs, just confirming if I understand that correctly

**Comment by DhanshreeA** [comment]
@KimFarida that's correct!

**Comment by aderemi1224** [comment]
@DhanshreeA please can this be assigned to me once my PR has been merged

**Comment by KimFarida** [comment]
@DhanshreeA is this still up for the taking?
Saw you merged my PR so i can work on something else. Thank you so much 😊

**Comment by DhanshreeA** [comment]
Hi @aderemi1224 this is an umbrella issue that has [two components](https://github.com/ersilia-os/ersilia/issues/949#issuecomment-2370453409) as you can see in the linked comment - the Development.md and Contributing.md, and both of those individual issues are already being worked upon by @adebisi4145 and @Ajoke23. I would suggest you to pick another issue.

**Comment by aderemi1224** [comment]
@DhanshreeA Noted. Thank you

**Comment by GemmaTuron** [comment]
This has been completed
