### ISSUE TITLE
Improve catalog by including model size in "ersilia catalog" output

### ISSUE THREAD

**Issue by Amna-28** [ersilia-os/ersilia#95]
**feature request :** Improve catalog by including model size in "ersilia catalog" output. A Column displaying model size against each model would help the user to get an idea of the amount of time it will take to download, also the user would get to know how much space is required in the disk. 
**Problem :** while working on the issue #8 , I had to test the deletion of models. for which I had to download a couple of models. I was looking the models that require the least space on disk so that the testing would take lesser time, but there was no mechanism of finding that out before running the fetch command.
**Alternatives :** 
- A column of model size could be added to the "ersilia catalog" command's output
- An additional option could be added to the catalog command such as "ersilia catalog --size" that would print the catalog differently (including the size information)
- A webpage could open to display the catalog to include the model size (this idea was also mentioned in another issue)

![image](https://user-images.githubusercontent.com/98670206/161425392-ff19b450-b0b3-4439-832c-3536ead11746.png)

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola , I would like to work on this issue.

**Comment by miquelduranfrigola** [comment]
Hi @Amna-28 this is great.

I like the `ersilia catalog --size` option. Let's go for it.

At the moment, we have an airtable base, so perhaps it is not urgent to display yet another website https://airtable.com/shrUcrUnd7jB9ChZV/tblZGe2a2XeBxrEHP

**Comment by Amna-28** [comment]
Hi @miquelduranfrigola just saw your comment, thank you for assigning me the task.
As far as I have looked up on the internet, there is no way to pre-determine the size of git-lfs repo. The recommended way is to clone the repository and then find its size.
In my understanding, the fetched models are being downloaded in the **_eos_** directory. 
I have run the comman `du -h --max-depth=1 </path/to/eos/directory>` for which I get the following output: 

![image](https://user-images.githubusercontent.com/98670206/162639277-20185146-2164-4c6a-babf-1d988a902e1d.png)

What we can do is download all the models available in ersilia hub and determine the size, store the sizes in a file and make use of the file while displaying the catalog. What do you say?
Please guide me if this is not the right way.

**Comment by miquelduranfrigola** [comment]
Hi @Amna-28 thanks for your comments, all well noted! Indeed, Git LFS does not easily allow for getting model size. Please see issue https://github.com/ersilia-os/ersilia/pull/188 where we are trying to estimate time to fetch a model. The same approach can be used to get model size, i.e. we just need to store model size in the metadata file.

I am closing this issue now since I feel that issue https://github.com/ersilia-os/ersilia/pull/188 provides a good solution. Feel free to jump in at any stage!

**Comment by Amna-28** [comment]
Sure, thank you @miquelduranfrigola , I would be pleased to contribute to issue #188
