### ISSUE TITLE
🦠 Model Request: Cytotoxicity in HepG2, HSkMC and IMR-90

### ISSUE THREAD

**Issue by Richiio** [ersilia-os/ersilia#955]
### Model Name

Human cytotoxicity endpoints

### Model Description

The authors tested the dataset of 39312 compounds from the antibiotics-ai model (eos18ie) against several cytotoxicity endpoints; human liver carcinoma cells (HepG2), human primary skeletal muscle cells (HSkMCs) and human lung fibroblast cells (IMR-90). Cellular viability was measured after 2–3 days of treatment with each compound at 10 μM, and activities were binarized using a 90% cell viability cut-off. 3,341 (8.5%), 1,490 (3.8%) and 3,447 (8.8%) compounds classified as cytotoxic for HepG2 cells, HSk-MCs and IMR-90 cells.

### Slug

antibiotics-ai-cytotox

### Tag

Cytotoxicity

### Publication

https://www.nature.com/articles/s41586-023-06887-8

### Source Code

https://github.com/felixjwong/antibioticsai

### License

MIT

**Comment by Richiio** [comment]
@miquelduranfrigola Does this description look good?

**Comment by GemmaTuron** [comment]
I have modified the description and tags, here we are not doing anything related to antibiotics, only cytotoxicity.
I have left the slug as the eos18ie adding the cytotox part so we easily identify these models are related. Please make sure @Richiio that the versions of packages are exactly the same between this model and the antibiotic one.

**Comment by GemmaTuron** [comment]
@Richiio 

In this case we want to incorporate three models, please make sure to reflect appropriate names on the headers of the output, so the user knows what is each column.
Thanks!

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Please first finish editing the model Dockerfile (specify ALL versions of packages) and try:
- Codespaces
- Local run from --repo_path
Before making a PR

**Comment by Richiio** [comment]
@GemmaTuron @miquelduranfrigola @HellenNamulinda 

The antibiotics model successfully uploaded to dockerhub with 20 checkpoints having a size of ~888MB. This model has 60 checkpoints having a size ~2,7GB. When making a PR, should I make use of the 60 checkpoints or have a total of 45(15 per model)

**Comment by GemmaTuron** [comment]
Hi @Richiio try locally first and let's see if it works, as hellen did.
Make sure to add the edited version of the workflow file to the repository for it to work

**Comment by HellenNamulinda** [comment]
@Richiio,
- In the pull request, https://github.com/ersilia-os/eos42ez/pull/2,  You mentioned that you created a scatter plot. Can we have a look.

@GemmaTuron, how about having a separate model for each human cell. 
I understand the best implementation is to have all of them as one one model. but given the large number of model checkpoints, isn't it resource intensive?

**Comment by GemmaTuron** [comment]
This model is  incorporated with fewer checkpoints than originally trained - we will need to think about what to do with these issues when we face large models!

**Comment by GemmaTuron** [comment]
The models are incorporated with 11 checkpoints each, thanks @Richiio !
