### ISSUE TITLE
Dili model validation

### ISSUE THREAD

**Issue by leilayesufu** [ersilia-os/ersilia#956]
### Summary

Compare performances of the dili models within the ersilia model hub using an unbiased dataset obtained from the literature

### Scope

Batch 🐕

### Objective(s)

- Build a dataset that contains dili positive and negative data (from ChEMBL for example)
- Check if the molecules we will use for testing have been used in the training of the dili Models in the Hub
- Test all the dili models in the Ersilia Model Hub with the dataset and compare performances

### Team

| Role & Responsibility | @leilayesufu ) | 
|--|--|
| Mentor | @DhanshreeA  |
| Project Manager | @gemmaturon |

**Comment by leilayesufu** [comment]
@GemmaTuron I am awaiting for feedback on this dili model. [eos21q7](https://github.com/ersilia-os/ersilia/issues/947)

For our test dataset, @DhanshreeA recommended using the [FDA Drug Induced Liver Injury Rank (DILIrank) Dataset](https://www.fda.gov/science-research/liver-toxicity-knowledge-base-ltkb/drug-induced-liver-injury-rank-dilirank-dataset), which includes the [DILIrank-DILIscore_List.xlsx](https://github.com/ersilia-os/ersilia/files/14178146/DILIrank-DILIscore_List.xlsx). This dataset categorizes drugs into three groups based on their DILI concern level: vMost-, vLess-, and vNo-DILI concern.

To streamline our analysis, we plan to assign a rating of 1 to drugs with the most or less DILI concern, and 0 to those with no DILI concern. We'll then convert the common names of these drugs to SMILES notation to utilize them as our test dataset since the tdc dili dataset has almost all drugs in common with the training set.

**Comment by GemmaTuron** [comment]
Hi @leilayesufu 

I have added feedback, I am sorry but I think more work is needed. The DILIrank, if I am not confused, is part of the model already, which uses 5 datasets

**Comment by GemmaTuron** [comment]
Hi @leilayesufu !

I'll close this issue as we will centralise all these tests via #966
