### ISSUE TITLE
🦠 Model Request: REINVENT 4 Mol2MolMediumSimilarity

### ISSUE THREAD

**Issue by ankitskvmdam** [ersilia-os/ersilia#957]
### Model Name

REINVENT 4 Mol2MolMediumSimilarity

### Model Description

The Mol2MolMediumSimilarity model is one of the models within REINVENT 4 used to find new molecules similar to the provided molecules.

### Slug

reinvent4-mol2mol-medium-similarity

### Tag

Similarity

### Publication

https://chemrxiv.org/engage/chemrxiv/article-details/65463cafc573f893f1cae33a

### Source Code

https://github.com/MolecularAI/REINVENT4

### License

Apache License 2.0

**Comment by miquelduranfrigola** [comment]
Hi @ankitskvmdam - Thanks for the model request. Please let me know if you have any questions!

**Comment by ankitskvmdam** [comment]
Hi @miquelduranfrigola, 

Sure I will let you know if I have any questions.

**Comment by ankitskvmdam** [comment]
@miquelduranfrigola I think we can close this Request. 
Ref: https://github.com/ersilia-os/eos694w

**Comment by miquelduranfrigola** [comment]
Thanks @ankitskvmdam ! @GemmaTuron can you test this model in hte context of ChemSampler maybe? Then we can close the issue.

**Comment by GemmaTuron** [comment]
Update

@miquelduranfrigola and @ankitskvmdam I have not had yet time to test the model within chemsampler, but the model does work. Can I close this issue? If there is concerns when I run chemsampler I'll open an issue on the model repo itself
