### ISSUE TITLE
🦠 Model Request: ADMET AI

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#958]
### Model Name

ADMET properties prediction

### Model Description

Fast batch prediction of ADMET properties for small molecules

### Slug

admet-ai-prediction

### Tag

ADME,Toxicity

### Publication

https://www.biorxiv.org/content/10.1101/2023.12.28.573531v1

### Source Code

https://github.com/swansonk14/admet_ai

### License

MIT

**Comment by DhanshreeA** [comment]
Additional details here: https://github.com/ersilia-os/ersilia/issues/954

**Comment by DhanshreeA** [comment]
@miquelduranfrigola https://github.com/ersilia-os/eos7d58/pull/1 please review/approve. It's ready.

**Comment by GemmaTuron** [comment]
This model is incorporated!
