### ISSUE TITLE
🐛 Bug: `/approve` command triggers workflows outside the "Model Request" issue template 

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#962]
### Describe the bug.

The `/approve` command triggers workflows to create a model repository when an Ersilia Maintainer approves a model request issue. This workflow runs every time a user (possibly only Ersilia maintainers) comment on any issue within this repository, whereas this workflow should be triggered only when the related issue is a "Model Request" issue.

This is a good first issue and provides a starting point for learning more about GitHub actions. The workflow being referenced is implemented [here](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/approve-trigger.yml). 

This can potentially be fixed by making the job within this workflow execute conditionally based on the issue label. You can find an example [here](https://github.com/ersilia-os/ersilia-self-service/blob/2d8f19d4532357743c7fb6ccf319e7d92a78e84c/.github/workflows/self-service.yml#L8).

### Describe the steps to reproduce the behavior

You can see the number of times this action has run where it was not relevant [here](https://github.com/ersilia-os/ersilia/actions/workflows/approve-trigger.yml). 

To reproduce this issue yourself, please open an issue, and tag one of the maintainers to comment on it. Once a maintainer comments on it, the workflow will be triggered.

### Expected behavior.

One possibility would be to modify the first triggered action to check for a `new-model`, as suggested by @GrantBirki . 

To make sure the implemented fix works, please tag a maintainer to post a comment on an issue and verify if the workflow no longer gets triggered. 

### Operating environment

Ubuntu 20.04 LTS

**Comment by GemmaTuron** [comment]
Is this a persisting issue? seems quite straightforward to fix. Perhaps a good first issue?

**Comment by DhanshreeA** [comment]
I agree - straightforward. We simply need to add a label filter in this [workflow](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/approve-trigger.yml), like we have it in [ersilia-self-service](https://github.com/ersilia-os/ersilia-self-service/blob/2d8f19d4532357743c7fb6ccf319e7d92a78e84c/.github/workflows/self-service.yml#L8).

**Comment by Ajoke23** [comment]
Hi @DhanshreeA. Could you please assign me this task?

**Comment by DhanshreeA** [comment]
@Ajoke23 we need to close your current PRs first before assigning more issues to you. :)

**Comment by Ajoke23** [comment]
> @Ajoke23 we need to close your current PRs first before assigning more issues to you. :) 

No problem @DhanshreeA. Please have a lot at pull request #1286

**Comment by aderemi1224** [comment]
@DhanshreeA I am done with my first task, can you please assign this to me?

**Comment by DhanshreeA** [comment]
@aderemi1224 go ahead!

**Comment by aderemi1224** [comment]
Thank you @DhanshreeA

**Comment by Ajoke23** [comment]
Hi @aderemi1224. Any progress with this issue?

**Comment by aderemi1224** [comment]
Yes please @Ajoke23

**Comment by Ajoke23** [comment]
Can you share what you have done so far so that I can know how to be of assistance to you?
> Yes please @Ajoke23 
>

**Comment by dzumii** [comment]
Hi @aderemi1224 can you share your progress with us on this issue?

**Comment by aderemi1224** [comment]
@dzumii i got stuck but know my around to solve the problem now.

**Comment by Ajoke23** [comment]
I saw your message on slack now saying you are getting error

**Comment by aderemi1224** [comment]
Triggering the approve workflow

**Comment by seunbayo** [comment]
@DhanshreeA  @miquelduranfrigola

**Comment by aderemi1224** [comment]
@DhanshreeA i have made the changes requested

**Comment by aderemi1224** [comment]
@DhanshreeA i have made the changes.
