### ISSUE TITLE
🐛 Bug: Failed to fetch eos42ez model

### ISSUE THREAD

**Issue by Richiio** [ersilia-os/ersilia#972]
### Describe the bug.

The model doesn't fetch at all on both codespace and on my local. On codespaces, I get a space pop-up and it remains stuck on fetching for over 2hours. On my local machine, it starts with fetching and the model's slug name, and remains stuck.

### Operating environment

Ubuntu 22.04

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Please update us on the issue with this model, which worked fine for me before

**Comment by Richiio** [comment]
Hi @GemmaTuron I'll try fetching this model again but when I tried fetching on Friday, it still took a long time at fetching antibiotics-ai

**Comment by GemmaTuron** [comment]
Hi @Richiio 

I just want to confirm that the issue was on your end, before trying fetching again (it has consumed almost 100 GB of GitLFS) can you clarify what the popup said?

**Comment by Richiio** [comment]
Not enough memory or space

**Comment by GemmaTuron** [comment]
Then it is simply an issue on your end not related to the model, so I'll close this issue. 
Let's leave this here as today is the last day of the internship and Ersilia team will take it from here. Remember for future projects that you can always leverage cloud space like google or codespaces to save internet and space in your local systems :)

**Comment by Richiio** [comment]
@GemmaTuron 
This was on codespaces though

**Comment by GemmaTuron** [comment]
oh that is surprising.. we might be hitting the limit of the free codespaces plan? I'll ping @DhanshreeA here so that we are aware of this.

**Comment by DhanshreeA** [comment]
Going to reopen this so we can validate it at least once and see what's happening.

**Comment by DhanshreeA** [comment]
Can confirm, this works just fine. Might have been a fluke issue back then.
