### ISSUE TITLE
🐛 Bug: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#976]
### Describe the bug.

Got this error during ersilia python package installation

`error:RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 2677 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output ` 

### Describe the steps to reproduce the behavior

`git clone https://github.com/ersilia-os/ersilia.git` 
### Expected behavior.

Creates a copy of Ersilia repository on my local machine

### Screenshots.

![Capture1](https://github.com/ersilia-os/ersilia/assets/46167222/1f00fc52-35f3-4c42-9cd9-ce96f43eb35e)

### Operating environment

Ubuntu 22.04.1

**Comment by Malikbadmus** [comment]
I updated all the packages and dependencies  in the Conda environment and the Issue was resolved.

Ersilia Installed Successfully

![see](https://github.com/ersilia-os/ersilia/assets/46167222/0ad959a5-c9fe-4f43-82b0-f5d5390ea6a1)

**Comment by DhanshreeA** [comment]
Thank you for the update @Malikbadmus, I am marking this issue as resolved.
