### ISSUE TITLE
Outreachy Documentation Project: Dennis Onyeka / dchidindu5

### ISSUE THREAD

**Issue by dchidindu5** [ersilia-os/ersilia#98]
Applicant: < @dchidindu5 >
  
Welcome to the Ersilia Open Source Initiative. This issue will serve to track all your contributions for the project “Improve the documentation and outreach material of the Ersilia Model Hub”.
  
Please tick the tasks as you complete them. To make a final application it is *not* required to have completed all tasks. Only the *Initial Steps* and *Community* sections are REQUIRED. The tasks are not ordered from more to less important, they are simply related to different skills. Start where you feel most comfortable. This project can be adapted to the applicants interests, please focus on the type of tasks that you prefer / have better skills / would like to work on as an intern.

---
### Initial steps:
- [x] Record your application for the project in the outreachy website referencing this issue. Please make sure to select the right project on the website.
- [x] Join the Slack channel to follow public communications
- [x] Comment under this issue explaining why are you interested in this project
---
### GitHub documentation:
- [x] Create a README file with the name <README_yourname.md> under the /documentation folder
- [x] Link the #PR in a comment under this issue
- [x] Incorporate feedback from the mentor
---
### Writing dissemination material
- [x] Read the [Strategic plan 2021-2023](https://ersilia.gitbook.io/ersilia-wiki/) for Ersilia and create a 1-page blogpost with the main points
- [x] Comment under this issue with a link to the blogpost (a google docs for example)
- [x] Incorporate feedback from the mentor
- [ ] Choose your own topic related to Ersilia (AI/ML for biomedical research, neglected diseases, drug discovery…) and write a 1-page blogpost to communicate to a non-expert audience
- [ ] Comment under this issue with a link to the blogpost (a google docs for example)
- [ ] Incorporate feedback from the mentor
- [x] Create a template for a twitter post to release every time a new model is incorporated in the Hub (twitter: 280 characters, you can suggest a main post +  thread with extra information) and add it as a comment under this issue
- [ ] Create a template short Newsletter (1 paragraph) to send every month to our community (funders, users, contributors). It should mention metrics (models in the hub, number of users, funding…), thank you etc 
---
### Technical skills (required for the tutorial only)
- [x] [Install](https://ersilia.gitbook.io/ersilia-book/quick-start/installation) the Ersilia Model Hub
- [ ] Test one model
- [ ] Add a screenshot under this issue showing the model running in your computer
- [ ] Write a docstring for the ErsiliaModel class. Use the Google Python Style guide. Paste the docstring as a comment below (do not use a PR).
---
### Graphic material
- [x] Read the [Ersilia Brand Guidelines](https://medium.com/ersiliaio/ersilia-open-source-initiative-brand-guidelines-130fe53104f5)
- [x] Read [“Why Ersilia?”](https://ersilia.gitbook.io/ersilia-wiki/)
- [x] Create one image / slide to explain Ersilia’s mission and vision
- [x] Link to the image/slide as a comment under this issue
- [x] Incorporate feedback from the mentor
- [ ] Create two slides / short video showing how to use the Ersilia Model Hub and add them under the /tutorial folder 
- [ ] Link the #PR in this issue
- [ ] Incorporate feedback from the mentor
---
### Scientific content
- [ ] Check the models available in the [Hub](https://airtable.com/shrXfZ8pqro0jjcsG/tblZGe2a2XeBxrEHP/viwd5XJVLslkE11Tg)
- [ ] Select one model from the list and write a technical card (what is the model for, what input, which data was used to create it, what kind of ML algorithm uses…) for it
- [ ] Add your card as a comment to this issue
- [ ] Search the scientific literature and suggest 3 new models (comment in this issue) that would be relevant to incorporate in the Hub.
---
### Community
- [x] Look up two other projects and comment on their issues with feedback on one of their tasks
- [x] If you have feedback from your peers, answer it in this issue.
---
### Other
If you have interest in working on related topics, or have new suggestions, please do the following
- [x] Add a comment in this issue with your new idea, tagging the mentor 
- [x] Get feedback from the mentor and act accordingly
- [x] Link in the comments any other PR you have contributed to.
---
### Final application
- [x] I have answered all comments from mentors and contributors
- [x] All PR or issues assigned to me are complete
- [x] I have submitted my final application to the project

**Comment by dchidindu5** [comment]
Why I am interested in Ersilia?

Ersilia Model Hub is a free, open-source repository of Artificial Intelligence and Machine Learning (AI/ML) models for drug discovery.
 I'm an open source advocate though till new to the space, my passion for open source has given me the opportunity to participate and to contribute meaningfully to Ersilia to ensure remarkable breakthrough in the field of medicine.

**Comment by dchidindu5** [comment]
@GemmaTuron As regards to the previous issue I posted concerning Specifying in details the two conda distribution packages that should be outlined in the "Ersilia Installation Guide" to enable users make their choices in installation''.
Can I still go with the task?
I've already written the documentation in collaboration with my assigned contributor.

**Comment by GemmaTuron** [comment]
Hi @dchidindu5 
yes please go on with it and tag it here in a comment when its completed so I can revise and provide feedback!
thanks

**Comment by dchidindu5** [comment]
### Which should you choose?

**Minconda OR Anaconda**

> Note:

 Conda is the package manager (i.e. it displays all the installed packages in the environment.)
Whereas Anaconda and Miniconda are distributions (i.e. they are collection of packages, pre-built and pre-configured, that can be installed and used on a computer system).

**Choose Miniconda:**


- If you do not mind installing each of the packages you want to use individually.

- If you do not have time or disk space to install over 1,500 packages at once.

- If you want fast access to Python and the conda commands and you wish to sort out the other programs later.

    Once you have Miniconda, you can easily install Anaconda into it with this command
 `conda install anaconda` .

**Choose Anaconda:**


- If you are new to conda or Python.
- If you like the convenience of having Python and over 1,500 scientific packages automatically installed at once.
- If you have enough  disk space--- 4 GB RAM and above.
- If you do not want to individually install each of the packages you want to use.
- If you wish to use a set of packages structured and examined for interoperability and usability.

Whether you use Anaconda  or Miniconda, select the most recent version.

**Comment by dchidindu5** [comment]
k

**Comment by dchidindu5** [comment]
I created a pull request as regards to the documentation that should be added to the Ersilia Installation Guide #154

**Comment by GemmaTuron** [comment]
Hi @dchidindu5 great thanks for the clarification
We will consider adding it to our installation guide on Gitbook. Please continue with some new tasks !

**Comment by dchidindu5** [comment]
Thanks for giving me a feedback

**Comment by dchidindu5** [comment]
I created a slide explaining Ersilia's Mission and Vision Statements, Can you please review it? @GemmaTuron 
Here's the link below [](https://docs.google.com/presentation/d/1zrgZca6zhmk1Af7XlwnB3be1MATHHTrLswBbJane8Aw/edit?usp=sharing)

**Comment by dchidindu5** [comment]
@GemmaTuron I Created a pull request on a document I corrected in victor_windows.md #181

**Comment by GemmaTuron** [comment]
Hi @dchidindu5 

Thanks for going through the work of other applicants. Please make sure to mention to the creator of the file what did you find and why you corrected it, always abiding by our code of conduct!

As for the slides, I like how you elaborated on the mission and vision. Can I ask you to choose a background that follows Ersilia's color palette? Just some comments for your consideration on the mission text:

- accepted and reliable research atmosphere - research should always be acceptable, perhaps we can think in the direction of world-class, something that points out to scientific excellence
- unending solutions: Can you find another word for unending?.

**Comment by dchidindu5** [comment]
@GemmaTuron Thanks for bringing that to my notice. I'll stick to the plan

**Comment by dchidindu5** [comment]
@GemmaTuron I've done the correction you asked me to do
### Things I Implemented in the slide
- I changed the border colours to that of Ersilia's brand guideline by using the following colour palette - #bee6b4, #d2d2d0, #50285a, #aa96fa
- Then I replaced the words **"acceptable and reliable research atomosphere"** to **world-class research atmosphere**
- I also changed the term **"unending solutions**" to **"lasting solutions"**
Here is the link [Misson and Vision of Ersilia](https://docs.google.com/presentation/d/1zrgZca6zhmk1Af7XlwnB3be1MATHHTrLswBbJane8Aw/edit?usp=sharing)

**Comment by dchidindu5** [comment]
### **Initial Contributions**

- I created a README document for new users that specified guidelines to consider before choosing mini or anaconda for Ersilia model.  [Guidelines to consider before choosing mini or anaconda distribution](https://github.com/ersilia-os/ersilia/blob/master/documentation/Miniconda_OR_Anaconda_DennisOnyeka.md)  and it was merged on the 7th of April  #154 

- I also made a little correction I noticed in an applicants document and it was merged on the 8th of April #181

**Comment by dchidindu5** [comment]
I have created a sample blogpost document with respect to strategic Plans of Ersilia.
[Blog post for Ersilia strategic plans](https://docs.google.com/document/d/1nR9J-w4BQ2mxoj12aJ9nf3gGjJCatFCkXvUI_xQUoa0/edit?usp=sharing)
I'm open to corrections

**Comment by tracycod3r** [comment]
Hi @dchidindu5 i have noticed spelling mistakes in the slide that explains Ersilia's mission statement. I believe the words below in the parentheses would rectify the errors.

1. Ersilia aims at making this (these) tools readily available
2. The goal is to provide a world-class research atmosphere for researcher (researchers)

**Comment by dchidindu5** [comment]
Thank you for the correction

**Comment by GemmaTuron** [comment]
Hi @dchidindu5 

Thanks for making the requested changes in the mission and vision, reads much better now!
The Strategic Plan blogpost has your own style, and you have added some phrases I really like _ need radical solutions with innovative thought to break the current impasse in service delivery by setting up world class laboratories._ Thanks for putting effort into it.
I would like you to focus on the Miniconda or anaconda contribution since this was your idea and it will be good to incorporate to the installation guidelines. Can you add a bit more explanation on what exactly is miniconda and what is anaconda, and then in the list simply leve requirements for each system? for example:
_Both Anaconda and Miniconda are distributions (i.e ...) Miniconda is a distribution of conda that .... and Anaconda ...
Anaconda requirements:
- 4 GB RAM
- ...
Miniconda requirements:
- ...
_
Links to anaconda and miniconda webs would be helpful too

If there is any other task you are working on, add it here, but otherwise focus on finishing this contribution and make your final application
Please link this issue in the outreachy application

**Comment by dchidindu5** [comment]
Okay thanks 😊
I'll make the changes as soon as possible

**Comment by dchidindu5** [comment]
@GemmaTuron I've sucessfully made the changes to the document. Ive created a pull request #239

**Comment by dchidindu5** [comment]
I've also created a Twitter template for the release of new models  [Twitter template](https://docs.google.com/document/d/1FNPKxudcDUoFQQouUDye4G6JMHOVLCJGSbA0MyDhGy0/edit?usp=sharing)

**Comment by GemmaTuron** [comment]
Thanks @dchidindu5 for the twitter suggestion.
I have merged your PR, you should now focus in the final application!

**Comment by dchidindu5** [comment]
Thanks a lot, I really appreciate @GemmaTuron
