### ISSUE TITLE
✍️ Contribution period: Alphonse Brandon

### ISSUE THREAD

**Issue by AlphonseBrandon** [ersilia-os/ersilia#980]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by AlphonseBrandon** [comment]
# Motivational Letter for Outreachy 2024 Internship at Ersilia

Dear mentors,

I am Alphonse Brandon, alumni from the university of Buea, Cameroon through which Ersilia has partnership with the faculty of science. 

Ersilia's focus on strengthening the research capacity for infectious and neglected diseases by developing and implementing novel artificial intelligence and machine learning tools perfectly aligns with my aspirations, especially as the impact will be immediately felt in my locality in Cameroon which a pilot project is currently running.

My skills in machine learning (developing and deploying predictive models), data science and AI will be a great boast in contributing to helping Ersilia archieve her focus in helping researchers answer biomedical questions.

Ersilia's commitment to providing free and open source, low-code solution that provides seamless access to AI/ML models for drug discovery excites me and I am eager to learning from the talented team at Ersilia and community members.

Contributing to Ersilia model hub during this internship will significantly enhance my career trajectory by demonstrating a track record of my use of cutting edge AI/ML as used in Ersilia.

During the internship; I plan to collaborate closely with my mentor, actively participating in daily standups, code reviews and submitting reports of my work progress daily or weekly as my mentor choses, contributing to meaningfull code, documentation or other deliverables to enhance the project.

After the 3 months internship is over; I plan to continue contributing to Ersilia as an active community member and also explore opportunities for long-term collaboration with Ersilia.

I look forward to making an impact that matters by contributing to Ersilia's mission. Thank you for your time and consideration. I look forward to the possibility of making a positive impact together.

sincerely,
Alphonse Brandon.

**Comment by DhanshreeA** [comment]
Hi @AlphonseBrandon, I see that you have completed tasks from Week 2 but you have not shared with us a repository with your work here.

**Comment by AlphonseBrandon** [comment]
Thank you for pointing that out @DhanshreeA 

Please click [here to find the repository](https://github.com/AlphonseBrandon/machine-learning-for-chemistry/tree/master) of my work

Checkout the [focused notebook](https://github.com/AlphonseBrandon/machine-learning-for-chemistry/blob/master/notebooks/ra-score-prediction-model.ipynb) of the task

**Comment by DhanshreeA** [comment]
@AlphonseBrandon this is incomplete work. For starters, I don't see you using a model that is actually mentioned in the list. 

Since you are using Google Colab, which is okay but not advisable, I am assuming that you are using data directly from your Drive or local computer, but you have not provided that dataset here. You should provide the source, and the methodology behind how you obtained the data you are working with. See [instructions](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-summer-2024#week-2-get-familiar-with-machine-learning-for-chemistry)

**Comment by AlphonseBrandon** [comment]
Thank you for the feedback @DhanshreeA 

Let me redo it right away. I did all the previous work during week 1 (I think 1 day after getting accepted for outreach '24) and by then the instructions you provided in the link above weren't there.

The instructions I saw and worked with are presented below However, I am restarting the entire process now. 

Thank you for pointing me in the right direction.

**Screenshot of previous instruction I was working with**
![image](https://github.com/ersilia-os/ersilia/assets/57611883/a06e8a7a-5d0c-4cc4-8d06-5e627316e994)

**Screenshot of the updated instruction you just sent**
![image](https://github.com/ersilia-os/ersilia/assets/57611883/e58b4862-2469-4010-9099-5000b88b34b9)

**Comment by DhanshreeA** [comment]
@AlphonseBrandon apologies. We had announced in the Slack workspace and during the community call that we will be finalizing the models by the end of week 1. :) Let me review your work, and let us know if you need help anywhere.

**Comment by DhanshreeA** [comment]
@AlphonseBrandon I could not find any updates in your repository since last week. Have you picked out a model from the list? Let us know if you need help.

**Comment by GemmaTuron** [comment]
Hi @AlphonseBrandon 

We are almost at the end of week 3 of the Application period. If we do not hear back from you by next week we will close this issue to be able to provide better support to the applicants who wish to make a final application to Ersilia. Thanks for your understanding!
