### ISSUE TITLE
✍️ Contribution period: <Khadijah Kamorudeen> 

### ISSUE THREAD

**Issue by Khadijahhhh** [ersilia-os/ersilia#985]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [ ] Install Docker if needed, and test another model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by GemmaTuron** [comment]
Hi @Khadijahhhh 
We have not seen your application to Outreachy. To focus on active applicants, we have closed the project to new contributors.
I'll close this issue as well, thanks for your understanding
