### ISSUE TITLE
✍️ Contribution period: Ruth Ambogo

### ISSUE THREAD

**Issue by Ambogo2** [ersilia-os/ersilia#987]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Ambogo2** [comment]
I was exited when I got selected by Outreachy for the contribution phase and as I was scrolling through
the Project list, Ersilia caught my interest. The goal of Ersillia is so profound and transformative, and I would love to be part of that mission.
As a software engineer and a Data scientist, I am specifically drawn to solving problems that are impactful and 
transformative to the society. I am therefore writing to express my interest and motivation to work and contribute to the Ersilia community.
My ultimate career objective is to utilize my expertise in machine learning and Artificial intelligence to drive change, specifically in the healthcare sector.

Becoming part of Ersilia community will allow me to express my ideas and grow my expertise even more therefore
this is a great opportunity for me to make a contribution to Increase AI and ML models in the model hub for the biomedical research
In addition to my expertise, I am highly committed, organized and very disciplined. I thrive in an environment that fosters team work and collaboration, therefore my ability to handle projects and deliver results positions me as a valuable asset in any team.
Thank you and I look forward to work with Ersilia community.

Regards.
Ruth Ambogo

**Comment by DhanshreeA** [comment]
Hi @Ambogo2 I do not see any progress here since the last 2 weeks, since it will be hard to catch up with the other applicants at this point, let us know if you wish to continue. Otherwise, we will close this issue.
