### ISSUE TITLE
✍️ Contribution period: Mercy Bassey

### ISSUE THREAD

**Issue by mercybassey** [ersilia-os/ersilia#989]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by mercybassey** [comment]
I am a software developer and DevOps enthusiast with a deep passion for technology. I have experience in programming with bash, JavaScript, and Python, and I am also interested in Linux, automation, Infrastructure as Code, and cloud computing. I have always loved technology and programming; I grew up in a tech-savvy environment, knew how to operate a computer at a very early age because my father had one, and have always been in pursuit of enhancing my programming skills with books and various resources, whether free, paid, or sponsored.

Coming from a low socio-economic background, my journey through university was challenging, as I had to work part-time as a technical writer to see myself through school. I graduated with a second-class lower grade in Computer Science, and up until now, securing internship roles has proven to be difficult. This was attributed to both my low academic grades and lack of industry experience, which stems from the divided attention I had to give to both work and studies during my early university days. This situation was further compounded by the barriers facing women in the tech industry, especially in my country, for those of us with low grades and a lack of industry experience. This is not something I am proud of or happy about, as it has overshadowed my ability to contribute and gain visibility in being part of projects that matter.

In response to these challenges, I was drawn to the Outreachy internship program. I saw this opportunity as a moment to break through the barriers that have held me back. Through the Outreachy internship, I get to prove my passion and love for technology, an opportunity to be in a supportive environment, where I can prove myself and show how valuable I can be to any team. Through the internship, I get to demonstrate my capabilities in solving complex technical problems and showcase that I can communicate and collaborate with anyone, regardless of their background and race.

My ambition extends beyond refining my skills in programming and DevOps. One of the reasons I started to learn Python a few years back was that I plan to work in the artificial intelligence and machine learning space someday. I am particularly interested in the intersection of Artificial Intelligence and Machine Learning with various sectors, including healthcare, education, and beyond. The potential of Artificial Intelligence and Machine Learning to enhance our lives is immense, and I am eager to be a part of this transformative field. My goal is to specialize in Machine Learning Operations (MLOps), bridging my DevOps expertise with Artificial Intelligence and Machine Learning, to not only develop solutions but also ensure they are reliable and efficient in real-world applications; working at Ersilia is more than a single step towards achieving this goal.

Working with Ersilia presents a unique opportunity to showcase my learning capabilities by contributing to achieving Erisilia's goal of increasing the collection of available models.  During the internship, I am committed to fully engaging with the Ersilia Model Hub project, aiming to contribute to the availability and usability of AI and ML models for researchers worldwide. Additionally, working at Ersilia represents more than just an internship opportunity for me. It is a chance to advance my career and take significant steps toward realizing my dream of making a positive impact through technology. I am eager to bring my skills, passion, and determination to Ersilia, contributing to your efforts to make AI/ML technologies more accessible and impactful in the field of biomedical research.

**Comment by mercybassey** [comment]
Hi @DhanshreeA I'd like to submit my week2 task1 for review: https://github.com/mercybassey/AKS-Model-Validation. Thank you.

**Comment by DhanshreeA** [comment]
Hi @mercybassey good progress so far. From your results, can you reason about the model's bias? Could you also comment on the distribution of model predictions?

**Comment by DhanshreeA** [comment]
Hi @mercybassey thank you for letting us know. We hope to see you around the next time, and all the best for your endeavors.
