### ISSUE TITLE
✍️ Contribution period: Daisy Bochaberi

### ISSUE THREAD

**Issue by BochaberiDaisy** [ersilia-os/ersilia#994]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [x] Find a suitable dataset with sufficient experimental results
- [x] Clean and standardize the dataset
- [x] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [x] Submit the final application in the Outreachy website

**Comment by BochaberiDaisy** [comment]
**Motivational Letter**

I am Daisy Bochaberi, an aspiring data scientist from Nairobi, Kenya. I recently completed my undergraduate study at Jomo Kenyatta University of Agriculture and Technology, where I pursued a BSc in Telecommunication and Information Engineering. As a Telecommunications Engineer, my journey has been one of exploration, innovation, and a relentless pursuit of understanding complex systems. While my background allowed me to delve into the intricacies of networking systems and programming, I found myself drawn to a career at the intersection of data science and medicine, where my work would be a conduit for transforming healthcare outcomes. As such, Ersilia’s commitment to Artificial Intelligence for antimicrobial drug discovery is nothing short of inspiring.

I share Ersilia’s commitment to leveraging open science to support research in neglected diseases in low-income countries. During my studies, I developed an interest in socially impactful innovations and developed ClassifyMe, a course recommendation system for Kenyan high school students, with my team. As such, I learned the intricacies of conducting and documenting research and honed skills and competencies that would enable me to develop impactful projects. Working on ClassifyMe allowed me to develop my skills in research and machine learning techniques. I am currently adept in programming languages such as Python and SQL and in using a variety of tools and platforms including GitHub and Git. 

Joining Ersilia for the Outreachy internship presents an opportunity for me to contribute to impactful work by applying my technical skills in machine learning to enhance existing models that will benefit the community. I am excited about the opportunity to gain hands-on experience contributing to real-world projects and refine my technical and human skills through mentorship and guidance from experienced professionals.

My focus during the internship will be to actively engage with the community, deliver high-quality work, and seek opportunities for growth and learning. Beyond this internship, I plan to further develop my data science skills through open-source contribution. I see the Outreachy internship as a stepping stone towards achieving this long-term goal, providing me with the necessary experience and networks to make a meaningful impact in the tech industry.

**Comment by Malikbadmus** [comment]
Hi @BochaberiDaisy, can you post the log file of the error message you are getting?

**Comment by DhanshreeA** [comment]
@BochaberiDaisy let me debug this, meanwhile to progress in your work, you have two options:

1. Either work in Codespaces, or,
2. Fetch the model from github using the following command: `ersilia -v fetch eos6oli --from_github`

**Comment by BochaberiDaisy** [comment]
@DhanshreeA , thank you!
The fetch command solved the error

**Comment by BochaberiDaisy** [comment]
Hello @DhanshreeA 

I have completed my Week 2 Task 1. [Here](https://github.com/BochaberiDaisy/eos6oli/tree/main) is my repository containing the work for your review.
Your feedback will be appreciated.

**Comment by DhanshreeA** [comment]
Hi @BochaberiDaisy good work so far! Could you also update the repository with Week 2 Task 2 work?

**Comment by BochaberiDaisy** [comment]
Hi @DhanshreeA 
I have updated my repository to include my Week 2 Task 2 work. Here is the [notebook](https://github.com/BochaberiDaisy/eos6oli/blob/main/notebooks/01_model_reproducibility.ipynb) for the task.

**Comment by DhanshreeA** [comment]
@BochaberiDaisy looks good so far! Please move onto tasks from week 3. I will review again on Monday, then we will work on the final application!

**Comment by BochaberiDaisy** [comment]
@DhanshreeA , thank you so much. I have updated the comment above for better reference. 

Part of Week 2 task 2 required that we reproduce the same results using our model of choice from the Ersilia Model Hub. Is that a better way of checking for model reproducibility rather than reproducing figures and values from the publication?

**Comment by BochaberiDaisy** [comment]
# Week 3 
## Task: Validation in the wild
### Description of Tasks
1.  I researched an external dataset with aqueous solubility of molecules and the work is documented in this [notebook](https://github.com/BochaberiDaisy/eos6oli/blob/main/notebooks/03_external_validation.ipynb). I found a publication on [Evaluation of Deep Learning Architectures for Aqueous Solubility Prediction](https://pubs.acs.org/doi/full/10.1021/acsomega.2c00642) that had a curated dataset with experimental values in solubility and molar mass of molecules. I calculated the log solubility of the molecules with the two features.
2. I cleaned the dataset by standardizing the SMILES and InChiKey values of the molecules.
3. I checked for data leakage in the validation dataset against the SolTranNet training dataset. This step made it tasking to find a dataset since most of the datasets I found on public repositories such as PubChem and MoleculeNet were used in the training dataset.
4. I ran predictions on the eos6oli model and saved the predictions for analysis.
5. I calculated the performance metrics of the model such as Mean Absolute Error (MAE) and R2 score.

### Metrics
- The Mean Absolute Error depicted the deviation of the predicted solubility from the experimental solubility. The calculated value was **1.03**.
- The R2 score depicted the proportion of variance in the predicted solubility that can be explained by the experimental solubility. The calculated R2 score was **0.54**.

### Conclusion
- From the calculated metrics, I concluded that the model has room for improvement in learning the patterns in the data.


@DhanshreeA, please provide insights on the work done in week 3, especially on the calculated metrics. Is this what was depicted during the validation of the model?

**Comment by DhanshreeA** [comment]
> @DhanshreeA , thank you so much. I have updated the comment above for better reference.
> 
> Part of Week 2 task 2 required that we reproduce the same results using our model of choice from the Ersilia Model Hub. Is that a better way of checking for model reproducibility rather than reproducing figures and values from the publication?

Hi @BochaberiDaisy - the reproducibility exercise aims to do two things: 
1. Is the author's claim in the paper reproducible? We do this by reproducing values and plots from the paper. 

2. Did the right model get incorporated within the Ersilia Model Hub? That is, do we still get the same values and figures from the EMH implementation as we did by implementing the original model code? This second part is especially important because for a lot of models, their repositories can contain several model checkpoints in addition to the checkpoint of interest. This could happen because maybe the authors trained the same model on different sets of data to compare performance, or saved model checkpoints after x numbers of epochs, to name a few.

**Comment by DhanshreeA** [comment]
> # Week 3
> ## Task: Validation in the wild
> ### Description of Tasks
> 
>     1. I researched an external dataset with aqueous solubility of molecules and the work is documented in this [notebook](https://github.com/BochaberiDaisy/eos6oli/blob/main/notebooks/03_external_validation.ipynb). I found a publication on [Evaluation of Deep Learning Architectures for Aqueous Solubility Prediction](https://pubs.acs.org/doi/full/10.1021/acsomega.2c00642) that had a curated dataset with experimental values in solubility and molar mass of molecules. I calculated the log solubility of the molecules with the two features.
> 
>     2. I cleaned the dataset by standardizing the SMILES and InChiKey values of the molecules.
> 
>     3. I checked for data leakage in the validation dataset against the SolTranNet training dataset. This step made it tasking to find a dataset since most of the datasets I found on public repositories such as PubChem and MoleculeNet were used in the training dataset.
> 
>     4. I ran predictions on the eos6oli model and saved the predictions for analysis.
> 
>     5. I calculated the performance metrics of the model such as Mean Absolute Error (MAE) and R2 score.
> 
> 
> ### Metrics
> 
>     * The Mean Absolute Error depicted the deviation of the predicted solubility from the experimental solubility. The calculated value was **1.03**.
> 
>     * The R2 score depicted the proportion of variance in the predicted solubility that can be explained by the experimental solubility. The calculated R2 score was **0.54**.
> 
> 
> ### Conclusion
> 
>     * From the calculated metrics, I concluded that the model has room for improvement in learning the patterns in the data.
> 
> 
> @DhanshreeA, please provide insights on the work done in week 3, especially on the calculated metrics. Is this what was depicted during the validation of the model?

Exactly! Good work @BochaberiDaisy! You can start working on the final application. :)

**Comment by BochaberiDaisy** [comment]
@DhanshreeA, thank you for the valuable insights and the timely feedback
