### ISSUE TITLE
✍️ Contribution period: Siddhi Agarwal

### ISSUE THREAD

**Issue by agaSiddhi** [ersilia-os/ersilia#996]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by agaSiddhi** [comment]
I am Siddhi Agarwal. I come from India. I am currently in my 3rd year pursuing B.Tech in CSE.
I have always been passionate about coding ever since I first wrote the Java program in my class 6th. I believe that “skill” is the most expensive currency one can possess and I continue the process of upskilling myself. I love to explore differnet domains and have built projects in web-development using MERN stack, app-development, Machine learning, data science and Artificial Intelligence. I have built projects using LLM, OpenAI API too. I am proficient in python and have solid understanding of python libraries like numpy, pandas, scipy, scikit-learn. 

In the vast and unending journey of gaining knowledge, one thing that has always remained constant is the urge to build projects that can positively impact the society.This drive is evident in all the projects I've undertaken so far. The fact that few lines of code have power to transform lives has always fascinated me and continue to do so.

Hence when I stumbled upon Ersilia on the project page, it resonated with the motivation that keeps me going. Ersilia’s goals is rooted in compassion, that longs to create a world where healthcare is available to all regardless anything. Ersilia aspires to extend technological advancements in field of AI/MLtools for infectious and neglected disease research beyond boundaries, where anyone can contribute and also leverage the knowledge. 

I want to work at Ersilia, because primarily it aligns with my vision. I am confident in my existing skills and believe I can further develop the ones necessary to contribute to their codebase.Additionally, I'm drawn to Ersilia's supportive community, filled with skilled individuals who can help me expand my capabilities.  I plan to actively contribute to Ersilia during and later the internship period, because its only a win-win situation.

**Comment by agaSiddhi** [comment]
@DhanshreeA I am doing the task 1 of second week. I have created the repository and uploaded the notebook. I am still working and drawing inferences. I request you to review the [GitHub Repository](https://github.com/agaSiddhi/model-verification-eos30gr) and suggest any changes that I need to incorporate. Thanks!
I will update the Readme file soon.

**Comment by Adhivp** [comment]
Hey @agaSiddhi  I noticed you have been working in Task2 , If you need any help feel free to contact in slack(Adhithyan vp)

**Comment by DhanshreeA** [comment]
Hi @agaSiddhi great work so far! Good job on deep diving into molecule properties and correlating them to the predicted outcomes, and I like that you have articulated your thought process within the notebook. However, I want to comment on your use of scatterplots, which I had pointed out over Slack some time ago. Scatter plots are used for comparing numerical datasets, while an inchikey/or a smile index vs the model outcome is not a good case for using scatter plots.

**Comment by agaSiddhi** [comment]
Thank you, @DhanshreeA, for the feedback and for highlighting the limitations of using scatter plots in our analysis. I will remove the scatter plot in the next commit. 
Moreover, I am working on Task 2 of the second week and will soon push the notebook.

**Comment by DhanshreeA** [comment]
@agaSiddhi Any updates to share? I will be reviewing the final updates on Monday. Then we work on the final application.

**Comment by agaSiddhi** [comment]
Thanks for the update. I'm currently focusing on completing the second task for week 2 and will ensure it's ready for review before Monday.
Appreciate your support @DhanshreeA

**Comment by agaSiddhi** [comment]
@DhanshreeA, I have uploaded the notebook for Week 2 Task 2 - Model Reproducibility. Please take a look and provide feedback. Thank you for your time.

[Link to task2 notebook](https://github.com/agaSiddhi/model-verification-eos30gr/blob/main/notebooks/Ersilia_Model_eos30gr_Reproducibility.ipynb)
[Link to repository](https://github.com/agaSiddhi/model-verification-eos30gr)

Additionally, what should I work on next?

**Comment by DhanshreeA** [comment]
@agaSiddhi good work! We have been getting the same results from a lot of people re model eos30gr. This is helpful for us to go and review that model. 

Regarding next steps, I would advise not starting on Task 3. Instead, please work on submitting your final application as that's a lot more important.
