### ISSUE TITLE
✍️ Contribution period: <Ekwoge Blaise> 

### ISSUE THREAD

**Issue by ekBlaise** [ersilia-os/ersilia#998]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by ekBlaise** [comment]
### Why Join Outreachy and why specifically Ersilia

My name is Ekwoge Blaise and I am a Junior Data Scientist from Buea, Cameroon. Being young in the data world, getting hands-on experience to get my hands dirty is one thing I've been keen on given my limited resources. And though being trained and certified by DataCamp, I knew getting a chance on working on life project is something which is dire to my growth as a Data Scientist. I saw Outreachy to be the perfect place to get started, given it's vast collection of projects, some of which are exactly what I need to horn my skills. Aside that, I saw Outreachy as the spring boot to carry me forward given that it provides opportunities which can be done even by those in a marginalized area like mine, granting me an opening to projects being used in the real world.

Why Ersilia? I would say it's exactly the kind of project I have been longing for; one that makes use of the skills I'm currently hoping to develop and while not, some more. Skills in Python, Data Science where I believe it will help me deepen my understanding of libraries and packages such as scikit-learn, seaborn, pandas, numpy, and to use ML techniques, data visualize with seaborn, matplotlib and more. Maybe some deep learning models too, natural language processing and LLMs if it came to it.

I also discovered that Erisilia is setting up an AI/ML platform for the identification of novel antivirals from African at the University of Buea, the same university where I've done my Bachelors in Software Engineering and soon a master in the same field at the same University. Given all I've gathered being trained in this university, seeing something like this gives me double motivation to work more so I can contribute to this wonderful project.

I believe I'll be able to learn invaluable skills during the internship and master young ones. Being new in Data Science, I believe there is so much I can get only by working on such projects. During the internship, I would do everything to learn from those more experience and from the mentors and to chip in the small I have so that the team and project can progress. After the internship, if granted the means, I would love to keep contributing to the project but even more, to get a chance to work on similar projects as a volunteer at the end of this, up to the point where my skills can land me to a good role in the data world.

**Comment by GemmaTuron** [comment]
Hi @ekBlaise 

We are on week 3 of the contribution period. Please let us know if you plan to continue with your contribution by the next 2 days, otherwise we will close this issue so we can focus on the applicants who want to make a final application to Ersilia.

**Comment by GemmaTuron** [comment]
Hi @ekBlaise 

We will close this issue so mentors can focus on those applicants who wish to make a final application to Ersilia. thanks for your understanding and let us know if you were still planning on applying.
